### ISSUE TITLE
Add validators to Edit User form fields

### ISSUE THREAD

**Issue by cippall** [dpgaspar/Flask-AppBuilder#1008]
Hi,

How do i add custom validators for  Edit User Details form. At the moment all fields get validated as long as they are not empty.

### Environment

Flask-Appbuilder version: All

### Steps to reproduce
Go To Security > List  Users> Edit Record > Replace Email or User field data with space and press Save.

Thanks!

**Comment by dpgaspar** [comment]
Hi,

You can create your own custom security manager. https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

You can just override the userdbmodelview (if AUTH_DB) when implementing your own security manager.

**Comment by cippall** [comment]
Thanks, i'm doing that already in my example. But i can't find the actual form used to edit the user details. Any hint ? How can add the correct validators  for each field ?

**Comment by cippall** [comment]
Ok, found the **edit_form_extra_fields**  feature and that provides access to form field validators. 

By overriding Email  validators i lost the default Already exists default  validation . How do i manually added it back?

**Comment by cippall** [comment]
Is there to  append to existing column validators **DataRequired(), Email()** rather than replacing it, as i did in my example?

**Comment by cippall** [comment]
Working on **extendsecurity2** example, i'm overwriting the email field validators in the **sec_views.py**. 

```
  edit_form_extra_fields = {
        "email": StringField(
            lazy_gettext("Email"),
            description=lazy_gettext(
                "Email"
            ),
            validators=[DataRequired(), Email()],
            widget=BS3TextFieldWidget(),
        ),
    }
```

In order to use the existing Unique validator i need to have access to appbuilder and user database.  That creates a circular import error. 

```
from flask_appbuilder.validators import Unique
from . import appbuilder, db
```

ERROR:

`Was unable to import app Error: cannot import name 'appbuilder' from 'app'`

I've tried moving MyUserDBModelView to the main view.py and importing it from there in security.py. Same circular import error. 

What would be the best approach in this case?

Thanks!

**Comment by soundmaking** [comment]
Hello, 

not an expert here, but looking at your final Error described, I ended up with this structure to get similar things happening:

```
/project 
    /app
        /__init__.py
        /models.py
        /sec_models.py
        /sec_views.py
        /sec.py
        /views.py
```

Any models I need the security manager to use are defined in `sec_models.py` and imported from there in `sec.py` : eg:

```python
from .sec_models import User, MyUser, EmailAddressRecord, EmailMessage
```

Then inside the custom SecurityManager class, to access the database, you can use the inherited `get_session` - eg:
```python
class MySecurityManager(SecurityManager):
    # ...
    def find_email_address_record(self, email_address):
        '''return EmailAddressRecord for given email_address if found
        
        Arguments:
            email_address {str} -- address to look up
        
        Returns:
            EmailAddressRecord -- or False
        '''

        if not email_address:
            # FIXME other validation on input email address?
            return False
        email_address = email_address.lower().strip()
        email_addr_rec = self.get_session.query(
            EmailAddressRecord
        ).filter_by(
            email=email_address
        ).first()
        if not email_addr_rec:
            return False
        return email_addr_rec
```

You can also call `self.appbuilder` in you SecurityManager class: eg:

```python
        mail = Mail(self.appbuilder.get_app)
```

Finally, in `views.py` to I things like this to call functions that are in my security manager:

```python
                            contact.email_addr = [
                                appbuilder.sm.get_email_address_record(
                                    request.form['cd_email']
                                )
                            ]
```


I'm sure this could all be a lot more beautiful, but it works (any tips on a better way are welcome!)
