### ISSUE TITLE
How to reuse users/list

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#101]
How to reuse users/list:

http://0.0.0.0:8080/users/list/

But instead I would like to populate it with my custom logic and SQLite database

**Comment by dpgaspar** [comment]
Could you detail a bit more?

**Comment by scheung38** [comment]
Where are the template directories? Seem like it is embedded into the Flask-AppBuilder than within the newly created app itself?

**Comment by scheung38** [comment]
For example, the Welcome html page is embedded in the Flask-AppBuilder package? so any changes are going to be outside of my new app?

**Comment by dpgaspar** [comment]
Nop, you can override everything (or almost), Read the chapter on how to use your own index from doc's

http://flask-appbuilder.readthedocs.org/en/latest/customizing.html#changing-the-index

Read the templates chapter:

http://flask-appbuilder.readthedocs.org/en/latest/templates.html

Take a look at the example, It's overriding the index (and other config):

https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickhowto2

**Comment by dpgaspar** [comment]
was this helpful?

**Comment by scheung38** [comment]
Thanks a lot will read through them
