### ISSUE TITLE
Not able to add new custom button like save. Is any customisation possible for Adding new button? 

### ISSUE THREAD

**Issue by pulkit69** [dpgaspar/Flask-AppBuilder#1015]
```
{% macro render_form_controls() %}
    <div class="well well-sm">
        <button type="submit" class="btn  btn-sm btn-primary">{{_("Save")}}
            <i class="fa fa-save"></i></button>
        {{ lnk_back() }}
    </div>
{% endmacro %}
```
any customisation for save button or if we want to add a new button?

**Comment by MarcusSorealheis** [comment]
Need more details. Where would you like to add the save button? Where does it live?  Which aspect of the code is not working?

Is it not rendered? How are you starting your app?

**Comment by MarcusSorealheis** [comment]
Need more details. Where would you like to add the save button? Where does it live? Which aspect of the code is not working?

Is it not rendered? How are you starting your app @pulkit69 ?

**Comment by pulkit69** [comment]
I am building a functionality where before saving add connection form using flask-appbuilder i need to test provided connection string is valid or not using a `Test Connection` button.
