### ISSUE TITLE
Passing extra_args also to widgets

### ISSUE THREAD

**Issue by noxqs** [dpgaspar/Flask-AppBuilder#1017]
Why not expose the extra_args to widgets also, this way you could implement a footer for a table with ease for example.

I could add this in RenderTemplateWidget but for now I override the `__call__` method in my custom widget like this:
```
    def __call__(self, **kwargs):
        ctx = _request_ctx_stack.top
        jinja_env = ctx.app.jinja_env

        template = jinja_env.get_template(self.template)
        args = self.template_args.copy()
        args.update(kwargs)
        if hasattr(self,'extra_args'):
            args.update(self.extra_args)
        return template.render(args)
```
which allows me to to use in my custom ListWithFooter widget `{{ extra_args['table_footer'] }}`
which is used and defined in my view:    
```add_widget = ListWithFooter
extra_args = {'table_footer': 'Additional HTML text to guide user for this add template'}
```

Does this sound logical or am I re-inventing a wheel I haven't seen ?

**Comment by dpgaspar** [comment]
Looks good, but if I'm not mistaken you would add `extra_args` has an attribute on ListWithFooter
