### ISSUE TITLE
Proposal for SAML Authentication Support to FAB

### ISSUE THREAD

**Issue by hsm2** [dpgaspar/Flask-AppBuilder#1028]
### Motivation

To enable a more secure way of authentication as an option. It is also the primary way of authentication at Affirm and many other companies. It also seems to be requested by others in the community -

[Need help with saml 2.0 integration](https://github.com/apache/incubator-superset/issues/5123)
[Add SAML support](https://github.com/dpgaspar/Flask-AppBuilder/issues/449)

@mistercrunch - requesting suggestions and comments, thanks!

### Proposed Change

When creating an app using FAB, users get an option to choose from 5 existing ways of authentication like _AUTH_DB_, _AUTH_OAUTH_ and more. To provide SAML as an option to users, _AUTH_SAML_ will be added to this list. In the config.py file, users can select _AUTH_SAML_ as their authentication method and would have to list the SAML Identity Providers they'd like to support. 

When they run the app, users will be directed to the chosen SAML Identity provider to login.

### New or Changed Public Interfaces

- _AUTH_SAML_ will be added to the list of constants in const.py.
- _login_saml.html_ will be added to templates/.../security
- _AuthSAMLView_ will be added to security/views.py
- _UserSAMLModelView_ will be added to security/views.py

Other views and models will be added as per the need. These changes will enable flow of authentication using SAML, from sign on request to retrieving user info, just as is done for other authentication methods.

### New dependencies

python3-saml is required and has the MIT License

### Rejected Alternatives

Rejected using library flask-saml2 because it is not maintained as frequently as python3-saml. python3-saml is backed by onelogin and has good documentation and support.

**Comment by sumous** [comment]
I am working on it for support SAML2 in CAS.  #968 
It will be release in FAB 2.2

**Comment by hsm2** [comment]
@sumous okay, do you know what the timeline for supporting SAML2 is? I looked at python-cas and it seems that it only supports SAML 1.0, are there plans to support SAML 2.0? More than happy to help, thanks!

**Comment by dpgaspar** [comment]
.

**Comment by elukey** [comment]
@dpgaspar Hi! Sorry to ask a redundant question but what is the status of this task? I am really interested in this so I can help if needed, at Wikimedia we are starting to use CAS and I'd love to bridge the gap between it and Presto+Kerberos (working on it in https://github.com/apache/incubator-superset/issues/8794).

**Comment by elukey** [comment]
gentle ping :)

**Comment by 628567** [comment]
bump for Apache Airflow FAB SAML support.

**Comment by green2k** [comment]
Any update on this, guys?
