### ISSUE TITLE
How to create new role other than the default Admin and Public?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#103]
In a newly created app, tried adding new role in config.py:

AUTH_ROLE_PUBLIC = 'Public'

# added
AUTH_ROLE_MODERATOR = 'Moderator'

But not showing in app?

**Comment by dpgaspar** [comment]
On the config just use the config keys from docs, or from the used packages like flask-sqlalchemy, flask-wtfroms etc...

You add a new roles using the UI, like a normal admin user.
