### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lohithn4** [dpgaspar/Flask-AppBuilder#1030]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: Flask-AppBuilder-2.1.4

pip freeze output:
actions==1.0.3
apispec==1.3.3
attrs==19.1.0
Babel==2.7.0
blinker==1.4
bunch==1.0.1
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.0.3
Flask-AppBuilder==2.1.4
Flask-Babel==0.12.2
Flask-HTTPAuth==3.3.0
Flask-JWT-Extended==3.18.2
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
jsontools==0.1
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.3
numpy==1.16.4
opencv-contrib-python==3.4.4.19
pdfkit==0.6.1
prison==0.1.1
PyJWT==1.7.1
pyrsistent==0.15.2
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1.1
requests==2.22.0
six==1.12.0
SQLAlchemy==1.3.4
SQLAlchemy-Utils==0.34.0
urllib3==1.25.3
urltools==0.3.2
Werkzeug==0.15.4
WTForms==2.2.1

when i run my  python run.py file
it fails to run the app

it used to run properly but now it fails

```pytb
Paste the full traceback if there was an exception.
```
$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app,db
  File "/home/pi/esrbatch/app/__init__.py", line 4, in <module>
    from flask_appbuilder import AppBuilder, SQLA
  File "/home/pi/esrbatch/venv/lib/python3.5/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/home/pi/esrbatch/venv/lib/python3.5/site-packages/flask_appbuilder/api/__init__.py", line 440
    f"Registering route {self.blueprint.url_prefix}{url} {methods}"

**Comment by dpgaspar** [comment]
Hi @lohithn4,

python 3.5 is not supported, please upgrade to > 3.6.
