### ISSUE TITLE
Check the LDAP group when users log in

### ISSUE THREAD

**Issue by TempleZhou** [dpgaspar/Flask-AppBuilder#1032]
### Environment

Flask-Appbuilder version: v2.1.4

Now, my LDAP has too much people but I do not hope all of them can log in the Web APP.

So, is there any solution to detect if the the user who wants to log in contained by specified group(appears in the group's attribute -- member).

**Comment by TempleZhou** [comment]
Can I create a PR for this issue ?

**Comment by TempleZhou** [comment]
@villebro This issue is different to yours #956 , right?

**Comment by villebro** [comment]
Yes, this is different. @TempleZhou check `AUTH_LDAP_SEARCH_FILTER` on https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/config.rst

**Comment by TempleZhou** [comment]
But, I don't think everyone enabled the memberOf feature for LDAP. 

As for me, our LDAP entry doesn't have this feature, and it's difficult to persuade ADMIN to enable it.

For universality, the AUTH_LDAP_GROUP_SEARCH_BASE and AUTH_LDAP_GROUP_SEARCH_FILTER should be added.

For my instance, I only need to set the AUTH_LDAP_GROUP_SEARCH_FILTER to "(member=%)", which can detect the user group.
