### ISSUE TITLE
In quickhowto, how to change background color

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#104]
Say if one of the element field when from "normal" to "alert" then change background to red for that single element

**Comment by dpgaspar** [comment]
You can use your own CSS and JS, and do what ever you want with it.

Import your own CSS and JS like this: 

http://flask-appbuilder.readthedocs.org/en/latest/templates.html#css-and-javascript

For doing what you want, is not trivial, you should also take a look at own the render field are done:

http://flask-appbuilder.readthedocs.org/en/latest/templates.html#css-and-javascript

And own the forms are built:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/widgets/form.html

You can always override, with your own.

Hope this helps.

**Comment by scheung38** [comment]
Basically if any of a cell row has a certain string text say 
OK then it is green
Failed red 

to give quick visualization
