### ISSUE TITLE
JWT Refresh Specs Missing Args

### ISSUE THREAD

**Issue by deckar01** [dpgaspar/Flask-AppBuilder#1047]
### Environment

Flask-Appbuilder version: 2.1.5

pip freeze output: N/A

### Describe the expected results

The security API for refreshing a JWT token should advertise the ways it can accept a refresh token.

### Describe the actual results

There is currently no way for the generated swagger page to submit a valid refresh request, because it does not define any arguments in its specs.

<img width="300" alt="Screen Shot 2019-06-28 at 9 57 21 AM" src="https://user-images.githubusercontent.com/3108007/60351465-74c3be80-998b-11e9-9708-ffc8362f28ca.png">
<img width="300" alt="Screen Shot 2019-06-28 at 9 57 57 AM" src="https://user-images.githubusercontent.com/3108007/60351464-74c3be80-998b-11e9-8788-ef699f2665bc.png">

### Steps to reproduce

1. Open the swagger API page
2. Submit a valid request to the security login endpoint
3. Add the access token in the swagger jwt auth form
4. Submit a request to the security refresh endpoint

### Notes

There don't seem to be any docs on how `@jwt_refresh_token_required` reads the refresh token. [flask-jwt-extended `_decode_jwt_from_request()`](https://github.com/vimalloc/flask-jwt-extended/blob/67de379bc2184fa042aa4202034f3572fb750293/flask_jwt_extended/view_decorators.py#L250-L257) is the underlying implementation. Advertising the request arg would get swagger working, but it would be good to declare as many of the accepted formats in the spec as possible.

After looking at the implementation of `_decode_jwt_from_request()`, the first place it looks for a token is the cookie. Automatically storing the tokens in the cookie would make authorizing requests (and refresh requests) much more convenient for API clients.

**Comment by deckar01** [comment]
The fix for this should only require declaring the refresh token options in the refresh route's spec docstring. I am interested in opening a PR for this if this solution sounds acceptable.

**Comment by dpgaspar** [comment]
Awesome! please do

**Comment by deckar01** [comment]
By default only the "headers" options is allowed for tokens, so there is only one token format to document. The spec needs to declare a second security schema for refresh tokens and reference that in the refresh operation's spec docstring. That should include a second input for the refresh token in the auth popup on the swagger page and include it automatically when the refresh operation is executed.
