### ISSUE TITLE
Performance issue: Table scan before creation of related object

### ISSUE THREAD

**Issue by nachtkinder** [dpgaspar/Flask-AppBuilder#1049]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.1.5

pip freeze output:

```
apispec==2.0.1
attrs==19.1.0
Babel==2.7.0
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.0.3
Flask-AppBuilder==2.1.5
Flask-Babel==0.12.2
Flask-JWT-Extended==3.19.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.17.0
prison==0.1.2
PyJWT==1.7.1
PyMySQL==0.9.3
pyrsistent==0.15.2
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1.1
six==1.12.0
SQLAlchemy==1.3.5
SQLAlchemy-Utils==0.34.0
Werkzeug==0.15.4
WTForms==2.2.1
```

### Describe the expected results

With reference to objects and tables in the example code posted below:

I expect that adding a new OtherThing object to a Thing object via the Thing object's "List Other Thing" tab does not cause a full table scan of the _thing_ table in the underlying database.

### Example app

```python
import logging

from flask import Flask, render_template
from flask_appbuilder import AppBuilder, SQLA, ModelView, ModelRestApi, Model
from flask_appbuilder.models.sqla.interface import SQLAInterface
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship

config = {
        'SQLALCHEMY_DATABASE_URI': ('mysql+pymysql://USER:PASSWORD@'
                                    'HOST:PORT/SCHEMA?charset=utf8'),
    'CSRF_ENABLED': True,
    'SECRET_KEY': '\2\1thisismyscretkey\1\2\e\y\y\h',
    'APP_NAME': 'Issue #1049'
}

"""
 Logging configuration
"""

logging.basicConfig(format="%(asctime)s:%(levelname)s:%(name)s:%(message)s")
logging.getLogger().setLevel(logging.DEBUG)

app = Flask(config['APP_NAME'])
app.config.update(config)
db = SQLA(app)
appbuilder = AppBuilder(app, db.session)


class Thing(Model):
    __tablename__ = 'thing'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)

    def __repr__(self):
        return self.name


class OtherThing(Model):
    __tablename__ = 'other_thing'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)
    thing_id = Column(Integer, ForeignKey('thing.id'))

    related_things = relationship('Thing', backref='related_other_things')

    def __repr__(self):
        return self.name


class OtherThingView(ModelView):
    datamodel = SQLAInterface(OtherThing)
    list_columns = ['name', 'related_things']


class ThingView(ModelView):
    datamodel = SQLAInterface(Thing)
    list_columns = ['name', 'related_other_things']
    related_views = [OtherThingView]

db.create_all()

appbuilder.add_view(
        OtherThingView,
        'OtherThingView',
        icon='fa-folder-open-o'
        )

appbuilder.add_view(
    ThingView,
    'ThingView',
    icon='fa-folder-open-o')

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080, debug=True)

```

### Describe the actual results

Upon adding a new OtherThing object to a Thing object via the Thing object's "List Other Thing" tab, a select statement is issued immediately before the insert statement that creates the new OtherThing instance.  This select statement queries every field of each Thing object.  This results in a full table scan of the _thing_ table in the underlying database.  This creates a serious performance issue if there are many Things defined.  In the real world example I discovered this in the select took 16+ minutes!

I do not understand why the Flask Appbuilder code queries all the Thing objects when adding an associated OtherThing to a single Thing object.  If it is refreshing some internal cache can this be done in the background after adding the association?

```pytb
Paste the full traceback if there was an exception.
```

### Steps to reproduce

1. Create a new MySQL schema to use for the example app.
2. Grant permissions for a user to the new schema.
3. configure your MySQL server to log general queries.
4. Create a new Python 3 virtual environment (using venv or pipenv).
5. Activate the new virtual environment.
6. Install the requirements listed in the above pip freeze output.
7. Copy the example code into a new file (app.py).
8. Amend the SQLALCHEMY_DATABASE_URI with the details of the new MySQL schema created in step 1 and the user granted permission in step 2.
9. Create an admin user with `flask fab create-admin`.
10. Run the app with `python3 app.py`.
11. Begin to monitor the MySQL general log ( on Linux simply `tail -f /path/to/mysql/general.log` as root or prefixed with `sudo `).
12. Open the app in a browser window.
13. Log in with the admin user created in step 9.
14. Navigate to 'ThingView' from the main navigation.
15. Click the "+" button to create a new Thing.
16. Fill in the required Name field, leaving the "Related Other Things" field empy.
17. Click the "Save" button.
18. Edit/view the Thing object using the controls in the table.
19. Click through to the "List Other Thing" tab.
20. Click the "+" to add a related "Other Thing".
21. Fill in the required name field.
22. Click the "Save" button.
23. Observe that in the MySQL log, immediately before the insert statement for the new OtherThing, there is a select statement for all columns of the _thing_ table that has no where clause.

Regards,
Nachtkinder

**Comment by dpgaspar** [comment]
Using the example `quickhowto` this is the output of SQLALchemy echo (removed all the security permissions related queries)

```
2019-07-10 17:10:38,518 INFO sqlalchemy.engine.base.Engine INSERT INTO contact (name, address, birthday, personal_phone, personal_celphone, contact_group_id, gender_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2019-07-10 17:10:38,531:INFO:werkzeug:127.0.0.1 - - [10/Jul/2019 17:10:38] "POST /contactmodelview/add?_flt_0_contact_group=1 HTTP/1.1" 302 -
2019-07-10 17:10:38,544 INFO sqlalchemy.engine.base.Engine SELECT contact_group.id AS contact_group_id, contact_group.name AS contact_group_name 
FROM contact_group 
WHERE contact_group.id = ?
 LIMIT ? OFFSET ?
2019-07-10 17:10:38,544:INFO:sqlalchemy.engine.base.Engine:SELECT contact_group.id AS contact_group_id, contact_group.name AS contact_group_name 
FROM contact_group 
WHERE contact_group.id = ?
 LIMIT ? OFFSET ?
2019-07-10 17:10:38,547 INFO sqlalchemy.engine.base.Engine SELECT count(?) AS count_1 
FROM contact 
WHERE ? = contact.contact_group_id
2019-07-10 17:10:38,550 INFO sqlalchemy.engine.base.Engine SELECT contact.id AS contact_id, contact.name AS contact_name, contact.address AS contact_address, contact.birthday AS contact_birthday, contact.personal_phone AS contact_personal_phone, contact.personal_celphone AS contact_personal_celphone, contact.contact_group_id AS contact_contact_group_id, contact.gender_id AS contact_gender_id 
FROM contact 
WHERE ? = contact.contact_group_id ORDER BY contact.name ASC
 LIMIT ? OFFSET ?
2019-07-10 17:10:38,617 INFO sqlalchemy.engine.base.Engine SELECT contact_group.id AS contact_group_id, contact_group.name AS contact_group_name 
FROM contact_group 
WHERE contact_group.id = ?
2019-07-10 17:10:38,633:INFO:werkzeug:127.0.0.1 - - [10/Jul/2019 17:10:38] "GET /groupmodelview/show/1 HTTP/1.1" 200 -
```

**Comment by nachtkinder** [comment]
Hi @dpgaspar ,

Thanks for getting back to me on this as this is the most pressing issue I now face with developing my app on Flask-AppBuilder.

I created a new `pipenv` environemnt and installed only flask-appbuilder and mysqlclient.  I then modified app.py to not use pymysql and to add SQLAlchemy's echo flag.  When adding a new _OtherThing_ with related _Thing_ 

> 2019-07-12 15:21:04,479 INFO sqlalchemy.engine.base.Engine ('OtherThingView', 'can_add', 1)
> 2019-07-12 15:21:04,479:INFO:sqlalchemy.engine.base.Engine:('OtherThingView', 'can_add', 1)
> 2019-07-12 15:21:04,480 INFO sqlalchemy.engine.base.Engine SELECT count(%s) AS count_1 FROM thing
> 2019-07-12 15:21:04,480:INFO:sqlalchemy.engine.base.Engine:SELECT count(%s) AS count_1 FROM thing
> 2019-07-12 15:21:04,480 INFO sqlalchemy.engine.base.Engine ('*',)
> 2019-07-12 15:21:04,480:INFO:sqlalchemy.engine.base.Engine:('*',)
> **2019-07-12 15:21:04,481 INFO sqlalchemy.engine.base.Engine SELECT thing.id AS thing_id, thing.name AS thing_name FROM thing**
> 2019-07-12 15:21:04,481:INFO:sqlalchemy.engine.base.Engine:SELECT thing.id AS thing_id, thing.name AS thing_name
> FROM thing
> 2019-07-12 15:21:04,481 INFO sqlalchemy.engine.base.Engine ()
> 2019-07-12 15:21:04,481:INFO:sqlalchemy.engine.base.Engine:()
> 2019-07-12 15:21:04,483 INFO sqlalchemy.engine.base.Engine INSERT INTO other_thing (name, thing_id) VALUES (%s, %s)
> 2019-07-12 15:21:04,483:INFO:sqlalchemy.engine.base.Engine:INSERT INTO other_thing (name, thing_id) VALUES (%s, %s)
> 2019-07-12 15:21:04,483 INFO sqlalchemy.engine.base.Engine ('Thing Three', 1)
> 2019-07-12 15:21:04,483:INFO:sqlalchemy.engine.base.Engine:('Thing Three', 1)
> 2019-07-12 15:21:04,483 INFO sqlalchemy.engine.base.Engine COMMIT
> 2019-07-12 15:21:04,483:INFO:sqlalchemy.engine.base.Engine:COMMIT

The bolded entry shows the query of _Thing_ that results in the table scan.

Please take a look at [app.py.txt](https://github.com/dpgaspar/Flask-AppBuilder/files/3391330/app.py.txt) to check that I have not done anything stupid.

Regards,
Nachtkinder

**Comment by nachtkinder** [comment]
Hi @dpgaspar ,

The backref was a bit of a Red Herring I'm afraid.

It appears that the table scan occurs on each table that represents a model that is related to the model being currently edited/created.  I've observed this with the quickhowto example also.  The SQLAlchemy echo extract you posted begins with the INSERT statement while the lines that show queries that result in table scans (below in bold) occur _before_ the INSERT (below in bold italics):

> 2019-07-22 14:07:05,034 INFO sqlalchemy.engine.base.Engine ('Jane Doe',)
> 2019-07-22 14:07:05,034:INFO:sqlalchemy.engine.base.Engine:('Jane Doe',)
> 2019-07-22 14:07:05,038 INFO sqlalchemy.engine.base.Engine SELECT count(?) AS count_1 FROM gender
> 2019-07-22 14:07:05,038:INFO:sqlalchemy.engine.base.Engine:SELECT count(?) AS count_1 FROM gender
> 2019-07-22 14:07:05,039 INFO sqlalchemy.engine.base.Engine ('*',)
> 2019-07-22 14:07:05,039:INFO:sqlalchemy.engine.base.Engine:('*',)
> **2019-07-22 14:07:05,042 INFO sqlalchemy.engine.base.Engine SELECT gender.id AS gender_id, gender.name AS gender_name FROM gender**
> 2019-07-22 14:07:05,042:INFO:sqlalchemy.engine.base.Engine:SELECT gender.id AS gender_id, gender.name AS gender_name FROM gender
> 2019-07-22 14:07:05,042 INFO sqlalchemy.engine.base.Engine ()
> 2019-07-22 14:07:05,042:INFO:sqlalchemy.engine.base.Engine:()
> 2019-07-22 14:07:05,046 INFO sqlalchemy.engine.base.Engine SELECT count(?) AS count_1 FROM contact_group
> 2019-07-22 14:07:05,046:INFO:sqlalchemy.engine.base.Engine:SELECT count(?) AS count_1 FROM contact_group
> 2019-07-22 14:07:05,046 INFO sqlalchemy.engine.base.Engine ('*',)
> 2019-07-22 14:07:05,046:INFO:sqlalchemy.engine.base.Engine:('*',)
> **2019-07-22 14:07:05,050 INFO sqlalchemy.engine.base.Engine SELECT contact_group.id AS contact_group_id, contact_group.name AS contact_group_name FROM contact_group**
> 2019-07-22 14:07:05,050:INFO:sqlalchemy.engine.base.Engine:SELECT contact_group.id AS contact_group_id, contact_group.name AS contact_group_name FROM contact_group
> 2019-07-22 14:07:05,050 INFO sqlalchemy.engine.base.Engine ()
> 2019-07-22 14:07:05,050:INFO:sqlalchemy.engine.base.Engine:()
> **_2019-07-22 14:07:05,053 INFO sqlalchemy.engine.base.Engine INSERT INTO contact (name, address, birthday, personal_phone, personal_celphone, contact_group_id, gender_id) VALUES (?, ?, ?, ?, ?, ?, ?)_**
> 2019-07-22 14:07:05,053:INFO:sqlalchemy.engine.base.Engine:INSERT INTO contact (name, address, birthday, personal_phone, personal_celphone, contact_group_id, gender_id) VALUES (?, ?, ?, ?, ?, ?, ?)
> **_2019-07-22 14:07:05,053 INFO sqlalchemy.engine.base.Engine ('Jane Doe', '', None, '', '', 3, 2)_**
> 2019-07-22 14:07:05,053:INFO:sqlalchemy.engine.base.Engine:('Jane Doe', '', None, '', '', 3, 2)
> **_2019-07-22 14:07:05,057 INFO sqlalchemy.engine.base.Engine COMMIT_**
> 2019-07-22 14:07:05,057:INFO:sqlalchemy.engine.base.Engine:COMMIT
> 2019-07-22 14:07:05,062:INFO:werkzeug:127.0.0.1 - - [22/Jul/2019 14:07:05] "POST /contactmodelview/add HTTP/1.1" 302 -

I still can't fathom why these queries should occur before the INSERT but after the form is submitted.  Any ideas?

Regards,
Nachtkinder

**Comment by dpgaspar** [comment]
Hi @nachtkinder,

These:
```
2019-07-22 14:07:05,042 INFO sqlalchemy.engine.base.Engine SELECT gender.id AS gender_id, gender.name AS gender_name FROM gender
```

Are queries to populate the dropdown lists, those are not paginated on "normal" `ModelView`s.

**Comment by nachtkinder** [comment]
Hi @dpgaspar ,

> These:
> 
> ```
> 2019-07-22 14:07:05,042 INFO sqlalchemy.engine.base.Engine SELECT gender.id AS gender_id, gender.name AS gender_name FROM gender
> ```
> 
> Are queries to populate the dropdown lists, those are not paginated on "normal" `ModelView`s.

Then why do these appear after the form is submitted not before the form is rendered?  To see what I mean:

1. Start the app from the command line
2. Navigate to the add form for OtherThing
3. Type something in the terminal from which the app was launched to act as a marker.
4. Fill out and submit the form.
5. Scroll back to see the output that was generated from SQLAlchemy since the marker was typed.

Is SQLAlchemy's echo output buffered in some way that delays this until after the form is submitted?

Thanks as always for sparing the time to look at this.

Regards,
Nachtkinder

**Comment by nachtkinder** [comment]
Hi @dpgaspar,

It's been a while.  Has there been any progress on this?

Regards,
Nachtkinder

**Comment by nachtkinder** [comment]
Hi @dpgaspar,

Whilst I appreciate that the select lists for related models in the CRUD views need to be driven from the database, is it necessary to query the database every time the list is rendered?  Surely it can be cached and invalidated/rebuilt when some relevant event happens to a model?

The real life example that I reduced to the test case for this issue involves two objects; a product_line and pack_size for that product line.  The pack_size model has been omitted from the navigation menu of the application and is accessed instead as a related_view tab of the product_line view.  By the time the user has navigated to the pack_size the application already knows the product_line being added to and so no drop-down-list of product_lines is, or ever needs to be, displayed.  However, flask_appbuilder by default queries all fields of all product_line models (which is millions of rows of 40+ columns) after submitting the add form for a pack_size.

Is there a way of by-passing refreshes of select-list information when displaying a related_view form (or other form for that matter) that does not render them?  If there is then at least I can circumvent this issue.

Thanks in advance,
Nachtkinder

**Comment by guzzijones** [comment]
I am only seeing the table scan if the record I am trying to enter already exists.  Then a full scan of the related tables occurs.
