### ISSUE TITLE
Database migration issue in quickhowto

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#105]
After initially creating a database and then making changes to the schema within .models.py file, tried to migrate using $python run.py db migrate doesn't seem to work unless I went ahead and delete the migration folder and the app.db database which defects the purpose of migration?

**Comment by dpgaspar** [comment]
There is no migration feature on F.A.B. 

The option upgrade-db on fabmanager is for upgrading the framework models after upgrade from 1.2.X to 1.3.X.

(env)[root@localhost Flask-AppBuilder]# fabmanager upgrade-db --help
Usage: fabmanager upgrade-db [OPTIONS]

  Upgrade your database after F.A.B. upgrade if necessary (SQLAlchemy only)

  Version 1.3.0 upgrade needs database upgrade, read version migration on
  docs for further details.

Options:
  --config TEXT  Your application config file path
  --backup TEXT
  --help         Show this message and exit.

**Comment by dpgaspar** [comment]
You have to handle model changes yourself, there are specialized packages for this that you can install along with F.A.B.

**Comment by scheung38** [comment]
Do you mean for example Fabric or South? Not sure which one is more popular.

**Comment by dpgaspar** [comment]
https://pypi.python.org/pypi/alembic

https://pypi.python.org/pypi/sqlalchemy-migrate

I think South is for DJANGO models.
