### ISSUE TITLE
Add 'show' API endpoint

### ISSUE THREAD

**Issue by bolkedebruin** [dpgaspar/Flask-AppBuilder#1059]
The rest API provides not enough information when using '/read', it only exposes 'list' information that is secured with 'can_list' information. A new API endpoint should be added that exposes 'show' so more details can be gotten from there.

**Comment by dpgaspar** [comment]
Hi @bolkedebruin,

The is a new API on FAB: https://flask-appbuilder.readthedocs.io/en/latest/rest_api.html

The old API is deprecated and should be removed on 2.3.X

**Comment by bolkedebruin** [comment]
I know that, but it seemed not to be available for superset yet, however I found that /api/get/<pk> sometimes exists. (But does not show up on /api).

**Comment by dpgaspar** [comment]
If this is still relevant to you, feel free to reopen (and please post more info). Thank you
