### ISSUE TITLE
quickhowto testdata generation

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#106]
If I deleted the already provided randomly generated data in quickhowto in NAMES.dic I cannot recreate it again as it now complains that rerunning the testdata.py file:

raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)

?

**Comment by dpgaspar** [comment]
i'll try to reproduce it. How did you deleted the data? delete, drop table?

**Comment by scheung38** [comment]
Was using PyCharm right click migration folder, and app.db in order to recreate new db and then command line:

$python manage.py (run.py) db init
$python manage.py db migrate

But this deletes of course all previously held data...

**Comment by dpgaspar** [comment]
What is 'manage.py' ? have you changed quickhowto models?

**Comment by scheung38** [comment]
Yes manage.py was run.py

**Comment by dpgaspar** [comment]
I'll close this, if you want to you can reopen it later.
