### ISSUE TITLE
Apache - wsgi - sqlite REDONLY

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1061]
FAB version latest (got by pip)
Ubuntu 14.04
correctly configured and installed at https://www.socializit.tk (WSGI  / python 3.6)
Server: Apache
issue sqlite appears to be **readonly**
file app.db set WRITE permission 
Running the same at 127.0.0.1 works fine

`[Mon Jul 15 13:06:49.889237 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] ERROR:flask_appbuilder.models.sqla.interface:Add record error: (sqlite3.OperationalError) attempt to write a readonly database
[Mon Jul 15 13:06:49.890119 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] [SQL: INSERT INTO ab_user (first_name, last_name, username, password, active, email, last_login, login_count, fail_login_count, created_on, changed_on, created_by_fk, changed_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[Mon Jul 15 13:06:49.890252 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] [parameters: ('dddd', 'dddd', 'ddd', 'pbkdf2:sha256:150000$j3Vr7COS$b9cfce74c332e99008b16065d5e0edcc1e6a8a9dfe09ff5cbbadcdca750a8b36', 1, 'ulixes@dddd.it', None, None, None, '2019-07-15 13:06:49.879298', '2019-07-15 13:06:49.879360', 1, 1)]
[Mon Jul 15 13:06:49.890397 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] (Background on this error at: http://sqlalche.me/e/e3q8)
[Mon Jul 15 13:06:49.890529 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] Traceback (most recent call last):
[Mon Jul 15 13:06:49.890656 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
[Mon Jul 15 13:06:49.890807 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     cursor, statement, parameters, context
[Mon Jul 15 13:06:49.890938 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
[Mon Jul 15 13:06:49.891065 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     cursor.execute(statement, parameters)
[Mon Jul 15 13:06:49.891210 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] sqlite3.OperationalError: attempt to write a readonly database
[Mon Jul 15 13:06:49.891336 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] 
[Mon Jul 15 13:06:49.891467 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] The above exception was the direct cause of the following exception:
[Mon Jul 15 13:06:49.891593 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] 
[Mon Jul 15 13:06:49.891808 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] Traceback (most recent call last):
[Mon Jul 15 13:06:49.891953 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 380, in add
[Mon Jul 15 13:06:49.892110 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     self.session.commit()
[Mon Jul 15 13:06:49.892236 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
[Mon Jul 15 13:06:49.892368 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     return getattr(self.registry(), name)(*args, **kwargs)
[Mon Jul 15 13:06:49.892939 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
[Mon Jul 15 13:06:49.893097 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     self.transaction.commit()
[Mon Jul 15 13:06:49.893239 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
[Mon Jul 15 13:06:49.893374 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     self._prepare_impl()
[Mon Jul 15 13:06:49.893506 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
[Mon Jul 15 13:06:49.893634 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     self.session.flush()
[Mon Jul 15 13:06:49.893762 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
[Mon Jul 15 13:06:49.893889 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     self._flush(objects)
[Mon Jul 15 13:06:49.894016 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
[Mon Jul 15 13:06:49.894174 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     transaction.rollback(_capture_exception=True)
[Mon Jul 15 13:06:49.894303 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
[Mon Jul 15 13:06:49.894502 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     compat.reraise(exc_type, exc_value, exc_tb)
[Mon Jul 15 13:06:49.894733 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
[Mon Jul 15 13:06:49.894906 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     raise value
[Mon Jul 15 13:06:49.895161 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
[Mon Jul 15 13:06:49.895293 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     flush_context.execute()
[Mon Jul 15 13:06:49.895432 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
[Mon Jul 15 13:06:49.895566 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     rec.execute(self)
[Mon Jul 15 13:06:49.895694 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
[Mon Jul 15 13:06:49.895850 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     uow,
[Mon Jul 15 13:06:49.895982 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
[Mon Jul 15 13:06:49.896132 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     insert,
[Mon Jul 15 13:06:49.896272 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
[Mon Jul 15 13:06:49.896410 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     statement, params
[Mon Jul 15 13:06:49.896548 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
[Mon Jul 15 13:06:49.896682 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     return meth(self, multiparams, params)
[Mon Jul 15 13:06:49.896822 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
[Mon Jul 15 13:06:49.896952 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     return connection._execute_clauseelement(self, multiparams, params)
[Mon Jul 15 13:06:49.897148 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
[Mon Jul 15 13:06:49.897286 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     distilled_params,
[Mon Jul 15 13:06:49.897431 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
[Mon Jul 15 13:06:49.897583 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     e, statement, parameters, cursor, context
[Mon Jul 15 13:06:49.897709 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
[Mon Jul 15 13:06:49.897834 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     util.raise_from_cause(sqlalchemy_exception, exc_info)
[Mon Jul 15 13:06:49.897960 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
[Mon Jul 15 13:06:49.898105 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[Mon Jul 15 13:06:49.898231 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
[Mon Jul 15 13:06:49.898363 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     raise value.with_traceback(tb)
[Mon Jul 15 13:06:49.898495 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
[Mon Jul 15 13:06:49.898622 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     cursor, statement, parameters, context
[Mon Jul 15 13:06:49.898748 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]   File "/var/www/socializit.tk/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
[Mon Jul 15 13:06:49.898873 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710]     cursor.execute(statement, parameters)
[Mon Jul 15 13:06:49.899016 2019] [wsgi:error] [pid 26614:tid 2893912896] [remote 192.210.241.185:33710] sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database`

**Comment by khood5** [comment]
how did you fix this?
