### ISSUE TITLE
How to specify the `__bind_key__` of database when using `sqlalchemy.Table`

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#1064]
I have multiple database in the app. It's easy to specify the database in `Model` using `__bind_key__ ='my_sql1'`. But how to specify the database when I need to use `Table` from `sqlalchemy`?

For example, how can I specify something like`__bind_key__ ='my_sql1'` in the following code?
```python
from sqlalchemy import Table
assoc_benefits_employee = Table(
    "benefits_employee",
    Model.metadata,
    Column("id", Integer, primary_key=True),
    Column("benefit_id", Integer, ForeignKey("benefit.id")),
    Column("employee_id", Integer, ForeignKey("employee.id")),
)
```

**Comment by dpgaspar** [comment]
Hi @shizidushu,

This is a SQLAlchemy question
