### ISSUE TITLE
Performance Issue with FAB 2.1.6/7

### ISSUE THREAD

**Issue by pich02** [dpgaspar/Flask-AppBuilder#1068]
It seems that there is a general performance issue in FAB 2.1.6 and greater

On the same page in my project I got :
with FAB 2.1.5 -> 359ms to load a page
with FAB 2.1.6/7 -> 5s to load a page

This append on all pages.

Is there anyone who got the same problem ?

pip3.7 packages : 

Package                 Version   
----------------------- ----------
aiozeroconf             0.1.8     
altgraph                0.16.1    
apispec                 1.3.3     
appdirs                 1.4.3     
asn1crypto              0.24.0    
attrs                   19.1.0    
Babel                   2.7.0     
cached-property         1.5.1     
certifi                 2019.6.16 
cffi                    1.12.3    
chardet                 3.0.4     
Click                   7.0       
colorama                0.4.1     
cryptography            2.7        
decorator               4.4.0     
defusedxml              0.6.0     
dicttoxml               1.7.4     
Flask                   1.1.1     
Flask-AppBuilder        2.1.5     
Flask-Babel             0.12.2    
Flask-Compress          1.4.0     
Flask-JWT-Extended      3.20.0    
Flask-Login             0.4.1     
flask-mongoengine       0.9.5     
Flask-OpenID            1.2.5     
Flask-SQLAlchemy        2.4.0     
Flask-WTF               0.14.2    
future                  0.17.1    
graphviz                0.11.1    
heapy                   0.6       
idna                    2.8       
ipython-genutils        0.2.0     
isodate                 0.6.0     
itsdangerous            1.1.0     
Jinja2                  2.10.1    
jinja2compact           1.1       
jsonpickle              1.2       
jsonschema              3.0.1     
jupyter-core            4.5.0     
lxml                    4.3.4     
macholib                1.11      
MarkupSafe              1.1.1     
marshmallow             2.19.5    
marshmallow-enum        1.4.1     
marshmallow-sqlalchemy  0.17.0    
memory-profiler         0.55.0    
modbus-tk               1.0.0     
mongoengine             0.18.2    
multiprocessing-logging 0.3.0     
nbformat                4.4.0     
netifaces               0.10.9    
objgraph                3.4.1     
ordereddict             1.1       
pefile                  2019.4.18 
pip                     19.1.1    
pipenv                  2018.11.26
plotly                  4.0.0     
prison                  0.1.2     
psutil                  5.6.3     
py-zabbix               1.1.5     
pycparser               2.19      
pyftpdlib               1.5.5     
PyInstaller             3.5       
PyJWT                   1.7.1     
pymongo                 3.8.0     
Pympler                 0.7       
pyOpenSSL               19.0.0    
pyrsistent              0.15.3    
pyserial                3.4       
python-dateutil         2.8.0     
python3-openid          3.1.0     
pytz                    2019.1    
PyYAML                  5.1.1     
requests                2.22.0    
requests-toolbelt       0.9.1     
retrying                1.3.3     
schedule                0.6.0     
setuptools              41.0.1    
six                     1.12.0    
SQLAlchemy              1.3.6     
SQLAlchemy-Utils        0.34.1    
traitlets               4.3.2     
urllib3                 1.25.3    
virtualenv              16.6.2    
virtualenv-clone        0.5.3     
websockets              8.0.1     
Werkzeug                0.15.5    
WTForms                 2.2.1     
xmltodict               0.12.0    
zeep                    3.4.0 

Between the 2 tests only pip FAB version changed.

**Comment by dpgaspar** [comment]
Hi,

Thank you for reporting this. 
This is really strange, we I would expect is a performance improvement on 2.1.6 not the other way around, what kind of backend are you using? 

Can you please post logs and metrics

**Comment by pich02** [comment]
Sorry for responding so late, but I have resolved my problem.

I don't know why, but I had to add : 

'Admin': [
            ['.*', '.*']
        ]

in my FAB_ROLES app config with my other default roles. 

Now it works well with FAB 2.1.6 and upper

**Comment by kubaraczkowski** [comment]
Oh wow, that saved my day. What's the cause for that?
I was struggling to profile my 1s+ page loads that now dropped to 200ms.
Thanks!

**Comment by runoutnow** [comment]
> Oh wow, that saved my day. What's the cause for that?
> I was struggling to profile my 1s+ page loads that now dropped to 200ms.
> Thanks!

I have just had a look into this...
The function def has_access uses the function def  _has_access_builtin_roles (both from from security.manager).
On each pageload all permissions are checked with this function.

when
'Admin': [
['.', '.']
]
is in the config.py
The permissions will not be checked by querying the database (this is the time you save), because def _has_access_builtin_roles got this line:

if re.match(_view_name, view_name) and re.match(_permission_name, permission_name):
                return True

and re.match(".", view_name) and re.match(".", permission_name) will always return True!

This good be stopped by using re.fullmatch instead of re.match 
But that would also stop the quick loading... :-)

Anyway, if you setup another role in the config with ['.', '.'], they will have full access!
