### ISSUE TITLE
Issue : Cannot login when launching from Internet Explorer 8

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#107]
How to make it IE 8 compatible? As launching from IE 8 doesn't even show Login button? Well it does, but after clicking an empty space where Login should be, then the Login button appears. After which Login takes to Sign In page, but Username and Password cannot be clicked? So I can assume it is not IE 8 compatible in mind?

**Comment by dpgaspar** [comment]
http://getbootstrap.com/getting-started/#support

This project makes heavy use of bootstrap.

**Comment by scheung38** [comment]
So it will not work in IE 8 then as this is the environment I have.
