### ISSUE TITLE
Modify base_permissions based on record count

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#108]
Hi,

I need to forgive adding new rows (can_add) on modelview when the user has reached their quota (that it is a number of new rows in table). The idea is that the user can do everything with the modelview till they reach the maximum allowed of new rows inserted, after that he won't be allowed to add, but it will gain that permission (can_add) again if he deletes one row.

I don't know where to apply the logic to do this. I've tried inside the modelview class itself, with no luck:
```
classMyItemsView(ModelView):
	datamodel = SQLAInterface(MyItems)
	nitems=appbuilder.session.query(MyItems).filter(MyItems.created_by_fk.like(get_user_id())).count() 
	if nitems>=3:
		base_permissions = ['can_list','can_show','can_edit','can_delete']
```

**Comment by dpgaspar** [comment]
is it ok for your solution to use pre_add method?

The user would have access to the add buttom, he could even fill the form, but when he adds the record, by overriding the pre_add method you would flash a message with a quota reached.

**Comment by jvinolas** [comment]
Hi,

I already tried that, it worked, but it is not nice to let the user 'waste' their time filling a form that will never be created because he is out of quota.

Is it possible to deactivate (or remove) the add button on top of list view overriding the list method itself and it's properties?

I would also like to add another 'add_from_myown' button on top of list view, besides the 'add' button, so the user has two add methods that make different things. I have the @expose method working well but I don't know if I should do it overriding the html template or is it possible from ModelView.

Thanks.

**Comment by dpgaspar** [comment]
yes, you can always implement your own ListWidget take a look at:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/widgets.py#L142

Create your own class, inherit from ListWidget and just override the template property to your template.

Your template could be an adapted version of appbuilder/general/widgets/list.html.

Any questions feel free to post, hope this helped.

**Comment by jvinolas** [comment]
Thanks, I'm working on overriding things... ;-)
