### ISSUE TITLE
Edit value for multiple rows

### ISSUE THREAD

**Issue by cippall** [dpgaspar/Flask-AppBuilder#1085]
Hi,

Is there an example on how to edit values for multiple rows?

Thanks!

**Comment by dpgaspar** [comment]
On code, UI? can you add more detail?

**Comment by cippall** [comment]
Ideally both , but mainly code.  

I'm looking for an example of action that modifies the column value for selected rows.

**Comment by dpgaspar** [comment]
You probably already saw this one: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickactions/app/views.py#L23

Instead of delete, update
