### ISSUE TITLE
Switch to mysql

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1086]
Hello to everybody, 
It is not an issue I just would like to know if is there a fast way to switch from sqlite to mysql, creating db file and exporting data without reinstalling all appbuilder. 

Thank you to everybody helps

**Comment by dpgaspar** [comment]
Hi @Ulixestoitaca,

There are lot's of different ways to do this.
You can always use sqlite dump and then re import into mysql, but you probably have to change change some things on the generated DDL.

You don't have to reinstall appbuilder, what do you mean by that

**Comment by Ulixestoitaca** [comment]
My app is almost ready and I used sqlalchemy. I think it should be compatible to mysql too.

So could you just confirm the steps

1 dump sqlite and mysql file creation.
2 connection string will be exactly the one I can find on your manual?
3 about DLL what to do exactly

Thanks a lot again

**Comment by Adam-Leyshon** [comment]
- Use a tool like DBeaver to export the data in your SQLite Database as SQL Insert statements.
- You may have to change the SQL syntax to work in MySQL depending on the complexity of your models/tables.
- Remember that SQLite does not enforce Primary Keys, Sequences, Auto Increments, Foreign keys or strict data types.
- Change your connection string to one that uses MySQL and target your new database.
- Start the app and let FAB create it's tables based on your defined models and/or run any Alembic migrations if you have any.
- Stop the app.
- Run the SQL Inserts generated from the SQLite DB against your MySQL database.
- Start your app, all the data should've been migrated across.

Remember you need to update your requirements.txt (and virtual environment if you're using one) to include the MySQL dependencies like pyMySQL.

There is no need to recompile any DLLs.

Hopefully this helps.
