### ISSUE TITLE
Application on production

### ISSUE THREAD

**Issue by ramiroarraya** [dpgaspar/Flask-AppBuilder#1087]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:

pip freeze output:

### Describe the expected results

Tell us what should happen.

```python
Paste a minimal example that causes the problem.
```

### Describe the actual results

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

**Comment by ramiroarraya** [comment]
Once I run the application on prod environment, from time to time the application doesnt response, I have the message that the site cant not be reached, and when I review in the  server and execute a ps to check the fabmanager application I noticed that is running, but cant not be reached,  and I have to kill the process and re started again.
Please help me with this. Thank you in advance.

**Comment by dpgaspar** [comment]
Hi @ramiroarraya,

What do you mean on ps to check `fabmanager` application, please don't run `fabmanager run` on production. you should run Flask app's using some WSGI.

**Comment by ramiroarraya** [comment]
ok, sorry I am really new in this, do you have some example that I can follow up...

**Comment by dpgaspar** [comment]
No problem, remember that flask-appbuilder is a flask extension, so you're deploying a Flask app.

Take a look at: https://flask.palletsprojects.com/en/1.1.x/deploying/
