### ISSUE TITLE
add_form_extra_fields not reusable

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#109]
I want to reuse my modelview with two different add methods but it is throwing this exception as I try to add extra fields. It seems the fields are not really created, but it works if I don't override add method and I put all the code inside modelview:

UndefinedError: 'flask_appbuilder.forms.DynamicForm object' has no attribute 'template_base'

 I've also tried to put only add_form_extra_fields in modelview itself, but same error here.
```
	@expose('/add', methods=['GET', 'POST'])
	@permission_name('add')
	@has_access
	def add(self):
		self.add_title = "Create new"
		self.add_form_extra_fields = {'size': [[TextField('Size',
								description='Dimensions',
								widget=BS3TextFieldWidget())]],
								'template_base':  [[QuerySelectField('Base Template',
								query_factory=template_query,
								widget=Select2Widget())]]}
		self.add_columns = ['name',
				'template_base',
				'size',
				'icon',
				'description']
		widget = self._add()
		if not widget:
			return redirect(self.get_redirect())
		else:
			return self.render_template(self.add_template,
                                   title=self.add_title,
                                   add_form_extra_fields=self.add_form_extra_fields,
                                   add_columns=self.add_columns,
                                   widgets=widget,
                                   appbuilder=self.appbuilder)
```

**Comment by dpgaspar** [comment]
This is because the forms are created on object init. If you must use this pattern you have to recreate the form, on this case add_form.

you can introduce:

   self.add_form = conv.create_form(self.label_columns,
                                             self.add_columns,
                                             self.description_columns,
                                             self.validators_columns,
                                             self.add_form_extra_fields,
                                             self.add_form_query_rel_fields)

Or call self._init_forms.

Hope this helps, i'll be away for a few days.

**Comment by jvinolas** [comment]
Thanks,

I'll try to do it that way. I solved it now by creating another view with the parameters I need.
