### ISSUE TITLE
how to select table in postgres database using flask-appbuilder and I have connected the postgres but i dont know how to select the existing table in postgres using flask-appbuilder.to get all the informations frm the table to my application

### ISSUE THREAD

**Issue by sanjsa02** [dpgaspar/Flask-AppBuilder#1090]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:

pip freeze output:

### Describe the expected results

Tell us what should happen.

```python
Paste a minimal example that causes the problem.
```

### Describe the actual results

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

### Steps to reproduce
****
I am using flask-appbuilder to create an user interface 

how to select table in postgres database using flask-appbuilder and I have connected the postgres but i dont know how to select the existing table in postgres using flask-appbuilder. @dpgaspar

**Comment by sanjsa02** [comment]
how to select table in postgres database using flask-appbuilder and I have connected the postgres but i dont know how to select the existing table in postgres using flask-appbuilder. @dpgaspar

**Comment by dpgaspar** [comment]
Hi @sanjsa02,

What do you mean by "select the existing table" ?, also can you improve this issue title and detail?

**Comment by dpgaspar** [comment]
duplicated
