### ISSUE TITLE
Flask-appbuilder

### ISSUE THREAD

**Issue by sanjsa02** [dpgaspar/Flask-AppBuilder#1091]
I have created user interface using flask-appbuilder

how to select table in postgres database using flask-appbuilder and I have connected the postgres but i dont know how to select the existing table in postgres using flask-appbuilder. to get the data from the table and apply to my user interface @dpgaspar

**Comment by dpgaspar** [comment]
Hi @sanjsa02,

What do you mean by "select the existing table" ?

**Comment by sanjsa02** [comment]
Hi @dpgaspar 
I have an exsisting table in postgresSQL database now i have created UI using flask-appbuilder I dont know how to link the exsisting table in PostgresSQL with flask-appbuilder UI.I have connected the PostgresSQL in flask-appbuilder i am able to create table in POSTGRES SQL but i am not able to link the exsisting table using flask-appbuilder.

I have some questions
1. I have made one UI in flask and another UI in flask-appbuilder can you tell me how to integrate it.
2. In flask-appbuilder UI can you tell me how to remove that default login User tab in that because i am changing the landing page as login page .

**Comment by sanjsa02** [comment]
and also how to bring the nav-bar vertical

**Comment by sanjsa02** [comment]
last question. How to change my  my home page

**Comment by sanjsa02** [comment]
after login successful my homepage should be customized can you help me in this

**Comment by bawantha** [comment]
Hi can is there any Postgress example for FAB I have DDL I want to create basing CRUD application from that I couldn't find any tutorial  about postgres

**Comment by sanjsa02** [comment]
after login successful my homepage should be customized can you help me in this @dpgaspar
