### ISSUE TITLE
how to encode datetime in rison format?

### ISSUE THREAD

**Issue by jabbawockeez** [dpgaspar/Flask-AppBuilder#1099]
Because datetime(like 2019-08-29 01:00:00) contains colon puctuation(:), seems like the js lib(https://github.com/Nanonid/rison) didn't work well with that.

**Comment by dpgaspar** [comment]
Hi @jabbawockeez,

FAB itself is using `prison` for Rison. Can you give me more detail on your problem?

**Comment by jabbawockeez** [comment]
@dpgaspar well, I'm using Vue as the front-end, so my flask app serves as api server, and now I have to send datetime data but I don't know how to encode it while there are colons in the data.

**Comment by dpgaspar** [comment]
oh! I see, sorry, so you mean on a GET request, for filters? If yes, that's a good question.

**Comment by dpgaspar** [comment]
Made some simple tests and
```
http://localhost:8080/api/v1/contact/?q=(filters:!((col:birthday,opr:gt,value:'1954-01-01 10:00')))
```
Works, can you post more details?
