### ISSUE TITLE
How to edit or update a particular field after it is generated ?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#110]
Are there working examples?

In model.py:

class myModel(Model):
    __tablename__ = mymodel
    id = Column(Integer, primary_key=True)
    Name = Column(String(25), default=None)
    Address = Column(String(25), default=None)

in view.py

def fill_model():
    try:
        db.session.add(myModel(Name='hello', Address ='UK')
        db.session.commit()
    except:
        db.session.rollback()

class myModelView(ModelView):
    datamodel = SQLAInterface(myModel)
    list_columns = ['Name', 'Address']

db.create_all()
appbuilder.add_view(myModelView, myModel, icon="fa-folder-open-o", category="Panel Operations", category_icon='fa-envelope')

How would you update field for 'Address' ?

Thanks

**Comment by scheung38** [comment]
Actually maybe easier just to define all the Column database objects in the add_view since they are all read only, and then with the Edit button that's provided, only showing just the Column database object that are editable? But not sure how modify such that only one data obect is editable

**Comment by dpgaspar** [comment]
On the docs: http://flask-appbuilder.readthedocs.org/en/latest/advanced.html#forms

on your use case, first define a readonly widget:
 
    from flask_appbuilder.fieldwidgets import BS3TextFieldWidget

    class BS3TextFieldROWidget(BS3TextFieldWidget):
        def __call__(self, field, **kwargs):
            kwargs['readonly'] = 'true'
            return super(BS3TextFieldROWidget, self).__call__(field, **kwargs)

Then on you ModelView definition:

    class myModelView(ModelView):
        datamodel = SQLAModel(myModel)
        list_columns = ['Name', 'Address']
        edit_form_extra_fields = {'Name': TextField('Name',
                                widget=BS3TextFieldROWidget())}

This way on the edit form, the **Name** field will be readonly. I've not tested this answer, please tell me if this what your asking, and if it worked.
