### ISSUE TITLE
LDAP to multiple servers (superset)

### ISSUE THREAD

**Issue by ziusware** [dpgaspar/Flask-AppBuilder#1101]
Is your feature request related to a problem? Please describe.
I was trying to connect more than one domain on my Superset, but I think Superset does not permit that. When I try to connect more than one LDAP SERVER the Superset doesn't accept because on his source code he just accept one parameter.

Describe the solution you'd like
Ask for a option to add more than one domain on Superset.

Describe alternatives you've considered
Superset just permit us to connect just one LDAP connection with the parameters below:

AUTH_LDAP_SERVER = ""
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_BIND_USER = ""
AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_SEARCH = ""
AUTH_LDAP_UID_FIELD = ""
AUTH_LDAP_FIRSTNAME_FIELD = ""
AUTH_LDAP_LASTNAME_FIELD = ""

If we can use a separition to connect one more domain, ou many others, separating them with a space or a comma it would be very useful.

**Comment by BennyJane** [comment]
I expect that there will be a good solution!

**Comment by CameronNemo** [comment]
https://github.com/dpgaspar/Flask-AppBuilder/issues/806

**Comment by dpgaspar** [comment]
Hi,

Sorry for the delay. FAB currently does not support this and `python-ldap` does not support it either.

Take a look at: https://github.com/python-ldap/python-ldap/issues/248

If fail over is what you aim for, try the described solution above, or you can always use a load balancer in front of your LDAP servers
