### ISSUE TITLE
Customize one widget on the default form (make a widget a fixed list select)

### ISSUE THREAD

**Issue by Annakan** [dpgaspar/Flask-AppBuilder#1103]
Hello
I need to limit the choices on a status field to a limited number of values.
These values are not especially in the DB.
I would like to override **one** widget on the default form with a wtforms.fields.SelectField.

Is that possible ? Or do I have to override the whole form ?

Can I define this in the model without relying the specific SqlA data source because I want later on to access a NoSQL database through a Generic Data Source.

More generally how does one override one widget without rendering direct markup as in 
https://flask-appbuilder.readthedocs.io/en/latest/advanced.html#custom-fields

Or do I have to use
@render decorator and then SelectField() rendering instead of markup ?

**Comment by dpgaspar** [comment]
See if this example help with your use case

**Comment by Annakan** [comment]
Thanks a lot.
It works for Enum, I'll reformulate the more general question about customizing one widget.
