### ISSUE TITLE
Per object/row access  right / field based conditional edition

### ISSUE THREAD

**Issue by Annakan** [dpgaspar/Flask-AppBuilder#1109]
Hello again.
I am implementing a very simple list of objects + edit form for the object application.
The only things is that object have a status and when the status is "validated/published" they can't be modified anymore.

I would like to not have the edit or suppress button for those but that's a consequence of the general action that are allowed on them.

I could probably override the whole list form and check for this property on each row but that's a bad design because it would not, for instance, prevent the REST API or a maligned POST to still update or delete the object, unless I duplicate the logic in the validation.

Is there a better way like a callback method on the model that would take the context (request, user) and the instance and return a list of allowed actions (that would be further limited by the set of permission) ?

**Comment by dpgaspar** [comment]
Hi,

For a better UX on the MVC templates, you must override the list template and check the `status` on each row (like you said)

On edit you can use `pre_edit` and check for the `status` property
