### ISSUE TITLE
Permission: any authed user

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#111]
Is it possible (and if not, treat this as a feature request) to have a 'special' role like Public for any authenticated user. Especially when using ldap as an auth backend, it would be nice to have all new users be a member of a role so they can get higher permissions than Public. Maybe just call that role User?

Thanks,

**Comment by dpgaspar** [comment]
Hello Ben,

Sorry for the delay, you can create your own role with the permissions you like and then set it on config to be used as the default, using: AUTH_USER_REGISTRATION_ROLE

All auto registering users on LDAP will be assoc with this role.

Am i misunderstanding you question?

**Comment by ben-github** [comment]
That's exactly what I want -- I just didn't see that AUTH_USER_REGISTRATION_ROLE configuration. Thanks.
