### ISSUE TITLE
Oauth2 can not be logout in server

### ISSUE THREAD

**Issue by cdmikechen** [dpgaspar/Flask-AppBuilder#1110]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:
Flask-AppBuilder 1.13.0, using in superset==0.28.1
pip freeze output:
pip3 list |grep Flask-AppBuilder
Flask-AppBuilder       1.13.0   

I used cas-oauth2(5.3) to test.
```
from flask_appbuilder.security.manager import AUTH_OAUTH
AUTH_TYPE = AUTH_OAUTH
OAUTH_PROVIDERS = [
    {   'name':'casOauth2',
        'token_key':'access_token', 
        'icon':'fa-address-card',   
        'remote_app': {
            'consumer_key':'xxx',  
            'consumer_secret':'xxx', 
            'request_token_params':{},
            'access_token_method':'POST',    
            'access_token_params':{     
                'client_id':'xxx',
                'client_secret':'xxx'
            },
            'access_token_headers':{    
                'Authorization': 'Basic Base64EncodedClientIdAndSecret'
            },
            'base_url':'http://localhost:8443/cas/oauth2.0/',
            'access_token_url':'http://localhost:8443/cas/oauth2.0/accessToken',
            'authorize_url':'http://localhost:8443/cas/oauth2.0/authorize'
        }
    }
]
```

### Describe the expected results
Tell us what should happen:
When finishing configuration in Flask-AppBuilder with oauth2, I login with user A, and then logout. After that I change user B to login, it should work.

### Describe the actual results
Tell us what happens instead:
When I logout, Flask-AppBuilder can not logout in oauth2 server. So that when I want to change another user B login, It login directly with the user A.

### Steps to reproduce
Maybe we need to support a method to logout in oauth2 server.

**Comment by jeverling** [comment]
Hi @cdmikechen maybe the problem is just that Flask Appbuilder redirects to the homepage after logout, so you get logged in straight back with User A?

[flask_appbuilder/security/views.py#L477](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L477)
```
class AuthView(BaseView):
    route_base = ""
    login_template = ""
    invalid_login_message = lazy_gettext("Invalid login. Please try again.")
    title = lazy_gettext("Sign In")

    @expose("/login/", methods=["GET", "POST"])
    def login(self):
        pass

    @expose("/logout/")
    def logout(self):
        logout_user()
        return redirect(self.appbuilder.get_url_for_index)
```

So the logout is actually working - all it does is to delete the `session` cookie. But then the redirect to the homepage will set the session cookie again, so you "remain" logged in with user A.
This could be fixed by making the "redirect after logout" configurable in Flask Appbuilder, I'm going to open a ticket for this.

**Comment by shawnzhu** [comment]
After #1618 merged, when only one oauth2 provider configured, AppBuilder will not show the provider selection page when redirecting to `/login` nor `/login/<provider>`. I'd propose changing the logout flow to show provider selection login page instead, or it will never let user log out of app.
