### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by gbrian** [dpgaspar/Flask-AppBuilder#1115]
Hi @dpgaspar ,
Do you think is worth it to integrate https://flask-monitoringdashboard.readthedocs.io/en/latest/ with Flask-AppBuilder? Testing with Superset

Thanks

![image](https://user-images.githubusercontent.com/767180/64685069-96aae880-d486-11e9-9ba4-04212dc2e8cc.png)

**Comment by CameronNemo** [comment]
This seems like a neat tool, but I have two questions:

1. What sets it apart from other performance monitoring mechanisms, such as Elasticsearch's APM.
2. Why does FAB need to be integrated with this? From what I can tell, it should be possible to invoke the library in your application without having to change FAB code. https://flask-monitoringdashboard.readthedocs.io/en/latest/installation.html#setup-the-flask-monitoringdashboard
