### ISSUE TITLE
Menu data got directly from db

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1121]
Hello to everybody,

it is not an issue just a question, I am not currently able to find a solution.
I just would like to create a menu list getting data from mariadb, something like "select xxx from yyy where kkk =" + g.user.id in order to list directly in menu elements related to  the user.

Clearly I am getting a context error and I wonder if it is really doable what I am tryng to do and how.

Thanks for any help you could provide to me

**Comment by dpgaspar** [comment]
Hi,

do you really mean a menu dropdown? or a ModelView list?

**Comment by Ulixestoitaca** [comment]
a menu dropdown,  but in that situation I am still out of context so I am not aware if is there a way really

**Comment by dpgaspar** [comment]
No request context no user logged in, yes

**Comment by Ulixestoitaca** [comment]
ok thanks...no workaround for having another kind of list in the header (for example a bootsrap select object) ?

**Comment by Ulixestoitaca** [comment]
after login I mean, with a valid g.user.id
