### ISSUE TITLE
IE9 compatibility

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#113]
I see that inside appbuilder/init.html already has html5shiv.js to take care of IE8 and below

 

so not sure why it is still not rendering properly in IE8 browser?

**Comment by dpgaspar** [comment]
Hello,

Sorry for the delay. This is true, at it may be a bug, reading bootstrap docs this should go after *bootstrap*. I've tried it, but i must warn you, it will not render the same way as IE10 or above.

I'll release a minor with this change ASAP.

**Comment by scheung38** [comment]
Thanks, if loading using bower into project directory locally already helps? So that when working offline environment IE can still render?

**Comment by dpgaspar** [comment]
Thanks, new version 1.3.3 is out, and corrects this issue. Haven't made many tests on this.

**Comment by scheung38** [comment]
So do I modify the actual base init.html within the FlaskAppBuilder -> templates -> appbuilder -> init.html since this is where others from this:

```html
<!--[if lt IE 9]>
	<script src="bower_components/html5shiv/html5shiv.js"></script>
<![endif]-->

**Comment by dpgaspar** [comment]
I think that there is no need to modify anything.

**Comment by scheung38** [comment]
This is what it renders on IE 8

**Comment by scheung38** [comment]
This is what it renders in IE8, cannot click...

**Comment by dpgaspar** [comment]
send me the output of 'pip list' from your enviroment, please.

**Comment by scheung38** [comment]
Babel==1.3
CouchDB==1.0
Cython==0.21
DataShape==0.4.2
Flask==0.10.1
Flask-AppBuilder==1.3.3
Flask-Assets==0.10
Flask-BabelPkg==0.9.6
Flask-Bcrypt==0.6.0
Flask-Bootstrap==3.3.0.1
Flask-Cache==0.13.1
Flask-CouchDB==0.2.1
Flask-HTTPAuth==2.3.0
Flask-LDAP==0.1.6
Flask-Logging==0.1.3
Flask-Login==0.2.11
Flask-Mail==0.9.1
Flask-Migrate==1.3.0
Flask-Moment==0.4.0
Flask-OAuth==0.12
Flask-OpenID==1.2.4
Flask-PageDown==0.1.5
Flask-PyMongo==0.3.0
Flask-Restless==0.17.0
Flask-SQLAlchemy==2.0
Flask-SSLify==0.1.4
Flask-Script==2.0.5
Flask-SimpleLDAP==0.3.0
Flask-SocketIO==0.4.3
Flask-Sockets==0.1
Flask-Testing==0.4.2
Flask-Uploads==0.1.3
Flask-WTF==0.11
ForgeryPy==0.1
Jinja2==2.7.3
Mako==1.0.0
Markdown==2.5.2
MarkupSafe==0.23
PIL==1.1.7
PyAudio==0.2.7
PyYAML==3.11
Pygments==1.6
SQLAlchemy==0.9.8
Sphinx==1.2.3
WTForms==2.0.2
Werkzeug==0.10.1
XlsxWriter==0.5.7
abstract-rendering==0.5.1
alembic==0.7.2
amqp==1.4.6
anyjson==0.3.3
argcomplete==0.8.1
astropy==0.4.2
atom==0.3.9
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
billiard==3.3.0.19
binstar==dev
bitarray==0.8.1
blaze==0.6.3
bleach==1.4.1
blinker==1.3
blz==0.6.2
bokeh==0.6.1
boto==2.32.1
casuarius==1.1
cdecimal==2.3
celery==3.1.17
cffi==0.8.6
chaco==4.4.1
click==3.3
clyent==0.3.2
colorama==0.3.3
configobj==5.0.6
configparser==3.3.0r2
coverage==3.7.1
cryptography==0.5.4
cytoolz==0.7.0
decorator==3.4.0
docutils==0.12
enable==4.3.0
enaml==0.9.8
flask-heroku-mongoengine==0.1.5
flask-mongoengine==0.7.1
future==0.13.1
futures==2.1.6
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.3
gnureadline==6.3.3
graphviz==0.4.2
greenlet==0.4.4
grin==1.2.1
gunicorn==19.1.1
h5py==2.3.1
html5lib==0.999
httplib2==0.9
ipython==2.3.1
itsdangerous==0.24
jdcal==1.0
juggernaut==0.2
kiwisolver==0.1.3
kombu==3.0.24
llvmpy==0.12.7
lxml==3.4.0
matplotlib==1.4.0
mimerender==0.5.5
mock==1.0.1
mongoengine==0.8.7
multipledispatch==0.4.7
networkx==1.9.1
nltk==3.0.0
nose==1.3.4
numba==0.14.0
numexpr==2.3.1
numpy==1.9.1
oauth2==1.5.211
openpyxl==1.8.5
pandas==0.14.1
patsy==0.3.0
pep8==1.5.7
ply==3.4
psutil==2.1.1
psycopg2==2.5.3
py==1.4.25
py-bcrypt==0.4
pyOpenSSL==0.14
pycosat==0.6.1
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.5
pydot==1.0.2
pyface==4.4.0
pyflakes==0.8.1
pymongo==2.7.2
pyparsing==2.0.1
pyreadline==2.0
pytest==2.6.3
python-dateutil==2.3
python-ldap==2.4.19
python-mimeparse==0.1.4
python-openid==2.2.5
pytz==2014.10
pyzmq==14.3.1
redis==2.9.1
requests==2.5.0
rope==0.9.4
rq==0.5.0
runipy==0.1.1
scikit-image==0.10.1
scikit-learn==0.15.2
scipy==0.14.0
selenium==2.44.0
six==1.8.0
sockjs-tornado==1.0.1
speaklater==1.3
spyder==2.3.1
sqlalchemy-schemadisplay==1.2
statsmodels==0.5.0
sympy==0.7.5
tables==3.1.1
toolz==0.7.0
tornado==4.0.2
traits==4.4.0
traitsui==4.4.0
uWSGI==2.0.8
ujson==1.33
unicodecsv==0.9.4
webassets==0.10.1
wsgiref==0.1.2
xlrd==0.9.3
xlwt==0.7.5

**Comment by dpgaspar** [comment]
Ok, thanks, i've done some tests using WinXP and IE8 and it works. You must check the following:

1 - Goto Developer tools on IE
2 - Choose IE8 on default browser and on compatibility choose IE8 also.

**Comment by scheung38** [comment]
So was it because of your change or would this have worked anyway? Thanks Daniel

**Comment by dpgaspar** [comment]
is it working?

**Comment by scheung38** [comment]
checking...

**Comment by scheung38** [comment]
With 1.3.3 Theme doesnt seem to work at all, changed theme setting and output still showing previous themes and any changes made to other themes is still not reflected in web browser, whether Firefox or IE8
