### ISSUE TITLE
Marshmallow version is restrictive and out of date

### ISSUE THREAD

**Issue by mattdornfeld** [dpgaspar/Flask-AppBuilder#1133]
The Marshamallow version is pretty restrictive and is not up to date with the latest major release of Marshmallow. Any chance this can be updated to allow for 3.x.x releases of Marshmallow. This package is a dependency for Airflow, which is pretty widely used. The version restriction basically precludes using any other packages that use a new version of Marshmallow along with Airflow.

**Comment by dpgaspar** [comment]
Left a comment on the PR

**Comment by ecederstrand** [comment]
Left a comment in the PR - the version restriction in Airflow is gone.

**Comment by dpgaspar** [comment]
Thank you, great news!
