### ISSUE TITLE
Rendering multiple databases on the same page in SQLite

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#114]
Doc says can work with multiple databases: 

http://flask-appbuilder.readthedocs.org/en/latest/multipledbs.html

So whether SQLite, MySQL etc , multiple databases can be rendered on a single page too?

**Comment by dpgaspar** [comment]
No reason why not. But remember that F.A.B. by default will render a View or ModelView per page.
You would have to create your own template to render multiple ModelView widgets on the same page.
Use multiple databases more or less (be careful with relations) the same way you would by using the a single database.

You can easily use different databases on the same app.

Note also, that you can use relations between models that exist on different databases, but they will not  behave correctly on updates or delete.
