### ISSUE TITLE
formatters_columns is ignored during "show" if you use fieldsets

### ISSUE THREAD

**Issue by kdhunter** [dpgaspar/Flask-AppBuilder#1141]
Flask-Appbuilder version:  2.1.13 (and current master branch in GitHub)

### Describe the expected results

formatters_columns should be consulted when formatting output when using fieldsets

### Describe the actual results

The field value is rendered directly, instead of passing it through the formatter.

The problem is in flask_appbuilder/templates/appbuilder/general/widgets/show.html - lines 34-36 (no fieldsets) contain:
```
                {% set formatter = formatters_columns.get(item) %}
                {% set v = value_columns[loop.index-1]%}
                <span style="white-space: pre-line">{{formatter(v) if formatter else v}}</span>
```
which behave as expected, but line 19 (with fieldsets) is just
```
<td><span style="white-space: pre-line">{{value_columns[include_columns.index(item)]}}</span></td>
```

As you can see, there is no check for/use of a formatter.

Using a template in which line 19 is replaced with the following corrects the problem

```
            {% set formatter = formatters_columns.get(item) %}
            {% set v = value_columns[include_columns.index(item)]%}
            <td><span style="white-space: pre-line">{{formatter(v) if formatter else v}}</span></td>
```

**Comment by dpgaspar** [comment]
Seems like it, are you willing to submit a PR for solve it?
