### ISSUE TITLE
Datetime Field and nanoseconds precision - SQL Server

### ISSUE THREAD

**Issue by jelther** [dpgaspar/Flask-AppBuilder#1151]
I have a datetime field defined inside my model as:

```
dt = Column(Datetime,'dt')
```

When I try to edit a specific row through the Edit Record option, my datetime field is shown with a nanoseconds precision:

![image](https://user-images.githubusercontent.com/4515493/65972518-9079ad80-e42f-11e9-9c30-cfa63322b5bb.png)

If I try to update the whole record without tampering this field, it raises an error : 

![image](https://user-images.githubusercontent.com/4515493/65972600-b1da9980-e42f-11e9-9eed-42d779e0e315.png)

Is there an easy way to correctly define the nanoseconds without having to create a custom form?

**Comment by LeiYangGH** [comment]
can you share how you import `Datetime`? i also have similiar question.
