### ISSUE TITLE
Embed dash app inside FAB

### ISSUE THREAD

**Issue by giordyb** [dpgaspar/Flask-AppBuilder#1152]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.1.13

pip freeze output:

### Describe the expected results

I'm trying to embed a Dash app (https://plot.ly/dash/) inside FAB in order to leverage the ldap authentication, roles, etc.

the only example I could find is this one (https://community.plot.ly/t/dash-on-multi-page-site-app-route-flask-to-dash/4582/18), but it doesn't seem to be working.

Does anybody have any examples on how to do this?

thanks!
### Describe the actual results

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

### Steps to reproduce
this is what I added to my views.py

```
class DashTest(BaseView):
    route_base = "/"
    default_view = "index"

    @expose("/dashtest")
    def index(self):
        return redirect('/dashtest2')



appbuilder.add_view_no_menu(DashTest, "DashTest")

app = Flask(__name__)

dash_app = Dash(server=app, routes_pathname_prefix="/dashtest2/")

dash_app.layout = html.Div(
    [
        html.Div(id="target"),
        dcc.Input(id="input", type="text", value=""),
        html.Button(id="submit", n_clicks=0, children="Save"),
    ]
)


@dash_app.callback(Output("target", "children"), [Input("submit", "n_clicks")], [State("input", "value")])
def callback(n_clicks, state):
    return "callback received value: {}".format(state)


appbuilder.add_link("Dash", href="/dashtest", icon="fa-list", category="Demo Dash", category_icon="fa-list")
```

when I try to access the dashtest2 url i get a "Page not found" from FAB

**Comment by giordyb** [comment]
so I did a little bit more research and found this project, that embeds dash with flask and flask-login:
https://github.com/okomarov/dash_on_flask

basically it registers the dash app in the __init__.py like this:
```
def register_dashapps(app):
    from app.dashapp1.layout import layout
    from app.dashapp1.callbacks import register_callbacks

    # Meta tags for viewport responsiveness
    meta_viewport = {"name": "viewport", "content": "width=device-width, initial-scale=1, shrink-to-fit=no"}

    dashapp1 = dash.Dash(__name__,
                         server=app,
                         url_base_pathname='/dashboard/',
                         assets_folder=get_root_path(__name__) + '/dashboard/assets/',
                         meta_tags=[meta_viewport])

    with app.app_context():
        dashapp1.title = 'Dashapp 1'
        dashapp1.layout = layout
        register_callbacks(dashapp1)

    _protect_dashviews(dashapp1)
```


and then protects the view behind flask-login using this
```
def _protect_dashviews(dashapp):
    for view_func in dashapp.server.view_functions:
        if view_func.startswith(dashapp.config.url_base_pathname):
            dashapp.server.view_functions[view_func] = login_required(dashapp.server.view_functions[view_func])
```

if I skip the "_protect_dashviews" then the app gets registered and can be reached at the "/dashboard" url, what I am trying to do is protect it behind FAB's own authentication.

i tried to replace "login_required" with has_access but i got a "Was unable to import app Error: 'method' object has no attribute '_permission_name'" error.

I'm not familiar with all the objects and dependencies of flask-appbuilder...can anybody give me any hints?

**Comment by adityamehta1990** [comment]
Check this out: https://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.security.decorators.permission_name

You basically need to define which permission name is required to view the dashboard. If you only use the `has_access` decorator, it will look for a permission name which is the same as the method name.

I was not able to find out a way to simply check whether a user has logged in vs checking for a specific permission. The `permission_name` approach might make things a bit more complicated but it allows you to have a lot more flexibility - for example, you can have different permissions for different users.

**Comment by giordyb** [comment]
@adityamehta1990 thanks for the reply, 

It looks like the issue here is that the view functions created by Dash (and which I am trying to protect with the _protect_dashviews() function)  are not FAB's view functions and don't have the "_permission_name" attribute so everything breaks down...
the permission_name decorator only sets the permission name but cannot create the attribute.

**Comment by giordyb** [comment]
Nevermind, I was able to get a working Dash dashboard embedded inside FAB and protected with the login using this example https://github.com/jimmybow/Flask_template_auth_with_Dash

 @dpgaspar would you accept a pull request for a simple example to add to the "examples" folder  even though it embeds a different project?

**Comment by adityamehta1990** [comment]
@giordyb Can you share a code snippet or a gist with an example till the time you add an example to FAB?

**Comment by giordyb** [comment]
@adityamehta1990  you can find the example in repo https://github.com/giordyb/Flask-AppBuilder/tree/master/examples/dash
