### ISSUE TITLE
Make redirect after logout configurable

### ISSUE THREAD

**Issue by jeverling** [dpgaspar/Flask-AppBuilder#1154]
Hi all,

I think it would be really useful if the URL that Flask-Appbuilder redirects to after logout would be configurable - akin to Django's `LOGOUT_REDIRECT_URL` setting.

Right now, the user is redirected to the hompage:

[flask_appbuilder/security/views.py#L477](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L477)
```
class AuthView(BaseView):
    route_base = ""
    login_template = ""
    invalid_login_message = lazy_gettext("Invalid login. Please try again.")
    title = lazy_gettext("Sign In")

    @expose("/login/", methods=["GET", "POST"])
    def login(self):
        pass

    @expose("/logout/")
    def logout(self):
        logout_user()
        return redirect(self.appbuilder.get_url_for_index)
```

This might not be what is desired though, maybe the user should see a "thank you and see you soon page" or something like that, and it can also lead to problems with setups that use oauth2 for authentication, because the user will be logged straight back in if the oauth2 provider is configured to allow login without a prompt. I think this is what happens in #1110
So I think having an option to configure where users are redirected to after logout would be really useful, e.g.

```
    return redirect(
        self.appbuilder.app.config.get(
            "LOGOUT_REDIRECT_URL", self.appbuilder.get_url_for_index
        )
    )
```

**Comment by dpgaspar** [comment]
Agree, are you willing to submit a PR for it?

**Comment by jeverling** [comment]
I'm happy to do that, but I'll be a few days until I'm able to work on it.
