### ISSUE TITLE
[QUESTION] How to make API calls with Celery?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#1159]
How to integrate with Celery to make async API call? Examples shown?

**Comment by dpgaspar** [comment]
Hi @scheung38,

Take a look at superset:

https://github.com/apache/incubator-superset/tree/master/superset/tasks

an example task:
https://github.com/apache/incubator-superset/blob/master/superset/sql_lab.py#L137

etc...
