### ISSUE TITLE
Access ab_ relation tables from session.query

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#116]
Hi,

I need to do populate a dropdown with a select like this:
```
appbuilder.session.query(Templates).\
			join(Table(ab_user_role.id).\
			join(User.id).\
			filter(User.id==1).\
		        group_by(Templates.id)
```
That I need to convert completely to sqlalchemy from this select:
```
SELECT templates.* 
FROM ab_role 
LEFT JOIN ab_user_role ON ab_user_role.role_id = ab_role.id 
LEFT JOIN ab_user ON  ab_user_role.user_id = ab_user.id  
LEFT JOIN template_roles ON template_roles.role_id = ab_role.id  
LEFT JOIN templates ON templates.id = template_roles.template_id 
WHERE ab_user.id = 1 
GROUP BY templates.id;
```
That basically will filter all the templates that have the same roles assigned (template_roles table) as the user (ab_user_role).

But the problem is I can't access 'ab_user_role' table (neither other ab_ tables) in my first sqlalchemy test as I don't have the model, but I assume it is created on appbuilder backend. Is it possible to access that table model class or do I have to recreate all from Base?

Or... maybe is another quicker way of doing what I need?

Thanks.

**Comment by dpgaspar** [comment]
You can access the models by importing them from:

    from flask_appbuilder.security.sqla.models import User, Role

give me feedback if this was enough to solve your problem.

**Comment by jvinolas** [comment]
Well it was not exactly that. I knew I could access User and Role models from sqlalchemy, but I was not able to access relation tables like 'ab_user_role'. So I found I could do it if I recreate that class:
```
class AssocUserRoles(Base):
    __tablename__ = 'ab_user_role'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('ab_user.id'))
    role_id = Column(Integer, ForeignKey('ab_role.id'))
```
And now I can filter using sqlalchemy:
```
appbuilder.session.query(Templates).join(AssocTemplateRoles).join(Role).join(AssocUserRoles).filter(AssocUserRoles.user_id==get_user_id())
```
