### ISSUE TITLE
Store password as configuration in custom class causes error

### ISSUE THREAD

**Issue by kootenpv** [dpgaspar/Flask-AppBuilder#1166]
I thought to just extend one of the simple examples, and to add a password column. At first I tried `PasswordType` from `sqlalchemy_utils`, but even with `String` as is done in `Flask-AppBuilder` itself it causes an error):

```python
class ContactGroup(BaseMixin, Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    password = Column(String(256))

    def __repr__(self):
        return self.name
```

Here is the error:

```python
  File "/home/pascal/.pyenv/versions/3.7/envs/nostal/lib/python3.7/site-packages/wtforms/form.py", line 65, in __getitem__
    return self._fields[name]
KeyError: 'password'
```

When I try to add a column called `name2` it *does* work. But I obviously want a (masked) password column.

**Comment by kootenpv** [comment]
This is different from hashing a password as it needs to be encrypted/decrypted. 
I'll look at airflow how they are doing this.

**Comment by HugoNeves** [comment]
Hi @kootenpv,

Did you manage to make it work in the end?

I'm also trying to add a column of type password to my Model but I can't see to find a way to do it.
