### ISSUE TITLE
I'm trying to filter results in ViewModel with MongoDB as a backend - it doesn't work

### ISSUE THREAD

**Issue by reffael** [dpgaspar/Flask-AppBuilder#117]
I'm using Mongo as the backend and I'm trying to filter a view to show only the entries of the logged in user (by its customerID in the mongo document)
I'm following the example from the docs and this is my code:

    from  flask.ext.appbuilder.models.sqla.filters import FilterEqualFunction
    -------
    def get_user():
        return str(g.user.id)

    class ItemModelView(ModelView):
        datamodel = MongoEngineInterface(Item)
        list_widget = MyWidgetList
        base_filters = [['customerID', FilterEqualFunction, get_user],]

but it doesn't effect the result at all - all the records are shown.
btw - do I use the correct filter ? I took the one from sqla.filters because there isn't something similar in the Mongo folder.

**Comment by dpgaspar** [comment]
This is because your using FilterEqualFunction from models.sqla this package is for SQLAlchemy.

But, the problem is that i've not implemented a **FilterEqualFunction** for MongoEngine. I'll correct this ASAP, releasing a minor version.

**Comment by reffael** [comment]
Yes, that what I was thinking
Thanks, you are my hero..

**Comment by dpgaspar** [comment]
Thanks, new version 1.3.3 is out, and corrects this issue
