### ISSUE TITLE
Custom Validations Not working

### ISSUE THREAD

**Issue by nehatharani** [dpgaspar/Flask-AppBuilder#1171]
Hi, 
I am trying to write custom validation as per documentations: 
https://flask-appbuilder.readthedocs.io/en/latest/advanced.html
 Validation looks like: 
```
class DelModelView(ModelView):
    datamodel = SQLAInterface(Dell)
    base_filters = [['cap_id', FilterEqualFunction, get_user]] #current user
    list_columns = ["cap_id", "s_code", "s_name", "sos", "date_of_change"] 
    #base_order = ("cap_id", "asc")
    validators_columns = {
        'cap_id':[FilterEqualFunction(get_user, message=_('fields must match'))]
    }
```

I am getting an error: 
TypeError: __init__() got an unexpected keyword argument 'message'

When I remove the message field, the validation simply doesn't work. 

I have followed the instructions, [Here](https://flask-appbuilder.readthedocs.io/en/v1.13.0/advanced.html#forms-custom-validation-rules)

Please help me fix this. 

Thank you. 

Regards,
Neha

**Comment by dpgaspar** [comment]
Hi @nehatharani,

Note that:
```
class MyView(ModelView):
    datamodel = SQLAInterface(MyModel)
    validators_columns = {'my_field1':[EqualTo('my_field2',
                                        message=gettext('fields must match'))
                                      ]
    }
```
So, `EqualTo` is not the same as `FilterEqualFunction` Take a look at WTForms for more detail

**Comment by nehatharani** [comment]
Hi @dpgaspar 

Thank you for replying. :) 

I have tried this as well. This doesn't seem to work either. I have read all the issues related to this but nothing seems to validate. I have been working on fixing this since 5 days now.. :( 

My current code is: 

```
class DelModelView(ModelView):
    datamodel = SQLAInterface(Dell)
    base_filters = [['cap_id', FilterEqualFunction, get_user]] #current user
    list_columns = ["cap_id", "s_code", "s_name", "sos", "date_of_change"] 
    #base_order = ("cap_id", "asc")
    validators_columns = {
        'cap_id':[EqualTo(get_user, message=_('fields must match'))]
    }
```
where cap_id is coming from **DelModel**. I am using Inbuild App builder forms. 
In the form, while adding, I gave added the correct entry (cap_id = current_user) but it still says **Invalid Field Name".** The message in gettext isn't displaying either. Can you suggest something here? 

I want to enforce users to enter only cap_id while adding new entries, not anything else. 

Thank you,
Neha

**Comment by nehatharani** [comment]
I figured it out.  I gave a cap_id a default value which is get_user. I removed cap_id from add and edit columns and now it works. This may not ideal solution here but it works for the current use-case we have. 

Cheers!!

**Comment by nehatharani** [comment]
closing this one. Thanks. :)
