### ISSUE TITLE
Enhancement: Support forJSON:API-compliant requests and responses

### ISSUE THREAD

**Issue by zeusttu** [dpgaspar/Flask-AppBuilder#1172]
Flask-AppBuilder provides some helpers to create CRUD API endpoints directly from a model. Which is great! Unfortunately there seem to be little to no options for customizing the request and response format, which means that I would have to write my own endpoint code from scratch for each individual HTTP verb if I want to accept requests and send responses that conform to e.g. the JSON:API standard. It would be great if there was some option that conditions API endpoints to expect requests and produce responses in the JSON:API format instead of what looks to be Flask-AppBuilder's own format.

**Comment by zeusttu** [comment]
I can probably work on this myself, in which case I will probably assume the following constraints:

* There is one Flask configuration option `APPBUILDER_REQUEST_AND_RESPONSE_FORMAT`.
* The default value is `Flask-AppBuilder`.
* If its value is `JSON:API` then all endpoints will accept JSON:API-compliant requests and produce JSON:API-compliant responses.
* Any value of the configuration option that is neither `Flask-AppBuilder` not `JSON:API` will result in the default behaviour as if the option was configured to `Flask-AppBuilder`.
* The configuration option is case sensitive.
* There is no way to override the behaviour for a specific model or endpoint.

If you are unhappy about any of these constraints, please let me know, then I might do it differently. If all goes well then you may see a pull request sometime this week :)

**Comment by dpgaspar** [comment]
This is a very interesting proposal. I would like also to offer the alternative for non Rison parameters so that FAB and Swagger can play more nicely.

Maybe we can evaluate the option of using:
```
GET /articles HTTP/1.1
Accept: application/vnd.api+json
```
instead of using a config key

Any thoughts?

**Comment by zeusttu** [comment]
I like it! If the Accept-header is easily accessible in the parts of the code I have to modify then I will do it that way and forego the config option 👍

**Comment by zeusttu** [comment]
It seems I have to initialise separate Marshmallow schemas for JSON:API and non-JSON:API responses, which complicates things a bit because those schemas are initialised at server startup rather than on a request-by-request basis. This leaves us with three options:

* Initialise two schemas per model. This will increase memory usage and server startup time.
* Lazy-load schemas. This will decrease the server startup time but increase the first request handling time by the same amount. This solution also probably requires the most code.
* Fall back on my original configuration option idea, which would increase the configuration burden for someone writing a JSON:API with Flask-Appbuilder.

I think the impact of each would be small, but do you have a preference? I'm personally inclined to try the lazy loading method.

**Comment by zeusttu** [comment]
Also, I notice you prepend some local variables' names with underscores. Is there some convention to this? Do you have a document about the code style you use? If not then I will produce code that conforms to what little I managed to figure out about your code style (basically only that you use a 90-character line length) and conform to PEP-8 for the rest of it, and leave it up to you to further format my code according to your own standards.

**Comment by dpgaspar** [comment]
Ok, good point so let's:
```
Fall back on my original configuration option idea, which would increase the configuration burden for someone writing a JSON:API with Flask-Appbuilder.
```
No particular strict code style on the underscore prefices, I use flake8 and black so you should conform to that
