### ISSUE TITLE
Forms generated for boolean fields marked 'nullable=False' force user to check box

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#1175]
When creating a model and a CRUD view for it, the add/edit forms do not allow setting non-nullable boolean values to False. The checkbox is marked as a required input, even though an unchecked box represents a non-null value (False).

**Comment by CameronNemo** [comment]
bump

**Comment by CameronNemo** [comment]
bump

**Comment by NathanDalley** [comment]
This also happens in search filters:
![image](https://user-images.githubusercontent.com/5194565/82315589-d6ab6d80-9a0e-11ea-99f7-843bcaa4ff95.png)

**Comment by Th4nat0s** [comment]
Hi,

I got the same issue, i fixed it by allowing the field to be nullable in the data model.
    deprecated = Column(Boolean(), nullable=True, default=False)

And the db got all field set to 0 or 1

sqlite> select deprecated from attck_technic group by deprecated;
0
1

**Comment by CameronNemo** [comment]
@Th4nat0s that is not a suitable fix for my use cases. I want the data model to actual reflect the non-nullability requirement.
