### ISSUE TITLE
How to get Custom CSS file to work. 

### ISSUE THREAD

**Issue by nehatharani** [dpgaspar/Flask-AppBuilder#1176]
Hi, I am playing around a bit with Custom CSS and HTML. I have followed the documentation exactly But Custom CSS is not working at all. 

app: / 
---static/
---appbuilder/
---css
     ---my_css_file.css
      --- footer.html
     templates/
      --- mybase.html

mybase.html is exactly as [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quicktemplates/app/templates/mybase.html). Further I cannot see footer either. I have tried to delete, edit few properties on my_css_file.css nothing seems to affect the UI. 

Is there something I can do to make it work? There aren't any other sources to refer for UI. 

I have already refered this: #504 It didn't help much. 

Looking for suggestions! Thanks.

**Comment by trejas** [comment]
+1 on this question. Have the same structure, but am getting 404 errors on the boostrap-theme.css file.

**Comment by nehatharani** [comment]
Hey @trejas , So I am able to modify a few things  in terms of style like alignment, font-size etc by using:  
```html
<h1 style="font-size: 100px; text-align: center;">{{ _("Welcome") }}</h1>
```
I know not very efficient way. :( 

However, There is a slightly different problem now that I want to overwrite index.html. I lose all the formatting. 


my_index.html is: 

```
{% extends "appbuilder/base.html" %} {% block content %} {% block head_css %}
{{ super() }}
<link
  href="{{url_for('static',filename='appbuilder/css/themes/bootstrap-theme.css')}}"
  rel="stylesheet"
/>
{% endblock %}

<div class="jumbotron">
  <div class="container" style="text-align: center;">
    <h1 style="font-size: 100px; text-align: center;">{{ _("Welcome") }}</h1>
    <p style="align-content: center;">
      {{ _("Please Navigate to Data Entry section to add your data!") }}
    </p>

    <p>
      {{
        _(
          "If you're having troubles accessing the page, please contact our team at data@det.com"
        )
      }}
    </p>
  </div>
</div>
{% endblock %}

```
@dpgaspar 
The documentation is very limited when it comes to customizing. If there are any thoughts on why this is happening, please let me know. 

Thank you!
