### ISSUE TITLE
Throws error with SQLA 0.9.9::  from sqlalchemy.ext.declarative import as_declarative ImportError: cannot import name 'as_declarative'

### ISSUE THREAD

**Issue by walentas** [dpgaspar/Flask-AppBuilder#118]
Many thanks D!

Works fine dialing back to 0.9.8.

**Comment by davidism** [comment]
May be a regression in SQLAlchemy, reported here: https://bitbucket.org/zzzeek/sqlalchemy/issue/3328/as_declarative-has-moved

**Comment by dpgaspar** [comment]
Thanks, new version 1.3.3 is out, and corrects this issue
