### ISSUE TITLE
Multitenancy support for Flask-AppBuilder

### ISSUE THREAD

**Issue by zchencq** [dpgaspar/Flask-AppBuilder#1181]
Hi,
We're looking for the possibility of extending Flask-AppBuilder to be able to support multitenancy application. 
Think an application that provides access to multiple separate organizations and these organizations have each its own database . We want have sth inside FAB to be able to switch database sessions to specific "tenant". And each tenant also contains its own data for FAB security manager, which means tenant has its own users/roles/permissions.   

a similar example we found for Flask (https://smirnov-am.github.io/multitenancy-with-flask/)

We've already made some effort to extend FAB, but would like to see what's the easiest/best way to implement this.

@dpgaspar any advice or thought about this? thanks in advance.

**Comment by dpgaspar** [comment]
Very interested on this, I have some work around this also. Basically around SQLAlchemy events, was able to do it, but it's not easy to make it optional or has an addon

**Comment by zchencq** [comment]
@dpgaspar nice to hear that you are also interested:)
do you have some code to share to see how you implement with SQLAlchemy events? 

Basically we tried to use sessionmaker to bind tenant databases, in most cases it works fine. But when it touches FAB security manager, seems it keeps calling original FAB db session.

**Comment by phiea** [comment]
Let me elaborate on this further, as i am part of the we ;). Our current effort and the way we intend to push forward if we have to hack it in our selves is to hook into the appbuilder get_session function and return the tennant session which is assigned to the user. Our problem arises from the fact that the datamodel instances are hard to hack into while keeping appbuilder as is pristine. It's possible with inspect, but of coarse this is getting really ugly. The other way would be to extend all the security datamodels with the new get_session function but that would mean rewriting and doubling so much code that i do not see it as sustainable, and in that case we think it's probably better to make it a public extension.
To be frank, coding is not our primary occupation, we are network engineers, and want to use this framework as a fronted for network automation tasks. We have been hacking away at this for some time and came to the solution i described. But if you have have better way's of doing this, maybe we can help out with that instead.

**Comment by dpgaspar** [comment]
There are of course several ways of doing this, probably In general you have to add a `tenant_id` field on all your models, and on the following FAB models:
ab_user, ab_role etc... 

Your approach with `get_session` could be one way, can you share some code to make things clearer? 

My take with SQLAlchemy events is around implementing compile and filtering everything generically.

The most simple and least hackish could be implementing the models with the tenant field (on FAB also) and using `base_filters`
