### ISSUE TITLE
Create dynamic form fields based on request

### ISSUE THREAD

**Issue by giordyb** [dpgaspar/Flask-AppBuilder#1184]
### Environment

Flask-Appbuilder version: 2.2.0

pip freeze output:

### Describe the expected results

I am trying to create a dynamic form based on arguments passed on the request.
(ex. http://localhost:8080/rundagviewform/form?fields=field1%2C+field2%2C+field3)

What I would like is that every time the request is made a new form with different fields is created.

I have inherited from BaseFormView class to create the view and the form is create dynamically when this_form_get is called.

```python
def create_form_fields(fields):
    class RunDagForm(DynamicForm):
        pass
    for field in fields:
        setattr(RunDagForm, field, StringField(field))
    myform = RunDagForm()
    return myform
        



class RunDagViewForm(BaseFormView):

    @expose("/form", methods=["GET"])
    @has_access
    def this_form_get(self):
        fields = request.args.get("fields").split(',')
        print(fields)
        self.form = create_form_fields(fields)
        self._init_vars()
        form = self.form.refresh()
        self.form_get(form)
        widgets = self._get_edit_widget(form=form)
        self.update_redirect()
        return self.render_template(
            self.form_template,
            title=self.form_title,
            widgets=widgets,
            appbuilder=self.appbuilder,
        )
```

### Describe the actual results

The first time I call the form the correct fields get created correctly.
on the next requests it either:

- if I add a field it does not show the field even though the print statement shows that all the parameters are received

- if I remove a field it throws an error saying

```pytb
> jinja2.exceptions.UndefinedError: 'app.views.RunDagForm object' has no attribute ' field3'
```

Is there a way to implement this functionality? I cannot figure out a way to "refresh" the view so that the new form object is used instead of the first one.

thanks,

Giordano

**Comment by dpgaspar** [comment]
As an example take a look on how flask-appbuilder is creating it's forms dynamically: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/forms.py#L236

**Comment by giordyb** [comment]
Hi, thanks for the tip, based on your suggestion I tried the following code:

```
class XForm(BaseFormView):

    @expose("/xform", methods=["GET"])
    @has_access
    def this_form_get(self):
        fields = request.args.get("fields").split(',')
        form_props  = {"name": StringField("test",widget=BS3TextFieldWidget())}
        print(fields)
        for field in fields:
            form_props[field] = StringField(f"{field}",widget=BS3TextFieldWidget())
        print(form_props)
        form = type('DynamicForm', (DynamicForm,), form_props)
        self.form = form
        print(form)
        self._init_vars()
        form = self.form.refresh()
        self.form_get(form)
        widgets = self._get_edit_widget(form=form)
        self.update_redirect()
        return self.render_template(
            self.form_template,
            title=self.form_title,
            widgets=widgets,
            appbuilder=self.appbuilder,
        )

#appbuilder.add_view_no_menu(XForm)
appbuilder.add_view(XForm, "form test", icon="fa-table", category="Projects")
```

which i am calling with 
`http://localhost:5000/xform?fields=field1,field2`


on the first run after reloading the app it shows both fields, but if I call again with 
`http://localhost:5000/xform?fields=field1,field2,field3`

field3 doesn't get created, on the other hand if i call again with just 
`http://localhost:5000/xform?fields=field1`
I get 
`jinja2.exceptions.UndefinedError: 'app.views.DynamicForm object' has no attribute 'field2'`

I ended up doing this at a lower level by creating a plan wtform and defining my own template, but I would really like to use fab's higher level classes...

Thanks,
Giordano
