### ISSUE TITLE
The skeleton for fab-addon uses depreciated imports

### ISSUE THREAD

**Issue by lemeur** [dpgaspar/Flask-AppBuilder#1185]
### Environment

Flask-Appbuilder version :F.A.B Version: 2.1.1.

pip freeze output:
alembic==1.0.10
apispec==1.3.3
appdirs==1.4.3
attrs==19.1.0
Babel==2.6.0
cached-property==1.5.1
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.0.2
Flask-AppBuilder==2.1.1
Flask-Babel==0.12.2
Flask-BabelPkg==0.9.6
Flask-Ext==0.1
Flask-JWT-Extended==3.18.2
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
gunicorn==19.9.0
idna==2.8
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
ldap3==2.6
lxml==4.3.3
Mako==1.0.11
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.3
mysqlclient==1.4.2.post1
Pillow==6.0.0
prison==0.1.1
pyasn1==0.4.5
pyasn1-modules==0.2.5
PyJWT==1.7.1
pyrsistent==0.15.2
python-dateutil==2.8.0
python-editor==1.0.4
python-ldap==3.2.0
python3-openid==3.1.0
pytimeparse==1.1.8
pytz==2019.1
PyYAML==5.1
requests==2.21.0
requests-toolbelt==0.9.1
six==1.12.0
speaklater==1.3
SQLAlchemy==1.3.3
Unidecode==1.1.1
urllib3==1.24.3
Werkzeug==0.15.2
WTForms==2.2.1
zeep==3.3.1

### Describe the expected results

Tell us what should happen.

```python
flask fab create-addon
...
```
The addon skeleton uses imports from "flask.ext.appbuilder" instead of "flask_appbuilder", and "flask_babelpkg" instead of "flask_babel"

**Comment by dpgaspar** [comment]
Thank you for reporting this, it's fixed now:
https://github.com/dpgaspar/Flask-AppBuilder-Skeleton-AddOn/pull/3
