### ISSUE TITLE
SSO SAML - Not working with Github enterprise 

### ISSUE THREAD

**Issue by manoj-pathak** [dpgaspar/Flask-AppBuilder#1198]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.2.0

I have integrated the GitHub login with Apache Airflow using flash builder to get the RBAC functionality. I am able to login successfully with my personal Github account using ouath2 client flow.

But It does not work with GitHub Enterprise login.  My Github Enterprise has SSO enabled using Ping Federated. 

Can someone confirm, whether this framework provides support for SAML authentication flow? 

** Login Flow to reproduce the issue ** 
Airflow login page -> Login using Github -> redirected to PingFederated IDP server -> Authentication using org user -> successfully redirected back to GitHub with valid SAML token -> failed while redirecting to Airflow home page.

```

{cli.py:844} DEBUG - [4 / 4] sleeping for 30s starting doing a refresh...
{views.py:632} DEBUG - Authorized init
{client.py:661} DEBUG - Prepare oauth2 remote args "\x1b[1m{'code': 'xxxx', 'client_secret': 'xxxx', 'redirect_uri': 'http://xxxx:8080/oauth-authorized/github'}\x1b[0m"
{client.py:400} DEBUG - Request 'https://github.azc.ext.hp.com/login/oauth/access_token' with 'POST' method
{views.py:637} DEBUG - OAUTH Authorized resp: {'access_token': 'xxxx', 'scope': 'user', 'token_type': 'bearer'}
{manager.py:113} DEBUG - Token Get: ('xxxx', '')
{client.py:400} DEBUG - Request 'https://<my-url>>/user' with 'GET' method
{manager.py:452} DEBUG - User info from Github: b'\n<!DOCTYPE html>\n<html lang="en ...... </body>\n</html>\n'
{views.py:643} ERROR - Error returning OAuth user info: 'bytes' object has no attribute 'get'
{views.py:632} DEBUG - Authorized init
{app.py:1891} ERROR - Exception on /oauth-authorized/login [GET]
Traceback (most recent call last):
....
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 633, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'
```

Note: I have found a similar issue on StackOverflow.
https://stackoverflow.com/questions/58973077/cant-fetch-userinfo-after-authentication-flaskappbuilder-with-github-enterpri

**Comment by Chandan-Nayak** [comment]
Any idea on this ?

**Comment by pvcnt** [comment]
@Chandan-Nayak Did you find a workaround for this? I am having the same issue.

**Comment by Chandan-Nayak** [comment]
Nope I have not found anything on it. I was wondering how i am the only one stuck here :)

**Comment by pvcnt** [comment]
@Chandan-Nayak I ended up following steps described here: https://issues.apache.org/jira/browse/AIRFLOW-4470 Not sure which parameter exactly was required (I didn't take time to narrow it down), but it eventually worked correctly.
