### ISSUE TITLE
Info about redirect after registration

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1201]
Hello,

my version is 2.1.13 I would need to know where exactly is managed redirect after user registration (DB registration), actually it redirects to homepage.

Thank you for any help

**Comment by Ulixestoitaca** [comment]
I have used my own indexview and after registration the user is redirected to homepage instead of login page (as I think it is supposed to be)

**Comment by dpgaspar** [comment]
It's here: https://github.com/dpgaspar/Flask-AppBuilder/blob/786a90828d7add3842332526608843db92345ea8/flask_appbuilder/security/registerviews.py#L174
