### ISSUE TITLE
How to setup whitelists for the security manager and what do they do?

### ISSUE THREAD

**Issue by metaperl** [dpgaspar/Flask-AppBuilder#1206]
In [FAB Security Views](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L690) we can see some logic related to whitelists.

What we do not see in the Superset or FAB documentation is any mention on how to set them up and what effect they have.

Documentation on this would be useful.

**Comment by dpgaspar** [comment]
True, I write some docs around it

**Comment by hgrecco** [comment]
any example for this?

**Comment by dpgaspar** [comment]
See if this is enough to get you started:
https://github.com/apache/incubator-superset/blob/master/superset/views/dashboard/api.py#L135

**Comment by hgrecco** [comment]
Thanks a lot. I am having trouble to authenticate through oauth. I am getting "Invalid login. Please try again." The only message that I see in the log is "No whitelist for OAuth provider" (That is why I thought this issue was relevant)

**Comment by ironhacker** [comment]
Needed this feature in superset, which is built on fab.  Wherever you have access to the app instance, just append your whitelist.  Mine looks like this:

`app.appbuilder.sm.oauth_whitelists['azure'] = [re.compile(r'example.com', re.IGNORECASE), ]`

It expects a list of regular expressions, keyed by oauth provider.

Hope this helps.
