### ISSUE TITLE
How to show menu items just for logged-in users?

### ISSUE THREAD

**Issue by reffael** [dpgaspar/Flask-AppBuilder#121]
or in general how to control menu presentation by role?

**Comment by dpgaspar** [comment]
You have the following type of builtin permissions:

can list
can show
can add
can edit
can delete
can download
menu access on

The "menu access on" is the one you want, each permission is associated with an endpoint, action or menu item. Each user has a group of roles, and each role has a collection of permission/views.

On the demo take a look at the "Guest" role: http://flaskappbuilder.pythonanywhere.com/roles/list/

**Comment by reffael** [comment]
yes, my mistake. I was adding permissions to public user by mistake,  so even before login, the menu was visible.

**Comment by dpgaspar** [comment]
Everything ok then. I'm closing this one.
