### ISSUE TITLE
How to create a simple page from navigation tab without dropdown selection?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#122]
Examples show how to navigate from navigation tab, then select from dropdown and then navigating to new page from selected dropdown, but how to simply create a page when a navigation tab is clicked just to show a page without the dropdown selections, as in the admin or login page? As these are automatically generated for you?

**Comment by dpgaspar** [comment]
If i understand correctly you want to create a menu item without a dropdown, add your view like this:

     appbuilder.add_view(MyModelView, "My View")

Just omit the category parameter.

**Comment by dpgaspar** [comment]
I'll close this, if you want to, you can reopen it later.
