### ISSUE TITLE
Display Hyperlink Within List Table

### ISSUE THREAD

**Issue by jimmyhurff** [dpgaspar/Flask-AppBuilder#1220]
Is it possible to display a hyperlink within a list or show screen without the link's HTML being escaped?  That is, I have a model attribute which stores a hyperlink (https://abc.com/somelink.html) and I'd like for this link to be active as a list_column and show_column.  It looks as though FAB or Flask escape the HTML.  Is it possible to avoid the escaping?

**Comment by dpgaspar** [comment]
Hi @jimmyhurff,

One simple way to do this is by creating a specific property or method to escape the URL, take a look at: https://flask-appbuilder.readthedocs.io/en/latest/quickfiles.html#define-your-model-models-py

Hope this helps!

**Comment by jimmyhurff** [comment]
This worked perfectly!  Exactly what I was looking for.
