### ISSUE TITLE
Error extending User model

### ISSUE THREAD

**Issue by Barceloch** [dpgaspar/Flask-AppBuilder#1221]
Flask-Appbuilder version: 2.2.1
reading: https://flask-appbuilder.readthedocs.io/en/release-2.0.0/

----------------------------------
$ flask fab upgrade-db
Usage: flask fab [OPTIONS] COMMAND [ARGS]...

Error: No such command "upgrade-db".

-------------------------------------

**Comment by lpe234** [comment]
enter： flask fab ，then you can see all the COMMANDs.

**Comment by dpgaspar** [comment]
Hi @Barceloch the tittle of this issue is not very consistent with your question. If you need help please update
