### ISSUE TITLE
suggestion: Entity-Relationship or UML model of FAB?

### ISSUE THREAD

**Issue by metaperl** [dpgaspar/Flask-AppBuilder#1223]
In my work to customize Superset (a FAB app), I often wondered about the relationship between the FAB database entities. As such, it would be nice to use a tool (I used DataGrip) to document these relationships.

Alternatively, some people might prefer a UML model of the various classes in the FAB source code.

<img width="304" alt="db-er-diagram" src="https://user-images.githubusercontent.com/21293/71191668-c151cd80-223b-11ea-9e17-27f1899abe06.png">

**Comment by dpgaspar** [comment]
The docs already have some simple diagrams around classes and db entities. A PR that improves this is certainly welcome
