### ISSUE TITLE
Question: how to include robots.txt?

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1226]
Hello,

I wonder if is there  a method to add robots.txt to the root.
I have found in some oldest docs the html_extra_path variable and tried to add to config but actually does not work.
Anybody can help?

Thank you

**Comment by sdfreeman** [comment]
maybe something similar to this might work:
```python
@app.route('/favicon.ico')
def favicon():
    return send_from_directory(
        os.path.join(app.root_path, 'static'),
        'favicon.ico',
        mimetype='image/vnd.microsoft.icon'
    )
```

**Comment by Ulixestoitaca** [comment]
Thank you!
I thought a method was setup for this.
Anyway it is solved. Have an happy new year :)

**Comment by sn1p3r46** [comment]
Any hint on how? @Ulixestoitaca
