### ISSUE TITLE
How to stop update using functions : "pre_update"

### ISSUE THREAD

**Issue by Wirymen** [dpgaspar/Flask-AppBuilder#1228]
Hello,

I am new in flask app-builder and with my adventure in web site applications.
I was trying find  answer on my question:

"How i can abort edit/add rows using functions: Pre_update and Pre_add?"

in the official website i can read that it is possible:
"pre_update(item)
    Override this, this method is called before the update takes place. If an exception is raised by this method, the message is shown to the user and the update operation is aborted. Because of this behavior, it can be used as a way to implement more complex logic around updates. For instance allowing only the original creator of the object to update it.  "

I checked every issues closed and open, but i couldn't find answer on my question - but probably it is very simple how i can do it.

Thank you in advance

**Comment by dpgaspar** [comment]
Using the quick how from the examples:

```
class GroupModelView(ModelView):
    datamodel = SQLAInterface(ContactGroup)
    related_views = [ContactModelView]

    def pre_add(self, item):
        raise Exception("This is an error")

```

Will always error when adding new `groups`

**Comment by Wirymen** [comment]
Its working perfect!
Thank you very much for quickly answer,
( i knew that answer is so simple but unfortunately i cant find it)
