### ISSUE TITLE
Making an item in row clickable?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#123]
Say an item is clicked in row, how to take user to new page and populate it and showing more detailed view associated with that row?

Correction:

Expanded view of the selected row underneath clicked row with more details about that particular row, NOT navigating away from it.

**Comment by dpgaspar** [comment]
Hello,

On the model declare a new method named (as an example click_row) on you model.py:

from flask import Markup

    class MyModel(Model):
        id = Column(Integer, primary_key=True)
        name = Column(String(150), unique = True, nullable=False)
        name2 = Column(String(150), unique = True, nullable=False)
    
        def click_row(self):
            return Markup('<a href="' + url_for('MyModelView.show',pk=str(self.id))">self.name</a>')

Then on your view reference this method for display:

    class PersonModelView(MyModelView):
        datamodel = SQLAInterface(MyModel)
        list_columns = ['click_row', 'name','name2']




http://flask-appbuilder.readthedocs.org/en/latest/quickfiles.html#define-your-model-models-py

**Comment by scheung38** [comment]
I see, example from the quickimages example.

While trying to run the quickimages example, after login as admin, and trying to load an image, whether png, jpg or tif I get:

OSError
OSError: [Errno 13] Permission denied: '/Users/minminsanjose/PycharmProjects/Flask-AppBuilder/examples/quickimages/app/static/uploads'

**Comment by dpgaspar** [comment]
Exactly!

check if dir exists and permissions are sufficient for the webserver.

**Comment by scheung38** [comment]
This seems to have missing quotes?

        return Markup('<a href="' + url_for('MyModelView.show',pk=str(self.id))">self.name</a>')

**Comment by scheung38** [comment]
Corrected to:

return Markup('<a href="' + url_for('ServicesModelView.show', pk=str(self.id)) + ">self.name</a>")

But this seems to output in the row:

var modelActions = new AdminActions();

instead of the usual data defined in the Model?

**Comment by dpgaspar** [comment]
i'm sorry, but i'm not following...

**Comment by scheung38** [comment]
If copying and pasting the above the code has missing quotes

**Comment by dpgaspar** [comment]
You should also import url_for.

Markup('<a href="' + url_for('MyModelView.show',pk=str(self.id)) + '">self.name</a>')

**Comment by scheung38** [comment]
It is just my typo, if following your code it will not work for some reason

**Comment by dpgaspar** [comment]
Can you post your code, and/or the error message?

**Comment by scheung38** [comment]
On IE8 this is what is looks like and it is actually what I hope to replicate in other browsers 
![image](https://cloud.githubusercontent.com/assets/1273014/6850231/cfc940a6-d3cf-11e4-99a4-0e19069dcda8.jpg)

**Comment by dpgaspar** [comment]
Your probably posting on the wrong issue, MasterDetail one? please post the code, so i can help you.

Or you want the click row for the MasterDetail question?

**Comment by dpgaspar** [comment]
any news from this, can i close this one?

**Comment by scheung38** [comment]
No, still working on it

**Comment by jvinolas** [comment]
You can add html like this in you model to have a button in a row ( or
many):

def check(self):
if self.active==False:
return '<a class="list-group-item"  href="">Check</a>'
else:
return ''

And then call any page/populate anything as you can create your own href.

Don't know if this is what you need.
El dia 02/04/2015 15.33, "Sebastian M Cheung" <notifications@github.com> va
escriure:

**Comment by scheung38** [comment]
Thanks JVINOLAS I will look into it. It is similar to the dynamic dropdown list I was asking about related to #29 Dynamic field filter if you know how to it would be appreciated but if Daniel mentions that it is not supported then not sure how to override it

**Comment by jvinolas** [comment]
I updated #29... see if it helps.

2015-04-02 15:42 GMT+02:00 Sebastian M Cheung <notifications@github.com>:

**Comment by dpgaspar** [comment]
Did @jvinolas post helped? do you need any further help on this? I'm following the #29 problem, but let's keep it on #29 issue.

**Comment by scheung38** [comment]
I did see it but don't really understand it to implement it

**Comment by dpgaspar** [comment]
I'll close this, if you want to, you can reopen it later.
