### ISSUE TITLE
Readonly values in "Edit_fieldset"

### ISSUE THREAD

**Issue by Wirymen** [dpgaspar/Flask-AppBuilder#1230]
Hello,

I have one question about function "Edit_fieldset".
Is it possible through this function create readonly field?

Based on example from "demo", i have 2 fields - "Personal info" and "summary".
When i go to edit view - press button "edit" i have below screen:

![Git](https://user-images.githubusercontent.com/56919995/71713602-ab7f0380-2e0a-11ea-8c86-9a86514ff0a2.PNG)

I can modify in this view - Name, Gender, Contact Group, Address, Birthday  and so on,
What i have to do to allow change data only in fields "Summary"?

Code below:

    class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)

    label_columns = {'contact_group.name': 'Contacts Group'}
    list_columns = ['name', 'personal_celphone', 'birthday', 'contact_group.name']
    list_template = 'contact.html'
    base_order = ('name', 'asc')

    show_fieldsets = [
        ('Summary', {'fields': ['name', 'gender', 'contact_group']}),
        (
            'Personal Info',
            {'fields': ['address', 'birthday', 'personal_phone', 'personal_celphone'], 'expanded': False}),
    ]

    add_fieldsets = show_fieldsets

    edit_fieldsets = show_fieldsets`

Thank you in advance

**Comment by kurtforrester** [comment]
https://flask-appbuilder.readthedocs.io/en/latest/advanced.html#forms-readonly-fields
