### ISSUE TITLE
Connect user roles with specific values of a variable

### ISSUE THREAD

**Issue by bd317** [dpgaspar/Flask-AppBuilder#1240]
Hello,

i am not sure, where to address a simply question, so I will try it here:

I have a database which contains a column named "department". Every row contains a 1 or 2 for the different departments. I want to connect it with the user roles. So a user from department 1 should just see the data with "1" in column "department". Can someone help how to realize it? I didn`t find a solution to connect user roles with a specific value of a variable.

Best wishes

**Comment by dpgaspar** [comment]
Just to clarify, your mapping roles to departments?

I way of doing this, would be to have a model for deparments and then making a N to N relation from the models you want to "protect"
