### ISSUE TITLE
Sample for after form post action computation (i.e. computed field)

### ISSUE THREAD

**Issue by Kkeller83** [dpgaspar/Flask-AppBuilder#1241]
Would you have an example that shows how I can access data from a post request from the out of the box crud forms and then change the value or add data to the post request before writing it back to the database?

Sample would be adding the username of the user who send the form before saving it to the database. 

Or computing 2 values from the post request and saving the result to the database as well. 

In generally I would be curious how we can do computed fields in the standard crud forms?

Thank you! 

Kevin

**Comment by CameronNemo** [comment]
>Sample would be adding the username of the user who send the form before saving it to the database.

This is best handled using the `AuditMixin` please see the docs for more information.

>Or computing 2 values from the post request and saving the result to the database as well.

This might be possible with [post_update](https://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.baseviews.BaseCRUDView.post_update), but I am not sure.
