### ISSUE TITLE
glyphicons-halflings-regular.woff2 missing

### ISSUE THREAD

**Issue by amaline** [dpgaspar/Flask-AppBuilder#1246]
glyphicons-halflings-regular.woff2 missing (woff version exists) in master/flask_appbuilder/static/appbuilder/fonts but referred to in the bootstrap.min.css causing 404 error

**Comment by feluelle** [comment]
My current workaround is to download it from `https://github.com/twbs/bootstrap-sass/raw/master/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2` and put it in `/usr/local/lib/python3.7/site-packages/flask_appbuilder/static/appbuilder/fonts/`

I added this to my Dockerfile:
```
    && wget -P /usr/local/lib/python3.7/site-packages/flask_appbuilder/static/appbuilder/fonts/ \
        https://github.com/twbs/bootstrap-sass/raw/master/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 \
```

**Comment by feluelle** [comment]
@dpgaspar
