### ISSUE TITLE
How to filter a model

### ISSUE THREAD

**Issue by jimmyhurff** [dpgaspar/Flask-AppBuilder#1247]
Apologies in advance if this is the wrong place for this sort of question.  What is the proper way to filter the list of model classes below called newtonproductcost?  I only want the children with the same product_id.  Can I apply a filter to the relationship query so that I only get costs with the product_id?

Thanks in advance.

```
class Newtonproductpo(Model):
    po_id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, ForeignKey(Newtonproduct.product_id), nullable=False)
    newtonproduct = relationship(Newtonproduct)
    cost_id = Column(Integer, ForeignKey(Newtonproductcost.cost_id), nullable=False)
    newtonproductcost = relationship(Newtonproductcost)
```

**Comment by jimmyhurff** [comment]
My desire if for newproductcost list to only be for the parent product_id.

for example, is there a way to use relationship() with filter criteria:

`newtonproductcost = relationship(Newtonproductcost, "<add where filter product_id = product_id>")
`

**Comment by ThomasP0815** [comment]
Normally filtering is done in a view.
Have a look at the demo site http://flaskappbuilder.pythonanywhere.com/
login: guest
pw: welcome

Contact -> List Groups
Contact -> Master Detail Groups
