### ISSUE TITLE
css not picked up in cell row

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#125]
I have placed in static/css/mycss.css file:

.OK{
    background-color: lightgreen;
}

.Alert{
    background-color: #ff6a6a;
}

mybase.html:

% extends 'appbuilder/baselayout.html' %}

{% block head_css %}
    {{ super() }}
    <script src="{{url_for('static', filename='css/your_css_file.css')}}"></script>
{% endblock %}

{% block head_js %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/your_js_file.js')}}"></script>
{% endblock %}

{% block tail_js %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/your_js_file.js')}}"></script>
{% endblock %}

But not sure how to check and change background row cell to this background-color if row cell text is 'OK' or other color when text string criteria is matched?

**Comment by dpgaspar** [comment]
I'll close this, if you want to, you can reopen it later.
