### ISSUE TITLE
edit_columns does not accept a function decorated with @renders

### ISSUE THREAD

**Issue by tagwato** [dpgaspar/Flask-AppBuilder#1253]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment
Miniconda on Windows 10, python 3.8.0

**Flask-Appbuilder version:**
2.2.1

**pip freeze output:**
apispec==1.3.3
attrs==19.3.0
Babel==2.7.0
certifi==2019.11.28
Click==7.0
colorama==0.4.3
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.2.1
Flask-Babel==0.12.2
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10.3
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
Pillow==7.0.0
prison==0.1.2
PyJWT==1.7.1
pyrsistent==0.15.6
python-dateutil==2.8.1
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.2
six==1.13.0
SQLAlchemy==1.3.12
SQLAlchemy-Utils==0.36.0
Werkzeug==0.16.0
wincertstore==0.2
WTForms==2.2.1

### Describe the expected results

According to https://flask-appbuilder.readthedocs.io/en/latest/api.html#module-flask.ext.appbuilder.models.decorators, it is possible to decorate a function to show a formatted output of a field.  As the example shows, the function my_custom() can be used in the list_columns property of a ModelView :

```
class MyModel(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique = True, nullable=False)
    custom = Column(Integer(20))

    @renders('custom')
    def my_custom(self):
        # will render this columns as bold on ListWidget
        return Markup('<b>' + custom + '</b>')

class MyModelView(ModelView):
    datamodel = SQLAInterface(MyTable)
    list_columns = ['name', 'my_custom']
```
Well, we need to use this type of decorator to format the output when **editing** (not listing) a column.

So, I've tried to put a renders function inside the "**edit_columns**" property of the ModelView.
But, it raises an error when starting the app. 
Note: Didn't test what happens when the decorated function is used inside "add_columns" or "show_columns" properties, but the **expected** behavior would be the same: well formatted columns/fields being presented.   

Below the changes I've made in the F.A.B "employees" example, so I could test this feature. 

```python
Paste a minimal example that causes the problem.

#models.py
class Employee(Model):
    ...
    @renders('employee_number')
    def renders_employee_number(self):   # <<-- this is a render function, to be used in list/edit_columns in views.py
        return Markup('<font color="red">' + str(self.employee_number) + '</font>')

#views.py
class EmployeeView(ModelView):
    ...
    #CHANGED: employee_number >>> renders_employee_number;  Ok, it works
    #list_columns = ["full_name", "department.name", "employee_number"]
    list_columns = ["full_name", "department.name", "renders_employee_number"]

    #TRYING TO USE: employee_number >>> renders_employee_number;  it's NOT working !!! (error when starting app)
    edit_columns = ['full_name', 'address', 'fiscal_number', 'renders_employee_number', 'department', 'function', 'begin_date', 'end_date']
	
```

### Describe the actual results
When starting the app, an error is raised. We know it's caused by the "renders_employee_number" function we put inside the edit_columns property, because the error is supressed when that line of code is commented.

```pytb

  File "...........\app\views.py", line 63, in <module>
    appbuilder.add_view(
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\base.py", line 421, in add_view
    baseview = self._check_and_init(baseview)
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\base.py", line 354, in _check_and_init
    baseview = baseview()
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\views.py", line 502, in __init__
    super(ModelView, self).__init__(**kwargs)
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\baseviews.py", line 751, in __init__
    super(BaseCRUDView, self).__init__(**kwargs)
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\baseviews.py", line 487, in __init__
    self._init_forms()
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\baseviews.py", line 785, in _init_forms
    self.edit_form = conv.create_form(
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\forms.py", line 273, in create_form
    self._convert_col(col_name, self._get_label(col_name, label_columns),
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\forms.py", line 228, in _convert_col
    return self._convert_simple(
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\forms.py", line 194, in _convert_simple
    default_value = self.datamodel.get_col_default(col_name)
  File "c:\miniconda3_4_6_14\envs\fab\lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 513, in get_col_default
    default = getattr(self.list_columns[col_name], "default", None)
KeyError: 'renders_employee_number'
```

### Steps to reproduce
Change the "employees" example as shown above and run it.
Comment the line starting with edit_columns and the error is supressed.

PS:
Although the code above is only a test, we think the correction of this problem would be a big step towards a large-scale adoption of  F.A.B, because users expect that fields are well formatted when presented or imputed, for instance currency values.

Thanks!

**Comment by CameronNemo** [comment]
FWIW I have found that the `renders` decorator is an anti-pattern. You want to keep as much of your view/formatting logic outside of the models as possible for purposes of maintainability and separation of responsibilities. [formatters_columns](https://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.baseviews.BaseCRUDView.formatters_columns) is much nicer to work with.

**Comment by tagwato** [comment]
> FWIW I have found that the `renders` decorator is an anti-pattern. You want to keep as much of your view/formatting logic outside of the models as possible for purposes of maintainability and separation of responsibilities. [formatters_columns](https://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.baseviews.BaseCRUDView.formatters_columns) is much nicer to work with.


Totally agree with you, @CameronNemo. 

I was testing "@renders" as a workaround to set input masks and output formats for the whole app (a "unified way").
But  "@renders" can't do that.
Neither can "formatters_columns".
These are solutions only for the List/Show views, as we can conclude after reading the FAB documentation more carefully.
So, this is not really a issue or "bug", it's just the way F.A.B works.

That said, I think F.A.B. still needs a"unified way" to define masks/formats for the fields/columns, one that works not only for List/Show views, but also for the Add/Edit view (forms).

For anyone interested, I think I have found an initial solution for this problem, as described in the second comment of this issue: #1224
