### ISSUE TITLE
Redirection to oauth-authorized/login instead of /login

### ISSUE THREAD

**Issue by ayush-san** [dpgaspar/Flask-AppBuilder#1254]
I think there is a bug in redirect logic of views.py of Flask-Appbuilder security package.

### Environment

Flask-Appbuilder version: 2.2.1

pip freeze output:

```
Flask==1.1.1
Flask-Admin==1.5.4
Flask-AppBuilder==2.2.1
Flask-Babel==0.12.2
Flask-Bcrypt==0.7.1
Flask-Caching==1.3.3
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OAuthlib==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-swagger==0.2.13
Flask-WTF==0.14.2
```

### Describe the expected results

I am trying to run apache airflow with RBAC in ECS using the v1.10.5 version of [apache-airflow](https://github.com/apache/airflow/tree/1.10.5) using [my fork](https://github.com/ayush-san/airflow/tree/zmaster). 

In airflow, we have to use the `webserver_config.py` file to define the authentication method. I have made a mistake in my whitelist param while enabling google auth. So in [oauth_authorized method of class AuthOAuthView ](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L701), it should have redirected me to `https://your-airflow.domain.com/login` and displayed a flash warning of `You are not authorized` 

### Describe the actual results

Since my webserver_config has whitelisted a wrong domain I was getting the flash message of You are not authorized and was redirected to https://your-airflow.domain.com/oauth-authorized/login instead of https://your-airflow.domain.com/login

![image](https://user-images.githubusercontent.com/57655135/73173991-b177b400-412c-11ea-8274-1bb43a369d81.png)

### Steps to reproduce
Give the wrong domain in whitelist param of google OAuth and try to log in.

**Comment by kdwyer** [comment]
Similar to #1186?
