### ISSUE TITLE
Flask App Builder Login Form converts usernames to lower case

### ISSUE THREAD

**Issue by gaurav1999** [dpgaspar/Flask-AppBuilder#1262]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.2.2

pip freeze output:
```
alembic==1.3.2
amqp==2.5.2
-e git+https://github.com/apache/incubator-superset/@a4ed0758b0f04d6eb4d5da4d81867fb38c1e22ca#egg=apache_superset
apispec==1.3.3
appdirs==1.4.3
aspy.yaml==1.3.0
astroid==1.6.6
attrs==19.3.0
Babel==2.8.0
backcall==0.1.0
backoff==1.10.0
billiard==3.6.1.0
black==19.3b0
bleach==3.1.0
celery==4.4.0
certifi==2019.11.28
cffi==1.13.2
cfgv==2.0.1
chardet==3.0.4
click==6.7
colorama==0.4.3
console-log==0.2.10
contextlib2==0.6.0.post1
coverage==4.5.3
croniter==0.3.31
cryptography==2.8
decorator==4.4.1
defusedxml==0.6.0
filelock==3.0.12
Flask==1.1.1
Flask-AppBuilder==2.2.2
Flask-Babel==0.12.2
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-Cors==3.0.7
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-talisman==0.7.0
Flask-Testing==0.7.1
Flask-WTF==0.14.2
future==0.18.2
geographiclib==1.50
geopy==1.20.0
gevent==1.4.0
gevent-websocket==0.10.1
greenlet==0.4.15
gunicorn==20.0.4
humanize==0.5.1
identify==1.4.11
idna==2.8
importlib-metadata==1.4.0
ipdb==0.12
ipython==7.11.1
ipython-genutils==0.2.0
isodate==0.6.0
isort==4.3.21
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.10.3
jsonschema==3.2.0
kombu==4.6.7
lazy-object-proxy==1.4.3
Mako==1.1.1
Markdown==3.1.1
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
mccabe==0.6.1
more-itertools==8.1.0
msgpack==0.6.2
mypy==0.670
mypy-extensions==0.4.3
nodeenv==1.3.4
nose==1.3.7
numpy==1.18.1
pandas==0.25.3
parsedatetime==2.5
parso==0.6.0
pathlib2==2.3.5
pexpect==4.8.0
pickleshare==0.7.5
pip-tools==3.7.0
pluggy==0.13.1
polyline==1.4.0
pre-commit==1.17.0
prison==0.1.2
prompt-toolkit==3.0.3
psycopg2-binary==2.7.5
ptyprocess==0.6.0
py==1.8.1
pyarrow==0.15.1
pycodestyle==2.5.0
pycparser==2.19
pydruid==0.5.7
Pygments==2.5.2
PyHive==0.6.1
PyJWT==1.7.1
pylint==1.9.2
pyrsistent==0.15.7
python-dateutil==2.8.1
python-dotenv==0.10.5
python-editor==1.0.4
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.3
redis==3.2.1
requests==2.22.0
retry==0.9.2
selenium==3.141.0
simplejson==3.17.0
six==1.14.0
SQLAlchemy==1.3.12
SQLAlchemy-Utils==0.36.1
sqlparse==0.3.0
statsd==3.3.0
toml==0.10.0
tox==3.11.1
traitlets==4.3.3
typed-ast==1.3.5
urllib3==1.25.8
vine==1.3.0
virtualenv==16.7.9
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.11.2
wsgigzip==0.1.4
WTForms==2.2.1
WTForms-JSON==0.3.3
zipp==2.0.0
```
### Describe the expected results
Apache Superset is one of the most popular applications built on top of FAB, I discovered that in Login forms which Apache Superset simply imports from FAB have a vulnerability.
The login form probably converts the username to lowercase and it gets coincides with another account if it exists.

Login form should read the provided username irrespective of casing.

### Steps to reproduce
1. Create a user with user name "hello" [Role: Public]
2. Set it's password "test123"
3. Create another user with user name "Hello"  [Role: Alpha]
4. Set it's password "test123"

I tried to distinguish by roles, I set one user's role as "Public" and another's "Alpha", now when I login with Alpha user which is "Hello" it gets me to the user "hello" which is a public user and that's a problem because system probably lower cased the username  and incidentally their passwords were same so voila you get in to other user's account.

**Comment by gaurav1999** [comment]
I wish to make this issue private because it's related to security, but not sure where is the option to do so :-/

**Comment by dpgaspar** [comment]
Hi @gaurav1999,

Thank you for reporting. FAB does not convert usernames to lower case, this is related with backend configuration, it happens on SQLLite but not on PG or MySQL. Can you please confirm this is the backend your using (SQLLite) ?

**Comment by gaurav1999** [comment]
Yeah, seems like you are right, this is happening to me in SQLLite at the moment, not sure about MySql and PG.

**Comment by dpgaspar** [comment]
No actually the behavior is not correct, I'll make a fix ASAP

**Comment by gaurav1999** [comment]
Hi Daniel,

I was wondering if it's fixed at the moment, or will take a bit more time ?
Would like to see the link of the commit if it's possible.
Thanks a lot for your consideration.

Best regards
Gaurav
