### ISSUE TITLE
Running mongoimages examples return Connection refused

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#127]
mongoimages $ fabmanager create-admin
Username [admin]: 
User first name [admin]: 
User last name [user]: 
Email [admin@fab.org]: 
Password: 
Repeat for confirmation: 
Was unable to import app Error: Cannot connect to database default :
[Errno 61] Connection refused

**Comment by dpgaspar** [comment]
is your MongoDB server up?
