### ISSUE TITLE
New release of werkzeug 1.0.0 breaks flask-appbuilder

### ISSUE THREAD

**Issue by stuartz** [dpgaspar/Flask-AppBuilder#1274]
Not exactly an issue with flask-appbuilder itself as flask recommends pinning dependencies.  However, the latest release removes deprecated modules and causes a new unpinned install of flask-appbuilder to fail.

Solution is to pin Werkzeug in the requirements:
Werkzeug>=0.15.1,<=0.16.1

**Comment by dpgaspar** [comment]
This should be fixed on the latest release 2.2.3

**Comment by stuartz** [comment]
Still had a  problem with 2.2.3.
Ended up being on my end.  I was using a proxy to serve and using ProxyFix in my app/\__init\__.py

Changed from:
`from werkzeug.contrib.fixers import ProxyFix`

Changed to:
`from werkzeug.middleware.proxy_fix import ProxyFix`

...
`app = Flask(__name__)`
`app.wsgi_app = ProxyFix(app.wsgi_app)`
