### ISSUE TITLE
mongoimages example: mongoengine.errors.ValidationError ValidationError: 1 is not a valid ObjectId

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#128]
after starting mongod 

and python testdata.py

fabmanager run 

I get back:

mongoengine.errors.ValidationError
ValidationError: 1 is not a valid ObjectId

**Comment by dpgaspar** [comment]
You have to cleanup your cookies from the browser (hapens to me too), the user.id from admin is still there with value 1.
