### ISSUE TITLE
flask fab `No such command "fab".`

### ISSUE THREAD

**Issue by iairsalem** [dpgaspar/Flask-AppBuilder#1285]
EDIT: my issue was related to how I have python3 installed (using pyenv) on my mac. when I was running `flask <anything>` it was not using the venv i was in. 
SOLUTION for me: uninstall that python and the bashrc, bash_profile files (that pointed to pyenv), installing the latest python3, creating venv with python 3, and then follow fab instructions  

---
I tried flask fab create-app following the instructions in the docs. everything went fine.
a few days later (today) I try the same, but with different results. `flask fab create-app` doesn't work.
on the other hand, fabmanager works, and it's supposed to be deprecated.

### Environment

Flask-Appbuilder version:
Flask-AppBuilder==2.2.3
pip freeze output:
apispec==1.3.3
attrs==19.3.0
Babel==2.8.0
Click==7.0
colorama==0.4.3
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.2.3
Flask-Babel==1.0.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.3
itsdangerous==1.1.0
Jinja2==2.11.1
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.22.2
prison==0.1.2
PyJWT==1.7.1
pyrsistent==0.15.7
python-dateutil==2.8.1
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.3
six==1.14.0
SQLAlchemy==1.3.13
SQLAlchemy-Utils==0.36.1
Werkzeug==1.0.0
WTForms==2.2.1

**Comment by iairsalem** [comment]
This might be entirely related to my setup. Apparently the flask command is running from outside the virtualenv. I leave this here for future reference.

**Comment by dpgaspar** [comment]
Yes, probably related to your setup. Thank you @iairsalem
