### ISSUE TITLE
How to override default index.html page

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#129]
in __init__.py

appbuilder = AppBuilder(app, db.session, menu=Menu(reverse=False), indexview=MyIndexView)
from app import views, models
from views import MyIndexView

in views.py:

class MyIndexView(IndexView):
    index_template = 'index.html'

in app/templates/index.html:

{% extends "appbuilder/base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>{{("My App on FAB")}}</h1>
        <p>{{("My text)}}</p>
    </div>
</div>
{% endblock %}

But I get:

NameError: name 'MyIndexView' is not defined?

**Comment by dpgaspar** [comment]
Your referencing MyIndexView before importing.

You should put MyIndexView on a different file, say index.py.

The on \__init__.py

    from index import MyIndexView
    .
    .
    .   
    
    appbuilder = AppBuilder(app, db.session, menu=Menu(reverse=False), indexview=MyIndexView)
    from app import views, models
    from views import MyIndexView

**Comment by scheung38** [comment]
from index import MyIndexView
: 
: 
from views import MyIndexView

is there no conflict here?

**Comment by dpgaspar** [comment]
Yes, your right, i've updated it.

**Comment by scheung38** [comment]
Thanks, and could you pass a parameter to index.html, say <p>"Location: {{location}}"</p>, where location is determined by some geolocation or IP address so that 

Location: London
Location: Hong Kong 
etc

**Comment by dpgaspar** [comment]
You will have to override the index method, take a look at the source code:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/views.py#L15

    @expose('/')
    def index(self):
        self.update_redirect()
        location = 'London'
        return self.render_template(self.index_template, location=location, appbuilder=self.appbuilder)

**Comment by scheung38** [comment]
But @expose is from BaseView? Whereas now we are using IndexView?

**Comment by scheung38** [comment]
Thanks it works but css theme doesn't get picked up.

index.html:

{% extends "appbuilder/base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>{{_("MyWeb UI")}}</h1>
        <p>Location : {{_(location)}}</p>
    </div>
</div>

<div class="container">
    <table>
        <tr>
            <th>Test1</th>
            <th>Test2</th>
            <th>Test3</th>
        </tr>
        <tr>
            <td class="OK">Yes</td>
            <td>Fail</td>
            <td>No</td>
        </tr>
    </table>
</div>
{% endblock %}


app/static/css/your_css_file.css:

.OK{
    background-color: lightgreen;
}


init.py:

appbuilder = AppBuilder(app, db.session, menu=Menu(reverse=False), indexview=MyIndexView, base_template='mybase.html')


But background never changes to lightgreen?
