### ISSUE TITLE
adding AUTH_LDAP_SEARCH_FILTER breaks login. Does not allow any logins

### ISSUE THREAD

**Issue by jhwal47** [dpgaspar/Flask-AppBuilder#1290]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: Flask-AppBuilder              1.13.0 

I have LDAP working with RBAC in airflow 1.10.7, but when I try to add 
the AUTH_LDAP_SEARCH_FILTER = (memeberOf=cn=mygroup,ou=Users,dc=myco,dc=com)

No one is able to login

### Describe the expected results

I want to limit logins to the AD group mygroup

I'd actually like to only allow 2 groups access with 
(|(memberOf=cn=mygroup1)(memberOf=cn=mygroup2))

**Comment by mikle7771** [comment]
I have the same problem. Also, during registration, the user is not assigned mail from LDAP. I tried doing `search_s ("dc = example, dc = com", ldap.SCOPE_SUBTREE, 'uid = user'))` from the python console and there is no "mail" and "member0f" in the output, but there is other information. But if I enter `bind_s ("user", "pass")`, then after the search it gives info by mail and memberOf. It feels like the search is performed before the login AUTH_LDAP_BIND_USER upon login.
