### ISSUE TITLE
Custom Routes

### ISSUE THREAD

**Issue by lu-zero** [dpgaspar/Flask-AppBuilder#130]
I'm considering moving [plaid](http://github.com/lu-zero/plaid) to AppBuilder, but one of the first blocks is that I couldn't find how to customize the routes. Since plaid has to be route-compatible with patchwork, I need to support routes such as `project/<project>/patches/`.

So far the AppBuilder CRUD systems seems the best I found for Flask, but I couldn't figure out this detail.

**Comment by dpgaspar** [comment]
Seems like a good idea. But can you be more specific and detailed about your question?

**Comment by lu-zero** [comment]
I have something like that for all the compatible paths.

```
bp = Blueprint('project', __name__, url_prefix='/project/<project_name>')


@bp.url_value_preprocessor
def get_project(endpoint, values):
    project_name = values.pop('project_name')
    g.project = Project.query.filter_by(name=project_name).first_or_404()


@bp.url_defaults
def add_project(endpoint, values):
    if 'project_name' in values or not g.project:
        return
    values['project_name'] = g.project.name


@bp.route('/')
def index():
    return render_template('project.html',
                           title="Project %s" % g.project.name)

@bp.route('/patches/')
@bp.route('/patches/<group>')
def patches(group=None):
    if group:
        patches = getattr(g.project, group+"_patches", [])
    else:
        group = 'patches'
        patches = g.project.patches
    return render_template('project_list.html',
                           title="Project %s" % g.project.name,
                           patches=patches,
                           group=group)
```

And here I'd like to use your CRUD to list patches, either grouped by a certain category (e.g. all the stale patches, all the unreviewed patches) or providing a breakout view with the first 10 of each category.

All of it seems easy with your crud, beside the fact it doesn't seem to take a query object easily.

**Comment by dpgaspar** [comment]
Ok, i'll make some tests to see if this is already possible, or if we need a new feature.

**Comment by dpgaspar** [comment]
After some tests, I have reached some conclusions and some doubts.

1:
You can achieve this with the current version using a global url_defaults and url_value_proprocessor, something like the following (views.py):

    @app.url_defaults
    def add_language_code(endpoint, values):
        print "ADD " + endpoint + " " + str(values)
        if (endpoint == 'YourView.somemethod'):
            if 'lang_code' in g: values.setdefault('lang_code', g.project.name)
        return values

    @app.url_value_preprocessor
    def pull_lang_code(endpoint, values):
        print "PRE " + endpoint + " " + str(values)
        if (endpoint == 'YourView.somemethod'):
            g.project.name = values.pop('project.name')

This is not exactly correct for your example, but i think you get the idea.

2:
I can include a new property to all views (BaseView) for url_defaults and url_value_proprocessor.

Yet ! there is one "problem", how do you imagine the menu construction for this kind of views? 
The menu is constructed using url_for(Endpoint.default_view), but before a real request to /project/<project_name>/list there is no way **url_for** can figure out the URL for list.

Are you planning a different UI approach on this?

**Comment by lu-zero** [comment]
That is yet another problem, plaid has a breadcrumb navigation system:

![screenshot-localhost 5000 2015-03-27 16-10-10](https://cloud.githubusercontent.com/assets/239012/6870358/d646438a-d49b-11e4-91f6-6e2c2c758ad0.png)
![screenshot-localhost 5000 2015-03-27 16-09-41](https://cloud.githubusercontent.com/assets/239012/6870359/d64b2c74-d49b-11e4-85bd-a51b85b910c0.png)
![screenshot-localhost 5000 2015-03-27 16-09-07](https://cloud.githubusercontent.com/assets/239012/6870360/d64fbf50-d49b-11e4-908b-5584dcf7183c.png)
![screenshot-localhost 5000 2015-03-27 16-08-36](https://cloud.githubusercontent.com/assets/239012/6870361/d64ff22c-d49b-11e4-939d-aa634aefeeb0.png)
![screenshot-localhost 5000 2015-03-27 16-07-51](https://cloud.githubusercontent.com/assets/239012/6870362/d6555f00-d49b-11e4-9893-41fab28bf61e.png)

And I'd like to keep it.

I really like your CRUD system and your user management approach but I would change completely the menu system and other components.

**Comment by dpgaspar** [comment]
plaid looks great! I'll take a look at your source, you've probably got some nice ideas.

What's your plan on integrating F.A.B. on it? Any initial ideas?

**Comment by lu-zero** [comment]
F.A.B has two great features I like a lot:
- Quite nice user support
- Amazingly nice CRUD and tabular-view for data (pretty unique in the Flask world).

As I said the problems I have is that plaid is implemented as blueprints with extensive use of the preprocessor feature to be compatible with [patchwork](http://jk.ozlabs.org/projects/patchwork/).

Since should be possible to register the preprocessor trick, now I'm wondering how hard would to change a little the CRUD system so it takes the query generated by the preprocessor trick and appends to it the rest of the search query.

Then I need to move the User model to F.A.B as well (Github-Flask or similar would work?)

With that done I'd need to change the template to support the breadcrumb system.

Then eventually I'll have to migrate the command line application to click (it does act as mail-filter and git hook).

I found the master-detail system really interesting and probably I'll look on how to leverage it later.

**Comment by dpgaspar** [comment]
Thanks!!

It would be great if you could pull this one off (it's a lot of work). You will have to extend the framework or fight it to get the jog done.

I agree, first test the preprocessor "trick", and test the base CRUD, don't register your view with **add_view** because **url_for** will break when you do, register it with **add_view_no_menu**, then test it using direct URL or something.

The query with **project_name** should be no problem, the problem will come with the UI navigation system. There is no breadcrumb on F.A.B. maybe we could add one?

Your auth is based on OAuth? this is not supported yet, but it's planned to be.

If your willing to do it, i'm willing to help.

**Comment by dpgaspar** [comment]
Any luck on this?

**Comment by lu-zero** [comment]
Not yet, changing the model is quite a bit of effort I discovered ^^ Might be useful to keep your abstraction compatible with the Flask-SQLAlchemy. I used the `query` shortcut pretty much every where.

**Comment by dpgaspar** [comment]
I see, the "problem" is related to this #93

**Comment by dpgaspar** [comment]
I'll close this one, if you want to you can repopen it later.
