### ISSUE TITLE
OpenApi endpoint doesn't show one to many relation as a list

### ISSUE THREAD

**Issue by ThomasP0815** [dpgaspar/Flask-AppBuilder#1304]
![image](https://user-images.githubusercontent.com/30863072/75790301-493f7200-5d6b-11ea-9f41-c4fda2adf7ef.png)

![image](https://user-images.githubusercontent.com/30863072/75791050-4b560080-5d6c-11ea-997c-61d26b0baafd.png)

**Comment by ThomasP0815** [comment]
Debugging the framework I found the reason for the problem.
Following change solved my problem:

![image](https://user-images.githubusercontent.com/30863072/75874964-16e94f80-5e13-11ea-8fe4-04e75fed0fb8.png)

But I don't know if there are some side effects!

**Comment by dpgaspar** [comment]
Seems reasonable, open a PR with it and we can work from there

**Comment by ThomasP0815** [comment]
#1305
