### ISSUE TITLE
Any AuditMixin working examples?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#131]
Thanks

**Comment by dpgaspar** [comment]
Nop, i'll add one to the docs ASAP.

But you just have to:

``` python

flask.ext.appbuilder.models.mixins import AuditMixin

class MyModelView(ModelView, AuditMixin):
     datamodel = SQLAInterface(MyModel)
```

Remember this is not a complete example, just general guideline.

**Comment by dpgaspar** [comment]
Just updated the docs on github, this will be online, probably today, planning new minor release today.

**Comment by scheung38** [comment]
Thanks for that

**Comment by scheung38** [comment]
Thanks

**Comment by dpgaspar** [comment]
Hello,

First, thank you for reporting this.

Please change **BaseMixin** and **Base** to **Model**, example

``` python
from sqlalchemy import Column, Integer, String, ForeignKey, Date
from sqlalchemy.orm import relationship
from flask.ext.appbuilder import Model

class City(AuditMixin, Model):
     id = Column(Integer, primary_key=True)
     name = Column(String(150), unique=True, nullable=False)
     region_id = Column(Integer, ForeignKey('region.id'), nullable=False)
     region = relationship("Region")
     country_id = Column(Integer, ForeignKey('country.id'), nullable=False)
     country = relationship("Country")
```
Then on the view limit your columns for Add and Edit use **add_columns** and **edit_columns**. You don't want to update these values, the framework does this for you.

Take a look at the example: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickfiles/app/views.py

**Comment by scheung38** [comment]
Could you reduce the created_on:

2015-04-09 15:22:46.489098 to 
2015-04-09 15:22:46

**Comment by dpgaspar** [comment]
Updated the docs with a simple example:

http://flask-appbuilder.readthedocs.org/en/latest/security.html#auditing

I'll look into your request ASAP

**Comment by dpgaspar** [comment]
You can now user 'formatters_columns'. Closing, feel free to reopen if it's still relevant
