### ISSUE TITLE
[ Question ] How to properly handle sitemap for multi-language content? 

### ISSUE THREAD

**Issue by sn1p3r46** [dpgaspar/Flask-AppBuilder#1320]
Hi there, 
firstly thanks again for maintaining this amazing project!

I was going through the code and it looks like the language settings are stored in the session object.  I was wondering how to handle the sitemap given this and how to optimize for search engines. 

_How do you suggest to handle the sitemap for multiple languages?_ 

Let's say I have the same article in two different languages how do I tell search engines that my website has two version of the same article (and language stored in session) how do i tell search engines my website is in two languages and the same url can contain two different contents based on the language? (e.g.: as far as I know google don't follow 302 redirects) 

Thanks in advance and all the best!

**Comment by FranciscoCarbonell** [comment]
show here https://support.google.com/webmasters/answer/189077?hl=es-419

**Comment by sn1p3r46** [comment]
The issue is that there is no canonical link for different languages. So the url is the same for several languages and the language variable is stored on sessions (server side) thanks to a session cookie as far as I know Google's crawler is not storing any cookie at all. That's the origin of the question. 

https://www.google.com/search?q=google+crowler+not+using+cookies.&oq=google+crowler+not+using+cookies.+&aqs=chrome..69i57j69i64.5881j0j7&sourceid=chrome&ie=UTF-8
