### ISSUE TITLE
addon secret key question

### ISSUE THREAD

**Issue by FranciscoCarbonell** [dpgaspar/Flask-AppBuilder#1322]
I am creating an addon, but there is a line that has me a little confused

```
class StoreAddOnManager(BaseManager):


    def __init__(self, appbuilder):
        """
             Use the constructor to setup any config keys specific for your app. 
        """
        super(AlmacenAddOnManager, self).__init__(appbuilder)
        self.appbuilder.get_app.config.setdefault('STORE_KEY', 'SOME VALUE')

    def register_views(self):....
```

this line:
`self.appbuilder.get_app.config.setdefault('STORE_KEY', 'SOME VALUE')`

This line, what name do you hope to receive? the name of the class? the name of the addon? for example my addon is called fab_addon_store, what name should it put? is this really being used?

**Comment by dpgaspar** [comment]
No, that's just an example
