### ISSUE TITLE
using request or session in the viewmodel

### ISSUE THREAD

**Issue by reffael** [dpgaspar/Flask-AppBuilder#135]
I've tried both and I get:
RuntimeError: working outside of request context
error message
this is the code:
    
    def get_website():
        if request.args.get('siteID'):
            g.user.siteID = request.args['siteID']
        if hasattr(g.user, 'siteID'):
            return g.user.siteID
        else:
            return False;

    class ItemMV(ModelView):

        datamodel = SQLAInterface(Item)
        list_widget = ItemWidgetList
        list_columns = ['title',  'image','status','link']
        base_filters = [['cid', FilterEqualFunction, get_user],]
        if (get_website()):
            base_filters.append(['siteID', FilterEqualFunction, get_website])

**Comment by dpgaspar** [comment]
You can only use Flask's request when your on a request context (an actual request is happening).

You just can't do it this way. You can override the list method (and call super()) or setup a before_request.

**Comment by reffael** [comment]
you mean overriding -
    @expose('/list/')
    @has_access
    def list(self):

        widgets = self._list()
        return self.render_template(self.list_template,
                                    title=self.list_title,
                                    widgets=widgets)

in my code and add my functionality?

**Comment by dpgaspar** [comment]
Yes,

``` python
@expose('/list/')
@has_access
def list(self):
    if (get_website()):
        base_filters.append(['siteID', FilterEqualFunction, get_website])
    super(YOUMODELCLASS, self).list()
```

Another option, and probably cleaner would be to create your own filter.

``` python
from flask.ext.appbuilder.model.sql.filters import BaseFilter, FilterRelation, BaseFilterConverter

class MyFilterEqualFunction(BaseFilter):
    name = "Filter view with a function"

    def apply(self, query, func):
        value = func()
        if value:
            return query.filter(getattr(self.model, self.column_name) == func())
        else
            return query
```
Then use your filter on base_filters

I have not tested any of this, any questions your welcome to post.

**Comment by reffael** [comment]
working like a charm (minor modifications)

```python
    @expose('/list/')
    @has_access
    def list(self):
        if (get_user() != 1 ):
            self.base_filters.append(['cid', FilterEqualFunction, get_user])
        return super(ItemMV, self).list()
```
