### ISSUE TITLE
Upgrade jQuery to 3.5

### ISSUE THREAD

**Issue by ryw** [dpgaspar/Flask-AppBuilder#1350]
I'm working to clear a [Cross-site Scripting (XSS) CVE](https://app.snyk.io/vuln/SNYK-JS-JQUERY-565129) in Airflow, looks like Airflow gets its jQuery from FAB. Is there a way for us to override the jQuery? Or maybe we can bump jQuery here?

**Comment by dpgaspar** [comment]
Thanks for the warning, we can do it here this is important for FAB also

**Comment by dpgaspar** [comment]
2.3.3 is released https://pypi.org/project/Flask-AppBuilder/
