### ISSUE TITLE
Was unable to import app Error: Install 'email_validator' 

### ISSUE THREAD

**Issue by kitson618** [dpgaspar/Flask-AppBuilder#1358]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment
Python 3.6.10

Flask-Appbuilder version:
2.3.2

### Describe the expected results

Tell us what should happen.

```python
Able to create an admin user by running "fabmanager create-admin"

```

### Describe the actual results

Tell us what happens instead.

```pytb
An Error message shows: 
Was unable to import app Error: Install 'email_validator' for email validation support.

Probably setup.sh missing the plugin "email_validator"
```

### Steps to reproduce
1. pip install flask-appbuilder
2. fabmanager create-app
3. fabmanager create-admin

An error will be hit -> 
Was unable to import app Error: Install 'email_validator' for email validation support.

**Comment by dpgaspar** [comment]
I'm able to reproduce, this is related with this issue also: https://github.com/dpgaspar/Flask-AppBuilder/issues/1356

Do the following:
```
pip install wtforms==2.2.1
```

**Comment by dpgaspar** [comment]
New FAB 2.3.3 fixes this problem
