### ISSUE TITLE
Is there away to create pure flask views as part of my FAB

### ISSUE THREAD

**Issue by reffael** [dpgaspar/Flask-AppBuilder#136]
but with the look&feel of the rest of the pages, using the same permissions, roles, menus and so on.. ?

**Comment by dpgaspar** [comment]
Yes, using any king of view (BaseView, ModelView ...) create your custom endpoints:

```python
from flask.ext.appbuilder import ModelView
from flask.ext.appbuilder.models.sqla.interface import SQLAInterface

class GroupModelView(ModelView):
    datamodel = SQLAInterface(ContactGroup)
    related_views = [ContactModelView]

    @expose('/mycustomview')
    @has_access
    def mycustomview(self):
        # do whatever you want
        return self.render_template('mycustomview.html')
```

Then on template extend base:

    {% extends "appbuilder/base.html" %}
    {% block content %}
          ....
    {% endblock %}

**Comment by reffael** [comment]
thanks, going to try it
