### ISSUE TITLE
Refactoring classname ContactGroup in MasterDetail example causing sqlalchemy.exc.NoForeignKeysError

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#137]
Is it some kind of bug? In MasterDetail example, refactoring the class name ContactGroup to anything else and then

rm app.db 
python testdata.py returns:

sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship ManagementServer.contact_group - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

**Comment by scheung38** [comment]
Is it some kind of bug? In MasterDetail example, refactoring just the class name ContactGroup to anything else and then

rm app.db 
python testdata.py returns:

sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship ManagementServer.contact_group - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

**Comment by dpgaspar** [comment]
Can you post your models? F.A.B. is not being able to find the relation between your two model to generate the master detail.

**Comment by dpgaspar** [comment]
This is already solved rigth, problem with the Model's names.
