### ISSUE TITLE
allow multi roles in AUTH_USER_REGISTRATION_ROLE

### ISSUE THREAD

**Issue by tooptoop4** [dpgaspar/Flask-AppBuilder#1372]
I am using superset.

I would like to set 

AUTH_USER_REGISTRATION_ROLE = "Gamma,sql_lab,hivedb"
AUTH_TYPE = AUTH_LDAP
AUTH_ROLE_ADMIN = 'Admin'
AUTH_USER_REGISTRATION = True

Multi roles seems not allowed, i don't want anyone to click roles/permission in the UI, I want all new users to get Gamma,sql_lab,hivedb by default

**Comment by dpgaspar** [comment]
Hi @tooptoop4,

Makes sense, this should be a simple change, do you want to do it?

**Comment by tooptoop4** [comment]
not sure where to change. as a workaround i changed /usr/local/lib64/python3.6/site-packages/flask_appbuilder/security/sqla/manager.py 

within add_user --> (is it safe change?)


            user.roles.append(role)
            roleextra1 = self.find_role('sql_lab')
            if roleextra1 is not None:
                user.roles.append(roleextra1)
            roleextra2 = self.find_role('hivedb')
            if roleextra2 is not None:
                user.roles.append(roleextra2)
