### ISSUE TITLE
Charts/dashboards/metadata queries are not being run as impersonation user

### ISSUE THREAD

**Issue by tooptoop4** [dpgaspar/Flask-AppBuilder#1373]
Superset: When a datasource like hive/presto has impersonation ticked I would expect charts/dashboards/metadata queries to run as the impersonated (UI login user) not the principal user in the datasource, but this is not the case. Only sqllab queries get run by impersonated user

**Comment by dpgaspar** [comment]
Sorry, can't see how this is a flask-appbuilder question?
