### ISSUE TITLE
Use "allow list" or "safe list" instead of the term "whitelist"

### ISSUE THREAD

**Issue by ashb** [dpgaspar/Flask-AppBuilder#1390]
Language matters. I'd like to remove all references in Apache Airflow to white list or black list and I found an example in the default webserver template config we ship.

The recent global events have made this even more relevant, Here is a well written article for why I think it matters 

https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

 >   It's fairly common to say whitelisting and blacklisting to describe desirable and undesirable things in cyber security.
>
>    However, there's an issue with the terminology. It only makes sense if you equate white with 'good, permitted, safe' and black with 'bad, dangerous, forbidden'. There are some obvious problems with this. 

The security manager has a field called `oauth_whitelists` -- I think we could call that `oauth_allow_list` and it has the added benefit of being slightly clearer too. It is possible to make this change in a backwards-compatible way.

**Comment by ashb** [comment]
Unstaleify :)

**Comment by ashb** [comment]
Unstaleify still

**Comment by soundmaking** [comment]
Although it would break the principle of `There should be one-- and preferably only one --obvious way to do it.`, might it be possible to have `oauth_allow_list` as an alias letting people code via that in their work, whilst the archaic `oauth_whitelists` would still be available for backwards compatibility?
