### ISSUE TITLE
Multiple models as context in a single template

### ISSUE THREAD

**Issue by paalped** [dpgaspar/Flask-AppBuilder#1394]
Hello there,

First I would like to applause on this fabulous appbuilder package. I never thaught it could be so easy to make a webapp. Thank you guys so much, and you @dpgaspar for making this!

I have a question though.

How can I use mutiple models in a single template? I would like to pass serveral models as a context dicitonary for the template engine. Is it compatible with this framework?

I'd love to post the example back here if I can get some advice.

Paal

**Comment by ThomasP0815** [comment]
In my opinion this wish contradicts with MVC (model view control)!
Please describe your problem in detail?

**Comment by ThomasP0815** [comment]
You can have multiple lists within one view using the class "MultipleView".

https://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html?highlight=multipleview
