### ISSUE TITLE
What is the difference between : FilterEqual and FilterEqualFunction?

### ISSUE THREAD

**Issue by reffael** [dpgaspar/Flask-AppBuilder#140]
I use them both and not sure what is right?
self.base_filters.append(['cid', FilterEqualFunction, g.user.id]

base_filters = [['offline', FilterEqual, 0],]

**Comment by dpgaspar** [comment]
FilterEqualFunction expects the uses the returned value of a given function for comparison.

FilterEqual compares with a given value

Take a look at the source:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/filters.py#L114
