### ISSUE TITLE
allow_blank=True does not do anything for QuerySelectMultipleField warning

### ISSUE THREAD

**Issue by andreamancini-work** [dpgaspar/Flask-AppBuilder#1402]
Hi, 
I'm using your package from a pair of mouths and it is very good.
Sometimes in logs appears this warning, but I can't understand if it is caused by my wrong configuration or others.

```
/home/pi/.local/lib/python3.7/site-packages/flask_appbuilder/fields.py:182: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  "allow_blank=True does not do anything for QuerySelectMultipleField."
```

Thanks in advance.

**Comment by mapio** [comment]
The issue has been closed as stale, but the bug is still present and the pull request fixing it is stale (since unprocessed).
