### ISSUE TITLE
Many to Many Relational Table Model in Single View

### ISSUE THREAD

**Issue by naresnayak** [dpgaspar/Flask-AppBuilder#1404]
Hello there,

First i would like to thank to this wonderful app-builder package.it is very useful to create web app.Thank you guys so much guys.

I have a question though.

How can i use Many to Many relational Model in single view. Example.
**Order** and **Product** 

![Order](https://user-images.githubusercontent.com/65640697/84917660-3c0d7f80-b0dd-11ea-9c3d-bb5f7cdd22bf.PNG)

**Comment by fainyang** [comment]
You can try **related_views**

Can refer https://flask-appbuilder.readthedocs.io/en/latest/quickhowto_mongo.html?highlight=related_views#define-your-views-views-py

**Comment by naresnayak** [comment]
Thanks for your time.I know about related view but i wanted to add both relational models in a single 
view.In related view we cannot do that.

**Comment by ThomasP0815** [comment]
You can have multiple lists within one view  using the class "MultipleView".

https://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html?highlight=multipleview
