### ISSUE TITLE
Work with multiple databases

### ISSUE THREAD

**Issue by aagudeloz** [dpgaspar/Flask-AppBuilder#1414]
Hi

I have two databases, one in Oracle (read only) and the other in mysql. I am creating an application on mysql that should be check the oracle database to maintain the integration of the data. Tried to implement relationships according to this link (https://stackoverflow.com/questions/7410010/sqlalchemy-declarative-relationships-across-multiple-different-databases) but it marks me error.

Can someone here give me a light? How can I query a field in Oracle database while capturing information for mysql? of course doing it in flask-appbuilder.

I have no problems connecting to databases and defining tables.

Sorry for my English

Thanks a lot.

**Comment by duyluandethuong** [comment]
I assume MySQL is the main datasource for your FAB app?

So you just use external connection to query Oracle DB and check whatever you want. You can use SQLAlchemy for this
