### ISSUE TITLE
Could be possible to create a Chart grouped by two or more columns?

### ISSUE THREAD

**Issue by blacklupo** [dpgaspar/Flask-AppBuilder#142]
I have created this View:

```python
class JiraWorklogsChartView(GroupByChartView):
    datamodel = SQLAInterface(JiraWorklogs)
    chart_title = 'Direct Data'
    definitions = [
        {
            #'label': 'Monthly',
            'group': 'product',
            'series': [(aggregate_sum, 'timespent')]
        },
        {
            #'label': 'Monthly',
            'group': 'userName',
            'series': [(aggregate_sum, 'timespent')]
        }
    ]
```

And I need to group it by 'product' and 'userName', is this possible?

Many thanks.

**Comment by dpgaspar** [comment]
Yes it is possible using a group with a function.

On your Model create a function that outputs a string concatenating *userName* and *product*, use this function for your group.

Try it out, tell me if it works

**Comment by blacklupo** [comment]
Thanks you so much Daniel, It works perfectly!! :)

**Comment by dpgaspar** [comment]
Great!
