### ISSUE TITLE
Charts are not visible

### ISSUE THREAD

**Issue by skripthostmsr** [dpgaspar/Flask-AppBuilder#1420]
I can´t see charts anymore. I don´t even see any charts in the demo version:

http://flaskappbuilder.pythonanywhere.com/countrydirectchartview/chart/0

I just have a blank screen. I think it it has something to do with changed referring urls. Can anyone help me out?

Thanks!

**Comment by kmorkah** [comment]
temporarily I changed the appbuilder.static url

<script async type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> 
to
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

in all source with custom templete.

**Comment by skripthostmsr** [comment]
That was the perfect solution!

Thank you!
