### ISSUE TITLE
stacking menus on top of each other

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#144]
class ViewA(ModelView):
    add_template = 'myFirstTemplateA.html'

class ViewB(ModelView):
    add_template = 'mySecondTemplate.html'

How to render it such that myFirstTemplateA is on top of mySecondTemplateB? At the moment they exist separately as

appbuilder.add_view(ViewA, "MenuA", icon="fa-tachometer")
appbuilder.add_view(ViewB, "MenuB", icon="fa fa-hdd-o")

**Comment by blacklupo** [comment]
I think that issue is related to the behavior of Bootstrap navbar. I think that it could be possible editing the CSS.

**Comment by dpgaspar** [comment]
Hello,

If i understand correctly you want a menu dropdown, you need to add the views like this:

``` python
appbuilder.add_view(ViewA, "MenuA", icon="fa-tachometer", category="Templates", category_icon="fa fa-hdd-o")
appbuilder.add_view(ViewB, "MenuB", icon="fa fa-hdd-o", category="Templates")

```

**Comment by scheung38** [comment]
No, a single call to 

appbuilder.add_view(ViewA, "MenuA", icon="fa-tachometer", category="Templates", category_icon="fa fa-hdd-o")

to render MenuA and then MenuB stacked below MenuA

**Comment by dpgaspar** [comment]
You want the user to select MenuA and render on the same page ViewA and ViewB ?

**Comment by scheung38** [comment]
Yes stacking two different database tables on top of each other or more

**Comment by dpgaspar** [comment]
This can be currently done if without the search widget, is this sufficient?

PS:
new major release with JSON REST and angularJS would bring so many new possibilities... i have to make time to do it...

**Comment by scheung38** [comment]
Yes that will be great, just to display two will be awesome

**Comment by scheung38** [comment]
Can't wait. Especially the dynamic dropdown

**Comment by dpgaspar** [comment]
I'll give you a solution for this (before the release of 2.0.0, that will take long), please be patient.

**Comment by scheung38** [comment]
Thanks Daniel, so currently not supported?

**Comment by dpgaspar** [comment]
1.3.6 is out, includes a view you can use to implement this, take a look at MultipleView.

**Comment by scheung38** [comment]
Inside my conda created virtual environment:

cd PyCharmProject/Flask-AppBuilder

git pull 

but still displaying 1.3.4?

**Comment by scheung38** [comment]
From my understanding the MultipleView renders master and detail views, is it also for rendering two unrelated databases as well?
