### ISSUE TITLE
Add support for `ldap3`

### ISSUE THREAD

**Issue by fengsi** [dpgaspar/Flask-AppBuilder#1447]
Currently, FAB is using legacy [python-ldap](https://github.com/python-ldap/python-ldap) as its LDAP library.  There are several issues:
1. `python-ldap` is a wrapper of [OpenLDAP](https://www.openldap.org), hence it requires OpenLDAP libs/headers to be compiled.  This is too heavy for a feature that could be implemented without these dependencies, especially in the container world.
2. `OpenLDAP` made `python-ldap` not Pythonic, just like many other extensions.
3. I might be wrong, but it seems FAB is not using many fancy features that `python-ldap` provides other than auth and search.  After all, what we need is just a simple client talking to LDAP server and such.

I noticed the problem while trying to switch auth backend in [Airflow](https://github.com/apache/airflow).  Airflow uses the new [ldap3](https://github.com/cannatag/ldap3) as its default LDAP lib, but if RBAC is enabled, the admin interface switches to FAB, and then `python-ldap` will be required.  All LDAP-related settings in Airflow become invalid.

What I'd suggest is to implement a new workflow around `ldap3`.  We could still keep current LDAP settings as is, as much as possible.  We could have a mapping to translate these into `ldap3` world.  This would ensure maximum backward-compatibility, and also allow using `ldap3` as the lib.

Suggested action items:
1. Add LDAP auth workflow using `ldap3`
2. Keep current `python-ldap` specific LDAP settings as is, and try mapping them for `ldap3` to use
3. Introduce a new setting specifying LDAP lib with default `python-ldap`, but allow user to switch to `ldap3` by changing that flag
4. Change default lib to `ldap3` (optional)
5. Refactor LDAP settings to align better with `ldap3`; deprecate old settings (optional)
6. Completely remove `python-ldap` stuff (optional)

I might be too optimistic, but if this sounds like a good idea, I'd be willing to implement it for FAB.

**Comment by mik-laj** [comment]
In the case of a container environment, I would consider using a Keycloak + OpeniD proxy for authentication. This will allow you to provide greater isolation and flexibility.

**Comment by fengsi** [comment]
> In the case of a container environment, I would consider using a Keycloak + OpeniD proxy for authentication. This will allow you to provide greater isolation and flexibility. Isolation is especially important with Airflow, because the Webserver executes user code.

Thanks for the advise.  I agree on isolation and such, but the extra deps is really overkill in our case.  It's not like adding a new LDAP feature, but just making existing LDAP working with existing FAB RBAC.

Airflow has an official Docker image, but it contains no LDAP libs.  Installing `ldap3` for default admin interface is fine as it's pure Python, but enabling RBAC + LDAP would require `python-ldap`, which would also require the giant `lib*-dev` deps.

The official Airflow image is multi-stage and it already cleaned up build deps before making the final image.  So if I were to include `python-ldap` myself, I'll have to source from the base, install deps again, compile `python-ldap`, and then clean up.  That's a lot of hassle.

Furthermore, the "official" Helm chart has bunch of hooks that allow a user to install Python deps on the fly during deployment, without touching the image. Unfortunately again, such neat feature won't work due to Airflow image lacking of build deps.  Even if it were possible, it may be okay for a new web Pod to spend say 3 seconds each time to install the extra Python deps when launching, but definitely no go for 60 seconds including all the build deps for `python-ldap` alone...

If we can make `ldap3` work in FAB, I'd imagine it'll be much easier for Airflow LDAP users to enable RBAC.  Actually I'm already building my image from scratch base on Python, not Airflow, mainly due to `python-ldap` deps...

**Comment by dpgaspar** [comment]
Sounds great by me, are you willing to make a PR?

**Comment by fengsi** [comment]
> Sounds great by me, are you willing to make a PR?

sure; let me spend some time on that
