### ISSUE TITLE
method_permission_name is ignored

### ISSUE THREAD

**Issue by lgprobert** [dpgaspar/Flask-AppBuilder#1449]
This issue should be renamed to `method_permission_name` resulted unexpected permission sets.
### Environment

Flask-Appbuilder version: 3.0.1

pip freeze output:
encodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.0
widgetsnbextension==3.5.1
wrapt==1.11.2
WTForms==2.3.3
yarl==1.4.2
zict==1.0.0
zipp==0.6.0
### Describe the expected results

Tell us what should happen.
`method_permission_name` can compress the permissions to user defined less permission names like **'read' and 'write'**.

```python
class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)
    class_permission_name = "contact_perm"
    # previous_class_permission_name = "ContactModelView"
    method_permission_name = {
        'add': 'write',
        'delete': 'write',
        'download': 'write',
        'edit': 'write',
        'list': 'read',
        'muldelete': 'write',
        'show': 'read'
    }
```

### Describe the actual results

Tell us what happens instead.
Execute `security-converge --dry-run` has following calculated results:
```
Computed security converge:                                                                                  
Add to Roles:                                                                                                
Where ('udview', 'can_add') add {('GroupModelView', 'can_add')}                                              
Where ('udview', 'can_show') add {('GroupModelView', 'can_show')}                                            
Where ('udview', 'can_list') add {('GroupModelView', 'can_list')}                                            
Where ('udview', 'can_download') add {('GroupModelView', 'can_download')}                                    
Where ('udview', 'can_delete') add {('GroupModelView', 'can_delete')}                                        
Where ('udview', 'can_edit') add {('GroupModelView', 'can_edit')}                                            
Where ('ContactModelView', 'can_add') add {('contact_perm', 'can_add'), ('contact_perm', 'can_write')}       
Where ('ContactModelView', 'can_show') add {('contact_perm', 'can_read'), ('contact_perm', 'can_show')}      
Where ('ContactModelView', 'can_list') add {('contact_perm', 'can_list'), ('contact_perm', 'can_read')}      
Where ('ContactModelView', 'can_download') add {('contact_perm', 'can_write')}                               
Where ('ContactModelView', 'can_delete') add {('contact_perm', 'can_write'), ('contact_perm', 'can_delete')} 
Where ('ContactModelView', 'can_edit') add {('contact_perm', 'can_write'), ('contact_perm', 'can_edit')}     
Del from Roles:                                                                                              
('udview', 'can_add')                                                                                        
('ContactModelView', 'can_edit')                                                                             
('udview', 'can_delete')                                                                                     
('ContactModelView', 'can_show')                                                                             
('udview', 'can_list')                                                                                       
('udview', 'can_download')                                                                                   
('ContactModelView', 'can_download')                                                                         
('ContactModelView', 'can_list')                                                                             
('udview', 'can_show')                                                                                       
('ContactModelView', 'can_delete')                                                                           
('udview', 'can_edit')                                                                                       
('ContactModelView', 'can_add')                                                                              
Remove views:                                                                                                
ContactModelView                                                                                             
udview                                                                                                       
Remove permissions: 
```
The resulted permissions set for effective view "contact_perm" are as followed:
can_list	    contact_perm
can_read	    contact_perm
can_write	    contact_perm
can_edit	    contact_perm
can_add	    contact_perm
can_delete   contact_perm
can_show     contact_perm

### Steps to reproduce
1. Add the codes to change the class of `ContactModelView` in example `enums/app/views.py`.
2. run "flask fab security-converge" with `FAB_UPDATE_PERMS = False` set in `config.py`
> with line `class_permission_name = "contact_perm"` in place, the last step of security-converge will generate an error indicates the "ContactModelView" is not exists. But commenting out the class_permission_name lines do the make difference for the final effect. 
3. comment out the line of  `FAB_UPDATE_PERMS = False` set in `config.py`
4. start the application and check permissions, the `method_permission_name` worked some way but produced very different set of permissions.

**Comment by lgprobert** [comment]
Looks twice into the output of `security-converge`, it is strange to see that appbuilder will add list of permissions when it rename current view name per `class_permission_name` and migrate the permissions:

```
Where ('ContactModelView', 'can_add') add {('contact_perm', 'can_add'), ('contact_perm', 'can_write')}       
Where ('ContactModelView', 'can_show') add {('contact_perm', 'can_read'), ('contact_perm', 'can_show')}      
Where ('ContactModelView', 'can_list') add {('contact_perm', 'can_list'), ('contact_perm', 'can_read')}      
Where ('ContactModelView', 'can_download') add {('contact_perm', 'can_write')}                               
Where ('ContactModelView', 'can_delete') add {('contact_perm', 'can_write'), ('contact_perm', 'can_delete')} 
Where ('ContactModelView', 'can_edit') add {('contact_perm', 'can_write'), ('contact_perm', 'can_edit')
```
I think the expected result is only one permission per rule is generated, not a list.

**Comment by dpgaspar** [comment]
Thank you for reporting this.

On the example you gave `# previous_class_permission_name = "ContactModelView"` this was commented was it commented when you run or not?

Can you please post the full example (use gist) for example. Then run from a clean DB and post the logs. This way I can reproduce and compare the logs.

**Comment by lgprobert** [comment]
Thanks for the quick reply.

The commented `previous_class_permission_name` was used to revert back to default class permission because I am not sure if setting of `method_permission_name` can be applied after I change `class_permission_name` to non-default name. 

It seems `security-converge` has a side-effect that it would try again to remove a already-removed view if it sees a class has set a non-default `class_permission_name` even it has been done at last run. This would generate error from `security-converge` though I am not sure if it has any negative effect to the execution of the command. 

The modified view module is posted at: https://github.com/lgprobert/testapp/blob/master/app/views.py
In this version, I comment out the method_permission_name because I want to test if shared `class_permission_name` among a few classes can work. You can simply uncomment the `method_permission_name` code block to test it.
Thanks
