### ISSUE TITLE
[Not an issue] I have a couple of question for this

### ISSUE THREAD

**Issue by JunkyardCat** [dpgaspar/Flask-AppBuilder#1450]
1. how similar is this to flask admin? I was searching around and wanted something similar to flask admin that is actively being maintained.
2. Im assuming that its also easy to create a crud datatable like flask admin. If so is there a way to just copy the functionality of that table creation? Im only interested in creating datatables and also creating records and associating this record with that record(foreign key and many to many relation ship) 
3. can app builder work in windows or does it needs dependency that will only work in linux?
4. Is there a forum or discord that people can ask question?

**Comment by dpgaspar** [comment]
Hi @JunkyardCat,

1. Here's an answer: https://stackoverflow.com/questions/30126607/flask-admin-vs-flask-appbuilder#:~:text=On%20the%20overall%20i%20think,building%20very%20specific%20security%20models.

(It's a bit old now)

2 - The concept is very similar, take a looks at the examples

3 - Take a look at the README (main github page for this repo). We have gitter and a google mailing list
