### ISSUE TITLE
Using Flask AppBuilder with python RQ

### ISSUE THREAD

**Issue by duyluandethuong** [dpgaspar/Flask-AppBuilder#1455]
When I add python **RQ (Redis queue)** to the project, everything is working normally, except that when I enqueue a task to be run by a worker, the worker will **reload the whole FAB application** before it can actually run it's task (I can see the log, so I am sure the app is reloaded).

That costs the worker a significant extra amount of time just to load the FAB code.

How can I fix this?

When I use raw Flask (without Flask AppBuilder) with Python RQ, I did not have this issue.

These are the dependencies that I use:

- redis==3.5.3
- rq==1.5.0

**Comment by dpgaspar** [comment]
That's strange, but I can only wild guess what may be happening. Note that one of the best ways to run a flask app is by using the factory pattern.

If you haven't figure it out yet, post the code here and server logs
