### ISSUE TITLE
settings page

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#146]
Any idea how this would be implemented? A typical settings page with 

First Setting : Value
Data Name  Data Value

Second Setting : Value
Data Name Data Value

Etc

**Comment by dpgaspar** [comment]
Could you please post a more "formal" data structure definition. Is this something like:

{'<KEY>':{'<DATA_NAME>':'<DATA_VALUE>', ... }, ... }

A dict inside a dict? What is your goal here?

**Comment by dpgaspar** [comment]
No update, i'll close this, if you want to you can reopen it.
