### ISSUE TITLE
logging session to file

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#147]
logging.basicConfig(format='%(asctime)s:%(levelname)s:%(name)s:%(message)s')
logging.getLogger().setLevel(logging.DEBUG)

how to log all events from launching to exit to file?

**Comment by dpgaspar** [comment]
logging module is not F.A.B. i use as a best practice, take a look at the docs:

https://docs.python.org/2/library/logging.html
