### ISSUE TITLE
The Chart is not visible after deployed on the server. (This issue is related to #1418)

### ISSUE THREAD

**Issue by tetsuya0617** [dpgaspar/Flask-AppBuilder#1473]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:  2.3.4

pip freeze output:

alembic==1.4.0
apispec==1.3.3
appnope==0.1.0
attrs==19.3.0
Babel==2.8.0
backcall==0.1.0
BigQuery-Python==1.14.0
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
colorama==0.4.3
configparser==5.0.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.2.9
dnspython==1.16.0
email-validator==1.1.0
et-xmlfile==1.0.1
Flask==1.1.2
Flask-AppBuilder==2.3.4
Flask-Babel==1.0.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.2.1
Flask-OAuthlib==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.3
future==0.16.0
google-api-core==1.17.0
google-api-python-client==1.7.6
google-auth==1.20.0
google-auth-httplib2==0.0.3
google-cloud-bigquery==1.24.0
google-cloud-core==1.3.0
google-cloud-datastore==1.7.3
google-cloud-logging==1.10.0
google-cloud-secret-manager==1.0.0
google-cloud-storage==1.13.2
google-gax==0.15.16
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
grpc-google-iam-v1==0.12.3
grpcio==1.27.1
httplib2==0.18.0
idna==2.9
importlib-metadata==1.6.0
install==1.3.3
ipython==7.14.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
Mako==1.1.1
MarkupSafe==1.1.1
marshmallow==2.21.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.0
mysqlclient==1.4.6
numpy==1.19.1
oauth2client==3.0.0
oauthlib==2.1.0
openpyxl==3.0.3
pandas==1.1.1
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
ply==3.8
prison==0.1.3
prompt-toolkit==3.0.5
protobuf==3.12.1
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
PyJWT==1.7.1
PyMySQL==0.9.3
pyrsistent==0.16.0
python-dateutil==2.8.1
python-dotenv==0.14.0
python-editor==1.0.4
python3-openid==3.1.0
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==0.8.0
rsa==4.0
six==1.14.0
SQLAlchemy==1.3.16
SQLAlchemy-Utils==0.36.5
traitlets==4.3.3
uritemplate==3.0.1
urllib3==1.25.9
wcwidth==0.1.9
Werkzeug==0.16.1
WTForms==2.3.1
zipp==3.1.0

### Describe the expected results

The Chart is not visible. I am trying to see the chart of the user stats in the security menu. 
I temporarily deal with it by writing '<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>' in chart.html, multiple_chart.html, and direct_chart.html in widgets.  This is already issued in # 1418. 

I could successfully see the chart in the local server by doing the same way as # 1418 but after I deployed the application, I am not able to see the chart on the cloud server. 

### This is the issue picture. 

It's on the cloud server.
![スクリーンショット 2020-09-14 11 50 04](https://user-images.githubusercontent.com/38417952/93038673-9daf9c80-f680-11ea-98d0-0f44690ad0a4.png)

It's on the local server.
![スクリーンショット 2020-09-14 11 52 30](https://user-images.githubusercontent.com/38417952/93038757-d2bbef00-f680-11ea-917e-75515d6e5890.png)

**Comment by pasqwal** [comment]
The Charts display is relying on internet access. Is it possible your server does not have access to the web or some Firewalls rules to block some URLs ?

**Comment by swalkowski** [comment]
Isn't it https://github.com/dpgaspar/Flask-AppBuilder/issues/1442, which was fixed in 3.0.1?
