### ISSUE TITLE
How to display a multiple values(checkbox) in edit?

### ISSUE THREAD

**Issue by HHself** [dpgaspar/Flask-AppBuilder#1474]
Hi,

In CRUD, I have a field need use CheckBox(multiple select)， using QuerySelectMultipleField(from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField) and widget=Select2ManyWidget(from flask_appbuilder.fieldwidgets import Select2ManyWidget), but always get an error.

When using SelectMultipleField(from wtforms.fields import SelectMultipleField) and widget=Select2ManyWidget()，then override pre_add()、pre_update(), the problem solved.  However, in item edit operation, we can not make multi-data  Correctly display in the fields.

I have no idear about this issue, Where can I find a solution?

Thanks.

**Comment by HHself** [comment]
> Hi,
> 
> In CRUD, I have a field need use CheckBox(multiple select)， using QuerySelectMultipleField(from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField) and widget=Select2ManyWidget(from flask_appbuilder.fieldwidgets import Select2ManyWidget), but always get an error.
> 
> When using SelectMultipleField(from wtforms.fields import SelectMultipleField) and widget=Select2ManyWidget()，then override pre_add()、pre_update(), the problem solved. However, in item edit operation, we can not make multi-data Correctly display in the fields.
> 
> I have no idear about this issue, Where can I find a solution?
> 
> Thanks.

**Comment by ThomasP0815** [comment]
You can do this is if you have a many to many relationship between 2 tables.

Have a look at this example:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/employees

**Comment by HHself** [comment]
> You can do this is if you have a many to many relationship between 2 tables.
> 
> Have a look at this example:
> https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/employees

thanks 

> You can do this is if you have a many to many relationship between 2 tables.
> 
> Have a look at this example:
> https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/employees

success now! Thank you very much!

**Comment by HHself** [comment]
> You can do this is if you have a many to many relationship between 2 tables.
> 
> Have a look at this example:
> https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/employees

success now! Thank you very much!

**Comment by HHself** [comment]
Another question 
in many to many, how to make fields required(nullable=false), for employees example, make Benefits have a red star?

**Comment by ThomasP0815** [comment]
I think you can't achive this via the database model.

Put the following statement in the EmployeeView:

```
def pre_add(self, item):

        if item.benefits == []:
            raise Exception("benefits must not be empty")
```

With this you force at least one benefit for each employee.

**Comment by HHself** [comment]
Ha, Ha, Ha (smiling face), That is exactly what I thought myself.

Thanks again

**Comment by HHself** [comment]
> I think you can't achive this via the database model.
> 
> Put the following statement in the EmployeeView:
> 
> ```
> def pre_add(self, item):
> 
>         if item.benefits == []:
>             raise Exception("benefits must not be empty")
> ```
> 
> With this you force at least one benefit for each employee.

Ha, Ha, Ha (smiling face), That is exactly what I thought myself.

Thanks again

**Comment by HHself** [comment]
> I think you can't achive this via the database model.
> 
> Put the following statement in the EmployeeView:
> 
> ```
> def pre_add(self, item):
> 
>         if item.benefits == []:
>             raise Exception("benefits must not be empty")
> ```
> 
> With this you force at least one benefit for each employee.

Ha, Ha, Ha (smiling face), I was thinking the same thing.
Thanks again
