### ISSUE TITLE
[Question]: Recommend way to implement a TimeSeries Chart?

### ISSUE THREAD

**Issue by a-mckinley** [dpgaspar/Flask-AppBuilder#149]
I have a simple model that stores a timestamp and associated number of elements.

```
class Event(Model):
        id = Column(Integer, primary_key=True)
        number = Column(Integer)
        time = Column(DateTime)
```

How can I use DirectByChartView to display a binned time series representation of the aggregate of number during each time slice?

Do I need to implement additional methods on my model to generate a binned "view" of the model?

E.g:

![image](https://cloud.githubusercontent.com/assets/5833029/7158718/b1106c02-e374-11e4-8d5d-6c5ac3bdb9f3.png)

**Comment by dpgaspar** [comment]
On your models.py (or where you have defined Event) import python's datetime then create a method to aggregate your time column (assuming hours):

``` python

    class Event(Model):
        id = Column(Integer, primary_key=True)
        number = Column(Integer)
        time = Column(DateTime)

        def hours(self):
            return datetime.datetime(self.time.year, self.time.month, self.time.day, self.time.hour, 1)
```

Then define your direct chart view class (on views.py):

``` python
class CountryDirectChartView(DirectByChartView):
    datamodel = SQLAModel(CountryStats)
    chart_title = 'Direct Data'

    definitions = [
        {
            'label': 'Hourly',
            'group': 'hours',
            'series': ['number']
        }
    ]

```

I have not tested this so it's probably not 100% correct, but this is the general idea, tell me if it worked.
