### ISSUE TITLE
Pin pre-1.0 dependencies by middle version number

### ISSUE THREAD

**Issue by sloria** [dpgaspar/Flask-AppBuilder#1496]
As suggested [here](https://github.com/dpgaspar/Flask-AppBuilder/pull/1111#pullrequestreview-285084039), pre-1.0 dependencies should be pinned by middle version number because a middle version bump may introduce a breaking change.

You may not need to do this for _every_ pre-1.0 dep, but I do suggest doing it for at least marshmallow-sqlalchemy (for which I am the maintainer). This will prevent future pain for [Airflow users](https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/241) when breaking changes are made to marshmallow-sqlalchemy.

**Comment by dpgaspar** [comment]
@sloria right you are, thank you for pointing it out. Next FAB 3.1.1 will constraint these
