### ISSUE TITLE
Example extendsecurity not filtering contact list as expected.

### ISSUE THREAD

**Issue by hblandford** [dpgaspar/Flask-AppBuilder#1510]
### Environment
Running in WSL2 on Ubuntu 20.04LTS
Flask-Appbuilder version: 3.1.1 running the extendsecurity example.

pip freeze output:
apispec==3.3.2
attrs==20.2.0
Babel==2.8.0
blinker==1.4
click==7.1.2
colorama==0.4.4
defusedxml==0.6.0
dnspython==2.0.0
email-validator==1.1.1
flake8==3.8.4
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-DebugToolbar==0.11.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==3.8.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
mccabe==0.6.1
Pillow==8.0.1
prison==0.1.3
pycodestyle==2.6.0
pyflakes==2.2.0
PyJWT==1.7.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2020.1
PyYAML==5.3.1
six==1.15.0
SQLAlchemy==1.3.20
SQLAlchemy-Utils==0.36.8
Werkzeug==1.0.1
WTForms==2.3.3

### Describe the expected results

contactmodelview/list/ should only display contacts from the company of the logged in user.  I was trying to understand this example to adopt into my own site.

### Describe the actual results

I always see all the contacts.

### Steps to reproduce

I believe I have installed the demo correctly.  It doesn't appear to work.
If I add a ['name', FilterStartsWith, 'a'] to the base_filters of the class ContactModelView(ModelView) in views.py I am returned 3 records from multiple companies.

Here is a screenshot showing the base_filters working partially.
![filtered_records_startswith_a](https://user-images.githubusercontent.com/14069848/97782135-ed700600-1be3-11eb-8e4d-1b23224977e0.png)

**Comment by finnkr539** [comment]
Hi,  
the result in the screenshot looks right to me, all names displayed are beginning with an 'a'. Are you sure you have the filter set on the right field? 

To achieve your goal, you would probably have to extend the User Model (add the users company) and query against that.

**Comment by hblandford** [comment]
Hi @finnkr539 and all,

thanks for taking the time to reply/read my post.  My post was really a question, not a bug report, it will be a lack of understanding on my part.  Anyway, in replying to your post I thought I had better start all over again so I could be clear in explaining and now it is working as expected!  In my screenshot, I was only expecting to see users from their own company.

Obviously a problem between keyboard and chair.  With user1_company1, I am now only seeing contacts from company_one as it says in the documentation.  I swear I had tried this before but thank you for prompting me to go back and have a look all over again!

Thanks again,

Hugh
