### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by mswastik** [dpgaspar/Flask-AppBuilder#1512]
I want to add multiple entries to a model at a single time, for this I was experimenting with different settings.

In a class derived from ModelView, I mentioned `add_widget = ListAddWidget`. 
I got below error

> jinja2.exceptions.TemplateNotFound: appbuilder/general/widgets/list_add.html

Also I found there is `lnk_add(my_href)` macro which can enable multi form entries into a model, can you guide how can I include it in custom add template.

**Comment by finnkr539** [comment]
Can you tell me where you put the list_add.html? Jinja is probably looking for the file in the wrong directory.
