### ISSUE TITLE
[question] How to upload a file with rest api and ModelRestApi

### ISSUE THREAD

**Issue by mjozan** [dpgaspar/Flask-AppBuilder#1515]
Hello,

I am trying to upload a pdf file from a form in a React component. 

I get an error when I make a post request with a `'Content-Type': 'multipart/form-data'` header to the model endpoint `http://localhost:5000/api/v1/template/` . The error is `error 400: Bad request` and the message is `Request is not JSON`. 

Which means that the api does not accept 'multipart/form-data' request. Then, how can I upload a file to the rest api? Thank you for your answer.

**Comment by dpgaspar** [comment]
Hi, you have to build your own endpoint for this, you can inherit from `ModelRestApi` also and custom develop your HTTP POST endpoint
