### ISSUE TITLE
Extending the documentation for AUTH_LDAP

### ISSUE THREAD

**Issue by PhilippB21** [dpgaspar/Flask-AppBuilder#1519]
Hey Flask-AppBuilder Team,

It would be nice to have also the AUTH_LDAP_SEARCH_FILTER documented. We needed this for the Apache Airflow LDAP connection. A look into the source code brought it to light.

As description you could include the following.
_This filter can be used to restrict the LDAP search. An example value is "(|(memberOf=cn=group1*)(memberOf=cn=group2*))"_

Here is the link to the documentation where I expected the parameter:
https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap

Many thanks for your good work. Keep up the good work

**Comment by dpgaspar** [comment]
Thank you, did exactly that
