### ISSUE TITLE
Cannot find jQuery and AngularJS libraries

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#152]
The src location was entered in PyCharm as jquery and then CTRL-SPACE twice so it automatically detected correct location of jQuery and AngularJS libraries:

```html5
{% extends "appbuilder/general/model/list.html" %}

{% block head_js %}
    {{ super() }}
    <script src="../static/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="../static/bower_components/angular/angular.min.js"></script>
{% endblock %}
```
But it is always returning 404 not found:
...static/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 404 -

**Comment by dpgaspar** [comment]
On Flask it is advised to use jinja2 url_for. You don't need to import jquery it's already imported by F.A.B. on head_js.

``` html
{% block head_js %}
{{ super() }}
<script src="{{url_for('static',filename='bower_components/angular/angular.min.js')}}"></script>
</script>

```

**Comment by scheung38** [comment]
Thanks Daniel, I don't really understand how the SecurityManager works? 


     On Thursday, April 16, 2015 1:34 PM, Daniel Vaz Gaspar <notifications@github.com> wrote:
   

 On Flask it is advised to use jinja2 url_for. You don't need to import jquery it's already imported by F.A.B. on head_js.{% block head_js %}
{{ super() }}
<script src="{{url_for('static',filename='bower_components/angular/angular.min.js')}}"></script>
</script>

**Comment by scheung38** [comment]
Author used:

<script src="bower_components/angular/angular.js"></script>
<script src="js/app.js"></script>

https://www.youtube.com/watch?v=2geC50roans

But I can't seem to get  AngularJS to work in here...

**Comment by dpgaspar** [comment]
Did the angularJS file loaded?

**Comment by dpgaspar** [comment]
I'll close this, if you want to you can reopen it later.
