### ISSUE TITLE
Clarification on parameter AUTH_LDAP_APPEND_DOMAIN

### ISSUE THREAD

**Issue by tylerwmarrs** [dpgaspar/Flask-AppBuilder#1524]
When I use this parameter to authenticate it works great for binding. However, when the search LDAP logic is executed, I am unable to find my user. This is due to the AUTH_LDAP_APPEND_DOMAIN setting being applied in the search.

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L799

Is there a way to have the authenticating user's credentials append the domain only during authentication and not during the search? Otherwise, I would like to have a configuration option that tells it to append on search.

```
AUTH_LDAP_APPEND_DOMAIN_ON_SEARCH = False
```
It can of course default to the original functionality of True. I just don't want to patch the code.

My employer uses Microsoft AD. Here are some of the settings that I'm using:

```
AUTH_LDAP_BIND_FIRST = False
AUTH_LDAP_SERVER = 'ldap://X.X.X.X:3268'
AUTH_LDAP_SEARCH = 'dc=XXXX,dc=com'
AUTH_LDAP_SEARCH_FILTER = '(objectClass=user)'
AUTH_LDAP_BIND_USER = ''
AUTH_LDAP_APPEND_DOMAIN = 'XXXX.com'
AUTH_LDAP_USERNAME_FORMAT = ''
AUTH_LDAP_BIND_PASSWORD = ''
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_ALLOW_SELF_SIGNED = False
AUTH_LDAP_TLS_DEMAND = False
AUTH_LDAP_TLS_CACERTDIR = ''
AUTH_LDAP_TLS_CACERTFILE = ''
AUTH_LDAP_TLS_CERTFILE = ''
AUTH_LDAP_TLS_KEYFILE = ''
AUTH_LDAP_UID_FIELD = 'samaccountname'
AUTH_LDAP_FIRSTNAME_FIELD = 'givenName'
AUTH_LDAP_LASTNAME_FIELD = 'sn'
AUTH_LDAP_EMAIL_FIELD = 'mail'
```

**Comment by tylerwmarrs** [comment]
Of course, after posting this I find a non-patching workaround. In my use case, I simply set the AUTH_LDAP_UID_FIELD to the same value as the AUTH_LDAP_EMAIL_FIELD, email.

**Comment by thesuperzapper** [comment]
@TVerse I believe the feature you request was implemented by my PR https://github.com/dpgaspar/Flask-AppBuilder/pull/1374, a version with this PR is yet to be released 

@dpgaspar says sometime this week https://github.com/dpgaspar/Flask-AppBuilder/pull/1374#issuecomment-776843223
