### ISSUE TITLE
How could we have an add_link in a new tab ?

### ISSUE THREAD

**Issue by Th4nat0s** [dpgaspar/Flask-AppBuilder#1527]
It's a simple question, not a technical issue..

How could we use the appbuilder.add_link to add to the menu an external ressource which open in a new tab ?
I had seen the doc nothing related.

I had try that :) 
appbuilder.add_link("test", href='https://perdu.com" target="_blank"', category='mytest', icon="fa-connectdevelop")
Of course, this kind of injection does not work due to html sanitisation.

Should I do build a custom baseview with a html code to launch it or is it a trick available ?

Thanks.

**Comment by ThomasP0815** [comment]
You can do this with javascript in a custom baselayout

custom_baselayout.html:

{{% extends 'appbuilder/baselayout.html' %}

{% block head_js %}
    {{ super() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('a:contains("test")').click(function () {
                window.open("https://perdu.com", '_blank');
            });
        });
    </script>
{% endblock %}

appbuilder = AppBuilder(App, db.session, base_template='custom_baselayout.html')
