### ISSUE TITLE
mass update

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#153]
Here mentions mass update but I cannot see example?

http://flask-appbuilder.readthedocs.org/en/latest/actions.html

So if a large database is changing then how to automatically update say every periodically, as well as click of a button?

I subclass list_template and added a 

form
```HTML5
<form action="/updateServices" method="post">
    <table>
        <tr><td><input name="update" type="submit" value="Update Status"/></td></tr>
    </table>
</form>
```

**Comment by dpgaspar** [comment]
If i understand correctly your question, you don't need to do that. 

The docs have a mass "update" example already, one that deletes the rows, you can do whatever you want with a user's selected rows on the list view.

``` python
@action("muldelete", "scheung38Update", "Do Sheung39 update?", "fa-rocket", single=False)
def muldelete(self, items):
    for item in items:
        # UPDATE YOUR ITEM HERE
        # FOR EXAMPLE item.col1 = 'NEW VALUE'
        self.appbuilder.session.commit()
    self.update_redirect()
    return redirect(self.get_redirect())
```

F.A.B. will automatically render an actions dropdown with all your registered actions for this ModelView.
