### ISSUE TITLE
Feature request : add actions in the listing buttons

### ISSUE THREAD

**Issue by Th4nat0s** [dpgaspar/Flask-AppBuilder#1530]
Hello, 
It will be nice to be able to add to simply add "buttons" for an entry. 
It will be usable like the @actions decorator but with icon link in the icon bar.

For now I had managed to do so with a model decorator. 
![image](https://user-images.githubusercontent.com/1728186/101279375-2cd0da00-37c2-11eb-9ae0-f9b8b84e9772.png)

Does it make sense ?

**Comment by dpgaspar** [comment]
I get your point, but I don't want to over engineer base model views with too many options/knobs. Best way could be by overriding or creating new list templates and using those. There are so many possibilities, that I think it's not the right path to support them all but to facilitate a few obvious cases and make it easy to change/extend/override. 

Would be great if you could make a PR with your solution has an example
