### ISSUE TITLE
Using SQLA Filter `FilterContians`

### ISSUE THREAD

**Issue by kaushalvivek** [dpgaspar/Flask-AppBuilder#1535]
https://github.com/dpgaspar/Flask-AppBuilder/blob/e21059fd0b8cf10c2eb98549e85e26103ef1de62/flask_appbuilder/models/sqla/filters.py#L114

```NotImplementedError: <function ilike_op at 0x7fc150244510>``` getting this error on using `FilterContains` to check if a column which stores an array contains an array of users (string), contains a particular user. Is there something I am doing wrong?

**Comment by ThomasP0815** [comment]
FilterContains is intended for string columns!

Have a look at the implementation (flask_appbuilder/models/sqla/filters):

     class FilterContains(BaseFilter):
        name = lazy_gettext("Contains")
        arg_name = "ct"
    
        def apply(self, query, value):
            query, field = get_field_setup_query(query, self.model, self.column_name)
            return query.filter(field.like("%" + value + "%"))
