### ISSUE TITLE
Role based issue

### ISSUE THREAD

**Issue by kalimuthu123** [dpgaspar/Flask-AppBuilder#1538]
Hi,
i am try to create a user (not a admin )only who is responsible for usermanagment ( exclude other permissions ).
i want him to create users and assign roles to them except admin permissions

summary : creating a user who's is not able to create admin users

Reply me the possibilites @mistercrunch 

thanks

**Comment by dpgaspar** [comment]
One possibility:

You have to custom develop a new list users views with a custom CRUD, on the edit and add form filter out the admin role. Then the user creator must only have permissions to this view (He can't be a full admin).
