### ISSUE TITLE
object 'myTable' has no attribute 'query'

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#154]
```python
from app import db
from app import Table
db.create_all()
myTable = Table(name='Tom')
db.session.add(myTable)
db.session.commit()
myTable = Table.query.all()

type(myTable)
flask_appbuilder.models.sqla.ModelDeclarativeMeta
```
type object 'myTable' has no attribute 'query'

**Comment by dpgaspar** [comment]
An sqlalchemy model does not have a query object.

The way to do it is:

``` python
db.session.query(YourModelName).query.all()
```

**Comment by scheung38** [comment]
auto completion stops at
```python
db.session.
```
so not sure how you managed to get:
```python
db.session.query
```

**Comment by dpgaspar** [comment]
Auto completion from PYCharm is not bullet proof and cannot be, because of the nature of python.

You need to know what objects you dealing with, db is an SQLAlchemy object, just go to the SQLAlchemy docs.

**Comment by MahmoudHegazi** [comment]
> ```python
> db.session.query(YourModelName).query.all()
> ```

it solved the problem
 but why `YourModelName.query.query.all()` not work  in   association table but works with normal tables
