### ISSUE TITLE
Question: REST API - combine id's with json result

### ISSUE THREAD

**Issue by dgleba** [dpgaspar/Flask-AppBuilder#1543]
I have been looking through the docs and googling, but I haven't found a solution.

### Environment

Flask-Appbuilder version:  3.1.1

pip freeze output: 

```
albe@ubu555c:/ap/test/532dkrcollection/549-flasks/549-a-flask-appbuilder-yard/549a-fab$ docker-compose run --rm flaskdev bash -c 'pip freeze'
apispec==3.3.2
attrs==20.3.0
Babel==2.9.0
click==7.1.2
colorama==0.4.4
defusedxml==0.6.0
dnspython==2.1.0
email-validator==1.1.2
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-Cors==3.0.10
Flask-JWT-Extended==3.25.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==3.1
importlib-metadata==3.3.0
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==3.10.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2020.5
PyYAML==5.3.1
six==1.15.0
SQLAlchemy==1.3.22
SQLAlchemy-Utils==0.36.8
typing-extensions==3.7.4.3
Werkzeug==1.0.1
WTForms==2.3.3
zipp==3.4.0
albe@ubu555c:/ap/test/532dkrcollection/549-flasks/549-a-flask-appbuilder-yard/549a-fab$

```

### Describe the expected results

I am looking for a way to get the `ids` within the `result` JSON, something like the following.

```
"result":[{"id":3, title":"www"},{"id":4, title":"33"}]
```

Can someone help suggest a way this can be done?

### Describe the actual results

Below, the `ids` are in an array separate from the `result` JSON object.

```
{"count":3,"ids":[3,4],"result":[{"title":"www"},{"title":"33"}]}
```

### Steps to reproduce

albe@vamp398:/srv/dkr/532dkrcollection/549-flasks/549-a-flask-appbuilder-yard/549a-fab$ 
curl -X GET "http://192.168.88.93:14224/api/v1/posts/?q=(columns:!(id,title),keys:!(none))" -H  "accept: application/json" -H "Authorization: Bearer $token"

**Comment by dpgaspar** [comment]
You can just add the `id` to the list of columns like this: https://github.com/apache/superset/blob/master/superset/databases/api.py#L130

check if it work!
