### ISSUE TITLE
Searching and filtering in related views

### ISSUE THREAD

**Issue by AlesMaver** [dpgaspar/Flask-AppBuilder#1548]
Dear Daniel,
firstly I would like to thank you for the excellent Flask AppBuilder - it makes it so easy to develop database backed websites and is currently very helpful for us!

Perhaps this is more of a feature request rather than a bug. I use related views in model views quite a lot, however, I noticed that there is no possibility to enable searching through the elements of the list in related views. Is there any possibility to add the "Search" field in the related views?

Additionally, for lists with fields obtained from related tables, it is not possible to add them to search columns and consequently it is not possible to search within lists that draw most of the information from relationships. FAB simply outputs an error when using the dotted notation, for example variants.genesymbol field:
`Was unable to import app Error: 'variants.genesymbol'`

The dotted notation also does not work for me in the base_filters section of the ModelView, despite the manual stating that:
> Since version 1.5.0 you can use base_filter with dotted notation, necessary joins will be handled for you on the background.

So it is possible that I may be using it wrong. 

If these features are not possible yet, do you think it would take a significant effort to implement them?
Thank you!

**Comment by AlesMaver** [comment]
I have just noticed that the question regarding searching in related views has been opened previously, but it seems that it is not yet implemented:
https://github.com/dpgaspar/Flask-AppBuilder/issues/624
https://github.com/dpgaspar/Flask-AppBuilder/issues/887

If anyone has any idea on how to enable interactive filtering (based on user selecting a filter or clicking a button in related view) in any other way, I would very much appreciate any advice. I have considered using @action but this is tied to selected items specifically. 

Thanks a lot!

**Comment by ThomasP0815** [comment]
Have a look in the example of my pull request.
#1432

**Comment by AlesMaver** [comment]
This is perfect - thanks for this work! Is your PR ready for testing - I will be happy to try it!

**Comment by ThomasP0815** [comment]
There are only little changes in the framework, which are necessary for the custom view in the example.
It's no perferct but it worked for me.
Feel free to test the example implementation.
