### ISSUE TITLE
google groups - Content unavailable

### ISSUE THREAD

**Issue by dgleba** [dpgaspar/Flask-AppBuilder#1549]
When I follow the link to google groups on this page, https://github.com/dpgaspar/Flask-AppBuilder, is says `Content unavailable`

**Comment by dpgaspar** [comment]
strange I can open it: https://groups.google.com/forum/#!forum/flask-appbuilder

**Comment by dgleba** [comment]
![image](https://user-images.githubusercontent.com/4622715/105999314-87c4d600-607b-11eb-81f5-707c8c5fc44a.png)

**Comment by dpgaspar** [comment]
got it, sorry, I've changed the permissions, so that anyone can see the group. Can you retry?

**Comment by dgleba** [comment]
It works now. Thanks.
