### ISSUE TITLE
condition for base_filters

### ISSUE THREAD

**Issue by luixx** [dpgaspar/Flask-AppBuilder#1557]
### Environment

Flask-Appbuilder version: 3.1.1

### Problem
Hi I want to show all data if the user has an admin role. If the user is not an admin the user should only see its own created data.
That the user sees its own created data is possible with the following code 

```python
base_filters = [['user_id', FilterEqualFunction, get_user]]
```

no i want to make something like this:

```python
base_filters = [['user_id', FilterEqualFunction, get_user],['user.roles', FilterNotEqual, 'Admin']]
```
Is there a possibilit to make a check something like this: if the user.roles is not admin then use the filer user_id == current_user.id

**Comment by dpgaspar** [comment]
it is you have to create your own custom Filter, for example: https://github.com/apache/superset/blob/master/superset/databases/filters.py#L26

Then reference it: https://github.com/apache/superset/blob/master/superset/databases/api.py#L91

**Comment by luixx** [comment]
thank you very much. i will try this out. i find a solution i will post it here.

**Comment by luixx** [comment]
I am still trying to figure out how is this supposed to work. Is there maybe a better solution instead of a filter. For example is it possible to query the table with the filter for the user role e.g. Model.query.filter(user.role=='Admin')? My model looks like this:

```
class MedicalProductPos(Model):
    id = Column(Integer, primary_key=True)
    serial_nr = Column(String(255))
    buy_date = Column(Date)
    first_use_date = Column(Date)
    stop_use_date = Column(Date)
    ce_label = Column(String(255))

    user_id = Column(Integer, ForeignKey('ab_user.id'), default=get_user_id, nullable=False)
    user = relationship("MyUser")

    created = Column(DateTime, index=True, default=datetime.utcnow)
    updated = Column(DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return self.name

    @classmethod
    def get_user_id(cls):
        try:
            return g.user.id
        except Exception:
            return None
```

**Comment by ThomasP0815** [comment]
from flask import g
      from flask_appbuilder.models.filters import BaseFilter
      from flask_appbuilder.security.sqla.models import Role
      from app import db

      class CustomAdminFilter(BaseFilter):
    
          def apply(self, query, value):
       
                adminRole = db.session.query(Role).filter(Role.name == "Admin").one()
                if not adminRole in g.user.roles:
                    return query.filter(MedicalProductsPos.user == g.user)
                else:
                     return query


     class MedicalProductsPosView(ModelView):

          base_filters = [['', CustomAdminFilter, None]]
