### ISSUE TITLE
Increasing the default length of User.username

### ISSUE THREAD

**Issue by a-mckinley** [dpgaspar/Flask-AppBuilder#157]
Hi @dpgaspar ,

As our LDAP server needs to use fully qualified usernames to bind (unfortunately out of my control) the default length of 32 characters is not enough.

Is there a recommended way to change this?  I think that I can easily override this field in a custom user class inheriting from User, but I am not sure if I can easily set my SecurityManager to use a custom derivative of RegisterUser where the 32 character limit also exists.

**Comment by dpgaspar** [comment]
I'll update this next version, i've found a bug also with charts and UTF-8 that i need to correct ASAP.
Do you think 64 is a valid size?

**Comment by a-mckinley** [comment]
64 is ok for me.

I wonder could this be more generically be solved by allowing simple subclassing of the RegisterUser model in addition to User?

**Comment by dpgaspar** [comment]
You will not be using RegisterUser with LDAP. The users are automatically inserted. SubClassing works for extra, but does not support overriding existing properties.

**Comment by a-mckinley** [comment]
What about an AbstractUser type with a list of required class properties something like:

```
class AbstractUser(object):
    required_props = ["name","email"]
    def __init__(self):
        for prop in self.required_props:
            if not hasattr(self,prop):
                raise Exception("%s class has no property %s" % (self.__class__.__name__,prop))

class BadUser(AbstractUser):
    name = "test"

class GoodUser(AbstractUser):
    name = "name"
    email = "email"

u1 = GoodUser()
u2 = BadUser()

```

**Comment by dpgaspar** [comment]
That's a very used approach, and a good one too. But I wanted to design something that the devs would not have to worry about security, or have to implement their own User Model. 

This would also present a problem when relating Role, Permissions etc... with the unknown (to the framework) User Model. Design decisions...
