### ISSUE TITLE
Invalid link in "about" of GitHub repo

### ISSUE THREAD

**Issue by thesuperzapper** [dpgaspar/Flask-AppBuilder#1574]
Currently the "about" section has an invalid link to http://flaskappbuilder.pythonanywhere.com/:
![Screen Shot 2021-02-26 at 09 53 32](https://user-images.githubusercontent.com/5735406/109230256-ab18a780-7818-11eb-9cac-583ecf34705f.png)

Lets fix this and link to the docs: https://flask-appbuilder.readthedocs.io/en/latest/

@dpgaspar

**Comment by thesuperzapper** [comment]
@dpgaspar this is kind of annoying, and you can fix it in like 2 seconds

**Comment by thesuperzapper** [comment]
@dpgaspar please, my OCD cant handle it! (All you need to do is click edit on the repo description, and fix the link)

**Comment by dpgaspar** [comment]
Fixed, renewed for another 3 months
