### ISSUE TITLE
[feature request] Password policy/Complexity

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [dpgaspar/Flask-AppBuilder#1576]
Currently Flask AppBuilder does not allow the password check for any complexity requirements, so we rely on the end users to setup a strong password.

It would be great if we could force some minimum complexity requirements in the password, so that end users can not set weak password.

**Comment by dpgaspar** [comment]
Agree this should be included. 

I'll make a config hook, with a simple default, that people can modify. Maybe a hookable field validator

**Comment by kamalkeshavani-aiinside** [comment]
@dpgaspar Can you please tag this to avoid getting stale label?

**Comment by dpgaspar** [comment]
@kamalkeshavani-aiinside new PR about to be merged will support custom complexity and default complexity. Feel free to comment on the PR

**Comment by dpgaspar** [comment]
@kamalkeshavani-aiinside thank you for your help, the PR is merged and will be released soon
