### ISSUE TITLE
Update flask-login from 0.4.1 (end of 2017) to current release

### ISSUE THREAD

**Issue by laroche** [dpgaspar/Flask-AppBuilder#1578]
Please update flask-login from the currently used version 0.4.1 (which was
released end of 2017) to a current version. Would be great to see such critical
parts of Flask-AppBuilder to be based on current software releases.

Thanks a lot for FAB,

Florian La Roche

**Comment by dpgaspar** [comment]
Just checked latest version is 0.5.0 and the previous was 0.4.1. Following semantic versioning this could be a breaking change. I'll check and bump
