### ISSUE TITLE
Admin users when using LDAP authentication

### ISSUE THREAD

**Issue by a-mckinley** [dpgaspar/Flask-AppBuilder#158]
Hi @dpgaspar ,

What is the correct method for creating admin users when using LDAP authentication?

I want the default user role to be "public" but having done this it looks like I cannot create an admin user.

Using fabmanger create-admin succeeds but the admin user fails to log in (I imagine because it is checking the LDAP server for a non LDAP user).

**Comment by dpgaspar** [comment]
Yes, if you change the authentication method for LDAP, all auth will be LDAP. You need to create an LDAP user using *fabmanager create-admin*

**Comment by a-mckinley** [comment]
Hi @dpgaspar,

Thanks for the speedy reply.  I am not sure that I understand.  It looks to me like create-admin just creates a user in the local database.  Does this mean I should use create-admin with the details of that LDAP user account before they first log in?  (I tried this procedure after log in which caused an IntegrityError as the new email is not unique).

**Comment by a-mckinley** [comment]
FYI this procedure seems to work.


1 .fabmanager create-db
2. fabmanager create-admin (with credentials of exisiting LDAP user)
3. fabmanager run
4. Login as admin LDAP user 

If you log in with this user before create-admin, this fails.

Perhaps an additional fabmanager command to give a particular an existing user admin rights would be useful for those using LDAP_AUTH?

**Comment by dpgaspar** [comment]
On OpenID, REMOTE_USER and LDAP authentication types, the framework authenticates using the defined type, then checks if the user is created on DB. So for LDAP, it will authenticate on your LDAP server and then check if the user exists on the DB.

Could you be more specific on the fabmanager command?

**Comment by a-mckinley** [comment]
Hi @dpgaspar ,

Thanks again for your quick response.

I was thinking something like:

```
fabmanager make-admin $existing_user
```

That means that if my users authenticate with my F.A.B server over LDAP, they can automatically get an unprivileged role and easily be given admin rights later.

**Comment by dpgaspar** [comment]
I see, this already exists in a nicer way.

Use the following config properties:

AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Low User'

"Low User": is a Role you have already created with limited privileges.
This way if a user authenticates on F.A.B. and does not exist on the DB, he/she will be created on the DB with the role "Low User".

**Comment by a-mckinley** [comment]
Hi @dpgaspar 

Thanks again for your help.

I actually was already using this feature with the AUTH_USER_REGISTRATION_ROLE set to "Public".
My issue arose when I needed to make one of these Public users into an admin.

**Comment by dpgaspar** [comment]
I'm getting an error testing this... haven't tested this one for a long time, it's throwing:

    UnboundLocalError: local variable 'ldap_user_info' referenced before assignment

Do you get this too?

**Comment by a-mckinley** [comment]
Is this without the new option set to True?  If so, this is the original error that I was seeing before my fix.
The problem is there is a path where you can successfully bind without first performing a search, which means ldap_user_info is not created.

I am not familiar with LDAP so I assumed that there was a reason for searching before binding.

In any case, I am fairly certain you should not attempt to add a user without searching the LDAP server, which I think is what you are seeing.

**Comment by dpgaspar** [comment]
I've done some rework on LDAP auth, specially for self user registration. could you please clone branch 1.3.7 and test?

**Comment by dpgaspar** [comment]
new version 1.3.7 is out. Update to solve this issue.
