### ISSUE TITLE
Schema of ab_user and other FAB databases

### ISSUE THREAD

**Issue by rodrigues-pedro** [dpgaspar/Flask-AppBuilder#1585]
This isn't a bug report, is more of a question, or an enhancement 

My databases are separated by environments (develop, homolog and prod),
In witch environment we have a multitude of projects, with a schema for each project.

When creating a FAB app it created a bunch of tables to save users, roles and permissions. but it created on the public schema, I wish there was a way to override this behavior without needing to override every single of the models.

I'm very new to SQLAlchemy and to Flask App Builder. If that's already a thing I'm sorry...

**Comment by rodrigues-pedro** [comment]
Don't know if this would work:
```
class Model(object):
    if get_app.config["APP_SCHEMA"]:
        __table_args__ = {"extend_existing": True, 'schema':get_app.config["APP_SCHEMA"]}
    else:
        __table_args__ = {"extend_existing": True}
```
but, adding a config option as APP_SCHEMA, then using it to set the __table_args__ may work...

**Comment by dpgaspar** [comment]
Hi @rodrigues-pedro,

there are a couple of ways of doing this, but it can depend on your engine, for postres one simple way it to:

``` python
SQLALCHEMY_ENGINE_OPTIONS'] = {"connect_args": {'options': f'-csearch_path={schema_name}'}}
```

**Comment by rodrigues-pedro** [comment]
I ended up doing it by using an SQLAlchemy Engine when creating my session.
Instead of:
```
db = SQLAlchemy(app)
appbuilder = AppBuilder(app, db.session)
```

I did:
```
db = SQLAlchemy(app)
db_eng = db.engine.execution_options(schema_translate_map= {None: "recsys"})
Session = sessionmaker(bind=db_eng)
db_sess = scoped_session(Session)
appbuilder = AppBuilder(app, db_sess)
```
