### ISSUE TITLE
Unable to Expose POST method in BaseView

### ISSUE THREAD

**Issue by naresnayak** [dpgaspar/Flask-AppBuilder#1601]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 3.2.1

pip freeze output:

### Describe the expected results

Tell us what should happen.

```python
Paste a minimal example that causes the problem.
```
#Bulk Email to Lead
class CustomView(BaseView):
    default_view = "bulkemail"  
    @expose("/bulkemail/",methods="POST")
    @has_access
    def bulkemail(self):       
            return self.render_template("bulkemail.html")

appbuilder.add_view(CustomView(), "Bulk Email",category="Utilities")

### Describe the actual results

Tell us what happens instead.

I want to send the html template form data to the Baseview.

```pytb
Paste the full traceback if there was an exception.
```
**The method is not allowed for the requested URL.**

**Comment by soundmaking** [comment]
If you’re accessing your view via “utilities” in the navigation, then you will need GET as well as POST

methods=("GET", “POST”)

?
