### ISSUE TITLE
Update AzureAD - Relax must be required fields

### ISSUE THREAD

**Issue by hyunjong-lee** [dpgaspar/Flask-AppBuilder#1612]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 3.2.2

pip freeze output:

### Describe the expected results

Current code requires `given_name` must be required.
- https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L602-L609

I explicitly claimed `given_name` in token configuration, however, it does not give `given_name` field if the value is empty.

![image](https://user-images.githubusercontent.com/391920/114808658-a79aa900-9de3-11eb-8ce5-26a25052d922.png)

Therefore, I can't login with AzureAD because `given_name` field does not exist.

> superset_app             | 2021-04-13 04:53:27,972:ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'given_name'

Fields from token

> superset_app             | 2021-04-15 02:46:34,089:DEBUG:flask_appbuilder.security.manager:Parse JWT token : {'aud': '', 'iss': '', 'iat':, 'nbf':, 'exp':, 'amr': [''], 'email': '', 'family_name': '', 'ipaddr': '', 'name': '', 'oid': '', 'onprem_sid': '', 'rh': '', 'roles': ['Admin'], 'sub': '', 'tid': '', 'unique_name': '', 'upn': '', 'ver': '1.0'}

```python
```

### Describe the actual results

I created a new pypi project with the fixes.
- https://pypi.org/project/Flask-AppBuilder-AzureAD/

The result shows that I can login without `given_name` field with AzureAD.

```pytb
```

### Steps to reproduce

It can be reproduced with AzureAD with an account which does not have `given_name` field.

**Comment by dpgaspar** [comment]
@hyunjong-lee thank you for the fix, this should be released soon
