### ISSUE TITLE
Certificate Failure

### ISSUE THREAD

**Issue by valhuber** [dpgaspar/Flask-AppBuilder#1614]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 

pip freeze output:

(venv) val@Vals-MacBook-Pro-16 ApiLogicServer % pip freeze
aniso8601==9.0.1
ApiLogicServer==2.0.7
apispec==3.3.2
attrs==20.3.0
Babel==2.9.0
cffi==1.14.5
click==7.1.2
colorama==0.4.4
cryptography==3.4.7
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.1
Flask==1.1.2
Flask-Admin==1.5.7
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-Cors==3.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-RESTful==0.3.8
flask-restful-swagger-2==0.35
Flask-SQLAlchemy==2.5.1
flask-swagger-ui==3.36.0
Flask-WTF==0.14.3
idna==3.1
inflect==5.0.2
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
logicbank==0.9.6
logicbankutils==0.6.0
MarkupSafe==1.1.1
marshmallow==3.11.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
pycparser==2.20
PyJWT==1.7.1
PyMySQL==1.0.2
pyodbc==4.0.30
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.15.0
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
safrs==2.11.2
six==1.15.0
SQLAlchemy==1.3.20
SQLAlchemy-Utils==0.36.8
Werkzeug==1.0.1
WTForms==2.3.3
(venv) val@Vals-MacBook-Pro-16 ApiLogicServer % 

### Describe the expected results

Tell us what should happen.

```python
Should build flask app directories.... 
```

### Describe the actual results

Tell us what happens instead.
Sorry, intermittent - has occurred on PC and Mac...

```pytb
Something went wrong <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

### Steps to reproduce
My app issues the following (not via the CLI):
```
flask fab create-app --name /Users/val/dev/servers/api_logic_server/ui/basic_web_app --engine SQLAlchemy
```

**Comment by dpgaspar** [comment]
Hi @valhuber,

Take a look at https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

So it depends on your OS, normally this means that your OS CA trust store is out of date

**Comment by valhuber** [comment]
Thanks!

A colleague discovered a similar article, so I placed both references in our [Trouble Shooting](https://github.com/valhuber/ApiLogicServer/wiki/Troubleshooting#certificate-failures).

**Comment by dpgaspar** [comment]
Nice, thanks @valhuber
