### ISSUE TITLE
Can't connect to ldap (superset)

### ISSUE THREAD

**Issue by fropa** [dpgaspar/Flask-AppBuilder#1615]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 3.2.2

pip freeze output:

aiohttp==3.7.4.post0
alembic==1.5.8
amqp==2.6.1
apache-superset==0.38.1
apispec==3.3.2
async-timeout==3.0.1
attrs==20.3.0
Babel==2.9.0
backoff==1.10.0
billiard==3.6.4.0
bleach==3.3.0
Brotli==1.0.9
cachelib==0.1.1
celery==4.4.7
cffi==1.14.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
contextlib2==0.6.0.post1
croniter==1.0.10
cryptography==3.4.7
dataclasses==0.8
decorator==5.0.5
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.2
Flask==1.1.2
Flask-AppBuilder==3.2.2
Flask-Babel==1.0.0
Flask-Cache==0.13.1
Flask-Caching==1.10.1
Flask-Compress==1.9.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-Migrate==2.7.0
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
flask-talisman==0.7.0
Flask-WTF==0.14.3
geographiclib==1.50
geopy==2.1.0
gunicorn==20.0.4
humanize==3.3.0
idna==3.1
idna-ssl==1.1.0
importlib-metadata==3.10.0
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
kombu==4.6.11
ldap3==2.9
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==1.1.1
marshmallow==3.11.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
msgpack==1.0.2
multidict==5.1.0
numpy==1.19.5
packaging==20.9
pandas==1.1.5
parsedatetime==2.6
pathlib2==2.3.5
Pillow==8.2.0
polyline==1.4.0
prison==0.1.3
py==1.10.0
pyarrow==1.0.1
pyasn==1.6.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyJWT==1.7.1
pyldap @ file:///home/btsiklauri/pyldap-3.0.0.post1-py3-none-any.whl
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.17.0
python-editor==1.0.4
python-geohash==0.8.5
python-ldap==3.3.1
python3-ldap==0.9.8.4
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
retry==0.9.2
selenium==3.141.0
simplejson==3.17.2
six==1.15.0
slackclient==2.5.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.36.8
sqlparse==0.3.0
typing-extensions==3.7.4.3
urllib3==1.26.4
vine==1.3.0
webencodings==0.5.1
Werkzeug==1.0.1
WTForms==2.3.3
WTForms-JSON==0.3.3
yarl==1.6.3
zipp==3.4.1

### Describe the expected results

I'm trying to connect ldap from apache superset with flask-appbuilder

the error is "ERROR:flask_appbuilder.security.manager:LDAP search for '(uid=myuser)' in scope 'DC=,DC=' returned multiple results
"

from flask_appbuilder.security.manager import AUTH_DB,AUTH_LDAP

the config : 
AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = X.X.X.X"
AUTH_LDAP_BIND_USER = "CN=,OU=,DC=,DC="
AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_SEARCH = "DC=,DC="
AUTH_LDAP_UID_FIELD = "uid"

**Comment by dpgaspar** [comment]
@fropa this is fixed here: https://github.com/dpgaspar/Flask-AppBuilder/pull/1602

3.2.3 will be out this week with the fix
