### ISSUE TITLE
I can't manage to force a redirect on post_add

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#162]
I have this now:
```
return redirect(url_for('TemplateView.list'))
```
and it builds the url correctly in post_add method, but allways goes back in history instead. Should I put it in another method?

**Comment by dpgaspar** [comment]
The *post_add* is intended to be used to change your models after the record is added.

If you need to do this, you can try an hack, override the add method for ModelView:

``` python
@expose('/add', methods=['GET', 'POST'])
    @has_access
    def add(self):

        widget = self._add()
        if not widget:
            return redirect(url_for('TemplateView.list'))
        else:
            return self.render_template(self.add_template,
                                        title=self.add_title,
                                        widgets=widget)
```

I've not tested it, but it should work.

**Comment by jvinolas** [comment]
Thanks, it worked!
