### ISSUE TITLE
Any plans to update to SQLAlchemy 1.4.11 (it currently resets SQLAlchemy to 1.3.24)

### ISSUE THREAD

**Issue by valhuber** [dpgaspar/Flask-AppBuilder#1621]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:

pip freeze output:

(venv) val@Vals-MacBook-Pro-16 XpiLogicServer % pip freeze
aniso8601==9.0.1
apispec==3.3.2
attrs==20.3.0
Babel==2.9.0
cffi==1.14.5
click==7.1.2
colorama==0.4.4
cryptography==3.4.7
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.2
Flask==1.1.2
Flask-Admin==1.5.8
Flask-AppBuilder==3.2.2
Flask-Babel==1.0.0
Flask-Cors==3.0.10
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-RESTful==0.3.8
flask-restful-swagger-2==0.35
Flask-SQLAlchemy==2.5.1
flask-swagger-ui==3.36.0
Flask-WTF==0.14.3
greenlet==1.0.0
idna==3.1
inflect==5.0.2
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
logicbankutils==0.6.0
MarkupSafe==1.1.1
marshmallow==3.11.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
pycparser==2.20
PyJWT==1.7.1
PyMySQL==1.0.2
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.17.0
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
safrs==2.11.2
six==1.15.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.36.8
Werkzeug==1.0.1
WTForms==2.3.3
(venv) val@Vals-MacBook-Pro-16 XpiLogicServer % 

### Describe the expected results
Replace my installed SQLAlchemy version, as described below.

Tell us what should happen.
Would like option to utilize latest SQLAlchemy (1.4.11).  Not so simple, I realize - it's not compatible.

```python
Paste a minimal example that causes the problem.
```

### Describe the actual results

Tell us what happens instead.

```pytb
Installing collected packages: SQLAlchemy, flask-appbuilder
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 1.4.11
    Uninstalling SQLAlchemy-1.4.11:
      Successfully uninstalled SQLAlchemy-1.4.11
Successfully installed SQLAlchemy-1.3.24 flask-appbuilder-3.2.2

```

### Steps to reproduce
create a venv with SQLAlchemy 1.4.11, then install flask-appbuilder
you will see the output above, where SQLAlchemy 1.4.11 is replaced by 1.3.24 as shown in pip freeze, above.

**Comment by dpgaspar** [comment]
Good question, yes this is currently pending by: https://github.com/pallets/flask-sqlalchemy/issues/953
