### ISSUE TITLE
Dissuade users from modifying roles through UI if AUTH_ROLES_SYNC_AT_LOGIN is enabled

### ISSUE THREAD

**Issue by cccs-rc** [dpgaspar/Flask-AppBuilder#1627]
### Environment

Flask-Appbuilder version: 3.2.1

<details>
  <summary>pip freeze output</summary>
aiohttp==3.7.2
alembic==1.4.3
amqp==2.6.1
apispec==3.3.2
async-timeout==3.0.1
attrs==20.2.0
Authlib==0.15.2
Babel==2.8.0
backoff==1.10.0
billiard==3.6.3.0
bleach==3.2.1
boto3==1.16.10
botocore==1.19.10
Brotli==1.0.9
cached-property==1.5.2
cachelib==0.1.1
celery==4.4.7
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.4
contextlib2==0.6.0.post1
convertdate==2.3.0
cron-descriptor==1.2.24
croniter==0.3.36
cryptography==3.2.1
decorator==4.4.2
defusedxml==0.6.0
Deprecated==1.2.11
dnspython==2.0.0
elasticsearch==7.12.1
elasticsearch-dbapi==0.2.1
email-validator==1.1.1
et-xmlfile==1.0.1
Flask==1.1.2
Flask-AppBuilder==3.2.1
Flask-Babel==1.0.0
Flask-Caching==1.9.0
Flask-Compress==1.8.0
Flask-Cors==3.0.9
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Migrate==2.5.3
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
flask-talisman==0.7.0
Flask-WTF==0.14.3
future==0.18.2
geographiclib==1.50
geopy==2.0.0
gunicorn==20.0.4
holidays==0.10.3
humanize==3.1.0
idna==2.10
ijson==3.1.2.post0
importlib-metadata==2.1.1
isodate==0.6.0
itsdangerous==1.1.0
jdcal==1.4.1
Jinja2==2.11.3
jmespath==0.10.0
jsonlines==1.2.0
jsonschema==3.2.0
kombu==4.6.11
korean-lunar-calendar==0.2.1
linear-tsv==1.1.0
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==1.1.1
marshmallow==3.9.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
msgpack==1.0.0
multidict==5.0.0
mysql-connector-python==8.0.23
mysqlclient==1.4.2.post1
natsort==7.0.1
numpy==1.19.4
openpyxl==3.0.5
packaging==20.4
pandas==1.2.2
parsedatetime==2.6
pathlib2==2.3.5
pgsanity==0.2.9
Pillow==7.2.0
polyline==1.4.0
prison==0.1.3
protobuf==3.15.8
psycopg2==2.8.5
psycopg2-binary==2.8.5
py==1.9.0
pyarrow==3.0.0
pycparser==2.20
pydruid==0.6.1
PyGithub==1.54.1
PyHive==0.6.3
PyJWT==1.7.1
PyMeeus==0.3.7
pyparsing==2.4.7
pyrsistent==0.16.1
python-dateutil==2.8.1
python-dotenv==0.15.0
python-editor==1.0.4
python-geohash==0.8.5
python-json-logger==2.0.1
python3-openid==3.2.0
pytz==2020.4
PyYAML==5.4.1
redis==3.2.1
requests==2.24.0
retry==0.9.2
rfc3986==1.4.0
s3transfer==0.3.3
sasl==0.2.1
selenium==3.141.0
simplejson==3.17.2
six==1.15.0
slackclient==2.5.0
SQLAlchemy==1.3.20
sqlalchemy-trino==0.2.2
SQLAlchemy-Utils==0.36.8
sqlparse==0.3.0
tableschema==1.20.0
tabulator==1.52.5
thrift==0.13.0
thrift-sasl==0.4.2
trino==0.305.0
typing-extensions==3.7.4.3
unicodecsv==0.14.1
urllib3==1.25.11
vine==1.3.0
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.12.1
WTForms==2.3.3
WTForms-JSON==0.3.3
xlrd==1.2.0
yarl==1.6.2
zipp==3.4.0
</details>

### Describe the expected results

As of 3.2.0, FAB has supported an AUTH_ROLES_SYNC_AT_LOGIN flag, which re-syncs a user's roles every time they login. This means that, if someone manually modifies a user's roles through the UI (UserModelView?), those modifications won't persist between logins. This can cause some confusion!

I see two options that might help alleviate this confusion:

1) A warning (or a flag to enable a warning) on the "Edit User" page indicating that AUTH_ROLES_SYNC_AT_LOGIN is set to true and any changes made to a users' roles won't persist between logins.

e.g.:
![image](https://user-images.githubusercontent.com/62034438/116550881-45eb3c00-a8c5-11eb-8750-2683fef26974.png)

Alternatively, maybe a message that appears only if/when someone modified the Role field would be an option.

![image](https://user-images.githubusercontent.com/62034438/116550373-b04fac80-a8c4-11eb-9143-832e272e514d.png)

2) Disable the editable "Roles" field in the "Edit User" page if AUTH_ROLES_SYNC_AT_LOGIN is enabled (or have a flag to optionally disable the field). However, this seems a bit restrictive. It can be useful to manually add a role either as a temporary measure to allow a user to do something they wouldn't normally do, or for testing purposes to verify if an added role will, in fact, allow a user to do what they want to do.

### Describe the actual results

There is no indication in the UI that AUTH_ROLES_SYNC_AT_LOGIN is set to true. A user's roles can be modified, these modifications persist for the duration of that user's session and then, the next time they log in, those roles have been reverted. 

### Steps to reproduce

1. Set AUTH_ROLES_SYNC_AT_LOGIN to true in app's config
2. Login to app as an Admin user
3. Modify a user's Roles via the "Edit User" view. Add a role they are not granted through configuration.
4. Login as the user whose roles were modified. 
5. Check the user's roles; the newly added roles have been removed.

**Comment by thesuperzapper** [comment]
@dpgaspar I like this proposal, what are your thoughts?

**Comment by dpgaspar** [comment]
@thesuperzapper me too, planning on doing it on this next 2 week slot

**Comment by naveenbussari** [comment]
@cccs-rc is there any way to enable this config AUTH_ROLES_SYNC_AT_LOGIN for specific user/role only but not all the users at a time
