### ISSUE TITLE
Google OpenID Connect

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#163]
I can't get OpenID work with appbuilder and I've found that google has shutdown OAuth2 and now uses OpenID Connect protocol.
```
Important: OpenID 2.0 is no longer supported. If your app uses OpenID 2.0, you must migrate your app by the shutdown date April 20, 2015, as shown in the migration timetable.
https://developers.google.com/identity/protocols/OpenID2
```
I've seen that the libraries that appbuilder use are python-openid and Flask-OpenID that I see on their documentation that use the extinc OpenID 2.0 instead of OpenID Connect.

So, is that the problem I'm facing?

**Comment by dpgaspar** [comment]
Thank you for reporting this.

Looks like OpenID is dead, at least for Google. OpenID connect is an OAuth authentication mechanism, i have some work done with OAuth but it's not so easy to integrate on the framework...

Is your work heavily based on Google OpenID?

**Comment by jvinolas** [comment]
I'm just creating new app. It will be nice to let my users self register using Google OpenID. For now I'll use database & email registering.

Thanks!

**Comment by dpgaspar** [comment]
New version 1.4.0 will include OAuth authentication and self register for users. You will be able to authenticate users with Google.

Take a look at the milestones.

**Comment by jvinolas** [comment]
Thanks, I will wait for new version. For now it is enough with email registering, that works great!
