### ISSUE TITLE
Can't order fields in Views using mongoengine

### ISSUE THREAD

**Issue by osk386** [dpgaspar/Flask-AppBuilder#164]
Hi, I 've using this sample shown in flask-appbuilder mongo views docs :

http://flask-appbuilder.readthedocs.org/en/latest/quickhowto_mongo.html

----------------------------------------------------------------------------------------------------------------
on my init.py:

import logging
from flask import Flask
from flask_appbuilder import AppBuilder
from flask_appbuilder.security.mongoengine.manager import SecurityManager
from flask_mongoengine import MongoEngine

logging.getLogger().setLevel(logging.DEBUG)

app = Flask(__name__)
app.config.from_object('config')
dbmongo = MongoEngine(app)
# The Flask-AppBuilder init
appbuilder = AppBuilder(app, security_manager_class=SecurityManager)

from app import models, views

----------------------------------------------------------------------------------------------------------------

views.py

from flask.ext.appbuilder import ModelView
from flask.ext.appbuilder.models.mongoengine.interface import MongoEngineInterface
from app import appbuilder
from models import Contact,ContactGroup

class ContactModelView(ModelView):
    datamodel = MongoEngineInterface(Contact)

    label_columns = {'contact_group':'Contacts Group'}
    list_columns = ['name','personal_celphone','birthday','contact_group']

    show_fieldsets = [
        ('Summary',{'fields':['name','address','contact_group']}),
        ('Personal Info',{'fields':['birthday','personal_phone','personal_celphone'],'expanded':False}),
        ]

class GroupModelView(ModelView):
    datamodel = MongoEngineInterface(ContactGroup)
    related_views = [ContactModelView]

----------------------------------------------------------------------------------------------------------------

models.py:

from mongoengine import Document
from mongoengine import DateTimeField, StringField, ReferenceField, ListField

class ContactGroup(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return self.name

class Gender(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

class Tags(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

class Contact(Document):
    name = StringField(max_length=60, required=True, unique=True)
    address = StringField(max_length=60)
    birthday = DateTimeField()
    personal_phone = StringField(max_length=20)
    personal_celphone = StringField(max_length=20)
    contact_group = ReferenceField(ContactGroup, required=True)
    gender = ReferenceField(Gender, required=True)
   tags = ListField(ReferenceField(Tags))

----------------------------------------------------------------------------------------------------------------

But I cant get that system display in given order: 

list_columns = ['name','personal_celphone','birthday','contact_group']

    show_fieldsets = [
        ('Summary',{'fields':['name','address','contact_group']}),
        ('Personal Info',{'fields':['birthday','personal_phone','personal_celphone'],'expanded':False}),
        ]

Whats wrong?

Where this order is defined? 

![selection_001](https://cloud.githubusercontent.com/assets/1568533/7353615/8e17e3b4-ecda-11e4-8a75-07a260e86498.png)

Thanks for your answer

**Comment by dpgaspar** [comment]
show_fieldsets is for the show page, use edit_fieldsets or add_fieldsets for edit or add forms.
The syntax is the same.

**Comment by osk386** [comment]
That's right! thank you.
