### ISSUE TITLE
Custom Show "View" for a ModelView.

### ISSUE THREAD

**Issue by Th4nat0s** [dpgaspar/Flask-AppBuilder#1644]
Hello, 

I can't find an example or documentation for what I try to do. I want to setup a custom Show "view" template for a Modelview, ( changing the html template). But I want to leave edit and list as usual.

Is it possible, I can I achieve this ?

MultipleViewsExp is not what I look for.

Thank's.

**Comment by soundmaking** [comment]
If you only need to change the html template, then set `show_template = 'path/to/template.html'` 

`self.show_template` is used in the show function in class ModelView : 

https://github.com/dpgaspar/Flask-AppBuilder/blob/27b15e59316e85e0fe62b8aa9978391ed4c729c9/flask_appbuilder/views.py#L562-L573

It gets its default value in the class BaseCRUDView:

https://github.com/dpgaspar/Flask-AppBuilder/blob/3dd1eb28cb7646de2739491ca5e3e2c703ab7201/flask_appbuilder/baseviews.py#L795-L796

**Comment by Th4nat0s** [comment]
Hi, @soundmaking thank's for your help.

According to https://flask-appbuilder.readthedocs.io/en/latest/customizing.html I tried to change simply for view for one modelview.

I got the following

` class CustomerView(ModelView):
      datamodel = SQLAInterface(Customer)
      show_template = "test.html"
`
test.html is located in the app/templates folder.

**Comment by dpgaspar** [comment]
@Th4nat0s 
Take a look at: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickhowto2/app/views.py

See if it helps
