### ISSUE TITLE
flask-migrate using app factory pattern

### ISSUE THREAD

**Issue by japs** [dpgaspar/Flask-AppBuilder#1654]
### Environment

Flask-Appbuilder version: Flask-AppBuilder==3.1.0
(Using an older version due to incompatibility with other packages in production)

pip freeze output:

```
alembic==1.6.5
apispec==3.3.2
attrs==21.2.0
Babel==2.9.1
click==7.1.2
colorama==0.4.4
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.3
Flask==1.1.4
Flask-AppBuilder==3.1.0
Flask-Babel==1.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-Migrate==3.0.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.15.1
greenlet==1.1.0
idna==3.2
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
Mako==1.1.4
MarkupSafe==2.0.1
marshmallow==3.12.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.26.1
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
six==1.16.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.37.7
Werkzeug==1.0.1
WTForms==2.3.3
```

### Describe the expected results

I would like to use `flask-migrate` to handle db migrations. The db should be initialised, migrated and upgraded with `flask db init / migrate / upgrade`. Migrate should be able to compare the schema with the actual db and register changes with migrate, then apply them to the db with upgrade.

I'm aware of the example https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickmigrate and of #738, however I wasn't able to use them to solve the problem.

```
# app.py
from flask import Flask
from flask_appbuilder import AppBuilder, SQLA
from flask_migrate import Migrate
import os
from flask_appbuilder import Model
from sqlalchemy import Column, Integer


class Config():
    basedir = os.path.abspath(os.path.dirname(__file__))
    SQLALCHEMY_DATABASE_URI = \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False


db = SQLA()
migrate = Migrate()
appbuilder = AppBuilder()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)

    with app.app_context():
        appbuilder.init_app(app, db.session)
        appbuilder.post_init()

    return app


class MyTable(Model):
    __tablename__ = "my_table"

    id = Column(Integer, primary_key=True)
    mycol = Column(Integer)


if __name__ == "__main__":
    app = create_app()
    app.run()
```

### Describe the actual results

The db gets created by `flask-appbuilder`, so `flask-migrate` is presented with an already up-to-date db and cannot register changes.

### Steps to reproduce

Start with no db and issue
```
export FLASK_APP=app.py
flask db init
flask db migrate
```
The output reads "INFO  [alembic.env] No changes in schema detected".

**Comment by dpgaspar** [comment]
Currently flask-appbuilder will initially create all your models. You can use `flask-migrate` to version your changes from the initial point forward exactly has you mentioned.

So after:
```
export FLASK_APP=app.py
flask db init
flask db migrate
```

Edit your `app.py` and add a column to `MyTable`:

``` python
class MyTable(Model):
    __tablename__ = "my_table"

    id = Column(Integer, primary_key=True)
    mycol = Column(Integer)
    newcol = Column(Integer)
```

then:
```
flask db migrate
```

assert that a new revision file get's generated with:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_table', sa.Column('newcol', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_table', 'newcol')
    # ### end Alembic commands ###
```

migrate the db:
```
flask db upgrade
```

To have the full migration with the initial state included you have to override the security manager and change `create_db`.  Then use `FAB_UPDATE_PERMS` to False. The idea is to bypass FAB DB creation. I'll make a change with a new config key `FAB_DB_CREATE` to bypass the database creation to better support this pattern
