### ISSUE TITLE
[Feature] Google groups - RBAC role mapping

### ISSUE THREAD

**Issue by rng-spokeo** [dpgaspar/Flask-AppBuilder#1657]
Description
With Google OAuth authentication enabled, users able to login without pre-creating user account in Airflow. However, AUTH_ROLES_MAPPING won't work with Google provider because Google OAuth v2 API do not return user's group information.

So, can we add a new feature for Google groups - RBAC role mapping. Maybe with Google Service Account setting and Admin SDK API call? With this feature, we can fully automate the authentication and authorization processes.

Thank you!

**Comment by dpgaspar** [comment]
For sure! ping me when you have a PR up
