### ISSUE TITLE
modal search form to select

### ISSUE THREAD

**Issue by enricosecco** [dpgaspar/Flask-AppBuilder#1659]
(my english is awful and this is an automatic translation, i hope correct ...)

I don't want to report an error but a gap (for me).
When you create a form in which there is a select field it happens that the select is not the most appropriate component.
If I have to choose between a very large number of complex entities, I should be able to search for the necessary entity by means of a search tool that allows an articulated selection.
A component would be needed (I am thinking for example of a search modal form ...) that allows you to choose the entity and thus populate the field that refers it to the basic form.
I don't know how to do it by respecting the rules and the structure of flask-appbuilder but only by building a form completely from scratch.
Do you think it is possible to realize it with the components present in the framework?
Thank you
Enrico

**Comment by dpgaspar** [comment]
Don't think so, building from scratch would obviously work, maybe you can take a stab at creating your own custom Select widget
