### ISSUE TITLE
encrypt uploaded file

### ISSUE THREAD

**Issue by enricosecco** [dpgaspar/Flask-AppBuilder#1661]
hi, I need to encrypt the uploaded files and of course decrypt them on download.
I guess this needs to be done by defining a new filemanager but I don't know how to configure the app to use the new filemanager and not the default one.
Can you give me advice?

**Comment by AlesMaver** [comment]
This may not be a direct answer to your question, but I have found a nice guide that describes the implementation of a custom filemanager for handling S3 AWS files: [https://github.com/dpgaspar/Flask-AppBuilder/issues/851](https://github.com/dpgaspar/Flask-AppBuilder/issues/851)

**Comment by enricosecco** [comment]
Really very informative. My case should be simpler and the help code has more of what I need. Thank you very much for the information.
