### ISSUE TITLE
pip install failed with dependency conflicts but pip3 worked

### ISSUE THREAD

**Issue by biofool** [dpgaspar/Flask-AppBuilder#1664]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:
Flask-AppBuilder==3.3.1

pip freeze output:
apispec==3.3.2
attrs==21.2.0
Babel==2.9.1
click==7.1.2
colorama==0.4.4
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.3
Flask==1.1.4
Flask-AppBuilder==3.3.1
Flask-Babel==1.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
idna==3.2
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==2.0.1
marshmallow==3.12.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
Pillow==8.3.0
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
six==1.16.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.37.8
Werkzeug==1.0.1
WTForms==2.3.3

### Describe the expected results

Tell us what should happen.

```python
pip install flask-appbuilder
#  Should succeed without error
```

### Describe the actual results

Install failed with dependency conflicts in Jinja others
```pytb
Paste the full traceback if there was an exception.
```

### Steps to reproduce

My initial attempt to reproduce failed

**Comment by dpgaspar** [comment]
Hard to troubleshoot without any logs or errors, the reference to pip3 make me wonder if you were using python 2.

Closing this issue, feel free to reopen with more info.
