### ISSUE TITLE
User List UI in security not showing plus sign

### ISSUE THREAD

**Issue by saurasingh** [dpgaspar/Flask-AppBuilder#1667]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

Responsible disclosure:
We want to keep Flask-AppBuilder safe for everyone. If you've discovered a security vulnerability
please report to danielvazgaspar@gmail.com.

### Environment

Flask-Appbuilder version: 3.3.0

pip freeze output:

### Describe the expected results
We are using FAB with airflow2.0 and with azure AD. Things are working fine people are able to join as Admin but I am missing plus sign to edit users roles. 

![Screen Shot 2021-07-08 at 10 07 05 AM](https://user-images.githubusercontent.com/19628707/124952203-04bc8a00-dfe2-11eb-884a-21811df4506c.png)

I can see the plus sign in the list role panel. Also here is permission associated with the Admin role.

![Screen Shot 2021-07-08 at 11 46 49 AM](https://user-images.githubusercontent.com/19628707/124953517-3aae3e00-dfe3-11eb-98f8-b5369a544b06.png)

Not able to figure out why this is happening.

**Comment by asimerel** [comment]
I have the exact same problem with LDAP authentication. I can't change users role.

**Comment by saurasingh** [comment]
@asimerel Was it working for you before.

**Comment by asimerel** [comment]
@saurasingh It was working until upgrading the airflow to 2.1.0 . Also it is not working on airflow 2.1.1 too.

**Comment by saurasingh** [comment]
@asimerel Same for me it did work just once and then it stopped and that too on 2.1.0 .

**Comment by kaxil** [comment]
@saurasingh @asimerel Can you test my downgrading FAB version?

```
pip install -U Flask-AppBuilder==3.2.3
```

**Comment by asimerel** [comment]
hi @kaxil ,
I tried with downgrading Flask-Appbuilder to 3.2.3 but the problem is still exist, nothing changed.

**Comment by kaxil** [comment]
@asimerel If it worked with `Flask-Appbuilder` 3.2.3 with Airflow 2.0.2 or something than it is an Airflow Issue -- we will fix it as part of Airflow. But can you confirm it works with `Flask-Appbuilder` 3.2.3 with Airflow 2.0.2 please?

**Comment by asimerel** [comment]
@kaxil 
I tested now, the plus sign and the user edit buttons are available with airflow==2.0.2 and Flask-AppBuilder==3.2.3

**Comment by kaxil** [comment]
OK that basically means that something broke it in Airflow itself in 2.1.0 or 2.1.1

**Comment by saurasingh** [comment]
@kaxil Yes I am can also confirm that  the user edit buttons are available with airflow==2.0.2 and Flask-AppBuilder==3.2.3.

**Comment by dpgaspar** [comment]
@kaxil from my understanding this is not a FAB issue, is this corret?

**Comment by kaxil** [comment]
@dpgaspar Yup that is correct, safe to close this issue and we can tackle it on the Airflow side

**Comment by dpgaspar** [comment]
ok, feel free to ping if I can help in any way
