### ISSUE TITLE
Self registering with email doing nothing

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#167]
I activated database & email registering in a running appbuilder site but nothing happens when I click on register (login page reloads). This is more or less what I've done:

```
pip install flask-email
```
And in config.py
```
AUTH_TYPE = AUTH_DB
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "demo"
RECAPTCHA_PUBLIC_KEY = 'set google public key'
RECAPTCHA_PRIVATE_KEY = 'set google private key'
MAIL_SERVER = 'mail.example.com'
MAIL_USE_TLS = True
MAIL_USERNAME = 'info@example.com'
MAIL_PASSWORD = 'mypassword'
MAIL_DEFAULT_SENDER = 'register@example.com'
```
Do I need anything else?

**Comment by dpgaspar** [comment]
Sorry, this feature is disabled/not functioning now, i'll correct this ASAP with 1.3.7 release.

**Comment by jvinolas** [comment]
Thanks. It is important that there is an available self registering method, either OpenID or email. If not, there is no other way to let users self register in my app.

**Comment by dpgaspar** [comment]
No, problem this should be working. self register is working (on 1.3.7 not yet released) for auth_db, auth_ldap and auth_openid (but openid is dead for google).
