### ISSUE TITLE
Upgrade Jquery to 3.5.0 or greater due to vulnerability

### ISSUE THREAD

**Issue by HardikVijayPatel** [dpgaspar/Flask-AppBuilder#1671]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

Responsible disclosure:
We want to keep Flask-AppBuilder safe for everyone. If you've discovered a security vulnerability
please report to danielvazgaspar@gmail.com.

Flask-Appbuilder version: 3.3.1

Tell us what happens instead.
Currently Jquery version used is 3.4.1, need to update to 3.5 or higher due to security vulnerability
### Steps to reproduce

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/static/appbuilder/js/jquery-latest.js

**Comment by HardikVijayPatel** [comment]
@dpgaspar can the jquery version be bumped up now? this for security vulnerability in the current version used by Flask-appbuilder?

**Comment by dpgaspar** [comment]
@HardikVijayPatel the JQuery bump is merged on master and will be released soon (no ETA yet)

**Comment by HardikVijayPatel** [comment]
@dpgaspar  Do we have an ETA on the release now?

**Comment by zacqed** [comment]
jQuery 3.6 is already there in latest version
