### ISSUE TITLE
How can we delete a login button on the first page ? 

### ISSUE THREAD

**Issue by tetsuya0617** [dpgaspar/Flask-AppBuilder#1676]
Is there any setting in flask app builder to delete a login button on the first page like the below?

![スクリーンショット 2021-08-10 16 55 03](https://user-images.githubusercontent.com/38417952/128829961-33692036-edaf-4216-a294-2a86445023ab.png)

**Comment by qlands** [comment]
I don't know if there is a setting but if not then you could overwrite the template using an AddOn. See https://stackoverflow.com/questions/67660273/how-can-a-flask-addon-overwrite-a-template
