### ISSUE TITLE
question: fabmanager makes no traceback of python exceptions

### ISSUE THREAD

**Issue by NicolasBertrand** [dpgaspar/Flask-AppBuilder#168]
Hello,
First thanks for this app !

fabmanager seems to not make traceback of python errors ( due to code errors in my code):
I have just this ouptut : 
<pre>
2015-05-12 15:28:39,927:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Security.Permission on Views/Menus
Was unable to import app Error: 
</pre>
and no information of exception raised by pyhon : How I can display it ?

Thanks in advance
Nicolas

**Comment by dpgaspar** [comment]
I know i'm planning to improve it. If your using the base skeleton app run:

    python run.py

**Comment by NicolasBertrand** [comment]
Thansks for the answer !

**Comment by dpgaspar** [comment]
No problem, i've already fixed and will be included on the next version. Hope you enjoy coding with F.A.B.
