### ISSUE TITLE
[Feature] Upgrade Templates to use  Bootstrap 5 instead of Bootstrap 3.x

### ISSUE THREAD

**Issue by shanmukhsista** [dpgaspar/Flask-AppBuilder#1681]
[Feature] 

# Update Flask Templates to use Bootstrap 5 Theme. 

### Environment

Flask-Appbuilder version: Latest Version

## Description

Currently Flask App Builder renders a UI that uses bootstrap 3.3.x and jQuery. The proposal is to update the Templates to use a Bootstrap 5 Theme system, and render all UI using this. 

I'm planning to take up this change and convert the templates to upgrade them.

**Comment by lnnwvr** [comment]
We also are willing to do this. If you want to share some tasks. We should talk.

I Started a branch some months ago but didn't had the time. I made it configurable because of upstream projects depending on the current template.

**Comment by AttaM1rza** [comment]
Hello! 
any new updates regarding upgrading to bootrap5 ?

**Comment by lnnwvr** [comment]
Hi,
o well i forgot this issue. We stopped working with static rendering instead we wrote an addon to have a dataprider and datagrid based on fab modelrestapi in react.
