### ISSUE TITLE
UserView not showing extended model fields

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#169]
I've extended the user model in 1.3.7 as explained in documentation. The fields are created on database but UserView is not overriden with MyUserDBModelView so I don't see those new fields in list, add, edit, ... This is what I've done:

security.py
```
class MyUser(User):
	'''
            MyUser fields
	'''
	domain = Column(String(32))
	group  = Column(String(32))

	#~ def path(self):
		#~ return  self.domain+'/'+self.group+'/'+username

class MyUserDBModelView(UserDBModelView):
    """
        View that add DB specifics to User view.
        Override to implement your own custom view.
        Then override userdbmodelview property on SecurityManager
    """
    show_fieldsets = [
        (lazy_gettext('User info'),
         {'fields': ['username', 'active', 'roles', 'login_count', 'domain', 'group']}),
        (lazy_gettext('Personal Info'),
         {'fields': ['first_name', 'last_name', 'email'], 'expanded': True}),
        (lazy_gettext('Audit Info'),
         {'fields': ['last_login', 'fail_login_count', 'created_on',
                     'created_by', 'changed_on', 'changed_by'], 'expanded': False}),
    ]

    user_show_fieldsets = [
        (lazy_gettext('User info'),
         {'fields': ['username', 'active', 'roles', 'login_count', 'domain', 'group']}),
        (lazy_gettext('Personal Info'),
         {'fields': ['first_name', 'last_name', 'email'], 'expanded': True}),
    ]

    add_columns = ['first_name', 'last_name', 'username', 'active', 'email', 'roles', 'domain', 'group', 'password', 'conf_password']
    list_columns = ['first_name', 'last_name', 'username', 'email', 'active', 'roles', 'domain','group']
    edit_columns = ['first_name', 'last_name', 'username', 'active', 'email', 'roles', 'domain', 'group']

class MySecurityManager(SecurityManager):
	'''
		This are main Security class overrides
	'''
	user_model = MyUser
	userdbmodelview = MyUserDBModelView
```

And added this MySecurityManager to __init__.py

```
appbuilder = AppBuilder(app, db.session, base_template='my_base.html', indexview=IndexView, security_manager_class=MySecurityManager)

```

What I'm missing?

**Comment by dpgaspar** [comment]
Thats strange just pasted your code and everything seems ok...

i use sec_views.py for MyUserDBModelView, sec_models.py for MyUser, and sec.py for MySecurityManager

Just commited an example take a look at: https://github.com/dpgaspar/Flask-AppBuilder/tree/1.4.0/examples/issue_169

**Comment by jvinolas** [comment]
Thanks, I've done some tests. The problem raises when I activate my LDAP code, that I override from the current one in appbuilder to use the code we already have for other python apps.

If I use db auth it works fine, but when I activate ldap with my code it doesn't show MyUserView (but the fields are created on mysql). I tried with your LDAP module to be sure it is my code and not LDAP in general, but then I can't login because it throws and 'Invalid DN syntax' all the time (same DN used with my code works). Why I can't login with local user 'admin' that I've created through fabmanager create-admin? I thought that user will be a local one and not ldap.

This is the full MySecurityManager code where I've overriden some methods, mainly _bind_ldap to adapt to our existing LDAP python code that works.

```
import datetime
import logging
from flask import url_for, g, session
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, current_user
from flask_openid import OpenID
from flask_babelpkg import lazy_gettext as _

from flask_appbuilder.basemanager import BaseManager
from flask_appbuilder.const import AUTH_OID, AUTH_DB, AUTH_LDAP, \
					AUTH_REMOTE_USER, AUTH_OAUTH, \
					LOGMSG_ERR_SEC_AUTH_LDAP, \
					LOGMSG_WAR_SEC_NO_USER, \
					LOGMSG_WAR_SEC_NOLDAP_OBJ
from flask_appbuilder.security.sqla.manager import SecurityManager

from flask_appbuilder.security.sqla.models import User
from sqlalchemy import Column, Integer, ForeignKey, String, Sequence, Table
from sqlalchemy.orm import relationship, backref
from flask_appbuilder import Model

from flask_appbuilder.security.views import UserDBModelView
from flask_babelpkg import lazy_gettext

#~ from flask_appbuilder.security.sqla.manager import SecurityManager
from .ietb_security_models import MyUser
from .ietb_security_views import MyUserDBModelView

log = logging.getLogger(__name__)


class MySecurityManager(SecurityManager):
	'''
		This are main Security class overrides
	'''
	user_model = MyUser
	userdbmodelview = MyUserDBModelView
	
	'''
		Override SecurityManager LDAP to adapt to IETB
	'''
	def auth_user_db(self, username, password):
		"""
			Method for authenticating user, auth db style

			:param username:
				The username
			:param password:
				The password, will be tested against hashed password on db
		"""
		if username is None or username == "":
			return None
		user = self.find_user(username=username)
		if user is None or (not user.is_active()):
			return None
		elif check_password_hash(user.password, password):
			self.update_user_auth_stat(user, True)
			return user
		else:
			self.update_user_auth_stat(user, False)
			return None

	def _search_ldap(self, ldap, con, username):
		"""
			Searches LDAP for user, assumes ldap_search is set.

			:param ldap: The ldap module reference
			:param con: The ldap connection
			:param username: username to match with auth_ldap_uid_field
			:return: ldap object array
		"""
		filter_str = "%s=%s" % (self.auth_ldap_uid_field, username)
		user = con.search_s(self.auth_ldap_search,
							ldap.SCOPE_SUBTREE,
							filter_str,
							[self.auth_ldap_firstname_field,
							 self.auth_ldap_lastname_field,
							 self.auth_ldap_email_field
							])
		if user:
			if not user[0][0]:
				return None
		return user

	def _bind_ldap(self, ldap, con, username, password):
				try:
						con_id = con.search(self.auth_ldap_search,ldap.SCOPE_SUBTREE,"uid=%s" % username)
						usr_type,ldap_info=con.result(con_id, 0)
						user_dn = ldap_info[0][0]
						valid=con.simple_bind_s(who=user_dn,cred=password)
						if valid:
							return True,ldap_info
						else:
							return False,None
				except ldap.INVALID_CREDENTIALS:
						print "INVALID CREDENTIALS"
						return False,None

	def auth_user_ldap(self, username, password):
		"""
			Method for authenticating user, auth LDAP style.
			depends on ldap module that is not mandatory requirement
			for F.A.B.

			:param username:
				The username
			:param password:
				The password
		"""
		if username is None or username == "":
			return None
		user = self.find_user(username=username)
		# If user is Admin... logon agains db
		if user is not None and user.username=='admin':
			if self.auth_user_db(username,password):
				return user
			else:
				return None
				
		if user is not None and (not user.is_active()):
			return None
		else:
			try:
				import ldap
			except:
				raise Exception("No ldap library for python.")
				return None
			try:
				if self.auth_ldap_allow_self_signed:
					ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW)
				con = ldap.initialize(self.auth_ldap_server)
				con.set_option(ldap.OPT_REFERRALS, 0)
				# Authenticate user
				bind,ldap_info=self._bind_ldap(ldap, con, username, password)
				if not bind:
					if user: self.update_user_auth_stat(user, False)
					return None
				# If user does not exist on the DB and not self user registration, go away
				if not user and not self.auth_user_registration:
					return None
				# User does not exist, create one if self registration.
				elif not user and self.auth_user_registration:
						#~ self.getUserLdapData(ldap_info)
						print "User data:",self._search_ldap(ldap,con,username)
						user = self.add_user(
								username=username,
								first_name=username,
								last_name=username,
								email="test_mail",
								role=self.find_role(self.auth_user_registration_role)
							)
				#Si ja esta a la base de dades
				self.update_user_auth_stat(user)
				return user

			except ldap.LDAPError as e:
				if type(e.message) == dict and 'desc' in e.message:
					log.error(LOGMSG_ERR_SEC_AUTH_LDAP.format(e.message['desc']))
					return None
				else:
					log.error(e)
					return None

	#~ def getUserLdapData(self,ldap_info):
		#~ username=ldap_info[0][1]["uid"][0]
		#~ mail=ldap_info[0][1]["mail"][0]
		#~ firstname=ldap_info[0][1]["sn"][0]
		#~ path=ldap_info[0][1]["homeDirectory"][0].split("/home/users/")[1].split("/"+username)[0]
		#~ domain=path.split('/')[0]
		#~ group=path.split('/')[1]
		#~ return username,mail,firstname,domain,group
```

**Comment by dpgaspar** [comment]
If your using LDAP you should subclass UserLDAPModelView and 

``` python
class MySecurityManager(SecurityManager):
    '''
        This are main Security class overrides
    '''
    user_model = MyUser
    userldapmodelview = MyUserLDAPModelView

```

**Comment by dpgaspar** [comment]
Made corrections to docs, since this is not clear.

**Comment by jvinolas** [comment]
Thanks a lot. Now it is working. I copied MyUserDBModelView to MyUserLDAPModelView  and then I could view my own user fields.

**Comment by baxnul** [comment]
hello, please help me set up the authorization of ldap users with two different auth_ldap_server, you need to automatically check which domain the user is in, and if the user is detected in one of the domains, then let them into the system, in the code that I sent, authorization with one ldap is successful
`import os
from flask_appbuilder.security.forms import LoginForm_db
from flask_appbuilder.security.manager import AUTH_LDAP
from app.security import MySecurityManager

basedir = os.path.abspath(os.path.dirname(__file__))

# Your App secret key
SECRET_KEY = "\2\1thisismyscretkey\1\2\e\y\y\h"

# The SQLAlchemy connection string.
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:MyPassword@localhost:5433/users_db'

# Flask-WTF flag for CSRF
CSRF_ENABLED = True

# ------------------------------
# GLOBALS FOR APP Builder
# ------------------------------
# Uncomment to setup Your App name
APP_NAME = "Kad 2.0"
# ----------------------------------------------------
# AUTHENTICATION CONFIG
# ----------------------------------------------------
# The authentication type
AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = False
AUTH_LDAP_UID_FIELD = "userPrincipalName"
AUTH_LDAP_SERVER = "ldap://qw.tat.com"
AUTH_LDAP_SEARCH = "DC=qw,DC=tat,DC=com"
AUTH_LDAP_BIND_USER = "test@qw.tat.com"
AUTH_LDAP_BIND_PASSWORD = "MyPassword"

AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True 
AUTH_LDAP_UID_FIELD = "userPrincipalName"
AUTH_LDAP_SERVER = "ldap://hq.tat.com"
AUTH_LDAP_SEARCH = "DC=hq,DC=tat,DC=com"
AUTH_LDAP_BIND_USER = "test@hq.tat.com"
AUTH_LDAP_BIND_PASSWORD = "MyPassword"

# ---------------------------------------------------
# Setup default language
BABEL_DEFAULT_LOCALE = "en"
# Your application default translation path
BABEL_DEFAULT_FOLDER = "translations"
# The allowed translation for you app
LANGUAGES = {
    "en": {"flag": "gb", "name": "English"},
    "pt": {"flag": "pt", "name": "Portuguese"},
    "pt_BR": {"flag": "br", "name": "Pt Brazil"},
    "es": {"flag": "es", "name": "Spanish"},
    "de": {"flag": "de", "name": "German"},
    "zh": {"flag": "cn", "name": "Chinese"},
    "ru": {"flag": "ru", "name": "Russian"},
    "pl": {"flag": "pl", "name": "Polish"},
}
# ---------------------------------------------------
# Image and file configuration
# ---------------------------------------------------
# The file upload folder, when using models with files
UPLOAD_FOLDER = basedir + "/app/static/uploads/"

# The image upload folder, when using models with images
IMG_UPLOAD_FOLDER = basedir + "/app/static/uploads/"

# The image upload url, when using models with images
IMG_UPLOAD_URL = "/static/uploads/"
`

**Comment by baxnul** [comment]
``If it's useful to someone, then here's how I solved this problem
Create: security.py
``from flask_appbuilder import expose
from flask_appbuilder.security.forms import LoginForm_db
from flask_appbuilder.security.sqla.manager import SecurityManager
from flask import current_app, flash, g, redirect, request
from flask_appbuilder._compat import as_unicode
from flask_appbuilder.utils.base import get_safe_redirect
from flask_login import login_user
from flask_appbuilder.security.views import AuthView
from flask_appbuilder.security.manager import BaseSecurityManager


class MyAuthLDAPView(AuthView):
    login_template = "appbuilder/general/security/login_ldap.html"

    def user_domain(self, dom, lds, ldse):
        if dom == 'domain_name.RU':
            # print('Ru')
            AUTH_LDAP_SERVER = lds  
            AUTH_LDAP_SEARCH = ldse  
            AUTH_LDAP_BIND_USER = "User1@corp.domain_name.RU"
            AUTH_LDAP_BIND_PASSWORD = "UserPassword1"
            return AUTH_LDAP_SERVER, AUTH_LDAP_SEARCH, AUTH_LDAP_BIND_USER, AUTH_LDAP_BIND_PASSWORD
        elif dom == 'domain_name.COM':
            # print('Com')
            AUTH_LDAP_SERVER = lds  
            AUTH_LDAP_SEARCH = ldse
            AUTH_LDAP_BIND_USER = "User2@corp.domain_name.COM"
            AUTH_LDAP_BIND_PASSWORD = "UserPasword2"
            return AUTH_LDAP_SERVER, AUTH_LDAP_SEARCH, AUTH_LDAP_BIND_USER, AUTH_LDAP_BIND_PASSWORD

    @expose("/login/", methods=["GET", "POST"])
    def login(self):
        if g.user is not None and g.user.is_authenticated:
            return redirect(self.appbuilder.get_url_for_index)
        form = LoginForm_db()
        if form.validate_on_submit():
            try:
                username = form.username.data
                username = username.lower()
                domain = username.split("@")[1]
                l = len(domain.split('.'))
                ldss = ''
                ldsse = ''
                if l > 2:
                    ldss = 'ldap://' + domain.split('.')[0] + '.domain_name.' + domain.split('.')[2]
                    ldsse = 'DC=' + domain.split('.')[0] + ',DC=domain_name,DC=' + domain.split('.')[2]
                    domain = domain.split('.')[1:]

                else:
                    ldss = 'ldap://' + domain.split('.')[0] + '.' + domain.split('.')[1]
                    ldsse = 'DC=' + domain.split('.')[0] + ',DC=' + domain.split('.')[1]
                    domain = domain.split('.')

                dom = '.'.join(domain)

                con = self.user_domain(dom, ldss, ldsse)

                SERVER, SEARCH, USER, PASSWORD = con  # Присвоил каждой переменной свое значение из словаря
                print(SERVER + '\n' + SEARCH + '\n' + USER + '\n' + PASSWORD)
                current_app.config.update(AUTH_LDAP_SERVER=SERVER, AUTH_LDAP_SEARCH=SEARCH, AUTH_LDAP_BIND_USER=USER,
                                          AUTH_LDAP_BIND_PASSWORD=PASSWORD)
            except:
                flash(as_unicode(AuthView.invalid_login_message), "warning")
                return redirect(self.appbuilder.get_url_for_login)
            user = self.appbuilder.sm.auth_user_ldap(
                form.username.data, form.password.data)
            if not user:
                flash(as_unicode(AuthView.invalid_login_message), "warning")
                return redirect(self.appbuilder.get_url_for_login)
            login_user(user, remember=False)
            next_url = request.args.get("next", "")
            return redirect(get_safe_redirect(next_url))
        return self.render_template(
            self.login_template, title=self.title, form=form, appbuilder=self.appbuilder
        )


class MySecurityManager(SecurityManager):
    BaseSecurityManager.authldapview = MyAuthLDAPView``


You also need to declare __ in your file __init__.py :

``appbuilder = AppBuilder(app, db.session, security_manager_class=MySecurityManager)``
