### ISSUE TITLE
Possible PyJWT dependency upgrade?

### ISSUE THREAD

**Issue by mark-carrington** [dpgaspar/Flask-AppBuilder#1691]
### Environment

Flask-Appbuilder version: >=3.1.1,<4.0

### Describe the expected results

[Feature Request]

Hi,

I have a project which currently depends on apache-airflow 2.0.2, which in turn depends on flask-appbuilder>=3.3.2, <4.0.0. This project is using Poetry for dependency management. I would like to add Sentry as a dependency, so I can use this for application performance monitoring. I don't seem to be able to install recent versions of Sentry alongside recent versions of apache-airflow (including 21.3) since apache-airflow requires pyjwt (<2), whereas recent Sentry versions want PyJWT (2.1.0).

Given the popularity of Sentry, I wondered if you'd consider upgrading to using a more recent version of PyJWT? This would allow apache-airflow to update their dependencies too, and would be huge win for those who want to use these 2 packages together.

I raised a [request with apache-airflow earlier today](https://github.com/apache/airflow/issues/18091), and @potiuk suggested I contact you. I would appreciate if you are able to help with this.

Thanks
Mark

### Describe the actual results

[see above]

### Steps to reproduce

% poetry add sentry

**Comment by potiuk** [comment]
Just to add - it comes comes from  Flask-jwt-extended < 4: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/setup.py#L60 and Flask-JWT-extended 3.25 (latest from 3 line) has PyJWT < 2.

**Comment by pritampbonde** [comment]
@potiuk : We are currently using apache-airflow(2.1.0) have transitive dependency apache-airflow/2.1.0 » Flask-AppBuilder/3.3.2» PyJWT/1.7.1(i.e. Basically < 2.0 Version)Could you please let us know if there are any near future upgradation considered for pyJWT component. If yes, please confirm us in which version of Flask-AppBuilder release, PyJWT version would be upgraded.

**Comment by pritampbonde** [comment]
@potiuk/ Development Team : Could you please guide us, if in any up coming release of Flask-AppBuilder we plan to upgrade PyJWT

**Comment by dpgaspar** [comment]
@mark-carrington @pritampbonde this is identified, flask-JWT-extended is a breaking change so it will probably imply a major bump on FAB also. Will keep you updated

**Comment by pritampbonde** [comment]
@dpgaspar : thanks for response. awaiting on your updates

**Comment by pritampbonde** [comment]
> @mark-carrington @pritampbonde this is identified, flask-JWT-extended is a breaking change so it will probably imply a major bump on FAB also. Will keep you updated
@dpgaspar : thanks for response. awaiting on your updates

**Comment by pritampbonde** [comment]
Hello @dpgaspar @mark-carrington do let us know if bump dependency is resolved for upgrading flask-JWT

**Comment by dpgaspar** [comment]
not just that, flask-jwt-extended 4 is a breaking change. I'll evaluate after the next release

**Comment by schwannden** [comment]
Would be so nice if we can bump PyJWT, I am also experiencing various dependency conflict with PyJWT in my Airflow dags, having to use virtual environment for all of my task is causing huge performance overhead.

**Comment by bala-anjane** [comment]
We are facing a similar issue with our database connector library upgraded to PyJWT 2.3.0.

**Comment by dpgaspar** [comment]
@mark-carrington pyJWT and other's (Flask) have been upgraded on FAB 4.0.0. Released just now

**Comment by potiuk** [comment]
Cool!

**Comment by pritampbonde** [comment]
@dpgaspar @potiuk :thanks a lot
