### ISSUE TITLE
Need help on revising translations

### ISSUE THREAD

**Issue by dpgaspar** [dpgaspar/Flask-AppBuilder#17]
It would be awesome, if someone could help me on revising the existing translations. I made them with google translate, so they probably are a bit foolish.

Translations are here: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/translations

The framework currently supports (besides English):

- German
- Spanish
- Portuguese
- Portuguese Brazil
- Russian
- Simplified Chinese

Any help on how to proceed, just ask. If your a native speaker of any of the above this should be pretty easy (i hope).

**Comment by anogues** [comment]
Hellom

I can work on Spanish and Catalan ones if you want. If you're interested tell me and i start revising / creating them.

**Comment by dpgaspar** [comment]
Hellom,

:)

Thanks, spanish was already revised by @tuxskar, you can take a look to see if you would change something. Catalan is a possibility but the flag would be Spanish also, are you up to it?

**Comment by scheung38** [comment]
I can help with Chinese if you need Daniel.

**Comment by dpgaspar** [comment]
Thank you, but chinese as been reviewed by #jiangrzh already. Do you think something is not correct?

**Comment by dpgaspar** [comment]
Currently all translations were revised, thank you so much for your contributions!
