### ISSUE TITLE
Documentation on deployment to cloud

### ISSUE THREAD

**Issue by juaneschutte** [dpgaspar/Flask-AppBuilder#170]
Great api and documentation Daniel. I was wondering if you could spare some time quickly showing how to deploy the app (even one of the simple examples with sqlite and testdata) to Openshift or Pythonanywhere for example.

I wangled the files in the appropriate format for Openshift and have managed to get the app on Openshift with the welcome page but cannot login.  This is because the create-db, run testdata.py and create-admin needs to be initialised, i presume.  What script can i use in "/.openshift/action_hooks" to get the venv setup and the rest?

I tried looking at the FLOG repo example but there is no deployment documentation anywhere on it.

Any help and advice would be greatly appreciated,
Thanks

**Comment by dpgaspar** [comment]
Hello,

I do not use OpenShift and this is a bit out of scope. But after creating the application on openshift (and downloaded your source code) you should create the database and then create your first admin user.

You can execute the following:

``` bash
fabmanager create-db
 fabmanager create-admin --username admin --firstname admin --lastname user --email admin@fab.org --password password

```

If you get this working, your very welcome to submit a pull request to update the docs.

Thank you.

**Comment by juaneschutte** [comment]
Hi, 

Thanks for responding quickly. I already have worked through all the examples locally and works fine. I wanted to then deploy one of them either to openshift or pythoneverywhere but to no avail. 

How would u suggest going about getting your appbuilder site repo deployed to pythoneverywhere?

**Comment by dpgaspar** [comment]
Sorry for the delay, I'll produce some docs for pythonanywhere ASAP.

**Comment by juaneschutte** [comment]
Thanks, i managed to deploy to Openshift by using SSH to initialise db and admin user, which ended up working.  Will commit to a git repo and let you know.

**Comment by Code-Slave** [comment]
would love help getting it running on pythonanywhere. having issues getting mysql setup

**Comment by dpgaspar** [comment]
Closing, feel free to reopen if it's still relevant

**Comment by danalvin** [comment]
> Sorry for the delay, I'll produce some docs for pythonanywhere ASAP.

Please?

**Comment by geraldo** [comment]
As by 2024 it's really simple to set up _flask-appbuilder_ on pythonanywhere:
1. Set up a `virtualenv` as explained on the [official pythonanywhere docs](https://help.pythonanywhere.com/pages/Flask/#setting-up-your-virtualenv)
2. Install _flask_ and _flask-appbuilder_ as explained on the [official flask-appbuilder docs](https://flask-appbuilder.readthedocs.io/en/latest/installation.html)
3. Rename the `app` folder to `flask_app`
4. Set up a web app as explained on the [official pythonanywhere docs](https://help.pythonanywhere.com/pages/Flask/#setting-up-the-web-app-using-manual-configuration). This includes defining the route to your _virtualenv_.
5. Edit your _WSGI file_ on the _webapps tab_ and  as explained on the [official pythonanywhere docs](https://help.pythonanywhere.com/pages/Flask/#configuring-the-wsgi-file). Actually you only have to update the _path_ (or _project_home_ as it's called be default) in your _WSGI file_.
