### ISSUE TITLE
Type error in the official rest_api example code 

### ISSUE THREAD

**Issue by journeast** [dpgaspar/Flask-AppBuilder#1700]
I am a new FAB user here, and found a minor but frustrating error in the official documentation. 

- https://flask-appbuilder.readthedocs.io/en/latest/rest_api.html
- Flask-AppBuilder/docs/rest_api.rst

I was trying to follow through the above rest_api example, and copy the exact code below to my editor but it did not work. It turned out that it is just a simple type error. It should use [route_base] instead of [base_route], please correct this asap so as not to turn off new users.

`from flask_appbuilder.api import BaseApi, expose
from . import appbuilder

class ExampleApi(BaseApi):

    base_route = '/newapi/v2/nice'

    @expose('/greeting')
    def greeting(self):
        return self.response(200, message="Hello")

appbuilder.add_api(ExampleApi)`

**Comment by fedepad** [comment]
@journeast I submitted a PR to fix that. Thanks for spotting it!
