### ISSUE TITLE
LDAP problems

### ISSUE THREAD

**Issue by perrfect** [dpgaspar/Flask-AppBuilder#1709]
Flask-Appbuilder version: 3.3.3

- aiohttp==3.7.4.post0
- alembic==1.6.5
- amqp==2.6.1
- apache-superset==0.0.0.dev0
- apispec==3.3.2
- async-timeout==3.0.1
- attrs==21.2.0
- Babel==2.9.1
- backoff==1.11.1
- billiard==3.6.4.0
- bleach==3.3.1
- boto3==1.18.19
- botocore==1.21.19
- Brotli==1.0.9
- cached-property==1.5.2
- cachelib==0.1.1
- celery==4.4.7
- certifi==2021.5.30
- cffi==1.14.6
- chardet==4.0.0
- charset-normalizer==2.0.4
- click==7.1.2
- colorama==0.4.4
- convertdate==2.3.2
- cron-descriptor==1.2.24
- croniter==1.0.15
- cryptography==3.4.7
- defusedxml==0.7.1
- deprecation==2.1.0
- dnspython==2.1.0
- email-validator==1.1.3
- et-xmlfile==1.1.0
- Flask==1.1.4
- Flask-AppBuilder==3.3.3
- Flask-Babel==1.0.0
- Flask-Caching==1.10.1
- Flask-Compress==1.10.1
- Flask-Cors==3.0.10
- Flask-JWT-Extended==3.25.1
- Flask-Login==0.4.1
- Flask-Migrate==3.1.0
- Flask-OpenID==1.3.0
- Flask-SQLAlchemy==2.5.1
- flask-talisman==0.8.1
- Flask-WTF==0.14.3
- future==0.18.2
- geographiclib==1.52
- geopy==2.2.0
- gevent==21.8.0
- graphlib-backport==1.0.3
- greenlet==1.1.1
- gunicorn==20.0.4
- holidays==0.10.3
- humanize==3.11.0
- idna==3.2
- ijson==3.1.4
- isodate==0.6.0
- itsdangerous==1.1.0
- Jinja2==2.11.3
- jmespath==0.10.0
- jsonlines==2.0.0
- jsonschema==3.2.0
- kombu==4.6.11
- korean-lunar-calendar==0.2.1
- linear-tsv==1.1.0
- Mako==1.1.4
- Markdown==3.3.4
- MarkupSafe==2.0.1
- marshmallow==3.13.0
- marshmallow-enum==1.5.1
- marshmallow-sqlalchemy==0.23.1
- msgpack==1.0.2
- multidict==5.1.0
- mysqlclient==1.4.2.post1
- numpy==1.21.1
- openpyxl==3.0.7
- packaging==21.0
- pandas==1.2.5
- parsedatetime==2.6
- pgsanity==0.2.9
- Pillow==7.2.0
- polyline==1.4.0
- prison==0.2.1
- progress==1.6
- psycopg2-binary==2.8.5
- pure-sasl==0.6.2
- pyarrow==4.0.1
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pycparser==2.20
- pydruid==0.6.2
- PyHive==0.6.4
- pyinstrument==4.0.2
- PyJWT==1.7.1
- PyMeeus==0.5.11
- pyparsing==2.4.7
- pyrsistent==0.16.1
- python-dateutil==2.8.2
- python-dotenv==0.19.0
- python-editor==1.0.4
- python-geohash==0.8.5
- python-ldap==3.3.1
- python3-openid==3.2.0
- pytz==2021.1
- PyYAML==5.4.1
- redis==3.5.3
- requests==2.26.0
- rfc3986==1.5.0
- s3transfer==0.5.0
- sasl==0.3.1
- selenium==3.141.0
- simplejson==3.17.3
- six==1.16.0
- slackclient==2.5.0
- SQLAlchemy==1.3.24
- SQLAlchemy-Utils==0.36.8
- sqlparse==0.3.0
- tableschema==1.20.2
- tabulate==0.8.9
- tabulator==1.53.5
- thrift==0.13.0
- thrift-sasl==0.4.3
- typing-extensions==3.10.0.0
- unicodecsv==0.14.1
- urllib3==1.26.6
- vine==1.3.0
- webencodings==0.5.1
- Werkzeug==1.0.1
- WTForms==2.3.3
- WTForms-JSON==0.3.3
- xlrd==2.0.1
- yarl==1.6.3
- zipp==3.4.1
- zope.event==4.5.0
- zope.interface==5.4.0

Hello I need help wtih LDAP:.
I'm getting the error:
`ERROR:flask_appbuilder.security.manager:{'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'}`

**My LDAP configuration:**
```
AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True
AUTH_ROLE_ADMIN = 'Admin'
AUTH_ROLES_MAPPING = { "memberOf=cn=admins,cn=groups,cn=accounts,dc=example,dc=net": ["Admin"] }
AUTH_LDAP_SERVER =  "ldaps://example.net:636"
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_GROUP_FIELD = "memberOf"
AUTH_LDAP_BIND_USER = "uid=forldap,cn=users,cn=accounts,dc=example,dc=net"
AUTH_LDAP_BIND_PASSWORD = "password"
AUTH_LDAP_SEARCH = "cn=users,cn=accounts,dc=example,dc=net"
AUTH_LDAP_SEARCH = "(&(MemberOf=cn=admins,cn=groups,cn=accounts,dc=example,dc=net)(uid=%u)(!(MemberOf=cn=restricted,cn=groups,cn=accounts,dc=example,dc=net)))"
AUTH_LDAP_UID_FIELD = "uid"
```

**Comment by perrfect** [comment]
Sorry, the problem solved.
A line AUTH_LDAP_SEARCH was wrong. Should be - `AUTH_LDAP_SEARCH = "dc=example,dc=net"`

**Comment by dpgaspar** [comment]
nice then, going to close the issue

**Comment by caxefaizan** [comment]
@perrfect I am facing a similar issue https://github.com/dpgaspar/Flask-AppBuilder/issues/1825
but i tried your solution by keeping only the dc in search base but it still doesn't work. could you look into my issue. thanks
