### ISSUE TITLE
Relax SQLAlchemy version dependency

### ISSUE THREAD

**Issue by vsolovyov** [dpgaspar/Flask-AppBuilder#1710]
Right now in `setup.py` we have SQLAlchemy pinned to <1.4.0:

        # SQLAlchemy 1.4.0 breaks flask-sqlalchemy and sqlalchemy-utils
        "SQLAlchemy<1.4.0",

flask-sqlalchemy added support for 1.4 in release [2.5.0](https://github.com/pallets/flask-sqlalchemy/blob/main/CHANGES.rst#version-250) (released in March).
sqlalchemy-utils added support for 1.4 in release [0.37.0](https://github.com/kvesteri/sqlalchemy-utils/blob/master/CHANGES.rst#0370-2021-04-12) (released in April).

I think we should update SQLAlchemy dependency.

**Comment by kyoshi-warrior** [comment]
Any update on easing this dependency?
`        # SQLAlchemy 1.4.0 breaks flask-sqlalchemy and sqlalchemy-utils
        "SQLAlchemy<1.4.0",
`
