### ISSUE TITLE
LDAP w/REMOTE_USER

### ISSUE THREAD

**Issue by keith6014** [dpgaspar/Flask-AppBuilder#1711]
Using Flask-AppBuilder with Airflow. I am able to determine  REMOTE_USER with with proxy, nginx. Seperatly, when I enable AUTH_LDAP I can get it to work but that would require me to login. 

When I have AUTH_TYPE = AUTH_REMOTE_USER I keep getting "Redirecting... error. ERR_TOO_MANY_REDIRECTS"

Is there a way to have auth with AUTH_REMOTE_USER and AUTH_LDAP?

**Comment by dpgaspar** [comment]
sorry, currently not possible
