### ISSUE TITLE
Can I modify add form field to have select list from data got by external API?

### ISSUE THREAD

**Issue by Shhad** [dpgaspar/Flask-AppBuilder#1717]
I want to extend one field from add form, to be able to choose option from select list got by external API. Let me explain the question.
I've got model like:
```
class ContactGroup(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    my_field_id = Column(Integer, nullable=False)

    def __repr__(self):
        return self.name
```
When I want to add new entity, by default form created by app-builder, I have to specify my_field_id "by hand". So my question is, can I extend my_field_id to instead of specifying integer I will have a select list with data returned by external API.
Api is providing data as a json, ex.:
```
{
  data: [
    {
      id: 1,
      name: "My field"
    }
    ...
  ]
}
```
Thanks!

**Comment by Shhad** [comment]
Yes, that's exactly what I needed. Thank you very much @fedepad !
I have yet one question.
When I  create my own form, how to specify relationship and foreign keys fields?
For example, these two fields taken from AppBuilder docs in Model Views chapter.
```
contact_group_id = Column(Integer, ForeignKey('contact_group.id'))
contact_group = relationship("ContactGroup")
```

**Comment by fedepad** [comment]
Hi, does this help? https://stackoverflow.com/questions/36180084/flask-wtforms-and-sqlaalchemy-selectfield-with-relation
Also, check what fields you listed as `add_columns`.

**Comment by Shhad** [comment]
Yes, sorry for so late reply. I paused that project for some time. Thank you very much for your help!
