### ISSUE TITLE
Sending personalized extra_args based on user query

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#173]
I don't know if this is possible, but I can't get it working. I've done this in the view:
```
extra_args = {'qd':quota(get_user())}
```
and also tried this on query:
```
def quota(user_id=None):
    try:
            user_id=g.user.id
    except:
            return 0
    return appbuilder.session.query(func.max(Quota.size)).select_from(Quota).join(AssocQuotaRoles).join(Role).join(AssocUserRoles).filter(AssocUserRoles.user_id==user_id).scalar()

```
And tried in different ways, but I get always the **raise RuntimeError('working outside of application context')** error on starting app because it does evaluate user and there is no context.

**Comment by dpgaspar** [comment]
Flask/Python is invoking quota(get_user()) at the class instantiation time, so there is no context.

You can only invoke quota(get_user()) with context, so you can do it on the template, define extra_args with the function reference don't invoke it.

``` python
extra_args = {'qd': _quota}

def _quota():
    return quota(get_user())
```

Then on Jinja2 invoke qd.

I have not tested it, but i think it should work.

**Comment by jvinolas** [comment]
Thanks! It was that.
