### ISSUE TITLE
update docs website for Flask-AppBuilder `3.4.0`

### ISSUE THREAD

**Issue by thesuperzapper** [dpgaspar/Flask-AppBuilder#1741]
Flask-AppBuilder 3.4.0 was [released 2 days ago](https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v3.4.0), but the https://flask-appbuilder.readthedocs.io/en/latest/index.html website still only has `3.3.0` visible under the `latest` tag.

**Comment by thesuperzapper** [comment]
@dpgaspar was there a reason for this, or was it just missed?

**Comment by dpgaspar** [comment]
just missed, updated, thank you @thesuperzapper
