### ISSUE TITLE
[Feature] Added AUTH_ROLES_MAPPING  support using Azure OAuth

### ISSUE THREAD

**Issue by Amphagory** [dpgaspar/Flask-AppBuilder#1742]
AUTH_ROLES_MAPPING is not currently not support using the Azure provider.

Mimicking what has been done for Okta, it seems we would need to add a single line of code ("role_keys": data.get("groups", []),) in the return dictionary for the provider Azure located here: https://github.com/dpgaspar/Flask-AppBuilder/blob/1efbbcca7088422a3e90ba518c2ea644dee7c322/flask_appbuilder/security/manager.py#L612

**Comment by Amphagory** [comment]
I've added the code to enable AUTH_ROLES_MAPPING  for Azure provider and it has been merged earlier this year.

**Comment by ziedb** [comment]
Hello 
From AirFlow '3.5.0) The AUTH_ROLES_MAPPING seems not working.. I use  my own Oauth/SSO service.
In the other hand I can map authenticated user to Admin Role  by AUTH_USER_REGISTRATION_ROLE = "Admin"
Any help
