### ISSUE TITLE
base_filters doesn't work for filtering relationship

### ISSUE THREAD

**Issue by forestlzj** [dpgaspar/Flask-AppBuilder#1745]
### Environment

Flask-Appbuilder version: 3.3.3

pip freeze output:

### Describe the expected results

Tell us what should happen.
In example： extendsecurity/extendsecurity2,  if base_filters set to filter on relationship,  it doesn't take effect to filter by the user's company.  Instead it shows all the records 

E.g. In extendsecurity2 example
```python

def get_user_companies():
    return set([company.id for company in g.user.companies])

class ContactModelView(ModelView):
...
     base_filters = [["created_by.companies", FilterInFunction, get_user_companies]]
```

### Steps to reproduce
Run example: extendsecurity/extendsecurity2

**Comment by ThomasP0815** [comment]
Why do you change the example.
Use FilterInManyFunction instead of FilterInFunction.

**Comment by forestlzj** [comment]
i had also tried the original code:

```
class FilterInManyFunction(BaseFilter):
    name = "Filter view where field is in a list returned by a function"

    def apply(self, query, func):
        query, field = get_field_setup_query(query, self.model, self.column_name)
        return query.filter(field.any(Company.id.in_(func())))


def get_user_companies():
    return set([company.id for company in g.user.companies])
    return g.user.companies


class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)
    list_columns = [
        "name",
        "personal_celphone",
        "birthday",
        "contact_group.name",
        "created_by",
        "created_by.companies"
    ]
    add_columns = [
        "name",
        "address",
        "birthday",
        "personal_phone",
        "personal_celphone",
        "contact_group",
        "gender",
    ]
    edit_columns = [
        "name",
        "address",
        "birthday",
        "personal_phone",
        "personal_celphone",
        "contact_group",
        "gender",
    ]
    base_order = ("name", "asc")
    base_filters = [["created_by.companies", FilterInManyFunction, get_user_companies]]
```
when login with user2_company2,  in view "List Contacts", it shows all the 99 records instead of only records for company2

**Comment by ThomasP0815** [comment]
But it works for me.
![grafik](https://user-images.githubusercontent.com/30863072/143674560-62e038ee-c7c1-4c1f-9b1a-c3af35e08933.png)
![grafik](https://user-images.githubusercontent.com/30863072/143674652-ab966f9a-f795-4dab-a919-4ab03e74cf95.png)

user2_company2 sees contact from 2 user.

**Comment by forestlzj** [comment]
# Flask-Appbuilder version: 3.3.3

# pip freeze output:
apispec==3.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.2.0
chardet==4.0.0
click==8.0.1
colorama==0.4.1
decorator==5.1.0
defusedxml==0.5.0
dnspython==1.16.0
email-validator==1.0.5
et-xmlfile==1.1.0
fab-addon-audit==0.0.1
Flask==1.1.1
Flask-AppBuilder==3.3.3
Flask-Babel==1.0.0
Flask-BabelPkg==0.9.6
Flask-Excel==0.0.7
Flask-JWT-Extended==3.18.0
Flask-Login==0.4.1
Flask-OpenID==1.3.0
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
idna==2.9
importlib-metadata==4.8.1
ipython==7.28.0
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.10.1
jsonschema==3.0.1
lml==0.1.0
MarkupSafe==1.1.1
marshmallow==3.5.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.0
matplotlib-inline==0.1.3
numpy==1.21.2
openpyxl==3.0.9
pandas==1.3.3
parso==0.8.2
pickleshare==0.7.5
Pillow==8.3.2
prison==0.2.1
prompt-toolkit==3.0.20
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyexcel==0.6.7
pyexcel-io==0.6.4
pyexcel-webio==0.1.4
Pygments==2.10.0
PyJWT==1.7.1
pyrsistent==0.14.11
python-dateutil==2.8.0
python-ldap @ file:///D:/downloads/python_ldap-3.3.1-cp37-cp37m-win_amd64.whl
python3-openid==3.1.0
pytz==2018.9
PyYAML==5.1
six==1.12.0
speaklater==1.3
SQLAlchemy==1.3.1
SQLAlchemy-Utils==0.33.9
texttable==1.6.4
traitlets==5.1.0
typing-extensions==3.10.0.2
wcwidth==0.2.5
Werkzeug==0.15.5
WTForms==2.2.1
zipp==3.6.0

It does't work for me :(
![image](https://user-images.githubusercontent.com/3266040/143726695-93ba24b1-39cf-4447-937e-c7b3f8d32820.png)

![image](https://user-images.githubusercontent.com/3266040/143726705-5db52a5d-af5b-4130-908c-a214519d64fc.png)

**Comment by ThomasP0815** [comment]
Yes you are right!
Sorry I used an virtual environment linking to an old development version (<3.0.0).
I found the breaking changes (#1398).

![grafik](https://user-images.githubusercontent.com/30863072/143762889-4b0cf306-0b06-4839-895a-1ff72cc80c41.png)

**Comment by ThomasP0815** [comment]
The function "get_inner_filters" causes the problem.
if "flt.column_name" is dotted it can't be a relation 

My solution:
```
-   elif self.is_relation_many_to_one(flt.column_name
-   ) or self.is_relation_one_to_one(flt.column_name):  
+   elif self.is_relation_many_to_one(flt.column_name.split(".")[0]
+   ) or self.is_relation_one_to_one(flt.column_name.split(".")[0]):    
     _filters.append((flt.column_name, flt.__class__, value)) 
```

**Comment by forestlzj** [comment]
thanks @ThomasP0815 . 
@dpgaspar Will the fix be included in next release?

**Comment by RastaKolobar** [comment]
Thank  you @ThomasP0815 .

**Comment by ptitlouis** [comment]
Hello the solution get_inner_filters using get_column_root_relation is working well on the example. But the List of Values (for my application) doesn't get the filter even though the list view has been filtered correctly. Is there something wrong with my code?
![image](https://user-images.githubusercontent.com/10941134/146766910-a99d1946-eaa0-487b-b025-67b9902d3a65.png)
Many thanks.

**Comment by ThomasP0815** [comment]
Base_filters will only apply on list views !
I think you are looking for ' add_query_rel_fields' or 'edit_query_rel_fields'.

**Comment by ptitlouis** [comment]
Ok thank you, I'm looking this way.
