### ISSUE TITLE
Display custom icon instead of text in CRUD

### ISSUE THREAD

**Issue by MatFluor** [dpgaspar/Flask-AppBuilder#175]
Hi there,

is it possible to display icons instead of text in a standard CRUD-View?

E.g. to display boolean values, instead of "True" or "False" in the field, it would be nice to see a check-mark or a cross. For other stuff it might be interesting too (certain values = certain icons).

**Comment by dpgaspar** [comment]
You can use declare fields as methods, something like this

``` python
class Contact(Model):
    id = Column(Integer, primary_key=True)
    name =  Column(String(150), unique = True, nullable=False)
    active =  Column(Boolean)

    def render_active(self):
        if self.active:
            return Markup("<i class="fa fa-thumbs-up"></i>")
        else:
            return Markup("<i class="fa fa-thumbs-down"></i>")
```

Then on ModelView

``` python
class MyModelView(ModelView):
    datamodel = SQLAInterface(MyModel)
    list_columns = ['name', 'render_active']
```

**Comment by MatFluor** [comment]
Perfect, thank you.
