### ISSUE TITLE
Custom Index - where to put images?

### ISSUE THREAD

**Issue by MatFluor** [dpgaspar/Flask-AppBuilder#176]
Hi there,

Might be a dumb question - but I don't know / find where to put images or similar stuff in the project structure to display on the pages - without touching the appbuilder folders.

Thanks for your time and cool project!

**Comment by dpgaspar** [comment]
Hi,

No dumb question, this is probably not clear on the docs. My advice is take a look at the demo site, i think it's pretty simple: https://github.com/dpgaspar/Flask-AppBuilder-Site

There you have:

app/templates -> for your own jinja2 templates
app/static -> for your own images, CSS, js, etc...

Hope it helps, i'll take a look at the docs to make this clearer.

**Comment by MatFluor** [comment]
Yes, thank you very much.

I'll look into the docs - maybe I see some things for clarification and "pull request" them to you.
