### ISSUE TITLE
MultipleView javascript bug with 2 (or more?) charts

### ISSUE THREAD

**Issue by absinthetized** [dpgaspar/Flask-AppBuilder#177]
if one tries to build a multiple view with two charts (GroupByChartView) two "slots" (divs) are rendered into the page but only one chart is plotted.

it seems that all charts are rendered into the <div id="chart" ></div>, therefore all charts are overlapping due to the fact that many divs now have the same "chart" id and only the first is used by javascript functions... 
also the id="chart" thing is hardwired all alround even into the javascript function responsible of the creation of the charts: function createChart().
I think the solution is to assign a progressive id to divs, like id="chart0", id="chart1" and so on and adjust the createChart() function, but I've not investigated more...

**Comment by absinthetized** [comment]
ok: first easy fix is to substitute the 'chart' id into the general/widgets/direct_chart.html file with the {{ chart_title }} variable.
this renders every div but only json data coming from the latest chart are actually plotted into all the charts

**Comment by absinthetized** [comment]
ok final bug fix is quite easy again: just use {{ chart_title|replace(' ','_') }} to define everithin in a unique manner (and keep care of possible spaces in title) so:

'chart' become id='{{ chart_title|replace(' ','_') }}'
jsonData become jsonData{{ chart_title|replace(' ','_') }}

bye!

**Comment by dpgaspar** [comment]
Hello @absinthetized new 1.4.1 is out, this version addresses this bug, please update.
