### ISSUE TITLE
Best practice to create GTE and LTE filters from existing GT, LT, and equal to filter

### ISSUE THREAD

**Issue by fredthomsen** [dpgaspar/Flask-AppBuilder#1781]
### Environment

Flask-Appbuilder version: v3.3.0

### Describe the expected results

What is best practice to create a "greater than or equal to" filter from the filters in  `flask_appbuilder/models/sqla/filters.py`?  Are there none defined in this module intentionally?  Is there a clever mixin or some composition of filters that can be done that I am missing?

### Describe the actual results

Just a question in regards to best path forward.

**Comment by fedepad** [comment]
I try to answer, but not sure entirely your starting point and probably others have better suggestions.

1. If you use the api that FAB builds out of the box using basically SQLA models, you can just copy paste the code for the 

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/filters.py#L158
so something like that:

```python
class FilterGreaterOrEqual(BaseFilter):
    name = lazy_gettext("Greater than or equal to")
    arg_name = "gte"

    def apply(self, query, value):
        query, field = get_field_setup_query(query, self.model, self.column_name)
        value = set_value_to_type(self.datamodel, self.column_name, value)

        if value is None:
            return query

        return query.filter(field >= value)
```
Most of the SQLA types where you want to use this filter (I assume numbers...) I imagine `>=` exists.

2. You have to define your own "conversion table" like this one: 
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/filters.py#L280
but in your case you will add `FilterGreaterOrEqual` to the `is_integer` list of Filters (at least, then if you want to use also for floats, numeric you have to decide):
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/filters.py#L338

3. Then you have to create the interface with the custom converter (which include your extra filter) so one option could be to subclass:
https://github.com/dpgaspar/Flask-AppBuilder/blob/e2b744c258ff62ece9d5ac7172c3b4644ff4c2fe/flask_appbuilder/models/sqla/interface.py#L48
`SQLAInterface` and override the attribute `filter_converter_class` and set it to the class representing your converter.

4. Then use this new interface in place of `SQLAInterface`.

If you instead use an external api and FAB just for the views and generic models, you filter code could look different.

If you will use that filter on a special custom type and this filter has a special meaning, then one approach could be the one here: https://github.com/dpgaspar/Flask-AppBuilder/blob/a54df11c82d53c86239befac01484d9f679fb5d2/examples/crud_rest_api/app/api.py#L62

More or less this should be one way to approach, I am sure there are other ways depending on the specific case.

**Comment by fredthomsen** [comment]
Thanks @fedepad.  These filters seem common enough to warrant inclusion in this repo.  Any reason a PR like that wouldn't be desired?
