### ISSUE TITLE
Question - Is there a way to add users via REST API or other means?

### ISSUE THREAD

**Issue by srinisubramanian** [dpgaspar/Flask-AppBuilder#1790]
This is a newbie question .. this is regarding an integration of an app to an internal FAB based application.  When a user registers in the host app we need to create a user automatically in the internal FAB based app.

I did hunt through the documentation but the standard user model api seems to be removed now?  I have not been able to get any docs on how to do this.  Is there an API that can be accessed in the FAB app that can be used to create a user in the FAB app and assign a role to it?

Thanks for the assist and apologies if this is a repeat.

**Comment by ThomasP0815** [comment]
flask-appbuilder.readthedocs.org

![image](https://user-images.githubusercontent.com/30863072/150781172-223ba421-8968-4bbb-b0d8-0b8dfc3af86d.png)

**Comment by srinisubramanian** [comment]
@ThomasP0815 Thanks for the pointer .. this is I guess Self Registration?  As mentioned I need to create the user programmatically using a REST API for e.g

**Comment by ThomasP0815** [comment]
No, the registration takes place at the first login.

**Comment by srinisubramanian** [comment]
OK, so if I understand this right there is no API to create the user and I probably need to add one and use?  (FYI: User initiated login will not work for us)

**Comment by ThomasP0815** [comment]
There is not API-Endpoint out of the box. But you can create a Swagger/OpenAPI with such an endpoint.

**Comment by srinisubramanian** [comment]
OK .. thanks

**Comment by ThomasP0815** [comment]
Why do you use Users/Roles, if the are not allowed to login?
Have a look at the examples:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/extendsecurity2/testdata.py

**Comment by srinisubramanian** [comment]
> Why do you use Users/Roles, if the are not allowed to login? Have a look at the examples:
> 
> https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/extendsecurity2/testdata.py

Its not that we do not use Users/Roles .. we want to so that all their existing functionality with the user/role in the FAB app continues to work.  However we do not want the user to be provisioned directly in the FAB app.  Instead in the new App that is being developed (outside of FAB) user management is handled and we wanted to auto-provision the same user as the new system in the FAB app programmatically.  This would enable the user to use both the new app and the new app seamlessly as we were planning to redirect with the auth information.  Hope that explains,

**Comment by ThomasP0815** [comment]
What kind of authentication backend do you use ?

**Comment by srinisubramanian** [comment]
> What kind of authentication backend do you use ?

Users are present in an SQL database

**Comment by ThomasP0815** [comment]
How do you handle a password change process ?

**Comment by srinisubramanian** [comment]
I think a little more detail is needed.  Basically the new app is like a launchpad with additional functionality.  So all users are expected to login to the Launchpad from where they can either open the existing FAB apps or connect to other apps.  All User Management is being handled in the new app (incl. auto provisioning, password reset, two factor etc etc).  I know it sounds convoluted but thats the need :(

**Comment by ThomasP0815** [comment]
Ok, it sounds weird to me, but you can do what ever you want.
Like I sayed there is no API endpoint for that, but you should be able to extend the API.

**Comment by srinisubramanian** [comment]
Weird it may be :)  Net-net what the customer wants they get .. and what they need like I said is to make a Launchpad application.  If there was an ADS/LDAP hookup somewhere we could have configured that but they prefer the database.  Will check on extending the API.  Thanks

**Comment by fatchat** [comment]
not weird at all, i want to do exactly the same thing. superset handles the visualization part of a larger application where my users reside, when i create a user in my larger application i want to create a login for them in superset. i absolutely do not want self-registration via oauth... the customer org may be large and only a small team will use my application

**Comment by lynchzival** [comment]
The issue has been closed, but in case anyone is looking for the solution, you can manually add the **UserApi** class to the appbuilder in your **views.py** like this. Not sure why it wasn’t added by default or mentioned in the docs—I had to dig through the source code to figure it out.

```
from . import appbuilder
from flask_appbuilder.security.sqla.apis.user import UserApi

appbuilder.add_api(UserApi)
```

This should enable you to do things with your user model via REST API.
