### ISSUE TITLE
Flask AppBuilder, Apache & WSGI Config

### ISSUE THREAD

**Issue by buytore** [dpgaspar/Flask-AppBuilder#180]
Can you provide any help or point me to any documentation that might setup Flask AppBuilder, Apache & WSGI?
I have some of the "Flask" sample WSGI setup working fine on Apache and have followed a few of the tips share for Nginx but nothing seems to be working. 

flaskapp.wsgi
#!/usr/bin/python
import sys
import logging
logging.basicConfig(stream=sys.stderr)

activate_this = '/data/web/test.staging.avrostrategies.ca/env/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

from FlaskApp import app as application

__init__.py 
from flask import Flask

app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)
appbuilder = AppBuilder(app, db.session)

from app import views

if __name__ == '__main__':
  app.run()

ERROR is:
ImportError: No module named FlaskApp (Line 13 in flaskapp.wsgi)
DIRECTORY STRUCTURE
webapps/FlaskApp
                         FlaskApp
                                    __initi__.py
                                    views.py
                                    models.py
                         flaskapp.wsgi

Hope this makes some sense.

**Comment by buytore** [comment]
Resolved this:

web/
wsgi.py
#!/usr/bin/python
import sys
import logging
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/data/web/mbannan.staging.avrstrategies.ca/web/")

from apps import app as application


web/apps/__init__.py
from flask import Flask
from flask.ext.appbuilder import SQLA, AppBuilder

app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)
appsbuilder = AppBuilder(app, db.session)

from apps import views


Hope this helps and thx for a great product!!

**Comment by dpgaspar** [comment]
Great, i'll try to find the time to make a chapter on the docs about Apache, Nginx, Cloud deploy.

**Comment by buytore** [comment]
Let me know if I can help on that front.

**Comment by bawantha** [comment]
> Great, i'll try to find the time to make a chapter on the docs about Apache, Nginx, Cloud deploy.

Did you make any ?

**Comment by dpgaspar** [comment]
No it eventually seemed a bit off, since I believe you can always use Flask docs about it: https://flask.palletsprojects.com/en/1.1.x/deploying/

**Comment by jdc91** [comment]
Hi @dpgaspar I am trying to deploy flask app builder on an apache server using AWS ElasticBeanStalk 
http://swyftadminappdev-env.6by4im993t.ap-south-1.elasticbeanstalk.com/
The static resources don't seem to be loading. Elastic beanstalk is deployed on mod_wsgi any tips on how I can resolve this issue?
