### ISSUE TITLE
exception raised when sorting a column based on a property

### ISSUE THREAD

**Issue by noyeitan** [dpgaspar/Flask-AppBuilder#183]
I have a table that includes an IP address (as integer) and a mask (as integer). I've added to the model a property called subnet and implemented the getter and setter that translate from string to the 2 columns. It works great (by using edit_form_extra_fields) for the table view and editing.

It breaks when I click the sort button at the top of the table, it generates a SQL 'order by' clause using the property name, which obviously does not exist in the table. I've traced the flask-appbuilder code and could not find any way to override it.

Am I using it incorrectly? If not, can you suggest a fix? I'll implement it...

**Comment by dpgaspar** [comment]
Could you please post your model definition?

**Comment by noyeitan** [comment]
class IpSubnet(Model): 
    id = Column(Integer, primary_key=True) 
    ip = Column(Integer, nullable=False) 
    mask = Column(Integer, nullable=False) 
    name = Column(String(256)) 
 
    @property 
    def subnet(self): 
        return "%s/%d" % (IPAddress.numToDottedQuad(self.ip), self.mask) 
 
    @subnet.setter 
    def subnet(self, value): 
        vals = value.split('/') 
        self.ip = IPAddress.dottedQuadToNum(vals[0]) 
        self.mask = int(vals[1]) 
 
    def __repr__(self): 
        return self.name

**Comment by dpgaspar** [comment]
Because your using properties appbuilder will consider them as normal model columns and include them to be sorted. You must manually exclude this "column" using **order_columns**

``` python
class IpSubnetModelView(ModelView):
     datamodel = SQLAInterface(IpSubnet)
     order_columns = ['ip','mask','name']
     ....

```

**Comment by JamesGalt** [comment]
Hi Daniel,
and what if you want it sorted?
thanks

**Comment by absinthetized** [comment]
IMHO, using this code is like to not get any result. FAB expect Model-derived classes to be SQL schema. Period. Just 2 quick'n'dirty ideas:

1- Maybe, you could wrap your SQL Model into a Generic Model, where you map 1-to-1 existing fields and you also add unexistent data fields. You can then overload any add/edit/X method in the generic model to re-commit into the underling SQL model.

2- just avoid the SQL Model class at all, bypass flask-sqlalchemy and create a generic model which maps directly the the underlying SQLAlchemy logic. Act as described in solution 1 but using directly the SQLAlchemy API. I do this for some stuff in my code.

bye

**Comment by peterholdsworth** [comment]
The same problem occurs when `@renders` is used to render columns in the base table. 
If you are using Postgres you can define a view based on the table with rendered columns defined in SQL (instead of using `@render`). Use rendered columns for display and update corresponding un-rendered columns and Postgres will update the view. 
You can then sort on rendered columns without getting exceptions.

**Comment by dpgaspar** [comment]
Closing, feel free to reopen if it's still relevant
