### ISSUE TITLE
add Azure OAUTH example to security docs

### ISSUE THREAD

**Issue by thesuperzapper** [dpgaspar/Flask-AppBuilder#1835]
Currently, we don't list an Azure OAUTH example for [in the security docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) for `OAUTH_PROVIDERS`.

However, we already have an example for Azure OAUTH in the [`./examples/oauth/config.py`](https://github.com/dpgaspar/Flask-AppBuilder/blob/v3.4.5/examples/oauth/config.py#L71-L87) file, so we can probably copy that example into [`./docs/security.rst`](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/security.rst#authentication-oauth) to help users understand that this is an option.

__For example: (derived from `./examples/oauth/config.py`)__

```python
OAUTH_PROVIDERS = [
...
...
...
{
    "name": "azure",
    "icon": "fa-windows",
    "token_key": "access_token",
    "remote_app": {
        "client_id": "AZURE_APPLICATION_ID",
        "client_secret": "AZURE_SECRET",
        "api_base_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2",
        "client_kwargs": {
            "scope": "User.read name preferred_username email profile upn",
            "resource": "AZURE_APPLICATION_ID",
        },
        "request_token_url": None,
        "access_token_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2/token",
        "authorize_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2/authorize",
    },
},
...
...
...
]
```

**Comment by thesuperzapper** [comment]
I have raised a PR to add these docs https://github.com/dpgaspar/Flask-AppBuilder/pull/1837

**Comment by Narender-007** [comment]
> Currently, we don't list an Azure OAUTH example for [in the security docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) for `OAUTH_PROVIDERS`.
> 
> However, we already have an example for Azure OAUTH in the [`./examples/oauth/config.py`](https://github.com/dpgaspar/Flask-AppBuilder/blob/v3.4.5/examples/oauth/config.py#L71-L87) file, so we can probably copy that example into [`./docs/security.rst`](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/security.rst#authentication-oauth) to help users understand that this is an option.
> 
> **For example: (derived from `./examples/oauth/config.py`)**
> 
> ```python
> OAUTH_PROVIDERS = [
> ...
> ...
> ...
> {
>     "name": "azure",
>     "icon": "fa-windows",
>     "token_key": "access_token",
>     "remote_app": {
>         "client_id": "AZURE_APPLICATION_ID",
>         "client_secret": "AZURE_SECRET",
>         "api_base_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2",
>         "client_kwargs": {
>             "scope": "User.read name preferred_username email profile upn",
>             "resource": "AZURE_APPLICATION_ID",
>         },
>         "request_token_url": None,
>         "access_token_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2/token",
>         "authorize_url": "https://login.microsoftonline.com/AZURE_TENANT_ID/oauth2/authorize",
>     },
> },
> ...
> ...
> ...
> ]
> ```

is this working ?
