### ISSUE TITLE
readthedocs has not been updated for 4.0.0 release

### ISSUE THREAD

**Issue by thesuperzapper** [dpgaspar/Flask-AppBuilder#1836]
Currently, the docs on https://flask-appbuilder.readthedocs.io/en/latest/ have not been updated since the 3.4.0 release.

**Comment by thesuperzapper** [comment]
@dpgaspar I think you are the only one who can do this?

Perhaps we should create a github action to automatically do this for new releases?

**Comment by dpgaspar** [comment]
Updated, yes that's a very good idea, I'll look into how to trigger a build on readthedocs
