### ISSUE TITLE
Where should I put business logic?

### ISSUE THREAD

**Issue by noyeitan** [dpgaspar/Flask-AppBuilder#184]
Hi, 
I would like to add validators that are not field specific and I'm not sure where to add them.
For examples: When updating/deleting a record, I would like to check for some conditions on multiple fields and either ask for additional user confirmation or cancel the operation.

From looking in to the code it does not look like I can add a "non-field" specific validator. It looks like pre_update/pre_... do not have an option to cancel the operation.

I would like it to be low level enough that it applies to changes through the form or through the CRUD api. One place I thought would make sense is to sub-class the SQLAInterface and add inject my code on top of the add/edit/delete functions. But I'm not sure how this will allow me to send messages back to the user.
Another option was to sub-class the Form class and add code to the validate function.

What do you think?

**Comment by dpgaspar** [comment]
Good point, i'll make some tests to see if it's feasible to include some kind of generic return value on pre_add, pre_update etc...

**Comment by dpgaspar** [comment]
There are several ways to do it:

1 - Create you own WTF form and associate it to your ModelView using add_form or edit_form. Create your own validations also.

2 - Override the ModelView.add/edit method. Create whatever logic you would like.

3 - Next version i will add on pre_update, pre_add, pre_delete a boolean return value, so it can be possible to cancel the operation.

**Comment by dpgaspar** [comment]
Next version is out 1.4.2 (minor).
