### ISSUE TITLE
BuildError with related view and add_view_no_menu

### ISSUE THREAD

**Issue by ItWazzntMe** [dpgaspar/Flask-AppBuilder#185]
I get the following error when I try to set up a related view and add it via add_view_no_menu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/views.py", line 378, in show
    related_views=self._related_views)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 155, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 20, in block "content"
    {{ widgets.get('related_views')[loop.index - 1](pk = pk)|safe }}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 9, in top-level template code
    {{ lib.render_list_header(can_add, page, page_size, count, filters, actions, modelview_name) }}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/lib.html", line 248, in template
    {% set path = url_for(modelview_name + '.add') %}
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/lib64/python2.7/site-packages/werkzeug/routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)

But everything works fine if I add the view with add_view. 

My models are defined as so:

``` python
class Nic(AuditMixin, Model):
    __table_args__ = (UniqueConstraint('device_id', 'nictype_id'),)
    id = Column(Integer, primary_key=True)
    device_id = Column(Integer, ForeignKey('device.id'))
    device = relationship("Device")
    nictype_id = Column(Integer, ForeignKey('nic_type.id'))
    nictype = relationship("NicType")
    macaddress = Column(CHAR(12), unique=True, nullable=True)
    usedhcp = Column(Boolean, default=True)
class Device(AuditMixin, Model):
    __table_args__ = (UniqueConstraint('name', 'site_id'),)
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    description = Column(String(255))
    site_id = Column(Integer, ForeignKey('site.id'))
    site = relationship("Site")
    alias_id = Column(Integer, ForeignKey('device.id'))
    alias = relationship("Device")
    devicetype_id = Column(Integer, ForeignKey("device_type.id"))
    devicetype = relationship("DeviceType")
And views are:
class NicView(ModelView):
    datamodel = SQLAModel(Nic)
    label_columns = {'nictype': "NIC Type",
                     'macaddress': "MAC Address",
                     'usedhcp': "Generate DHCP", }
    add_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    edit_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    list_columns = ['nictype', 'macaddress', 'usedhcp','ipaddresses']
class DeviceView(ModelView):
    datamodel = SQLAModel(Device)
    label_columns = {'devicetype': "Device Type"}
    add_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    edit_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    list_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    show_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    related_views = [NicView]
```

**Comment by dpgaspar** [comment]
First use SQLAInterface instead of SQLAModel (take a look at the docs).
Second please post your **add_view_no_menu** command.

**Comment by ItWazzntMe** [comment]
I didn't catch in the docs what the difference between SQLAInterface and SQLAModel was. The skeleton project had SQLAModel imported by default.

Unfortunately changing to SQLAInterface did not help. I'm getting the same error/traceback.

Here's the full content of my source:
models.py:
import socket, struct
from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn
from sqlalchemy import Column, Integer, String, ForeignKey, Date, Text, CHAR, Boolean, Table, UniqueConstraint
from sqlalchemy.orm import relationship
from sqlalchemy import types

class Device(Model):
    __table_args__ = (UniqueConstraint('name', 'site_id'),)
    id = Column(Integer, primary_key=True)
    name = Column(String(64), nullable=False)
    description = Column(String(255))
    site_id = Column(Integer, ForeignKey('site.id'))
    site = relationship("Site")
    alias_id = Column(Integer, ForeignKey('device.id'))
    alias = relationship("Device")
    devicetype_id = Column(Integer, ForeignKey("device_type.id"))
    devicetype = relationship("DeviceType")

    def __repr__(self):
        return self.name


class Site(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(64), unique=True, nullable=False)
    description = Column(String(255))

    def __repr__(self):
        return self.name


class DeviceType( Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(64), unique=True, nullable=False)
    description = Column(String(255))

    def __repr__(self):
        return self.name


class IpAddress(Model):
    id = Column(IPAddress, primary_key=True)

    def __repr__(self):
        return self.id


assoc_ip_addresses_nic = Table('ip_address_nic', Model.metadata,
                               Column('id', Integer, primary_key=True),
                               Column('ip_address_id', Integer, ForeignKey('ip_address.id')),
                               Column('nic_id', Integer, ForeignKey('nic.id')))


class Nic(Model):
    __table_args__ = (UniqueConstraint('device_id', 'nictype_id'),)
    id = Column(Integer, primary_key=True)
    device_id = Column(Integer, ForeignKey('device.id'))
    device = relationship("Device")
    nictype_id = Column(Integer, ForeignKey('nic_type.id'))
    nictype = relationship("NicType")
    macaddress = Column(CHAR(12), unique=True, nullable=True)
    usedhcp = Column(Boolean, default=True)
    ipaddresses = relationship('IpAddress', secondary=assoc_ip_addresses_nic, backref='nic')

    def __repr__(self):
        return ':'.join(self.macaddress[i:i+2] for i in range(0, 12, 2))


class NicType(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(64), unique=True, nullable=False)
    description = Column(String(255))

    def __repr__(self):
        return self.name

views.py:
from flask.ext.appbuilder.models.sqla.interface import SQLAInterface
from flask.ext.appbuilder import ModelView
from app import appbuilder, db
from .models import Device, Nic, NicType, DeviceType, Site


class NicTypeView(ModelView):
    datamodel = SQLAInterface (NicType)
    add_columns = ['name', 'description']
    edit_columns = [ 'name', 'description']
    list_columns = ['name', 'description']


class NicView(ModelView):
    datamodel = SQLAInterface (Nic)
    label_columns = {'nictype': "NIC Type",
                     'macaddress': "MAC Address",
                     'usedhcp': "Generate DHCP", }
    add_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    edit_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    list_columns = ['nictype', 'macaddress', 'usedhcp',]
    show_columns = ['nictype', 'macaddress', 'usedhcp',]


class DeviceView(ModelView):
    datamodel = SQLAInterface (Device)
    label_columns = {'devicetype': "Device Type"}
    add_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    edit_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    list_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    show_columns = ['name', 'description', 'devicetype', 'site', 'alias']
    related_views = [NicView]

    show_template = 'appbuilder/general/model/show_cascade.html'
    edit_template = 'appbuilder/general/model/edit_cascade.html'

class DeviceTypeView(ModelView):
    datamodel = SQLAInterface (DeviceType)
    add_columns = ['name', 'description']
    edit_columns = ['name', 'description']
    list_columns = ['name', 'description']
    related_views = [DeviceView]

class SiteView(ModelView):
    datamodel = SQLAInterface (Site)
    related_views = [DeviceView]
    add_columns = ['name', 'description']
    edit_columns = ['name', 'description']
    list_columns = ['name', 'description']


db.create_all()
appbuilder.add_view(DeviceView, "Devices")
appbuilder.add_view_no_menu(NicView, "NICs")
appbuilder.add_view(DeviceTypeView, "Device Types", category="Configuration")
appbuilder.add_view(NicTypeView, "NIC Types", category="Configuration")
appbuilder.add_view(SiteView, "Sites", category="Configuration")


Thanks.

**Comment by dpgaspar** [comment]
This is probably because of the add_view_no_menu API change. Take a look at:

http://flask-appbuilder.readthedocs.org/en/latest/api.html#flask.ext.appbuilder.base.AppBuilder.add_view_no_menu

Just add it using: appbuilder.add_view_no_menu(NicView)

Tell me if it resolves the issue.

**Comment by ItWazzntMe** [comment]
Ah. Excellent. That did it. Thanks!

**Comment by scheung38** [comment]
Not what is the purpose of 'add_view_no_menu', Daniel could you expand why it is needed?
