### ISSUE TITLE
update `Authlib` requirement to allow version 1.0.1

### ISSUE THREAD

**Issue by thesuperzapper** [dpgaspar/Flask-AppBuilder#1861]
Currently, we are [restricting `Authlib` to `<1.0.0`](https://github.com/dpgaspar/Flask-AppBuilder/blob/v4.1.1/setup.py#L72) in our requirements, authlib has now released version [1.0.1](https://docs.authlib.org/en/latest/changelog.html) with lots of fixes and security patches, we should update our pin to allow 1.0.1.

Lots of people have been inadvertently testing using 1.0.1 for us! This is because airflow [forgot to pin `authlib`](https://github.com/apache/airflow/commit/6d7fa874ff201af7f602be9c58a827998814bdd1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R274) to the same versions as `Flask-AppBuilder`, so the latest `authlib` is always installed with airflow.

@potiuk you may want to look at that!

----

The main issues I see from people who have already tried to use 1.0.1, are related to `jwks_uri` not being set (rather than any actual issue with Flask-AppBuilder). 

The error text is: `Error authorizing OAuth access token: Missing "jwks_uri" in metadata`, see related issues:
- https://github.com/apache/superset/issues/13948#issuecomment-856981962
- https://github.com/dpgaspar/Flask-AppBuilder/issues/1821
- https://stackoverflow.com/questions/72035617/runtimeerror-missing-jwks-uri-in-metadata-for-flask-and-azure-ad-authlib

---

Currently, all of our [OAUTH security examples](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) don't show setting `jwks_uri` which is [now required](https://docs.authlib.org/en/latest/client/frameworks.html#parsing-id-token) when using `id_token` auth.
We need to update our examples to set `jwks_uri` so they continue to work with `authlib` 1.0.1.

__Example for Google with `jwks_url`:__

```python
OAUTH_PROVIDERS = [
    {
        "name": "google",
        "icon": "fa-google",
        "token_key": "access_token",
        "remote_app": {
            "client_id": "GOOGLE_KEY",
            "client_secret": "GOOGLE_SECRET",
            "api_base_url": "https://www.googleapis.com/oauth2/v2/",
            "client_kwargs": {"scope": "email profile"},
            "access_token_url": "https://accounts.google.com/o/oauth2/token",
            "authorize_url": "https://accounts.google.com/o/oauth2/auth",
            "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs",
        },
    },
]
```

---

We may also want to show setting `server_metadata_url` to an OpenID `/.well-known/openid-configuration` URL, (which replaces the need to set `authorize_url`, `access_token_url`, and `jwks_uri` so is a bit easier for people).

__Example for Google with `server_metadata_url`:__

```python
OAUTH_PROVIDERS = [
    {
        "name": "google",
        "icon": "fa-google",
        "token_key": "access_token",
        "remote_app": {
            "client_id": "GOOGLE_KEY",
            "client_secret": "GOOGLE_SECRET",
            "server_metadata_url": "https://accounts.google.com/.well-known/openid-configuration",
            "client_kwargs": {"scope": "email profile"},
        },
    },
]
```

__Example for Okta with `sever_metadata_url`:__

```python
OAUTH_PROVIDERS = [
  {
      "name": "okta",
      "icon": "fa-circle-o",
      "token_key": "access_token",
      "remote_app": {
          "client_id": "OKTA_KEY",
          "client_secret": "OKTA_SECRET",
          "server_metadata_url": "https://OKTA_DOMAIN.okta.com/.well-known/openid-configuration",
          "client_kwargs": {"scope": "openid profile email groups"},
      },
  },
]
```

**Comment by thesuperzapper** [comment]
@dpgaspar thoughts on this?

**Comment by potiuk** [comment]
> @potiuk you may want to look at that!

Ah. Cool yhanks for that. I will update it. Actually the setup.py entry is wrong in a different way. We should use "flask-app-builder[oauth]" as dependency there so that we do not have to manually sync dependencies when FAB updates it.

BTW. We have just started to migrate to FAB 4.0 @thesuperzapper - you might want to join our crew of people who will help with testing it (there are many breaking changes in the underlying libraries). I've added you so to that you are aware and possibly help us with testing Airfflow  https://github.com/apache/airflow/issues/22397#issuecomment-1156603972 

In the meantime - indeed upgrading of the authlib in FAB 4.1.2 might be a good idea indeed (and once we use oauth extra, airflow deps will update automatically)

**Comment by dpgaspar** [comment]
I'll open a PR to bump and test authlib

**Comment by potiuk** [comment]
Also @thesuperzapper we have a way to fix that for you users too (and ours). I am going to update constraint and re-generate docker images with authlib=1.0.0

**Comment by thesuperzapper** [comment]
@potiuk actually the version would need to be the last `0.X` version (which is `0.15.5`) for this `jwks_uri` issue not to be a problem.

But I think we may as well keep `1.0.1` as the authlib version in the docker containers (it's only installed in the 2.2.0 containers and later anyway).

**Comment by potiuk** [comment]
Right....

**Comment by potiuk** [comment]
I prefer to get it "*updated to latest authlib*" in upcoming 2.3.3 (I hope we will upgrade to FAB 4 by then rather than break oauth for 2.2.5 - 2.3.2 users :)

**Comment by potiuk** [comment]
BTW. 2.2.4 and below had 0.15.5

**Comment by potiuk** [comment]
@thesuperzapper - FYI: all constraints and images of Airlfow 2.2.5, 2.3.0, 2.3.1. 2.3.2 are refreshed now.

**Comment by Narender-007** [comment]
when i am using azure authentication in flask app builder getting this error :

Error returning OAuth user info: %s 'upn'
2023-08-01 12:04:40,989:ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'upn'

how can i resolve it
