### ISSUE TITLE
Updating from a given JSON

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#187]
Could I pre-populate database with a JSON file?

**Comment by dpgaspar** [comment]
If i understand correctly this is not a flask-appbuilder question but more a SQLAlchemy question:

The answer may depend on you backend (MySQL, PostGres, SQLLite, ORACLE etc....).
You can allways *load* the JSON file and then iterate it, on each iteration create a Model object and insert it on the DB using SQLAlchemy.
