### ISSUE TITLE
Relation columns are shown which should be hidden

### ISSUE THREAD

**Issue by ThomasP0815** [dpgaspar/Flask-AppBuilder#1892]
### Environment

Flask-Appbuilder version: 4.1.3

### Describe the expected results

I extended the example "quickhowto" by excluding the field "contact_group" from search.

class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)
    ...
    search_exclude_columns = ["contact_group"]

I expected this result:

![image](https://user-images.githubusercontent.com/30863072/179518583-92e5c820-86df-47dd-a4b0-a5f92fca86e7.png)
 

### Describe the actual results

I extended the example "quickhowto" by excluding the field "contact_group" from search.

class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)
    ...
    search_exclude_columns = ["contact_group"]

I got this:

![image](https://user-images.githubusercontent.com/30863072/179518707-6d4bc522-50f8-4918-80b1-4eab7c6e9625.png)

Analysis:

I think the pull request #1862 causes this problem.
![image](https://user-images.githubusercontent.com/30863072/179520002-4841eba3-f99a-4bae-93dc-a84b3ac24a2c.png)

I think issue #1867 is also related to this problem.

**Comment by dpgaspar** [comment]
Thank you for the report, this looks like a bug.

**Comment by dpgaspar** [comment]
@ThomasP0815,

`search_exclude_columns` does not relate with the edit form. Why were you expecting for the field to be excluded?

**Comment by ThomasP0815** [comment]
get_filter_args changes self._filters
thats why exclude_cols does not include the relation anymore!

![image](https://user-images.githubusercontent.com/30863072/180438409-3266e0b6-5427-4a96-a265-eaad418308cf.png)

**Comment by dpgaspar** [comment]
Sorry, I may be miss understanding, this what you've reported. So you excluded `contact_group` from the search and it's rendered on the edit form

<img width="754" alt="Screenshot 2022-07-22 at 16 16 44" src="https://user-images.githubusercontent.com/4025227/180470489-1efbd2a0-69d0-47c4-9a8f-33e52d3991de.png">

**Comment by dpgaspar** [comment]
I'll double check

**Comment by ThomasP0815** [comment]
Navigation path:

- menu "Contacts" -> "List Groups"
- show "Friends"
- tab "List Contacts"
- edit "Abbey Szkarlat Faraday Etti"
- "contact group" field should be hidden

**Comment by dpgaspar** [comment]
why should it be hidden? we are excluding it from search not from the edit form

**Comment by ThomasP0815** [comment]
counter question, why was this field hidden in the past (using version 3.4.5)?

**Comment by dpgaspar** [comment]
Tested on 3.4.5 an got the same behaviour.

For example using the examples quickhowto, create a new `ModelView`:
```
class ContactModelView2(ModelView):
    datamodel = SQLAInterface(Contact)

    list_columns = ["name", "personal_celphone", "birthday", "contact_group.name"]

    base_order = ("name", "asc")
    edit_columns = ["name", "personal_celphone", "birthday", "contact_group"]
    search_exclude_columns = ["contact_group"]

...
appbuilder.add_view(
    ContactModelView2, "List Contacts2", icon="fa-envelope", category="Contacts"
)
```

On the UI, the search is excluded:
<img width="690" alt="Screenshot 2022-07-27 at 10 46 45" src="https://user-images.githubusercontent.com/4025227/181217411-5e154fa7-c564-43ab-8809-bba96ed849b5.png">

The edit form still shows `contact_group`:
<img width="654" alt="Screenshot 2022-07-27 at 10 48 01" src="https://user-images.githubusercontent.com/4025227/181217642-b8120568-8ed8-4e91-81f9-eef4c82ee710.png">

**Comment by ThomasP0815** [comment]
Yes this result is alwright, but you didn't follow the naviation path!

Navigation path:

    menu "Contacts" -> "List Groups"
    show "Friends"
    tab "List Contact"
    edit "Abbey Szkarlat Faraday Etti"
    "contact group" field should be hidden

**Comment by dpgaspar** [comment]
oh! I see what you mean, it's on the related model views. sorry

It's a bug, needs to be fixed

**Comment by dpgaspar** [comment]
@ThomasP0815 got a fix up: https://github.com/dpgaspar/Flask-AppBuilder/pull/1898

**Comment by dpgaspar** [comment]
Thank you for the bug report, this is currently fixed on master. Will make a new release soon
