### ISSUE TITLE
Customise field rendering in model view ?

### ISSUE THREAD

**Issue by stuaxo** [dpgaspar/Flask-AppBuilder#190]
How can I customise field rendering in the model view, to do things like make urls into links or other miscellaneous text munging.

**Comment by dpgaspar** [comment]
It depends, if you want to change the rendering of fields on lists you can use two different aproaches:

1 - Use a ModelView custom methods as columns. Take a look at: http://flask-appbuilder.readthedocs.org/en/latest/quickfiles.html

2 - Create custom widgets and reuse them: http://flask-appbuilder.readthedocs.org/en/latest/templates.html#widgets

For form fields, you can create custom WTForm fields and "tell" ModelView's to use them.
http://flask-appbuilder.readthedocs.org/en/latest/advanced.html#forms

**Comment by stuaxo** [comment]
Cheers - was hoping to be able to be able to pass a callable as a column, but having it on the view is also fine :)
