### ISSUE TITLE
flask_appbuilder.security.views:No whitelist for OAuth provider

### ISSUE THREAD

**Issue by evanerwee** [dpgaspar/Flask-AppBuilder#1902]
Why do I get: flask_appbuilder.security.views:No whitelist for OAuth provider
### Environment

Flask-Appbuilder version: latest

pip freeze output:

anyjson @ file:///home/conda/feedstock_root/build_artifacts/anyjson_1620792011962/work
apispec @ file:///home/conda/feedstock_root/build_artifacts/apispec_1598774312921/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///D:/bld/argon2-cffi-bindings_1649500515836/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1643313750486/work
astroid @ file:///C:/ci/astroid_1628063282661/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1659291887007/work
Authlib==1.0.1
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1655419414885/work
bcrypt @ file:///D:/bld/bcrypt_1651441745194/work
brotlipy==0.7.0
certifi @ file:///C:/Windows/TEMP/abs_e9b7158a-aa56-4a5b-87b6-c00d295b01fanefpc8_o/croots/recipe/certifi_1655968940823/work/certifi
cffi @ file:///D:/bld/cffi_1656782930891/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///D:/bld/click_1651215430313/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1655412516417/work
colour==0.1.5
cryptography @ file:///D:/bld/cryptography_1657174166005/work
dnspython @ file:///home/conda/feedstock_root/build_artifacts/dnspython_1646621171513/work
email-validator @ file:///home/conda/feedstock_root/build_artifacts/email-validator-meta_1651458094096/work
Flask @ file:///opt/conda/conda-bld/flask_1648041541647/work
Flask-AppBuilder @ file:///home/conda/feedstock_root/build_artifacts/flask-appbuilder_1657136469192/work
Flask-Babel @ file:///home/conda/feedstock_root/build_artifacts/flask-babel_1598620434524/work
Flask-Genshi==0.5.1
Flask-JWT-Extended @ file:///home/conda/feedstock_root/build_artifacts/flask-jwt-extended_1658977396494/work
Flask-Login @ file:///home/conda/feedstock_root/build_artifacts/flask-login_1658793187139/work
Flask-SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/flask-sqlalchemy_1616102249273/work
Flask-WTF @ file:///tmp/build/80754af9/flask-wtf_1622018667443/work
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1645629044586/work/source/flit_core
furl @ file:///home/conda/feedstock_root/build_artifacts/furl_1632798741194/work
Genshi==0.7.7
greenlet @ file:///D:/bld/greenlet_1648882589361/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1642433548627/work
importlib-metadata @ file:///D:/bld/importlib-metadata_1653252997230/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1658604161399/work
infinity @ file:///home/conda/feedstock_root/build_artifacts/infinity_1622383622831/work
intervals @ file:///home/conda/feedstock_root/build_artifacts/intervals_1625223179549/work
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1648147185463/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1659525086692/work
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529288960/work
MarkupSafe @ file:///D:/bld/markupsafe_1648737757460/work
marshmallow @ file:///home/conda/feedstock_root/build_artifacts/marshmallow_1656394161184/work
marshmallow-enum @ file:///home/conda/feedstock_root/build_artifacts/marshmallow-enum_1602427317752/work
marshmallow-sqlalchemy @ file:///home/conda/feedstock_root/build_artifacts/marshmallow-sqlalchemy_1623007433413/work
mccabe==0.6.1
orderedmultidict==1.0.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
passlib==1.7.4
pendulum @ file:///D:/bld/pendulum_1649254700992/work
phonenumbers @ file:///home/conda/feedstock_root/build_artifacts/phonenumbers_1659637215673/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
prison @ file:///home/conda/feedstock_root/build_artifacts/prison_1631689776410/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1652398519695/work
pylint @ file:///C:/ci/pylint_1627536884966/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyrsistent @ file:///D:/bld/pyrsistent_1649013531721/work
PySocks @ file:///C:/ci/pysocks_1605307512533/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1647961439546/work
pytzdata @ file:///home/conda/feedstock_root/build_artifacts/pytzdata_1594644346367/work
PyYAML @ file:///D:/bld/pyyaml_1648757346451/work
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
SQLAlchemy @ file:///D:/bld/sqlalchemy_1659998891615/work
SQLAlchemy-Utils @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy-utils_1644108849278/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1656706066251/work
urllib3 @ file:///C:/ci/urllib3_1650639883891/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1660053523487/work
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306162074/work
wincertstore==0.2
wrapt @ file:///C:/ci/wrapt_1607574570428/work
WTForms @ file:///home/conda/feedstock_root/build_artifacts/wtforms_1634562573864/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1659400682470/work

Using Azure Login. Error:  Invalid login. Please try again. (Login in DEBUG is successfull. JWT Token parse correctly.)

**Comment by evanerwee01** [comment]
Solved

AUTH_PROVIDERS = [
    {
        "name": "azure",
        "icon": "fa-windows",
        "token_key": "access_token",
        "whitelist": ["@somecompany.com"],

**Comment by dpgaspar** [comment]
Assuming this is solved, feel free to reopen if not
