### ISSUE TITLE
[question] how do I create my own set or permissions?

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#192]
First let me say that I'm coming from Django / FlaskAdmin and I'm really glad I found this project. I really enjoy having the battery included in terms of auth and the CRUD look great. 

I have a view for which I want to break down the permissions, meaning that depending on the parameter that is passed to the view I want to look up whether the person can see this view for this parameter. 

So either I'd have to do a bit of meta programming and generate views dynamically, or I can actually register my own set of permissions, and check whether the user has access to this view/parameter combination inside my view.

It looks like the API is built around the idea of permissions generated by the framework, and the use of decorators to implement them. How do I take control?!

**Comment by dpgaspar** [comment]
Thanks, glad you like it.

This is an interesting question, i never tried it, i guess you can create your own *special* decorator for this based on has_access. You need to insert your own permissions and their relation with the views (they are currently mapped with methods and view classes).

I'll make an example for this, see if this is feasible and get back.
