### ISSUE TITLE
Is the oauth state parameter mishandled?

### ISSUE THREAD

**Issue by egurnick** [dpgaspar/Flask-AppBuilder#1925]
The oauth "state" parameter, used to prevent csrf attacks, is generated in fab like so for each auth request

https://github.com/dpgaspar/Flask-AppBuilder/blob/e7692d1d87a1ff76359950711fa733b89c507227/flask_appbuilder/security/views.py#L622-L626

Where `config["SECRET_KEY"]` is defined in config.py (and should be set by the developer)
https://github.com/dpgaspar/Flask-AppBuilder/blob/27b15e59316e85e0fe62b8aa9978391ed4c729c9/bin/config.py#L5

and `request.args` is defined as
https://github.com/pallets/werkzeug/blob/main/src/werkzeug/sansio/request.py#L170-L185

```
    def args(self) -> "MultiDict[str, str]":
        """The parsed URL parameters (the part in the URL after the question
        mark).
        By default an
        :class:`~werkzeug.datastructures.ImmutableMultiDict`
        is returned from this function.  This can be changed by setting
        :attr:`parameter_storage_class` to a different type.  This might
        be necessary if the order of the form data is important.
        """
        return url_decode(
            self.query_string,
            self.url_charset,
            errors=self.encoding_errors,
            cls=self.parameter_storage_class,
        )
```

Thus, the state parameter is essentially a constant and has the same value over multiple auth requests. If config["SECRET_KEY"]` is known, the state parameter is predictable. 

The oauth standard states
https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.1
>state
         RECOMMENDED.  An opaque value used by the client to maintain
         state between the request and callback.  The authorization
         server includes this value when redirecting the user-agent back
         to the client.  The parameter SHOULD be used for preventing
         cross-site request forgery as described in [Section 10.12](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12).

https://datatracker.ietf.org/doc/html/rfc6749#section-10.12
>state (e.g., a hash of the session
   cookie used to authenticate the user-agent)

All other implementations I have seen use a randomly generated string for each new auth request

Is this correct usage of the state parameter?

**Comment by dpgaspar** [comment]
Thank you for reporting.
although it's an opaque value and prevent CSRF, I agree we should be using a random string. I'll make a fix ASAP.

**Comment by dpgaspar** [comment]
Got a PR up #1932 , @egurnick a review would be great

**Comment by dpgaspar** [comment]
merged will be included on the next release

**Comment by egurnick** [comment]
Looks good, nice solution, thank you @dpgaspar !
