### ISSUE TITLE
[question] authentication using http headers

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#194]
I work in an corporate environment that provides an authentication service that acts as a reverse proxy and provides headers with the user's name and information about their LDAP groups. I'm interested in using that to create and authenticate users on the fly using these headers.

Can someone either point to a shortcut to do this easily, or give pointers on how to write a new authentication backend to support this.

**Comment by mistercrunch** [comment]
For reference, here's how it's done using Django:
https://docs.djangoproject.com/en/1.8/howto/auth-remote-user/

**Comment by dpgaspar** [comment]
You can use REMOTE_USER too, set by the web server. config the AUTH_TYPE = AUTH_REMOTE.
This user must be equal to ab_user.username.
