### ISSUE TITLE
AdminLTE - Theme Support (help wanted)

### ISSUE THREAD

**Issue by mariofix** [dpgaspar/Flask-AppBuilder#1946]
Hello all, I'm working on a way to update the current default theme to AdminLTE and -hopefully- end up with a nicer way to create new templates, my working repo is at https://github.com/mariofix/fab-theme-adminlte 

right now I'm taking the route to replace and update the original template files under "templates/appbuilder/", I copied them to my app and started changing html.

If anyone would like to contribute or making recommendations as to how to do this, feel free to do so.
I'm @mariofix in most networks

**Comment by alitrack** [comment]
Which version FAB you support? 
I tried your theme, got the following error,

```
jquery.min.js:2 Uncaught TypeError: $(...).datetimepicker is not a function
    at HTMLDocument.<anonymous> (ab.js:50:31)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)
```

tested on fab 4.1.5 and 4.1.6 with the same issue.

**Comment by mariofix** [comment]
Hi @alitrack thanks for your reply, I would be very surprised if that worked, it's only the first commit not close to test.

I'm looking for contributors for this project, if you'd like to help in make it possible, let me know.

**Comment by alitrack** [comment]
You just want someone to make the theme work for you, right?

**Comment by mariofix** [comment]
not at all, i'm really looking for help to add theme support to FAB, it's the one thing preventing me to use FAB in my projects is the lack of themes (yeah, I know...). I have a  few django projects where I use django-baton to overwrite the default theme.

I was looking for a similar way to do this (I could just copy what's in django-baton and try to apply it to FAB, but i prefer to start something new), I first tried to overwrite the files in appbuilder with some python magic, but i decided on the long road described in the documentation:
- Copy all the files from appbuilder/template and start changing the html to match what's on AdminLTE HTML structure.
- Then try to find a way for an addon to register and use the new template, without any python code (by just registering on ADDON_MANAGERS)
- If this goes well, try to merge into FAB itself to incorporate the theme support (and not just a style from bootswatch) by default.

I've done my first commit and also decided to ask for help in case anyone was interested into helping achieve this, but I understand why you think I just wanted someone to do this for me.

Anyway, if you want to help or recommend anything in any way, it would be welcome.
