### ISSUE TITLE
FAB 4.1.0 / sqlalchemy 1.4/ mssql ab_user issues

### ISSUE THREAD

**Issue by samhoustonusyd** [dpgaspar/Flask-AppBuilder#1953]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

Responsible disclosure:
We want to keep Flask-AppBuilder safe for everyone. If you've discovered a security vulnerability
please report to danielvazgaspar@gmail.com.

### Environment

Flask-Appbuilder version:

4.1.0

pip freeze output:
[env.yml.txt](https://github.com/dpgaspar/Flask-AppBuilder/files/10080449/env.yml.txt)

### Describe the expected results
The problem is when I try to add a user.
Back end database is MSSQL in Azure

Tell us what should happen.

User Should get added normally.

### Describe the actual results

Tell us what happens instead.
In the UI I get :
General Error <class 'sqlalchemy.exc.ProgrammingError'>

At the console I see:
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [FreeTDS][SQL Server]Invalid object name 'ab_user_id_seq'. (208) (SQLExecDirectW)")
[SQL: INSERT INTO ab_user (id, first_name, last_name, username, password, active, email, last_login, login_count, fail_login_count, created_on, changed_on, created_by_fk, changed_by_fk) OUTPUT inserted.id VALUES (NEXT VALUE FOR ab_user_id_seq, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]

```pytb
Paste the full traceback if there was an exception.
```

### Steps to reproduce

If I revert sqlalchemy to 1.3.18 and do nothing else: - the problem disappears - but I would like to standardise on 1.4 now

I acknowledge that the issue may be sqlalchemy/ sql rather than fab...

Thanks for your help!
Sam

**Comment by dpgaspar** [comment]
Thank you for reporting this.

FAB CI is running tests against MSSQL 2017-CU8: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/.github/workflows/ci.yml#L124

and sqlalchemy==1.4.29

looking at your env, I see your using sqlalchemy=1.4.44.

Can you please test with 1.4.29 to try to narrow the issue down?

**Comment by samhoustonusyd** [comment]
Hi again, I put sqlalchemy back to 1.4.0 and problem still occurs...

**Comment by samhoustonusyd** [comment]
Could the issue be related to this:?
https://docs.sqlalchemy.org/en/14/dialects/mssql.html#sequence-support

SEQUENCE support
The [Sequence](https://docs.sqlalchemy.org/en/14/core/defaults.html#sqlalchemy.schema.Sequence) object now creates “real” sequences, i.e., CREATE SEQUENCE. To provide compatibility with other dialects, [Sequence](https://docs.sqlalchemy.org/en/14/core/defaults.html#sqlalchemy.schema.Sequence) defaults to a start value of 1, even though the T-SQL defaults is -9223372036854775808.

New in version 1.4.0.

Also - looking at the database the sequence is actually dbo.user_id_seq - but the error from fab is about 'ab_user_id_seq'.  

I think I have found the issue....If sqlalchemy 1.4 is used, sequence objects are created in server\Programmability\Sequences when the app is created.  They are what is referenced (to get the next index for a user etc) when users are added.

If the database has been created using sqlalchemy 1.3 - these objects do not exist.  Not sure how to fix yet - but thats the issue.   Some sort of database migration is required.  I have tried manually creating the objects that aure auto created when using 1.4 - but I get a different error

**Comment by samhoustonusyd** [comment]
some pics to explain further.  db when created using sqlalchemy 1.3.18
![image](https://user-images.githubusercontent.com/38679101/205547808-1331eacb-db2e-406e-b5a1-3d444fb4f636.png)

and when using sqlalchemy 1.4.44
![image](https://user-images.githubusercontent.com/38679101/205547996-9cf3a519-96a0-4384-bfef-360a9881e1c9.png)

**Comment by samhoustonusyd** [comment]
Just to clarify - the issue occurs when upgrading sqlalchemy to 1.4 in an environment which has been created using 1.3.18.  If you stay in the version that was used when the db was created - there are no issues...

**Comment by dpgaspar** [comment]
Great troubleshooting @samhoustonusyd, makes perfect sense to me. That also explains why current tests run perfectly fine with sqlalchemy 1.4.X and MSSQL.

It must be possible to create the missing sequences on `ab_` tables, but I expect this must occur on all other app tables, are you using alembic for db migration?

**Comment by samhoustonusyd** [comment]
ok, I never figured out alembic.  However - I managed to manually fix this issue:
i. Create sequence objects for both ab_user and ab_user_role table ids:

CREATE SEQUENCE [dbo].[ab_user_id_seq] 
 AS [bigint]
 START WITH 100
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO


CREATE SEQUENCE [dbo].[user_id_seq] 
 AS [bigint]
 START WITH 100
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO

Remove IDENTITY from both ab_user and ab_user_role tables

1. Add a new temporary column.
2. Update the new column with the same values.
3. Set the new column as NOT NULL.
4. Drop Foreign Keys Constraints.
5. Drop Primary Key.
5. Drop IDENTITY column.
6. Rename the new column with the name of the old one.
7. Add new Primary Key.
8. Change id column type to BIGINT

Thats it - you can now use FAB, with Azure MSSQL with sqlalchemy 1.4 and manage users...

This may need to be done on the other ab tables which use IDENTITY...haven't tested that yet.
