### ISSUE TITLE
Numeric support

### ISSUE THREAD

**Issue by Bengreen** [dpgaspar/Flask-AppBuilder#198]
Do you provide or intend to support Numeric data types for currency, etc ?

**Comment by Fuzzwah** [comment]
I've found that as long as I don't have numeric fields searchable they'll work.

From my models.py:

```
class Driver(Model):
    __tablename__ = 'driver'
    id = Column(Integer, primary_key=True)
    name = Column(String(250), nullable=False)
    current_value = Column(Numeric(5, 2))
```

In views.py:

```
class Drivers(ModelView):
    datamodel = SQLAInterface(Driver)
    label_columns = {'name': 'Driver', 'id': 'Number', 'current_value': 'Value'}
    list_columns = ['name', 'id', 'current_value']
    search_columns = ['name']
    base_order = ('current_value', 'desc')
```

If I don't have ```search_columns``` set it'll throw an error due to wtforms search function.

**Comment by dpgaspar** [comment]
Sorry for the late answer. 

mmm, thats not very good... Let me make some tests.

**Comment by dpgaspar** [comment]
I'm going to run some tests for Numeric data type, meanwhile can you use Float?

``` python

def test():
        return math.pi - 1.0

class FloatModel(Model):
    id = Column(Integer, primary_key=True)
    value = Column(Float, nullable = False, default=test)


    def __repr__(self):
        return self.value
```

**Comment by Bengreen** [comment]
Float is not good because i need the field for currency and float is approximate. That is why i want to use Numeric

**Comment by dpgaspar** [comment]
Ok, i will add support for Numeric next version (1.4.5). I'll release it ASAP.

**Comment by dpgaspar** [comment]
Hello, sorry for the delay. 1.4.5 is out (finally) and brings support for Numeric data type.
