### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by pUC19** [dpgaspar/Flask-AppBuilder#1982]
Hello, is there a way to completely redesign the login page? If yes, what is the best way to go about it? Best regards

**Comment by soundmaking** [comment]
I only made small changes to the login page - adding a single link... starting point for me towards that was :
https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

the link I added was for "Forgot password" and then the app has a custom set of methods and objects to handle a process around that... some of which described in 
https://github.com/dpgaspar/Flask-AppBuilder/issues/1485#issuecomment-752283155

...but that's getting off topic from redesigning the Login page - start with teh docs for how to serve customise security.

some snippets from my app:
```python
# in sec_views.py
class MyAuthDBView(AuthDBView):
    """Custom login view"""
    login_template = "login.html"
```

```python
# in sec.py
class MySecurityManager(SecurityManager):
    """
    custom SecurityManager for appbuilder
    available in the app as appbuilder.sm
    """
    registeruserdbview = MyRegisterUserDBView
    authdbview = MyAuthDBView
```

**Comment by pUC19** [comment]
Thank you very much. Your approach helps me a lot.
