### ISSUE TITLE
FTSDocuments: an appbuilder show case with FTS5 SQLITE

### ISSUE THREAD

**Issue by gbrault** [dpgaspar/Flask-AppBuilder#1987]
@dpgaspar can you please go and see: https://github.com/gbrault/FTSDocuments

I needed to make few tweaks to come to this (in appbuilder) and you can have a look and tell me if you would like to integrate them in the main stream?

I tried to make a pull requests, but I am not successful!

Thanks for your work and your support!

**Comment by gbrault** [comment]
@dpgaspar , I have finally used a systematic "Monkey Patching" strategy to avoid bothering you with too specific ECO (Engineering Change Orders). It as been applied in the above project and documented as well.
May be it's something you could publicized as it could help you avoid facing the same problem with other flask-appbuilder?

**Comment by dpgaspar** [comment]
Thank you for sharing, very helpful example

It's possible to add custom filters to the existing `ModelRestApi` and `ModelView`, so you probably don't need to patch it like on: https://github.com/gbrault/FTSDocuments/blob/master/patch_flask_appbuilder/flask_appbuilder/models/sqla/filters.py#L9

Friendly advice, ideally if you need to change/add flask-appbuilder feel free to make a PR, I'll try my best to help you get it merged. Another approach would be to fork the project and install the package from the fork or make it public on pypi, could be hard to maintain but probably easier then monkey patching the package after installing.

Making a Pull Request (PR):
- fork flask-appbuilder, it will create a copy of the project on your own github account
- locally: `git clone <YOU_FORK_URL>`
- create a branch on your fork: `git checkout -b <MY_BRANCH_NAME>` ex: feat/new-match-filter
- make the necessary changes, commit push etc
- go to your project on github, it will show a banner to create a PR with your changes

**Comment by gbrault** [comment]
Thanks @dpgaspar and few comments

- The patching is not only filtering, but also adding the Matching token in the UI interface.
- Patching enable to use your last update code with just a review for compatibility, so, at the end it's not so much work
- I fully understand you cannot accept all the modifications from all your user, it's perfectly fine
- Patching, including monkey patching, centralized and documented is not so harmful and too bad git doesn't support it so well

Concerning the PR, It's what I am doing except the checkout, I will try then to see if it works better.

Thanks again for your code it is very helpful for my current projects.
