### ISSUE TITLE
Issue with Search 'ends with', with FAB 4.2, 4.2.1, 4.3 (OK with 4.1)

### ISSUE THREAD

**Issue by samhoustonusyd** [dpgaspar/Flask-AppBuilder#2004]
### Environment
[environment.txt](https://github.com/dpgaspar/Flask-AppBuilder/files/10964197/environment.txt)

Tell us what should happen.
When using search 'ends with' - reduced list showing only matching records should appear

Use employees example with the environment above

### Describe the actual results
all records are shown.  Somehow the endpoint when using FAB >=4.2 is miscalculated (see url) 
![image](https://user-images.githubusercontent.com/38679101/224896570-0a5fb9ea-5490-49b5-949f-e6d637ae3865.png)

if the 'flt_undefined' is edited to 'flt_1' , it works.

Roll back to FAB 4.1 and importantly clearing browser cache resolves the issue

Issue also occurs with 'contains', but not 'starts with'

**Comment by samhoustonusyd** [comment]
Thanks Daniel - it works...when might it hit Pypi/ conda?

**Comment by dpgaspar** [comment]
it's out: https://pypi.org/project/Flask-AppBuilder/4.3.1/ on Pypi
