### ISSUE TITLE
flask_appbuilder/static/appbuilder/css/font-awesome.min.css file is missing in the source distribution

### ISSUE THREAD

**Issue by bkyryliuk** [dpgaspar/Flask-AppBuilder#2059]
flask_appbuilder/static/appbuilder/css/font-awesome.min.css file is missing in the source distribution but is present in the wheel.
To manually check it, it is possible to download files form https://pypi.org/project/Flask-AppBuilder/#files unpack or wheel unpack and check the context

This leads to a missing font in superset that uses flask app builder >= 4.3.0
<img width="990" alt="image" src="https://github.com/dpgaspar/Flask-AppBuilder/assets/5727938/ba847626-ccc9-48d5-99e0-b5af00604eab">

### Environment
Flask-Appbuilder version: >= 4.3.0

### Steps to reproduce

```pip install Flask-AppBuilder==4.3.2 --no-binary :all:```   and check that is missing in the distribution

alternatively run superset with the Flask-AppBuilder built from source and check editing the columns in the datasets, expand button will be missing due to the missing css file.

**Comment by dpgaspar** [comment]
I believe the name changed, it's called `css/fontawesome/fontawesome.min.css` now

**Comment by bkyryliuk** [comment]
yep, saw that however superset somehow is still referencing `flask_appbuilder/static/appbuilder/css/font-awesome.min.css` and that file is present in the wheel distribution. 
Unfortunately I don't know much how fonts / css files are discovered to provide more info here

**Comment by dpgaspar** [comment]
checking if Superset should be calling `super()` on that block
