### ISSUE TITLE
multiple primary_key

### ISSUE THREAD

**Issue by Bengreen** [dpgaspar/Flask-AppBuilder#207]
I have a table which needs to use more than one column to create the unique primary_key.
I believe this is supported in sqlalchemy. I tried it in FAB, but found that it was possible to look at the list view, but not the show view as it crashed because only one pk was coming through.

Does FAB support multiple keys for the primary_key and if so is there a specific construct to do this ?

**Comment by dpgaspar** [comment]
Sorry, this is not supported.

**Comment by EvilConsultant** [comment]
Multiple primary_keys is still not supported? Could I add this as an enhancement request? Same issue, I have several tables that use multiple primary_keys (in my case, copied data from different ecom stores where store_id and item_id are keys). I guess the work around is to add another unique key and autoincrement it, but just curious how common the use case is.
