### ISSUE TITLE
CRUD Security API for permissions-resources endpoint: columns not allowed to filter

### ISSUE THREAD

**Issue by nhan34** [dpgaspar/Flask-AppBuilder#2074]
I am using the latest version of Superset and have enabled the FAB_ADD_SECURITY_API flag to expose and use the endpoints for the Security permissions CRUD API #1801. 

I am using Postman to GET from the /api/v1/security/permissions-resources/ endpoint with the following query filter parameter:

```python
{"filters": [ {"col" : "permission.name", "opr" : "eq", "value" : "database_access"} ]}
```

However, instead of receiving permission-resource entries that fulfill this parameter, I get the message: "Filter column: permission.name not allowed to filter". This applies to all three columns in the permissions-resources endpoint, including id and view_menu.name. 

### Notes
- I have tried the same query and filter on different endpoints, including /api/v1/security/permissions/, /api/v1/security/resources/, and /api/v1/security/users/, but do not get the same error as the permissions-resource endpoint (the queries work). 
- I am logged in as the superuser of the Superset application (admin), which has the most auth possible, when making these calls.

### Steps to reproduce

- [ ] Expose the Security API endpoints for FAB
- [ ] Test the /api/v1/security/permissions-resources/ endpoint with the given query filter parameter

Thank you!

**Comment by dpgaspar** [comment]
Unfortunately this is currently not supported, you have to make 2 API calls:

One to fetch the permission id, and a final to `api/v1/security/permissions-resources/` with:
```
{
  "filters": [
    {
      "col": "permission",
      "opr": "rel_o_m",
      "value": 1
    }
  ]
}
```

**Comment by dpgaspar** [comment]
Closing this issue, feel free to reopen if you need more info
