### ISSUE TITLE
Pagination with Mongo

### ISSUE THREAD

**Issue by mgellesch** [dpgaspar/Flask-AppBuilder#208]
I have a relatively simple mongo document but with about 18000 entries. It is veryyyy slow to load (20s+). Is it possible that pagination isn't working right? I profiled the db queries which are fast, but the data download is very slow (both with local db and remote mongolabs). With fewer entries (<100) the listview loads much faster. Any ideas?

Thx!

**Comment by mgellesch** [comment]
Update: I found the problem. The given method was downloading all 18000 entries from the server due to len(objs). I created a pull request with a few additional improvements and bug fixes for the method.

**Comment by dpgaspar** [comment]
Great work, thanks!
