### ISSUE TITLE
413 when editing role with more than 1000 users.

### ISSUE THREAD

**Issue by Always-prog** [dpgaspar/Flask-AppBuilder#2085]
Hello!
Editing role that is assigned to 1000+ users raise error in werkzeug due-to more than 1000 form_parts (max_form_parts in werkzeug is set to 1000).
### Environment

Flask-Appbuilder version: 4.3.3

### Describe the expected results

Saving role successfully
### Describe the actual results
Got error 413

![image](https://github.com/dpgaspar/Flask-AppBuilder/assets/66589759/61b620ef-5ed1-4d72-9e57-1fa38695e65f)

### Steps to reproduce
Add 1000 users to the one role and try to edit and save that role.

**Comment by dpgaspar** [comment]
Interesting, could not reproduce the issue on 4.3.3 nor 4.3.4, 4.3.5, when saving the role I get no users being submitted.

No users field on the roles edit form:

<img width="953" alt="Screenshot 2023-07-27 at 16 17 59" src="https://github.com/dpgaspar/Flask-AppBuilder/assets/4025227/e6b8ce69-ab49-4757-844c-7d8232890ee5">

**Comment by Always-prog** [comment]
@dpgaspar Hmm, I'm experiencing this issue in the latest master of Apache Superset. When I save a role, the Form Data includes the full list of users. 

If you tested it in the clear FAB and couldn't reproduce the issue, how does the updated users list return to Flask?

**Comment by dpgaspar** [comment]
Superset is slightly overriding Role list and edit view, here: https://github.com/apache/superset/blob/master/superset/security/manager.py#L138
Since this is not a FAB specific issue, please open an issue there or propose a PR with the change. Thank you
