### ISSUE TITLE
[Minor Issue] UserInfoEditView & ResetMyPassword

### ISSUE THREAD

**Issue by ozanonurtek** [dpgaspar/Flask-AppBuilder#2086]
### Environment

Flask-Appbuilder version:

Flask-AppBuilder==4.3.4

### Describe the expected results

Migrating from 4.3.3 to 4.3.4, ResetMyPassword and UserInfoEditView is broken.

### Steps to reproduce

- Install  <= 4.3.3, initialize project. Upgrade to 4.3.4

**Comment by dpgaspar** [comment]
Hi thank you for reporting this issue, I was able to replicate, and a fix is ready on #2091

**Comment by dpgaspar** [comment]
Fixed and released on: https://pypi.org/project/Flask-AppBuilder/4.3.5/
