### ISSUE TITLE
"GET /static/appbuilder/css/bootstrap.min.css.map HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by zcattacz** [dpgaspar/Flask-AppBuilder#2103]
Flask-AppBuilder==4.3.5

I don't use packers, just wondering if this matters ?
Maybe fab can ship a dummy to mute it. It always show up in the logs.

**Comment by dpgaspar** [comment]
Thanks for opening the issue. I can see it, not much, since it won't happen to end users.

Created a PR nonetheless
