### ISSUE TITLE
missing .get(col_name)

### ISSUE THREAD

**Issue by gbrault** [dpgaspar/Flask-AppBuilder#2104]
https://github.com/dpgaspar/Flask-AppBuilder/blob/6130d078b608658eb66e15530502efd309653435/flask_appbuilder/views.py#L463

@dpgaspar as you can see, in the add, you have the  .get(col_name) in 

```python
        if self.add_form_query_rel_fields:
            filter_rel_fields = self.add_form_query_rel_fields.get(col_name)
```

But it's missing in the edit!

Adding it just fix the issue!

**Comment by dpgaspar** [comment]
@gbrault thank you

Made the fix, but, please make sure to not depend on this API, it's deprecated
