### ISSUE TITLE
Real time update

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#212]
Hi Daniel

If I need to refer to external real time update, say weather report on hourly basis, then I would need jQuery right?

**Comment by dpgaspar** [comment]
Hi,

Sorry for the delayed answer. You can do this is so many ways.... yes JQuery can help you invoke external REST API's, or AngularJS, you can also use python and update on the server side.

**Comment by scheung38** [comment]
Can it provide a real time update like this:

https://mern-crud.herokuapp.com/

at the moment flask-appbuilder only refreshes when clicking on reload, correct? Or you saying that with bit of React/Angular2 this real time update can also be achieved here?
