### ISSUE TITLE
Add_form ModelView tutorial for an "association object" or multiple models

### ISSUE THREAD

**Issue by juaneschutte** [dpgaspar/Flask-AppBuilder#213]
Hi Daniel,

Im trying to follow the issue here http://stackoverflow.com/questions/21968176/flask-flask-admin-one-to-many-cascade.  Although it uses flask-admin with the " column_auto_select_related = True", how can i reproduce a similar answer with FAB using the add_form feature?

The idea is to have a form where the candidat fills in the add_form that lists all languages from language model and a field to provide input of the levels of such languages... 
Firstname : ____
Lastname : _____
Level for Language 1: _____
Level for Language 2: _____
...

The complexity comes when the add_form requires a list of all languages to be displayed in the form with an input required for each. Similar problem can be said for listing the required questions of a survey with a required input for each. 

The Model:

``` python
class Candidat(Model):
    id = Column(Integer, primary_key=True)
    firstname = Column(String(128))
    lastname = Column(String(128))
    birthdate = Column(Date)

    def __repr__(self):
        return '<Nom %r>' % self.lastname


class Language(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(128))

    def __repr__(self):
        return '%s' % unicode(self.name)


class Languagelevel(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(128))

    def __repr__(self):
        return '%s' % self.name

class CandidatLanguage(Model):
    id = Column(Integer, primary_key=True)
    candidat_id = Column(Integer, ForeignKey('candidat.id'))
    language_id = Column(Integer, ForeignKey('language.id'))
    language_level_id = Column(Integer, ForeignKey('languagelevel.id'))

    language = relationship(Language, backref="Candidat")
    candidat = relationship(Candidat, backref="Langue")
    languagelevel = relationship(Languagelevel, backref="Candidat")


The ModelView:

class CandidatView(ModelView):
    datamodel = SQLAInterface(Candidat)
    relatedviews = [CandidatLanguage]
    add_form = ??
```

Any help is appreciated,
Thanks.

**Comment by juaneschutte** [comment]
Hi Daniel,

Just a reminder about the question above when you have some time.  Much appreciated!

**Comment by dpgaspar** [comment]
So sorry for the delay, i'll look into it ASAP.

**Comment by juaneschutte** [comment]
Thanks Daniel.  Look forward to the response!

**Comment by juaneschutte** [comment]
Hi, just a reminder about the above. Thanks.

**Comment by juaneschutte** [comment]
Hello, can anyone else point me in the right direction?
Thanks

**Comment by dpgaspar** [comment]
Sorry once more for the delay, and i think i don't have good news on this one.

If i understand correctly, your want related select fields. Is this correct?

Two or more select fields, when the user selects the first the following are filtered by it's choice?

**Comment by juaneschutte** [comment]
Hi Daniel.  Thanks for responding. 
Yes to the first question and possibly no to the second. I would be happy just to list the rows (as in questions in a survey) of a table with a response for each.

**Comment by dpgaspar** [comment]
Related select fields is already possible
