### ISSUE TITLE
CompactCRUDMixin partially responsive when using a multi-threaded server

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#214]
I have the intuition that the `CompactCRUDMixin` is somewhat stateful on the server side. When I run my app as multi-threaded (using Gunicorn), clicking edit on items in `CompactCRUDMixin` won't always open up the form. If I click enough time, it ends up working as (I think) I hit one of the thread that received and edit request before.

I don't mind writing a PR to fix it but would like a bit of guidance before I start digging in.

**Comment by dpgaspar** [comment]
Yes, i was expecting this... I must confess, i've done it the wrong way.

Take a look at: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/views.py#L567

I'm using class properties to keep state between requests, this is plain wrong. This should be done using Flask session (sign cookie). It would be great if you write a PR to solve this one.

**Comment by dpgaspar** [comment]
Thanks, once more for your PR on this.
