### ISSUE TITLE
Constrain file extension in "quickfiles" example.

### ISSUE THREAD

**Issue by JamesGalt** [dpgaspar/Flask-AppBuilder#221]
Hi Daniel,
I'm trying to constrain the file extension when uploading with the quick files example.
What's the best way to do it?
Thanks a lot.

**Comment by JamesGalt** [comment]
I've managed to do it with custom validator

**Comment by dpgaspar** [comment]
Great, but i'm going to add a new config key for this 'FILE_ALLOWED_EXTENSIONS' on the next release. I'll close this one when it's alvailable on PyPi

Once again, sorry for the delayed answer.

**Comment by JamesGalt** [comment]
Nice.
Thanks

**Comment by dpgaspar** [comment]
version 1.4.6 is out, take a look at the docs for using the new config key
