### ISSUE TITLE
Handling Non-Standard OAuth2 Implementations

### ISSUE THREAD

**Issue by yokonsan** [dpgaspar/Flask-AppBuilder#2236]
### Environment

Flask-Appbuilder version:  4.4.1

### Describe the expected results

If a third party's OAuth2 implementation does not comply with standards, such as using `app_id` instead of `client_id` for the redirection parameter, and the `access_token` field also deviates from the norm, is there a mature solution available?

**Comment by Yoyasp** [comment]
If your provider is a one that could be used by other people/organisations than i would suggest to create a pull request where you add a provider in the [flask_appbuilder/security/manager.py](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py) file under the `get_oauth_user_info()` method.

If you are using a custom provider that is used only by you the cleanest solution would be to[ extend the security manager](https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security) and use that when you initialise the app.

**Comment by yokonsan** [comment]
Thank you. I've rewritten the OAuth2 related methods of the Authlib library and recompiled it.
