### ISSUE TITLE
AuditMixin and manual database manipulation

### ISSUE THREAD

**Issue by ItWazzntMe** [dpgaspar/Flask-AppBuilder#225]
I'm trying to create default entries in the database in my views.py:
```python
db.session.add(DeviceType(name="Server"))
db.session.commit()
```
Which works fine without the AuditMixin, but when I try to do after adding the mixin, I get:
(_mysql_exceptions.OperationalError) (1048, "Column 'changed_by_fk' cannot be null")

**Comment by dpgaspar** [comment]
AuditMixin fills current time stamp, and current user on created_by_fk and changed_by_fk.

So, when adding a new record or updating you must have a context with a user signed in.

If this is impossible you must fill these fields, they are:

- created_by : User Model
- changed_by: User Model

Hope this helps.
