### ISSUE TITLE
Select all in views only select objects in the current page (mongoengine)

### ISSUE THREAD

**Issue by JamesGalt** [dpgaspar/Flask-AppBuilder#226]
Hi,
When I use the checkbox to select all items in a view it only selects the items showed in the current page.
is there a way to make it select all?
Thanks

**Comment by JamesGalt** [comment]
Hello,
Any idea?
Thanks

**Comment by dpgaspar** [comment]
This is not supported right now, one way to do it is to add a implement your own widget and add you own control button: http://flask-appbuilder.readthedocs.org/en/latest/templates.html#widgets

Then add you control on:

{% block begin_content scoped %}
    Area next to the controls
{% endblock %}

Make this bootstrap button call a method were you can do what ever you like to all records.

See if this is a good option for you, any further help your welcome to post it here.

Sorry for the delayed answer

**Comment by JamesGalt** [comment]
Hi,
I'm not a html/js guru so any help wold be great.
thanks
