### ISSUE TITLE
How to create nested menus?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#227]
Hi,
I'm enjoying appbuilder very much. Now i'm beginning a "real" app and my current question is how to create a nested menu. I see the add_category method with a parent_category argment on the Menu class but I can't quite figure out how to use it. Any help would be appreciated!
Thanks

**Comment by dpgaspar** [comment]
Hello, glad you liked it.

You can only have one neste level, this is a bootstrap "limitation".

Take a look at the docs: http://flask-appbuilder.readthedocs.org/en/latest/customizing.html#changing-menu-construction

If you have any doubts, your welcome to post them here.

**Comment by AustinJim** [comment]
Thanks!

**Comment by AustinJim** [comment]
When I change
appbuilder = AppBuilder(app, db.session)
to 
appbuilder = AppBuilder(app, db, menu=Menu(reverse=False))
I get the error: NameError: name 'Menu' is not defined.
I assume it's because I have not imported the Menu class. Can you tell me where it is and more generally, how to find the classes when I need to import them?
I found Flask-AppBuilder/flask_appbuilder/menu.py in Git but I can't seem to import Menu from appbuilder.
Thanks!

**Comment by dpgaspar** [comment]
Right, import it like this:

``` python
from flask.ext.appbuilder.menu import Menu
```

I'll change the docs to include the imports.

Hope this helps,
Thanks

**Comment by AustinJim** [comment]
Thanks!

**Comment by AustinJim** [comment]
Thanks Daniel,If you're revising the docs you might add explicit instructions on how to add a nested menu. I tried the example code in the docs and it doesn't create a nested menu. I will (probably) figure it out given a little time to study it but a copy and paste example would be a nice head start.
I know it's tough for you to find time to maintain appbuilder and live the rest of your life also so please accept my thanks for whatever you do. If I get proficient I expect to submit some samples you may be able to use in the docs alsl.
Thanks again, Jim

**Comment by dpgaspar** [comment]
Ok, thanks for the input, docs are far from perfect, any help would be highly appreciated.

Hope you managed to create your menus the way you want it. Any further question just post an issue.
