### ISSUE TITLE
apply base filter to search filter options?

### ISSUE THREAD

**Issue by Fuzzwah** [dpgaspar/Flask-AppBuilder#228]
I've had a good dig around but I can't seem to wrap my head around how I would apply a base filter to the options of a search filter.

I have a ModelView which has:

```base_filters = [['player_id', FilterEqualFunction, get_user_id],]```

This works fine, only displaying content which the particular user has created. However in the dropdown list for a search filter the user is able to see all content from all users. I'd like to limit the options in the drop down list to only show the content the user has made.

I'm guessing that ```search_filters``` is the thing I'm looking for, I just can't work out the format of the option.

**Comment by Fuzzwah** [comment]
Well I've hacked in something that works, but I'm sure that there has to be a better way.

I created my own SearchWidget that intercepts the ```form_fields['player_deck']``` and loops through the options using regex and removes any that aren't linked to the user.

**Comment by dpgaspar** [comment]
hello, sorry for the delay. 

Actually there is no way of doing this. In current version you only have this option for add and edit forms using add_form_query_rel_fields, and edit_form_query_rel_fields i will add  search_form_query_rel_fields on the next release.

When it's out i'll post it here and close this issue.

Thanks for submiting this issue.

**Comment by dpgaspar** [comment]
Ok, 1.4.7 is out, please try the new property search_form_query_rel_fields. Thanks
