### ISSUE TITLE
readonly fields

### ISSUE THREAD

**Issue by tarsnake** [dpgaspar/Flask-AppBuilder#23]
Is there any way to render a field as readonly without writing a custom form?  If not, pointers on creating a custom edit form would be helpful.

**Comment by TYLERWAKEFIELD** [comment]
f

**Comment by TYLERWAKEFIELD** [comment]
class ExampleView(ModelView):
    datamodel = SQLAModel(ExampleModel)
    edit_form_extra_fields = {'field2': TextField('field2',
                                    widget=BS3TextFieldROWidget())}

whats 'TextField'?

**Comment by slavo83** [comment]
Hi,
I have quick question:
Is there any way to make such readonly field work on relation?
Let's say we have:

class A(Model):
    id = Column(Integer, primary_key=True)
    fieldA
    ClassB_rel = relationship("B", back_populates = "ClassA_rel")


class B(Model):
    id = Column(Integer, primary_key=True)
    fieldB
    ClassA_rel = relationship("A", back_populates = "ClassB_rel")

And In view (using class B model) I would like to have read only field as follows:

edit_form_extra_fields = {
       'somefield': TextField("ClassA_rel.fieldA", widget=BS3TextFieldReadOnlyWidget())
    }    

Thank you.,
S.
