### ISSUE TITLE
Merging another Flask app into simpleview2 tabs.

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#230]
How to embed say another Flask app like this Miguel Grinberg's Flask-SocketIO-Chat: 

https://github.com/miguelgrinberg/Flask-SocketIO-Chat

into one of the simpleview2's view.py so that instead of calling method3.html, it will launch the above Flask-SocketIO-Chat?

**Comment by dpgaspar** [comment]
on __init__.py initialize it:

``` python
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)
```

**Comment by scheung38** [comment]
Don't I need to use Blueprint? As merging will mean two apps that originally had two 
'''
app = Flask(__name__)
'''

**Comment by dpgaspar** [comment]
Did you manage to do it?

**Comment by scheung38** [comment]
No, slightly confused about the way sockets are generated and called, and merging with another app that does it it normal way, but i guess it is blueprint related
