### ISSUE TITLE
Best way to update existing model and add new one

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#231]
Hi All,
I am writing an app using appbuilder that imports spreadsheets and I want to be able to update existing records and insert new ones as simply as possible.I've created an Event(Model) class for this. For example, the Event record has an EventID that is an identity primaryKey (generated by the db upon insert) and an EventKey which I allow the user to define. The EventKey must be unique and is the identifier as far as the user is concerned. Upon import I search for an existing record with the matching EventKey. If it's found I want to update the model, else I want to insert it.
Is it as simple as instantiating an Event instance with an EventID to update and instantiating one without an EventID to insert one? Will the code behind the Model class handle that? Any help or links to how to do this would be very much appreciated.

Thanks!

**Comment by dpgaspar** [comment]
The code behind Model class is almost plain SQLAlchemy Model. 

When you import the spreasheet all the rows go where? to a model related to Event?

**Comment by AustinJim** [comment]
Hi Daniel,
Thanks for the quick reply. It may be a couple of days before I can completely reply to your question. Can you send me a link showing how to correctly create and save or update an object based on the Model (or maybe a better) class?
Thanks again for all that you are doing with appbuilder.
Jim

**Comment by dpgaspar** [comment]
Take a look at the test data insert on the examples: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickhowto/testdata.py

And see if you can work from there.

**Comment by dpgaspar** [comment]
I'll close this one, if you have further questions, just open a new one or reopen this.
