### ISSUE TITLE
working with filtered data?

### ISSUE THREAD

**Issue by Fuzzwah** [dpgaspar/Flask-AppBuilder#232]
I'd like to add some stats to the top of a ModelView list, for example a count of the number of list items which have a field that contains a certain value.

I initially thought I might be able to get the logic done in the ModelView and pass the info through to the template using ```extra_args```, but I can't work out how I can query the db from in the ModelView class. I just get ```RuntimeError: working outside of application context```

Since I also want these stats to work with search filters I looked at hijacking the search widget to collect up the list of filters and make db queries, but this just felt like I was reinventing the wheel.

I'd stooped as low as creating a new ModelView with a ```page_size = 10000000000``` in order to get all the rows and then doing logic in the jinja template, but I'm well aware that this is a massive no no.

Any tips on how I can do logic on the data between the ModelVIew and the template?

**Comment by Fuzzwah** [comment]
I've worked out a method; I've created a jinja globals function in my __init__.py which I pass the ```value_columns``` object to. I then do all the logic in this python function and hand a json dictionary back.

I still feel like I'm being a newb and failing to understand some part of the process, but its working.

**Comment by JamesGalt** [comment]
Hello,
i'm currently trying to do the same thing, could you post your solution please?
thanks

**Comment by Fuzzwah** [comment]
In the ```__init__.py``` file, after the db var is created, you can set up functions which access the database and can be called from your jinja templates. Here's a mocked up example:

```
app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)

def jinja_get_things(value_columns):
	""" you can do any logic you want here
	"""
    things = {}
    
	for item in value_columns:
		# item is a dict with col names as keys and the value as.... values....
		print(item)
		
		# you can even make queries to the database
		things[item['col'] = db.session.query(Model).filter(Model.bar == item['col']).first().foo
		
	return things

app.jinja_env.globals.update(get_things=jinja_get_things) 

# finall we set up the appbuilder
appbuilder = AppBuilder(app, db.session)
```

Then in the template:

```
{% things = get_things(value_columns) %}
```

**Comment by JamesGalt** [comment]
Thanks it helped me.

**Comment by dpgaspar** [comment]
That's a pretty simple way of solving it. I'm sorry all for the delayed answers here, i expect to be back on track soon. Thanks for sharing this @Fuzzwah
