### ISSUE TITLE
How do I extend the rest functions

### ISSUE THREAD

**Issue by thornpw** [dpgaspar/Flask-AppBuilder#233]
If I add an object that is shown using a ModelView, I like to create another object (a tag) based on the first letter of the object. How could I extend the rest add function?

**Comment by dpgaspar** [comment]
The add rest method is here: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/views.py#L233

So you can just override it, or extend it on ModelView and call super. As you can notice the method is on RestCRUDView and ModelView extends it.

Once more sorry for the delayed answer, i hope this will be just a phase, lots of work right now....

**Comment by thornpw** [comment]
Thanks for your support.

**Comment by dpgaspar** [comment]
No problem.
