### ISSUE TITLE
Field condition in forms

### ISSUE THREAD

**Issue by JamesGalt** [dpgaspar/Flask-AppBuilder#234]
Hi Daniel,
Do you know a method to have different fields in a form when conditions differs i.e.:
foo is count of values in db so it's dynamic
``` python
class MyForm(DynamicForm):
    if foo>0:
        my_field1 = StringField('My Field 1', widget=BS3TextAreaFieldWidget())
    else:
        my_field2 = IntField('My Field 2')

```

Thanks a lot, as always.
James

**Comment by dpgaspar** [comment]
Take a look at this, see if it help:

http://stackoverflow.com/questions/11622592/wtforms-create-variable-number-of-fields

**Comment by JamesGalt** [comment]
Hi,
The problem is that the views are initiated once at startup, so do I need to re-init the view, or something?
Thank a lot

**Comment by JamesGalt** [comment]
I managed to do it by creating a fun outside the view an setting the form for the view there

**Comment by JamesGalt** [comment]
Hi, 
I solved it by making a fun outside the view, make the changes here and set the form for the view

**Comment by dpgaspar** [comment]
great!

**Comment by giordyb** [comment]
Hi,

I have the same exact problem, I am able to create the form fields dynamically *before* the view is instantiated but not after.

Is there a way to reset the form view? I cannot figure out how @JamesGalt did it...
