### ISSUE TITLE
Can a model validate itself?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#238]
I see that there are validation checks for views. Can a model indicate if it is valid? For example, I have the Event class below. Is there a method to check all of the required fields and return false if any are None? Also, I'm using PyCharm community edition and it can't drill into the class my classes inherit from (like Model in this case) so I'm having trouble researching this for myself. If there a source of the complete inheritance tree for the appbuilder classes? That may help me answer some of my own questions.
btw, I'm building an AngularJS front end and have just started using the json api. Create addition to the framework!

Thanks!

``` python
class Event(Model):
    EventID = Column(Integer, primary_key=True)
    EventKey = Column(String(30), unique=True, nullable=False)
    Name = Column(String(100), nullable=False)
    Description = Column(Text(1000), nullable=False)
    BeginDate = Column(Date)
    EndDate = Column(Date)
    RegBeginDate = Column(Date)
    RegEndDate = Column(Date)
    Location = Column(String(200))
    Address1 = Column(String(200))
    Address2 = Column(String(200))
    City = Column(String(20))
    State = Column(String(2))
    Zip = Column(String(10))
    URL = Column(String(100))
    Email = Column(String(100))
    Phone = Column(String(20))
```

**Comment by dpgaspar** [comment]
Hello, sorry for the delay....

The best method to validate your data is using Validators from WTForms.

Your work on FE using AngularJS really interests me. If you have any questions or want to work together on this, you welcome to email me, or post your questions here.

Remember Model is pretty much a flask-sqlalchemy model.

**Comment by AustinJim** [comment]
Hi Daniel,
I have to get the backend working before I can continue on the AngularJS front end so I'm currently working on an import using pyexcel and I want to validate the entire file before attempting the import. I have an Event class that extends Model to which I've added an isValid() method. I've included the class below. The import code that validates each record is listed below the Event class. Can I use WTForms to validate records not entered via a form? If so, how. If not, do you have any recommendations on how to do this better than the code below?
Thanks!

class Event(Model):
    EventID = Column(Integer, primary_key=True)
    EventKey = Column(String(30), unique=True, nullable=False)
    Name = Column(String(100), nullable=False)
    Description = Column(Text(1000), nullable=False)
    BeginDate = Column(Date)
    EndDate = Column(Date)
    RegBeginDate = Column(Date)
    RegEndDate = Column(Date)
    Location = Column(String(200))
    Address1 = Column(String(200))
    Address2 = Column(String(200))
    City = Column(String(20))
    State = Column(String(2))
    Zip = Column(String(10))
    URL = Column(String(100))
    Email = Column(String(100))
    Phone = Column(String(20))
    
    ordered_column_names=['EventKey','Name','Description','BeginDate','EndDate','RegBeginDate','RegEndDate','Location','Address1','Address2','City','State','Zip','URL','Email','Phone']

    def setValues(self, **kwargs):
        for key, value in kwargs.iteritems():
            setattr(self, key, value)

    def __init__(self, record):
        print 'record: ', record
        #TODO Skip any columns in the record that are not on this class.
        # Could use a simple list of valid columns names similar to ordered_column_names. Check docs for better way.
        for key, value in record.iteritems():
            setattr(self, key, value)

    def list_mapped_columns(self):
        list_obj_mapped_columns(self)
    
    def isValid(self):
        validationMessage = ""
        columns = get_obj_mapped_columns(self)
        for column in columns:
            if not column.nullable:
                print column.name
                if not getattr(self, column.name):
                    # Add validation message
                    validationMessage = validationMessage + ", " + column.name + " can not be empty."
        return validationMessage

    def __repr__(self):
        return self.EventKey
=========== validation code in the import class =============
            records = pe.get_records(file_name=fullName)
            for row in records:
                event = Event(row)
                if (event.isValid()):
                    print 'valid'
                else:
                    print 'invalid:', event.getValidationMessages()

**Comment by dpgaspar** [comment]
No you can't use WTForms in your use case.

Your checking if the record has columns that violate the nullable=false, isn't you database already doing this? You should leave your db deal with it and just catch the exceptions.
