### ISSUE TITLE
Error while using AuditMixin

### ISSUE THREAD

**Issue by freemanpolys** [dpgaspar/Flask-AppBuilder#244]
I have this error with AuditMixin
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Niveau|niveau, expression 'Niveau.changed_by_fk == User.id' failed to locate a name ("name 'User' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.Niveau'> class after both dependent classes have been defined.

The model is : 

class Niveau(Model,AuditMixin):
    __tablename__ = 'niveau'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique = True, nullable=False)
    def __repr__(self):
        return self.name

Regards,

**Comment by eschulma** [comment]
@freemanpolys how did you fix this? I have the same problem.
