### ISSUE TITLE
Change sentence

### ISSUE THREAD

**Issue by porthos** [dpgaspar/Flask-AppBuilder#246]
I need to change the phrase "can post on this form Reset Password View"
How do I do?
![image](https://cloud.githubusercontent.com/assets/2421687/10543147/2d35668e-73f3-11e5-9a14-aceb4e78dbd6.png)

**Comment by dpgaspar** [comment]
This is a bit harcoded, this string is created on: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/sqla/models.py#L44

I would not mess with it... the string came out a bit stupid i know...
