### ISSUE TITLE
Listing records created by logged user

### ISSUE THREAD

**Issue by gnud** [dpgaspar/Flask-AppBuilder#250]
I got so far this code:
```
class ProjectGroup(AuditMixinUser, Model):
    """
    """

    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    user_id = Column(Integer, ForeignKey('ab_user.id'), nullable=False)

    def __init__(self):
        from flask import g
        self.user_id = g.user.id

    def __repr__(self):
        return self.name
```

How to make each record be visible for the logged user ?

**Comment by dpgaspar** [comment]
Hello,

You can/should use this: http://flask-appbuilder.readthedocs.org/en/latest/advanced.html#base-filtering

So you can create a ModelView unfiltered and associate it with an admin role and another ModelView based on the same model but filtered and associate it with a normal user Role.

Hope this helps. If it does, could you please close the issue?

**Comment by gnud** [comment]
Yes, that's the solution, thanks :).
