### ISSUE TITLE
flash display uses invalid Bootstrap style

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#252]
Hi,
The display of the message(s) set by the flash() function are displayed with class="alert alert-message". alert-message is not a valid style in Bootstrap 3. I could add my own CSS file and set this style but it's going to be a problem for other folks as well so I would like to fix it in the base template. But, I don't know where that template is. Where is that template?
Thanks!

**Comment by dpgaspar** [comment]
It's here : https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/flash.html

**Comment by AustinJim** [comment]
Man, I love the implementation! My mistake for not understanding that I can pass a category.
Thanks again!

**Comment by dpgaspar** [comment]
Thanks!
