### ISSUE TITLE
Custom register view

### ISSUE THREAD

**Issue by gnud** [dpgaspar/Flask-AppBuilder#254]
I'd like add a view that can do self registration, based on some parameters, like email.

```
    class RegisterUserByEmailView(BaseRegisterUser):
        """"""
    
        form = RegisterUserDBForm
    
        redirect_url = '/'
        route_base = '/register/byemail/'
    
        def form_get(self, form):
            pass
    
        def form_post(self, form):
            param_email = request.form['email']
            self.add_registration(username=param_email, first_name=''', last_name='', email=param_email, password='')
    
    appbuilder.add_view(RegisterUserByEmailView, "RegisterUserByEmailView", icon="fa-twitter", label='Register User By Email View')
```

The problem is the override method form_post it's seems not being invoked.

Then I tried adding new method to the view:
```
    @expose('/activation/<string:activation_hash>')
    def activation(self, activation_hash):
        pass
```

it being called, but then I don't have self.add_registration in self :(.

**Comment by gnud** [comment]
without
```
    appbuilder.add_view(RegisterUserByEmailView, "RegisterUserByEmailView", icon="fa-twitter",     label='Register User By Email View'
```
And using http://flask-appbuilder.readthedocs.org/en/latest/api.html?highlight=baseregisteruser#flask.ext.appbuilder.security.registerviews.BaseRegisterUser

'''
    class MySecurityManager(SecurityManager):
        registeruseroauthview = RegisterUserByEmailView

    appbuilder = AppBuilder(app, db.session, security_manager_class=MySecurityManager)
'''
I managed to get it working.

**Comment by dpgaspar** [comment]
Great! that's it
