### ISSUE TITLE
Error when trying to delete and recreate db

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#255]
I'm trying to start over with data. I've deleted app.db. When I run fabmanager create-admin the following error occurs. I've tried removing all menu items but to no avail. Can you tell me where to look for this problem?

Recognized Database Authentications.
2015-10-22 12:35:05,835:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. (sqlite3.IntegrityError) ab_user.extra may not be NULL [SQL: u'INSERT INTO ab_user (first_name,
last_name, username, password, active, email, last_login, login_count, fail_login_count, created_on, changed_on, created_by_fk, changed_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [paramet
ers: (u'admin', u'user', u'admin', 'pbkdf2:sha1:1000$QjC4oFXt$21c926b16b0332d59f9fad848e352a91416ca3fb', 1, u'admin@fab.org', None, None, None, '2015-10-22 12:35:05.831000', '2015-10-22 12:35:05.83100
0', None, None)]
No user created an error occured

**Comment by absinthetized** [comment]
mmm... have you tried to create a new empty project. rm the db and issue a fabmanager create-admin?
here I can rm my entire db and issue the command without problems. also searching for ab_user.extra neither gives results in sqlite3 nor in FAB sources, where does it came from?!
FAB version? python version?

**Comment by AustinJim** [comment]
I started with a new project and added back my code a little at a time until I found the problem. The offending statement was db.drop_all() which was just before the db.create_all(). I thought I needed to do that to get a change in my model class structure to be recognized. I did not and removing the db_drop_all() solved my problem.
Thanks for the help!
