### ISSUE TITLE
pylint and FAB

### ISSUE THREAD

**Issue by absinthetized** [dpgaspar/Flask-AppBuilder#256]
it seems that pylint doesn't like FAB so much. Every time I call a method from a fab derived class (even a simple new idex view) lyplint replies with errors like:

``` bash
E: 34, 8: Instance of 'xxxView' has no 'update_redirect' member (no-member)
```

sofware versions:

```
Flask-AppBuilder==1.4.7
pylint-flask==0.1
pylint==1.4.4
```

I've tried something like 

```
pylint --extension-pkg-whitelist=flask_appbuilder
```

as suggested here: https://bitbucket.org/logilab/pylint/issues/58, but it doesn't work.
Any suggestion?

**Comment by dpgaspar** [comment]
I've tested it with quickhowto2 example and only get errors from SQLAlchemy class (flask-sqlalchemy).

```
pylint -E app
No config file found, using default configuration
************* Module app
E: 18,29: Instance of 'SQLA' has no 'session' member (no-member)
************* Module app.views
E: 20, 8: Instance of 'SQLA' has no 'session' member (no-member)
E: 21, 8: Instance of 'SQLA' has no 'session' member (no-member)
E: 22, 8: Instance of 'SQLA' has no 'session' member (no-member)
E: 24, 8: Instance of 'SQLA' has no 'session' member (no-member)
E: 27, 0: class already defined line 3 (function-redefined)
```

**Comment by absinthetized** [comment]
mmm... therefore this requires more in-depth analysis on my side. I'll restart with a smaller example (now my app is small sized but not trivial) and go bottom-up!

I'll re-post here my results!

**Comment by dpgaspar** [comment]
Thanks!

**Comment by absinthetized** [comment]
ok, let's go...

1. created a new vitual env
2. pip installed fab 1.4.7 along with patch #263 
3. added pylint with pylint-flask, This is the freeze:
```
Babel==2.1.1
Flask==0.10.1
Flask-AppBuilder==1.4.7
Flask-BabelPkg==0.9.6
Flask-Login==0.2.11
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.0
Flask-WTF==0.12
Jinja2==2.8
MarkupSafe==0.23
SQLAlchemy==1.0.9
WTForms==2.0.2
Werkzeug==0.10.4
argparse==1.2.1
astroid==1.3.8
click==5.1
colorama==0.3.3
itsdangerous==0.24
logilab-common==1.1.0
pylint==1.4.4
pylint-flask==0.1
pylint-plugin-utils==0.2.3
python-openid==2.2.5
pytz==2015.6
six==1.10.0
speaklater==1.3
wsgiref==0.1.2
```

1. cloned FAB source and checked out v.1.4.7
2. copied-pasted the example folder into the virtual env
3. run pylint against quickhowto2

```
$ pwd
/home/utente/virtualenvs/lint_fab_test/examples/quickhowto2
$ pylint --load-plugins=pylint_flask -E app/
No config file found, using default configuration
************* Module app.views
E: 27, 0: class already defined line 3 (function-redefined)
```
this is the only error I got. No SQLAlchemy warnings. I suppose the flask plugin suppresses them all but the last one (not SQLA related).

1. run a more aggrassive test from withing examples dir:
```
for dir in $(find . -maxdepth 1 -type d | grep "^./[a-z]"); do cd $dir && echo "entering $dir" && pylint --load-plugins=pylint_flask -E app/ ; cd ..; done
```
output is here: https://gist.github.com/absinthetized/f462f88c07f297f512ae
