### ISSUE TITLE
unable to unittest basic login

### ISSUE THREAD

**Issue by absinthetized** [dpgaspar/Flask-AppBuilder#257]
I don't understand where I'm wrong, but passing a wrong password to login unit test doesn't return error. On the opposite, correct login is not followed by resource access.

Here the test snippet:

``` python
import unittest
from app import app

INVALID_LOGIN_STRING = 'Invalid login'

class stocktip_test(unittest.TestCase):
    def setUp(self):
        self.app = app
        self.c = app.test_client()

    def tearDown(self):
        pass

    #helpers from FAB tests
    def login(self, c, username, password):
        return c.post('/login/', data=dict(
            username=username,
            password=password
            ), follow_redirects=True)

    def logout(self, c):
        return c.get('/logout/')

    def test_basic_access_list(self):
        with self.c as c:           
            rv = c.get('/')
            self.assertEqual(rv.status_code, 200, 'Unable to access index')

            rv = self.login(c, 'admin', '000')
            data = rv.data.decode('utf-8')
            self.assertTrue(INVALID_LOGIN_STRING in data)

            rv = c.get('/dbview/list/')
            self.assertEqual(rv.status_code, 200, 'Unable to access view')          

            self.logout(c)

if __name__ == '__main__':
    unittest.main()
```

The file is stored next to the run.py, and app il loaded correctly by the test file (I see no errors in the werkzeug report).
- Index access test is sucessful
- If I pass the _wrong_ '000' password I do not receive any error: self.assertTrue fails.
- If I pass the _right_ password the next resource test fails and werkzeug logs it:

``` bash
2015-10-23 12:57:03,288:WARNING:flask_appbuilder.security.decorators:Access is Denied for: can_list on: DBView
```

 Of course firing the run script and login from chrome works as expected and "passes" all tests.

**Comment by dpgaspar** [comment]
I've tested it, but no conclusion yet. It's strange...

**Comment by pogzyb** [comment]
Did anyone ever find a solution for this? I'm running into this issue for testing as well. I use FAB's browser_login() method then attempt to request a view's uri (something like "/customerview/list/") with a test client, but still get denied.

**Comment by absinthetized** [comment]
Nope on my side, sorry. At the time I had a sortage of time and I abandoned
the testing thing.
Today I've totally changed my job and there is no hope to go back to the
topic :(

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Mobile: 3351613944

Il mer 13 nov 2019, 19:46 pogzyb <notifications@github.com> ha scritto:

**Comment by pogzyb** [comment]
No problem! Thanks for the reply anyway.
For anyone with the same issue, instead of using the browser_login() method I decided to modify the session. For example:
```
...
client = app.test_client()
with client.session_transaction() as session:
    session['user_id'] = 1
    session['_fresh'] = True
# login_required views are accessible
rv = client.get(...)
...
```
