### ISSUE TITLE
How to use a select list for column input on edit/add form?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#259]
Hi,
I'm trying to replace the default text input for a field with a select list of values from another table. The other table is in a parent relationship with this one and I have defined the relationship in the model class. I have decided to relate all of the tables with integer primary and foreign keys but I never want the users to see them. So, I'm asking the user to enter a unique key for every record. For example, the Events table is parent in a one to many relationship with the CarClasses table. i.e. each Event can have 0 or more CarClasses related to it. I've required an EventKey to be entered by the user to uniquely identify the event. This might be something like "2015CarShow".
When the user adds or edits a CarClass record I want them to select the EventKey from a list of existing EventKeys in the Events table. So I want a select list on the add/erdit page for the CarClasses.EventKey field to be a list of EventKeys from the Events table.
I guess an alternative would be to present the EventId as the key in a select list with the EventKey associated with each EventId to be the displayed option for the EventId.
What's the best way to do this staying within the framework? I've looked into add_form_extra_fields on the  model but I'm not sure that's the best way to go.
Any guidance would be very much appreciated!
Jim

**Comment by dpgaspar** [comment]
Could you post your models here? or send them by email?

**Comment by AustinJim** [comment]
Hi Daniel,
Thanks for the offer. First I'm going to refactor my code and try to solve it myself.
Thanks!

**Comment by dpgaspar** [comment]
Ok.
