### ISSUE TITLE
Does FAB have Forget password action?

### ISSUE THREAD

**Issue by valVk** [dpgaspar/Flask-AppBuilder#260]
Hi, I've just started to learn how to use your meta framework, and found that there is no actions for reset password.

Or Maybe I missed it.

Thanks

**Comment by dpgaspar** [comment]
There is a view on the UI for the user to reset his/her password.

There is no forget password 'action' on the login view, if this is what you mean.

Maybe this could be a new feature?

**Comment by valVk** [comment]
Hi.

This is a common feature, if user forgot his password than there have to be possibility for reset password. 
Also there have to be implemented email feature which mail to the user with request to use token for resetting password.

I'll look into the case when user makes a sign up, whether he got email with token for activation his account or not.

Thanks

**Comment by dpgaspar** [comment]
I know this is a common feature, no time for everything.... I'll take a look to implement this one, or are you willing to submit a PR?

**Comment by valVk** [comment]
Unfortunately I'm a new comer to the Python World and to the Flask.
I've just search a kickstarter application which will allow me to build a complex web APP in a right way.
I've showed your application to the experienced Python Dev and he told me that this a good point to start. So I'll want to give a chance to the F.A.B. Maybe later when I'll be more familiar with Python/Flask I'll create a few PR ))

Thanks for your app.

**Comment by mw66** [comment]
Can't believe this is 2025, there is no "forget password" functionality.
