### ISSUE TITLE
How to set template folder explicity?

### ISSUE THREAD

**Issue by valVk** [dpgaspar/Flask-AppBuilder#262]
<my_project>
        <app>
            __init__.py
            models.py
            views.py
            <templates>
                <theme>
                    <appbuilder>
                        <security>
                            login_db.html
                    **mybase.html**
                <theme2>
                    <appbuilder>
                        <security>
                            login_db.html
                    **mybase.html**

**Comment by valVk** [comment]
And the answer is yes I can `app = Flask(__name__, template_folder='templates/theme')`

**Comment by dpgaspar** [comment]
good!
