### ISSUE TITLE
force dependency versioning

### ISSUE THREAD

**Issue by absinthetized** [dpgaspar/Flask-AppBuilder#263]
hi,

in order to test some other issue pointed out here in github, I've made a new from scratch virtualenv reinstalling FAB v.1.4.7.

the new install downloads flask-sqlalchemy v.2.1 rather than v.2.0 (the version I've succesfully used in my project). This causes the fabmanager to chrash when you try to create a db.
```
fabmanager create-db
Was unable to import app Error: make_declarative_base() takes exactly 1 argument (2 given)
```
forcing the reinstall of flask-sqlalchemy 2.0 (along with deps) fixes the issue. 
I have not seen the pip config but I'll suggest to use fixed versioning of deps to avoid issues.

cheers,
M

**Comment by dpgaspar** [comment]
Yes, your right, in fact i've just pinned it on master. Thanks!
