### ISSUE TITLE
Add widgets on the index.html

### ISSUE THREAD

**Issue by gnud** [dpgaspar/Flask-AppBuilder#264]
How do I add widgets on the first loaded page, for instance the index.html, need to resemble a dashboard?

Thanks.

**Comment by absinthetized** [comment]
you have to override the default index as explained here: http://flask-appbuilder.readthedocs.org/en/latest/customizing.html

**Comment by gnud** [comment]
That's not what I need :(.

I want to make a masterdetail that is, to contain several column views, just like a dashboard.
And that view to be added in the index page when logged user is used, so far I made to switch to different templates, when the user is logged, in the IndexView.
Now I'm trying to override the list_template property, but I don't know if that's the correct way.

**Comment by absinthetized** [comment]
ok, don't know if I've got this but... 
each view has it's own 'can_list' permission. use a custom index page with the required view and set the view method as follow: 
```python
@expose('/list/')
@has_access
def list(self):
#override the list method even just invoking the super's method
```
doesn't this work (or at least doesn't this make you closer to the solution :-P)?

**Comment by gnud** [comment]
I'm having trouble visualising your suggestion.
The goal is when I open the IndexView, to show a template something like https://d85wutc1n854v.cloudfront.net/live/products/600x375/WB09498FH.png (sorry for the random external image), meaning, the default_view to be some template, that shows a grid of widgets.

Do you understand what I'm after :) ?

**Comment by absinthetized** [comment]
ok,

1- about the grid of widgets: it's your business :-P As the most complex layout I'm aware of in FAB is a multiview layout which is basically a column of piled widgets. If you want something like a grid please, implement and contribute back!

2- about the logged/anonymous user: it should be enough to apply the previous decorators to the list (or any other method used to render the widget) to avoid radom users to see anything.

3- to make this view the default index view you have to override the index class as previously described.

I'm currently on a JS web app. If I'll find time I'll try to post a link to a working example. As start just try to render a basic table with a basic modelview and check for permissions to work properly! then try to make this your ovdrloaded index view.

cheers

**Comment by dpgaspar** [comment]
Thanks @absinthetized
