### ISSUE TITLE
Best way to communicate two Flask-AppBuilder apps

### ISSUE THREAD

**Issue by gnud** [dpgaspar/Flask-AppBuilder#267]
What if I got two separate apps, running on the same machine, and I want to open an url in a new tab on app2 ?

My solution is to have API routes that validate the session, app1 request to open some route on app2, with params the session, then app2 ask on a different route app1 to check the session, if ok app2 creates new login with that session.

Is my solution ok, or it's too complicated ?

**Comment by dpgaspar** [comment]
This is only server side, right? you would have to have some form of authentication between the services. Take a look of how it's done using web services auth using tokens.

An alternative would possibly be:
If you use the same secret for both apps, and the same users are shared, passing the client cookie would work...
