### ISSUE TITLE
How to set up 3 table relationships?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#268]
Hi,
I need a little help setting up the relationships between 3 tables. This application is to register people with cars in car shows. The tables are:
Event (car show)
CarClass (classes of cars like Triumph TR6 or Triumph Spitfire)
Registration (People registered for an event)
Each registration should have one CarClass and one Event selected.
This is what's confusing me. Each Event has a finite set of CarClass records that are not shared between other events.
I looked at the benefits example in the employee example but that seems to allow all employees to have any benefits. I need to limit the CarClasses to a specific event.
I tried adding the following relationships:
CarClass -> Event
Registration -> CarClass and Registration -> Event but I can't seem to get that to work. Is this the right way to go and I'm just not quite implementing it correctly or is there a different way I should go?
I'd appreciate any hints on how to proceed.
Thanks!

**Comment by AustinJim** [comment]
I've thought about it and I'm thinking that I can just relate Registration to CarClass and CarClass to Event. Two simple one to many relationships. But, I can't seem to get that to work. Here are abbreviated versions of my classes with relationships. When I delete the app.db and run fabmanager create-admin I get the following error:
"Was unable to import app Error: Could not determine join condition between parent/child tables on relationship Registration.carClass - there are no foreign keys linking these tables.  Ensure that refe
rencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression." 
Can anyone see what the problem is?
Thanks!

class Event(Model):
    EventID = Column(Integer, primary_key=True)
    EventKey = Column(String(30), unique=True, nullable=False)

class CarClass(Model):
    CarClassID = Column(Integer, primary_key=True)
    CarClassKey = Column(String(30), unique=True, nullable=False)
    EventID = Column(Integer, ForeignKey('event.EventID'), nullable=False)
    Event = relationship('Event')
   
class Registration(Model):
    RegistrationID = Column(Integer, primary_key = True)
    Organization = Column(String(30))
    CarClassID = Column(Integer, ForeignKey('carClass.CarClassID'), nullable=False)
    CarClass = relationship("CarClass")

**Comment by dpgaspar** [comment]
Sorry, we're you able to solve it?

**Comment by AustinJim** [comment]
Hi Daniel,I ended up leaving Events out of the relationships but used it to drive a select dropdown on the CarClass object. I did relate Registration to CarClass and that seemed to work fine. 
Thanks! Jim
