### ISSUE TITLE
Unable to run fabmanager

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#269]
Hi,
I'm trying to run fabmanager on a new computer but can't. Here is the log from installing flask-appbuilder and trying to run fabmanager. I uninstalled flask-appbuilder before running this. Can you give me any guidance on fixing this?
Thanks!

C:\Python27>pip install flask-appbuilder
Downloading/unpacking flask-appbuilder
  Running setup.py (path:c:\users\jicen_~1\appdata\local\temp\pip_build_jicen_000\flask-appbuilder\setup.py) egg_info for package flask-appbuilder

    warning: no files found matching '*' under directory 'bin'
    no previously-included directories found matching '*.pyc'
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask-BabelPkg>=0.9.4 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.2.11 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask-OpenID>=1.1.0 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask-SQLAlchemy>=0.16 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF>=0.9.1 in c:\python27\lib\site-packages (from flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in c:\python27\lib\site-packages (from Flask>=0.10->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from Flask>=0.10->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from Flask>=0.10->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in c:\python27\lib\site-packages (from Flask-BabelPkg>=0.9.4->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in c:\python27\lib\site-packages (from Flask-BabelPkg>=0.9.4->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): python-openid>=2.0 in c:\python27\lib\site-packages (from Flask-OpenID>=1.1.0->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy in c:\python27\lib\site-packages (from Flask-SQLAlchemy>=0.16->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\python27\lib\site-packages (from Jinja2>=2.4->Flask>=0.10->flask-appbuilder)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in c:\python27\lib\site-packages (from Babel>=1.0->Flask-BabelPkg>=0.9.4->flask-appbuilder)
Installing collected packages: flask-appbuilder
  Running setup.py install for flask-appbuilder

    warning: no files found matching '*' under directory 'bin'
    no previously-included directories found matching '*.pyc'
    Installing fabmanager-script.py script to C:\Python27\Scripts
    Installing fabmanager.exe script to C:\Python27\Scripts
    Installing fabmanager.exe.manifest script to C:\Python27\Scripts
Successfully installed flask-appbuilder
Cleaning up...

C:\Python27>fabmanager
Traceback (most recent call last):
  File "C:\Python27\Scripts\fabmanager-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Flask-WTF>=0.9.1

C:\Python27>pip show flask-wtf
---
Name: Flask-WTF
Version: 0.11
Location: c:\python27\lib\site-packages
Requires: Werkzeug, WTForms, Flask

**Comment by dpgaspar** [comment]
I had no problem using it. 

I ran pip from:

C:\python27\Scripts>pip install flask-appbuilder

Then:

C:\Python27\Scripts>pip list
Babel (2.1.1)
click (5.1)
colorama (0.3.3)
Flask (0.10.1)
Flask-AppBuilder (1.4.7)
Flask-BabelPkg (0.9.6)
Flask-Login (0.2.11)
Flask-OpenID (1.2.5)
Flask-SQLAlchemy (2.1)
Flask-WTF (0.12)
itsdangerous (0.24)
Jinja2 (2.8)
kerberos-sspi (0.2)
MarkupSafe (0.23)
mechanize (0.2.5)
pip (1.5.6)
python-openid (2.2.5)
pytz (2015.7)
pywin32 (218)
requests (2.7.0)
requests-kerberos (0.7.0)
setuptools (7.0)
speaklater (1.3)
SQLAlchemy (1.0.9)
Werkzeug (0.10.4)
WTForms (2.0.2)

C:\Python27\Scripts>dir
 Volume in drive C is OS
 Volume Serial Number is 3E35-EF64

 Directory of C:\Python27\Scripts

02-11-2015  16:05    <DIR>          .
02-11-2015  16:05    <DIR>          ..
30-04-2015  11:05            91.496 easy_install-2.7.exe
30-04-2015  11:05            91.496 easy_install.exe
02-11-2015  16:05               351 fabmanager-script.py
02-11-2015  16:05            65.536 fabmanager.exe
02-11-2015  16:05               645 fabmanager.exe.manifest
30-04-2015  11:05            91.468 pip.exe
30-04-2015  11:05            91.468 pip2.7.exe
30-04-2015  11:05            91.468 pip2.exe
02-11-2015  16:05            91.488 pybabel.exe
20-07-2012  14:48            25.369 pywin32_postinstall.py
02-11-2015  16:03            17.877 pywin32_postinstall.pyc
02-11-2015  16:03            17.877 pywin32_postinstall.pyo
19-03-2011  10:51             3.477 pywin32_testall.py
02-11-2015  16:03             2.791 pywin32_testall.pyc
02-11-2015  16:03             2.791 pywin32_testall.pyo
              15 File(s)        685.598 bytes
               2 Dir(s)  208.455.086.080 bytes free

**Comment by AustinJim** [comment]
Uninstalled everything including python and reinstalled and that fixed it.
