### ISSUE TITLE
TypeError: xxx is not JSON serializable when calling api/read

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#270]
Hi,
I have the following class. When I call it's view's api/read function I get the error "TypeError: TXABCD2015 is not JSON serializable". Note that TXABCD2015 is the value returned by the __repr__() method of the related Event object. I really would like the Event __repr__() value to be included in the json if possible. What should I do to handle this?

Thanks!

``` python
class CarClass(Model,ModelEnhancer):
    __tablename__ = "CarClass"
    CarClassID = Column(Integer, primary_key=True)
    CarClassKey = Column(String(30), unique=True, nullable=False)
    Marque = Column(String(30), nullable=False)
    Title = Column(String(30), nullable=False)
    Description = Column(Text(1000), nullable=False)
    StartYear = Column(Integer, nullable = True)
    EndYear = Column(Integer, nullable = True)
    EventID = Column(Integer, ForeignKey('event.EventID'), nullable=False)
    Event = relationship('Event')

    def setValues(self, row):
        self.validationMessages = ""
        for key, value in row.iteritems():
            setattr(self, key, value)

    def list_mapped_columns(self):
        list_obj_mapped_columns(self)

    def isValid(self):
        validationMessage = ""
        columns = self.required_column_names
        for name in columns:
            print name
            if not getattr(self, name):
                # Add validation message
                self.validationMessages = self.validationMessages + ", " + name + " can not be empty."
        return len(self.validationMessages) == 0

    def __repr__(self):
        return self.CarClassKey
`'`

**Comment by AustinJim** [comment]
More information:
The error is being thrown on like 442 of encoder.py:
            o = _default(o)
I believe it's looking for a _default() method on the Event object that is a foreign relation to the object being jsonified. See the line  "Event = relationship('Event')" above.
Does this mean I need to extend JSONEncoder() and write a default(self, o) method for all of my Views that I want to jsonify if they have relationships?
I want to make sure I'm not working against the framework so I could use some advice.
Thanks!

**Comment by dpgaspar** [comment]
Sorry for the delay, could you post you Event Model (with the def repr).

**Comment by AustinJim** [comment]
Hi Daniel. Thanks for the help.
class Event(Model, ModelEnhancer):
    EventID = Column(Integer, primary_key=True)
    EventKey = Column(String(30), unique=True, nullable=False)
    Name = Column(String(100), nullable=False)
    Description = Column(Text(1000), nullable=False)
    BeginDate = Column(Date)
    EndDate = Column(Date)
    RegBeginDate = Column(Date)
    RegEndDate = Column(Date)
    Location = Column(String(200))
    Address1 = Column(String(200))
    Address2 = Column(String(200))
    City = Column(String(20))
    State = Column(String(2))
    Zip = Column(String(10))
    URL = Column(String(100))
    Email = Column(String(100))
    Phone = Column(String(20))

    ordered_column_names=['EventKey','Name','Description','BeginDate','EndDate','RegBeginDate','RegEndDate','Location','Address1','Address2','City','State','Zip','URL','Email','Phone']
    import_column_names=['EventKey','Name','Description','BeginDate','EndDate','RegBeginDate','RegEndDate','Location','Address1','Address2','City','State','Zip','URL','Email','Phone']
    required_column_names=['EventKey','Name','Description']

    def setValues(self, row):
        self.validationMessages = ""
        for key, value in row.iteritems():
            # If column from the row matches an importable field on this class, set the value on the class.
            # Otherwise disregard the column. This allows the imported spreadsheet to have additional columns not needed here.
            if key in self.import_column_names:
                setattr(self, key, value)

    def list_mapped_columns(self):
        list_obj_mapped_columns(self)

    def isValid(self):
        validationMessage = ""
        columns = self.required_column_names
        for name in columns:
            print name
            if not getattr(self, name):
                # Add validation message
                self.validationMessages = self.validationMessages + ", " + name + " can not be empty."
        return len(self.validationMessages) == 0

    def __repr__(self):
        return self.EventKey

**Comment by AustinJim** [comment]
I think I've found the problem. The last name/value pair is the __repr__ of the related class. Note that it's value is not quoted but is a string. I'm going to start digging through the code to see where this comes from but I'm posting it now in case someone knows where the code is.

{'Description': u'All early MG sports cars ', 'StartYear': 1936, 'Title': u'MG-T Series ', 'CarClassKey': u'A1', 'Marque': u'MG', 'EndYear': 1955, 'Event': TXABCD2015}

**Comment by AustinJim** [comment]
I solved the problem by creating the following method on the Event class:
    def __html__(self):
        return self.EventKey

I was worried that this might interfere with getting json for the event object itself but the json looks correct. It returns the value from the __html__() method when it's a foreign key and the complete json when it's not.
