### ISSUE TITLE
AngularJS authentication method/sample?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#271]
I'm beginning to work on the AngularJS portion of my app. I have found examples of authentication using AngularJS with Flask. Is there any difference between the standard Flask techniques and capabilities of flask-appbuilder? Any sample code or links to the best tutorials would be appreciated.

Thanks!

**Comment by MichaelPereira** [comment]
You can look at this code for an example: https://github.com/dpgaspar/Flask-AppBuilder/issues/191#issuecomment-241796148
