### ISSUE TITLE
tried a wiki page for an issue I've met few days ago

### ISSUE THREAD

**Issue by absinthetized** [dpgaspar/Flask-AppBuilder#272]
It didn't fit into an issue, so I've tried a wiki page (really minimal). consider to kill it if you dislike the idea!

https://github.com/dpgaspar/Flask-AppBuilder/wiki/make-FAB-forms%27-fields-read-only

**Comment by dpgaspar** [comment]
Great iniciative! but, just one question could this be done using the proposed readonly field on the docs?

http://flask-appbuilder.readthedocs.org/en/latest/advanced.html#forms

**Comment by absinthetized** [comment]
DOH! I've completely missed it! OK let kill the wiki :P and remove a dep from my project!

**Comment by dpgaspar** [comment]
Nice solution thought... but better to remove the dep... Your very welcome to share other solutions.
