### ISSUE TITLE
Please add an index to examples/

### ISSUE THREAD

**Issue by stephlocke** [dpgaspar/Flask-AppBuilder#274]
There are a lot of examples and it'd be helpful if there was a README which outlined what each is meant to be an example of since the names aren't always informative

e.g. quickcharts and quickcharts2, quickhowto and quickhowto2 and quickhowto3

**Comment by dpgaspar** [comment]
Yes, i see what you mean, though each example has it's own README.

https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/factoryapp

But.... there is no index to list and explain each one of them. Where would you place this README?

**Comment by stephlocke** [comment]
You can drop it into examples and the README will be presented by default when people navigate to the folder

**Comment by dpgaspar** [comment]
Done! Thanks for the feedback.
