### ISSUE TITLE
mongoimages example error

### ISSUE THREAD

**Issue by mgazzin** [dpgaspar/Flask-AppBuilder#275]
Dear all,

I have just cloned AppBuilder in my machine and tried to run some examples.
mongoimages example fails with the following error:

mongoengine.errors.ValidationError
ValidationError: u'1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

is there something I can do it to avoid that?
Thanks.
Bye.

**Comment by dpgaspar** [comment]
This because you still have your sqlalchemy cookie, delete all your cookies or just the 'session' one, and retry

**Comment by scheung38** [comment]
I also deleted all cookies from browser history, but still seeing the same

```
mongoengine.errors.ValidationError
ValidationError: u'1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```
