### ISSUE TITLE
Content not served over HTTPS

### ISSUE THREAD

**Issue by jacobo3d** [dpgaspar/Flask-AppBuilder#277]
Hi,

After creating a simple default application, when trying to run a few actions (like clicking on the Login button), I will get this error on the console:

Mixed Content: The page at 'https://mySite.com' was loaded over HTTPS, but requested an insecure resource 'http://mySite.com/userinfoeditview/form'. This request has been blocked; the content must be served over HTTPS.

Any ideas?

Thanks!

**Comment by dpgaspar** [comment]
Is this the only link where this happens??

**Comment by raoden1** [comment]
change http to https. You're trying to access something over https using http. It's obvious that you get this error.

**Comment by dpgaspar** [comment]
If this is still relevant to you, feel free to reopen. Are you doing ELB ssl termination?
