### ISSUE TITLE
MySQL blob

### ISSUE THREAD

**Issue by mgazzin** [dpgaspar/Flask-AppBuilder#278]
Dear all,

I am building an application on one existing MySQL database.
I do not want to migrate the database to MongoDB. I think it would be too complex.
The database has some BLOB fields containing PDF files.
Could you please tell me if and how I can handle such fields with Flask AppBuilder.
I have not found any refernce in your documentation. I have just found 'mongoimages' example, which unfortunately is related to MongoDB.

Thanks.
Cheers.

**Comment by dpgaspar** [comment]
Sorry but Blob is not a supported column on flask-appbuilder, this means that form will not auto generate this field, you can use it, but you have to create your own form or list render.

This is a good candidate for an enhancement.
