### ISSUE TITLE
Add_link with absolute url

### ISSUE THREAD

**Issue by cuph62** [dpgaspar/Flask-AppBuilder#279]
Hello,

adding a link to the menu, references relatively to the current url,

eg from the example:
# Add a link
appbuilder.add_link("google", href="www.google.com", icon = "fa-google-plus")

navigates to <http://my-url/myflaskapp/www.google.com> instead of going to http://www.google.com.

Is there a way to have an absolute reference as menu instead ?

kind regards,
Herman

**Comment by dpgaspar** [comment]
use it like this:

appbuilder.add_link("Google", href="http://www.google.com", icon="fa-google-plus")

Docs are not correct about it, i'll update them ASAP.
