### ISSUE TITLE
Question: How to use base_filters with different roles?

### ISSUE THREAD

**Issue by ndemir** [dpgaspar/Flask-AppBuilder#281]
I implemented an application where each user sees his records. But I also need the admin user to see all records. I do not want to use base_filters if the user has admin role. 
How can I modify base_filters for each role?

**Comment by dpgaspar** [comment]
I think that the best way is to create an alternate ModelView equal to your filtered views but without the base_filters. Then give access to this view just for the admin role.

**Comment by ndemir** [comment]
@dpgaspar Yes, I've already done that. But I was looking for a more elegant way. By the way, thanks for answer.

**Comment by vincenzodesanctis** [comment]
I have the same issue, after creating the addition ModelView for the admin user, how to assign it to admin?
