### ISSUE TITLE
Question: How to get add/list/… link of a view?

### ISSUE THREAD

**Issue by ndemir** [dpgaspar/Flask-AppBuilder#282]
Currently I am using the following code to access the view.

```python
appbuilder.add_view(ItemView, "Item")
```
By default, it redirects me to listing page. And I know I can change the behaviour by overriding default_view.

But I am looking something as the following.
```python
appbuilder.add_link("Add New Item", ItemView().get_add_link())
appbuilder.add_link("List Items", ItemView().get_list_link())
```

How to get the view URL of the list/add pages of the view?

**Comment by dpgaspar** [comment]
You can use Flask's url_for('ItemView.add').
