### ISSUE TITLE
Dynamic field filter in select2

### ISSUE THREAD

**Issue by philliproso** [dpgaspar/Flask-AppBuilder#29]
Maybe I am not really understanding edit_form_query_rel_fields, but this is a pretty important feature. Build a filter to the drop down list based on the selection of previous drop down lists. 

Usecase user select category A from form field 1. User can then only select subsets of category A from form field 2. 

Is there an easy way of doing this

PS 0.10 looks rad

**Comment by scheung38** [comment]
This talks about it here

http://librelist.com/browser/flask/2012/10/3/populating-forms-based-on-initial-entry/#00bf3feb9757706a4254b0e3596a2159

But I am not sure if compatible with Flask-AppBuilder

**Comment by jvinolas** [comment]
And with a little of ajax? You have to expose /filtrarplantilla/<tipus>
(haven't test it in appbuilder, but works with Flask)

"""
function filtrarPlantillaTipus(element) {
	var tipus = element.options[element.selectedIndex].value
	var llista = document.getElementById("VMTemplate")
	$.ajax({
		type: "GET",
		//~ dataType: "json",
		url:"/filtraPlantilla/" + tipus,
		success: function(templates)
		{
			if (templates.length >0) {
				var contingut='<option value="">Seleccioneu una entre '+templates.length+' plantilles trobades</option>';
			} else {
				var contingut='<option value="">Cap plantilla coincident</option>';						
			}
		  for (var i=0; i<templates.length; i++) {
				contingut=contingut+'<option value="'+templates[i]['id']+'" >'+templates[i]['name']+'</option>';
			}
		  llista.innerHTML=contingut;
		}				
	});
"""

And then in your template:
"""
            <tr>
                <td>Tipus de plantilla:</td>
                <td><select name="VMTemplateType" onchange="filtrarPlantillaTipus(this);">
						<option value="">Seleccioneu tipus de plantilla:</option>
						<option value="VIMET">vimet</option>
						<option value="MEVES">Meves</option>
						<option value="PUBLIQUES">Públiques</option>
						</select>
				</td>
            <tr>
                <td>Plantilla:</td>
                <td><select id="VMTemplate" name="VMTemplate" onchange="selectChange(this);">
						<option value="">Seleccioneu plantilla base:</option>
				</td>
            <tr>
"""

**Comment by scheung38** [comment]
in my model.py:

class Regions(BaseMixin, Base):                  
    id = Column(Integer, primary_key=True)       
    name = Column(String(50), unique=True, nullab
                                                 
    def __repr__(self):                          
        return self.name                         
                                                 
                                                 
class DcName(BaseMixin, Base):                   
    id = Column(Integer, primary_key=True)       
    name = Column(String(50), unique=True, nullab
    regions_id = Column(Integer, ForeignKey('regi
    regions = relationship("Regions")            
                                                 
    def __repr__(self):                          
        return self.name                         
                                                 
                                                 
class Server(BaseMixin, Base):               
    id = Column(Integer, primary_key=True)       
    name = Column(String(150), unique=True, nulla
                                                 
    address = Column(String(564))                
    birthday = Column(Date, nullable=True)       
                                                 
    personal_phone = Column(String(20))          
    personal_cellphone = Column(String(20))      
                                                 
    regions_id = Column(Integer, ForeignKey('regi
    regions = relationship("Regions")            
    dc_name_id = Column(Integer, ForeignKey('dc_n
    dc_name = relationship("DcName")             
                                                 
    def __repr__(self):                          
        return self.name          


in my view.py:

class ContactGeneralView(ModelView):
    datamodel = SQLAInterface(Server)

    list_title = 'Manage Servers'

    label_columns = {'name': 'SRV_Name',
                     'personal_phone': 'SRV_Status',
                     'dc_name': 'DC_Name',
                     'regions': 'Regions'
                     }

    list_columns = ['name', 'personal_phone', 'dc_name', 'regions']
    base_order = ('name', 'asc')
    show_fieldsets = [
        ('Summary', {'fields': ['name', 'regions', 'dc_name']}),
        (
            'Personal Info',
            {'fields': ['address', 'birthday', 'personal_phone', 'personal_cellphone'], 'expanded': False}),
    ]

    add_fieldsets = [
        ('Summary', {'fields': ['name', 'regions', 'dc_name']}),
        (
            'Personal Info',
            {'fields': ['address', 'birthday', 'personal_phone', 'personal_cellphone'], 'expanded': False}),
    ]

    edit_fieldsets = [
        ('Summary', {'fields': ['name', 'regions', 'dc_name']}),
        (
            'Personal Info',
            {'fields': ['address', 'birthday', 'personal_phone', 'personal_cellphone'], 'expanded': False}),
    ]

class GroupMasterView(MasterDetailView):
    datamodel = SQLAInterface(Regions)
    related_views = [DcGeneralView]   
    list_title = 'List Regions'


class GroupGeneralView(ModelView):
    datamodel = SQLAInterface(Regions)
    related_views = [ContactGeneralView]
    list_title = 'Manage Regions'               

db.create_all()

# fill_gender()
appbuilder.add_view(GroupMasterView, "List Regions", icon="fa-folder-open-o", category="Regions")
appbuilder.add_separator("Regions")
appbuilder.add_view(GroupGeneralView, "Manage Regions", icon="fa-folder-open-o", category="Regions")
appbuilder.add_view(DcGeneralView, "Manage DC_Names", icon="fa-folder-open-o", category="Regions")
appbuilder.add_view(ContactGeneralView, "Manage Servers", icon="fa-folder-open-o", category="Regions")


But where would you implement that Javascript code, and where is the actual html to overrride? in my http://localhost:8080/contactgeneralview/add

![screen shot 2015-04-02 at 15 50 19](https://cloud.githubusercontent.com/assets/1273014/6966318/1415c5ce-d950-11e4-82fb-0651c4911bd8.png)

**Comment by jvinolas** [comment]
Hi again,

One option will be to override the add.html template to add your own javascript code and find what is the id for the html select block. For example:
```
                <select class="my_select2 form-control" data-placeholder="Select Value" id="template_base" name="template_base" style="width:250px"></select>
```
That in your example will be dummy_city2 or something like that.

But you should call filtrarPlantillaTipus on the first select (location) so I think the only way will be to create your own select widget that calls that function onchange.

This is only an idea.

**Comment by scheung38** [comment]
Hi Jvinolas,

Could you show how to override the add.html page?

**Comment by scheung38** [comment]
http://devzone.co.in/simple-example-of-dependable-dropdowns-cascading-dropdowns-using-angularjs/

in views.py:
class MgntServerGeneralView(ModelView):
    datamodel = SQLAInterface(MyTable)
    add_template = 'testDropDown.html'

/templates/testDropDown.html:

<!DOCTYPE html>
<html ng-app>
    <head>
        <title>Cascading Dropdowns in AngularJs :devzone.co.in </title>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
        <script>
            function CountryCntrl($scope) {
                $scope.countries = {
                    'India': {
                        'Maharashtra': ['Pune', 'Mumbai', 'Nagpur', 'Akola'],
                        'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur'],
                        'Rajasthan': ['Jaipur', 'Ajmer', 'Jodhpur']
                    },
                    'USA': {
                        'Alabama': ['Montgomery', 'Birmingham'],
                        'California': ['Sacramento', 'Fremont'],
                        'Illinois': ['Springfield', 'Chicago']
                    },
                    'Australia': {
                        'New South Wales': ['Sydney'],
                        'Victoria': ['Melbourne']
                    }
                };
            }
        </script>
    </head>
    <body>

        <div ng-controller="CountryCntrl">
            <div>
                Region:
                <select id="country" ng-model="states" ng-options="country for (country, states) in countries">
                    <option value=''>Select</option>
                </select>
            </div>
            <div>
                Dc_Name: <select id="state" ng-disabled="!states" ng-model="cities" ng-options="state for (state,city) in states"><option value=''>Select</option></select>
            </div>
        </div>

    </body>
</html>

in app.js:

function CountryCntrl($scope) {
    $scope.countries = {
        'India': {
            'Maharashtra': ['Pune', 'Mumbai', 'Nagpur', 'Akola'],
            'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur'],
            'Rajasthan': ['Jaipur', 'Ajmer', 'Jodhpur']
        },
        'USA': {
            'Alabama': ['Montgomery', 'Birmingham'],
            'California': ['Sacramento', 'Fremont'],
            'Illinois': ['Springfield', 'Chicago']
        },
        'Australia': {
            'New South Wales': ['Sydney'],
            'Victoria': ['Melbourne']
        }
    };
}

But this doesn't tie in with Flask-AppBuilder SQLAlchemy with look and feel and database.

**Comment by scheung38** [comment]
So is it a challenge to implement in Flask-AppBuilder? Or is it quite straight forward to add, say AngularJS logic to the front end by overriding select widget?
