### ISSUE TITLE
How to add add_form_extra_fields to the list_columns?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#290]
I've added this to my model:
    add_form_extra_fields = {'extra': StringField(gettext('Extra Field'),
                        description=gettext('Extra Field description'),
                        widget=BS3TextFieldWidget())}
I also limit the fields listed in the view using this:
    list_columns = ['Event', 'CarClassKey', 'Marque', 'Title', 'Description', 'Closed', 'Printed', 'StartYear', 'EndYear']

How can I add the extra field to the list of displayed fields?
Thanks!

**Comment by dpgaspar** [comment]
I assume you have added this to your ModelView not your Model right:

``` python

I've added this to my model:
add_form_extra_fields = {'extra': StringField(gettext('Extra Field'),
description=gettext('Extra Field description'),
widget=BS3TextFieldWidget())}
```

So add 'extra' to your model, maybe in the form of a function

**Comment by dpgaspar** [comment]
any luck with this?

**Comment by AustinJim** [comment]
Hi Daniel,
I did get it working with by adding this to my model:
```
    def extra(self):
        return 'test value'
```
Thanks for your help!

**Comment by AustinJim** [comment]
I do have a related question. Can the extra field be used in the list_columns list like below? When I try I get the error at the bottom. It seems to be looking for an attribute on the model. Is there a way to add an attribute that is not persisted to the database?
```
    list_columns = ['Event', 'CarClassKey', 'Marque', 'Title', 'Description', 'Closed', 'Printed','extra']

  File "C:\Python27\lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 384, in get_col_default
    default = getattr(self.list_columns[col_name], 'default', None)
KeyError: 'extra
```
