### ISSUE TITLE
Creating a custom list template

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#291]
I'm trying to create a custom list template for one of my model views. I've created listCarClassesPrint.html in the templates folder and added this to the view:
```
list_template = 'listCarClassesPrint.html'
```
For simplicity I've reduced the template to this:
```
{% extends 'appbuilder/general/widgets/list.html' %}

{% block begin_loop_values %}
    Make your loop and render the list itself.
{% endblock %}
```
The following error occurs:
```
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\general\lib.html", line 272, in template
    {{ render_pagination(page, page_size, count, modelview_name) }}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\general\lib.html", line 112, in template
    {% set pages = ((count / page_size)|round(0,'ceil')|int)%}
UndefinedError: 'count' is undefined
```
What am I doing wrong?
Thanks!

**Comment by dpgaspar** [comment]
Remember you've got template and widgets. You are replacing a template so you should extend it like this:

```
{% extends "appbuilder/general/model/list.html" %}

    {% block list_search scoped %}
        This Text will replace the search widget
    {% endblock %}
```
(...general/model/... not /general/widgets/...)

**Comment by AustinJim** [comment]
I'm still having trouble. I've tried pasting the complete block of code just below "Let’s make a simple example:" from the Templates page of the docs. It seems to have some problems like the closing div with no opening div and an incorrectly formed P tag. Even if I remove those I get this error: 
```
File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\general\lib.html", line 112, in template
{% set pages = ((count / page_size)|round(0,'ceil')|int)%}
UndefinedError: 'count' is undefined
```
I'm trying to add a Print button for each record in the list. I'd like to add it to the existing buttons. Do you have any sample code that does that or any advise on how to implement it?

Thanks!

The code from the online docs:
```
{% import 'appbuilder/general/lib.html' as lib %}
{% extends 'appbuilder/general/widgets/base_list.html' %}

{% block list_header %}
   {{ super() }}
   <a href="url_for('Class.method for my control')" class="btn btn-sm btn-primary"
        <i class="fa fa-rocket"></i>
   </a>
{% endblock %}

{% block begin_loop_values %}
    {% for item in value_columns %}
        {% set pk = pks[loop.index-1] %}
        {% if actions %}
            <input id="{{pk}}" class="action_check" name="rowid" value="{{pk}}" type="checkbox">
        {% endif %}
        {% if can_show or can_edit or can_delete %}
            {{ lib.btn_crud(can_show, can_edit, can_delete, pk, modelview_name, filters) }}
        {% endif %}
        </div>

        {% for value in include_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}
    {% endfor %}
{% endblock %}
```

**Comment by dpgaspar** [comment]
I think there is still some confusion between templates and FAB widgets.

But i think that the easiest ways to add a new buttom, would be to define it on your Model class. Something like this:

``` python
class Contact(Document):
    name = StringField(max_length=60, required=True, unique=True)
    
    def print_buttom(self):
        return Markup(
                '<a href="' + url_for(SOMETHING) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"
       title="Print">
        <i class="fa fa-edit"></i>
    </a>'
```

Then use it on your ModelView using list_columns property.

**Comment by AustinJim** [comment]
Thanks Daniel. I'll read up more on jinja2 and widgets and I'll try the code above. What do I need to include to get Markup()?

**Comment by dpgaspar** [comment]
No prob, remember these widget i'm talking about are specific to F.A.B. They use WTForms widgets but have extended them. 

For Markup import it from Flask, take a look at: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickfiles/app/models.py

**Comment by dpgaspar** [comment]
I'll close this one, any further questions, just reopen it. ok?

**Comment by AustinJim** [comment]
Perfect! Thanks so much for your help!

**Comment by AustinJim** [comment]
Hi Daniel,
Sorry to be so dense but I can't get it to work. I've looked through the examples but list_columns occurs so much that I couldn't find this type of use for it. If there is an example that implements this please tell me which one. I would really appreciate some guidance.
Thanks!

 I added this to my model:
```
    def print_button(self):
            return Markup('<a href="www.google.com" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"  title="Print"><i class="fa fa-edit"></i></a>')
```
and this to my view:
```
    label_columns = {'print_button': 'Print', 'EventID': 'Event', 'CarClassKey': 'Car Class Key', 'Description': 'Description')
```
But I get the following error which is because print_button is not in self.list_columns:
```
  File "C:\Python27\lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 384, in get_col_default
    default = getattr(self.list_columns[col_name], 'default', None)
KeyError: 'print_button'
```

**Comment by AustinJim** [comment]
Got it. The answer was in the example you provided above. 
Thanks!
