### ISSUE TITLE
Anyone Using Cassandra?

### ISSUE THREAD

**Issue by aaronbenz** [dpgaspar/Flask-AppBuilder#292]
Has anyone tried using Cassandra as their DB? Any guidances as to how to do that with https://github.com/thegeorgeous/flask-cqlalchemy?

**Comment by dpgaspar** [comment]
No, this will probably not work, i would have to make a specific interface for it.

Your very welcome to submit a PR with it thought :)

Take a look at: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/models

This is where the interfaces are implemented.
