### ISSUE TITLE
How to add foreign key to user table?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#293]
HI all,
I want to create a foreign key from a table I created to the user table. I don't want this user to be the user who is logged in. I just want to present a dropdown of all users so one can be assigned as the "author". I've tried the following:
```
    UserID = Column(Integer, ForeignKey('User.id'), nullable=False)
    User = relationship('User')
```
What's the correct way to do this?
Thanks!

**Comment by AustinJim** [comment]
I've decided to use the AuditMixin and let the currently logged in user be the "Author". Now I would like to rearrange the order of the fields but I don't know how to refer to the fields in the user table, like username. I'm guessing the ab_user table is opened under an alias. Is that correct?

How can I refer to the fields added by the AuditMixin in the edit_columns argument?

Thanks!

**Comment by dpgaspar** [comment]
Take a look at: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/mixins.py#L36

you have: created_on, changed_on, created_by, changed_by. Hope it helps!

**Comment by dpgaspar** [comment]
I'll close this one. Any further help, please reopen it, or open a new one.
