### ISSUE TITLE
How to OR base filters?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#295]
Is it possible to OR base filters? If so, what is the syntax. If not, what is the non-base filter way to filter by the user who created the record? I want to filter my table by the user who created the record OR the public flag, which is a boolean on the record.

Thanks!

**Comment by dpgaspar** [comment]
Sorry you can't use OR logic on base filters. I guess you have to implement you own Model View for this.

Any further help, your welcome to post.

**Comment by francisliyy** [comment]
Hi @AustinJim, did you implement this function?  how did you do?
