### ISSUE TITLE
Where is the code that renders Text columns?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#296]
Hi,
I'd like to add a button next to fields that are Text fields in the model. Where are those fields rendered?
Thanks!

**Comment by dpgaspar** [comment]
I advise you to create your own widget for this: http://flask-appbuilder.readthedocs.org/en/latest/templates.html#widgets

The "normal" edit widget is here: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/widgets/form.html

Hope it helps for inspiration :)
