### ISSUE TITLE
gettext in navbar_menu.html leads to runtime error in non-English locales

### ISSUE THREAD

**Issue by giyokun** [dpgaspar/Flask-AppBuilder#297]
In the release version (obtained by virtualenv pip install flask_appbuilder)
the following lines in navbar_menu.html would lead to runtime error in gettext

line 6:    {{\_(item.label)}}</a>
line 18:   {{\_(item1.label)}}<b class="caret"></b></a>

I removed the _() gettext and it worked like a charm (including the localization).

Is this a known issue?

**Comment by giyokun** [comment]
I also found similar issues in lib.html while navigating throughout the UI while in Japanese locale or Chinese locale. Is there an easy way to detect the gettext call is in the wrong place? To me the changes I was doing felt totally random.

**Comment by dpgaspar** [comment]
Ok, this could be a bug, can you submit a simple example where this happens? It would make it way easier for me.

**Comment by giyokun** [comment]
hmmm,  I honestly don't remember much of what I was doing three months ago. I think I created a basic app and after selecting a different language, navigated in the app to see a few errors. I am sorry I didn't keep a screenshot or log of what the error was... I would have to set up an env from scratch again to reproduce and I don't have any time to spend on this at the moment.
It is good to hear from you though... i was worried the project was not getting any of your attention anymore and held off working more on my hobby projects because of that.

**Comment by dpgaspar** [comment]
I'm sorry to hear that, my fault really. I'm planning to give you people much better support from now on.

I'll close this.
