### ISSUE TITLE
Prepared a PO file for Japanese localization

### ISSUE THREAD

**Issue by giyokun** [dpgaspar/Flask-AppBuilder#298]
Please find attached to this message.
[messages.zip](https://github.com/dpgaspar/Flask-AppBuilder/files/130101/messages.zip)

Most of my users will be Japanese so I wanted to have a minimum Japanese localization.
Let me know if you need anything from me.

**Comment by giyokun** [comment]
Updated (reviewed by a Japanese colleague)

[messages.zip](https://github.com/dpgaspar/Flask-AppBuilder/files/132996/messages.zip)

**Comment by dpgaspar** [comment]
This is great!!! Thank you. 

Sorry for the late reply, i'll include this one on the next release.

**Comment by dpgaspar** [comment]
It's included... i'll release it on 1.6.2 ASAP. you will be able to use it adding it to config like this:

``` python
LANGUAGES = {
    'en': {'flag': 'gb', 'name': 'English'},
    'pt': {'flag': 'pt', 'name': 'Portuguese'},
    'es': {'flag': 'es', 'name': 'Spanish'},
    'de': {'flag': 'de', 'name': 'German'},
    'zh': {'flag': 'cn', 'name': 'Chinese'},
    'ru': {'flag': 'ru', 'name': 'Russian'},
    'pl': {'flag': 'pl', 'name': 'Polish'},
    'ja_JP': {'flag': 'jp', 'name': 'Japanese'},
}
``` 

どうもありがとうございました
Daniel
