### ISSUE TITLE
Question: Is there a way to enable/add a Django-admin-like search box

### ISSUE THREAD

**Issue by dgleba** [dpgaspar/Flask-AppBuilder#303]
I have been reading the docs, but I haven't seen such a feature or ideas on how to add it.

The Django admin has a box that searches 'all' or multiple columns from one user input box.

Can I do that in Flask-AppBuilder?

**Comment by dpgaspar** [comment]
Nop, you can't do that in flask-appbuilder. But you can implement your own from scratch along with flask-appbuilder.
