### ISSUE TITLE
How to get a uploaded file in ModelView?

### ISSUE THREAD

**Issue by luylucas10** [dpgaspar/Flask-AppBuilder#304]
Hi. First, thanks a lot for this wonderful extension. 

I'm learning python and I'm developing an web application with this extension.
I created all my models and crud with SQLAInterface. 
But how I fetch a file uploaded in a form to read?

Thanks.

**Comment by dpgaspar** [comment]
Read this simple example: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickfiles

Then test with post_add and post_edit: http://flask-appbuilder.readthedocs.io/en/latest/api.html#flask.ext.appbuilder.baseviews.BaseCRUDView.post_add

I'll close this one, if you need extra pointers, or did not have any success, fell free to reopen it.
