### ISSUE TITLE
How to Use LDAP as Generic Datasource

### ISSUE THREAD

**Issue by sambanks** [dpgaspar/Flask-AppBuilder#305]
Hi There

Thanks for the great code! I was wondering if you could help me.
I'm trying to create create a Flask App that administers two external Data Sources; one mysql database and an ldap directory. I am keeping the authentication details for the app in sqlite and using SQLAlchemy bind to access the mysql database. That works fine, but I am having a lot of trouble setting up the LDAP as a datasource.

Following your example I have the following in view for mysql:

``` python
class UserDetailView(ModelView):
        datamodel = SQLAInterface(UserDetail)
        list_columns = ['user_name', 'id']
        edit_columns = ['last_name']
```

and for LDAP:

``` python
class LdapView(ModelView):
    datamodel = GenericInterface(LdapModel, sess)
    list_columns = ['uid', 'cn', 'mail']
    edit_columns = ['mail']
```

and in model:

``` python
class LdapModel(GenericModel):
    cn = GenericColumn(str, primary_key=True)
    givenName = GenericColumn(str)
    uid= GenericColumn(str)
    userPassword = GenericColumn(str)
    mail = GenericColumn(str)
```

``` python
class LdapSession(GenericSession):
    import ldap
    ldap_user='cn=Directory Manager'
    ldap_pass='Passw0rd'
    ldap_server='localhost'
    ldap_port='389'
    base_dn_asp='ou=People,dc=example,dc=com'
    conn = ldap.initialize('ldap://{}:{}'.format(ldap_server,ldap_port))
    conn.simple_bind_s(ldap_user,ldap_pass)
```

But I can't figure out how to finish the LdapSession Model to make it work like the mysql connection.

Hopefully that makes sense.

Thanks
Sam

**Comment by dpgaspar** [comment]
Ok, i've done this already but for reading and reseting password's only. Are you still interested on this. Please let me know, i'll get the code and post back.

**Comment by sambanks** [comment]
Yes thanks, that would be great. I ended up doing it with a form, but it would be much better to be able to do with the data source

**Comment by dpgaspar** [comment]
Sorry, this one is taking a while... Hope to get the code this week

**Comment by sambanks** [comment]
No worries, thanks for looking into it. If it turns out to be too big of a pain, don't worry, as I have an ugly workaround.
