### ISSUE TITLE
Add option to force TLS for LDAP authentication

### ISSUE THREAD

**Issue by mtrbean** [dpgaspar/Flask-AppBuilder#308]
Can we add an option to initiate TLS connection by calling `start_tls_s()`?

**Comment by mtrbean** [comment]
Never mind - I realize that I can just use `ldaps://ldapserver:636` for `AUTH_LDAP_SERVER`

**Comment by alexandrezia** [comment]
Using SSL is not the best option, as SSL is deprecated as insecure.
The only secure option is TLS
I think FAB should support TLS
