### ISSUE TITLE
fabmanager bug on windows

### ISSUE THREAD

**Issue by wtjcn** [dpgaspar/Flask-AppBuilder#311]
I use windows10, python2.7.11(64bit), flask_appbuilder1.6.0,
when try 'examples\simpleform' I get these:

> (flaskapp) R:\Flask-AppBuilder-master\examples\simpleform>fabmanager run
> 2016-04-09 06:50:43,437:WARNING:flask_appbuilder.security.manager:No user yet created, use fabmanager command to do it.
> 2016-04-09 06:50:43,441:INFO:flask_appbuilder.base:Registering class IndexView on menu
> 2016-04-09 06:50:43,448:INFO:flask_appbuilder.base:Registering class UtilView on menu
> 2016-04-09 06:50:43,453:INFO:flask_appbuilder.base:Registering class LocaleView on menu
> 2016-04-09 06:50:43,460:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu
> 2016-04-09 06:50:43,470:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu
> 2016-04-09 06:50:43,483:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu
> 2016-04-09 06:50:43,492:INFO:flask_appbuilder.base:Registering class AuthDBView on menu
> 2016-04-09 06:50:43,502:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
> 2016-04-09 06:50:43,532:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
> 2016-04-09 06:50:43,562:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
> 2016-04-09 06:50:43,585:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
> 2016-04-09 06:50:43,609:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
> 2016-04-09 06:50:43,634:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
> 2016-04-09 06:50:43,691:INFO:flask_appbuilder.base:Registering class MyFormView on menu My form View
> 2016-04-09 06:50:43,734:INFO:werkzeug: \* Restarting with stat
> **d:\tools\flaskapp\scripts\python.exe: can't open file 'D:\tools\flaskapp\Scripts\fabmanager': [Errno 2] No such file or directory**

I find "D:\tools\flaskapp\Scripts\fabmanager.exe" ,but not find "D:\tools\flaskapp\Scripts\fabmanager.py".
 Dose this cause the problem?

**Comment by dpgaspar** [comment]
That could be it. No windows 10 to test. Have you tried to copy it from D:\tools\flaskapp\Scripts\fabmanager.exe to D:\tools\flaskapp\Scripts\fabmanager.py. I know it's hackish
