### ISSUE TITLE
String encoding causing column labels to be prefixed with 'b' in Python 3x

### ISSUE THREAD

**Issue by andrewhn** [dpgaspar/Flask-AppBuilder#312]
Hi,

The names assigned to `label_columns` on Python 3x are being prefixed with the byte notation. Seems to me this is happening on [this line](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L450), which has the following effect in Python 3x:

```
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> str("abc".encode("UTF-8"))
"b'abc'"
```

**Comment by dpgaspar** [comment]
Are you able to test it with caravel and python 3x. branch 1.6.2
