### ISSUE TITLE
api/read fails for views with models which have foreign key / relationship

### ISSUE THREAD

**Issue by Fuzzwah** [dpgaspar/Flask-AppBuilder#313]
I have two simple models and views:

Models:

    class Album(Model):
        __tablename__ = 'albums'
        id = Column(Integer, primary_key=True)
        name = Column(String(254))
        card_id = Column(Integer, ForeignKey('cards.id'))
        card = relationship("Card")

        def __repr__(self):
            return self.name

    class Card(Model):
        __tablename__ = 'cards'
        id = Column(Integer, primary_key=True)
        number = Column(String(12), nullable=False)

        __mapper_args__ = {
            "order_by": id.desc()
        }

Views:

    class Albums(ModelView):

        datamodel = SQLAInterface(Album)

        search_columns = ['name', 'card']
        list_columns = ['name', 'card']
        edit_fieldsets = [('Album',{'fields':['name', 'card']})]
        add_fieldsets = [('Album',{'fields':['name', 'card']})]

    class Cards(ModelView):

        datamodel = SQLAInterface(Card)            

I have 1 row inserted into the db for each model, just for testing. The single album item is bound to a card item. Everything works as expected when dealing with the data via the webpage.

I'm then trying to get a return via an API call. I have everything working and can get a return from a call to the cards API (see my previous issue, where I worked out I needed to set ```WTF_CSRF_ENABLED = False```):

    # curl -X GET 'http://localhost:8080/cards/api/read'

    {
      "count": 1,
      "label_columns": {
        "id": "Id",
        "number": "Number"
      },
      "list_columns": [
        "number"
      ],
      "modelview_name": "Cards",
      "order_columns": [
        "number"
      ],
      "page": null,
      "page_size": null,
      "pks": [
        1
      ],
      "result": [
        {
          "number": "0123456789"
        }
      ]
    }

But when I attempt to do the same for albums I get a 500 error:

    # curl -X GET 'http://localhost:8080/albums/api/read'

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>500 Internal Server Error</title>
    <h1>Internal Server Error</h1>
    <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>    

Here is the traceback from the server:

    Traceback (most recent call last):
      File "/project_path/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/project_path/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/project_path/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/project_path/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/project_path/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/project_path/env/local/lib/python2.7/site-packages/Flask_AppBuilder-1.6.1-py2.7.egg/flask_appbuilder/security/decorators.py", line 52, in wraps
        return f(self, *args, **kwargs)
      File "/project_path/env/local/lib/python2.7/site-packages/Flask_AppBuilder-1.6.1-py2.7.egg/flask_appbuilder/views.py", line 228, in api_read
        result=result)
      File "/project_path/env/local/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
        indent=indent),
      File "/project_path/env/local/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
        rv = _json.dumps(obj, **kwargs)
      File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
        chunks = list(chunks)
      File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
        for chunk in _iterencode_dict(o, _current_indent_level):
      File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
        for chunk in chunks:
      File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
        for chunk in chunks:
      File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
        for chunk in chunks:
      File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/project_path/env/local/lib/python2.7/site-packages/flask/json.py", line 83, in default
        return _json.JSONEncoder.default(self, o)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: 0123456789 is not JSON serializable

**Comment by Fuzzwah** [comment]
I have worked around this issue by hacking into the models/base.py file to change the ```get_values_json``` function to work like this:

    def get_values_json(self, lst, list_columns):
        """
            Converts list of objects from query to JSON
        """
        result = []
        for item in self.get_values(lst, list_columns):
            for key, value in list(item.items()):
                if isinstance(value, datetime.datetime) or isinstance(value, datetime.date):
                    value = value.isoformat()
                    item[key] = value
                elif isinstance(value, list):
                    item[key] = [str(v) for v in value]
                else:
                    type_str = str(type(value))
                    if type_str[8:19] == 'app.models.':
                        item[key] = str(value)                    
            result.append(item)
        return result

I did some reading about isinstance and isclass and issubclass and feel that there is clearly a better way to fix the issue that what I've got above, but I hit a wall and just hacked it up to get it working so I could move on with my dev work.

I can offer a pull request for the above changes, but yeah... I'm not proud of it and I figure someone with more python skillz will be able to see a far better solution.

**Comment by dpgaspar** [comment]
Ok, sorry for the late reply. This does not look good, give me some time to make some tests.

**Comment by BGarber42** [comment]
An alternative workaround is to also override ``__html__`` in addition to ``__repr__``

**Comment by OverlordQ** [comment]
An alternative workaround is to also override __html__ in addition to __repr__

**Comment by dpgaspar** [comment]
Sorry still no time to test, have you tried:

``` python
class Card(Model):
    __tablename__ = 'cards'
    id = Column(Integer, primary_key=True)
    number = Column(String(12), nullable=False)

    def __repr__(self):
        return str(self.number)

    __mapper_args__ = {
        "order_by": id.desc()
    }
```

**Comment by dpgaspar** [comment]
Have you tried it? i haven't tried it with your use-case, sorry.

Anyway on examples the simple quickhowto is very similar with your problem and it works. Have you looked at it?

I'll close this one. Feel free to reopen it.
