### ISSUE TITLE
Question: How to implement conditional access on CRUD views?

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#317]
First, this project is amazing and underrated! Thanks for making it! Feel free to add [Caravel](https://github.com/airbnb/caravel) to the list of project (or I can send a PR adding the link)

--------------

I'm implementing a slightly more complex security scheme for Caravel and I'm curious on how to restrict CRUD access. Ideally I'd be able to add logic to the central `has_access` while having context about the model, the permission (view, edit, show, ...) and the id being accessed within that method.

I figured out how to filter the list model view fairly easily by defining my own filter (deriving BaseFilter), but for other CRUD operation I'd like to get advice before I start overriding or adding a hook some place.

**Comment by dpgaspar** [comment]
Hi @mistercrunch, 

Your project looks amazing, great work!

Could you be more specific about this one? you want to extend 'has_access', for preventing access based on conditions?

Yes, please submit a pull request, to add the link to caravel, i would be more then happy to reference it on f.a.b.

**Comment by mistercrunch** [comment]
Here's my use case. Users own objects (think model instances, or in this case specific case dashboards and charts), and for some roles, only the owner of the object should be able to update it. Now I'd like to enforce that in the CRUD, but I don't control it from my app.

I looked into how the `pre_update` hook to see if I could `raise` or `return False` as a way to prevent the update from taking place and that's not currently the case. I also looked into finding a way to alter FAB's `has_access` to include some of my app's logic but couldn't find any good way to do that.

So I'm looking for your guidance in either 1. suggesting a way for me to do this without altering FAB (some hook that exists that I'm unaware of), or 2. for me to add a hook in FAB that you would agree with upfront.

In case of option 2, let me know what you think. Adding a hook to the global `has_access`, adding a `has_access` to ModelView, supporting returning False or raising in the `pre_*` ModelView methods, ...

**Comment by dpgaspar** [comment]
Yes those are two distinct ways of doing it.

1 - Simpler and easier, would be to change BaseCRUDView._edit and BaseCRUDView._delete to check the return of self.pre_update(item) and self.pre_delete(item). If False the transaction would fail with some message (this could be an issue, what error?). By the way post_update, post_delete and post_add should implement this also. This could be a nice to have, although it's probably a breaking change, probably no one is returning anything from these def's, None == False on python....

2 - Add a new decorator with new permission types, @is_owner or something, this could 'mark' the function with a new attribute f._owner = True or f._owner = f.__name__ (or something). But these attributes should be generated and inserted on the db (like the base permissions). So security.manager should be altered also.

Any ideas?

**Comment by mistercrunch** [comment]
About 1 - What if instead of returning `False` the function would raise and exception, the calling code would have a `try` block to silence the hard error, but would abort the operation and flash the message in the exception. Let me try to send a quick PR that would show how it may work.

**Comment by dpgaspar** [comment]
I like it, it's simple. Let me make some tests.

**Comment by mistercrunch** [comment]
Oh I could have added unit tests as well, I just wanted to make sure you were ok with the approach before I did...
