### ISSUE TITLE
Hooks for "on save" redirects

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#318]
To help with my application flow, I'd like to control where saving an item from the modelview's add and edit redirects the user. 

Would you accept a PR adding in this functionality? Any recommendation as to how to proceed (I'm ok if this is vague!)

**Comment by dpgaspar** [comment]
Well if your willing to make a PR. Probably one way is to implement new functions on ModelView class, something like:

post_add_redirect, post_edit_redirect, post_delete_redirect

They could be overridden and by default would be:

``` python

def post_add_redirect(self):
    return redirect(self.get_redirect())

```

Then on ModelView change add, edit and delete like this:

``` python
@expose('/add', methods=['GET', 'POST'])
    @has_access
    def add(self):
        widget = self._add()
        if not widget:
            return self.post_add_redirect()
        else:
            return self.render_template(self.add_template,
                                        title=self.add_title,
                                        widgets=widget)
```

Haven't test it, there may be some side effects, that i'am not aware of right know.

What do you think? Fell free to propose a different approach or change names.

**Comment by mistercrunch** [comment]
Sounds right, I'll try to find some time to add this hook and related unit tests.

On a side note we still sometimes get bugs around the session variables in the Inlines, one day I might try to remove all the state handling in there. For now I just tell the users to clear their cookies when the bug happens and it gets things back on track.

**Comment by dpgaspar** [comment]
Ok, Thanks for your help. I'll be waiting for the PR.

I'm not aware of this issue, is there any github issue opened with it?

**Comment by bkyryliuk** [comment]
In caravel project there is an issue, most likely they are related:
https://github.com/airbnb/caravel/issues/1219
