### ISSUE TITLE
404 Error on Inline cookie cached 

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#322]
Caravel users are reporting issues around the inline model view when elements have been deleted but are somewhat referenced in the cookie. The server just fails hard (no debug stack trace gets provided).

I would suggest that the solution to this issue is to rip out references to session variables and any sort of state on the client side.

https://github.com/airbnb/caravel/issues/462

**Comment by mistercrunch** [comment]
For the record, I probably have introduced this error as an edge related to this PR:
https://github.com/dpgaspar/Flask-AppBuilder/pull/219

**Comment by dpgaspar** [comment]
Ok, help me out here, is this reproducible on plain flask-appbuilder, can you show me how, using the quickhowto example?

**Comment by dpgaspar** [comment]
Hi @mistercrunch just pushed a possible solution. It does not remove the session state (i know it's not good) but i think it solved the issue. Can you run some tests on it?

**Comment by mistercrunch** [comment]
Oh thanks for getting on this bug so quickly! I'll try to find a way to reproduce, it's just been something that pops up every now and then. With 150+ weekly active users internally, this bug bites once or twice a week somewhat randomly around people interacting with the Inline models, often around delete operations. The lack of stack trace (getting a 404) makes it hard to track... I usually tell people to clear their cookie for the domain and they can move forward.

If I fail at reproducing I may get ahead of Pypi and start running this branch in production an report if a bug happens again.

**Comment by dpgaspar** [comment]
Ok, you should test it on caravel, i've added a redirect on the return of the inline edit.

Give me some feedback, i'll release 1.6.2. ASAP, solves 2 bugs and as extra support for Japanese.

**Comment by mistercrunch** [comment]
Ok, it's live now. Will report here if people report the 404.

**Comment by dpgaspar** [comment]
? How did you put it live ?

**Comment by mistercrunch** [comment]
Oh, I cloned my updated FAB fork on my production server and ran `setup.py install`

**Comment by dpgaspar** [comment]
1.6.2 release to PyPi
