### ISSUE TITLE
Batch edit with form input

### ISSUE THREAD

**Issue by bwilkinsSG** [dpgaspar/Flask-AppBuilder#328]
Hello Daniel! 

Can you show a very simple example of how to do a batch update with mongoengine? The example shows sql and it is difficult to understand how to use with mongo engine.

Is it possible to ask for form input for a batch edit? 
Say I want to edit all selected entries by adding a "group name" via user input. Can you show a minimal example of how I could incorporate either form input, or input via the confirmation prompt? Thank you!!

**Comment by dpgaspar** [comment]
Hi @bwilkinsSG 

Sorry for the late reply. If i understand correctly you would need to override: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/confirm.html

Or you could develop something using SimpleFormView then batch updating by overriding form_post.

Or else you need to develop it yourself, i can't support/predict all use-cases.

**Comment by dpgaspar** [comment]
I'll close this one.
