### ISSUE TITLE
Simple printing of list view

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#329]
Hi,
I need a simple list view that the user can print using the browser's print functionality. Basically, just the data in rows. I can think of the following options. I'd appreciate any feedback or suggestions on other alternatives and any recommendations.
1) Set the page size for the list view to a very large number, make sure all columns are visible and print that. So far printing the list view page results in the links being displayed, not just the data. I saw another post that said that is a Bootstrap problem but I was unable to get the @media print css to work.
2) Create a new template with no (or minimal) css and no pagination. This seems most reasonable to me. If this is a good idea, is there a particular example in the Appbuilder example that might get me started on a template that doesn't inherit the application's CSS?
3) A Flask report package. This seems too trivial for this solution but if you have a report package to suggest I'll look at it.
Thanks so much for any feedback!
Jim

**Comment by dpgaspar** [comment]
I think number 2 is the way to go. If you just write the template without extending anything, just a normal, from scratch HTML/Jinja2 page. Then override list_template on your view.

As for 3, sorry don't know any flask report package....

I'll close this one, if you have any further questions regarding this, feel free to open it.

**Comment by AustinJim** [comment]
Daniel, I know this was not really an Appbuilder question and I really appreciate your responding anyway. Thanks!

**Comment by dpgaspar** [comment]
No problem! good luck.
