### ISSUE TITLE
Dealing with very large record sets

### ISSUE THREAD

**Issue by GregSilverman** [dpgaspar/Flask-AppBuilder#330]
I have the following two models, where one patient can have many encounters:

```
Class Encounter(Model):
    __tablename__ = 'cp_service'
    id = Column(Integer, primary_key=True, autoincrement=True)
    master_service_id = Column(String(255))
    admission_datetime = Column(DateTime)
    admission_provider_id = Column(String(255))
    admission_status = Column(String(255))
    age_at_visit = Column(String(255))
    attending_provider_id = Column(String(255))
    center = Column(String(255))
    department_name = Column(String(255))
    discharge_datetime = Column(DateTime)
    encounter_category = Column(String(255))
    encounter_class = Column(String(255))
    encounter_date = Column(DateTime)
    encounter_setting = Column(String(255))
    encounter_type = Column(String(255))
    primary_care_provider_id = Column(String(255))
    primary_service_yn = Column(String(255))
    provider_id = Column(String(255))
    serv_area_id_orig = Column(String(255))
    service_id = Column(Integer)
    patient_id = Column(Integer, ForeignKey('cp_patient.patient_id'))
```
```
class Patient(Model):
    __tablename__ = 'cp_patient'
    id = Column(Integer, primary_key=True, autoincrement=True)
    first_name = Column(String(100))
    middle_name = Column(String(80))
    last_name = Column(String(80))
    sex = Column(String(80))
    race = Column(String(80))
    birth_date = Column(DateTime)
    ethnicity = Column(String(80))
    race = Column(String(80))
    patient_id = Column(Integer)
    mrn = Column(String(80))
    title = Column(String(80))
    suffix = Column(String(80))
    name_alias = Column(String(80))
    addr_1 = Column(String(80))
    addr_2 = Column(String(80))
    addr_3 = Column(String(80))
    city = Column(String(80))
    state = Column(String(80))
    country = Column(String(80))
    zip = Column(String(80))
    encounter = relationship("Encounter", backref=backref("Patient"), lazy='dynamic', primaryjoin="Patient.patient_id==Encounter.patient_id")

```

I am trying to create a related view Encounter -> Patient, but the size of the record set is failing to render this (There are a LOT of Encounters!). 

My view definitions are as follows:

```

class EncounterView(AuditedModelView):
    datamodel = SQLAInterface(Encounter)

    list_columns = ['department_name',
                    'encounter_date',
                    'Patient.first_name',
                    'Patient.last_name']


class PatientView(AuditedModelView):
    datamodel = SQLAInterface(Patient)

    related_views = [EncounterView]
                 
    list_columns = ['first_name',
                    'last_name',
                    'id']
```

My Encounter view renders just fine (and it looks like it is using LIMIT to not returned the full data set, only those that are to be displayed in the LIST view:

2016-05-31 14:37:55,665:INFO:sqlalchemy.engine.base.Engine:SELECT cp_service.id AS cp_service_id, cp_service.master_service_id AS cp_service_master_service_id, cp_service.admission_datetime AS cp_service_admission_datetime, cp_service.admission_provider_id AS cp_service_admission_provider_id, cp_service.admission_status AS cp_service_admission_status, cp_service.age_at_visit AS cp_service_age_at_visit, cp_service.attending_provider_id AS cp_service_attending_provider_id, cp_service.center AS cp_service_center, cp_service.data_source_id AS cp_service_data_source_id, cp_service.department_id AS cp_service_department_id, cp_service.department_name AS cp_service_department_name, cp_service.discharge_datetime AS cp_service_discharge_datetime, cp_service.encounter_category AS cp_service_encounter_category, cp_service.encounter_class AS cp_service_encounter_class, cp_service.encounter_date AS cp_service_encounter_date, cp_service.encounter_setting AS cp_service_encounter_setting, cp_service.encounter_type AS cp_service_encounter_type, cp_service.primary_care_provider_id AS cp_service_primary_care_provider_id, cp_service.primary_service_yn AS cp_service_primary_service_yn, cp_service.provider_id AS cp_service_provider_id, cp_service.serv_area_id_orig AS cp_service_serv_area_id_orig, cp_service.service_id AS cp_service_service_id, cp_service.patient_id AS cp_service_patient_id 
FROM cp_service  
LIMIT %s
2016-05-31 14:37:55,665 INFO sqlalchemy.engine.base.Engine (10,)), 

but if I try to access the PatientView, it just hangs (it looks like it is doing a full select on the cp_service table - which is very large -

SELECT cp_service.id AS cp_service_id, cp_service.master_service_id AS cp_service_master_service_id, cp_service.admission_datetime AS cp_service_admission_datetime, cp_service.admission_provider_id AS cp_service_admission_provider_id, cp_service.admission_status AS cp_service_admission_status, cp_service.age_at_visit AS cp_service_age_at_visit, cp_service.attending_provider_id AS cp_service_attending_provider_id, cp_service.center AS cp_service_center, cp_service.data_source_id AS cp_service_data_source_id, cp_service.department_id AS cp_service_department_id, cp_service.department_name AS cp_service_department_name, cp_service.discharge_datetime AS cp_service_discharge_datetime, cp_service.encounter_category AS cp_service_encounter_category, cp_service.encounter_class AS cp_service_encounter_class, cp_service.encounter_date AS cp_service_encounter_date, cp_service.encounter_setting AS cp_service_encounter_setting, cp_service.encounter_type AS cp_service_encounter_type, cp_service.primary_care_provider_id AS cp_service_primary_care_provider_id, cp_service.primary_service_yn AS cp_service_primary_service_yn, cp_service.provider_id AS cp_service_provider_id, cp_service.serv_area_id_orig AS cp_service_serv_area_id_orig, cp_service.service_id AS cp_service_service_id, cp_service.patient_id AS cp_service_patient_id 
FROM cp_service). 

It does look like it is limiting the record set for Patient:
SELECT cp_patient.id AS cp_patient_id, cp_patient.first_name AS cp_patient_first_name, cp_patient.middle_name AS cp_patient_middle_name, cp_patient.last_name AS cp_patient_last_name, cp_patient.sex AS cp_patient_sex, cp_patient.birth_date AS cp_patient_birth_date, cp_patient.patient_id AS cp_patient_patient_id, cp_patient.mrn AS cp_patient_mrn, cp_patient.title AS cp_patient_title, cp_patient.suffix AS cp_patient_suffix, cp_patient.name_alias AS cp_patient_name_alias, cp_patient.addr_1 AS cp_patient_addr_1, cp_patient.addr_2 AS cp_patient_addr_2, cp_patient.addr_3 AS cp_patient_addr_3, cp_patient.city AS cp_patient_city, cp_patient.state AS cp_patient_state, cp_patient.country AS cp_patient_country, cp_patient.zip AS cp_patient_zip, cp_patient.county_current AS cp_patient_county_current, cp_patient.email_address AS cp_patient_email_address, cp_patient.home_phone AS cp_patient_home_phone, cp_patient.mobile_phone AS cp_patient_mobile_phone, cp_patient.work_phone AS cp_patient_work_phone, cp_patient.matched_address AS cp_patient_matched_address, cp_patient.research_consent AS cp_patient_research_consent, cp_patient.ethnicity AS cp_patient_ethnicity, cp_patient.ethnicity_code_orig AS cp_patient_ethnicity_code_orig, cp_patient.ethnicity_orig AS cp_patient_ethnicity_orig, cp_patient.race AS cp_patient_race, cp_patient.race_orig AS cp_patient_race_orig, cp_patient.cause_of_death AS cp_patient_cause_of_death, cp_patient.cause_of_death_2 AS cp_patient_cause_of_death_2, cp_patient.death_date AS cp_patient_death_date, cp_patient.death_record_id AS cp_patient_death_record_id, cp_patient.manner_of_death AS cp_patient_manner_of_death, cp_patient.mychart_email_yn AS cp_patient_mychart_email_yn, cp_patient.mychart_status AS cp_patient_mychart_status, cp_patient.underlying_cause_of_death AS cp_patient_underlying_cause_of_death, cp_patient.vital_status AS cp_patient_vital_status 
FROM cp_patient 
 LIMIT %s
2016-05-31 15:01:19,245:INFO:sqlalchemy.engine.base.Engine:(10,)

I've tried various lazy load methods, including joined (I assume this would be the proper one since I want to join Patient -> Encounter), subquery, no load, dynamic, and none of them seem to make any difference. NB: even without the Encounter view defined as related, I am unable to load the Patient views, due to the defined relationship with Encounter. 

This does not seem to be that out of the ordinary. Any ideas on how to make this work would be most welcome!

**Comment by GregSilverman** [comment]
Hi,
The issue appears to be that when I have a 1->n relationship and then try accessing the entity with the 1 (in my case, Patient), it will try fetching the entire related entity (in my case, Encounter) in one fell swoop. Is there a way that I can buffer the incoming data so that for a single page of Patients, I only grab Encounters for the current page? I tried playing around with the page and page_size parameters
in the query method of sqla/interface.py, but this was limiting the overall record set, and thus not desirable.  I also tried all the various eager loading methods in my Patient class, but alas...

**Comment by dpgaspar** [comment]
You can create a custom field that will render a dynamic URL for each field pointing to a filtered Encounter view list.

Take a look at: http://flask-appbuilder.readthedocs.io/en/latest/advanced.html#custom-fields

Is this feasible in your app? 

Have you tried adding

``` python
patient = relationship("Patient")
```

To your Encounter Model, and removing 'encounter' from your Patient model ?

**Comment by GregSilverman** [comment]
The solution would be similar to what I would have done with a non-scaffolded application, so yes this should be feasible (I may have some questions when I actually try it).

The relationship directly on the table with the FK constraint versus use of backref works perfectly!

Thanks!

**Comment by dpgaspar** [comment]
No problem, it's solved then. I'll close this one. Any further help, just open a new one.
