### ISSUE TITLE
following up on #334 python 3.5 file upload problem

### ISSUE THREAD

**Issue by timrichardson** [dpgaspar/Flask-AppBuilder#335]
I don't know how to reopen issue 334 :(
Regarding #334, do you have any hints on how to find where the error might be? Python 3.5 is the default on Ubuntu LTS 16.04 and this is first problem I've encountered, so I am happy to invest some time in fixing it. The trace seems to imply that an attempt to get a label attribute is failing ... does anything in the log give a hint to you about where the problem may lie?

**Comment by dpgaspar** [comment]
What version of flask-appbuilder are you using?

I've tested file upload using the quickfiles example using python 3.5, and i have no problems?

**Comment by timrichardson** [comment]
I thought I was using git head, but I will check and provide more detailed information.

**Comment by timrichardson** [comment]
With 1.7.1 from pypi, it works.
And then with a pip install from git, (1.8.1?) it also works (this is what was not working before, but I have rebuilt my development VM for other reasons so I now have a fresh python venv). 
So I can't reproduce it. Sorry.
