### ISSUE TITLE
many-to-many relationship on User Model instead of many-to-one (extendsecurity example)

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#336]
Congratulation! Flask-AppBuilder is fantastic. 
I would like to use FAB in the production environment, so I thought to modify the 'extendsecurity' example as master because it has a very interesting company relationship in the User Model. 
But my target is to allow users to see/and modify a list of companies (not only one), then I'm tring to change the ralationship from many-to-one to many-to-many.

I changed extendsecurity/app/models.py in this way, but it doesn't work, I think due to myuser.id missing:

`class Company(Model):`
`    id = Column(Integer, primary_key=True)`
`    name = Column(String(50), unique=True, nullable=False)`

`    def __repr__(self):`
`        return self.name`

`assoc_company_myuser = Table('company_myuser', Model.metadata,`
`                             Column('id', Integer, primary_key=True),`
`                             Column('company_id', Integer, ForeignKey('company.id')),`
`                             Column('myuser_id', Integer, ForeignKey('myuser.id'))`
`)`

`class MyUser(User):`
`    emp_number =  Column(String(150))`
`    company_id = Column(Integer, ForeignKey('company.id'), nullable=True)`
`    company = relationship('Company', secondary=assoc_company_myuser, backref='myuser')`

The error is : 
 _Was unable to import app Error: Could not determine join condition between parent/child tables on relationship MyUser.company - there are no foreign keys linking these tables via secondary table 'company_myuser'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions._

If I change this:

`class MyUser(User):`
`    id = Column(Integer, primary_key=True)`
`    emp_number =  Column(String(150))`
`    company_id = Column(Integer, ForeignKey('company.id'), nullable=True)`
`    company = relationship('Company', secondary=assoc_company_myuser, backref='myuser')`

The error is:

_Was unable to import app Error: Can't find any foreign key relationships between 'ab_user' and 'my_user'._

Sorry for my question not stricly related to FAB, I started to study Flask 1 week ago.

**Comment by dpgaspar** [comment]
Ok, i've prepared a simple example for this, take a look at the extendedsecurity2 on the examples.

**Comment by vincenzodesanctis** [comment]
Thank you dpgaspar!

**Comment by dpgaspar** [comment]
No problem, if this helps please close this issue.
