### ISSUE TITLE
Very basic question about changes on models.py 

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#339]
Most FAB examples use sqlite and I have no experience with it.
I don't understand what is the best way to modify the sqlite's db after models.py changes.
Do I have to modify testdata.py adding the new field (columns), remove app.db and then  "python testdata.py"? Or, is there another way to avoid removing app.db?
If I use FAB in the production environment and I'm going to add a new column, must I delete app.db every time?
What's the properly way?

**Comment by dpgaspar** [comment]
Normally on production you don't want to delete the database, just use 'alter table ...' to add or remove columns much like any other DB. Also checkout https://sqlalchemy-migrate.readthedocs.io/en/latest/
Have you tried doing 'sqlite3 app.db' ?

On the examples it depends, testdata.py and sqlite are just there to help everyone to quickly get a running example.
