### ISSUE TITLE
Question: howto select2 with AJAX default value

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#342]
select2 with AJAX on add_form_extra_fields works well, but do you know how to prefill a default value on it?  Even if the declared fileds on models.py are nullable=True I'm able to submit with the empty  field and then error Integrity error, probably unique constraint.
Where do I have to declare the default value? on models.py or on views.py?

**Comment by dpgaspar** [comment]
On this kind of fields, i can't do a auto-magic thing, you have to add the WTForms validators yourself.

I've updated the related_fields example, showing how to do this. You have to add the argument:

``` python
validators=[validators.DataRequired()]
```

To the AJAXSelectField.
