### ISSUE TITLE
Question about application name for wsgi

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#344]
I didn't use fabmanager create-app to create my app, but I modified one of the FAB examples changing piece of code adding APP_NAME=myapp to config.py. 
Maybe it's not the correct way...
However, my next step is to use apache to move the app to production. 
Following #180 I created the file wsgi.pyc inside the app folder, then added the code "from myappname import app as application"

when I run #uwsgi --socket 0.0.0.0:8000 --protocol=http -w wsgi the error is 
ImportError: No module named myappname

The question is: 

is it enough to put the application name on the variable APP_NAME (config.py) even if I didn't run "fabmanager create-app", or I have to change some other thing?

**Comment by vincenzodesanctis** [comment]
I fixed:  

the correct way is to add appname.wsgi inside the application folder and edit it

```
#!/usr/bin/python
import sys
import logging

activate_this = '/path/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/var/www/appname")

from app import app as application
```

```
<VirtualHost *>
    ServerName appname.example.com

    WSGIDaemonProcess appname user=myusername group=mygroup threads=5
    WSGIScriptAlias / /var/www/appname/appname.wsgi

    <Directory /var/www/appname/>
        WSGIProcessGroup appname
        WSGIApplicationGroup %{GLOBAL}
        Options Indexes FollowSymLinks
        Options +ExecCGI
        AddHandler cgi-script cgi pl py
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>

```

**Comment by vincenzodesanctis** [comment]
`from appname import app as application`
was wrong

just:

`from app import app as application`

**Comment by dpgaspar** [comment]
Great!
