### ISSUE TITLE
Question about form on special condition to hide or unhide filed based on other field contents

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#345]
I really appreciate if you can add an example with a special conditional filter form.
example:

in the addview, there are fieldA and fieldB. If the contents of fieldA is the string 'other' then unhide the fieldB, otherwise hide fieldB for input.

do I have to use "edit_form_query_rel_fields" with an sql query? ..I don't know..

**Comment by dpgaspar** [comment]
Hi @vincenzodesanctis 

This time I guess you have to develop this kind of solution yourself. I can't predict every kind of feature.

Study carefully the templates chapter on the docs: http://flask-appbuilder.readthedocs.io/en/latest/templates.html

You would need to create your own template and widget, and probably use some JS to develop your use-case.

**Comment by vincenzodesanctis** [comment]
Thank you again for your suggestion.

**Comment by dpgaspar** [comment]
No prob, good luck
