### ISSUE TITLE
Please tag releases going forward!

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#346]
I'm seeing that 1.8.1 is out, but I don't know a way to understand what is in there. It should be easy to simply `git tag 1.8.1` as you bump the version in `setup.py`. 

A changelog would be great as well. I use an npm package named `github-changes`that auto generates a `CHANGELOG.md` and it works well for me.

**Comment by dpgaspar** [comment]
Your right i should be using tag for mark versions and not branches

I'm manually updating https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/versions.rst with changes

I'll look into github-changes, Thanks!

**Comment by mistercrunch** [comment]
Oh I had not looked at the branches, works for me too. Oh and I was looking for CHANGELOG.* but version.rst works as well, I just didn't look long enough...
