### ISSUE TITLE
How to set timeout expiration session on FAB?

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#347]
A very interesting feature could be adding auto logout after time expiration, for example after 5minutes.
I'm trying to find the solution but at the moment without success.
The file session.py might contain something interesting:
```

def _make_timedelta(value):
    if not isinstance(value, timedelta):
        return timedelta(seconds=value)
    return value

permanent_session_lifetime = ConfigAttribute('PERMANENT_SESSION_LIFETIME',
        get_converter=_make_timedelta)
```

If you know how to do, please share. Thanks

**Comment by dpgaspar** [comment]
Take a look at: https://flask-login.readthedocs.io/en/latest/#cookie-settings

**Comment by vincenzodesanctis** [comment]
This should be the correct way in Flask:

```
from datetime import timedelta
from flask import session, app

@app.before_request
def make_session_permanent():
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=5)
```

but, howto in fab?

**Comment by vincenzodesanctis** [comment]
I tried in every way, but still doesn't work. Suggestions are welcome

**Comment by Praveenkarsana** [comment]
did you get the answer. please reply me.
