### ISSUE TITLE
handle multiple relationship (more than 2) with select2 using add_form_extra_fields

### ISSUE THREAD

**Issue by vincenzodesanctis** [dpgaspar/Flask-AppBuilder#353]
dpgaspar: reading the FAB documentation about select2 on Form section, you say "if you have two (or more) relationships that are related them self’s, like a group and subgroup on a contact, when the user selects the group the second select2 combo will be populated with the subgroup values that belong to the group....widget: Use Select2AJAXWidget (for the master) and Select2SlaveAJAXWidget for the slave..."  
My question is: if you have more relationship (for example three relationships) like contact_group, gender and contact_sub_group, is it possibile to handle the form?
If yes, who is the master and who is the slave? Now we have three elements, not two.

The target is to filter contact_sub_group based on contact_group and gender

your example:

```
add_form_extra_fields = {
                    'contact_group': AJAXSelectField('contact_group',
                    description='This will be populated with AJAX',
                    datamodel=datamodel,
                    col_name='contact_group',
                    widget=Select2AJAXWidget(endpoint='/contactmodelview/api/column/add/contact_group')),

                    'contact_sub_group': AJAXSelectField('Extra Field2',
                    description='Extra Field description',
                    datamodel=datamodel,
                    col_name='contact_sub_group',
                    widget=Select2SlaveAJAXWidget(master_id='contact_group',
                    endpoint='/contactmodelview/api/column/add/contact_sub_group?_flt_0_contact_group_id={{ID}}'))
                    }
```

my example that doesn't work

```
add_form_extra_fields = {
                    'contact_group': AJAXSelectField('contact_group',
                    description='This will be populated with AJAX',
                    datamodel=datamodel,
                    col_name='contact_group',
                    widget=Select2AJAXWidget(endpoint='/contactmodelview/api/column/add/contact_group')),

                    'contact_sub_group': AJAXSelectField('Extra Field2',
                    description='Extra Field description',
                    datamodel=datamodel,
                    col_name='contact_sub_group',
                    widget=Select2SlaveAJAXWidget(master_id='contact_group',
                    endpoint='/contactmodelview/api/column/add/contact_sub_group?_flt_0_contact_group_id={{ID}}')),


                    'contact_group': AJAXSelectField('gender',
                    description='This will be populated with AJAX',
                    datamodel=datamodel,
                    col_name='gender',
                    widget=Select2AJAXWidget(endpoint='/contactmodelview/api/column/add/contact_group')),

                    'contact_sub_group': AJAXSelectField('Extra Field2',
                    description='Extra Field description',
                    datamodel=datamodel,
                    col_name='contact_sub_group',
                    widget=Select2SlaveAJAXWidget(master_id='contact_group',
                    endpoint='/contactmodelview/api/column/add/contact_sub_group?_flt_0_gender_id={{ID}}')),
}
```

Is it possibile to do it?

**Comment by vincenzodesanctis** [comment]
Something like this:
```

class Select2AJAXWidget(object):

class Select2SlaveAJAXWidget(object):

class Select2SubSlaveAJAXWidget(object):
```

**Comment by dpgaspar** [comment]
Sorry for the late reply. I'll try to find time to run some tests this week

**Comment by vincenzodesanctis** [comment]
Thank you!!!
Il 11/lug/2016 13:02, "Daniel Vaz Gaspar" <notifications@github.com> ha
scritto:

**Comment by vincenzodesanctis** [comment]
I'm tring to understand how to do the multiple relations, but it's difficult...

**Comment by vincenzodesanctis** [comment]
Hi Daniel, did you find time the check if is possible to make a multiple relation on flask-appbuilder?
It will be very useful for me. Thank you

**Comment by vincenzodesanctis** [comment]
Hi Daniel, Since 2 months I have not seen your messages or answers in any posts. 
Are you OK?

**Comment by vincenzodesanctis** [comment]
Hi Daniel, how are you? is everything ok?  
it's long time since your last reply.... are you well? :+1:

**Comment by vincenzodesanctis** [comment]
Hi Daniel, I see that this issue I opened on 2 Jul 2016 is not yet closed.
Do you think to take a look at it in the next days of 2017? thank you

**Comment by vincenzodesanctis** [comment]
I see that this improvement is still in pending status, did you try to make some experimentation to complete it? it's very useful for my opinion.

**Comment by JohnElyson** [comment]
Trollou.
