### ISSUE TITLE
encrypting / decrypting password

### ISSUE THREAD

**Issue by yonelly** [dpgaspar/Flask-AppBuilder#359]
Hi, I have some passwords that I do not want to keep as plain text on mysql db. I was wondering if there was a way to implement setter and getter decorators to the model to encrypt and decrypt  the password in motion.

**Comment by vincenzodesanctis** [comment]
Try this:

> class HasPassword(object):
>     password = Column(Password)
> 
>     @validates('password')
>     def _validate_password(self, key, password):
>         return getattr(type(self), key).type.validator(password)
> 
> class User(HasPassword, Base):
>     __tablename__ = 'user'
>     id = Column(Integer, primary_key=True)
>     name = Column(Text)
> 
> class ProtectedFile(HasPassword, Base):
>     __tablename__ = 'protected_file'
>     id = Column(Integer, primary_key=True)
>     filename = Column(Text)
