### ISSUE TITLE
Google charts behind a proxy server

### ISSUE THREAD

**Issue by GregSilverman** [dpgaspar/Flask-AppBuilder#361]
We're unable to run charts behind a proxy server. Attached is an image of the error: 
<img width="1196" alt="screen shot 2016-07-27 at 9 34 14 pm" src="https://cloud.githubusercontent.com/assets/1007034/17199630/dcf1ea8a-5443-11e6-97b0-97355a9e4d84.png">

I Googled this error and, as I suspected, there is a call to google.com for the API. Unfortunately, we more than likely cannot open up access to google.com from this host, due to dealing with security restrictions surrounding patient specific data (PHI/PII). Is there any workaround to this that you can think of?

This works fine otherwise, if not behind a proxy server.

Thanks!

**Comment by GregSilverman** [comment]
If this is as simple as copying over some javascript and pointing to a local file instead of  Google, that would be great, but I'm not sure what and where needs tweaking to do this. Or, if there is an Google API call that would be a PITA to deal with.

**Comment by vincenzodesanctis** [comment]
The proxy server must allow the requests fetching http://www.google.com/jsapi and further requests for javascript code from Google's servers to pass freely without caching.

Perhaps your proxy is simply misconfigured?

**Comment by GregSilverman** [comment]
The issue is that we cannot add this url to the proxy server, due to security concerns. In any case, we found a solution by putting access to this app in a less restrictive environment that is in routable, but very restrictive, space.
