### ISSUE TITLE
Update jQuery for security fix

### ISSUE THREAD

**Issue by bobziuchkovski** [dpgaspar/Flask-AppBuilder#380]
We're using Caravel, which in turn depends on Flask-AppBuilder.

Unfortunately, a third party security audit flagged Flask-AppBuilder's bundled jquery version as unsafe due to known vulnerabilities.

I've reviewed the jquery 1.x release notes and I believe the audit was referring to the minifier bug in uglify-js detailed [here](https://diracdeltas.github.io/blog/backdooring-js/).  This was fixed in jquery 1.12 when they [updated the version of grunt-contrib-uglify](https://github.com/jquery/jquery/commit/835e9218beef8f0c559da314fac01cb85dacb740).

Anyway, would you be open to either updating the bundled jquery version to the latest 1.x release or accepting a PR that makes that update?

**Comment by gtoonstra** [comment]
Any further news on this?  With a more recent release, the version of jquery has not yet been updated.

**Comment by hodigy** [comment]
My basic tests shows that the framework it working OK with jQuery v3.3.1, so updating should be simple. Current jquery version is vulnerable: https://snyk.io/vuln/npm:jquery

**Comment by dpgaspar** [comment]
Ok, thks, will reopen this one

**Comment by tzengwei** [comment]
ab_actions.js ：Breaking change: Deprecated .size() removed.
.size() is deprecated as of jQuery 1.8 and removed in jQuery 3.0 in favor of the .length property.

**Comment by tzengwei** [comment]
> My basic tests shows that the framework is working OK with jQuery v3.3.1, so updating should be simple. Currently bundled jquery version is vulnerable: https://snyk.io/vuln/npm:jquery

in FAB examples/basefilter :
jquery-latest.js:2 Uncaught Error: Syntax error, unrecognized expression: a[href=#ContactModelView].
at HTMLDocument.<anonymous> (ab_keep_tab.js:17)

    //go to the latest tab, if it exists:
    var lastTab = localStorage.getItem('lastTab');
    if (lastTab) {
        $('a[href=' + lastTab + ']').tab('show');   <---error   (ab_keep_tab.js:17)

**Comment by CameronNemo** [comment]
bump

**Comment by CameronNemo** [comment]
Perhaps it would be wise to use the [migrate plugin](https://jquery.com/download/#jquery-migrate-plugin) to identify any compatibility issues.
