### ISSUE TITLE
Online Demo is Down

### ISSUE THREAD

**Issue by ninmesara** [dpgaspar/Flask-AppBuilder#386]
The online demo running on PythonAnywhere is down.

**Comment by dpgaspar** [comment]
Looks like their free hosting has changed. It's online now, i'll probably have to migrate to another solution. Do you recommend any?

**Comment by ninmesara** [comment]
[Openshift](https://www.openshift.com) is great. That's what I use to host my flog demo. You can host 3 apps for free there.
