### ISSUE TITLE
REST API - CSRF error on update and create methods

### ISSUE THREAD

**Issue by ninmesara** [dpgaspar/Flask-AppBuilder#387]
I'm getting a 400 error (bad request) on the `api/update/<pk>` and `api/create` entry points when using the [requests](http://docs.python-requests.org/en/master/) library. The response text is:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>CSRF token missing or incorrect.</p>\n`

I'm doing something like:

``` python
import requests

session = requests.session()
# Access to a custom route to authenticate the client
# I had to write a custom route for this purpose to bypass CSRF issues
session.get(auth_url, json={"username": username, "password": password})
# Access the URL
session.put(base_url + 'api/update/{}'.format(pk), data={"field": field_value)
```

I don't understand much CRSF tokens, but it seems that since these entry points perform form validation, they're complaining due to the lack of CSRF token. Is this something I'm doing wrong?
There are no tests for the REST api in F.A.B's repository, so I can't really see if I'm doing anything wrong.

**Comment by Bengreen** [comment]
I was looking at similar sort things for within AJAX calls.

I found that you need first to get a CRSF token from the server then include the CSRF with name 'csrf_token' token within your PUT call as an additional data field (e.g. inside your JSON PUT). Flask may be able to take the CSRF from the HTTP header, but my understanding is that FAB does not use that mechanism (I may be wrong... If you find contrary please let me know).

For getting the CSRF token in the first place i had to get the server to send it to me from a logged in page.  E.g. sending a template with something like this within it `<meta property="csrf-token" name="csrf-token" content="{{ csrf_token() }}">`
Then to provide csrf_token function into the template render function using something like this (where angst.html contains the 'csrf_token()' method above:
```
class AngTest(BaseView):
    default_view = 'angtest'

    route_base = "/ang"

    @expose('/angtest.html')
    @has_access
    def angtest(self):
        return self.render_template('angtest.html', csrf_token=generate_csrf)
```

Would love to hear if you find a better method !

**Comment by mistercrunch** [comment]
In my case my template didn't have `csrf_token` in its context somehow since I'm not inheriting from a FAB template. I was able to do this:
```
from flask_wtf import FlaskForm
ff = FlaskForm()
 ...
return self.render_template(
    'superset/sqllab.html',
    csrf_token=ff.csrf_token,
 )
```
and squeeze a `{{ csrf_token() }}` somewhere in my template.

In my javascript I pick it up with jQuery: `$('input#csrf_token').val()`

**Comment by jkornblum** [comment]
I know this issue has been closed but for anyone new landing here.
Flask-WTF is a requirement of this project, you can do the following to exempt from csrf check.
You can exempt routes or entire blueprints.

```python
from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect()

# exempt a route explicity
class ExampleApi(BaseApi):
    resource_name = 'example'

    @expose('/greeting')
    @csrf.exempt
    def greeting(self):
        return self.response(200, message="Hello")

# can also exempt all routes in blueprint, each "view" / "api" registers its own flask blueprint
# AFTER it's added to appbuilder like `appbuilder.add_api(ExampleApi)`

class ExampleApi(BaseApi):
    resource_name = 'example'

    @expose('/greeting')
    def greeting(self):
        return self.response(200, message="Hello")

my_api = ExampleApi()
appbuilder.add_api(my_api)
csrf.exempt(my_api)
```
