### ISSUE TITLE
FaskApp login with LDAP auth always needs the clear txt auth_ldap_bind_user or full DN name with the username

### ISSUE THREAD

**Issue by kennyzli** [dpgaspar/Flask-AppBuilder#390]
code line
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L572
the logic seems like trying to check the auth_ldap_bind_user first to search for the user, otherwise, it is going to use the inputed username/pwd to bind the LDAP this will throw out the error like "LDAP Error invalid DN" error because the ldap.bind_s method need the user name to be full qualified domain name like "cn=kenny.li, dc=example, dc=com" rather than just kenny.li. This makes the code could only work when deploment don't want to provide clear indirect binding password or first time login user don't want to provide full dn names.  but when we build UI, it might don't make sense to ask user to give the full LDAP path as user input

**Comment by kaiosama** [comment]
Any updates on this? I am facing the same problem, it doesn't work if I just use the following configuration:
```
AUTH_TYPE = 2
AUTH_USER_REGISTRATION = False
AUTH_LDAP_SERVER = "ldap://myserver.com"
```

It throws a '"invalid DN" error.

**Comment by alex-sousa** [comment]
Is there a fix to this?
My openldap server doesn't require bind user, but I can't login if I don't set one..
