### ISSUE TITLE
Offering help managing this project

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#399]
Hey @dpgaspar !

We love Flask AppBuilder at Airbnb and are committed this framework for Caravel (now renamed Superset) as well as a few other small internal applications, and would love to help managing and growing this project.

We'd like to offer helping managing the project, reviewing PRs, growing the set of unit test and automation, and helping with releases to as needed.

What do you think?

**Comment by dpgaspar** [comment]
Hi,

That would be great! unfortunately lately i have no time to help everyone and push flask-appbuilder forward.

How can we proceed with this?

**Comment by mistercrunch** [comment]
As the project owner you should define the rules! Maybe write a short manifest of what it means to be a committer on FAB, for example what sort of changes require your approval. Once we're in sync about rules you could grant me more rights on the repo to allow me to merge things.

Examples of rules can be:
* anything that breaks any sort of backwards compatibility require your approval
* anything "structural" that touch the architecture of the project require your approval
* release process should be done a certain way
* Any PR requires one approval from a trusted committer
* You need to approve who is a trusted committer
* You have full right to change the rules of collaboration at anytime
* You have the full right to "demote" anyone at any time, to revert any PR
* ...

We can commit to follow all of your rules and to do our best. We won't guarantee to spend huge efforts outside of what we care about for our own sake, but we care about the health of the project so that means we'll most likely do things like communicate on issues, review and merge PRs, improve test coverage and continuous integration, ...

We may need a bit more attention from you as we ramp up, but ultimately you decide how involved you want to be.

**Comment by MichaelPereira** [comment]
I agree with the proposal of adding more committers. While everyone is very thankful for all the work that went into FAB, the user base seems to keep growing and the list of issues and PRs just keeps growing without being addressed. 

Since the open-source Caravel/Superset project seems to be the biggest user of FAB, I trust that they will help maintain the project in the interest of the community.

**Comment by mistercrunch** [comment]
We've been considering forking too, in this option you could follow our progress more passively and eventually decide to merge in some or all of the stuff from the fork.

I really think it's better for the community if we can collaborate in this one spot here though.

**Comment by MichaelPereira** [comment]
Yeah, we also nearly came to that on our end, but we managed to disable the automatic database creation by overriding the `create_db()` method from our override of `flask_appbuilder.security.sqla.manager.SecurityManager`

I agree that the fork should be the last resort, please consider giving the project a second life by allowing the community to carry it @dpgaspar, sería uma grande ajúda!

**Comment by dpgaspar** [comment]
Sorry for the delayed answer, let's start our collaboration by discussing together the initial rules:

(let's start from @mistercrunch proposal)

- Anything that breaks any sort of backwards compatibility requires @dpgaspar approval. 
  - How is this approval process on github? These PR are tagged with "breaking feature" or something, and i would merge them or not?
-  Anything "structural" change that touch the architecture of the project require @dpgaspar approval.
  - How is this approval process on github? These PR are tagged with "architecture change" or something, and i would merge them or not?
- Release process - Ready to go releases are tagged, you can notify me (email?) we agree on a release date and i'll publish it on PyPi.
- @dpgaspar approves who is a trusted committer.
- @dpgaspar has full right to change the rules of collaboration at anytime.
- @dpgaspar has full right to "demote" anyone at any time.
- No 'direct' commits are allowed on master branch. Changes are submitted by PR.
- PR guidelines, we can adopt 'superset' definition on CONTRIBUTING.md.

@mistercrunch I've already added you has a trusted collaborator. Once more thanks you for your help on this, it is really appreciated.

**Comment by mistercrunch** [comment]
Awesome, I'll be very careful here and will ask for guidance only where/when necessary.
