### ISSUE TITLE
run under uwsgi?

### ISSUE THREAD

**Issue by gitrad** [dpgaspar/Flask-AppBuilder#4]
it's easy to run flask mini app (single file) under uwsgi directly (without a web server),
and i run FAB Skeleton app in virtualenv easily with python, but when issue:
[venv]# uwsgi --http :8080 --wsgi-file ./fab-skeleton/run.py --callable app
i get error:

---

ImportError: No module named app
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "./fab-skeleton/run.py", line 1, in <module>
    from app import app
ImportError: No module named app
unable to load app 0 (mountpoint='') (callable not found or import error)

---

it is with many flask-based web apps there on the web.
what's the problem?

**Comment by GregSilverman** [comment]
Hi there! I am fighting with this configuration on a Mac and unable to get it working. Any chance of sharing a working recipe? I have other Flask apps working just fine in uWSGI/Nginx, but this one is presenting itself to be quite a challenge. Thanks in advance!

**Comment by GregSilverman** [comment]
I guess I should be more clear. I am able to get my app working on port 8080, but not on port 80. Other Flask apps run just fine on port 80.

**Comment by GregSilverman** [comment]
If you want, I can open a new issue.

**Comment by GregSilverman** [comment]
Never mind, I ran the following uwsgi command in my flask-appbuilder directory:  uwsgi  -s /tmp/uwsgi.sock -H ./venv/ --chmod-socket=666 --wsgi-file myproject/wsgi.py and all is working on port 80.
