### ISSUE TITLE
EmbeddedDocument

### ISSUE THREAD

**Issue by trblft** [dpgaspar/Flask-AppBuilder#400]
Hi,
It's a wonderful idea. I tried to import one of my flask projects and it almost worked. It looks like the "lib.html" can't handle EmbeddedDocumentField from MongoEngine, I get the error `jinja2.exceptions.UndefinedError

jinja2.exceptions.UndefinedError: 'None' has no attribute 'label'
`
Is it a bug or a "missing" feature compared to Flask-Admin?

Here is the model : 
`
class Analysis(EmbeddedDocument):
    translit = StringField(null=True)
    maingramcat = StringField()

class Lemme(Document):
    identifier = StringField(max_length=16, required=True)
    analysis = EmbeddedDocumentField(Analysis)
`

The same code gives embedded form in Flask-Admin. I'd really like to implement this if it doesn't exist, how can I do? Do I have to hack the lib.html template?

Anyway thanks a lot for this wonderful app builder for MongoEngine.

**Comment by masrayie** [comment]
i have a case like this, how can it solve ? because i want to use embedded document too, thankyou
