### ISSUE TITLE
Multiple ModelView in same page

### ISSUE THREAD

**Issue by freemanpolys** [dpgaspar/Flask-AppBuilder#405]
Hi,

How can I display more than one ModelView which are non related in the same page ?

Regards,

**Comment by MichaelPereira** [comment]
You can use the [MultipleView](http://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html#extra-views) view for this specific case

**Comment by freemanpolys** [comment]
Tks. Do you know how to use a custom template to display it ?
