### ISSUE TITLE
Mass delete

### ISSUE THREAD

**Issue by philliproso** [dpgaspar/Flask-AppBuilder#41]
What would be the current easiest way to support mass delete

**Comment by vincenzodesanctis** [comment]
I added your excel @action  but this is the result IOError: [Errno 2] No such file or directory: '/flask/Flask-AppBuilder-master/examples/dekidaka/app/download_template.xlsx'

**Comment by vincenzodesanctis** [comment]
I improved the  @action adding BytesIO(), so the xlsx will not be saved on the server:

`   @action("Excel Download", "Download xlsx", "Procedi con il download", 'fa-file-excel-o')`
     `def excel_dl(self, items):`
`        output = BytesIO()`
`        list_items=list()`
 `       for item in items:`
   `         row=dict()`
   `        for col in self.datamodel.get_user_columns_list():`
       `         row[col]=str(getattr(item,col))`
       `    list_items.append(row)`

   `     df = pd.DataFrame(list_items)`

 `       #write to excel`
     `   writer = pd.ExcelWriter(output, engine='xlsxwriter')`
     `   df.to_excel(writer,'data', index=False)`
 `      writer.save()`
     `   output.seek(0)`
`        return send_file(output,`
             `            attachment_filename='dekidaka.xlsx',`
                      `   as_attachment=True)`

**Comment by dpgaspar** [comment]
Great, thanks for sharing again, are you willing to submit a PR with a simple example on the ./examples folder?

**Comment by zhangatao** [comment]
@philliproso 
Hello, thank you very much for sharing the code. Now I have a question. Can you share the details about the send_file function?

**Comment by tserafim** [comment]
@zhangatao http://flask.pocoo.org/docs/1.0/api/#flask.send_file
