### ISSUE TITLE
Rest API authorization

### ISSUE THREAD

**Issue by perpetum** [dpgaspar/Flask-AppBuilder#410]
Hi, currently I'm trying to insert new record into database through FABs REST  /api/create (base crud view) method.
If I set username into Public role, everything goes well, but if I set username other than Public, I've got an 401 error. I use basic http authentication in order to authenticate user. Can you please tell me, what I am do wrong, and what kind of authentication is supported to insert data through rest API

**Comment by dpgaspar** [comment]
Hi perpetum,

The REST api currently does not support basic http authentication. Have you tried using a cookie to mimic a normal user session?
