### ISSUE TITLE
redirection to original url after login (Superset)

### ISSUE THREAD

**Issue by iaperez** [dpgaspar/Flask-AppBuilder#412]
Is there anyway to redirect a user to the original url? 
I'm dealing with a situation like:

1. user is not logged in
2. user tries to access <host>/superset/dashboard/misc_charts/?extrafiltersandparams
3. user is redirected to the login form,
4. after entering his credentials, user is redirected to <host>/superset/dashboard/misc_charts/?extrafiltersandparams

I saw that the OID plugin has  #some of this, by using the next param in the url, but it is redirecting to the login page, not the original one.

any thoughts?

**Comment by willgroves** [comment]
I patched FAB and Superset (aka Caravel) to redirect successfully. Unfortunately my solution requires changes in both projects. 1) in Superset, the view must embed the intent ("next") path in the request_access url. 2) in FAB, the has_access method must also pass the intent to the login request. 3) in FAB, the '/login/' endpoint needs to redirect to the intent path.

in views.py of Superset:
```
class Superset(BaseSupersetView):
                 flash(
                     __(get_datasource_access_error_msg(datasource.name)),
                     "danger")
+                localpath = request.path
+                localmessages = request.args.get('messages',{})
+                return redirect(url_for("Superset.request_access", dashboard_id=str(dash.id), next=localpath))

```

in flask_appbuilder/security/decorators.py:
```
@@ -27,7 +27,8 @@ def has_access(f):
         else:
             log.warning(LOGMSG_ERR_SEC_ACCESS_DENIED.format(permission_str, self.__class__.__name__))
             flash(as_unicode(FLAMSG_ERR_SEC_ACCESS_DENIED), "danger")
-        return redirect(url_for(self.appbuilder.sm.auth_view.__class__.__name__ + ".login"))
+        print("path requested is this: ", request.path)
+        return redirect(url_for(self.appbuilder.sm.auth_view.__class__.__name__ + ".login", next=request.args.get('next','')))
```

in flask_appbuilder/security/views.py:
```
class AuthDBView(AuthView):
...
    @expose('/login/', methods=['GET', 'POST'])
    def login(self):
...
+        intent = request.args.get('next','')
+        if len(intent) > 0:
+	    return redirect(intent)

Any thoughts on a more minimal solution?

**Comment by iaperez** [comment]
I think this can help, although it has some problems like the session management, the flask_appbuilder/security/has_access duplication, and it is  very targeted on dashboards and welcome. However, it requires patching only superset. 

Essentially I wrote two decorators, remember_target_url and check_target_url, and it is using the session to store the target url.

in  superset/views.py:
```python
...
+ from superset.remember_url import remember_target_url, check_target_url
...
+   @remember_target_url
    @has_access
    @expose("/dashboard/<dashboard_id>/")
...
+   @check_target_url
    @expose("/welcome")
...
```
this is the new remember_url.py
```python
from flask_appbuilder.const import PERMISSION_PREFIX
import functools
from flask import request, url_for, redirect, session


def remember_target_url(f):
    if hasattr(f, '_permission_name'):
        permission_str = f._permission_name
    else:
        permission_str = f.__name__

    def wraps(self, *args, **kwargs):
        permission_str = PERMISSION_PREFIX + f._permission_name
        check = self.appbuilder.sm.has_access(permission_str, self.__class__.__name__)
        if check:
            if 'target_url' in session:
                session['target_url'] = ''
                session.pop('target_url')
            return f(self, *args, **kwargs)
        else:
            session['target_url'] = request.url
            return redirect(url_for(self.appbuilder.sm.auth_view.__class__.__name__ + ".login"))

    f._permission_name = permission_str
    return functools.update_wrapper(wraps, f)


def check_target_url(f):
    def wraps(self, *args, **kwargs):
        if 'target_url' in session:
            if session['target_url'] != '':
                url = session['target_url']
                session.pop('target_url')
                return redirect(url)
        return f(self, *args, **kwargs)

    return functools.update_wrapper(wraps, f)
```

**Comment by rpwils** [comment]
@iaperez @willgroves @xrmx 

why not just add update the has_access in appbuilder to the following where it checks if the user is logged in else it adds the requested url to the session and redirects to login. Then in the AuthViews we can check for that in the session (and set to null)

def has_access(f):
    """
        Use this decorator to enable granular security permissions to your
        methods. Permissions will be associated to a role, and roles are
        associated to users.

        By default the permission's name is the methods name.

        Forked from the flask_appbuilder.security.decorators
        TODO(bkyryliuk): contribute it back to FAB
    """
    if hasattr(f, '_permission_name'):
        permission_str = f._permission_name
    else:
        permission_str = f.__name__

    def wraps(self, *args, **kwargs):

        val = request.args.get('next')
        print(val)

        permission_str = PERMISSION_PREFIX + f._permission_name
         
        if self.appbuilder.sm.has_access(permission_str,
                                             self.__class__.__name__):
            return f(self, *args, **kwargs)
            
        elif not current_user.is_authenticated():
            session["requested_url"] = request.path
            return redirect(
            url_for(self.appbuilder.sm.auth_view.__class__.__name__ + '.login'))

        else:
            logging.warning(
                    LOGMSG_ERR_SEC_ACCESS_DENIED.format(permission_str,
                                                        self.__class__.__name__))
            flash(as_unicode(FLAMSG_ERR_SEC_ACCESS_DENIED), 'danger')
            
        # adds next arg to forward to the original path once user is logged in.
        return redirect(
            url_for(
                self.appbuilder.sm.auth_view.__class__.__name__ + '.login',
                next=request.path))

    f._permission_name = permission_str
    return functools.update_wrapper(wraps, f)
