### ISSUE TITLE
one to many examples?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#414]
Hi Daniel,

Do you have any one to many examples? Thanks

Seb

**Comment by MichaelPereira** [comment]
Hi Sebastian,

What exactly are you looking for related to one-to-many ? It should all boil down to SQL Alchemy models (http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html) and you can also look at the models of the project itself to see how they are implemented (https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/sqla/models.py)

**Comment by scheung38** [comment]
the employee labels from my memory can't be overridden correct? Unless you define your own template/index.html pages?

**Comment by tserafim** [comment]
> the employee labels from my memory can't be overridden correct?

@scheung38 can you elaborate on this? what do you mean by 'employee labels'?

And to repeat @MichaelPereira, what exactly are you looking for?
