### ISSUE TITLE
Change of port has no effect?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#417]
app.run(host='0.0.0.0', port=9999, debug=True)

But the output is still being served at localhost:8080?

**Comment by bb78657** [comment]
in cli.py:
def runserver(debug, address, port, timeout, workers):
if debug:
        app.run(
            host='0.0.0.0',
            port=5000,
            threaded=True,
            debug=True)
    else:
        ...
this works for me if you are setting debug to true in config and running the app throulg cli.py runserver

**Comment by PhE** [comment]
fabmanager does not call your *run.py* file.

So any changes you made to *run.py* will be ignored.

Instead of running your server with :
```fabmanager run``` 
do :
```python run.py ```
