### ISSUE TITLE
How to deploy to Heroku?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#420]
After making an example and trying to deploy to Heroku, it reported Success, but then upon launching it is saying 503 error, so do I need ProcFile and mongodB configured?

**Comment by dbill23** [comment]
I'm having the same issue deploying to Heroku. Did you manage to figure this out?

**Comment by bzreinhardt** [comment]
I'm running into cascading errors deploying to Heroku 

`ERROR:flask_appbuilder.security.sqla.manager:Add Permission to Role Error: (raised as a result of Query-invoked autoflush; `
