### ISSUE TITLE
fabmanager admin - ExtDeprecationWarning Grateful for help!

### ISSUE THREAD

**Issue by jerryhall** [dpgaspar/Flask-AppBuilder#421]
I've followed the Superset docs at http://airbnb.io/superset/installation.html but, am hung at creating the fabmanager admin. This is the entire dialog:

[ec2-user@ip-10-0-2-39 ~]$ **fabmanager create-admin --app superset**  
/home/ec2-user/.pyenv/versions/3.4.6/lib/python3.4/importlib/_bootstrap.py:1161:   ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.  
  spec.loader.load_module(spec.name)  
Username [admin]: admin  
User first name [admin]: admin  
User last name [user]: admin  
Email [admin@fab.org]: email@email.com  
Password:  
Repeat for confirmation:  
/home/ec2-user/.pyenv/versions/3.4.6/lib/python3.4/importlib/_bootstrap.py:1161:   ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.  
  spec.loader.load_module(spec.name)  
**Was unable to import superset Error: No module named 'pysqlite2'**  

I tried to see if I could take the next step in 'superset db upgrade' without an account and got a host of errors including 'ImportError: No module named '_sqlite3'. But, I do in fact see the sqlite3 package in my python 3.4 install dir shown above.

I have python 27 and 34 using pyenv, installed on my aws/centos6. 

Any help you can give would be greatly appreciated. I have a really fantastic use case for Superset and see long term opportunities to contribute.

**Comment by AIHELP-NET** [comment]
I have just the same problem, centos 6.9 with default python version 2.6, I changed python to 3.6  with the direction from http://blog.csdn.net/hobohero/article/details/54381475

**Comment by AIHELP-NET** [comment]
(venv) [root@s9-dal10 sasl-0.2.1]# fabmanager create-admin --app superset
Username [admin]: aihelp
User first name [admin]: aihelp
User last name [user]: aihelp
Email [admin@fab.org]: caochenghua@aihelp.net
Password: 
Repeat for confirmation: 
Error: the two entered values do not match
Password: 
Repeat for confirmation: 
Was unable to import superset Error: No module named 'pysqlite2'
(venv) [root@s9-dal10 sasl-0.2.1]# python
Python 3.6.0 (default, Sep  8 2017, 06:48:44) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(venv) [root@s9-dal10 sasl-0.2.1]# yum -y install sqlite-devel
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * epel: fedora-epel.mirror.lstn.net
Package sqlite-devel-3.6.20-1.el6_7.2.x86_64 already installed and latest version
Nothing to do
(venv) [root@s9-dal10 sasl-0.2.1]# uname -a
Linux s9-dal10.chuangtech.com 2.6.32-642.13.2.el6.x86_64 #1 SMP Thu Feb 23 02:55:00 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eliza-jane** [comment]
It's interesting that you are able to get a response in the terminal after entering the information. I stay hung after I enter the password and hit enter. No warnings or anything. However, I am attempting to get this to work on a company Windows machine (running 2007--yikes). Even though I am doing this on a Cygwin terminal, and thus am using a UNIX shell, I imagine this work environment is part of the issue? Thoughts would be great! Would love to get this up and running.

(As an aside, I am using Python 3.6. I will update this post when I am able to try this in my personal dev environment.)

**Comment by AnnePan** [comment]
i used flask-appbuilder created an Application and i changed the default file 'app' to an other name,  now run 'fabmanager run', then i got a error:"Was unable to import app Error: No module named app",i mast change name 'app' to other name, what can i do? very thanks if you can help me!
