### ISSUE TITLE
Connect to LDAP with a ca_cert file

### ISSUE THREAD

**Issue by gallamine** [dpgaspar/Flask-AppBuilder#427]
I am trying to add LDAP login support to FAB application (Superset). My LDAP requires encryption and I need to be able to specify the cert file in the config. I'm not finding anything about this in FAB.
Any thoughts? An example would be how ldap3 uses the ca_cert file in the TLS encryption: http://ldap3.readthedocs.io/ssltls.html#the-tls-object

**Comment by gallamine** [comment]
I looks like the BaseSecurityManager would need to be changed here (https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L579) to add in this functionality. I tried doing this myself by ran into issues where the `ldap` package wouldn't let me run a query like:

```
>>> ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, "/path/to/certfile/star_distil_it.ca")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/william/anaconda/envs/superset/lib/python2.7/site-packages/ldap/functions.py", line 135, in set_option
    return _ldap_function_call(None,_ldap.set_option,option,invalue)
  File "/Users/william/anaconda/envs/superset/lib/python2.7/site-packages/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
ValueError: option error
```

It would be preferable to use `ldap3` as it has Python3 support. Here is an example from the Airflow project: https://github.com/apache/incubator-airflow/blob/794540f9591cf6e3b7e182d0e2a26ddd14cc1f92/airflow/contrib/auth/backends/ldap_auth.py#L52

I guess another option would be to add in another LDAP auth mechanism that used `ldap3` instead of `ldap`. How would one go about doing this?

**Comment by MaheshSankaran** [comment]
Am also trying the same. Is there any update regarding this issue?
