### ISSUE TITLE
Prefill form values with GET (or POST) HTTP data parameters

### ISSUE THREAD

**Issue by calve** [dpgaspar/Flask-AppBuilder#439]
Hi there, 

I'm looking for a way to show users a form (namely, the `add` form from a `ModelView`) with some value prefilled. Ideally, I would like to fill the form with data fetched from GET (or POST) params, as show below.

![spectacle sm4542](https://cloud.githubusercontent.com/assets/4311079/23705618/ffd00114-040a-11e7-82f2-448983dc4354.png)

Specifically, I would call ``url_for()`` to generate an URL with the params pre-filled from an ``@action`` function, as in 

```
class MyView(BaseView):

     @action(...)
     def do_something(self, item):
            stuff = Stuff(message="hello world")
            return redirect(url_for('Stuff.add', stuff=stuff, message=message)
           # at this point, stuff is not inserted in database but we present a prefilled form to the user
```

Alternatively, I can create and save an instance with the values, then show the edit form, but this is not optimal as it insert an object and makes at least one extra database commit, as in

```
class MyView(BaseView):

     @action(...)
     def do_something(self, item):
            stuff = Stuff(message="hello world")
            db.session.add(stuff)
            db.session.commit()
            return redirect(url_for('Stuff.edit', pk=stuff.id)
```

I cannot find anything related in the doc, did I miss something ? Thanks in advance

**Comment by calve** [comment]
So I managed to solve this (thanks to my coworker). For reference;

```
from flask_wtf import FlaskForm
from flask import request


class MyForm(FlaskForm):
    """                                                                                                                                                                                                                             
    A custom FlaskForm which reads data from request params                                                                                                                                                                         
    """
    @classmethod
    def refresh(cls, obj=None):
        kw = dict(obj=obj)
        if request.method == 'GET':
            kw['formdata'] = request.args
        form = cls(**kw)
        return form


class MyView(ModelView):
    datamodel = SomeDataModel

    # install our very own form
    def _init_forms(self):
        super(Datapoints, self)._init_forms()
        self.add_form = type('MyForm', (MyFom, self.add_form), {})
```

Now, the form showed on `add` will be prefilled with GET params.

**Comment by MichaelPereira** [comment]
To provide another datapoint, if you don't need to configure them dynamically from the get parameters but just use default values, you can also set those in the model used as `datamodel`:
```python
class Environment(Model):
    id = Column('id', INTEGER(unsigned=True), primary_key=True)
    ...
    branch_name = Column('branch_name', String(length=256), nullable=False, default='master')
    delete_unexpected = Column(Boolean(), default=True)
```

When adding a new entry in my environments view, those fields are pre-populated already
