### ISSUE TITLE
change the default view

### ISSUE THREAD

**Issue by lordlinus** [dpgaspar/Flask-AppBuilder#442]
Thanks for making this project really easy to bootstrap flask project.
I am trying to change the default page to start at /login i.e. make login the first page and not sure how to do this. i think i need to change `get_url_for_index` but not sure how to do that

Also is it possible to change after login page depending on type of user?. e.g. is user1 is of role role1 and user2 is of role role2.
user1 url after login should be /page1 and
user2 url after login should be /page2

**Comment by MichaelPereira** [comment]
This is how we are overriding the default index view to use an index file one level above in the url path:
```python
from flask.ext.appbuilder import IndexView


class CustomIndexView(IndexView):
    index_template = 'index.html'
    route_base = '/..'

```
and it is used this way when declaring the application:
```python
appbuilder = AppBuilder(app, db.session, indexview=CustomIndexView)
```

**Comment by lordlinus** [comment]
@MichaelPereira i tried the above snippet , but that is not what i am after.
I want to change the default landing page to be the login page ( i.e. no welcome page for un-authenticated users). i have also tried to use 

i tried as below

    from flask.ext.appbuilder import IndexView
    class CustomIndexView(IndexView):
        index_template = 'index.html'
        route_base = '/login/'

but i get 404 on index page `/`

Also, tried the below

    class CustomIndexView(IndexView):
        default_view = 'index'
        def index(self):
            return redirect(url_for('login'))
i get `werkzeug.routing.BuildError: Could not build url for endpoint 'CustomIndexView.index'. Did you mean 'LocaleView.index' instead?`

**Comment by lordlinus** [comment]
I think the below works fine. But still dont know how to redirect to a specific url `after` login based on user.

     class MyIndexView(IndexView):
        index_template = 'index.html'
        @expose('/')
        def main(self):
           return redirect(url_for('AuthDBView.login'))

**Comment by lordlinus** [comment]
@dpgaspar any ideas or suggestions?

**Comment by dpgaspar** [comment]
Hi @lordlinus 

Sorry for the delayed answer, were you able to solve this one?

I have not tested it, but you can probably do all your logic inside your main method. Check if user is authenticated, if he is query and redirect, if not redirect to login.

Going to close this, feel free to reopen if it's still relevant

**Comment by MaaniBeigy** [comment]
I faced the same problem, the following steps solved my problem:

In `__init__.py` or `index.py` make `MyIndexView` class,

```python
from flask import Flask, g, redirect, url_for
from .yourmodule import app1

class MyIndexView(IndexView):
    @expose('/')
    def index(self):
        user = g.user

        if user.is_anonymous:
            return redirect(url_for('AuthDBView.login'))
        else:
            return self.render_template(
                "dash.html", dash_url=app1.url_base, appbuilder=appbuilder
            )

app = Flask(__name__)
app.config.from_object("config")
db = SQLA(app)


appbuilder = AppBuilder(app, db.session, indexview=MyIndexView)
appbuilder.add_view_no_menu(MyIndexView())
app = app1.Add_Dash(app, appbuilder)
``` 

Notice `index(self)` which is incorrectly written `main(self)` [up](https://github.com/dpgaspar/Flask-AppBuilder/issues/442#issuecomment-288851743) there. 

Do not forget `appbuilder.add_view_no_menu(MyIndexView())`.
