### ISSUE TITLE
Question: want to setup some sort of auto login?

### ISSUE THREAD

**Issue by govardhank** [dpgaspar/Flask-AppBuilder#445]
Hi ,

I am new to superset. Actually what i want is Iam developing web application using nodejs.After login into my web app , when i click a link in my application, it should redirect to superset auto login  and open dashboard page bypassing the login page in a separate window? can you please briefly explain or give me step wise instructions on how to do this.Didn't find documentation for REMOTE_USER
My mail Id: govardhan.kamle@gmail.com

Thanks & Regards,
Govardhan

**Comment by MichaelPereira** [comment]
I'm not familiar with Superset but you should make sure that the dashboard view is accessible to the Public role to allow that.

**Comment by dpgaspar** [comment]
thks @MichaelPereira, going to close this, feel free to reopen if it's still relevant or if you need further help.

**Comment by manavbagai** [comment]
@govardhank I am doing similar kind of stuff where I want to auto-login once I am authenticated on the web-app. Can you please tell how did you solve this problem.

**Comment by w2s2k** [comment]
Hi, @govardhank did you solved the problem, i have same use case, and i dont know very well how to make the authentication via flask-appBuilder.

**Comment by micimize** [comment]
Here's an example with both login and logout handled by a proxy:
https://gist.github.com/micimize/8a312ddc36f20f89517ca1828cc16383
