### ISSUE TITLE
[Question] How to create public page

### ISSUE THREAD

**Issue by songyanho** [dpgaspar/Flask-AppBuilder#446]
After some searching I still cannot find the way creating public view which one can view without login or authentication. With the public role, how could I do so that non-logged in user could view the certain page without prompt to login?

**Comment by songyanho** [comment]
I am thinking of removing @has_access but does there is other way to implement it?

**Comment by MichaelPereira** [comment]
You should be able to do it by assigning the views that you want to make public to the Public group
