### ISSUE TITLE
Overriding get_filter_args method

### ISSUE THREAD

**Issue by GregSilverman** [dpgaspar/Flask-AppBuilder#448]
I'm looking for the most general way of doing the following override to allow for defining multiple searches on the same field using the same filter type on the same model:

```
def get_filter_args(filters):
    filters.clear_filters()
    # _flt_2 -> contains
    # TODO: find general way to pass field name as param
    dx_test = request.args.getlist('_flt_2_dx_name')
    for arg in request.args:
        re_match = re.findall('_flt_(\d)_(.*)', arg)
        if re_match:
            filters.add_filter_index(re_match[0][1], int(re_match[0][0]), request.args.get(arg))
   # case where multiple dx_names in filter:
    if len(dx_test) > 1:
        for i in xrange(1, len(dx_test)):
            filters.add_filter_index('dx_name', 2, dx_test[i])
```

The above code works, but  I would like to pass a list of fields to allow for multiple filter selection, such, as in this case above, `dx_name` is allowed to have multiple 'Contains' filters. The problem with the above, is that for each new column I want to allow to have multiple filters of a particular type, this code would get messy fast. 

Thus, the desire to have something like, assuming `mult_filter = ['dx_name']`:

```
def get_filter_args(filters, multi_filter=None):
    filters.clear_filters()
    if multi_filter != None:
        for m in  multi_filter:
            multi = request.args.getlist('_flt_2_' + m)
    for arg in request.args:
        re_match = re.findall('_flt_(\d)_(.*)', arg)
        if re_match:
            filters.add_filter_index(re_match[0][1], int(re_match[0][0]), request.args.get(arg))
   # case where multiple dx_names in filter:
    if len(multi) > 1:
        for i in xrange(1, len(multi)):
            filters.add_filter_index(multi_filter[0], 2, multi[i])
```

Or something (this is not the most elegant, nor the most general, but you get the idea). I am wondering how to pass the list `multi_filter` from my views.py to be utilized by this?

**Comment by GregSilverman** [comment]
I'm thinking that this is possible by somehow tweaking the list_widget.

**Comment by dpgaspar** [comment]
Let's follow this one on #447
