### ISSUE TITLE
What is the correct syntax to pass sort order into REST read?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#450]
Hi all,
I'd like to call the REST read and have the results sorted. I found the docs but I just can't quite understand it. 
The docs say this:
Order by column:
 	`_oc_<<YOUR MODEL VIEW>=<COLUMN NAME>`

This is what I've tried:

http://localhost:8080/registrationview/api/read?_oc_registrationview=email

But that doesn't work. What's the correct way to do this?

Thanks!

**Comment by dpgaspar** [comment]
Do it like this,

?_oc_ContactModelView=name&_od_ContactModelView=asc

oc = order column
od = order direction
