### ISSUE TITLE
Using latest version. Windows 10 64 bit

### ISSUE THREAD

**Issue by TerjeMyk** [dpgaspar/Flask-AppBuilder#451]
Hi

There is something that is not correct.  I think I have followed the instruction 100 %, but I got this deprecation error:

(venv) C:\XXXX\Development\HSE\HSE>fabmanager create-admin
c:\XXXX\development\hse\venv\lib\site-packages\flask_sqlalchemy\__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \

Flask-AppBuilder looks very promising, so I really want to check it out.

Terje

**Comment by MichaelPereira** [comment]
This is not an error, just a warning, it won't prevent the application from running
