### ISSUE TITLE
Factory setup is not working

### ISSUE THREAD

**Issue by alexandrezia** [dpgaspar/Flask-AppBuilder#452]
I've been trying to implement a factory setup and there is no way I could make it work.
Even the example form here don't work:
   https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/factoryapp

RuntimeError: Working outside of request context.

**Comment by dpgaspar** [comment]
Yes i noticed, this used to work...

**Comment by dpgaspar** [comment]
Ok, I think i've nailed the bug, can you test if using branch 'update-dependencies' ?

This fix is probably going to be included on version 1.9.0

**Comment by alexandrezia** [comment]
Seems to be working, thanks
However my application broke in several parts, mostly due to the fact I was accessing 'app'
I'll have to refactor to be able to use factory
