### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jonalxh** [dpgaspar/Flask-AppBuilder#456]
Hi, I wanna know:
- There is an easy way to open a modal window on edit or create events?
- AppBuilder use bootstrap 3?
- There is an example with a vertical left menu? Is it possible?
- AppBuilder use inline Editing? It let us edit data in the list view, without going to a different form, flask-admin has it.

I am begginer and i decide using AppBuilder against Flask-Admin because I read your comparision in stack-overflow, thanks for answering. Great job. (excuse my english)

**Comment by dpgaspar** [comment]
There is an easy way to open a modal window on edit or create events?
It depends on your concept of easy ;)

AppBuilder use bootstrap 3?
Yes

There is an example with a vertical left menu? Is it possible?
Take a look at: http://flask-appbuilder.readthedocs.io/en/latest/templates.html#navigation-bar

AppBuilder use inline Editing?
Nop

No problem, Thanks!

**Comment by jonalxh** [comment]
Bit could  you explain me how to use the modal form view?

**Comment by dpgaspar** [comment]
There is no bootstrap modal view for Edit, Add or Show.

You have to do it yourself, actually you have to do the all CRUD views yourself. It should be an all in one page.
