### ISSUE TITLE
doing rest queries

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#46]
I'm trying to figure out doing REST queries to edit data and not finding a lot of documentation / examples. I can do a GET on https://localhost/contactmodelview/json to get a dump of the table in json.  But if I want to delete an entry, it seems I need to use the action option. When I try:

`http://localhost/contactmodelview/action/delete/1`

I get permission denied. Looking at the code, it seems the action needs to match a permission in the permissions table, so I tried

`http://localhost/contactmodelview/action/can_delete/1`

but that gives me an error:

```
2014-10-28 14:02:22,673:ERROR:app:Exception on /contactmodelview/action/can_delete/1 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/views.py", line 278, in action
    return action.func(self.datamodel.get(pk))
AttributeError: 'NoneType' object has no attribute 'func'
[pid: 28451|app: 0|req: 127/127] 192.168.0.178 () {52 vars in 1917 bytes} [Tue Oct 28 14:02:22 2014] GET /app/contactmodelview/action/can_delete/1 => generated 291 bytes in 213 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```

**Comment by cryptonomicon314** [comment]
I have implemented a Rest API over a F.A.B. app (a blog, source code [here](https://github.com/cryptonomicon314/flog), live demo [here](http://demo-ninmesara.rhcloud.com/category/about)). I just subclassed the BaseView class, and added some methods:

```python
class ClientApi(BaseView):
    route_base = "/client/api/v1"

    @csrf.exempt
    @has_access
    def auth(self):
        username = request.json.get('username')
        password = request.json.get('password')
        # ``appbuilder.sm`` is a ``SecurityManager``, responsible for adding
        # and authenticationg Users.
        user = appbuilder.sm.auth_user_db(username, password)
        if user:
            # Use the ``LoginManager`` to login the User.
            #
            # You login the user by adding a special cookie to
            # the session, which will be remembered by the client.
            login_user(user)
            return make_response(json.jsonify(success=True), 200)
        else:
            # If you can't authenticate the user, return a 403 error code:
            return make_response(json.jsonify(success=False), 403)

    @csrf.exempt
    @has_access
    @expose('/entry/', methods=['GET', 'PUT', 'POST', 'DELETE'])
    def entry(self):
        if method=='GET':
            ...
        if method=='DELETE':
            ....
        # etc
```

For my particular purposes, Flask-Restless wouldn't do, because I wanted to move complexity from the client to the server. The only inconvenient about using Flask-Restless with F.A.B. is that you are limited by the granularity of the permission system, which is usually not what you want in a Rest application. You want the users to be able to edit *their* entries, not all entries by a user with the same role. It would be great if F.A.B came up with a system to add this kind of granularity to database queries, but I think that as soon as you add something complex, like SQL joins the whole system falls apart.

**Comment by dpgaspar** [comment]
Hello,

I'll get to this new feature on the next version (finally). To start an initial discussion I propose something like this:

    class ApiView(BaseView):

        @has_access
        @expose('/', methods=['GET']
        def read(self):
            pass

        @has_access
        @expose('/', methods=['POST']
        def create(self):
            pass

        @has_access
        @expose('/', methods=['PUT']
        def update(self):
            pass

        @has_access
        @expose('/', methods=['DELETE']
        def delete(self):
            pass

Any thoughts

**Comment by IguanaBen** [comment]
I think it looks good, but let me make sure I'm fully understanding. Would ApiView be 'under' the ModelView. So the you would query:

http://flaskbaseURL/ModelViewName/ApiView/

Then a basic GET request would read that table (in json)? I'd like

flaskbase/ModelViewName/ApiView/56

to return the column of data with foreign key = 56. 

Also for the PUT method, as that is an update, I'm assuming the url would require the foreign key? (Ie you would do a put to flaskbase/ModelViewName/ApiView/56 to update the 56 item? Same with delete.

**Comment by dpgaspar** [comment]
Right, i would make it a subclass of BaseCRUDView or as a mixin for ModelView.
So two options:

1 - BaseCRUDView subclass, you would have an independent config, with the same properties has ModelView. You would have to independently register them with add_view_no_menu appbuilder method.
 
2 - Mixin, no need to rewrite any already defined ModelView properties, no need to register them,
security permissions could be superimposed from the ModelView.

I think that the main idea here is to support server side AJAX.

proposal update (example for mixin):

    class ApiMixIn(object):

        @expose('/', methods=['GET'])
        @has_access
        @permission_name('can_list')
        def read(self):
            pass

        @expose('/', methods=['POST'])
        @has_access
        @permission_name('can_add')
        def create(self):
            pass

        @expose('/<pk>', methods=['PUT'])
        @has_access
        @permission_name('can_edit')
        def update(self, pk):
            pass

        @has_access
        @expose('/<pk>', methods=['DELETE'])
        @permission_name('can_delete')
        def delete(self, pk):
            pass


You could use it like this:

      class GroupModelView(ModelView, APIMixIn):
          datamodel = SQLAInterface(ContactGroup)
          related_views = [ContactModelView]

**Comment by IguanaBen** [comment]
I like the MixIn approach where you don't have to register, etc. I'm also wondering if this could just be part of ModelView so you don't to have add it as a class when you create a view. Maybe there is a good reason not to expose the REST api, but I can't think of one.

**Comment by dpgaspar** [comment]
The downside is: if you want to have an app that has a user frontend that uses json, and use also an admin that uses ModelView, this way users would have access to the Admin views also.

You can't separate ModelViews from REST JSON. this could be a problem.

It's always the same problem, more possibilities more configuration.

**Comment by ben-github** [comment]
Can you explain that more? It seems like access via REST from an access/permission point of view is the same as via the regular View. An app could use the REST queries, but would have to have permission, just like a user would for the same view. I'm thinking of the REST queries just being a different but equivalent way of accessing the Views. Am I missing something?

**Comment by dpgaspar** [comment]
A vulgar use ModelView kind of view is to easily generate an admin interface for "special" users (admins, super users, backend users etc...). Next create the rest of the app more or less from scratch using plain Flask or using BaseView with tailored made templates.

Example:
- The BaseView's would be public or restricted to a general user role.
- The ModelView's would be restricted to admin role and Super User Role.

BaseViews's would "render" tailored made templates backed by db models. Developed specifically for some propose (buy products, create tickets, etc...)

One propose of a REST JSON views could be to give a more easy AJAX enabled templates to this specific views. If they are only implemented on ModelView's (the way i mentioned) they would expose the admin view also.

A user could access the URL: http://server.com/mymodel/list, 
The basic access is the same, right, if he can read JSON he could access ModelView.list. But this is a limitation (and in some perspective a security issue)

I'm just brain storming here, one could make a good defense the other way (more simple implementation, less security permission tags, etc.)

**Comment by ben-github** [comment]
Sorry, I'm still not getting it. What is the different between BaseView and ModelView? A user who can access to http://server.com/mymodel/list, has access to the data in mymodel, so he should be able to access the the REST JSON version as well (http://server.com/mymodel/rest/list) the same goes for delete, update, etc. I not seeing how this is a security issue. One could (I'm not suggesting this) rewrite all the FAB to *only* get data from the REST interface and have all the templates,etc, just be static templates that use REST and JS to make the webpage. In that case, all security is handled in the REST query. I'm not seeing why REST queries and webpage viewing isn't 1 to 1 for mapping permissions and thus adding new REST hooks shouldn't have an security implications as it is only exposing what is already exposed, just in a different form.

Maybe you can give me an example where this isn't the case (I'm oversimplifying things somehow) -- where you could want different permission for a View than for a REST query?

**Comment by dpgaspar** [comment]
Yes, it's just a view permission problem, not a data access one.

In fact i like both ideas, a simple REST class one can use exposing only the REST CRUD API URL's. and ModelView's with the REST addition.

That is (probably) possible without having to write the API twice using mixins. i'll write some code, and get back.

Another question i'm thinking about is where to "atach" the REST CRUD API:

1 - http://server/modelview/
2 - http://server/modelview/rest

Thank you all once more for your input.

**Comment by ben-github** [comment]
Cool. I think I like 2 -- clear separation between the regular url and the where the REST queries are.

**Comment by cryptonomicon314** [comment]
I also prefer number 2. This would allow you to return a JSON friendly message o a failed authentication.

**Comment by dpgaspar** [comment]
@cryptonomicon314 yes it would but i have to change some things.

Doing some tests using angularJS i really like the possibilities with rest, i think i will write an alternative widget (just like the current default widget for lists) using AngularJS and this REST service.

**Comment by ben-github** [comment]
That sounds excellent. I really like AngularJS / REST as a framework, but in the past have had to write custom REST code for each tables' CRUD and then Angular / html for each page. FAB with Angular/REST sounds incredibly powerful while still having all great things that is FAB.

**Comment by dpgaspar** [comment]
Do you see any downside if F.A.B. would use AngularJS by default with hybrid templating (Server and client side). I mean importing AngularJS by default and declaring the application (named FAB for example) on the main DIV?

**Comment by dpgaspar** [comment]
i'm building some tests on branch 2.0.0 with "quickhowto2" (as usual).

You can run it and test the link:

localhost:8080/contactmodelview2/jsonexp

It's an experiment with lists REST and AngularJS Directives.

**Comment by ben-github** [comment]
Cool. I don't see any issue with including AngularJS by default. It isn't a very heavy framework and lets you do a lot of things (I like Angular). I also think it would enable some pretty extensive customization to be done just in JS which might be nice for some applications.

**Comment by dpgaspar** [comment]
Thanks, new version 1.3.3 is out, it implements a still beta REST API, check it out.
docs:
http://flask-appbuilder.readthedocs.org/en/latest/quickhowto.html#rest-api

**Comment by Juanlu001** [comment]
Is it possible to do the authentication via the REST API too? Right now I'm doing this:

```
$ curl --data "username='admin'&password='1234'" http://0.0.0.0:8080/login/
```

and trying to save the session to use it in further requests, but I wonder if there is a better way. The documentation is scarce in this respect.

**Comment by Xalio08** [comment]
+1 for the auth using REST, it would be super useful !
