### ISSUE TITLE
Listing denormalized model with header at each change in parent value

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#463]
Hi,
I want to create a page using jqueryUI's accordion for use on mobile devices. All the accordion requires is an H3 for each header and contents between each H3.

I have a denormalized view that returns carclass and name with carclass being the repeated parent and name being distinct. The data looks like this:
CarClass Name
A1, Bob Smith
A1, Jim Roberts
A1, Tony Jones
A2, Robert Byers
A2, John Smith
I need to iterate over the data creating a header whenever the carclass changes. I would be happy to do this with Jinja2's language using "{%" or with a FAB template, whichever works best (and is easiest for me to understand!).
Can anyone get me started?
Thanks!

**Comment by dpgaspar** [comment]
Going to close this on, we will follow on #468

**Comment by dpgaspar** [comment]
Hi @AustinJim,

Were you able to do it? Can i close it?

**Comment by AustinJim** [comment]
I ended up doing this using javascript and jquery in a loop. Not real elegant but it works and I'm running up against a deadline.
Thanks for following up.
