### ISSUE TITLE
How to order results in a view?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#464]
Hi All,

I have the following Model
```
class RegistrationTest(Model, ModelEnhancer):
    __tablename__ = "Registration"
    RegistrationID = Column(Integer, primary_key = True)
    CarNo = Column(String(10), nullable=False)
    FirstName = Column(String(30))
    LastName = Column(String(30))
    CarClassID = Column(Integer, ForeignKey('CarClass.CarClassID'), nullable=False)
    CarClass = relationship("CarClass")
```

And the following View
```
class RegistrationTestView(ModelView ):
    datamodel = SQLAInterface(RegistrationTest)
    name = "RegistrationTestView"
    page_size=1000
    label_columns = {'CarNo':'Car #', 'FirstName':'First Name','LastName':'Last Name'}
    list_columns = ['CarNo','FirstName','LastName']
    edit_columns = ['FirstName','LastName']
    show_columns = edit_columns
    add_columns = edit_columns
    order_columns = ['FirstName']
```

No matter what value(s) I put in the order_columns list the data is always ordered by CarNo, which is the primary key. What do I need to do to order the output by another column?

Thanks!

**Comment by nyimbi** [comment]
Try this base_order = (Fieldname, "asc")  see if it works:
```
class RegistrationTestView(ModelView ):
    datamodel = SQLAInterface(RegistrationTest)
    name = "RegistrationTestView"
    page_size=1000
    label_columns = {'CarNo':'Car #', 'FirstName':'First Name','LastName':'Last Name'}
    list_columns = ['CarNo','FirstName','LastName']
    edit_columns = ['FirstName','LastName']
    show_columns = edit_columns
    add_columns = edit_columns
    order_columns = ['FirstName']
     base_order = ('FirstName', 'asc')
```

**Comment by AustinJim** [comment]
Thanks for the suggestion but that didn't work. Looks like I need to step into the code that creates the query. I tried opening C:\Python27\Lib\site-packages\flask_appbuilder\models\sqla\interface.py in PyCharm community edition and setting several breakpoints but none were hit. How can I step into the code that creates the query to understand what it's doing?
Thanks

**Comment by nyimbi** [comment]
Not completely sure but I think you should be looking in:
flask_appbuilder/models/generic/interface.py

**Comment by dpgaspar** [comment]
Thks @nyimbi, that it!

Take a look at: http://flask-appbuilder.readthedocs.io/en/latest/api.html#flask.ext.appbuilder.baseviews.BaseModelView.base_order 

```
class MyView(ModelView):
    datamodel = SQLAInterface(MyTable)
    base_order = ('my_column_name','asc')
```

**Comment by AustinJim** [comment]
That did it. Thanks so much!

**Comment by EnriqueGautoSand** [comment]
How to order using  base_order = ('my_column_name','asc')  if the  'my_column_name' is an related column
like     
```
categoria_id = Column(Integer, ForeignKey('categoria.id'), nullable=False)
    categoria = relationship("Categoria")
```
and Categoria class is 
```
class Categoria(Model):
    __tablename__='categoria'
    id = Column(Integer, primary_key=True)
    categoria = Column(String(50), unique=True, nullable=False)
```

and wanna to order by Categoria.categoria?
