### ISSUE TITLE
How to load an ImageColumn Programmatically?

### ISSUE THREAD

**Issue by nyimbi** [dpgaspar/Flask-AppBuilder#466]
I am trying to load a table with image data:
```
class Task(Model):
  id = Column(Integer, primary_key=True, autoincrement=True)
  name = Column(String(50))
  photo = Column(ImageColumn)
```

Then in another script
from app import db, models

```
for i in range(5):
   tsk = Task()
   tsk.name = 'name' + str(i)
   tsk.photo = 'image.jpg'
   db.session.add(tsk)
   db.session.commit()
```

BUT:
a). The image is not uploaded, nor is the name munged. How do I achieve this?

**Comment by MichaelPereira** [comment]
This is not really related to Flask App Builder, you should ask this question on https://stackoverflow.com/

Just to give you some help, you need to read the binary content of the picture in the `.photo` member, not put the image name.

**Comment by nyimbi** [comment]
Thank you for your input Michael. (BUT: ImageColumn is a flask_appbuilder mixin from filemanager.py

"The “ImageColumn” type, is an extended type from Flask-AppBuilder." So it might properly be a flask-appbuilder question.

**Comment by nyimbi** [comment]
Here is what finally worked for me:
`from flask_appbuilder.filemanager import  uuid_namegen, thumbgen_filename
  from PIL import Image, ImageOps
 import config

def save_image(image, path, format='JPEG'):
    if image.mode not in ('RGB', 'RGBA'):
        image = image.convert('RGBA')
    with open(path, 'wb') as fp:
        image.save(fp, format)

def upload_img(filename):
	upname = uuid_namegen(filename)
	thumb_name = thumbgen_filename(filename)
	
	#resize the file
	orig_img = Image.open(filename)
	
	thumb_img = ImageOps.resize(orig_img, (30,30), Image.ANTIALIAS)
	img = ImageOps.resize(orig_img, (400,400), Image.ANTIALIAS)
	
	save_image(img, config.IMG_UPLOAD_FOLDER + '/' + upname)
	save_image(thumb_img, config.IMG_UPLOAD_FOLDER + '/' + thumb_name)
`

**Comment by dpgaspar** [comment]
Thks @nyimbi
