### ISSUE TITLE
Help for list with bootstrap accordion

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#468]
Hi All,
I'm trying to create a list page that displays the repeating (header) data as a Bootstrap accordion with radio buttons within each accordion section allowing the user to vote for one candidate within each group.
I feel like if I can get to the collection of records being iterated over I could do this. But, it's opaque to me. I tried the following template but I get this error : 

 File "C:\Python27\lib\site-packages\flask_appbuilder\baseviews.py", line 798, in _get_list_widget
    modelview_name=self.__class__.__name__)
I have two questions:
1) What am I doing wrong in the template below?
2) Would anyone be willing to code me a page and do some other work for compensation? I'm getting up against a deadline and everything I try to do seems to take a long time.

I really like FAB but I think taking on Python, Flask and FAB all at once has beaten me.

```
{% import 'appbuilder/general/lib.html' as lib %}
{% extends 'appbuilder/general/widgets/base_list.html' %}

{% block list_header %}
   {{ super() }}
   <a href="url_for('Class.method for my control')" class="btn btn-sm btn-primary"
        <i class="fa fa-rocket"></i>
   </a>
{% endblock %}

{% block begin_loop_values %}
    {% for item in value_columns %}
        {% set pk = pks[loop.index-1] %}
        {% if actions %}
            <input id="{{pk}}" class="action_check" name="rowid" value="{{pk}}" type="checkbox">
        {% endif %}
        {% if can_show or can_edit or can_delete %}
            {{ lib.btn_crud(can_show, can_edit, can_delete, pk, modelview_name, filters) }}
        {% endif %}
        </div>

        {% for value in include_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}
    {% endfor %}
{% endblock %}



```

**Comment by dpgaspar** [comment]
Hi @AustinJim 

Are you still stuck on this?
How are you calling this, have you created a widget? can you post your view?
Have you read this: http://flask-appbuilder.readthedocs.io/en/latest/templates.html#list-templates ?

**Comment by AustinJim** [comment]
Hi Daniel,
I did read the docs on list templates and couldn't figure out how to make the changes I wanted to so I've decided to try an AngularJS page. Your example in quickhowto2 seems particularly well architected and I think I will have it working soon to accomplish a Bootstrap3 accordion.
Thanks.

**Comment by dpgaspar** [comment]
ok, going to close this one
