### ISSUE TITLE
FAB updated release

### ISSUE THREAD

**Issue by alexandre-zia-movile** [dpgaspar/Flask-AppBuilder#469]
Is there any plan to release an updated version of FAB?
At least fixing deprecated warnings and updating requirement packages?
I'm more concerned about any possible security fix considering FAB and all dependencies.
Thanks in advance

**Comment by mistercrunch** [comment]
@dpgaspar if you give me the pypi rights (`mistercrunch`) and guide me through my first release process, I'm happy pushing a release out every once in a while

**Comment by alexandre-zia-movile** [comment]
That would be awesome, fab is a great framework, flexible enough to adapt to many uncommon needs.
However it's becoming outdated as the other packages are evolving, like flask-sqlalchemy which  is not possible to use latest version or it will break FAB.
I would love to see new features in FAB, but if we keep it in sync with all dependencies at least we can keep it alive.

**Comment by mistercrunch** [comment]
I'd hate to have to fork this project :(

**Comment by dpgaspar** [comment]
Sorry everyone for this... I'll give myself an hard date to release a new version until 11-05-2017.
yes, I need to update dependencies and test the latest PR merges.

Any list of dependencies you would like to see updated?

**Comment by alexandre-zia-movile** [comment]
Thanks that's great, 
I'm more concerned about security fixes in all dependencies.

And if you have any improvements in Generic Data Sources, I'm using them a lot.

**Comment by dpgaspar** [comment]
Just submitted PR #471, probably final version for 1.9.0, any comments/critics would be very appreciated.

Thank you so much everyone for your contributions on 1.9.0.

**Comment by dpgaspar** [comment]
Ok, new 1.9.0 is out! Breaking changes for OAuth authentication.
