### ISSUE TITLE
Concatenate columns in view?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#470]
Hi All,
I have a model with a foreign key relationship to another model. In my view I have access to columns from both models, as expected. How can I concatenate some of the columns from the foreign table so in the view (actually in the json) there is a column like col1 + col2 + col3 followed by individual columns like col4, col5...

I've searched the docs but I can't find a match, probably because I don't know how to correctly describe this. 

Thanks!

**Comment by dpgaspar** [comment]
Hi @AustinJim 

Assuming you are using SQLAlchemy you can define an extra method where you concatenate the cols (or whatever), and then use it on your view:

``` python
class Product(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    price = Column(Float, nullable=False)
    photo = Column(ImageColumn)
    description = Column(Text())
    product_type_id = Column(Integer, ForeignKey('product_type.id'), nullable=False)
    product_type = relationship("ProductType")

    def extra_col(self):
        return self.name + ' '  + str(self.price)

  ````

Then on your view:

``` python
class ProductView(ModelView):
    datamodel = SQLAInterface(Product)
    list_columns = ['name', 'prive', 'product_type.name', 'extra_col']
 
```

**Comment by dpgaspar** [comment]
did this help? were you able to solve it?
