### ISSUE TITLE
Form with custom query

### ISSUE THREAD

**Issue by atelierJVA** [dpgaspar/Flask-AppBuilder#476]
Hi,

I have a Master-Detail view, but I need to use a custom query in the detail form to select just a subset of the related records. is this possible with FAB?

Thanks in advance,
Juan

**Comment by dpgaspar** [comment]
Hi @atelierJVA 

If your custom query is not too complex you can use base_filters on your detail ModelView: http://flask-appbuilder.readthedocs.io/en/latest/api.html#basechartview

**Comment by tserafim** [comment]
@atelierJVA were you able to find a solution to your problem?
