### ISSUE TITLE
How to accept a hand coded form?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#479]
Hi all,
I've hand coded a form that uses rest output to create the html elements in the form and I want to submit it to FAB for manual handling.  The data in the form is not backed by a model in the way it comes in. I would like to manipulate it then save it using a model. My first hurdle is to get the form posted into a method where I can access the request. I tried this in views.py.

```
@app.route("/postvotes", methods=['POST'])
def postVotes():
    data = "";
    #data = {request.json['votes']}
    # TODO Spin through votes saving each of them.
    return
```

with the form tag like this:
`	<form action = "/postvotes" method="post" name="voteform">
`
I put a breakpoint at the first line in the method and it is not hit. I can't tell if the form post is actually getting to the method I've added the route to. This is an error thrown from FAB:

```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\werkzeug\wsgi.py", line 697, in __next__
    return self._next()
  File "C:\Python27\lib\site-packages\werkzeug\wrappers.py", line 81, in _iter_encoded
    for item in iterable:
TypeError: 'Response' object is not iterable
```
I'd appreciate any help!

Thanks

**Comment by dpgaspar** [comment]
Have you tried using FormViews: http://flask-appbuilder.readthedocs.io/en/latest/api.html#basechartview?

**Comment by tserafim** [comment]
@AustinJim did you find a solution to your question? If not, can you share your code/application so someone can try to help you

**Comment by AustinJim** [comment]
Yes I did. I just didn't understand the framework well enough. Thanks for following up! I'll close this issue.
