### ISSUE TITLE
related_view for mongoDB is not showing other modelviews.

### ISSUE THREAD

**Issue by lohithn4** [dpgaspar/Flask-AppBuilder#480]
Hi,
I am trying to add MyModelViews to related_view by following the http://flask-appbuilder.readthedocs.io/en/latest/quickhowto_mongo.html#define-your-views-views-py
but i am not able see the related_views appearance, in the following example it is showing only ThirdModelView. 
except related_views appearance everything works fine.

> views.py

`class FirstModelView(ModelView):
    datamodel = MongoEngineInterface(First)
    label_columns = {'name':'name'}
    list_columns = ['name']
    show_columns = ['name']

class SecondModelView(ModelView):
    datamodel = MongoEngineInterface(Second)
    label_columns = {'name':'name'}
    list_columns = ['name']
    show_columns = ['name']

class ThirdModelView(MasterDetailView):
    datamodel = MongoEngineInterface(Third)
    related_views = [FirstModelView, SecondModelView]
`

> my model.py

`class First(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return self.name
class Second(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return self.name
class Third(Document):
    name = StringField(max_length=60, required=True, unique=True)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return self.name`
am i missing anything here for related_views to work with mongoDB, i think there is no issue if i use SqlAlchemy.

**Comment by dpgaspar** [comment]
Hi @lohithn4 

Your First needs to 'ReferenceField' the Second and Third.
