### ISSUE TITLE
How do i add custom database not listed?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#481]
I have other database i would like to explore like rethinkdb and arangodb, how do i create a customized deployment? i would like to contribute so it can be available to all as well

**Comment by MichaelPereira** [comment]
You would have to create classes specific for this database in https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/models, https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/security and probably more locations.

**Comment by dpgaspar** [comment]
Right!

- On the ./models/rethinkdb you need to create specific filters and implement the interface (RethinkDBEngineInterface).
- On the ./security/rethinkdb you need to implement the SecurityManager class and the db security models.
