### ISSUE TITLE
Static files path correct but FAB returns 404

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#490]
[Here is my template file, ](https://github.com/afidegnum/myfab/blob/master/app/templates/media_add.html)

Other static files, Js and css files are properly displayed but the one i uploaded returns error. Loading individual files returns 404 error

what do i need to correct?

**Comment by afidegnum** [comment]
@dpgaspar please can you look into this ?

**Comment by afidegnum** [comment]
the error is happening at http://localhost:8080/mymediaview/add

**Comment by dpgaspar** [comment]
The files are really not there: http://localhost:8080/static/appbuilder/css/style.css

https://github.com/afidegnum/myfab/tree/master/app/static/appbuilder/css

Where is style.css ?

**Comment by afidegnum** [comment]
style.css is located at 

app/static/appbuilder/css/style.css

**Comment by dpgaspar** [comment]
Not on your repo

**Comment by afidegnum** [comment]
I was trying to implement bluimp javascript image uploader, you can add to your app as well, you can suggest changes too if possible,

**Comment by dpgaspar** [comment]
Ok,

So, on media_add.html change:

```
<link rel="stylesheet" href="{{ url_for('appbuilder.static', filename='css/style.css') }}">
```

For this:
```
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
```
( Do it for all your imports css and js )

Next copy you ./app/static/appbuilder/* to ./app/static

Use your own static. Short explanation, but i hope you get the general idea.

**Comment by afidegnum** [comment]
Thanks, the files are showing now but unfortunately i need to change the upload library, they are not displaying here

**Comment by afidegnum** [comment]
ok, that works, i m now focusing on the media upload endpoint the the server to receive uploaded files
