### ISSUE TITLE
Implementing Image and File Upload on FAB

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#494]
HI, 

I have noticed Filecolumn and ImageColumn help to trigger file and image upload tool. 

How can i implement on the above class to add my own file upload system? 

Can i initiate a pull request to implement part of the code?

**Comment by afidegnum** [comment]
I m trying to implement the `BS3ImageUploadFieldWidget` class from upload.py

here is what i have started, can you please suggest? 

```
class BS3AjaxUploadFieldWidget(object):

    empty_template = ('<link rel="shortcut icon" href="{{ url_for %(static)s, filename=%(image)s) }}" type="image/x-icon">'
                      '<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">'
'<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">'
'<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">'


'<link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">'


'<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fileupload.css') }}">
'<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fileupload-ui.css') }}">'

```

What's the best approach?
can i add custom block regions here?

**Comment by afidegnum** [comment]
where do i direct the form POST ?

**Comment by dpgaspar** [comment]
Hi @afidegnum,

Did blocks work? not very nice to include this on the widget, so we have some options:

- include it globally on init.html, on the other hand we would be including something that will be probably never used.

- include it on a "special" widget for add and edit, something like: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/widgets/chart.html. This would imply changing forms.FieldConverter also and probably some other places. This approach is for totally changing the current File and Image "widgets" on F.A.B.

- Write your own template for what you want and WTForm class, would be great and simple for you! ( we could include it on the F.A.B. github repo has an example)

**Comment by afidegnum** [comment]
thanks a lot, i have taken note
