### ISSUE TITLE
Can you help with the following?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#495]
How do i set custom endpoint for ModelView?

I m setting a custom model type as AjaxImageColumn, how do i set filemanager.py to recognize this field?

How do i pass the form argument between pages?

**Comment by afidegnum** [comment]
I have how do i implement the CKEditor on textwidget?

**Comment by afidegnum** [comment]
@dpgaspar any insight?

**Comment by dpgaspar** [comment]
No time right now to look deeply into it.
But my advise to you, write your own WTForm and form template, this way you develop what you want the way you want, and stop fighting the framework ;) .

**Comment by dpgaspar** [comment]
Take a look at the quickhowto2:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickhowto2/app/forms.py

the on your ModelView override: http://flask-appbuilder.readthedocs.io/en/latest/api.html#flask.ext.appbuilder.baseviews.BaseCRUDView.edit_form

add_form and edit_form, you can (and probably want) to override also add_template and edit_template.

**Comment by afidegnum** [comment]
thanks a lot for the insight

**Comment by xqliu** [comment]
刘向前 赞了您的邮件。
Spark by Readdle
