### ISSUE TITLE
inheriting the field from mongodb to postgresql

### ISSUE THREAD

**Issue by lohithn4** [dpgaspar/Flask-AppBuilder#496]
Hi,
I'm able to define and use two databases in a single flask-appbuilder, mongodb and postgresql.

```
class MongoClass(Document):
    mc1 = StringField(max_length=60, required=True, unique=True)
    mc2 = StringField(max_length=2)

    def __repr__(self):
        return self.registration_number

class PostgreClass(BaseMixin, Base):
    pc1 =  Column(String(60), unique = True, nullable=False)
    pc2 = Column(String(2), nullable=False)

    def __repr__(self):
        return self.registration_number
```

I am trying to find a way to make a relationship between the classes such that pc1 references mc1. 
 let me know if there is a possible way to do it.
Thanks.

**Comment by afidegnum** [comment]
With postgres and mongo, you call the views you want to reference via     related_views = [ViewtoRelate]

while declaring models, on Postgews/sqlalchemy you use relationships and mongodb, you use ReferenceFIelds

**Comment by lohithn4** [comment]
here i'm trying to establish relationship between two different databases, i tried the above suggested one but it only displays data of the same database fields.
i do accept that there is no meaning in my question as i am trying to bring the relationship between the noSql field with the sql field. BTW i am not sure if anyone is able to do this thing in some way.

**Comment by afidegnum** [comment]
from the [Doc, ](http://flask-appbuilder.readthedocs.io/en/latest/multipledbs.html) you can use many databases, you can even call a relation between them, but i don't think you will use Join or relationship lookup to bridge 2 type of databases, you will need to define your own linking method.

**Comment by dpgaspar** [comment]
This is not possible, engine interfaces for MongoDB and SQLA uses ORM's relations, to find what columns are related and the relationship type, 1-N, N-1, N-N. Not possible to bridge between ORM's for this.
