### ISSUE TITLE
I can't expose path on modelview

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#497]
I have the following class but i can't get expose endpoint to work on the model view. 

```
class MyMediaView(ModelView):
    datamodel = SQLAInterface(Media)
    add_template = 'media_add.html'
    static_folder = 'static/appbuilder'

    @expose('/upoad/<string:myfile>',  methods=('GET', 'POST'))
    def upload_img(self, myfile):
        return myfile

appbuilder.add_view(MyMediaView, "MyMedia", icon="fa-folder-open-o", category="Admin")
```

But ` http://localhost:8080/mymediaview/upload/as `  returns 404 what could be the issue?

**Comment by dpgaspar** [comment]
upload =/ upoad
?

**Comment by afidegnum** [comment]
Yes. i just discovered it, can you please help with the previous question? I m trying to use ImageManager class to get the image, save, generate thumbnail and delete as well,
