### ISSUE TITLE
flask_wtf.csrf:The CSRF token is missing.

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#500]
I m defining my custom form even though i included 

```
        {% if csrf_token %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
	        {% endif %}
```

I still have this error, any reason why? 

I m running my test on Localhost and even disabled the csrf on the config script, i m still having this problem

**Comment by GregSilverman** [comment]
[https://github.com/dpgaspar/Flask-AppBuilder/issues/310](url)

**Comment by afidegnum** [comment]
Thanks a lot, i have fixed it already

**Comment by pricel3ss** [comment]
Please tell me how this was fixed! i'M DYING!

**Comment by manugarri** [comment]
@pricel3ss  just add this to the end of your form 

```
<form>
...
 {% if csrf_token %}
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
 {% endif %}
</form>
```
