### ISSUE TITLE
Where do I put css for custom themes?

### ISSUE THREAD

**Issue by danlurie** [dpgaspar/Flask-AppBuilder#504]
I've tried running `fabmanager collect-static` and putting my `.css` files in `/app/static/appbuilder/css/themes`, but it doesn't seem like that's where FAB is looking, because even if I replace `yeti.css` (which works when I have that set as `APP_THEME`) with the custom CSS, it still shows the standard `yeti` look.

Where is FAB actually looking for these files? I'm trying to use some of the new Bootswatch themes that aren't included with FAB.

**Comment by afidegnum** [comment]
create  a static folder, create a css and template folder if possible, then add to your View 

  `add_template = 'mystatic_folder/my_template_file.html'`
next in your templates, refer to your css/js file as example 

`<link rel="stylesheet" href="{{ url_for('static', filename='my_css_or_js_folder/mystatic_file.css') }}">`

**Comment by danlurie** [comment]
I'm not sure I follow. I'm specifically talking about the global `APP_THEME` stylesheets, not template-specific CSS.

**Comment by dpgaspar** [comment]
Hi @danlurie,

Flask will first look on your app's templates and static, next on FAB templates and static. So bootswatch css are on your virtualenv (if you have created one) on the flask_appbuilder lib. What you can do is take a look at the docs: http://flask-appbuilder.readthedocs.io/en/latest/templates.html#css-and-javascript and override css the way it's described. 

On the other hand, i should update bootswatch, i've just opened a PR #508 with this update that includes 5 new themes.

**Comment by dpgaspar** [comment]
Going to close this one, hope it helped.

**Comment by ashb** [comment]
@dpgaspar I think there's a missing component here - namely the `APP_THEME` config setting will only ever look for files installed in the flask_appbuilder/static/ folder (i.e. inside the installed FAB package)

It would be nice for our users if it was possible to drop a css file somewhere in their local folder and have it be used.

We can deal with some of this in airflow's baselayout.html `head_css` block, but it would nice to be able to support FAB's built in themes _and_ user custom themes. But with the route name hard-coded in https://github.com/dpgaspar/Flask-AppBuilder/blob/3931bc2f5297a85bbd197873ff78c5790f9bf574/flask_appbuilder/templates/appbuilder/init.html#L21-L23 that's not possible out of the box.

I'm not sure exactly what I'd like to see it changed to, but some way of not having `appbuilder.static` hard-coded there would be nice.

**Comment by ashb** [comment]
How about something like this.

If we have a blueprint like this that is registered

```python
bp = Blueprint(
    "site_themes",
    url_prefix="/site-theme",
    static_folder="static",
    static_url_path="/static")
```

And  then set this in the config:

```python
APP_THEME = "site_themes.static:foo.css"
```

And then something like this in the template (though probably pre-processed to be done in the app, not the template:

```jinja
 {% if appbuilder.app_theme %} 
     {% if ":" in appbuilder.app_theme;
         set route,filename = appbuilder.app_theme.split(':');
      %} 
        <link href="{{url_for(route, filename=filename )}}"  rel="stylesheet"> 
     {% else %}
        <link href="{{url_for('appbuilder.static',filename='css/themes/'+ appbuilder.app_theme )}}"  rel="stylesheet">
     {% endif %}
{% endif %}
```

That may not be valid Jinja. Hopefully you get the idea - if it is a "plain" filename then the existing behaviour is kept, if it contains a `:` then we treat it as `{route_name}:{path/and/filename.css}`

Does this sound like a useful feature? I'll happily turn this into a PR (a sensible one, where the code lives in python, not the templates, don't worry!) with docs.

**Comment by ashb** [comment]
@dpgaspar ^^ Any opinion on my previous comment?

**Comment by Sangee2610** [comment]
I Added my css file in 
 **"static/appbuilder/css/themes/mytheme.css"**
I added APP_THEME in config file ,  
**APP_THEME = "dark.css"**

When i run ,there is no effect in UI......I think APP_THEME is  taking the csv file from different  directory.... 

Any way without using Blueprint or without making changes in "init.html"

Any idea where we can specify the path for css file

**Comment by finnkr539** [comment]
> I Added my css file in
> **"static/appbuilder/css/themes/mytheme.css"**
> I added APP_THEME in config file ,
> **APP_THEME = "mytheme.css"**
> 
> When i run ,there is no effect in UI......I think APP_THEME is taking the csv file from different directory....
> 
> Any way without using Blueprint or without making changes in "init.html"
> 
> Any idea where we can specify the path for css file

Have you found a solution? I'm facing the same issue. In my app, I have the static folder with the CSS themes, but I couldn't get any new theme or modifications to work. I've tried different stuff, the only thing that works is changing the files in the lib folder of FAB. Is it possible that the path to the CSS files doesn't refer to the directories in the app?

**Comment by skripthostmsr** [comment]
I've found the solution. As is mentioned above, flask appbuilder won't use the directory in app/static, but in its package. 

In the config.py, I've added one line:
`FAB_STATIC_FOLDER = basedir + "/app/static/appbuilder/"`

That's it. For similar issues, I've found the solution by looking at two links, the [docs](https://flask-appbuilder.readthedocs.io/en/latest/api.html?highlight=static#flask_appbuilder.baseviews.BaseView.static_folder) and the [source code](https://flask-appbuilder.readthedocs.io/en/latest/_modules/flask_appbuilder/base.html#AppBuilder.__init__)

There are some other attributes to be set, so before anyone is about to use a more complex solution, it's definitely worth a look.

**Comment by finnkr539** [comment]
I've found the solution. As is mentioned above, flask appbuilder won't use the directory in app/static, but in its package. 

In the config.py, I've added one line:
`FAB_STATIC_FOLDER = basedir + "/app/static/appbuilder/"`

That's it. For similar issues, I've found the solution by looking at two links, the [docs](https://flask-appbuilder.readthedocs.io/en/latest/api.html?highlight=static#flask_appbuilder.baseviews.BaseView.static_folder) and the [source code](https://flask-appbuilder.readthedocs.io/en/latest/_modules/flask_appbuilder/base.html#AppBuilder.__init__)

There are some other attributes to be set, so before anyone is about to use a more complex solution, it's definitely worth a look.

**Comment by mac2000** [comment]
Have found one more workaround

lets pretend we have 

**static/demo.css**

```css
* {color:red!important}
```

**webserver_config.py**

```py
# ...
# add this at the very end
APP_THEME = "demo.css"
from flask import Response, current_app as app
@app.get('/static/appbuilder/css/themes/demo.css')
def theme():
    return Response(open(basedir + '/static/demo.css').read(), mimetype="text/css")
```

<img width="1432" alt="image" src="https://github.com/dpgaspar/Flask-AppBuilder/assets/88868/909fc33f-0e08-4bc7-ab92-150846ee6fca">

not prettier ever solution but works, and now we can tune visuals as we want
