### ISSUE TITLE
How to override view's route from ModelView

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#507]
This is what's happening

i have my static files at statics/images

but when loading the url it has 

/myviews/statics/images

how do i override the route from ModelView in order not to have ModelViews base route appended to this particular view?

**Comment by dpgaspar** [comment]
If you set the static folder on a ModelView you are telling Flask to do exactly that. Take a look at the quickimages example, notice that this does not happen there, take a look at the config vars:

UPLOAD_FOLDER = basedir + '/app/static/uploads/'
IMG_UPLOAD_FOLDER = basedir + '/app/static/uploads/'
IMG_UPLOAD_URL = '/static/uploads/'

These are global of course, see if this fits your use case.

**Comment by dpgaspar** [comment]
Any luck? did this helped?

**Comment by alexandropov** [comment]
yes, it helped.
