### ISSUE TITLE
Cannot delete permission, flask_appbuilder.security.manager

### ISSUE THREAD

**Issue by fufjvnvnf** [dpgaspar/Flask-AppBuilder#509]
How exactly do I delete a permission, and all view menus associated with that permission? I've tried all of `del_view_menu`, `del_permission` and `del_permission_view_menu` but none work. I also noted that according the source code these none of these methods are implemented, yet some other methods in the class call these methods. I am confused on what to do if I want to delete an existing permission.

**Comment by dpgaspar** [comment]
You're not supposed to delete permissions, just remove them from the role.

These permissions are FAB managed, if you find pending one's, use: http://flask-appbuilder.readthedocs.io/en/latest/security.html?highlight=clean#automatic-cleanup

**Comment by fufjvnvnf** [comment]
I'm not sure if I understand the method documentation accurately, but does `security_menu` only clean up `view_name` associated with `permission_name`s, but not `permission_name`s themselves?  Just trying to confirm; thank you for your response!

**Comment by dpgaspar** [comment]
What is "security_menu"? Do you mean "security_cleanup" method?

It will clean up permission_name also if it is not used anymore.

**Comment by fufjvnvnf** [comment]
@dpgaspar My bad, I meant `security_cleanup`. By being "used", do you mean that the permission is associated with a role? Also, does the method look directly into the database that store all these permissions, veiws and permission-view pairs, do determine if one is "used"? In my case, I still want to keep some permissions & views that are not associated with any role, but I want to delete certain views and permission-view pairs that I know I wouldn't need anymore. I think using `security_cleanup` in my case will delete more than I want.

**Comment by dpgaspar** [comment]
FAB will keep on the DB all the decorated @has_access methods. If you delete/rename some View or method *security_cleanup* will remove it from the DB. 

 "I think using security_cleanup in my case will delete more than I want."

Test it on a development environment. Backup you're DB prior to the change, the usual.
