### ISSUE TITLE
Nice framework!  but How to pass values as label to template and edit view?

### ISSUE THREAD

**Issue by alexandropov** [dpgaspar/Flask-AppBuilder#513]
Thanks very much for the framework released, i have read lot of interesting parts and play around with it, it's very handy for fast application development

However i have a little question to ask, 

I have to defined ModelView classes, I want to add and edit new items inherited from the master Class as shown here. but while editing the sub model, how do I pass the the parent value to the child class? how do i render that in the template?

```
class ChildView(ModelView):
    datamodel = SQLAInterface(Child)
    add_template = 'child_add.html'

    list_columns = ['child_id', 'parent_id' 'name']
    list_widget = ListThumbnail
    add_widget = FormWidget
    include_cols =  ['child_id', 'parent_id' 'name']
    value_columns =  ['child_id', 'parent_id' 'name']
    add_columns =  ['child_id', 'parent_id' 'name']

class ParentView(ModelView):

    datamodel = SQLAInterface(Parent)
    list_widget = ListItem

    list_columns = ['parent']
    related_views = [ChildView]
```

Unfortunately, there is nothing displaying in my child_add.html template as indicated in the tutorial as follow. can you suggest what's the best approach of rendering elements in the templates? 
```

{% import 'appbuilder/general/lib.html' as lib %}
{% extends 'appbuilder/general/widgets/base_list.html' %}

{% block list_header %}
   {{ super() }}
   <a href="url_for('Class.method for my control')" class="btn btn-sm btn-primary"
        <i class="fa fa-rocket"></i>
   </a>
{% endblock %}

{% block begin_loop_values %}
    {% for item in value_columns %}
        {% set pk = pks[loop.index-1] %}
        {% if actions %}
            <input id="{{pk}}" class="action_check" name="rowid" value="{{pk}}" type="checkbox">
        {% endif %}
        {% if can_show or can_edit or can_delete %}
            {{ lib.btn_crud(can_show, can_edit, can_delete, pk, modelview_name, filters) }}
        {% endif %}
        </div>

        {% for value in include_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}

        {% for value in list_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}


        {% for value in value_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}


        {% for value in add_columns %}
            <p {{ item[value]|safe }}</p>
        {% endfor %}



    {% endfor %}
{% endblock %}

```

**Comment by dpgaspar** [comment]
Hi @alexandropov, thank you!

Please post your models and FormWidget also. Even better can you create an example repo with this?

**Comment by alexandropov** [comment]
for the moment, I m working with the default FormWidget from flask_appbuilder.widget
i tried with different form widget as well in the widget library,
I m trying to integrate to an full design i m implementing. 
even though the template displays correctly the above block posted does not render.

here, i only want to pass the values from the master to the detail when editing or adding entries for the parent. 

here is my model, 

class Child(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=True)
    child = relationship("Publication")
    child_id = Column(Integer, ForeignKey('publication.id'), nullable=True)

class Parent(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=True)

**Comment by dpgaspar** [comment]
I assume Publication == Parent, right?

Still some questions child_add.html is extending base_list? Are you trying to override the template? If yes, if you don't override it does the related list display?

**Comment by alexandropov** [comment]
sorry, Publication == Parent, yes, 

I m not overriding the template, i m trying to inherit it's properties and add my own form, hence keeping the original design.  or anything that can help display elements from the ModelVIew

**Comment by alexandropov** [comment]
what's the best way to render editable element in the template?

**Comment by dpgaspar** [comment]
You want to Add or edit the Master Model and Child Model on the same form?

**Comment by alexandropov** [comment]
because they are inheriting from the Parent display, the add will carry {{ parent_id }} but if i m editing, i should have {{parent_id}} and {{child_id}}

**Comment by dpgaspar** [comment]
So, on ParentView you are talking about the add end edit of the related_views ChildView?

**Comment by alexandropov** [comment]
Following the [model relation documentation, ](http://flask-appbuilder.readthedocs.io/en/latest/relations.html)  i create a Parent Entry. so when i Click to show that Parent or tried to Edit it, I Add a Child if it does not exist. I can select to Edit that Child if it exist.

**Comment by alexandropov** [comment]
in that case i have to look for request argument.

**Comment by dpgaspar** [comment]
Yes, if you want to create you're own Add/Edit form for this. FAB omits this, because it's what you normally would want, you're on a related_view where Parent Item is 1 (for example), so the field on parent_id on the form to add or edit on the ChildView will always be 1. So FAB omits it on the form, and automatically "adds" the field on POST.

Note: 
- If you want to override this behaviour, you can always create 2 ModelViews for the ParentView, leaving one with the standard behaviour (for example) and the other is specialised by you and this is the one you use on ChildView.related_views.

- I can't include on FAB, all use cases, the aim is to address the most common ones, and open things enough so it can be easy to override the templates, or ModelViews. You can always inherit from BaseView (get minimal functionality) and do what ever you want like a Flask Blueprint.

**Comment by alexandropov** [comment]
ok, thanks, i believe this question is answer but lies on the situation on rendering the ModelField on the template which i m still unsuccessful able to achieve, 
i just tried this          {{ url_for(ChildView.show, pk=str(self.id)) }}
and i have` UndefinedError: 'ChildView' is undefined`

how can it be rendered?

**Comment by dpgaspar** [comment]
an example from lib:

```
{% macro lnk_back() %}
    <a href="{{url_for('UtilView' + '.back')}}" class="btn btn-sm btn-default" data-toggle="tooltip" rel="tooltip"
       title="{{_('Back')}}">
        <i class="fa fa-arrow-left"></i>
    </a>
{% endmacro %}
```
So does:

```
{{ url_for('ChildView.show', pk=str(self.id)) }}
````
work?

**Comment by alexandropov** [comment]
ok, that works in some way, had to remove the str() function but rather had an unexpected value

`{{ url_for('ChildView.show', pk=(self.id)) }}`

got this `/childview/show/
`
is there not a way to get a value from ChildView or from the Child Model?

**Comment by dpgaspar** [comment]
'self' will not do it you're on a template not a class, you have to study the widgets on FAB and Jinja2.

**Comment by alexandropov** [comment]
I m stuck in the middle, can you please help? 

on my Add form, i want to show items from the related field, 

but i have an error, 

```
{% extends "appbuilder/base.html" %}
{% import 'appbuilder/general/lib.html' as lib %}

     {% block content %}

{{ lib.panel_begin(title) }}

{% block add_form %}
    {{ widgets.get('add')(form_action=form_action)|safe }}
{% endblock %}

## this work as it displays the back arrow on top of the panel, since no items rendered yet, 



         {% if related_views %}
    <ul class="nav nav-tabs">
    <li class="active"><a href="#Home" data-toggle="tab">{{ _("Detail") }}</a> </li>
        {% for view in related_views %}
            <li>
                <a href="#{{view.__class__.__name__}}" data-toggle="tab">{{view.title}}</a>
            </li>
        {% endfor %}
    </ul>

    <div class="tab-content">
    {% for view in related_views %}
        <div id="{{view.__class__.__name__}}" class="tab-pane">
            {{ widgets.get('related_views')[loop.index - 1](pk = pk)|safe }}
        </div>
    {% endfor %}
{% endif %}

{% block show_form %}
    <div id="Home" class="tab-pane active">
        {{ widgets.get('show')()|safe }}
    </div>
{% endblock show_form %}

{% if related_views %}</div>{% endif %}

```

this leads me to an error 

```

2017-06-21 12:51:38,692:INFO:werkzeug:127.0.0.1 - - [21/Jun/2017 12:51:38] "GET /mymediaview/add?_flt_0_publications=1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/views.py", line 486, in add
    widgets=widget)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/PycharmProjects/myfab/app/templates/media_add.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/home/afidegnum/PycharmProjects/myfab/app/templates/media_add.html", line 51, in block "content"
    {% block show_form %}
  File "/home/afidegnum/PycharmProjects/myfab/app/templates/media_add.html", line 53, in block "show_form"
    {{ widgets.get('show')()|safe }}
AttributeError: 'NoneType' object has no attribute '__call__'
```

**Comment by dpgaspar** [comment]
Hi @alexandropov,

Please post your current ModelView, looks like widgets is not being passed to the template.

**Comment by alexandropov** [comment]
it's just the same ModelView i m playing with as before

meanwhile a quick question

i wanted to use extra_args rather but don't know if it's the correct way, how do i pass current model data to the extra_args? 

```
class ChildView(ModelView):
    datamodel = SQLAInterface(Child)
    add_template = 'child_add.html'

    list_columns = ['child_id', 'parent_id' 'name']
    list_widget = ListThumbnail
    add_widget = FormWidget
    include_cols =  ['child_id', 'parent_id' 'name']
    value_columns =  ['child_id', 'parent_id' 'name']
    add_columns =  ['child_id', 'parent_id' 'name']

class ParentView(ModelView):

    datamodel = SQLAInterface(Parent)
    list_widget = ListItem

    list_columns = ['parent']
    related_views = [ChildView]

```

**Comment by dpgaspar** [comment]
Ok, extra_args is a good idea for this:

Using the contacts example you can:

``` python

class ContactModelView(ModelView):
    datamodel = SQLAInterface(Contact)
    add_template = 'add_contact.html'

    @expose('/add', methods=['GET', 'POST'])
    @has_access
    def add(self):
        self.extra_args = {'xpto': 'XPTO'}
        return super(ContactModelView, self).add()
```
Then the template:

````
{% extends "appbuilder/general/model/add.html" %}

{% block add_form %}
{{ xpto }}
{{ super() }}
{% endblock %}

```

Just do whatever you want with 'xpto' ;)

**Comment by alexandropov** [comment]
thanks for the help given but one more last question, 
how do i inject the model values to extra_args? 
is this correct? 
self.extra_args = ['child_id', 'parent_id' 'name']
or 
self.extra_args = list_columns

or something else? 

P.S 
I saw you posted earlier you are going to support Angular for the front-end, i m very delighted, i m not too good in it but i would live to contribute, can you share your inclusion process, i can also assist,

**Comment by dpgaspar** [comment]
http://flask-appbuilder.readthedocs.io/en/latest/advanced.html?highlight=extra_args#template-extra-arguments

So, not a list but a dict.

Angular unfortunately will not come any time soon (no time), but who knows...

Going to close this one, best of luck and have fun developing your app with FAB ;)
