### ISSUE TITLE
missing template file

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#515]
HI @dpgaspar, 

i have noticed on [this class](https://github.com/dpgaspar/Flask-AppBuilder/blob/af095ac4094d068fa2dd467bd01fa8b95d697fc1/flask_appbuilder/widgets.py#L21) the referred `render.html` template is not there, is it intentional or it supposed to be there?

**Comment by dpgaspar** [comment]
True, maybe i should change it to 'None'
