### ISSUE TITLE
Consider using `permission` id & `view_menu` id as primary keys in `ab_permission_view`?

### ISSUE THREAD

**Issue by fufjvnvnf** [dpgaspar/Flask-AppBuilder#516]
I don't quite understand why do we need an extra `id` field in `ab_permission_view` table so that we are allowed to have rows with the same permission and view menu pairs. Under this design, my `ab_permission_view` table is populated with unwanted duplicate pairs. Shouldn't it be considered to use `pid` and `vid` as primaries keys so that we don't have duplicate permissions?

**Comment by dpgaspar** [comment]
Yes this would be a stronger model design, I must confess i choose this because of FAB limitation not supporting composite pk's (pk with two or more fields). 

Yet it's strange that your ab_permission_view has duplicates. have you tried calling security_cleanup ?

**Comment by fufjvnvnf** [comment]
@dpgaspar I'm directly using sqla's security manager's `add_permission_view` to add permissions that I wish, thus it's not strange that during the process same permissions are added. I also managed to explicitly delete permissions of my own wish by using methods in the same class, thus resolving my previous issue.

**Comment by dpgaspar** [comment]
Ok, thks
