### ISSUE TITLE
retrieving the user_id with mongoengine

### ISSUE THREAD

**Issue by lohithn4** [dpgaspar/Flask-AppBuilder#520]
I'm trying to retrieve the user.id of the currently logged in user, i'm using the mongoengine for mongoDB database

i'm using the function g.user.id but it results in 
```
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
```
i think with sql db it is of no issue, but how can it be done with mongoengine. i'm doing this mainly for displaying the currently logged in user data.

**Comment by dpgaspar** [comment]
This is most probably a flask-login, flask problem, you are calling g.user.id outside a context (request).

**Comment by kimendree** [comment]
Was there a solution to this ? 

This code throws the exception:
```
def get_user_id():
    return g.user.id
```

models.py in flask_appbuilder/security/mongoengine/ contains this , which prevents the exception.

```
def get_user_id():
    try:
        return g.user.id
    except Exception:
        return None
```

However, the consequence is that the createdby and changedby fields for the User Model are always populated with None.

**Comment by dpgaspar** [comment]
The initial reported problem was related with app context, if your sure g.user.id is not set for mongodb please open a new issue
