### ISSUE TITLE
How do i set the index page and custom theme for admin and other roles?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#521]
I m trying to build different roles and their personalized template i.e main simple user, admin, manager. 

how do i build their dedicated themes?

**Comment by dpgaspar** [comment]
If your templates are going to change based on different roles, you can:

- Use a Flask/Jinja2 filter to retrieve the role.
- Use extra_args to pass to the template the current user role.
- REST API that exposes the current user role.

Then implement your logic on the template.
