### ISSUE TITLE
Listing stored procedure results

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#522]
Hi all,
I've created a stored procedure in MySQL and I want to invoke it from a FAB menu and list it's results in a readonly list within FAB. I'd like to have the pagination, search and sort capabilities that the default list template provides, if possible. So I have a couple of questions:
1) Can I use a FAB Model backed by a stored procedure or should I use SQLAlchemy to call the proc from within the view class (or something else)?
2) What do I need to modify to create a page like described above?
Thanks!
p.s. I like all of the activity lately!

**Comment by afidegnum** [comment]
even though i m still fresh here, let me add my little cent before anyone else comes in, 
1. you can call stored procedures in FAB Model being also dependent of sqlalchemy.
you do something like, 

## from sqlalchemy ### 
connection = engine.raw_connection()
try:
    cursor = connection.cursor()
    cursor.callproc("my_procedure", ['x', 'y', 'z'])
    results = list(cursor.fetchall())
    cursor.close()
    connection.commit()
finally:
    connection.close()

2. you can do pagination in flask from this [link](http://flask.pocoo.org/snippets/44/) and there is a pagination module in [flask too ](https://pythonhosted.org/Flask-paginate/) you can apply the same principle here but with the listing, there could be a pagination option, i haven't come accross it, waiting for feedback from others as well
This is the model application that could answer all design needs, we need massive support to make it work, i really enjoyed. is an epitome of a perfect web RAD

**Comment by AustinJim** [comment]
Thanks for the help. The stored procedure call works perfectly. I'll move on to the display shortly. Thanks again!
