### ISSUE TITLE
no option export in csv or pdf format in table 

### ISSUE THREAD

**Issue by shivadyade16** [dpgaspar/Flask-AppBuilder#523]
Thanks for nice framework

We could not able to find option to export data from table in csv  or pdf or other format as we used  in datatable

Please share if its  exists on how to use it

**Comment by afidegnum** [comment]
Create a custom view and implement on this code

```
@expose('/csv/'. methods=['GET'])  
def download_csv():  
    csv = 'foo,bar,baz\nhai,bai,crai\n'  
    response = make_response(csv)
    cd = 'attachment; filename=mycsv.csv'
    response.headers['Content-Disposition'] = cd 
    response.mimetype='text/csv'
    return response
```

This is taken from few examples from flask serving files attachment, you can implement your own models, static files etc...

**Comment by MichaelPereira** [comment]
This is only valid for a custom endpoint. What @shivadyade16 is asking is for a way to download the content of any ModelView as a csv or pdf, a functionality that would need to be provided by the framework

**Comment by afidegnum** [comment]
you can implement the csvdump or pdf export of models, using sqlalchemy

**Comment by dpgaspar** [comment]
Hi @shivadyade16,

There's no default functionality for this on FAB, one simple way of doing it would be:

1 - First define a new list widget to add an additional button for the CSV download, create the following on your ./myapp/templates/widgets/list_download.html

``` python
{% import 'appbuilder/general/lib.html' as lib %}
{% extends 'appbuilder/general/widgets/list.html' %}

{% block list_header scoped %}
   {{ super() }}
    <a href="{{url_for('ContactModelView' + '.download_csv', **request.args)}}" class="btn btn-sm btn-default">
       <i class="fa fa-cogs"></i>
    </a>
{% endblock %}


{% block begin_content scoped %}
{{ super() }}
{% endblock %}

{% block begin_loop_header scoped %}
{{ super() }}
{% endblock %}

{% block begin_loop_values %}
{{ super() }}
{% endblock %}

{% block end_content scoped %}
{{ super() }}
{% endblock %}

```

Next on your views.py define your widget:

``` python
from flask_appbuilder.widgets import ListWidget


class ListDownloadWidget(ListWidget):
    template = 'widgets/list_download.html'
```

Then add the following to your ModelView:

``` python
from flask import make_response

class MyModelView(ModelView):
    datamodel = SQLAInterface(MyModel)
    list_widget = MyListWidget

    @expose('/csv', methods=['GET'])
    def download_csv(self):
        get_filter_args(self._filters)
        order_column, order_direction = self.base_order
        count, lst = self.datamodel.query(self._filters, order_column, order_direction)
        csv = ''
        for item in self.datamodel.get_values(lst, self.list_columns):
            csv += str(item) + '\n'
        response = make_response(csv)
        cd = 'attachment; filename=mycsv.csv'
        response.headers['Content-Disposition'] = cd
        response.mimetype='text/csv'
        return response
```

NOTE: self.datamodel.get_values(lst, self.list_columns) returns a list of dicts with the query result, just iterate over it to build your CSV.

**Comment by jreg2k** [comment]
Hello,
@dpgaspar  can you show us how to export only one record in CVS. The idea is to have the export button near the show, edit and delete button in the list page.

Thanks.

**Comment by chenhuican** [comment]
you can define a action function like this :      
  @action("down_excel","Download to xlsx","Proceed with download","fa-file-excel-o",single=False)
        def down_excel(self, items):
                output = BytesIO()
                list_items = list()
                i = 1
                for item in items:
                        row = dict()
                        for col,colname in self.label_columns.items():
                                row[colname] = str(getattr(item, col))
                        list_items.append(row)
                        i += 1
                        if i> 1300:
                                break
                df = pd.DataFrame(list_items)
                writer = pd.ExcelWriter(output, engine='xlsxwriter')
                df.to_excel(writer, 'data', index=False)
                writer.save()
                output.seek(0)
                def return_url():
                        self.update_redirect()
                        return redirect(self.get_redirect())
                return_url()
                return send_file(output,
                                attachment_filename=u'医生用户信息.xlsx',
                                as_attachment=True)

**Comment by brotherhui** [comment]
`   
Based on chenhuican's comments, I put more details here. 
1st, you need to install dependency as below for csv support
pip install pandas
pip install xlsxwriter

2nd, in view.py
from flask import redirect, send_file
from io import BytesIO
import pandas as pd

3rd, try with this block in your views
 @action("down_excel","Download to xlsx","","fa-file-excel-o",single=False)
    def down_excel(self, items):
        print(items)
        output = BytesIO()
        list_items = list()

        for item in items:
            row = dict()
            for col,colname in self.label_columns.items():
                row[colname] = str(getattr(item, col))
            list_items.append(row)

        df = pd.DataFrame(list_items)
        writer = pd.ExcelWriter(output, engine='xlsxwriter')
        df.to_excel(writer, 'data', index=False)
        writer.save()
        output.seek(0)

        return send_file(output, attachment_filename='list.xlsx', as_attachment=True)`

**Comment by bd317** [comment]
I tried

> Hi @shivadyade16,
> 
> There's no default functionality for this on FAB, one simple way of doing it would be:
> 
> 1 - First define a new list widget to add an additional button for the CSV download, create the following on your ./myapp/templates/widgets/list_download.html
> 
> ```python
> {% import 'appbuilder/general/lib.html' as lib %}
> {% extends 'appbuilder/general/widgets/list.html' %}
> 
> {% block list_header scoped %}
>    {{ super() }}
>     <a href="{{url_for('ContactModelView' + '.download_csv', **request.args)}}" class="btn btn-sm btn-default">
>        <i class="fa fa-cogs"></i>
>     </a>
> {% endblock %}
> 
> 
> {% block begin_content scoped %}
> {{ super() }}
> {% endblock %}
> 
> {% block begin_loop_header scoped %}
> {{ super() }}
> {% endblock %}
> 
> {% block begin_loop_values %}
> {{ super() }}
> {% endblock %}
> 
> {% block end_content scoped %}
> {{ super() }}
> {% endblock %}
> ```
> 
> Next on your views.py define your widget:
> 
> ```python
> from flask_appbuilder.widgets import ListWidget
> 
> 
> class ListDownloadWidget(ListWidget):
>     template = 'widgets/list_download.html'
> ```
> 
> Then add the following to your ModelView:
> 
> ```python
> from flask import make_response
> 
> class MyModelView(ModelView):
>     datamodel = SQLAInterface(MyModel)
>     list_widget = MyListWidget
> 
>     @expose('/csv', methods=['GET'])
>     def download_csv(self):
>         get_filter_args(self._filters)
>         order_column, order_direction = self.base_order
>         count, lst = self.datamodel.query(self._filters, order_column, order_direction)
>         csv = ''
>         for item in self.datamodel.get_values(lst, self.list_columns):
>             csv += str(item) + '\n'
>         response = make_response(csv)
>         cd = 'attachment; filename=mycsv.csv'
>         response.headers['Content-Disposition'] = cd
>         response.mimetype='text/csv'
>         return response
> ```
> 
> NOTE: self.datamodel.get_values(lst, self.list_columns) returns a list of dicts with the query result, just iterate over it to build your CSV.

I tried this out but I always end up with the following error:

`werkzeug.routing.BuildError: Could not build url for endpoint 'ContactModelView.download_csv'. Did you mean 'ContactModelView.download' instead?`

I created the widget file and inserted step 2 and 3 in my views.py. I changed 

```
class MyModelView(ModelView):
    datamodel = SQLAInterface(MyModel)
    list_widget = MyListWidget
```

to:

`class MyModelView(ModelView):
    datamodel = SQLAInterface(MyModel)
    list_widget = ListDownloadWidget`

Can someone help me out?

**Comment by dpgaspar** [comment]
@bd317, on your example it should be `MyModelView.download_csv`

**Comment by bd317** [comment]
@dpgaspar 
Thanks for coming back to me. Unfortunately, I receive the next error:

File "...\app\views.py", line 33, in download_csv
    order_column, order_direction = self.base_order
TypeError: cannot unpack non-iterable NoneType object

I tried now different possible solutions but it seems there is an issue with my data-modell?

![flask](https://user-images.githubusercontent.com/52275681/71101592-42b34c80-21b7-11ea-8cf3-c5165ae1056e.png)

**Comment by bd317** [comment]
I fixed it, i had some issues with the models. Thanks for your help!

**Comment by dpgaspar** [comment]
No problem!

**Comment by AlfonsoSargiotto** [comment]
> I fixed it, i had some issues with the models. Thanks for your help!

Hi, can you help me? I'm having the same issue, how did you fix it?

**Comment by AlfonsoSargiotto** [comment]
> @bd317, on your example it should be `MyModelView.download_csv`

Hi, I'm having similar issues. If I call MyModelView.download_csv in MyModelView, it doesn't recognize "MyModelView" (NameError: name 'MyModelView' is not defined).
If I set list_widget = ListDownloadWidget the button appears but then I have this problem :
File "...\app\views.py", line 33, in download_csv order_column, order_direction = self.base_order 
TypeError: cannot unpack non-iterable NoneType object

**Comment by EnriqueGautoSand** [comment]
> > @bd317, on your example it should be `MyModelView.download_csv`
> 
> Hi, I'm having similar issues. If I call MyModelView.download_csv in MyModelView, it doesn't recognize "MyModelView" (NameError: name 'MyModelView' is not defined).
> If I set list_widget = ListDownloadWidget the button appears but then I have this problem :
> File "...\app\views.py", line 33, in download_csv order_column, order_direction = self.base_order
> TypeError: cannot unpack non-iterable NoneType object

i have the same problem and works with  
```
    @expose('/csv', methods=['GET'])
    def download_csv(self):

        get_filter_args(self._filters)

        if self.base_order==None:
            count, lst = self.datamodel.query(self._filters)
        else:
           order_column, order_direction = self.base_order

           count, lst = self.datamodel.query(self._filters, order_column, order_direction)
           print(count , self.base_order)
```

you can see all the data in lst

**Comment by AlfonsoSargiotto** [comment]
Thank you very much man! it works!

**Comment by pUC19** [comment]
Hello, is it possible to link the csv export with following code? To export selected data only?

`@action("export", "Export", "Select Export?", "fa-file-excel-o", single=False)
    def export(self, items):
         if isinstance(items, list):
                urltools.get_filter_args(self._filters)
                order_column, order_direction = self.base_order
                count, lst = self.datamodel.query(self._filters, order_column, order_direction)
                csv = ''
               
                for item, items in self.datamodel.get_values(lst, self.list_columns):
                    csv += str(item) + '\n'
                    response = make_response(csv)
                    cd = 'attachment; filename=mycsv.csv'
                    response.headers['Content-Disposition'] = cd
                    response.mimetype='text/csv'
                    return response`
