### ISSUE TITLE
my template is weird, navbar overshadowing

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#524]
[this is my current page ](https://pasteboard.co/1dG3tUxw.png)after i have created navbar_menu.html located in my appbuilder directory

I have when applying     {% block header %} the menu doesn't show up, but with     {% block navbar %}
the posted result.
How do i get rid of FAB theme overshadowing mine?

**Comment by dpgaspar** [comment]
Take a look of how superset guys have done it: https://github.com/ApacheInfra/superset/tree/master/superset/templates/appbuilder

**Comment by dpgaspar** [comment]
I'll close this one. If you need further help, ask to reopen
