### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#526]
Hi all,
Does FAB or one of the libraries it uses support caching? I'm not sure I need a complete caching solution if I could just cache the results of the first query in the code and subsequently programatically control whether the cache is returned or a new query is executed. I have a fairly static list that changes only occasionally and a cheap and slow MySQL server. In my case, the only place this is important is in the REST call to read one model.
I'd appreciate any suggestions.
Thanks

**Comment by AustinJim** [comment]
I've been thinking more about this. I think I need to manually create a REST service to handle the query and caching. Seems like the easiest implementation since I don't really need caching throughout the system.

**Comment by afidegnum** [comment]
you can integrate any caching method you want, Flask-Caching, Flask Redis, etc... but remember as flask stated,
_Flask itself does not provide caching for you, but Werkzeug, one of the libraries it is based on, has some very basic cache support. It supports multiple cache backends, normally you want to use a memcached server._
you can read more [about it here, ](http://flask.pocoo.org/docs/0.12/patterns/caching/)

all the same you can include an existing flask caching tool into Flask-Appbuilder

**Comment by dpgaspar** [comment]
Hi @AustinJim,

That is right @afidegnum, and yes @AustinJim you can write your own REST endpoint with cache, or override the existing one using some sort of cache.

**Comment by AustinJim** [comment]
Thank you gentlemen!

**Comment by dpgaspar** [comment]
Best of luck Jim, going to close this one, any further issues just ask to reopen or open a new one.
