### ISSUE TITLE
F.A.B Filter

### ISSUE THREAD

**Issue by yunusAH** [dpgaspar/Flask-AppBuilder#527]
Can FAB Filter the data before showing the database?
Each time I run FAB it preloads all of my records which at the moment is 490,000 and growing
Is there a way to filter the database so it only shows the data when I press go?

I have tried base filtering. However it came up with an error Notimplemented error

**Comment by dpgaspar** [comment]
Hi @yunusAH,

FAB does not preload all the data, the query is issued to the db with the filters.
If you are certain of this can you be more specific, about "Each time i run FAB it preload all of my records", is this when starting the server, a list on ModelView? Charts? REST API?

**Comment by yunusAH** [comment]
Good Afternoon Daniel,

Its when I load a list on model view,  What I would like to do is have a
dropdown filter system so i can preset the data before it is displayed.

For example. Country,Department,Team,User is the fields
I would like a search filter to be displayed so I can select the country
and Department first before it show the database with my preset information.
At the moment when i hit view it shows every row of data.

kindest regards Yunus






On Thu, Jun 29, 2017 at 2:26 PM, Daniel Vaz Gaspar <notifications@github.com

**Comment by afidegnum** [comment]
hi @yunusAH, 

adding to @dpgaspar comment, 

Preloading 490,000 from the database the to the web interface is a very expensive thing to do. you will need to implement a REST framework on an existing ModelView or a custom page to hook your models, at the front end,  you develop a filter tool, it could be an auto-complete form, or a textbox  with a record lookup

once initial results loaded you can perform a master/data record drill down. 

this is best done in ajax or any javascript related tool. 

let me know if this answer the question or need something more specific.

**Comment by dpgaspar** [comment]
Hi @yunusAH,

Yes you can implement your own REST endpoints and the frontend, with autocomplete, that would be great. But one quick and "dirty" solution is on the add view force a predefined filter, using the quick how to example:

``` python
appbuilder.add_view(ContactModelView, "List Contacts2", href="?_flt_0_contact_group=1", icon="fa-envelope", category="Contacts")

```
So when the main list is loaded by default it will filter all contacts filtered by contact_group = 1.

**Comment by yunusAH** [comment]
I don't believe my programming skills are that good to write my own REST framework. Extremely new to programming and feel that i've found the hardest language to learn.

**Comment by afidegnum** [comment]
Python is the easiest language so far. you need some patience, dedication and research on a related problems you are trying to solve.
