### ISSUE TITLE
fabmanager run syntaxError in windows 10

### ISSUE THREAD

**Issue by a543589796** [dpgaspar/Flask-AppBuilder#529]
I run the webapp with fabmanager run in windows 10, but Error！Below is the error message：
2017-06-29 11:27:46,462:INFO:werkzeug: * Restarting with stat
  File "E:\pylianxi\flask_appbuilder\venv\Scripts\fabmanager.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file E:\pylianxi\flask_appbuilder\venv\Scripts\fabmanager.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details.

**Comment by afidegnum** [comment]
this is more python error i believe, 
fabmanager.exe  is an executable program, run it as ./fabmanager.exe

you might need to add this to the top of fabmanager script as well, 

`# -*- coding: utf-8 -*-`

**Comment by a543589796** [comment]
Thank you @afidegnum and @dpgaspar !This is a very good framework, I like it very much!
I'm a beginner.
The system is in Chinese,I try to do it, but still so!
Below is I do change:
```
#!e:\pylianxi\flask_appbuilder\venv\scripts\python.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'flask-appbuilder==1.9.1','console_scripts','fabmanager'
# -*- coding: utf-8 -*-

__requires__ = 'flask-appbuilder==1.9.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('flask-appbuilder==1.9.1', 'console_scripts', 'fabmanager')()
    )
```

Error message:
```
 File "E:\pylianxi\flask_appbuilder\venv\Scripts\fabmanager.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file E:\pylianxi\flask_appbuilder\venv\Scripts\fabmanager.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details.
```

**Comment by dpgaspar** [comment]
Hi @a543589796,

Do you have an initial app already? if note create one without 'fabmanager' yet. please clone 

```
git clone https://github.com/dpgaspar/Flask-AppBuilder-Skeleton.git myapp
````
Or go to https://github.com/dpgaspar/Flask-AppBuilder-Skeleton and download the zip.

Next:
```
cd myapp
python run.py
```

Do you get any error?

**Comment by a543589796** [comment]
Thank you @dpgaspar.
Thank you for your answer!Run the app without 'fabmanager' no error!
Only when using the 'fabmanager' running app have a error!
Wish I can solve this problem later. 
Thank you very much, you are great!

**Comment by dpgaspar** [comment]
;) no problem. 

Thank you for reporting this, probably there is a problem with UTF8 on fabmanager

**Comment by sohailq** [comment]
Instead of using >fabmanager run, use >python run.py, this solves it for me.
