### ISSUE TITLE
extra_args content comes as a list

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#531]
I m trying to output model contents alongside with other arguments into the show template, with the following code. 

```
class PageView(ModelView):
    datamodel = SQLAInterface(Page)
    page = Page()
    current_page = appbuilder.session.query(Page).all()
    extra_args = {'rich_textareas': ['body'], 'current_page': current_page}
```
however injecting `{{current_page}}` into the template, i have a list based output instead of a normal string. 

`[Sample data record print] `

**Comment by afidegnum** [comment]
I found it, the brain is overheated, :D 
I need to loop the list,

**Comment by dpgaspar** [comment]
:)
