### ISSUE TITLE
Dropping and creating a table for one Model?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#533]
Hi,
I have a FAB Model that I've changed the structure of. How an I drop and recreate it (without data)?
I've tried the following with every combination of the Model's class name but they don't work. What is the correct way to do this?

db.drop_all(bind=['acesstoken'])
db.create_all(bind=['accesstoken'])

Thanks!

**Comment by afidegnum** [comment]
using sqlalchemy with sqlite you can run `fabmanager create-db` it will do the job. if you need more assurance, you can delete the previous database file and run create-db again but you will need to create the admin user credential afresh

**Comment by gauravkumar37** [comment]
In case someone still needs this, use this `UserModel.__table__.drop(db.engine)` to drop only a single table for the `UserModel`.

**Comment by niklahun** [comment]
> In case someone still needs this, use this `UserModel.__table__.drop(db.engine)` to drop only a single table for the `UserModel`.

sqlalchemy.exc.UnboundExecutionError: Table object 'UserModel' is not bound to an Engine or Connection.  Execution can not proceed without a database to execute against.
