### ISSUE TITLE
Item based authorization

### ISSUE THREAD

**Issue by xiaochuan-du** [dpgaspar/Flask-AppBuilder#535]
The scenario:
For a table(Model), one group of users have access to parts of items, while other users may have access to other items (like adopting `where` cause on items). How should I implement this authorization mechanism ? I know FAB includes a module based security system but totally have no clue on how to deal with this item based one.

**Comment by afidegnum** [comment]
In order to control specific item/resources/application scope, there are constrains set based on roles (categories of users who will have access/control) and permissions (the type of access and control they granted). FAB provide that through its[ security mechanism ](http://flask-appbuilder.readthedocs.io/en/latest/security.html)

**Comment by xiaochuan-du** [comment]
Thanks @afidegnum , as far as i am concerned, if I want to follow FAB's design, I need add a new item in table `ab_view_menu` for any update in biz table. For example, I have a table called `vegs`, if want to add a new item which name is `tomato` and it can only be accessed by me, I should insert `tomato` 's id in `ab_view_menu` by some ways.  Is there a more decent way to do so ?

**Comment by dpgaspar** [comment]
Hi @xiaochuan-du ,

One simple way of doing it is using base_filters on your views, you can have a *vegs* view that is filtered to users that belong to a certain group (if you extend the user model) or contain a certain role. Then you can create a another ModelView based on the *vegs* Model, that contains no filters for admin users only. You can control who accesses what views, using normal FAB's security system.

This may not solved all use cases for row based access. See if it fits yours

**Comment by xiaochuan-du** [comment]
Thanks @dpgaspar , your answer sounds great, I'd like to give it a shot.
