### ISSUE TITLE
trying to understand the clear use of default_view of Baseview

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#536]
Hi, 

I m still having a slight difficulty of the use of [default_view of BaseView](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L73)

do we need to refer to the created view ? can you please show some example?

**Comment by dpgaspar** [comment]
This will work with url_for, take a look at: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/menu.py#L28

default_view = <YOUR DEFAULT METHOD NAME>

**Comment by afidegnum** [comment]
good, i understood now,
