### ISSUE TITLE
Server capacity?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#541]
Hi all,
My FAB app will be used for attendees to vote on cars at a car show. There are 3 REST hits:
1) log in
2) return about 150 records of cars that can be voted for. (now the user walks around to all of the cars recording their votes in the single page app. This could take 30 minutes to an hour.)
3) submit and save the votes.

There will be about 100 users doing this once per user over a 2 hour period so the load is pretty low.

Will the built in Python server handle this or do I need to run it under apache, nginx or something else?
I'm running on a shared linux server in Dreamhost which is cheap (good for our shoestring org) but I could also run under Amazon EC if needed. I'd prefer something easy to set up so I can spend my time finishing the app instead of configuring a server.
Thanks for your opinions!

**Comment by dpgaspar** [comment]
Hi Jim,

If you have time, put some load test on it, this way you would know what to expect. You should use nginx ( or apache). Amazon using Elastibeanstalk is pretty easy to setup (and it will scale if needed).

**Comment by AustinJim** [comment]
I'm giving PythonAnywhere a try. Thanks!
