### ISSUE TITLE
What's the difference between SimpleFormView and PublicFormView?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#545]
Looking at the codebase, it I can't spot the difference, can you please elucidate on it ?

**Comment by tserafim** [comment]
SimpleFormView uses [`@has_access`](https://github.com/dpgaspar/Flask-AppBuilder/blob/aa4fe744469ecd6e2aed30011b21898862eaf7d2/flask_appbuilder/views.py#L54) decorator

**Comment by afidegnum** [comment]
thanks,

**Comment by tserafim** [comment]
@afidegnum can you close the issue?
