### ISSUE TITLE
there is no register and email authentication function?

### ISSUE THREAD

**Issue by IvyGongoogle** [dpgaspar/Flask-AppBuilder#551]
hello, I visit [login](http://flaskappbuilder.pythonanywhere.com/login/) and find there is only login function. So is  there no `register` and `email authentication` function?

**Comment by dpgaspar** [comment]
Yes, you have that option: http://flask-appbuilder.readthedocs.io/en/latest/user_registration.html#user-registration

Not on the demo, you can login using 'guest' / 'welcome'
