### ISSUE TITLE
What are the best practices before deployment on production environment?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#552]
I noticed we need to disable the create_all() method on the view once db tables are created. what are other practices we need to follow?

**Comment by dpgaspar** [comment]
Take a look at:
https://12factor.net/

Some pratical basics:
- Change SECRET_KEY to something really long and convoluted. 
- Passwords (for FAB users) should meet complexity requirements.
- You should disable create_all. 
- Don't use fabmanager run or flask development server on production.
- rotate your logs

**Comment by afidegnum** [comment]
logs?
