### ISSUE TITLE
RegisterUser and User Model

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#554]
Hi, 
when do we use the RegisterUser model and the User model in `flask_appbuilder/security/sqla/models.py` ? do RegisterUser later copies the user entry to the User model?

**Comment by MichaelPereira** [comment]
Yes, this is the code that does it, once the user clicks on the registration email: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/registerviews.py#L118-L126

**Comment by afidegnum** [comment]
Thanks for the reply, then i think the registration table need to be purged automatically after successful activation so there won't be redundant data in the DB

**Comment by dpgaspar** [comment]
If the user is added successfully the registration is deleted: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/registerviews.py#L128
