### ISSUE TITLE
Jinja2 explicit iteration over result rows and columns

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#557]
Hi all,
I know this is not a FAB question but I'm hoping one of you experienced folks can help me anyway.

I want to iterate over a list of results in a FAB/jinja2 template with the ability to reach forward to the next record to check one if it's values. This is to format all records that have the same value in a column in a special way. That logic is not below but you can get an idea of what I'm trying to do. 

Can I do this in jinja2?

Thanks!

```
        {% for i in results|length %}
            <tr>
                {% for j in results[i]|length %}
                <td>{{results[i][j]}}</td>
                {% endfor %}
            </tr>
        {% endfor %}

```

**Comment by afidegnum** [comment]
yes it works perfectly if you call the appropriate variables,

**Comment by ramaschittella** [comment]
Can you upload the flask code for this jinja2 rendering?
