### ISSUE TITLE
New User role

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#558]
Hi If I login as non-admin, I cannot see any items that were previously edited while as admin, how to let public users 'VIEW' only 

Also why is testdata returning:

```
Traceback (most recent call last):
  File "testdata.py", line 59, in <module>
    c.name = get_random_name(names_list, random.randrange(2, 6))
  File "testdata.py", line 12, in get_random_name
    return " ".join(name_lst)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by afidegnum** [comment]
use can_view permission

**Comment by scheung38** [comment]
Thanks.

Regarding the testdata issue, could it be related to me using Python 3?

**Comment by scheung38** [comment]
Can't find this can_view permission?

**Comment by afidegnum** [comment]
hi @scheung38 have you had an outcome of your permission issue?

**Comment by scheung38** [comment]
Not yet
