### ISSUE TITLE
related_views

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#56]
This might be a SQLAlchemy question, but can you explain how the related_views works? Basically, what kind of db links between the two underlying tables are needed.

I have 3 tables:

```
class Items(Model):
    id = Column(Integer,primary_key=True)
    serial = Column(Integer,unique=True,nullable=False)
   ...


class ItemNotes(Model):
    id = Column(Integer,primary_key=True)
    serial_id = Column(Integer,ForeignKey('product_serial_log.serial'),nullable=False)    
    serial = relationship("Items")
    ...


class ItemProperies(Model):
    id = Column(Integer,primary_key=True)
    serial_id = Column(Integer,ForeignKey('product_serial_log.serial'),nullable=False)    
    serial = relationship("Items")
    ...
```

Now I can view Items table and have related views to ItemNotes and ItemProperies. But I'd like to view ItemProperties and have it link to ItemNotes. But if I just put a related view in ItemPropertiesView to ItemNotesView it doesn't make the link. I think the issue is because the link (serial_id) is through a 3rd table and not a direct foreign key. Is there a way to pass how to link the views. Or do I need to add some kind of relationship info in the SQLAlchemy level?

Thanks,

**Comment by dpgaspar** [comment]
seems like a good idea, if not simple and automatic, i has to be flexible. 

from what i understand you managed to make it work on your app, right?

**Comment by ben-github** [comment]
Yup, I got my app working with the FAB code change of https://github.com/ben-github/Flask-AppBuilder/commit/15f0b1f14fcccd59b4a56ba4e3e4913552161b07 and _get_related_view_widget override in my view.py View definition. 

I'm thinking maybe the solution would be a helper function that just passes the bind column to _get_related_view_widget 

Then the view function override would be:

```
def _get_related_view_widget(self, item, related_view,
                             order_column='', order_direction='',
                             page=None, page_size=None):
        _get_related_view_widget_helper_bind(item,related_view,order_column,order_direction,page,page_size,bind_field)
```

where _get_related_view_widget_helper_bind is just _get_related_view_widget but passing the bind_field to the  filters.add_filter_related_view call.
