### ISSUE TITLE
Accessing datamodel instance in override view

### ISSUE THREAD

**Issue by pywarrior** [dpgaspar/Flask-AppBuilder#560]
I have ModelView that I want to associate a custom template with:

`
add_form = OverForm
add_template = 'templates/add_over.html'

`
How do I access the instance of my datamodel from in my custom template? My ultimate goal is to implement a screen that allow the user to edit more than one instance of the datamodel at a time.

**Comment by afidegnum** [comment]
create a template inside your template directory and implement the add_template remember to import the original template to your new created template,

**Comment by pywarrior** [comment]
What variable is the instance stored in?

**Comment by afidegnum** [comment]
you can start from [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py),
