### ISSUE TITLE
Using Flask-Mail in Models

### ISSUE THREAD

**Issue by TcaManager** [dpgaspar/Flask-AppBuilder#563]
Hi,
I would like to access Flask-Mail in models.py file.
But the app import doesn't seem to work.
How can I import the "app" variable into the models.py file please?
Thanks.

**Comment by tserafim** [comment]
@TcaManager did you take a look at flask's [application factory pattern](http://flask.pocoo.org/docs/0.12/patterns/appfactories/)? It should solve your problem in a more elgant(not weird) way.

The basic idea is that you should instantiate `mail` like this: `mail = Mail()`.
Doing it this way , `mail` is not bound to `app` and you are free to use `mail` in your models, or wherever you like.

Inside the factory you bind mail to app: `mail.init_app(app)`. This is briefly mentioned in [flask-mail docs](https://pythonhosted.org/Flask-Mail/#configuring-flask-mail)

If the docs linked are not enough, google for flask factory and you should get more examples.

This repo has an [example](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/factoryapp) of basic usage of factory pattern

If you need further help let us know so we can solve it and than close this issue
