### ISSUE TITLE
Feature requested: permission supporting verbose name and identify by ID instead of string

### ISSUE THREAD

**Issue by fufjvnvnf** [dpgaspar/Flask-AppBuilder#565]
A scenario of me trying to use the FAB is that permission is lost once the name of the model view has changed. In superset, permission_views are created with model views' names, so that it's readable to the admin. However, if the object's name is changed, flask appbuilder could only identify permission by names, so permissions to the changed object is lost. I could however create the permission views by object ID in the first place, but then the permissions will look like secret keys to the users. Is there a way to support a feature similar to verbose name, so that FAB could identify permissions by ID while users could look at it as readable characters? Basically, I think FAB's interface to verify permission should be different to that of the user using and creating permissions. Hope you understand what I'm talking about and if not I am extremely happy to clarify.

**Comment by afidegnum** [comment]
have you tried `fabmanager security-cleanup` command?
