### ISSUE TITLE
How to override SAVE button ?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#568]
In the master-detail (or any other examples), how to override the functionality of the, say SAVE button, so that in addition to SAVE and create a new row, it is also making a RESTful API call to another API?

**Comment by afidegnum** [comment]
Sorry for the late reply, the SAVE Button is located on the selected button widget which you can override in jinja, [look at this](flask_appbuilder/templates/appbuilder/general/lib.html)

**Comment by alexandrezia** [comment]
I think you are looking for pre-add, post-add hooks, 
Take a look: 

http://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.baseviews.BaseCRUDView.post_add

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L1035

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L288

There are also pre/post update and delete hooks as well

**Comment by scheung38** [comment]
Thanks @alexandrezia, did you already try it?

**Comment by nyimbi** [comment]
To change the text from "Save" to something else look in:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/lib.html
