### ISSUE TITLE
Docs: Employee example has no pre and post update logic

### ISSUE THREAD

**Issue by tserafim** [dpgaspar/Flask-AppBuilder#575]
[Model relation docs](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/relations.rst) says "Take a look and run the example on Employees example It includes extra functionality like readonly fields, pre and post update logic, etc..."

I checked the [example](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/employees) and, unless I really misunderstand what 'pre and podst update' means, there is no code related to 'pre and post update logic' on the example.

**Comment by afidegnum** [comment]
Do you understand what happens during pre and post update?

**Comment by tserafim** [comment]
Sure, it executes whatever logic I put into methods pre_update and post_update. I was hoping to see that in the Employee example but could not find it.

Can you show me in that example where the extra "pre and post update logic" functionalities are used?

**Comment by afidegnum** [comment]
well i believe a typical use case is to do some constrain or load sample data into the form during the pre_update, that's when using the form or performing another operaton and the post_update is load a flash message, or any action after the form is being submitted. you can also [read this code. ](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L950)
