### ISSUE TITLE
quickactions example only has code related to babel

### ISSUE THREAD

**Issue by tserafim** [dpgaspar/Flask-AppBuilder#576]
This [README.rst](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/README.rst) leads readers to believe that quickactions example should "Show how to setup actions for list views." But example/quickactions only has code related to babel.

[https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickactions](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickactions)

edit: clarification

**Comment by afidegnum** [comment]
that was an example based on someone initial question, but there is more explained in the [documentation](http://flask-appbuilder.readthedocs.io/en/latest/actions.html).

**Comment by tserafim** [comment]
Sorry, I should have mentioned on my first post that the issue was related to this README file:
[https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/README.rst](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/README.rst)

I'll update the first post.

Anyway, reading that file I understand that example/quickactions  "Show how to setup actions for list views". And well, the example on examples/quickactions does not show that.

This is just a heads up so that the documentation is updated.

**Comment by afidegnum** [comment]
I think he will take note, he might be busy somewhere :)
