### ISSUE TITLE
How to dynamically add columns ?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#577]
Is it possible in SQLite, or must I use MongodB to dynamically add columns to my 

```
class SampleClass(BaseMixin, Model):
  id = Column(Integer, primary_key=True)
    name = Column(Date())
```
i.e 

and by default could I make dynamic instance of this class so that

sample1 = SampleClass()
sample1 has 1 extra Dates attributes created dynamically
sample2 has 2 extra Dates attributed and so on....

if so, please could you show how to add columns dynamically with MongodB from UI point of view?

**Comment by scheung38** [comment]
I.e 

https://stackoverflow.com/questions/23256507/how-to-store-dynamic-fields-in-mongo-db

**Comment by afidegnum** [comment]
Using sqlalchemy, after building or modify your models you can call fabmanager create-db which generates all tables and models for you, but if you are planning to dynamically add additional model of fields, you need to plan ahead. it's easy with the key-value based databases but with transactional databases, you need to plan ahead and set your models I don't know if this answers your question. someone can help though

**Comment by scheung38** [comment]
Thanks Afidegnum, I guess I need to use the mongoengine example ( which hasn't worked for me as errors seems to crop with when fabmanager create-admin) but can I also use pymongo instead?

**Comment by afidegnum** [comment]
If you want to use Pymongo, you will then need to modify interface.py inside inside the [flask_appbuilder/models/mongoengine. ](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/models/mongoengine) otherwise you [create a generic model ](http://flask-appbuilder.readthedocs.io/en/latest/generic_datasource.html) where you can integrate pymongo but i believe there is no much difference,

What problems are you having with the mongoengine?

**Comment by scheung38** [comment]
From the examples/mongoengine directory :

Fabmanager create-admin

Returns unexpecteb type

**Comment by afidegnum** [comment]
have you launched your app via fabmanager? `unexpecteb` or `unexpectedb`

**Comment by scheung38** [comment]
Mongoengine doesn't seem to run without errors when doing fabmanager create-admin

**Comment by afidegnum** [comment]
then let's wait for @dpgaspar enlighten us on this,

**Comment by scheung38** [comment]
Basically cannot get either mongo_extendedsecurity nor mongoengine from examples to run successfully:

mongo_extendedsecurity: runs, but localhost:8080 

returns

mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string


mongoengine:  File "/Users/mincheung/anaconda2/envs/jiraflask/lib/python3.5/site-packages/mongoengine/base/fields.py", line 159, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
