### ISSUE TITLE
mongoengine.errors.ValidationError

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#578]
For the mongo_extendedsecurity example, when running 

$ fabmanager create-admin

$ fabmanager run

Upon localhost:8080

returns

raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

Daniel mentioned something about cache still storing SQLAlchemy etc so I cleared cache but problem remains...

**Comment by lohithn4** [comment]
It is clearly telling that '1' is not a valid ObjectId means, what i think is in database one of the objectID might be stored with value '1' or you might be forcing to store '_id' with value '1' in some part of your code. most of the times the issue what i faced is database issue. i mean if there is already a database with the same name or collection, and if we are trying to use it again with other application with different field values then this kind of error we may get. it is one of the issue which i faced while experimenting with mongodb.

**Comment by scheung38** [comment]
As Daniel mentioned cache browser is still thinking it is using SQLAlchemy instead of mongoengine, and advised to clear chrome cache which is what i did, but it is still there for some reason, because when I tried using Firefox I didn't see this issue.
