### ISSUE TITLE
google charts  is blocked by China GFW

### ISSUE THREAD

**Issue by myliyifei** [dpgaspar/Flask-AppBuilder#579]
How can I move it into local resources in the server

**Comment by afidegnum** [comment]
can you try a different chart aside google ones?

**Comment by myliyifei** [comment]
How to change the online chart component instead of google?

**Comment by allankliu** [comment]
So far, ECharts is counterpart in China, before digging into FAB source code, I am using custom method and JS code to do that, just like in a regular Flask app.

**Comment by tzengwei** [comment]
1 change 'appbuilder/general/widgets/chart.html','appbuilder/general/widgets/direct_chart.html','appbuilder/general/widgets/multiple_chart.html'.
2  in China ,please use  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> .
3  “google.charts.load ”  replaced "google.load" .

**Comment by tzengwei** [comment]
1 change 'appbuilder/general/widgets/chart.html','appbuilder/general/widgets/direct_chart.html','appbuilder/general/widgets/multiple_chart.html'.
2  in China ,please use  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> .
3  “google.charts.load ”  replaced "google.load" .
