### ISSUE TITLE
reduce is not in python 3

### ISSUE THREAD

**Issue by philliproso** [dpgaspar/Flask-AppBuilder#58]
File "c:\Anaconda3\lib\site-packages\flask_appbuilder\models\base.py", line 90, in _get_attr_value

return reduce(getattr, col.split('.'), item)
NameError: name 'reduce' is not defined

**Comment by myliyifei** [comment]
still has bug in group.by


File "xxxxxx/fab-py33/lib/python3.3/site-packages/flask_appbuilder/models/group.py", line 194, in resolve_attr
        return g
 
    def resolve_attr(self, obj, attr):
        if not hasattr(obj, attr):
            # it's an inner obj attr
            return reduce(getattr, attr.split('.'), obj)
        if hasattr(getattr(obj, attr), '__call__'):
            # its a function
            return getattr(obj, attr)()
        else:
            # it's an attribute
NameError: global name 'reduce' is not defined
