### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by amoussoubaruch** [dpgaspar/Flask-AppBuilder#580]
Hello,

I want to configure ldap user to acces my app.
This information for my OS : Centos 7
- I follow all step to configure ldap. I use directly file config.py  and add following lines :

    -- from flask_appbuilder.security.manager import AUTH_DB, AUTH_LDAP
    -- AUTH_TYPE = AUTH_LDAP
    -- AUTH_USER_REGISTRATION = True
    -- AUTH_LDAP_SERVER = "Ldap-server" 
    -- AUTH_LDAP_SEARCH = "***"
    -- AUTH_LDAP_BIND_USER = "***"
    -- AUTH_LDAP_BIND_PASSWORD = "****"
    -- AUTH_LDAP_UID_FIELD = "uid"
    -- AUTH_LDAP_UID = "sAMAccountName"

When my application start and i try to connect i get "Invalid login Please try again"
And in command line i have this error :

ERROR:flask_appbuilder.security.manager:LDAP Error Referral
Anybody already have this issue? 
I use something like this for AUTH_LDAP_BIND_USER : CN=assat1,OU=Assat2,OU=Assat3,OU=Assat4 Operations,DC=fr,DC=comp,DC=org
Please help me

**Comment by afidegnum** [comment]
you can read about [Error referrals further.](https://technet.microsoft.com/en-us/library/cc978014.aspx)
do a manual connection test to your LDAP server the error might be some credentials not correct.

**Comment by amoussoubaruch** [comment]
ok @afidegnum 

Thanks

**Comment by amoussoubaruch** [comment]
@afidegnum  thanks for this link. I am read it and i thinks i well done my config. But i got this new error. 

![image](https://user-images.githubusercontent.com/13684386/29275832-c3f70fa0-810c-11e7-90ab-1832becf275f.png)

Have you an idea please?

**Comment by afidegnum** [comment]
looking at this screen, i don't there is an error,  use your browser and point to it you might get an error there if there is. just type this address: http://localhost:9000

**Comment by amoussoubaruch** [comment]
ok

**Comment by hamidmahmoodnbs** [comment]
where I can find config.py in flask-appbuilder. I am using mac High Sierra 10.13. Please help me. I want to configure ldap.
