### ISSUE TITLE
Project created from within examples directory fails to run when moved to desktop : mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#584]
Made a copy of one of the examples which worked (mongoimages), but when this newly created folder is moved to desktop, and opened in Pycharm 

$pip install -r requirements.txt

and 

$ fabmanager create-admin 
$ fabmanager run 

Both went fine, but uponing launching localhost:8080

fails with 

```
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

```
i.e How to launch this example derived app, without the confines of within the Flask-AppBuilder clone?

**Comment by afidegnum** [comment]
are you using windows?

**Comment by scheung38** [comment]
No, afidegnum... Mac OSX

**Comment by scheung38** [comment]
Even the original example derived which worked, now also displaying this in browser:

m`ongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string`

**Comment by afidegnum** [comment]
sorry i couldn't help much in that direction but there is a similar [posted in SO](https://stackoverflow.com/questions/25438459/mongoengine-test1-is-not-a-valid-objectid)
