### ISSUE TITLE
Cannot use Related Views

### ISSUE THREAD

**Issue by Rhynorater** [dpgaspar/Flask-AppBuilder#587]
I have the following definition in my model: 

class DomainView(ModelView):
    datamodel = SQLAInterface(Domain)
    label_columns = {'num_flagged':'# Flagged', 'num_subdomains':'# Subdomains', 'num_dir':'# of Dirs', 'num_flagged_dir':'# Flagged Dirs'}
    add_columns = edit_columns = ['domain', 'notes', 'company']
    list_columns = ['domain', 'company', 'num_flagged', 'num_subdomains', 'num_dir', 'num_flagged_dir']

class FileView(ModelView):
    datamodel = SQLAInterface(File)
    list_columns = ['file', 'domain', 'company']
    add_columns = edit_columns = ['file', 'subdomain', 'domain', 'notes']
    related_views = [DomainView]

When I run it I get the following error when I try to following url: 
http://127.0.0.1:8080/fileview/show/1

    File "/home/justin/github_projects/RhynoRecon/RR/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 739, in _get_related_view_widget

    log.error("Can't find relation on related view {0}".format(related_view.name))

    AttributeError: 'DomainView' object has no attribute 'name'

**Comment by afidegnum** [comment]
What are the objects in `Domain` model?  I can see in your list_columns you have 

`list_columns = ['domain', 'company', 'num_flagged', 'num_subdomains', 'num_dir', 'num_flagged_dir']`

can i see your Models ?

**Comment by Rhynorater** [comment]
class Domain(AuditMixin, Model):
    __tablename__="Domain"
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey('Company.id'))
    company = relationship("Company")
    domain = Column(String(162))
    notes =  Column(Text, default='Insert Notes Here')
    num_flagged = Column(Integer, default=0)
    num_subdomains = Column(Integer, default=0)
    num_flagged_dir = Column(Integer, default=0)
    num_dir = Column(Integer, default=0)
    changed_on = Column(DateTime, default=datetime.datetime.now,onupdate=datetime.datetime.now, nullable=False)
    created_on = Column(DateTime, default=datetime.datetime.now, nullable=False)

    def __repr__(self):
        return self.domain


Here is the domain model. Here is the file model: 
class File(AuditMixin, Model):
    __tablename__="File"
    id = Column(Integer, primary_key=True)
    file = Column(String(150))
    company_id = Column(Integer, ForeignKey('Company.id'))
    company = relationship("Company")
    domain_id = Column(Integer, ForeignKey('Domain.id'))
    domain = relationship("Domain")
    subdomain_id = Column(Integer, ForeignKey('Subdomain.id'))
    subdomain = relationship("Subdomain")
    notes =  Column(Text, default='Insert Notes Here')
    changed_on = Column(DateTime, default=datetime.datetime.now, onupdate=datetime.datetime.now, nullable=False)
    created_on = Column(DateTime, default=datetime.datetime.now, nullable=False)

    def __repr__(self):
        return self.file

**Comment by Rhynorater** [comment]
@afidegnum

**Comment by afidegnum** [comment]
Your `Domain` model do not have an attribute `name` so if you include what does not exist in your view, it will surely generate an error. do you mean `domain`  of `Domain.domain` ?

**Comment by Rhynorater** [comment]
I'm not including name anywhere. I don't even reference it, so far as I can see @afidegnum

**Comment by Rhynorater** [comment]
@afidegnum ?

**Comment by harmon** [comment]
I'm by no means and expert, but try updating your File class to reference something like:

```
domain = relationship("Domain", backref='files')
```

I think the issue is that the related model (Domain) doesn't have an attribute to point back to File, so adding backref should add an attribute called "files" that points back.

Just a guess, but hopefully that works.

**Comment by tomanizer** [comment]
The issue arises from a bug in a log message in flask appbuilder itself.
When flask appbuilder cannot determine the relation between the view and the related view it is trying to log an error message 
`log.error("Can't find relation on related view {0}".format(related_view.name))`
However, related_view does not have a name attribute, hence the log message fails with this error. It is not a problem with your model.

We should fix:
flask_appbuilder\baseviews.py", line 741, in _get_related_view_widget
in order to at least return the correct log message.
