### ISSUE TITLE
How to run in different port, other than 8080?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#588]
How to run in different port, other than 8080?

In run.py

```
from app import app
app.run(host='0.0.0.0', port=50000, debug=True)
```

But fabmanager run still runs in 8080?

**Comment by afidegnum** [comment]
fabmanager run --port 5000)

**Comment by scheung38** [comment]
Thanks @afidegnum

**Comment by manviagarwal** [comment]
how to run a flask application on two different ports simultaneously?

**Comment by m1lky** [comment]
manviagarwal
when i did it, i just used 2 threads and ran the app twice.
