### ISSUE TITLE
flaskmongoengine DateTimeField() defaults

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#589]
How to display  DateTimeField() from mongodb as

2017-08-02  when calender date is clicked

instead of

2017-08-02 23:37:05, i.e hours and seconds removed.

**Comment by afidegnum** [comment]
According to mongodb

_All datetimes retrieved from the server (no matter what version of the driver you’re using) will be naive and represent UTC._

i m not much conversant with mongodb but could this work? 
v = datetime(2010, 12, 19, 5, 35, 55, 286000)
v.astimezone(pytz.timezone("US/Eastern"))
`datetime(v.year, v.month, v.day, v.hour, v.minute, v.second, v.microsecond, pytz.utc)`
