### ISSUE TITLE
decorate SAVE button

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#591]
How to decorate SAVE button, so that when clicked, not only will it save to db as usual, but also sending these content (mongoengine) as payload to another RESTful server as CRUD methods?

**Comment by mistercrunch** [comment]
http://flask-appbuilder.readthedocs.io/en/latest/api.html?highlight=post_add#flask_appbuilder.baseviews.BaseCRUDView.post_add

there's all sorts of hooks on model views. `post_add` `pre_add`  `post_update` `pre_update`
