### ISSUE TITLE
Issues creating public views

### ISSUE THREAD

**Issue by leonardomateo** [dpgaspar/Flask-AppBuilder#594]
Hello,

I'm new to Flask-AppBuilder, if this is not the correct place to ask this question, please let me know where I should post it. 

I'm building a simple web site that requires, an about and a contact page.  Through the docs, I was able to override the index page,  but don't know how I can create views for static public pages.  Can someone please provide me with directions/resources on how to achieve this?

Thanks,

Leo

**Comment by MichaelPereira** [comment]
As mentioned in #446, assigning that contact page access to the Public role should do the trick.

**Comment by dpgaspar** [comment]
Thks @MichaelPereira
