### ISSUE TITLE
Is Gantt chart type supported ?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#595]
As I have, say for example two time series data A and B, but A and B both has further subplot of 

A-1, A-2, A-3 etc
B-1, B-2, B-3 etc

**Comment by afidegnum** [comment]
yes,

**Comment by scheung38** [comment]
Charttype: pie chart, linechart 

But I don't see gantt chart

**Comment by afidegnum** [comment]
I think you need to extend google chart and include [gantt chart from google](https://developers.google.com/chart/interactive/docs/gallery/ganttchart)

otherwise, you can implement your own chart system as related in this issue #424
