### ISSUE TITLE
appbuilder.add_link not available for mongoengine type of build?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#601]
appbuilder.add_link is not available if using mongoengine?

or must I use

appbuilder.add_view in this context?

When trying to add in views.py:

    class MyChartView(BaseView)

        default_view = 'method1'

        @expose('/method1/')
        @has_access
        def method4(self):
            return 'Hello'
    
        @expose('/method4/<string:param1>')
        @has_access
        def method4(self, param1):
            return self.render_template('method4.html', param1=param1)

    appbuilder.add_view(MyChartView, "Chart1" category="My Chart")
    appbuilder.add_view(MyChartView, "Chart1" href='/project/method4/john', category="My Chart")

returns:

builtin.AttributeError
AttributeError: view_menu

?

**Comment by jdclarke5** [comment]
I ran into this same issue. I traced it back to a loop in the `_has_view_access` method of flask_appbuilder/manager.py. There's a loop over roles and permissions. In my database, I have 53 elements in my `role.permissions` list field. I believe these are supposed to match the entries in the `permission_view` collection. However I found there were only 37 entries in this collection. Hence it ends up looking for attributes of entries which are simply not there. Anyway, without tracing back the source of that any further, the hacky solution that worked for me is to check to see if `permission` has the expected attribute (basically checking if it exists), like so:

```
for permission in permissions:
    if (hasattr(permission,'view_menu')) and (view_name == permission.view_menu.name) and (permission_name == permission.permission.name):
        return True
```

Hope this is useful for someone. Perhaps best to trace back why the inconsistency appears in the first place...
