### ISSUE TITLE
where is the base_template?

### ISSUE THREAD

**Issue by BenXu86** [dpgaspar/Flask-AppBuilder#602]
In "Flask-AppBuilder/flask_appbuilder/templates/appbuilder/base.html",it inherits base_template.
so,where is base_template?

**Comment by tserafim** [comment]
base_template is a variable available in jinja context.

It is defined in [AppBuilder `__init__` method](https://github.com/dpgaspar/Flask-AppBuilder/blob/aa4fe744469ecd6e2aed30011b21898862eaf7d2/flask_appbuilder/base.py#L123) and injected into the context on [BaseView `render_template` method](https://github.com/dpgaspar/Flask-AppBuilder/blob/aa4fe744469ecd6e2aed30011b21898862eaf7d2/flask_appbuilder/baseviews.py#L148-L158).

The default value for base_template is [appbuilder/baselayout.html](https://github.com/dpgaspar/Flask-AppBuilder/blob/aa4fe744469ecd6e2aed30011b21898862eaf7d2/flask_appbuilder/base.py#L97)
