### ISSUE TITLE
How to add recaptcha on login form?

### ISSUE THREAD

**Issue by jniloms** [dpgaspar/Flask-AppBuilder#613]
Hi, I'm testing flask-appbuilder and I'm liking. But I need to use captcha in login form.

It's possible?

**Comment by Cody-Steelman** [comment]
Hey, I just implemented this on a version I was working on, I made a fork of Flask-Appbuilder, and in Flask-Appbuilder/flask_appbuilder/security/forms.py, add recaptcha = RecaptchaField() to the login template your using i think by default its LoginForm_db. , under the template for that form, 'login_db.html' right above the submit button add in {{ form.recaptcha }}, and finally in config.py configure the keys using 'RECAPTCHA_PUBLIC_KEY = " " and RECAPTCHA_PRIVATE_KEY = " "  - Hope this helps!

**Comment by tserafim** [comment]
@jniloms were you able to solve this?
