### ISSUE TITLE
How can I use 'add_registration()' ?

### ISSUE THREAD

**Issue by efvaldez1** [dpgaspar/Flask-AppBuilder#619]
Hi all, I want to user add_registration of flask app builder for my alternative in registering user. 

from flask_appbuilder.security.registerviews import RegisterUserDBView,BaseRegisterUser
registeruserdbview=BaseRegisterUser()
print(registeruserdbview)
registeruser=registeruserdbview.add_registration(username=email, first_name=firstname, last_name=firstname, email=email, password='12345')
Returns an error of "Nonetype" has no attribute sm

**Comment by MichaelPereira** [comment]
We had to create a custom registration view for our project, this is how we register users:

```python

from flask_appbuilder.security.registerviews import BaseRegisterUser

from <app_name> import global_app

class CustomRegisterUserDBView(BaseRegisterUser):
    """
        View for Registering a new user, auth db mode
    """
    form = MyRegisterUserDBForm
    """ The WTForm form presented to the user to register himself """
    redirect_url = '/'

    def form_get(self, form):
        self.add_form_unique_validations(form)

    def form_post(self, form):
        self.add_form_unique_validations(form)
        public_role = global_app.appbuilder.sm.find_role(global_app.appbuilder.sm.auth_role_public)
        new_user = global_app.appbuilder.sm.add_user(username=form.username.data,
                                                     email=form.email.data,
                                                     first_name=form.first_name.data,
                                                     last_name=form.last_name.data,
                                                     role=[public_role],
                                                     password=form.password.data)

global_app just contains a variable:
```python
appbuilder = None
```
that is set to the appbuilder object when the application starts.

**Comment by efvaldez1** [comment]
****What is wrong with my code?** 
appbuilder = AppBuilder(app, db.session,indexview=MyIndexView,security_manager_class=MySecurityManager)
 
I created my own Form
class MyRegisterUserDBForm(DynamicForm):
	username = StringField(lazy_gettext('User Name'), validators=[DataRequired()], widget=BS3TextFieldWidget())
	first_name = StringField(lazy_gettext('First Name'), validators=[DataRequired()], widget=BS3TextFieldWidget())
	last_name = StringField(lazy_gettext('Last Name'), validators=[DataRequired()], widget=BS3TextFieldWidget())
	email = StringField(lazy_gettext('Email'), validators=[DataRequired()], widget=BS3TextFieldWidget())
	password = PasswordField(lazy_gettext('Password'),
							 description=lazy_gettext(
								 'Please use a good password policy, this application does not check this for you'),
							 validators=[DataRequired()],
							 widget=BS3PasswordFieldWidget())
	conf_password = PasswordField(lazy_gettext('Confirm Password'),
								  description=lazy_gettext('Please rewrite the password to confirm'),
								  validators=[EqualTo('password', message=lazy_gettext('Passwords must match'))],
								  widget=BS3PasswordFieldWidget())

**created my own View:
class MyRegisterUserDBView(BaseRegisterUser):**
	form = MyRegisterUserDBForm
	redirect_url= '/'
	def form_get(self,form):
		self.add_form_unique_validations(form)
	def form_post(self,form):
		print(request.remote_addr)
		self.add_form_unique_validations(form)
		self.add_registration(username=form.username.data,
											  first_name=form.first_name.data,
											  last_name=form.last_name.data,
											  email=form.email.data,
											  password=form.password.data                                     
											   ) 
**Add it to My Security Manager:**
class MySecurityManager(SecurityManager):
    user_model = MyUser    			#Extend default user model
    registeruserdbview	 = MyRegisterUserDBView		#override register view


**I get the user info using my chat widget, so i instantiate my Form**
tempForm=MyRegisterUserDBForm()
tempForm.username=email
tempForm.first_name=firstname
tempForm.last_name=firstname
tempForm.password='1234'
tempForm.email=email	
registeruser=appbuilder.sm.registeruserdbview.form_post(tempForm)

However I get this error in my registeruser:
"datamodel_user = self.appbuilder.sm.get_user_datamodel
AttributeError: 'NoneType' object has no attribute 'sm'"

**Comment by efvaldez1** [comment]
**(or this error)**
registeruser=appbuilder.sm.registeruserdbview.form_post(tempForm)
TypeError: form_post() missing 1 required positional argument: 'form'

**Comment by efvaldez1** [comment]
I am using a chat widget for this ^ registration, any tips how can I get it to register a user?

**Comment by efvaldez1** [comment]
I plan to use the add_register_user() and send_email() function after user has input data in chatwidget. How can I do so?

**Comment by efvaldez1** [comment]
Hi @MichaelPereira 
I have the following directory structure:
sampleapp
         /app
                 __init__.py
                 customregisterview.py
How can I import appbuilder from __init__.py , into customregister view.py?

**Comment by AkVijay** [comment]
Circular dependencies ....

**Comment by ln0358** [comment]
Hello @MichaelPereira, 

Thank you for the example you gave. 
In my case, i'm trying to create a custom register view with additional info and i find your answer which i think is going to be usefull.
But for me, i get this error message : "'NoneType' object has no attribute 'sm'

Could you explain with more details how to implement global_app (location, content perhaps and the relation with the custom view file ?) 
(i've created a global_app.py file with 1 row : appbuilder=None) located at the same level of my custom files). 

THank for your attention, 
Best regards


------------
[...]
from <app_name> import global_app
[...]
        public_role = global_app.appbuilder.sm.find_role(global_app.appbuilder.sm.auth_role_public)
        new_user = global_app.appbuilder...
