### ISSUE TITLE
MasterDetailView - Possible To Have Searchable Related Views ?

### ISSUE THREAD

**Issue by cavemancoder999** [dpgaspar/Flask-AppBuilder#624]
I noticed that views are not searchable when they are the related views of a MasterDetailView.
Is it possible to enable this somehow ?

**Comment by Cody-Steelman** [comment]
This would be helpful for me as well, was about to open the same question until seeing this.

**Comment by dpgaspar** [comment]
Not implemented, sorry.

**Comment by kalimuthu123** [comment]
Hi @dpgaspar  i am in need of that feature is it possible
