### ISSUE TITLE
Many to many relationship with prevalidating update conditions.

### ISSUE THREAD

**Issue by gmartindelcye** [dpgaspar/Flask-AppBuilder#627]
Great Work!!!

Thank you for this wonderful application.

I am making little app to register students in an event that have several workshops.
It's a many to many relationship, and its working great.

My problem is this: I have a quota of student per workshop that cannot be exceeded, this field is included in the model as well as the number of student current register in them.

In the student view I can assign the workshops without a problem. How can I check the workshop quota vs. register plus one, so that before updating de data, produces a warning and do not permit to assign that workshop to the student if the assigning exceeds the quota?

I have check to override pre_update and post_update methods but they work after the save button is push and I need to make the validation when the workshops are assign. Can you direct me in the right direction?

Many thanks in advance!

This are my models and views files:

# models.py

    assoc_student_workshop = Table('student_workshop', Model.metadata,
                                   Column('id', Integer, primary_key=True),
                                   Column('student_id', Integer, ForeignKey('student.id')),
                                   Column('workshop_id', Integer, ForeignKey('workshop.id')),
                          )

    class Student(Model):
        id = Column(Integer, primary_key=True)
        name = Column(Unicode(60), unique=True, nullable=False)
        grade = Column(Unicode(4))

        workshops = relationship('Workshop', secondary=assoc_student_workshop,
                                backref="Student")

        def __repr__(self):
            return self.name

    class Workshop(Model):
        id = Column(Integer, primary_key=True)
        name = Column(Unicode(60), unique=True, nullable=False)
        description = Column(UnicodeText)
        date = Column(Date, nullable=False)
        time = Column(Unicode(13), nullable=False)
        quota = Column(Integer)
        register = Column(Integer)

        def __repr__(self):
            return self.name

# views.py

    class StudentModelView(ModelView):
        datamodel = SQLAInterface(Student)

        list_columns = ['name', 'grade']

        base_order = ('name', 'asc')
        show_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

        add_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

        edit_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

**Comment by dpgaspar** [comment]
Sorry for the delay, were you able to solve it?

**Comment by gmartindelcye** [comment]
Actualy no, I'm no expert, but I think I have to tinker with jquery/Ajax since the validation must be before any button is pushed. What do you think?

**Comment by gmartindelcye** [comment]
I've found a solution, don't know is the best way but is working.
Change de __repr__ method from Workshop model to show the result from subtracting the register students from de quota getting the available spaces for each workshop:

    class Workshop(Model):
        id = Column(Integer, primary_key=True)
        name = Column(Unicode(60), unique=True, nullable=False)
        description = Column(UnicodeText)
        date = Column(Date, nullable=False)
        time = Column(Unicode(13), nullable=False)
        quota = Column(Integer)
        register = Column(Integer)

        def __repr__(self):
            return "%s: %d" % (self.name, self.quota - self.register)

Then modifing the StudentModelView:

    class StudentModelView(ModelView):
        datamodel = SQLAInterface(Student)
        list_columns = ['name', 'grade']
        base_order = ('grade', 'asc')
        show_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

        add_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

        edit_fieldsets = [
            ('Student', {'fields': ['name', 'grade', 'workshops']}),
        ]

        def post_update(self, item):
            workshops = db.session.query(Workshop).all()
            for w in workshops:
                w.register = len(w.Student)
            db.session.commit()

The last method "counts" the students register for each workshop and updates de result in the worshop register field that is use to determine the avaliable places for each wokshop in the repr method of the model.
