### ISSUE TITLE
Switch databases while running?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#629]
Hi all,
I have several databases with exactly the same structure but different data. Is it possible to switch databases from within FAB without editing the config file and restarting? I could populate a collection with all the databases in config because they are all known at startup.

Thanks!

**Comment by dpgaspar** [comment]
Have you tried changing, AppBuilder.session ? 
I did not tried it thought

**Comment by AustinJim** [comment]
I have not but I will give it a try.
Thanks!

**Comment by tserafim** [comment]
@AustinJim any progress on this?

**Comment by AustinJim** [comment]
Hi,
I had to put the project on hold and did not try this. I think when I pick it back up I will combine all databases into one and segregate the data by AccountID.
Jim

**Comment by harmon** [comment]
There's an industry term for this, google "multitenancy database design" for more info. It took me a while to find the exact terminology for this type of thing!

**Comment by omalbhagya** [comment]
@AustinJim I have the same issue. I have to switch between two database with same schema. I have added following lines into the __init__.py but I don't know that it is the best way to do it.

app = Flask(__name__)
app.config.from_object('config')
db1 = SQLA(app, session_options={"autoflush": False})
db2 = SQLA(app, session_options={"autoflush": False})
