### ISSUE TITLE
Geoalchemy2 support

### ISSUE THREAD

**Issue by Saneesh-B** [dpgaspar/Flask-AppBuilder#633]
Any ideas to implement geoalchemy2 support to Appbuilder ? Seems like this could be a great addition.

**Comment by dolfandringa** [comment]
@Saneesh-B I am making an addon [fab_addon_geoalchemy](https://github.com/dolfandringa/fab_addon_geoalchemy/) for this. It's still early days, and help is welcome, but I am using it right now to have display and edit widgets for Geometry(POINT) data with a leaflet map and geolocation. I would be happy if you check it out, test it and submit issues or PRs)
