### ISSUE TITLE
Can't use Flask session object in ModelView

### ISSUE THREAD

**Issue by seniordev555** [dpgaspar/Flask-AppBuilder#635]
I saved some information in Flask session and was trying to use this information in ModelView.

For example, I've saved past filters in session and when I get back to that page, I am going to pre-load past filters to base_filters.

But it is not able to use session object in ModelView.

I can't figure out what's wrong in my implementation.

**Comment by dpgaspar** [comment]
You probably don't have a Flask context, this is a Flask question.
