### ISSUE TITLE
Change edit_template and edit widget

### ISSUE THREAD

**Issue by jreg2k** [dpgaspar/Flask-AppBuilder#638]
Hello,

I am new to flask and flask app builder and I want to change the edit widget to have the edit fields split on two (or more) tabs.

How can I do ? Do you have some example for starters like me ?

Thnaks for your help.

**Comment by dpgaspar** [comment]
Docs: http://flask-appbuilder.readthedocs.io/en/latest/templates.html#widgets

Look how it's actually done: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/widgets/form.html

Hope it helps.

**Comment by jreg2k** [comment]
Thanks for your help. I think I can do something with that :+1:
