### ISSUE TITLE
Custom Field Conversion

### ISSUE THREAD

**Issue by jgao54** [dpgaspar/Flask-AppBuilder#642]
Curious if there is a way to override the default field conversion without creating an entire custom form.
For example, given a String column, I'd like to use a SelectFIeld for the input instead.

**Comment by tserafim** [comment]
I guess there is no easy way to override the default field conversion. But you also don't have to create an entire form.

You can simply override the default field with the field you want, as explained [here](http://flask-appbuilder.readthedocs.io/en/latest/advanced.html#forms-readonly-fields). You just gotta make sure the dictionary key has the same value as the field name.
