### ISSUE TITLE
create-admin error: There in no appbuilder var on your package, you can use appbuilder parameter to config

### ISSUE THREAD

**Issue by niks-git** [dpgaspar/Flask-AppBuilder#643]
Hi @dpgaspar 

I followed all the installation steps on my Windows 10 machine to install flask_appbuilder. Then I downloaded the skeleton app using the command : "fabmanager create-app". But when i issue the command: "fabmanager create-admin" from the newly created skeleton app dir, it throws the error: 
"There in no appbuilder var on your package, you can use appbuilder parameter to config".

I checked the app/__init__.py file, it does contain the appbuilder var. Here is dump of that file:
```
import logging
from flask import Flask
from flask_appbuilder import SQLA, AppBuilder

logging.basicConfig(format='%(asctime)s:%(levelname)s:%(name)s:%(message)s')
logging.getLogger().setLevel(logging.DEBUG)

app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)
appbuilder = AppBuilder(app, db.session)

from app import views
```
I tried issuing the same command with admin rights, but no success.
As per the documentation, if we try to use a different name (other that appbuilder), we can make use of --appbuilder option to configure that, but in my case I am not doing any such thing.

Here is a dump of pwd and ls commands from the directory where the command is issued:
`PS C:\Users\nikhil.sharma\Home\Work\Code\Flask-AppBuilder\fab_uploads> pwd

Path
----
C:\Users\nikhil.sharma\Home\Work\Code\Flask-AppBuilder\fab_uploads

PS C:\Users\nikhil.sharma\Home\Work\Code\Flask-AppBuilder\fab_uploads> ls

    Directory: C:\Users\nikhil.sharma\Home\Work\Code\Flask-AppBuilder\fab_uploads

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/7/2017  11:37 AM                app
d-----        11/7/2017  11:37 AM                babel
d-----        11/7/2017  11:37 AM                __pycache__
-a----       10/31/2017   5:13 PM           2196 config.py
-a----        9/19/2017   3:21 PM            225 README.rst
-a----        9/21/2017   3:02 PM             66 run.py`

Please suggest a solution for this.
NOTE: I have posted the same problem statement on another closed thread: https://github.com/dpgaspar/Flask-AppBuilder/issues/229

**Comment by niks-git** [comment]
One solution that I could come up with was shifting python version. Earlier I was using Python 3.6.3 that came bundled with Anaconda. But on my team-mate's suggestion, I installed stand alone python 3.6.0, and it worked!

Not an ideal solution to the problem here, just a workaround for someone facing similar problem.

**Comment by sjones-hep-ph-liv-ac-uk** [comment]
delete the app package, e.g. rm -rf /usr/lib/python3.4/site-packages/app
