### ISSUE TITLE
Forms - Override automatic form creation - an example

### ISSUE THREAD

**Issue by jreg2k** [dpgaspar/Flask-AppBuilder#645]
Hello,

Is there some example for "Forms - Override automatic form creation" ? I have read this : https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/advanced.rst and it was helpful to understand how thing works. Now I was wondering if there is some example of how "AddFormWTF" can be implemented ?

Regards

**Comment by jgao54** [comment]
Hi @jreg2k All the forms in FAB in inherits from FlaskForm.  I recommend taking a look at https://flask-wtf.readthedocs.io/en/stable/quickstart.html#creating-forms. Hope it helps~

**Comment by jreg2k** [comment]
Hi @jgao54  thanks for this information. I will take a look.
