### ISSUE TITLE
Using database views

### ISSUE THREAD

**Issue by npetrusic** [dpgaspar/Flask-AppBuilder#646]
Hello,
I was wondering if FAB has support for database views (not MVC views, but virtual tables)?
Thanks

**Comment by dpgaspar** [comment]
Yes this is possible, take a look at: 
https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quicksqlviews

You have to previously create the view, and then map in as an SQLAlchemy Model, on this example this happens on ContactGroupView
