### ISSUE TITLE
Accesing database and models from cutomized index page.

### ISSUE THREAD

**Issue by gmartindelcye** [dpgaspar/Flask-AppBuilder#654]
This issue is the result on the working of Issue  #627.

I need an index page that show a list of workshops and the student register for each workshop. I follow the instructions to customize the index page and is working. Now,

How to access de database and models to send the workshop object to the templates that is writen to take the data and display it as desire? The models  are the same as the issue  #627.

My index.py looks like this:

    from flask_appbuilder import IndexView
    from .models import Workshop
    from app import db

    class MyIndexView(IndexView):
        index_template = 'my_index.html'

        @expose('/')
        def index(self):
            self.update_redirect()
            workshops = db.session.query(Workshop).order_by(Workshop.id).all()
        return self.render_template(self.index_template, workshops=workshops, appbuilder=self.appbuilder)

But I keep getting:

    Was unable to import app Error: cannot import name db

The import works on views.py but not index.py. I don't get it!

**Comment by gmartindelcye** [comment]
Found the answer!!! Here it is for whomever need it.

    from flask_appbuilder import IndexView
    from flask_appbuilder.views import expose
    from flask_appbuilder.models.sqla.interface import SQLAInterface
    from .models import Workshop

class MyIndexView(IndexView):
    index_template = 'my_index.html'
    datamodel = SQLAInterface(Workshop)

    @expose('/')
    def index(self):
        self.update_redirect()
        workshops = self.datamodel.session.query(Workshop).order_by(Workshop.id).all()
        return self.render_template(self.index_template, workshops=workshops, appbuilder=self.appbuilder)

**Comment by Surge-Ricky** [comment]
> 

THANK YOU SO MUCH!!!!!!!!!!!! Your answer helped me out. Searched all over. I was like "WHY CAN I NOT IMPORT THE DB????????"

![image](https://user-images.githubusercontent.com/88600708/224522746-ea75b39d-4c1a-483e-a36c-b4b072391613.png)
