### ISSUE TITLE
How can I edit this form action?

### ISSUE THREAD

**Issue by Yuanmu93** [dpgaspar/Flask-AppBuilder#657]
Hi;
I am new to flask and flask_appbuilder and When I create a new role and want add some existing permssion on views and menus to this role. 
That will be difficult to operate when I have many views. Whether there can be multiple choice or select all function.

Thanks for your help.

![_20171201142013](https://user-images.githubusercontent.com/20705403/33471198-1c27869c-d6a7-11e7-836d-1eaa87828fc1.png)

**Comment by Yuanmu93** [comment]
Or can you tell me where is the related code (I tried to find it but I didn't find it), I will try to override  to implement my own function.

**Comment by Yuanmu93** [comment]
Forgive me poor english.

**Comment by dpgaspar** [comment]
Yes FAB role/permissions is very granular, so this can be a bit tricky.
The creation of new permissions related to a ModelView is always the same (this is an automatic procedure).

Go to the Security-> Permission on Views/Menus and study the generated permissions for each ModelView, these are the permissions you can associate to a Role

**Comment by Yuanmu93** [comment]
@dpgaspar 
Thanks a lot.
