### ISSUE TITLE
lookup from another tables field

### ISSUE THREAD

**Issue by aydin-ozcan** [dpgaspar/Flask-AppBuilder#664]
Hello ,

How can i define lookups in my views delivered from ModelView.
Lets say I have TableX and a field named TableX1 .
In my TableY's view , when user editing field TableY2 , let users select value from combobox .
And I want to  populate the combobox from TableX1 but using TableY1's values for filtering TableX1's values.
Foreign Key is not a suitable solution.

Thanks in advance.

**Comment by aydin-ozcan** [comment]
Hello , 

Further reading the documentation I found that  add_form_extra_fields  and  AJAXSelectField is for this job. 
But it looks like I can't define custom endpoints in my ModelView inherited view , and use that with 
AJAXSelectField , am I right?

**Comment by dpgaspar** [comment]
Have not tried it, but should work, as long as you obey the same principles.
So you need to support filters, take a look at: 
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/views.py#L373

**Comment by aydin-ozcan** [comment]
I tried , first I define custom endpoint on my ModelView which simply return "Hello" , and try to call it from Url , but it didn't work like it did with BaseView. Guess no custom endpoints on ModelView.

If it is the intended behevier do you advice using  some other BaseView for custom endpoint instead of related ModelView.

Maybe I am miss understanding the ModelView concept  in FAB, it is not like  PresentationModel 
where we can also implement  business logic .
