### ISSUE TITLE
Getting related fields properties in related views

### ISSUE THREAD

**Issue by npetrusic** [dpgaspar/Flask-AppBuilder#673]
Hi,
I want to know if it's possible to get an attribute value from base view model out of the related view.
E.g. I have a model Category with a CategoryModelView and I have a related view FamilyCategoryModelView based on FamilyCategoryModel. What I want is to get Category name value from FamilCategoryModelView so that I can override the template and use the name value on the page.
Thanks!

**Comment by dpgaspar** [comment]
You can use dotted notation when defining the columns on ModelView, will this solve you use case?

If not could you be more specific, post your code for example?

**Comment by npetrusic** [comment]
it is actually a problem of getting the uneditable fields visible (simplified)
