### ISSUE TITLE
Remove Permission from View Error: 'list' object has no attribute 'permission'

### ISSUE THREAD

**Issue by john-bodley** [dpgaspar/Flask-AppBuilder#683]
The `ERROR:flask_appbuilder.security.sqla.manager:Remove Permission from View Error: 'list' object has no attribute 'permission'` error is raised [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/sqla/manager.py#L353) as the `pv` variable is incorrectly overwritten to be a list (empty in this case).

The following change should be suffice,
```
if not self.get_session.query(self.permissionview_model).filter_by(permission=pv.permission).all()
    self.del_permission(pv.permission.name)
```

**Comment by dpgaspar** [comment]
I'm not aware of this error, can you please post:
- FAB version
- steps to reproduce the error (code)
- the log (not just one line)

and maybe i'm not understanding but
is'nt this:
```
pv = self.get_session.query(self.permissionview_model).filter_by(permission=pv.permission).all()
if not pv:
    self.del_permission(pv.permission.name)
````

equal to this:
````
if not self.get_session.query(self.permissionview_model).filter_by(permission=pv.permission).all()
    self.del_permission(pv.permission.name)
````

**Comment by john-bodley** [comment]
@dpgaspar the SQLAlchemy [Query.all](http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.all) method returns a list which is re-assigned to the `pv` variable. If this is empty, i.e., `[]` then `not pv` evaluates to `True` and 
```
self.del_permission(pv.permission.name)
```
is equivalently 
```
self.del_permission([].permission.name)
```
hence the exception. The suggested change ensures that the original permission view model is deleted if and only if there are no permissions associated with it.

**Comment by mistercrunch** [comment]
LGTM, @dpgaspar ok with merging this?
