### ISSUE TITLE
How remove duplicate related views?

### ISSUE THREAD

**Issue by allankliu** [dpgaspar/Flask-AppBuilder#684]
In my application, there are three tables:

- user_table
- device_table
- permit_table, with foreign keys to user.id and device.id

Since there are two roles, host and normal users. I defined two ModelView classes:
```

class PermitView(ModelView):
    datamodel = SQLAInterface(Permit)

    label_columns = {}
    list_columns = ['device','owner','submit','approve']  
    #related_views = [DeviceView]

    @expose('/mylist')
    def mylist(self):
        msg = _("My list")
        return self.render_template('testpage.html', msg = msg)

class PermitHostView(PermitView):
    base_filters = [['isHost', FilterEqualFunction, 'host'],]

class PermitUserView(PermitView):
    base_filters = [['isHost', FilterEqualFunction, 'user'],]

class DeviceView(ModelView):        
    datamodel = SQLAInterface(Device)
    related_views = [AccountView, PermitView, EventView]

```

But if I visit /deviceview/list and click one of the record like /deviceview/show/1, there are two **related views of permit**. I guess it is generated by FAB automatically by parsing underlaying foreign key relationship of views.

I want to know, how to remove duplicate one and assign proper one? Or should I remove the related view and embedded the permit url as a special column in device view ?

**Comment by dpgaspar** [comment]
It's kind of funny, it's not because of the foreign keys, it's because your using the parent class.

if you want to use inheritance on ModelView's (and please do, it's great) do it like this:

````
class BasePermitView(ModelView):
    datamodel = SQLAInterface(Permit)

    label_columns = {}
    list_columns = ['device','owner','submit','approve']  
    #related_views = [DeviceView]

    @expose('/mylist')
    def mylist(self):
        msg = _("My list")
        return self.render_template('testpage.html', msg = msg)

class PermitView(BasePermitView):
    pass

class PermitHostView(BasePermitView):
    base_filters = [['isHost', FilterEqualFunction, 'host'],]

class PermitUserView(BasePermitView):
    base_filters = [['isHost', FilterEqualFunction, 'user'],]

class DeviceView(ModelView):        
    datamodel = SQLAInterface(Device)
    related_views = [AccountView, PermitView, EventView]


```

**Comment by allankliu** [comment]
OK, I got it. I should one of the subclass as related_views.
