### ISSUE TITLE
How to abstract external RESTFul API in FAB? Generic data source or Oauth?

### ISSUE THREAD

**Issue by allankliu** [dpgaspar/Flask-AppBuilder#697]
Since I seperate my IoT servers into two layers, one layer is for device connect and management, which was written in Cyclone/Twisted, the application layer is written with FAB. 

The device server offers a RESTFul API for external applications, with apiKey/apiSecret to exchange token. It is a little different from oauth logon. since there is no callback_redirect_url.

```
https://domain/api/login , post with appKey/appSecret, returns access_token
https://domain/api/devices, get with access_token, userId, returns device list belongs to userId.
```

I prefer using it as a basic backend with long-live TCP/TLS like RDBS/redis. Even I can use requests in exposed URL handlers, I hope to find a proper method to lauch the authentication during application bootup just like MySQL/Redis do. And the applications are working like simple call to RDBS TCP link.

I have checked Tweet demo and Generic data source demo in examples. The tweet demo requires a complete oauth provider to be implemented, the generic data source is different from my case.

**Comment by dpgaspar** [comment]
Hi @allankliu,

This is not clear to me:
- You have written a simple Auth provider and you want FAB to use it for authentication?
- You want to retrieve the access_token on FAB bootup?

**Comment by allankliu** [comment]
Hi, @dpgaspar 

So far, I have implemented a REST client inside a flask handler. The flask handler will access external REST API via apiKey/apiSecret to get token, then use token to access external resources in JSON. But this approach will change token in every single API call. I hope to keep the token for a certain period, since token doesn't need to change every time. 

The situation is quite similar to database connection of MySQL/Redis. Of course, it is better to get the token during FAB bootup.
