### ISSUE TITLE
Deploy on AWS

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#698]
How can I deploy on AWS?
I tried to deploy directly on EC2, and I can start the app, but It seems I can not access the web.
Another way I tried is deploying through beanstalk, but I can access the web also.
Please help me.

**Comment by dpgaspar** [comment]
This is a Flask or AWS question.
"
I tried to deploy directly on EC2, and I can start the app, but It seems I can not access the web.
"
Security group? listening on localhost? etc...

**Comment by francisliyy** [comment]
Yes, I solved it. It is a security reason, need to add protocol and port support, then it can be accessed. First I thought maybe I need to do some specific configuration for Flask-AppBuild, so I address the issue here.
And for the beanstalk, it's still not working. I thought it's because Flask AppBuilder uses "fabmanager run" to start the programmer, AWS cannot recognize it.And it is not working.

**Comment by dpgaspar** [comment]
Don't use fabmanager run on production.

Create an application.py at the root of your project:

"""
    Init Python app for Apache
"""
from app import app as application

**Comment by francisliyy** [comment]
Then how to start it? I tried python application.py. it is not working.
Sorry, I am new in Python

**Comment by tserafim** [comment]
Flask-AppBuilder uses [flask](http://flask.pocoo.org/).
If you google 'how to deploy flask-appbuilder' you might not find many results, but I am sure you´ll find lots of stuff if you search for just 'how to deploy flask'. [Example 1](https://help.pythonanywhere.com/pages/Flask/), [example 2](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux-even-on-the-raspberry-pi) and [example 3](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-centos-7).

That being said, Flask documentation has a session on [deployment](http://flask.pocoo.org/docs/0.12/deploying/#deployment), but it may be a bit dry if you don´t know python or any of those deployment environments(Heroku, aws...).

**Comment by francisliyy** [comment]
@tserafim Thanks a lot. I will follow the examples you gave.
Appreciating your help.
