### ISSUE TITLE
Non-unique associations

### ISSUE THREAD

**Issue by john-bodley** [dpgaspar/Flask-AppBuilder#699]
On Superset we've noticed instances where the associations defined by the following tables:
- ab_permission_view
- ab_permission_view_role
- ab_user_role

are non-unique, i.e., queries of the form
```
SELECT 
    user_id,
    role_id,
    COUNT(1)
FROM 
    ab_user_role
GROUP BY 
    user_id,
    role_id
HAVING COUNT(1) > 1
```
return a number of records. Although I haven't seen this cause a problem in the web app REST API calls for updating the users associated with a specific role (`/roles/api/update/<id>`) will fail. It seems the solution is simply to enforce uniqueness constraints on these tables.

**Comment by dpgaspar** [comment]
Release on 1.9.7
