### ISSUE TITLE
Can I use bootstrap4 in the web page

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#705]
The F.A.B is based on bootstrap3, I want to use some beautiful design based on boostrap4, is there a way I can use it?

**Comment by tserafim** [comment]
FAB is fully customizable as you can provide your own jinja2 templates.

Check the [Templates - CSS and Javascript](http://flask-appbuilder.readthedocs.io/en/latest/templates.html#css-and-javascript) section on the docs.

And here is link to the [included templates](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/templates/appbuilder). This might give you some inspiration.

**Comment by francisliyy** [comment]
Yes, I have tried to include bootstrap4's css file in head_css part, but I think may be there are some conflict between version 3 and 4. The web page looks not that right.

**Comment by dpgaspar** [comment]
Yes there are breaking change on bootstrap 3 to 4. You could use it, but you have to tweek/change all the views that use it.

You can always use bootstrap4 and use only youre created views, just use FAB for security and controllers
