### ISSUE TITLE
BaseQuery not available in table classes

### ISSUE THREAD

**Issue by chris-hailstorm** [dpgaspar/Flask-AppBuilder#707]
Using SQLAlchemy without FAB:

    from flask import Flask
    from flask_sqlalchemy import SQLAlchemy
    app = Flask(__name__)
    db = SQLAlchemy(app)
    (add models)
    m.Identity.query.first()
    <database.models.Identity {"uuid": "3a526b5e"}>

Same, substituting FAB + SQLA:

    from flask import Flask
    from flask_appbuilder import SQLA
    app = Flask(__name__)
    db = SQLA(app)
    (add models)
    m.Identity.query.first()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/chris/.virtualenvs/power/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
    AttributeError: type object 'Identity' has no attribute 'query_class'

It appears the Class.query approach isn't available when using the FAB-provided SQLA.

It seems wrong that the subclassed SQLAlchemy would no longer have this capability.

**Comment by harmon** [comment]
@chris-hailstorm Try this:

```

from flask import Flask
from flask_appbuilder import SQLA
from flask_appbuilder.models.sqla.interface import SQLAInterface
app = Flask(__name__)
db = SQLA(app)
t = SQLAInterface(Tool, db.session)
t.query()
# => (2, [Record 1, Record 2])
```

**Comment by dpgaspar** [comment]
On FAB session is not attached to the Models, use it like on SQLAlchemy:

```
...
db = SQLAlchemy(app)
db.session.query(Indentity).all()
```

**Comment by harmon** [comment]
@dpgaspar Hi, is there a specific reason we can't assign the query_class? The `model.query` property is essentially useless without it, so I'm not sure why FAB would even assign it if we don't have an underlying query_class. I'm still new to the SqlAlchemy world, so I apologize if I don't understand how FAB is using sessions under the hood. Thanks!

```
class MySQLA(SQLA):
    def make_declarative_base(self, model, metadata=None):
        model = super(MySQLA, self).make_declarative_base(model, metadata=metadata)

        if not getattr(model, 'query_class', None):
            model.query_class = self.Query

        return model

######

MyModel.query.all()   # => [MyModel1, MyModel2]
```
