### ISSUE TITLE
password for test example?

### ISSUE THREAD

**Issue by datatalking** [dpgaspar/Flask-AppBuilder#713]
I'm looking to implement this app and I need to look at the example that is given but there is no password or username posted as far as... 'use this' to gain access as a test user.

**Comment by MichaelPereira** [comment]
You have to create the first admin user yourself via [the CLI command](http://flask-appbuilder.readthedocs.io/en/latest/fabmanager.html#create-admin-create-an-admin-user) or by calling the code behind yourself in the initialization part of your application

**Comment by datatalking** [comment]
Solved this, thankyou
