### ISSUE TITLE
Can mongodb have the AuditMixin?

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#717]
I upload files and save it in MongoDB, can it also have AuditMixin to include the create user, create time, modify user, modify time inside?
I added the AuditMixin to my model, but it seems not work.

**Comment by francisliyy** [comment]
I looked into the code in 'flask_appbuilder.security.mongoengine.models', in User class, though it has the code like 'created_by = ReferenceField('self', default=get_user_id())', I can not get created_by info when creating a new user. Is it possible to get current user in any documents?
I really need some help.

**Comment by masrayie** [comment]
how to solve it ? i got this problem too, thankyou
