### ISSUE TITLE
Using OAUTH Bearer Token on REST endpoints

### ISSUE THREAD

**Issue by dmigo** [dpgaspar/Flask-AppBuilder#722]
Is it possible to somehow configure my app so that its API would accept `Authorization` header containing `Bearer {my_token}` in it?

**Comment by dpgaspar** [comment]
I'm not a big fan also on the way security is implemented on the default API. 
This is currently not possible without heavy hacking, but you can always implement your own API endpoints and security mechanism

**Comment by dmigo** [comment]
@dpgaspar Could you probably point me in direction of the right solution?

**Comment by dpgaspar** [comment]
A simple solution could be:

Make a decorator to implement your auth:
```
def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        .... Implement HERE your authorization 
            # If unauthorized return make_json_response('', 401)
        return f(*args, **kwargs)
    return decorated

def make_json_response(data, code):
    response = make_response(jsonify(data), code)
    response.headers['Content-Type'] = "application/json"
    return response
```
Then make you're API endpoints:
````
@appbuilder.app.route('/api/v1/something/<arg1>/')
@requires_auth
def something(arg1):
     ... SOMETHING here set data=dict to return
     return make_json_response({'response': data}, 200)

```

**Comment by dmigo** [comment]
@dpgaspar Thank you! You've helped me very much.
