### ISSUE TITLE
Widget Render Template Does Not Exist

### ISSUE THREAD

**Issue by cavemancoder999** [dpgaspar/Flask-AppBuilder#729]
In widgets.py (Flask-AppBuilder/flask_appbuilder/widgets.py ),
the RenderTemplateWidget class has the template set to:
template = 'appbuilder/general/widgets/render.html'

When I look in appbuilder/general/widgets,  the render.html file is not present.

https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/templates/appbuilder/general/widgets

Was it accidentally left out ?

**Comment by dpgaspar** [comment]
RenderTemplateWidget is a base class, and your always supposed to implement it with a template and override the property. So it points to nowhere, maybe not the most elegant solution, I could have always created an empty template, but what could be the use of that  :)
