### ISSUE TITLE
can i set a relationship's field to search_column?

### ISSUE THREAD

**Issue by jiangrzh** [dpgaspar/Flask-AppBuilder#73]
hi, dpgaspar:
relationship's field to search_column?

in my models:

``` python
class HostGroup(Model):
    id = Column(Integer, Sequence('seq_gear_host_group_id'), primary_key = True, nullable = False)
    group_name = Column(String(60), nullable = False)

class Host(Model):
    id = Column(Integer, Sequence('seq_host_id'), primary_key = True, nullable = False)
    host_name = Column(String(20), nullable = False, unique = True)
    host_ip = Column(String(255), nullable = False)
    host_group_id = Column(Integer, ForeignKey(HostGroup.id), nullable = False)

    host_group = relationship(HostGroup, backref='host')

class HostLogin(Model):
    id = Column(Integer, Sequence('seq_host_id'), primary_key = True, nullable = False)
    host_id = Column(Integer, ForeignKey(Host.id), nullable = False)
    host = relationship(Host)
    login = Column(String(20), nullable = False)
    password = Column(String(40), nullable = False)
    home_path = Column(String(255), nullable = False)
    login_attr = Column(String(255), nullable = True)

class Application(Model):
    id = Column(Integer, Sequence('seq_gear_app_id'), primary_key = True, nullable = False)
    app_name = Column(String(60), nullable = False)

class AppDeploy(Model):
    id = Column(Integer, Sequence('seq_gear_app_deploy_id'), primary_key = True, nullable = False)
    app_id = Column(Integer, ForeignKey(Application.id), nullable = False)
    app =  relationship(Application)
    login_id = Column(Integer, ForeignKey(HostLogin.id), nullable = False)
    login = relationship(HostLogin)
    group_id = Column(Integer, ForeignKey(AppGroup.id), nullable = False)
    app_group = relationship(AppGroup)
```

my views:

``` python
class AppDeployAdmin(ModelView):
    datamodel = SQLAModel(AppDeploy, db.session)
    list_columns = ['app', 'app_group', 'login', 'login.host.host_group']
    search_columns = ['app', 'app_group']
```

now, if i want to search 'login.host.host_group' in AppDeployAdmin, how to set the search_column?

**Comment by dpgaspar** [comment]
Sorry for the delay. 
i would probably have to implement something to support it... 
Give sometime to look into it, next version will change some things, i will probably support MongoDB also.

Happy new year.

**Comment by jiangrzh** [comment]
how about join multi-table with datamodel for a view?

**Comment by dpgaspar** [comment]
Thank you, yes that should be the way to do it, going to try to support this next version.
It should go out early next week.

**Comment by jiangrzh** [comment]
It very lucky.
i defind model like:
'''python
class HostLogin(Model):
    __bind_key__ = 'users'
    __tablename__ = 't_gear_host_login'
    id = Column(Integer, Sequence('seq_host_id'), primary_key = True, nullable = False)
    host_id = Column(Integer, ForeignKey(Host.id), nullable = False)
    host = relationship(Host)
    login = Column(String(20), nullable = False)
    password = Column(String(40), nullable = False)
    home_path = Column(String(255), nullable = False)
    login_attr = Column(String(255), nullable = True)
    host_group = relationship('HostGroup',
                secondary="join(Host, HostGroup, Host.host_group_id == HostGroup.id)",
                primaryjoin="and_(HostLogin.host_id == Host.id)",
                uselist=True
'''

and i saw the filed in search widget:
![qq 20150107094516](https://cloud.githubusercontent.com/assets/3725828/5639471/fa5105ea-9651-11e4-95df-7f540cf7b075.png)

**Comment by jiangrzh** [comment]
It's very lucky,i make it.
I defined model like:
```python
class AppDeploy(Model):
    __bind_key__ = 'users'
    __tablename__ = 't_gear_app_deploy'
    
    id = Column(Integer, Sequence('seq_gear_app_deploy_id'), primary_key = True, nullable = False)
    app_id = Column(Integer, ForeignKey(Application.id), nullable = False)
    app =  relationship(Application)
    login_id = Column(Integer, ForeignKey(HostLogin.id), nullable = False)
    login = relationship(HostLogin)
    group_id = Column(Integer, ForeignKey(AppGroup.id), nullable = False)
    app_group = relationship(AppGroup)
    host_group = relationship('HostGroup',
                secondary="join(HostLogin, Host, HostLogin.host_id == Host.id)."
                "join(HostGroup, HostGroup.id == Host.host_group_id)",
                primaryjoin="and_(HostLogin.id == AppDeploy.login_id, Host.id == HostLogin.host_id)",
                uselist=True
                )
```

then i saw the field what i want (Host Group) in the search widget:
![qq 20150107114406](https://cloud.githubusercontent.com/assets/3725828/5640620/ab9cc752-9662-11e4-8f0c-3d4c6adbc4b4.png)
