### ISSUE TITLE
how add the different default value in Model?

### ISSUE THREAD

**Issue by LazyCountry** [dpgaspar/Flask-AppBuilder#731]
```
get_time():
    return time.time()

class MyModel(Model):
    create_time = Column(Float, default=get_time())
```

In MyModel, I need the create_time when add new record, but I saw the create_time always the same value, how can I do?

Thanks you for your help.

**Comment by tserafim** [comment]
You always get the same value cause `get_time` is evaluated when `class MyModel` is defined.
Suppose the time is 123.456 when python interpreter 'reads' your class definition. The interpreter will see `get_time()`, execute it, get the value back and than declare your class as:
```
class MyModel(Model):
    create_time = Column(Float, default=123.456)
```
To solve your problem, use `get_time` instead(without the `()`), as the `default` argument accepts a callable.
```
class MyModel(Model):
    create_time = Column(Float, default=get_time)
```

By the way, this is related to SQLAlchemy and not to Flask-AppBuilder. 
Here is a link to [SQLAlchemy docs](http://docs.sqlalchemy.org/en/latest/index.html), and a link to a [StackOverflow question](https://stackoverflow.com/questions/13370317/sqlalchemy-default-datetime) that might interest you.

**Comment by LazyCountry** [comment]
Thank you for you help.
