### ISSUE TITLE
Running flask on a dynamic (ENV variable) port

### ISSUE THREAD

**Issue by smokinjoe** [dpgaspar/Flask-AppBuilder#733]
I'm struggling mightily to get my docker-compose flask app running on Heroku. I *believe* what I need to do is properly expose the port that the app is running on (Heroku does not recognize EXPOSE). Unfortunately I can no figure out, for the life of me, how to perform a `flask run` where the port is assigned with an ENV variable.

For example (source is https://github.com/heroku/alpinehelloworld/blob/master/Dockerfile):

```
# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku			
CMD gunicorn --bind 0.0.0.0:$PORT wsgi 
```

However, I don't use `gunicorn` and can not figure out the equivalent for `flask run`. The code I use for local development that works fine is:

`CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]`

But I've tried replacing the `5000` with `$PORT`. I've tried replacing the whole line with `CMD flask run --host=0.0.0.0 --port=$PORT` and I keep getting issues that `port` needs to be an integer.

Is what I'm trying to do even possible with flask?

**Comment by smokinjoe** [comment]
So I've come to realize that I can not accomplish want I want by having the port being read dynamically in my `Dockerfile`. Took me a little longer than I'm willing to admit to learn that since I build the container locally to push to Heroku, it's impossible to locally use Heroku ENV vars!

Since I'm trying to get this docker container running on Heroku, instead of having the original `CMD` in the above comment of mine, I have:

    CMD python ./app.py

(Looking at it, I probably don't need the `./` but whatever, it works)

_Anyway_, I now have the running taking place in that `app.py` file:

    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)

And bam. Everything works great locally _and_ on Heroku!

**Comment by birkmarcus** [comment]
Thank you. This saved me. 
To get both flask's and gunicorn's ports synched with Heroku's dynamic port worked.
