### ISSUE TITLE
how to use a global sqlalchemy transaction to warp the delete/add

### ISSUE THREAD

**Issue by cw1427** [dpgaspar/Flask-AppBuilder#734]
As we known, in Flask-AppBuilder, we used sqlalchemy as the db layer which explicitly use session.commit()/ session/rollback() to control the transaction in the basic CRUD method in SQLInterface.
But how to unit those CRUD method in a global transaction ?

**Comment by dpgaspar** [comment]
This is not a flask-appbuilder question but take a look at: http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#using-savepoint
