### ISSUE TITLE
Views automatically sorted on multiple columns

### ISSUE THREAD

**Issue by bill-s** [dpgaspar/Flask-AppBuilder#736]
'base_order' allows sorting on a single table column.  It would be nice to support multiple column sorting through it.  For example, a table with companies and employees.  First sort on companies and then on company employees.

**Comment by dpgaspar** [comment]
Could be a nice enhancement, anyone else interested on this?

**Comment by sunshinetan** [comment]
i got the same problem，then how to solve it

**Comment by luixx** [comment]
i also would like these feature. i have right now the same problem

**Comment by zhangboli51** [comment]
it'll be great to have this feature
