### ISSUE TITLE
How best to add support for unsupported SA Column type (GeoAlchemy)

### ISSUE THREAD

**Issue by dolfandringa** [dpgaspar/Flask-AppBuilder#739]
I would like to integrate GeoAlchemy support into Flask-Appbuilder, similar to the way [Flask-Admin does it](https://github.com/flask-admin/flask-admin/tree/master/flask_admin/contrib/geoa) using leaflet.js. What would be the best way to go about this? I read issues #186 and #694, but this is more complicated I guess. 
Am I correct in guessing that the best way is to create a separate interface that inherits from SQLAInterface that adds support for the Geometry or Geography columns for GeoAlchemy2? And then create a widget with wtforms that does the display for it? 

I find the magic of the SQLAInterface a bit hard to understand quickly (or I am just too lazy) so some pointers in the right direction would be very much appreciated.
I'd be happy to contribute code in this direction back to flask  appbuilder if there is interest, or just document it if it is more trivial than I thought.

**Comment by cw1427** [comment]
That would be great to integrate GeoAlchemy into FAB. For my understanding, SQLAInterface is just an interface wrapped some basic Flask-SQLAlchemy CRUD operation. You can easily extend it as specify GeoAlchemy based Interface to overwrite the CRUD operation.

BTW, what is the use case when you use the GeeoAlchemy for the PostGIS ?

**Comment by dolfandringa** [comment]
I am developing a datamanagement application for environmental monitoring data. People in the field will record data about animal sightings basically and report them. Location is needed in there. Aside from a mobile client reporting data, I also want some staff be able to enter paper reports (legacy). Location is vital so I want them to add the location using a map display. Since GIS analyses are an important part, PostGIS/Geometry is important (plaintext coordinates are not enough). I will look into extending SQLAInterface for it. I probably also need to create my own widget for WTForms I guess.

**Comment by dpgaspar** [comment]
On a quick review I would say you need to change:

( add new column types )
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/interface.py

Update the conversion_tables if it makes sense to filter data by these fields:
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/filters.py

The view part, isn't clear, we probably need a new special widget for these fields based on leaflet.js?

**Comment by dolfandringa** [comment]
Just for others coming across this question, I am currently working on an flask appbuilder addon for this: https://github.com/dolfandringa/fab_addon_geoalchemy
