### ISSUE TITLE
LDAP user registration and admin user

### ISSUE THREAD

**Issue by hsum** [dpgaspar/Flask-AppBuilder#74]
If you use LDAP and do not set AUTH_USER_REGISTRATION = True, the security manager tries to find the user in the database, but fails and he cannot start a session.

flask_appbuilder/security/manager.py:406
```
if self.auth_user_registration and user is None:
```
Would it be reasonable to have AUTH_USER_REGISTRATION default to True when LDAP is in use or document the config section accordingly?

Since I switched to using LDAP, I no longer have an admin user.  We can have FAB create those ab_user rows, but they will have role 'Public'.   I went into app.db and did an sql update to make myself role_id = 1 (Admin).  Is there a less error prone way to do this?  I didn't see anything in the documentation.  Perhaps one option would be to first use the local db (for exceptions like the admin user) and then LDAP to authenticate users.

thank you!

**Comment by dpgaspar** [comment]
Happy new Year! 

Nice idea, and it's from a maker of Flask, i'll look into it. I Will keep this open until i have a solution.

**Comment by dpgaspar** [comment]
I found this also: http://flask.pocoo.org/docs/dev/cli/

This could be very interesting.

**Comment by dpgaspar** [comment]
New version will have a command line utility to do it.

You will be able to:

Create a fresh app
Create Admin users
Reset User passwords
Babel extract
Babel Compile
Run dev server

(and maybe some more).

**Comment by hsum** [comment]
Awesome!  Thank you.
