### ISSUE TITLE
project can't be access

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#746]
![screen shot 2018-05-17 at 12 43 46 pm](https://user-images.githubusercontent.com/6333979/40191657-1fcab01a-59d0-11e8-851e-f5f84d1ec9f3.png)

this is the screen shot, It seems "permission.view_menu" can be accessed. 
This problem appears when I try add base_permission = ['can_list'] in one of my View Class. But even I remove base_permission = ['can_list'], the problem still there. I thought it might be permission problem, so I try to restore my database,but the problem is still there.
I don't konw why, please help me, thank you

**Comment by dpgaspar** [comment]
Thats strange,

could you please clear your cookies and add the security clean up: http://flask-appbuilder.readthedocs.io/en/latest/security.html#automatic-cleanup

**Comment by francisliyy** [comment]
appbuilder.security_cleanup(), I tried it, but it is not working

**Comment by francisliyy** [comment]
additionally, my database is mongodb, will it related to this problem?

**Comment by francisliyy** [comment]
Now, I just try to add another menu or link, then this will happen.
I add another method in one model view class called ProcessView, the method is simple, nothing inside, just return to render another template. Then use add_link,like:
appbuilder.add_link("Advance Compare", href="/processview/heatmapCmp/", icon='fa-folder-open-o', category='MSE')

then this problem appeared, attached the screenshot 
![screen shot 2018-05-23 at 10 30 34 am](https://user-images.githubusercontent.com/6333979/40431265-14ddd49e-5e75-11e8-8c84-eea8631d427e.png)

**Comment by francisliyy** [comment]
![screen shot 2018-05-23 at 10 49 05 am](https://user-images.githubusercontent.com/6333979/40432160-00909a10-5e77-11e8-8c8f-40a59f02191d.png)
this permission is from collections permission or permission_view, I can't find this row in collections

**Comment by francisliyy** [comment]
I thought maybe this is the problem, I can't find this record in both permission and permission_view.
DBRef('permission_view', ObjectId('5afed339360e2e8f6dc5aace'))

I restarted the application, cleared the cache of the browser, even change a browser, quit the virtual env and reenter then start the application, it was still not working. Where does the framework get this ObjectId('5afed339360e2e8f6dc5aace') for the permission?

**Comment by francisliyy** [comment]
is it from collection role? the framework didn't remove the record from the role.permissions

**Comment by francisliyy** [comment]
It is probably the problem, I remove ObjectId('5afed339360e2e8f6dc5aace') from role.permissions, then it is working

**Comment by dolfandringa** [comment]
@francisliyy It would help a lot if you ask a question, to provide a minimal piece of example code that replicates your problem that we can try out. For us it is very difficult to help you if we can't replicate the problem ourselves. Do you still have the problem? If not, I will close it.

**Comment by redalert253225** [comment]
excuse me , in my case:
i use mongo ,
if i use  `appbuilder.add_view`or`appbuilder.add_link`
```
appbuilder.add_view_no_menu(TestView)
appbuilder.add_view(AddInvoiceNumberView, "AddInvoiceNumberView", icon="fa-hand-o-up", label=_("Add_Invoice_Number"),
        category="MyForms", category_icon="fa-cloud-upload",category_label=_("Forms"))
appbuilder.add_view(InvoiceNumberView, "InvoiceNumberView", icon="fa-th-list", label=_("Invoice_Number"),
        category="MyDataBase", category_icon="fa-database",category_label=_("Database"))
appbuilder.add_view(YuTsaiLprCashJournalView, "YuTsaiLprCashJournalView", icon="fa-th-list", label=_("Yu Tsai Lpr Cash Journal"),category="MyDataBase")
appbuilder.security_cleanup() 
```
and run program , when i login ,i will get error , but it not always
```
builtin.AttributeError
AttributeError: view_menu
```
when i rerun `fabmanager run`
i will get more DBRef('permission_view', ObjectId('XXXXXXXXXX'))
flask_appbuilder/security/manager.py:
```
def _has_view_access(self, user, permission_name, view_name):
        roles = user.roles
        for role in roles:
            permissions = role.permissions
            if permissions:
                for permission in permissions:
                    if  (hasattr(permission,'view_menu')) and (view_name == permission.view_menu.name) and (permission_name == permission.permission.name):  #i add  (hasattr(permission,'view_menu'))
                        return True
        return False
```
### i think,
it only happend when the `permission` get the `DBRef('permission_view', ObjectId('XXXXXXXXXX'))` 

now , it can work  ,but  more DBRef('permission_view', ObjectId('XXXXXXXXXX'))

Admin
--
[can this form get on ResetPasswordView, can this form post on ResetPasswordView, can this form get on ResetMyPasswordView, can this form post on ResetMyPasswordView, can this form get on UserInfoEditView, can this form post on UserInfoEditView, can list on UserDBModelView, can download on UserDBModelView, can delete on UserDBModelView, can add on UserDBModelView, can show on UserDBModelView, can userinfo on UserDBModelView, can edit on UserDBModelView, resetmypassword on UserDBModelView, resetpasswords on UserDBModelView, userinfoedit on UserDBModelView, menu access on List Users, menu access on Security, can list on RoleModelView, can download on RoleModelView, can delete on RoleModelView, can add on RoleModelView, can show on RoleModelView, can edit on RoleModelView, Copy Role on RoleModelView, menu access on List Roles, can chart on UserStatsChartView, menu access on User's Statistics, can list on PermissionModelView, menu access on Base Permissions, can list on ViewMenuModelView, menu access on Views/Menus, can list on PermissionViewModelView, menu access on Permission on Views/Menus, can test on TestView, can this form post on AddInvoiceNumberView, can this form get on AddInvoiceNumberView, DBRef('permission_view', ObjectId('5bcc880120d8e7165caa31b0')), menu access on MyForms, DBRef('permission_view', ObjectId('5bcc880220d8e716621902a6')), DBRef('permission_view', ObjectId('5bcc8b9320d8e716a2ce97b7')), DBRef('permission_view', ObjectId('5bcc8ba320d8e716ac7742fa')), DBRef('permission_view', ObjectId('5bcc8ba420d8e716b1d19789')), DBRef('permission_view', ObjectId('5bcc8c0820d8e716f3c91e0b')), can delete on InvoiceNumberView, can show on InvoiceNumberView, can download on InvoiceNumberView, can edit on InvoiceNumberView, can add on InvoiceNumberView, can list on InvoiceNumberView, muldelete on InvoiceNumberView, DBRef('permission_view', ObjectId('5bcc8c0820d8e716f3c91e15')), menu access on MyDataBase, DBRef('permission_view', ObjectId('5bcc8c3a20d8e716fd4d6c7e')), DBRef('permission_view', ObjectId('5bcc8c3a20d8e716fd4d6c7f')), DBRef('permission_view', ObjectId('5bcc8c3b20d8e71702ca59c6')), DBRef('permission_view', ObjectId('5bcc8c3b20d8e71702ca59c7')), DBRef('permission_view', ObjectId('5bcc8ead20d8e7175779bc7d')), DBRef('permission_view', ObjectId('5bcc8ead20d8e7175779bc7e')), DBRef('permission_view', ObjectId('5bcc8eaf20d8e7175c2fcf22')), DBRef('permission_view', ObjectId('5bcc8eaf20d8e7175c2fcf23')), DBRef('permission_view', ObjectId('5bcc8ec820d8e71768a0cd3e')), DBRef('permission_view', ObjectId('5bcc8ec820d8e71768a0cd3f')), can list on YuTsaiLprCashJournalView, can downloadExcel on YuTsaiLprCashJournalView, DBRef('permission_view', ObjectId('5bcc8ec820d8e71768a0cd44')), DBRef('permission_view', ObjectId('5bcc8ed020d8e7176ff4074c')), DBRef('permission_view', ObjectId('5bcc8ed020d8e7176ff4074d')), DBRef('permission_view', ObjectId('5bcc8ed020d8e7176ff4074e')), DBRef('permission_view', ObjectId('5bcc8ed120d8e71774c3793f')), DBRef('permission_view', ObjectId('5bcc8ed120d8e71774c37940')), DBRef('permission_view', ObjectId('5bcc8ed220d8e71774c37941')), DBRef('permission_view', ObjectId('5bcc930c20d8e7185f418cad')), DBRef('permission_view', ObjectId('5bcc930c20d8e7185f418cae')), DBRef('permission_view', ObjectId('5bcc930c20d8e7185f418caf')), DBRef('permission_view', ObjectId('5bcc933220d8e71869ea7484')), DBRef('permission_view', ObjectId('5bcc933220d8e71869ea7485')), DBRef('permission_view', ObjectId('5bcc933220d8e71869ea7486')), DBRef('permission_view', ObjectId('5bcc935120d8e71875a06a9c')), DBRef('permission_view', ObjectId('5bcc935120d8e71875a06a9d')), DBRef('permission_view', ObjectId('5bcc935120d8e71875a06a9e')), DBRef('permission_view', ObjectId('5bcc936420d8e7187f3cddcf')), DBRef('permission_view', ObjectId('5bcc936420d8e7187f3cddd0')), DBRef('permission_view', ObjectId('5bcc936420d8e7187f3cddd1')), can form get on AddInvoiceNumberView, can form post on AddInvoiceNumberView, menu access on AddInvoiceNumberView, menu access on InvoiceNumberView, menu access on YuTsaiLprCashJournalView]

**Comment by dolfandringa** [comment]
Hi @francisliyy @redalert253225 Sorry I have a hard time understanding and replicating your issues. It helps a lot if I can replicate your problems easily. I made a small single file app that [you can find here](https://gist.github.com/dolfandringa/5c19496ef2fe7a42040dbf7a084742af). If you could take that example, and replicate your issue by modifying it, and sharing that with me (as a gist, don't just copy-paste it in the text here) that would help a lot for me to fix this.

**Comment by redalert253225** [comment]
@dolfandringa  hi  today maybe i know  why i have the problem ,```
appbuilder.add_view(AddInvoiceNumberView, "AddInvoiceNumberView", icon="fa-hand-o-up", label=_("Add_Invoice_Number"),
        category="MyForms", category_icon="fa-cloud-upload",category_label=_("Forms"))
```
the first parameter can't equal the second , i should do that
```
appbuilder.add_view(AddInvoiceNumberView, "Add  Invoice  Number", icon="fa-hand-o-up", label=_("Add_Invoice_Number"),
        category="MyForms", category_icon="fa-cloud-upload",category_label=_("Forms"))
```
but  would you tell me why?
 i dont understand how it work  ,so i never note it is a problem.
before ,i think it just like a string for url

**Comment by dpgaspar** [comment]
The first parameter is used to identify your view, this way we will end up with 2 different views with the same ID. Going to close this issue. Glad you found the problem
