### ISSUE TITLE
Migrate from Flask-OAuthlib to Authlib

### ISSUE THREAD

**Issue by lepture** [dpgaspar/Flask-AppBuilder#748]
I see that you are using Flask-OAuthlib for OAuth authentication. It would be better to replace it with [Authlib](https://authlib.org/) since Flask-OAuthlib is deprecated.

Here is a guide: https://blog.authlib.org/2018/migrate-flask-oauthlib-client-to-authlib

And there are many built-in connections in https://github.com/authlib/loginpass which can be used directly. If you'd like, I can send a PR to finish the replacement.

- Checkout Authlib repository: https://github.com/lepture/authlib
- Authlib documentation: https://docs.authlib.org/

**Comment by dpgaspar** [comment]
Hi @lepture,

Yes, I have to migrate Oauthlib, but authlib comes with AGPL license, and this might be a problem.

@mistercrunch can you confirm this?

**Comment by adriankrupa** [comment]
@dpgaspar @mistercrunch are there any plans to switch to any oauth library that is not currently deprecated?

**Comment by dpgaspar** [comment]
No plans with dates yet, But I've used flask-dance and liked it, so it's a probable candidate.
Any thoughts on this?

**Comment by lepture** [comment]
Authlib is going to be licensed under BSD from next release. https://blog.authlib.org/2019/switch-to-bsd-license

**Comment by mistercrunch** [comment]
Highly recommend steering away from AGPL. If absolutely necessary, make it an optional dependency in `extra_requires`, not imported by default. Looks like in this case we can just wait for the next release.

**Comment by eve-n0rman** [comment]
This seems to have been closed out as stale without being addressed.  authlib is BSD licensed now, is there any intent to migrate to an actively developed oauth library?
