### ISSUE TITLE
how can i remove show, modify and delete button from list.html

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#752]
![image](https://user-images.githubusercontent.com/6333979/40487285-aa1790ba-5f31-11e8-8d38-1973dc13746f.png)

**Comment by dpgaspar** [comment]
http://flask-appbuilder.readthedocs.io/en/latest/advanced.html#advanced-configuration

Use base_permissions

**Comment by sodevious** [comment]
Look at this: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/templates/appbuilder/general/lib.html#L284

**Comment by EnriqueGautoSand** [comment]
how can add my own buttons on that section?
