### ISSUE TITLE
Relative link in menu

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#76]
I'd like to add a link to the 'add' functionality of a view (http://localhost:5000/someview/add) . It seems that when you do add_view it always links to the list, and you can't do multiple add_views to the same view, so it seems the right way to make the link I want is with add_link. I can add:

```
appbuilder.add_link("Click Here", href="/someview/add", icon="fa-folder-open-o", category="SomeCategory")
```

and this runs when I run FAB from python in the command line. However, I'm running FAB via uwsgi in a subdirectory: http://my.server.com/fab/ -- so I need the link to be http://my.server.com/fab/someview/add but only when running via uwsgi as this breaks the link when running python on the command line.

Is there a variable I can pass through the href argument so FAB will build the right url? IE:

```
appbuilder.add_link("Click Here", href="%FAB_BASE%/someview/add", icon="fa-folder-open-o", category="SomeCategory")
```

Ideally that url will either detect http vs https so stay agnostic to it.

Thanks!

**Comment by dpgaspar** [comment]
you should use Flask url_for:

    class MyModelView(ModelView):
           ....

    appbuilder.add_link("Click Here", href=url_for(MyModelView.add), icon="fa-folder-open-o", category="SomeCategory")

And yes using add_link is one way to do it.

**Comment by ben-github** [comment]
THanks -- that is exactly what I'm looking for. Unfortunately, when I try to use it get the error:
```
 File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 258, in url_for
    raise RuntimeError('Attempted to generate a URL without the '
RuntimeError: Attempted to generate a URL without the application context being pushed. This has to be executed when application context is available.
```


Am I missing something? I have
```
class TestView(ModelView):
    datamodel=SQLAModel(Test)

    
appbuilder.add_view(TestView, "Test", icon="fa-folder-open-o", category="Testing")
appbuilder.add_link("Test Add Item", href=url_for(TestView.add), icon="fa-folder-open-o", category="Testing")
```
