### ISSUE TITLE
JavaScript modelActions = AdminActions() attempts to manipulate DOM before document is loaded

### ISSUE THREAD

**Issue by nachtkinder** [dpgaspar/Flask-AppBuilder#761]
# Description
I've been working on modifications to Flask Appbuilder that will enable the display of a custom form in the dialogue for Model actions.  This has involved a lot of template overriding and some modification of flask_appbuilder/static/appbuilder/js/ab_actions.js.  During the course of this I discovered that sometimes the onClick event was not being assigned to the 'OK' button of my new modal dialogue.  I traced this to the following template chunk which I had copied from flask_appbuilder/templates/appbuilder/general/widgets/base_list.html:

    <script language="javascript">
        var modelActions = new AdminActions();
    </script>

The AdminActions JavaScript class, when initialised, attempts to attach an event listener to the modal dialogue's 'OK' button.  The problem is that the call to AdminActions happens irrespective of whether the DOM has completely loaded.

# Proposed solution
The solution to this is fairly trivial.  Simply wrap the contents of the script in a jQuery document ready block and prefix modelActions with 'window.' to ensure its availability outside of the document ready wrapper

I'll submit a pull request with the fix.

Regards,
Nachtkinder

**Comment by nachtkinder** [comment]
Hi All,
This issue is awaiting acceptance of pull request #762 .  I have not retested but I believe this issue to have been closed prematurely by stale[bot] 

Regards,
Nachtkinder

**Comment by dpgaspar** [comment]
This is merged and will be release with 1.12.3
