### ISSUE TITLE
using ComplexBaseField

### ISSUE THREAD

**Issue by outoftrun** [dpgaspar/Flask-AppBuilder#766]
I am using ComplexBaseField for a complex data field I have defined however I am getting field.name not defined error. Even when I use the exclude_cols attribute, I resolved the issue but checking for the existence of  field name  
 {% set field = form[col] %} 
 {% if field %}
.......
{% endif %}
is there a better way

**Comment by dpgaspar** [comment]
Can you please post the ModelView and the ComplexBaseField, code?
