### ISSUE TITLE
_add_permission bug in base when restart app it will clean the permission_role config

### ISSUE THREAD

**Issue by cw1427** [dpgaspar/Flask-AppBuilder#769]
There seems is a bug when _add_permission function been invoked add a new View.  It will call the add_permissions_view() function in security manager. And it will delete the permission role when the permission not in the base_permission.

So after I manually added the permission_role relationship, when I restart the system, it will trigger this add_permissions_view() so the original permission_role relationship about this new Views records had been deleted. I have to re-added the permission_role again.

Can anyone help me to investigate how to avoid it been deleted once I restart the app?

**Comment by cw1427** [comment]
Analyze the source code:
When restart the app, once the customer view was been added into appbuild, it will call below function. So if we have setup the "menu_access" permission for this View, but "menu_access" is not its base_permissions. So when we restart the app, this granted permission will be deleted again.

Is it a bug or it was designed as it? Can anyone explain am I wrong ?

   def add_permissions_view(self, base_permissions, view_menu):
        """
            Adds a permission on a view menu to the backend

            :param base_permissions:
                list of permissions from view (all exposed methods): 'can_add','can_edit' etc...
            :param view_menu:
                name of the view or menu to add
        """
        view_menu_db = self.add_view_menu(view_menu)
        perm_views = self.find_permissions_view_menu(view_menu_db)

        if not perm_views:
            # No permissions yet on this view
            for permission in base_permissions:
                pv = self.add_permission_view_menu(permission, view_menu)
                role_admin = self.find_role(self.auth_role_admin)
                self.add_permission_role(role_admin, pv)
        else:
            # Permissions on this view exist but....
            role_admin = self.find_role(self.auth_role_admin)
            for permission in base_permissions:
                # Check if base view permissions exist
                if not self.exist_permission_on_views(perm_views, permission):
                    pv = self.add_permission_view_menu(permission, view_menu)
                    self.add_permission_role(role_admin, pv)
            for perm_view in perm_views:
                if perm_view.permission.name not in base_permissions:
                    # perm to delete
                    roles = self.get_all_roles()
                    perm = self.find_permission(perm_view.permission.name)
                    # del permission from all roles
                    for role in roles:
                        self.del_permission_role(role, perm)
                    self.del_permission_view_menu(perm_view.permission.name, view_menu)
                elif perm_view not in role_admin.permissions:
                    # Role Admin must have all permissions

**Comment by nachtkinder** [comment]
Hi cw1427,

A while ago I had issues with Flask Appbuilder duplicating permissions on views as a result of restarting the app.  I think that issue may since have been resolved.  but the workaround that I used may be of use to you.

Basically, you can prevent Flask Appbuilder from updating the permissions on start up by adding `update_perms=False` to the params passed to AppBuilder in your application's __init__.py:

    appbuilder = AppBuilder(
        app,
        db.session,
        base_template='ab_overrides/baselayout.html',
        update_perms=False
    )

You will, of course, have to manage permissions yourself when you add a new view.

Hope this helps,
Nachtkinder

**Comment by cw1427** [comment]
Hi Nachtkinder:

Thanks for the reply. Yeah to shut downthe perms update can resolve it. But it will bring another problem, that is you can't update the new View's permissions.  So I changed the baseview code in the framework to add mean_access as one of the basic permission to avoid it been removed.
Please see my change above.  And I requested a pull request to the main branch. But my privious still not  been merged. So it can't be created success.
