### ISSUE TITLE
sql query based on fk id , shown on views

### ISSUE THREAD

**Issue by gcd445** [dpgaspar/Flask-AppBuilder#773]
Hello I have this query from php 
`$qry="select sum(amount) as charges from charge where ref_clientid='" . $clientid . "' and xxx is null " `
I want to show the value of it to the list_columns using ModelView of the Client
Whats the best way to do that? , 

```
class Charge(AuditMixin,Model):
    id = Column(Integer, primary_key=True)
    amount = Column(Numeric(10,2),default=0.00) 
    client_id = Column(Integer, ForeignKey('client.id'))
    client = relationship("Client")

class Client(AuditMixin,Model):
    id = Column(Integer, primary_key=True)
    client_id = Column(String(8), unique=True, nullable=False )     
    name = Column(String(64), unique=True, nullable=False)
```

**Comment by dpgaspar** [comment]
Hi,

You have 2 ways of doing this, either create an SQL view and define a ModelView on it, or create a function on the model that will act has a model property that will return the desired count:

something like: http://flask-appbuilder.readthedocs.io/en/latest/quickfiles.html#define-your-model-models-py

**Comment by gcd445** [comment]
Thanks for the reply, can you provide more snippets / samples?

**Comment by dpgaspar** [comment]
Using SQL views: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quicksqlviews/app/models.py#L26

Using "extra" columns: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickhowto2/app/models.py#L12

**Comment by gcd445** [comment]
Thank you , but I've done it like this,

```
class Client(AuditMixin,Model):
   ...
   def get_charges(self):
        sql = text('select sum(amount) as x from charge where client_id='+str(self.id)+' and z is null');
        result = db.session.execute(sql)
        row = result.fetchone()        
        return Markup('$' + str(row['x']))
```
then at views
```
list_columns = ['client_id', 'name', 'location', 'address','get_charges']
```

**Comment by dpgaspar** [comment]
Yes, thats it
