### ISSUE TITLE
deploy on apache2 on centos using https with Self Signed Certificate

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#778]
I don't know what's the problem, I deploy based on this article 
https://www.sslshopper.com/article-how-to-create-and-install-an-apache-self-signed-certificate.html

seems have everything done, but when accessing the application, only show
![image](https://user-images.githubusercontent.com/6333979/42328268-cda37852-803b-11e8-9d08-aaf4d147b71e.png)

how to do this deployment? please help

**Comment by dolfandringa** [comment]
Your question needs to be split-up in two: "how to setup flask-appbuilder in apache", and "how do I setup self-signed ssl certificates in apache". Try to get your flask appbuilder application running in apache first without ssl certificates. Once you have that running, then add the ssl certificates. 
Flask-appbuilder uses standard Flask for a lot of stuff, so in this case any documentation for setting up flask with apache should be applicable to flask-appbuilder too. The flask docs have a good section on this. I personally have only been using nginx for a long time, but I see no reason why the apache mod_wsgi approach wouldn't work. Also see issue #344

**Comment by dolfandringa** [comment]
#
I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.
