### ISSUE TITLE
Stripe Checkout 

### ISSUE THREAD

**Issue by gcd445** [dpgaspar/Flask-AppBuilder#781]
Hi, how can I do this using BaseView and SimpleFormView?

```
@app.route('/')
def index():
    return render_template('index.html', key=stripe_keys['publishable_key'])

@app.route('/charge', methods=['POST'])
def charge():
    # Amount in cents
    amount = 500

    customer = stripe.Customer.create(
        email='customer@example.com',
        source=request.form['stripeToken']
    )

    charge = stripe.Charge.create(
        customer=customer.id,
        amount=amount,
        currency='usd',
        description='Flask Charge'
    )

    return render_template('charge.html', amount=amount)
```

**Comment by dolfandringa** [comment]
We need a bit more information what "this" is. But SimpleFormView has a form attribute to which you can set the (WT)Form that you want displayed, it has a [form_template](https://flask-appbuilder.readthedocs.io/en/latest/templates.html#edit-templates) attribute where you can set the jina2 template, and an edit_widget that by default uses [FormWidget](https://flask-appbuilder.readthedocs.io/en/latest/templates.html#widgets) to display the fields (and has it's own template). 

See also https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L227 and https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/views.py#L44

**Comment by dolfandringa** [comment]
I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.
