### ISSUE TITLE
Should model primary key column attribute name must match column name 

### ISSUE THREAD

**Issue by lilila** [dpgaspar/Flask-AppBuilder#782]
Using Flask-AppBuilder 1.11.1 it seems to be required to have matching attribute name and column name for primary key (the case I encountered was with a composite key). 
It wasn't the case with Flask-AppBuilder-1.9.2

Is it a new convention? 

Thank you

**Comment by dolfandringa** [comment]
Have you tried something like this in your model?
```
class myModel(Model):
    email = Column('email_address', String(20))
```
Without diving in deeply, this should probably work. I you've tried and it doesn't. could you provide more info with a small minimal example code that doesn't work and a clear error?
