### ISSUE TITLE
add select box for a field in add page

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#784]
Hi, I add a function for showing a field as a select box, it can work when adding this field to the 'list_columns', but when I added it to the add_columns, it gave the errors like 'Was unable to import app Error: 'pro_name'.

so how can a use a select box for a field in the add page?

**Comment by francisliyy** [comment]
make a complement, I use MongoDB, which seems don't have a method is_enum to judge the field type, so can't decide to use select box

**Comment by dolfandringa** [comment]
Could you provide example code? Without it it's impossible to know what's going wrong. I am not using MongoDB, but I think it should still work I assume. The error you list seems to be unrelated. Is pro_name your app? The actually traceback is probably longer than you provided.
