### ISSUE TITLE
Creating Users

### ISSUE THREAD

**Issue by AnandRayarao** [dpgaspar/Flask-AppBuilder#787]
Hi,
Can you send a sample for creating default roles and adding permissions to users, creating users and adding roles to users. and also inserting test data into tables

**Comment by dolfandringa** [comment]
fabmanger does similar stuff to this. You can create your own version of fabmanager by creating a script that imports everything from flask_appbuilder.console (so all standard fabmanager commands work in your tool too) and then adding your own command. Flask Appbuilder uses click for this, so see the [click docs](https://click.palletsprojects.com/en/7.x/) for more information for that. For adding users and roles, see the [SecurityManager API Docs](https://flask-appbuilder.readthedocs.io/en/latest/api.html#basesecuritymanager), and check the create_admin command in flask_appbuilder.console for inspiration.

**Comment by dolfandringa** [comment]
Ah, and for turning your own commands into a script that works for the commandline, check [setup.py console_scripts entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point). This is what fabmanager uses too.

**Comment by dolfandringa** [comment]
I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.
