### ISSUE TITLE
Relation as Many filter does not work correctly when multiple values selected

### ISSUE THREAD

**Issue by nachtkinder** [dpgaspar/Flask-AppBuilder#789]
# Description

Having filtered a list view on a \*-to-many relationship:

 1. the filter field does not acknowledge values beyond the first
 2. the filtered list is incorrect (sometimes showing more results than it should, sometimes fewer or none)

Both of the above occur despite all the values for the selected field being present in the URL query string.

# Cause

The part of Flask Appbuilder that performs filtering of result sets uses `request.args.get('KEY')` in all instances rather than `request.args.getlist('KEY')`.  In the event that request.args['KEY'] has multiple values, `get()` returns only the first of the values whereas `getlist()` returns all values as a list.

# Proposed solution

Modify Flask Appbuilder's filtering to use `request.args.getlist()` in order to process multiple values for a single filter field.

**Comment by nachtkinder** [comment]
This was previously reported as issue #447 by Greg Silverman in 2017 but the many values for a single search field still appears not to work as described in the latest release (or on master for that matter).

**Comment by willrogers** [comment]
I have run into the same problem, and it seems clear to me that @nachtkinder's solution is the right one.

See 

https://flaskappbuilder.pythonanywhere.com/users/list/?_flt_2_first_name=a&_flt_2_first_name=c 

for an example search that works correctly with this fix applied.

I have added a couple of tests on top of their branch and will open a new PR, hopefully we can get it merged.
