### ISSUE TITLE
Customization of model edit view

### ISSUE THREAD

**Issue by backend-shakun** [dpgaspar/Flask-AppBuilder#792]
I need to change presentation of float numbers in model edit view from 2 decimal places to 8. 
Someone know how to do it??

**Comment by dolfandringa** [comment]
There are multiple ways. Probably the quickest is to define an additional property on your model that rounds the way you want to, and include that in your view's edit_columns/add_columns/etc. See [the sqlalchemy docs on hybrid attributes](https://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html#using-descriptors-and-hybrids) how to achieve this.

Another option would be to make your own implementation of the FormWidget to use it's own template and do it in there. See the [FAB docs about templates and widgets](https://flask-appbuilder.readthedocs.io/en/latest/templates.html#widgets) for more info.

**Comment by dolfandringa** [comment]
I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.
