### ISSUE TITLE
ab_permission sequence name

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#80]
It looks like in the security/sqla/modules.py you started putting a name in the for sequence on primary keys. E.G.:
```
Column('id', Integer, Sequence('seq_ab_permission_view_role_pk'), primary_key=True),
```

Before this was left out and the db autocreated a sequence using the default naming structure. In postgres at least, this means uing "ab_permission_id_seq". I can rename the sequence on my db and have the migration script do that as well, but first I wanted to check where the name "seq_ab_permission_pk" came from (maybe a mysql or sqlite thing?) and see if we want to change that name instead to match db default. 

Briefly looking at the code, I think this comes up with a few other sequences as well (ab_role, ab_user). 

Another option I think would be to remove the naming reference to the sequence as sqlalchemy knows the sequence without its explicit definition. Basically change the above line to:
```
Column('id', Integer, primary_key=True),
```

Thoughts?

**Comment by dpgaspar** [comment]
This came from #69 

It's an ORACLE compatibility thing on sqlalchemy, to support pk sequence from ORACLE.

On docs from sqlalchemy http://docs.sqlalchemy.org/en/latest/core/defaults.html#defining-sequences

But what exactly is the problem?

**Comment by ben-github** [comment]
The problem is that installs of FAB prior to 1.3.0 will have used the default naming scheme for their sequences. 1.3.0 will use the Sequence name given in the model definition and since they are different, you get an error (sequence doesn't exist).

If you need to define the sequences in the model def for Oracle, then I see two possible fixes

1. Rename the sequences to match the default names of sequences, so the names match the sequences that already exist in existing databases based on 1.2 or earlier. 

2. Rename sequences in the migration script to match sequence names in 1.3.0. Users of existing FAB installs will need to run this prior to upgrading to 1.3.0 but that is true anyway, so not a big deal.

I mildly vote for 1, but I think either is fine. Thoughts?

**Comment by dpgaspar** [comment]
This sequences were already present on 1.2.1. your upgrading from what version?

I was not expecting this one.... Thank you for your valuable help. I will run some tests, and get back on this ASAP.

**Comment by ben-github** [comment]
I was running 1.1.1.  If there is a release out there with these sequence names, I think we have to do a migration script. I'm guess it only breaks postgres (maybe sqlite / mysql don't use named sequences, just auto_increment?) but starting with that change, it would break upgrades on postgres installs.

Assuming my assumption is right, options are a little different:

1. Migrate db to use new sequence names -- will fix upgrades from 1.1 to 1.2 for pg users as well as 1.1 to 1.3 upgrade

2. Change name of sequences to default. No need to migrate on upgrades from 1.1 and earlier, but will need migrate script for 1.2->1.3 users. (1.1 to 1.2 upgrade was broken on pg so this only only affect users who did new install with 1.2 and then upgraded.

Hmm...

**Comment by dpgaspar** [comment]
On the sqlalchemy docs, Sequences will apply to Postgresql, Oracle, and Firebird.

I made a careless mistake on accepting #69 with those names.... I would say that there is no 100% way out for this, so i will try the path of less pain.

1 - No issues were submitted with this problem, so no pg user upgraded or cared.
2 - The correct way is to use Sequences (support for ORACLE) but use the names created by default on pg.

I would go for correcting the mistake, is out there for less time (and it's a mistake).

We could do one of 2 things:

1 - Open an issue, explaining the problem, and describing the solution using raw PG SQL, to alter sequence names.
2 - The migration script to 1.3, try/catches this specific error and executes the PG SQL script to alter the sequence names (this one is nicer, if your willing to...)

So, if you agree, i'm going to alter the sequence names and push it to 1.3.0.

**Comment by ben-github** [comment]
I agree. I'll attempt 2 and have migration script try to rename of the sequence and catch the error when it doesn't need to rename. If not, 1 is reasonable as well.

**Comment by jiangrzh** [comment]
great

**Comment by dpgaspar** [comment]
jiangrzh, this will impact your installation, when you upgrade you will probably have to rename your ORACLE sequences. I think this is the best approach. Any help needed your welcome to post an issue.

You #69 contribution was valuable, it was my fault not to notice the name collisions.
