### ISSUE TITLE
LDAP Authorization not work with correct config.py

### ISSUE THREAD

**Issue by alisheryakhyarov** [dpgaspar/Flask-AppBuilder#800]
Hello, help me please, i try set ldap auth. with MS AD

this is my config file : 

AUTH_TYPE = 2
AUTH_USER_REGISTRATION = False
#AUTH_USER_REGISTRATION_ROLE = "Alpha"
AUTH_LDAP_SERVER = "ldap://my.domain"
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_BIND_USER = "cn=Myuser,ou=somegroup,dc=my,dc=domain"
AUTH_LDAP_BIND_PASSWORD = "some_password"
AUTH_LDAP_SEARCH = "ou=some_group,dc=my,dc=domain"
AUTH_LDAP_UID_FIELD = "samAccountName"
AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
AUTH_LDAP_LASTNAME_FIELD = "sn"
#AUTH_LDAP_EMAIL_FIELD = "mail"
#AUTH_LDAP_APPEND_DOMAIN = 'my.domain'

And i get message : Invalid login. Please try again. 

I snip tcp dump, and there i see that AD authorization is correctly, attached screens to message. 

![screen_auth](https://user-images.githubusercontent.com/42531024/44322777-db757300-a470-11e8-8ddb-b104f303d02e.PNG)
![dump_screen](https://user-images.githubusercontent.com/42531024/44322778-df08fa00-a470-11e8-8874-be734fc342b7.PNG)

**Comment by alisheryakhyarov** [comment]
plus i attached debug file from superset
[dubug_file.txt](https://github.com/dpgaspar/Flask-AppBuilder/files/2301284/dubug_file.txt)

**Comment by jvrmaia** [comment]
try `AUTH_LDAP_UID_FIELD = "userPrincipalName"`

**Comment by alisheryakhyarov** [comment]
thanks, fix my problem with this 

AUTH_USER_REGISTRATION = True

**Comment by krsnik93** [comment]
This should be mentioned here: https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap.
