### ISSUE TITLE
Can't make an upgrade of the DB

### ISSUE THREAD

**Issue by aeweiwi** [dpgaspar/Flask-AppBuilder#802]
I am trying to follow the quick migrate example that was recently added. Unfortunately when trying to upgrade the database I stumple accross the following error

 Running upgrade  -> 986f3578d78f, empty message
Traceback (most recent call last):
  File "C:\Programs\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Programs\miniconda3\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Could not drop object 'ab_view_menu' because it is referenced by a FOREIGN KEY constraint. (3726) (SQLExecDirectW)")

....

sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Could not drop object 'ab_view_menu' because it is referenced by a FOREIGN KEY constraint. (3726) (SQLExecDirectW)") [SQL: '\nDROP TABLE ab_view_menu']

**Comment by BigBigXiong** [comment]
You should entry migrations/versions/ folder, open the current version like xxxx.py file, changes the upgrade() function codes: 
ex:
changes 
`op.drop_column('student', 'show')`
to  
`with op.batch_alter_table('student') as batch_op:
	batch_op.drop_column('score')`

**Comment by dolfandringa** [comment]
I am closing this issue to clean up our issue queue, but if you have additional questions, feel free to re-open the issue.
