### ISSUE TITLE
Add terms for registration

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#803]
![image](https://user-images.githubusercontent.com/6333979/44915586-59533d00-ad01-11e8-83bb-4761d51c5166.png)

Is there a way to add terms before reCaptcha for registration page?

**Comment by dolfandringa** [comment]
Sorry @francisliyy for the late reply, but it is possible. You should implement your own Security Manager (see https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security), and override the registerusedbview (or registeruseroidview depending on you authentication method) to point to your own view. Then implement your own view, that inherits from the relevant flask_appbuilder.security.registerviews.RegisterUser(DB/OID)View and changes the form attribute to point to your own form, that again, inherits from flask_appbuilder.security.forms.RegisterUser(DB/OID)Form. That is just a regular Flask Appbuilder form, so you can  override it's add_template (see https://flask-appbuilder.readthedocs.io/en/latest/templates.html#add-templates) to include anything you like.

**Comment by dolfandringa** [comment]
If you're willing to document this properly, a pull request to [docs/security.rst](https://github.com/dpgaspar/Flask-AppBuilder/blob/develop/docs/security.rst) would be very welcome.
