### ISSUE TITLE
How to run flask appbuilder with uWSGI and Nginx

### ISSUE THREAD

**Issue by djerrystyle** [dpgaspar/Flask-AppBuilder#805]
I build a web server with flask appbuilder,i can run this project by command: python3 run.py or fabmanage run,but it always No response when not interaction after some hours,So i try to run it with Nginx.

Here is my config:

uwsgi.ini:
```
[uwsgi]
base = /root/flask_spider/gttx_spider/web
all_base = /root/flask_spider/gttx_spider/
app = run
module = %(app)
chdir = %(base)
virtualenv = %(all_base)/venv
socket = %(all_base)/uwsgi_gttx_spider.sock
logto = /var/log/uwsgi/%n.log
master = true
processes = 500
chmod-socket = 666
vacuum = true
callable = app
```
nginx.conf

```
server {
    listen      82;
    server_name gttx_spider;
    charset     utf-8;
    client_max_body_size 75M;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/root/flask_spider/gttx_spider/uwsgi_gttx_spider.sock;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }
}
```
and modify run.py
```

from app import app

app.run(host='0.0.0.0')
#app.run(host='0.0.0.0', port=8080,debug=True)
```
and then:
```
sudo ln -s /root/flask_spider/gttx_spider/nginx.conf /etc/nginx/conf.d/
sudo /etc/init.d/nginx restart
uwsgi --ini uwsgi_gttx_spider.ini
```

When i access IP:82 and get this log in nginx:
`[error] 11104#11104: *3 upstream timed out (110: Connection timed out) while reading response header from upstream`

When i access IP:5000, And this log in uwsgi:
```
2018-09-10 19:36:25,747:INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-09-10 19:36:38,434:INFO:werkzeug:115.192.37.57 - - [10/Sep/2018 19:36:38] "GET / HTTP/1.1" 302 -
2018-09-10 19:36:38,466:INFO:werkzeug:115.192.37.57 - - [10/Sep/2018 19:36:38] "GET /home/ HTTP/1.1" 200 -
```

Also,i try this:
mv web/run.py web/run_bak.py
vi run.py
```

from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8090)
```
And access IP:82,it will return 'Hello World' and everything is fine

The difference is werkzeug will run the flask appbuilder project on 5000,and how to run in uwsgi.sock,Please Help,thanks!

**Comment by francisliyy** [comment]
I think you can follow this article 
https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-centos-7

**Comment by djerrystyle** [comment]
> I think you can follow this article
> https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-centos-7

 Thanks，it's very useful!
