### ISSUE TITLE
db.create_all() hangs on postgres

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#81]
I don't fully understand it, but when you are missing some tables that FAB needs to create, the command db.create_all() locks up waiting to get a lock from postgres which never happens. Only thing you can do is restart postgres. I think this is somewhat an issue with SQLAlchemy, but https://kronosapiens.github.io/blog/2014/07/29/setting-up-unit-tests-with-flask/ has some details on what is going on.

The 'fix' is to add the line db.session.remove() before db.create_all() in your views.py file. Like

```
db.session.remove()
db.create_all()
appbuilder.add_view(...)
...
```

Probably should add that line to the examples and documentation unless someone knows a better fix / work-around.

**Comment by dpgaspar** [comment]
Closing, if it's still relevant, feel free to reopen
