### ISSUE TITLE
Multirole only uses one set of permissions (1.3.0)

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#83]
If I create a user with roles role_a and role_b then he only gets permissions for role_a. If I delete his access to role_a (so he only has role_b) then he gets permissions on role_b, but it seems to only take the access of one role, not the sum of all his roles.

I'm running off the 1.3.0 branch.

**Comment by dpgaspar** [comment]
Solved. Thanks.
