### ISSUE TITLE
Problems with file upload field widget

### ISSUE THREAD

**Issue by deeagle001** [dpgaspar/Flask-AppBuilder#835]
Hello,

First, thank you for the F.A.B. After a learning curve, the programming becomes really rapid in it.

In fact, I found problems regarding the file upload widget named `BS3FileUploadFieldWidget`.

If my upload is canceled via a WTForms validator, the `FormWidget` (as `add_widget` for `ModelView`) will add an extra input text field and a delete checkbox.

![image](https://user-images.githubusercontent.com/22753186/47347123-e639c780-d6ae-11e8-8c16-f31dccd340f1.png)

I have several problems with these new fields:
* **Ugly**
No sizing, no spacing, no css.
* **No i18n**
The _Delete_ keyword is not covered with any kind of Babel's gettext, so it cannot be translated.
* **Exposes internals**
It prints the `field.data`, which is a `FileStorage`. These are implementation internals, so shall not be visible by the user.
* **Pointless**
The file itself is not uploaded as it does not appear in the `UPLOAD_FOLDER`, so deleting it makes no sense.

I am not sure about the last one, but I am sure that this is used deeply in F.A.B., in the `FieldConverter` and `MongoFileField`, and there is no easy way to customize it.

I see that the corresponding code migrated from the flask_admin, but in a trivial way.

I would propose to rather delete these additional fields than fix them, as they make no sense at all.

**Comment by deeagle001** [comment]
Bump!

**Comment by deeagle001** [comment]
Actually, I am most interested in the last one.
I figured out, that the file is saved in a temporary place, which is the werkzeug's `FileStorage` functionality, but I have never seen a website, which asks the user to whether delete or not the previously uploaded file on a reappearing form.

It would be a good feature in case of the multi-file upload controlled on the client side with Javascript. But this is not the case and the delete feature seems pointless.

I have already updated the delete feature to solve the other problems, but I would rather see this feature deleted than updated.

**Comment by deeagle001** [comment]
Bump!

**Comment by deeagle001** [comment]
Bump!

**Comment by deeagle001** [comment]
Bump!

**Comment by sdfreeman** [comment]
In the context of the 'modelview/edit' the delete option makes sense, I suppose what's happening here is that the same widget is being used for both 'add' and 'edit'.

**Comment by deeagle001** [comment]
Bump!

**Comment by deeagle001** [comment]
Bump!

**Comment by pogzyb** [comment]
Same here. I ended up just overriding the widget like so:

```
class UploadWidget(BS3FileUploadFieldWidget):
    """
    Removes ugly "FileStorage" render from File Field on validation error
    """
    def __init__(self):
        self.data_template = self.empty_template
```

BS3FileUploadFieldWidget source:
https://github.com/dpgaspar/Flask-AppBuilder/blob/120bc3ca38c4559a0099fe3b1a1badb319b6546e/flask_appbuilder/upload.py#L20-L56
