### ISSUE TITLE
Project Showcase

### ISSUE THREAD

**Issue by cryptonomicon314** [dpgaspar/Flask-AppBuilder#84]
Is there any place that gathers projects using Flask-Appbuilder?

I'm building a blog based on Flask-AppBuilder (almost done).
It supports some interesting features:

- rich text comments using [CKeditor](http://ckeditor.com/), including code blocks, inline code and math with [MathJax](http://www.mathjax.org/)
- a Rest API and a client that allow admin users to upload blog entries from Markdown texts, with support for linked images and MathJax. There is no installations support for the client yet. I just copy the python script to ``/usr/bin/``. This allows you to use version control on your entries, and it is much faster than using the admin interface. 
- Preview version of the blog, that only the admin can see and is blocked from other users (by subclassing a BaseView we can dramatically reduce repetition)
- PostgreSQL (full text search is planned but not yet ready)
- Ready for deployment on Openshift (their free tier is great)

It doesn't support:
- RSS feed (planned)
- Changing the default css or templates without reloading the app (maybe unnecessary, as the app reloads with less than 15 seconds of downtime)
- Spam protection. Commenters have to submit an email address, but it isn't even checked yet.

I haven't packed it into a blueprint, because I still don't understand flask blueprints very well, but people might find it interesting even as a standalone application.

**Comment by dpgaspar** [comment]
This looks awesome!

There is no place yet, but i would gladly create one. Maybe on the README.rst i can include a projects chapter with links to sites or github repos. Any ideas?

Remember 1.3.0 is almost out, it brings some changes (and many improvements), and unfortunatly some breaking features.
PostgreSQL it one of them, me and ben-github are preparing a migration script. any problem on upgrading post an issue.

**Comment by cryptonomicon314** [comment]
I think the README.rst is a great place to include links to projects, both github repos and websites.
I still haven't posted anything on my blog (still writing the first posts), so migration issues are not a problem. PostgreSQL support is important, though, because the FlaskAppbuilder Model breaks the Whoosh-Alchemy extension, which is the next better thing for search with SQLAlchemy. I'd have to use SQLite, which has some problems with ``datetime.timedelta`` support.

It would be interesting to have some kind of forum (or subreddit) to discuss questions related to FlaskAppbuilder, especially for guys like me with very little experience an little knowledge of best practices.

**Comment by dpgaspar** [comment]
Flask-Appbuilder supports and it has been tested for PostGreSQL, SQLite, MSSQL, ORACLE, MySQL.

The migration necessity on the new 1.3.0 is related with this issue #80

**Comment by cryptonomicon314** [comment]
I'm going to post the code on Github and upload a demo tonight on Openshift.
The code is not particularly well commented (the command line client is probably very hard to understand), but I hope the demo gives a taste of what's possible

**Comment by cryptonomicon314** [comment]
Done.
Github repo: https://github.com/cryptonomicon314/flog (flog, a flask blog)
Live Demo: http://demo-ninmesara.rhcloud.com/category/about - Contains instructions on how to log in. Allows you to explore the admin interface and break things. Don't worry if you break anything because it is very easy for me to restore the blog.

When I have more time I'll document the use of the command line tool, which saves a lot of time and allows you to edit the entries in markdown with a decent editor.

There are some ugly hacks to make it work on openshift, but I can probably fix them properly tomorrow or something

**Comment by cryptonomicon314** [comment]
I've fixed the hacks and some bugs. The github repo and the demo page have been updated.

**Comment by cryptonomicon314** [comment]
I've added spam protection using Akismet

**Comment by dpgaspar** [comment]
I really like it. 

Just a small remark (don't get me wrong) i think it would be nice to setup your menu using categories and some different fontawesome icons. But this is a matter of taste.

i'll check openshift also, currently using pythonanywhere (i'm happy with the free account).

Version 1.3.0 is a little late, but i'll mention this on the README or/and docs.

**Comment by cryptonomicon314** [comment]
Ok, that would reduce the clutter. Could you suggest a grouping by categories? Or just a single category for everything?

**Comment by cryptonomicon314** [comment]
I divided the menu into categories, restricted some views and permissions, added links to the *public* and *preview* pages, and changed a default view.

Until now, I hadn't explored the views and menus properly. The view/menu system is really great.

I have to tell you that you've managed to design a system in which a first time user can get some quick'n dirty CRUD working with absolutely no effort and a slightly more knowledgeable user can customized the hell out of it. I hope Flask-AppBuilder becomes the standard way to design non trivial Flask apps.

Thank you for all the hard work you did for free!

**Comment by dpgaspar** [comment]
Thank you for your kind words.

**Comment by dpgaspar** [comment]
Added to the list on README. Thank you for sharing this.
