### ISSUE TITLE
upgrading from 1.11.1 to 1.12.1 has breaking changes

### ISSUE THREAD

**Issue by apurvis** [dpgaspar/Flask-AppBuilder#849]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

1.12.2, running from within apache airflow.

### Describe the expected results

Bumping a minor version number should not crash.  If there is a breaking change, the major version should be bumped according to https://semver.org/

### Describe the actual results

`pip` automatically upgraded to 1.12.2 and broke my environment with `ImportError: "cannot import name DefaultMeta"`

**Comment by dpgaspar** [comment]
You have to upgrade Flask-SQLAlchemy, send the full pip freeze, please

**Comment by dpgaspar** [comment]
On the setup.py of Flask-AppBuilder we have:
Flask-SQLAlchemy>=2.3,<3

You're env has Flask-SQLAlchemy==2.1

Please upgrade and test again

Thank you
