### ISSUE TITLE
how to sort column with ip address

### ISSUE THREAD

**Issue by giordyb** [dpgaspar/Flask-AppBuilder#850]
### Environment

Flask-Appbuilder version: 1.12.1

pip freeze output:

Babel==2.6.0
Click==7.0
colorama==0.4.0
cyberpandas==1.1.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.1
Flask-Babel==0.11.2
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
ItsDangerous==1.0.0
Jinja2==2.10
MarkupSafe==1.0
numpy==1.15.3
pandas==0.23.4
pyasn1==0.4.4
pyasn1-modules==0.2.2
pymssql==2.1.4
python-dateutil==2.7.3
python-ldap==3.1.0
python3-openid==3.1.0
pytz==2018.5
six==1.11.0
SQLAlchemy==1.2.12
SQLAlchemy-Utils==0.33.6
Werkzeug==0.14.1
wfastcgi==3.0.0
WTForms==2.2.1

### Describe the expected results

I am writing a simple IP Address Management solution and I am populating the db tables with IP address info.
Since the IP addresses are written in the DB as strings, the sort is wrong.
If i use the SQlite db then they keep the order in which they were written (which would be an OK workaround) but if I use a MSSQL DB then they don't keep this order.

In my model.py I tried to use sqlalchemy_utils.IPAddressType but it did not make any difference

```
from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy_utils import IPAddressType
from sqlalchemy.orm import relationship
class IPTable(Model):
    IPAddress = Column(IPAddressType, primary_key=True)
    HostName = Column(String(150))
    DnsHostName = Column(String(150))
    Description = Column(String(150))
    LeaseExpiryTime = Column(String(150))
    AddressState = Column(String(150))
    ScopeId = Column(String(15))
    ClientId = Column(String(17))
    DHCPOptions = Column(String(150))
    Type = Column(String(150))

    def __repr__(self):
        return self.IPAddress
```

Is there a way to write an override sort function? I couldn't find any mention of it in the documentation.

Thanks,
Giordy

**Comment by dpgaspar** [comment]
Hi @giordyb,

On sqlalchemy_utils docs:

```
Changes IPAddress objects to a string representation on the way in and changes them back to IPAddress objects on the way out.
```

Very nice, but this means the ip is kept on the DB as a string. The sort is done by the DB so, it will never work for the whole dataset on the table, even overriding the sort.

On python3:

```
int(ipaddress.IPv4Address("192.168.0.1"))
str(ipaddress.IPv4Address(3232235521))
```

Don't know if the ordering will be ok on the DB side. Please test it
