### ISSUE TITLE
Inline Dynamic editing in DataTables

### ISSUE THREAD

**Issue by nipunsadvilkar** [dpgaspar/Flask-AppBuilder#854]
Hi @dpgaspar,

Thanks for such a great project. Your project saves a lot of development time and makes rapid-prototyping so fast in case of urgent project requests.

I did go through document and tried few examples myself but didn't find inline editing of datatables.

I was wonder if we can do inline editing after clicking *edit record* button as shown in image below. Since currently in one of the examples app (after clicking edit record) it directs from `subgroupmodelview/edit/{int}` -> `/contactmodelview/edit/{int}`
<img width="1214" alt="screen shot 2018-11-19 at 9 31 39 pm" src="https://user-images.githubusercontent.com/15062408/48719263-125f4e80-ec43-11e8-9afd-8f7d79287e7c.png">

will be very helpful in batch editing of contact from single list view.

It would be great if you can provide your views on this. Thanks!

**Comment by dpgaspar** [comment]
Yes it's a nice to have

**Comment by nipunsadvilkar** [comment]
Is it already implemented? If not, any thoughts on how to go about it?

**Comment by dpgaspar** [comment]
Sorry the bot caught you, it's not implemented and currently no plans to include it.
