### ISSUE TITLE
Can't login using ldap authentication using tls (Superset)

### ISSUE THREAD

**Issue by mprior10** [dpgaspar/Flask-AppBuilder#856]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Superset 0.24.0

Flask-Appbuilder version:1.9.6

pip freeze output:

$ pip freeze
alembic==1.0.2
amqp==2.3.2
asn1crypto==0.24.0
Babel==2.6.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
billiard==3.5.0.4
bleach==2.1.2
boto3==1.9.41
botocore==1.12.41
celery==4.1.0
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.9
cryptography==1.9
decorator==4.3.0
docutils==0.14
enum34==1.1.6
Flask==0.12.2
Flask-AppBuilder==1.9.6
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Compress==1.4.0
Flask-Login==0.2.11
Flask-Migrate==2.1.1
Flask-OpenID==1.2.5
Flask-Script==2.0.6
Flask-SQLAlchemy==2.1
Flask-Testing==0.7.1
Flask-WTF==0.14.2
flower==0.9.2
future==0.16.0
futures==3.2.0
geopy==1.11.0
gunicorn==19.7.1
html5lib==1.0.1
humanize==0.5.1
idna==2.6
ipaddress==1.0.22
ipython==5.8.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
kombu==4.2.1
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.1.0
numpy==1.15.4
pandas==0.22.0
parsedatetime==2.0
pathlib2==2.3.0
pexpect==4.6.0
pickleshare==0.7.5
polyline==1.3.2
prompt-toolkit==1.0.15
psycopg2==2.7.6
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycparser==2.19
pydruid==0.4.1
Pygments==2.2.0
PyHive==0.6.1
pyldap==3.0.0
python-dateutil==2.6.1
python-editor==1.0.3
python-geohash==0.8.5
python-ldap==3.1.0
python-openid==2.2.5
pytz==2018.7
PyYAML==3.13
requests==2.18.4
s3transfer==0.1.13
sasl==0.2.1
scandir==1.9.0
simplegeneric==0.8.1
simplejson==3.13.2
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.2
SQLAlchemy-Utils==0.32.21
sqlparse==0.2.4
superset==0.24.0
thrift==0.11.0
thrift-sasl==0.3.0
tornado==5.1.1
traitlets==4.3.2
unicodecsv==0.14.1
Unidecode==1.0.22
urllib3==1.22
vine==1.1.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
WTForms==2.2.1

### Describe the expected results
Need to authenticate to an ldap server using tls. No issue with authentication using python-ldap

AUTH_LDAP_USE_TLS = True
AUTH_LDAP_SERVER = "ldaps://my-ldap.acme.com:636"

Tell us what should happen.

User should be authenticated (able to login).

### Describe the actual results

User just gets a dialogue login box, as if they have entered a wrong username/password.

```pytb
No errors are logged.
```
### Steps to reproduce
-Install Superset 0.24.0 and Flask 0.12.2
-Configure /etc/openldap/ldap.conf for your domain
-Test ldaps connectivity in Python
import ldap, sys
con = ldap.initialize('ldaps://ad-ldap.acme.com', bytes_mode=True)
con.set_option(ldap.OPT_REFERRALS, 0)
con.simple_bind_s('admin@acme.com','secret')
basedn = "cn=Users,dc=acme,dc=com"
filter = "uid=don"
results = con.search_st(basedn, ldap.SCOPE_SUBTREE, filter)
for entry in results:
   print entry

- Edit superset_config.py and add
AUTH_LDAP_USE_TLS = True
AUTH_LDAP_SERVER = "ldaps://ad-ldap.acme.com:636"
- Try and login to Superset, it should fail
-Edit superset_config.py and add

AUTH_LDAP_USE_TLS = False
AUTH_LDAP_SERVER = "ldap://ad-ldap.acme.com"

Users should now be able to login.

**Comment by dpgaspar** [comment]
Please upgrade Flask-AppBuilder to 1.12.2 on a test environment and report back. New version has some new config features for LDAPS

**Comment by dpgaspar** [comment]
with 1.12.2

I use the following config with success:

AUTH_LDAP_SERVER = "ldaps://XXXX:636"
AUTH_LDAP_TLS_DEMAND = True

send me also the result of 'openssl s_client -connect XXXX:636' from the superset instance

**Comment by mprior10** [comment]
Thanks Daniel. When I use AUTH_LDAP_TLS_DEMAND = True and remove AUTH_LDAP_USE_TLS = True, it works.  Flask-AppBuilder 1.9.6 also works.
