### ISSUE TITLE
Cannot set indexview (default page)

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#86]
I'm trying to set the indexview -- get one view to load when you go to the root of the FAB app. I'm following http://flask-appbuilder.readthedocs.org/en/latest/customizing.html#changing-the-index for instructions, but if I put

```
class DefaultView(ModelView):
    list_template = 'default.html'
```
in my views.py and 
```
appbuilder = AppBuilder(app, db.session,indexview=DefaultView)
```
in my __init__.py

 then I get errors that appbuilder doesn't know what DefaultView is. If I move the definition of DefaultView into __init__.py then I get errors about not knowing ModelView class. If I add an import to ModelView to __init__.py then I get session errors.

I'm assuming I'm doing something wrong. I can add my view to view.py and add a link to it fine, but setting the indexview=DefaultView fails. I also tried the line
```
appbuilder.indexview=DefaultView
```
in views.py, but that got errors as well.

Thanks!

**Comment by dpgaspar** [comment]
You can do it two ways (but only one documented)

First (not explicitly on the docs) - you can override the index template, create your own template at app/templates/appbuilder/index.html. and thats it, no AppBuilder config.

Second: Create a file named for example indexview.py on it::

    from flask_appbuilder import IndexView

    class MyIndexView(IndexView):
        index_template = 'index.html'

Next on __init__.py:

    from flask import Flask
    from flask.ext.appbuilder import SQLA, AppBuilder
    from .indexview import MyIndexView

    app = Flask(__name__)
    app.config.from_object('config')
    db = SQLA(app)
    appbuilder = AppBuilder(app, db.session, indexview=MyIndexView)

    from app import views

This is assuming you do not need a View with a model

**Comment by ben-github** [comment]
Thanks. I went with method 2 and it works. Only one question -- how do I add a link in the menu system to this page? 

 I tried 
```

**Comment by dpgaspar** [comment]
Sorry for the delay, the index is accessible on the brand of the site. But i think you can also add it
using add_link('My Index','MyIndexView.index')

where index is the default endpoint on MyIndexView.

**Comment by ben-github** [comment]
I tried adding
```
appbuilder.add_view(MyIndexView.index, "Index", icon="fa-folder-open-o", category="Stuff")
```
to __init__.py (as MyIndexView isn't available in view.py) but I get on startup of FAB
```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/flask-appbuilder/app/__init__.py", line 27, in <module>
    appbuilder.add_view(MyIndexView.index, "My Index", icon="fa-folder-open-o", category="Stuff")
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 269, in add_view
    baseview = self._check_and_init(baseview)
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 224, in _check_and_init
    baseview = baseview()
TypeError: unbound method index() must be called with MyIndexView instance as first argument (got nothing instead)
```

Doing what is says and using MyIndexView instead of MyIndexView.index gets my the previously posted error:
```
werkzeug.routing.BuildError
BuildError: ('None.index', {}, None)
``` 

Thanks,

**Comment by dpgaspar** [comment]
You should not add the index view, because it's already added on AppBuilder, that's why you initialize it with:

    appbuilder = AppBuilder(app, db.session, indexview=MyIndexView)

Have you tried the add_link

    appbuilder.add_link('My Index','MyIndexView.index')

**Comment by ben-github** [comment]
Sorry I misread add_link and add_view. I tried what you have it gives a link to 
```
http://localhost:8000/<class%20'app.indexview.MyIndexView'>
```
which when you click on it doesn't work as that its a valid url.

**Comment by dpgaspar** [comment]
I've got it working just fine (version 1.3.0) using on views.py:

     ...
     appbuilder.add_link("Index","MyIndexView.index")

**Comment by ben-github** [comment]
Sorry, you are right, I missed the quotes on MyIndexView.index and put it as an object, not a string and it didn't work. Added quotes and there it is. Thanks!
