### ISSUE TITLE
overriding AuthDBView

### ISSUE THREAD

**Issue by AnandRayarao** [dpgaspar/Flask-AppBuilder#864]
Hi,
   I want to override Auth view And capture login and logout events but its not working any help on this

**Comment by AnandRayarao** [comment]
I want to catch login and logout events By overriding Authview but not working any help on this?

**Comment by dpgaspar** [comment]
Hi @AnandRayarao,

Have you tried this: https://flask-login.readthedocs.io/en/latest/#signals
