### ISSUE TITLE
related views

### ISSUE THREAD

**Issue by rozario-agro** [dpgaspar/Flask-AppBuilder#87]
It would be good to have related views not only for show and editing, but also for a new records. When the primary key is known in advance (eg. uuid), the user will be able to enter data in related views without additional steps in the UI. Especially when there must be at least one record in related view required by validation rules.

**Comment by dpgaspar** [comment]
I have to check if the current implementation of related views supports this (without a major change).

But i think it will probably need one to do it. The relation and auto fill from the related views is made with filter arguments, and add forms has no filter arguments.

**Comment by dpgaspar** [comment]
I agree on the UI experience improvement. But when a related record is added, it is actually added on the DB with the FK to the original model, even if we already know the PK of the "father" model, this poses some questions:

- The "father" model is not commited yet, the FK constraint will prevent you from inserting a record to a non existing model.
- If the user inserts the related models, and then cancels the add on the father model? the framework would have to rollback the exact inserts made on the related models.

This is a UI type of behaviour that can be done with MongoDB using a denormalized approach.
For now F.A.B. does not support denormalized MongoDB models.
