### ISSUE TITLE
Css problems

### ISSUE THREAD

**Issue by RafaelCenzano** [dpgaspar/Flask-AppBuilder#876]
How does one link css to the jinja2 files properly or add css without replacing the FAB theme css. I want my css to work with the FAB theme css but can't get it to work. The css I add always just removes all css that applies to the files.

**Comment by dpgaspar** [comment]
Hi,

Are you doing this:

```
{% extends 'appbuilder/baselayout.html' %}

{% block head_css %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/your_css_file.css')}}"></link>
{% endblock %}
```

**Comment by SavageCoder77** [comment]
The url_for static didn't work our current fix is using a relative path for example '../static/css/main.css'
