### ISSUE TITLE
Navbar creation problems

### ISSUE THREAD

**Issue by RafaelCenzano** [dpgaspar/Flask-AppBuilder#878]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:  1.12.2

pip freeze output: 
Babel==2.6.0
blinker==1.4
cachetools==3.0.0
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
google-api-python-client==1.7.6
google-auth==1.6.1
google-auth-httplib2==0.0.3
httplib2==0.12.0
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
oauth2client==4.1.3
pyasn1==0.4.4
pyasn1-modules==0.2.2
python-dateutil==2.7.5
python3-openid==3.1.0
pytz==2018.7
rsa==4.0
six==1.11.0
SQLAlchemy==1.2.14
uritemplate==3.0.0
Werkzeug==0.14.1
WTForms==2.2.1

### Describe the expected results

Tell us what should happen.

When running the app and creating a drop-down menu for unprotected/unhidden views the dropdown menu is only created for logged in users but the paths can be viewed when not logged in.

### Describe the actual results

Tell us what happens instead.

The dropdown menu not created unless signed in and the paths are able to be seen if typed in

### Steps to reproduce

Create a view and menu items in view.py and try to view that page without logging in

**Comment by SavageCoder77** [comment]
Wasn't quite sure how to couldn't find an easy way to tackle the problem that would be great!

**Comment by dpgaspar** [comment]
I'm assuming you solved the problem, if not, feel free to reopen.
