### ISSUE TITLE
list view ordering problem of related model with dotted notation

### ISSUE THREAD

**Issue by deeagle001** [dpgaspar/Flask-AppBuilder#884]
Hello, I would like to report a bug or undocumented restriction regarding the ordering of related field on show view.

### Environment

Flask-Appbuilder version:
1.12.2

pip freeze output:
Nothing extra. Only the dependencies of the Flask-AppBuilder itself.

### Describe the problem

The documentation mentioned that related field can be ordered with the dotted notation at the end of the linked chapter:
https://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html?highlight=order#define-your-views-views-py

However, the note does not mention the restriction which I found in the Issue related to the feature:
https://github.com/dpgaspar/Flask-AppBuilder/issues/51

@ben-github mentions the real restriction, which is more than I thought for the first time.
He mentioned, that the relationship field shall match with the related table name.
In most of the cases, the user can overcome this by renaming the desired `relationship` field.
In my case, the model has two foreign keys (relationships) to the same related model.
This case is impossible to be described with the given restriction.

Additionally, if you try to rename at least one of the `relationship` fields to satisfy the restriction, the sqlalchemy raises an error, that it could not figure out the ON clause for the JOIN statement, as the model has more than one foreign key for the same related table.
This happens in the models/sqla/interface.py in the `query` function, where it appends the join statements on the query in case of dotted notation.

**Comment by deeagle001** [comment]
bump

**Comment by dpgaspar** [comment]
Merged to master, thank you @deeagle001
