### ISSUE TITLE
ModelView how to make  dynamic list_columns

### ISSUE THREAD

**Issue by ghost** [dpgaspar/Flask-AppBuilder#889]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:
 latest
pip freeze output:

### Describe the expected results

file : view.py
list_columns =[dynamic_colmn1, dynamic_column2]
 i need capture the column name from UI Screen

### Describe the actual results
file : view.py

list_columns =[colmn1, column2]

how to give dynamic column name instead of static

**Comment by dpgaspar** [comment]
Can you be more specific or detailed

**Comment by subbiaht** [comment]
> Can you be more specific or detailed
Thank you @dpgaspar  i have edited the question please have look.

**Comment by CameronNemo** [comment]
I am still not sure what the original requestor desires, but one feature that could be useful is the ability to hide columns that are empty.

**Comment by pasqwal** [comment]
Not 100% sure, but this piece of code might help @ghost and others : 

`class MyColumnsView(ModelView)
    datamodell = SQLAInterface(MyModel)
    list_columns = datamodel.get_user_columns_list()`

the method **get_user_columns_list()** retrieves all the columns from the model, excluding the primary key
