### ISSUE TITLE
When trying to register FAB addon, getting: ERROR:flask_appbuilder.base:name 'reduce' is not defined

### ISSUE THREAD

**Issue by Walderman** [dpgaspar/Flask-AppBuilder#890]
### Environment

Flask-Appbuilder version: 1.12.2

pip freeze output:
attrs==18.2.0
Babel==2.6.0
click==6.7
colorama==0.3.9
defusedxml==0.5.0
dexter==0.1
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
gevent==1.3.7
greenlet==0.4.15
gunicorn==19.8.0
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
numpy==1.15.4
pandas==0.22.0
passlib==1.7.1
pluggy==0.6.0
psycopg2==2.7.5
py==1.7.0
pycrypto==2.6.1
pyodbc==4.0.23
pytest==3.4.2
python-dateutil==2.7.5
python3-openid==3.1.0
pytz==2018.7
simple-crypt==4.1.7
six==1.12.0
SQLAlchemy==1.2.14
sqlalchemy-redshift==0.7.1
Werkzeug==0.14.1
WTForms==2.2.1

### Describe the expected results

FAB working with new addon, when I register new addon key, like described in readme

```python
ADDON_MANAGERS = ['fab_addon_first.manager.FirstAddOnManager']
```

### Describe the actual results

Error happens, when i add the addon key to app config.

```pytb
ERROR:flask_appbuilder.base:name 'reduce' is not defined
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 31, in dynamic_class_import
return reduce(getattr, tmp[1:], package)
NameError: name 'reduce' is not defined
ERROR:flask_appbuilder.base:An error occurred when importing declared addon fab_add_audit.manager.AuditAddOnManager: name 'reduce' is not defined
```

### Steps to reproduce

in app config.py add an addon key.

pull request created with fix:
https://github.com/dpgaspar/Flask-AppBuilder/pull/891

**Comment by dpgaspar** [comment]
This is merged to master, thank you
