### ISSUE TITLE
CSV Import to update Data (MongoDB)

### ISSUE THREAD

**Issue by jawestory** [dpgaspar/Flask-AppBuilder#892]
i try  to find reference how to import csv to update the data , but cannot find it 
im using mongodb as my db 
is there anyone can advise me the example to do that?

**Comment by dpgaspar** [comment]
Have you read this: https://docs.mongodb.com/manual/reference/program/mongoimport/

**Comment by jawestory** [comment]
thank you for your response, but in the link you give is using terminal to run it..
what i want to is add import button in listview. so user can  select the file and import it from FAB web.. can you give advise on that one?

**Comment by dpgaspar** [comment]
One way of doing it is to override the list template take a look at:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickhowto2/app/templates/list_contacts.html

on 'list_list' block put a buttom that implements the file upload and POST to the server. On the server implement the file upload POST logic and csv import to mongo

**Comment by masrayie** [comment]
hello, i'm beginner in flask-app builder using mongo, could somebody please give me some example code for this case, importing data from csv to mongodb. thank you

**Comment by dpgaspar** [comment]
Hi @jawestory and @masrayie,

I've created a gitter chat where you can seek help. I want to avoid keeping open issues not related to bugs or new features.

Thank you
