### ISSUE TITLE
Pie chart fails: unorderable types

### ISSUE THREAD

**Issue by james1293** [dpgaspar/Flask-AppBuilder#899]
### Environment

Flask-Appbuilder version: 1.12.2

pip freeze output:
```
pip3 freeze
alembic==1.0.6
Babel==2.6.0
blinker==1.3
chardet==2.3.0
Click==7.0
cloud-init==18.4
colorama==0.4.1
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
idna==2.0
itsdangerous==1.1.0
Jinja2==2.10
jsonpatch==1.10
jsonpointer==1.9
language-selector==0.1
Mako==1.0.7
MarkupSafe==0.23
oauthlib==1.0.3
prettytable==0.7.2
pyasn1==0.1.9
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
python-apt==1.1.0b1+ubuntu0.16.4.2
python-dateutil==2.7.5
python-debian==0.1.27
python-editor==1.0.3
python-systemd==231
python3-openid==3.1.0
pytz==2018.9
PyYAML==3.11
requests==2.9.1
six==1.10.0
SQLAlchemy==1.2.16
ssh-import-id==5.5
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
virtualenv==16.2.0
Werkzeug==0.14.1
WTForms==2.2.1
```

### Describe the expected results

Pie chart should appear.

If needed, I can make a minimal repo (let me know), but you can use the [quickmigrate example](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickmigrate) and navigate to the pie chart (That's how I found the bug).

Here's the offending chart config in `views.py`:
```python

class ContactChartView(GroupByChartView):
    datamodel = SQLAInterface(Contact)
    chart_title = 'Grouped contacts'
    label_columns = ContactModelView.label_columns
    chart_type = 'PieChart'

    definitions = [
        {
            'group' : 'contact_group',
            'series' : [(aggregate_count,'contact_group')]
        }
    ]
```

### Describe the actual results

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/charts/views.py", line 190, in chart
    order_direction='asc')
  File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/charts/views.py", line 169, in _get_chart_widget
    value_columns = group.to_json(group.apply(lst, sort=order_column == ''), self.label_columns)
  File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/models/group.py", line 314, in apply
    data = sorted(data, key=self.attrgetter(*self.group_bys_cols))
TypeError: unorderable types: ContactGroup() < ContactGroup()
```

### Steps to reproduce

If you clone the [quickmigrate example](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickmigrate), then do these commands:

      $ export FLASK_APP=app/__init__.py
      $ flask db init
      $ flask db migrate
      $ flask db upgrade
      $ fabmanager create-admin
      $ python testdata.py
      $ fabmanager run

then...
 2. open the app
 3. log in as admin
 4. click Contacts > Contacts Chart
 5. the Traceback will occur.

### Other notes:
  
I tried changing [views.py line 169](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/charts/views.py#L169)

from

      sort=order_column == ''

to

      sort=order_column != ''

After I made that change, it **did** make the chart display (instead of crashing), but the resulting pie chart is grouped somewhat randomly:

![grppie](https://user-images.githubusercontent.com/7544606/51506846-59d99680-1dbc-11e9-85ce-c06255bbe549.png)

 

AFAICT, here’s the reason for the bizarre pie chart:

The function `group.apply()` is used by views.py on [line 169](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/charts/views.py#L169).

That `group.apply()` func uses the `itertools.groupby` func [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/group.py#L316). From the [docs]( https://docs.python.org/3/library/itertools.html#itertools.groupby ), the `groupby` func "generates a break or new group every time the value of the key function changes (which is why it is usually necessary to have sorted the data using the same key function)."

Let me know if I can do anything to improve this issue report, thanks!

**Comment by tzengwei** [comment]
File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/models/group.py", line 314.
    data = sorted(data, key=self.attrgetter(*self.group_bys_cols))
I commented out this line of code and the program is ready to run. But I didn't really solve the problem.
