### ISSUE TITLE
Several Erros with Python3.3 / 3.4

### ISSUE THREAD

**Issue by anogues** [dpgaspar/Flask-AppBuilder#90]
Hello.

Several errors when using with python 3.3 / 3.4:

ImportError: No module named 'StringIO' when using fabmanager.  --> console.py needs to be changed [from io import StringIO]

And also the urlopen import needs to be changed --> from urllib.request import urlopen.

Despite this i can't make it to work:

fabmanager create-app --name earlybird -engine SQLAlchemy
Something went wrong
Try downloading from <http.client.HTTPResponse object at 0x7f3fa074ddd0>

**Comment by dpgaspar** [comment]
Thanks for reporting this, i'll run some tests and make Py3 corrections on a new version ASAP.

On your error create-app do you have an internet connection from  your server/desktop?
You can try:

    git clone https://github.com/dpgaspar/Flask-AppBuilder-Skeleton.git earlybird

**Comment by anogues** [comment]
Hello Daniel.

Many Thanks. I think it is only necessary to edit the two imports however after that is still not working. 

Yes, I have internet connection on both servers i've tried. I'll try with the git.

Many Thanks and congratulations for the good work!

**Comment by dpgaspar** [comment]
Correction made on new version 1.3.2 (already on PyPi). Added tests for create_app also.

**Comment by anogues** [comment]
Hello Daniel
Sorry to bother you again. I am using a SimpleFormView or either a BaseView. Do you know how i can query directly the database to retrieve a full set of results that match a specific query?
I know that with flask-mysqlalchemy i can do:
Races= race.query.all() or if i want to query user.query.filter(...)
But i don't know how to do it fwith appbuilder. Can you point me?. I've tried datamodel = SQLAInterface(Race) and then try to do something but i guess this is the model object and is not possible to query or retrive all of the data.

Many Thanks,Albert.
 

     El Lunes 9 de febrero de 2015 14:21, Daniel Vaz Gaspar <notifications@github.com> escribió:
   

 Correction made on new version 1.3.2 (already on PyPi). Added tests for create_app also.—

**Comment by dpgaspar** [comment]
Hello, 

No bother, but can i ask you to open a new specific issue for this one (just copy/paste it)?

**Comment by anogues** [comment]
Done Daniel.
Many Thaks,Albert
 

     El Miércoles 11 de febrero de 2015 23:44, Daniel Vaz Gaspar <notifications@github.com> escribió:
   

 Hello, No bother, but can i ask you to open a new specific issue for this one (just copy/paste it)?—
