### ISSUE TITLE
Authentication Error 

### ISSUE THREAD

**Issue by willycornelissen** [dpgaspar/Flask-AppBuilder#900]
I am having problems with flask-mail when I try to register a new user. The configuration parameters are:

MAIL_SERVER = 'smtp.gmail.com'
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_PORT = 465
MAIL_USERNAME = 'XXXXXX'
MAIL_PASSWORD = 'XXXXXX'
MAIL_DEFAULT_SENDER = 'XXXXX'

After recaptcha, when I try to save the information about the new user, the log shows the following:

ERROR:flask_appbuilder.security.registerviews:Send email exception: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b8sm70207755qka.79 - gsmtp')

The user and password are correct. Do I misunderstand something?

**Comment by dpgaspar** [comment]
Hi @willycornelissen ,

Please review your config: https://flask-appbuilder.readthedocs.io/en/latest/user_registration.html#database-authentication

Make a simple send mail test using flask-mail, then report back

Thank you

**Comment by willycornelissen** [comment]
I was following the configuration on readthedocs, but they are not working.
I found a flask-mail simple test: 

https://github.com/RitheshShenthar/flask-mail-example-using-gmail

I got the same errors running this simple script:
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b8sm72853741qka.79 - gsmtp')

One note: the conf from readthedocs and the texxt github repo are slightly different. None of them work.

**Comment by Ulixestoitaca** [comment]
Hello,
I have same issue, email works correctly by flask_mail but trying to register a new user I get this error "Not possible to register you at the moment, try again later". I am in local by 127.0.0.1 and so I am currently using test recaptcha (see https://developers.google.com/recaptcha/docs/faq) which returns all verification requests as passed

**Comment by dpgaspar** [comment]
Any error on the logs?

**Comment by Ulixestoitaca** [comment]
For what I see there is not a log file, on the console no error is reported
