### ISSUE TITLE
How to create a public app or a public view (no login needed)?

### ISSUE THREAD

**Issue by brivadeneira** [dpgaspar/Flask-AppBuilder#903]
Hi !

I was reading the Flask-Appbuilder documentation, particulary security section and I still can't create a public app (no authenticaton needed at all) or a public view.

I tried with:

`AUTH_ROLE_PUBLIC` = 'Public'`
(in the config section)

`base_permissions = ['can_show', 'can_edit']`

but without success...

**Comment by soundmaking** [comment]
Within your view classes (in views.py) decorate a function with `@expose('/')`, but do not use @has_access.  

Then also make sure to call `appbuilder.add_view(YourViewClassName, 'Name for Menu' category='menu')` so that FAB 'finds' the class.

(I'm also quite new to FAB, so I hope my understanding of the question and these suggestions are accurate!)

**Comment by sydobrew** [comment]
I have just started working with Flask_Appbuilder and have found a similar struggle.  The AUTH_ROLE_PUBLIC setting seems to work, it correctly exposes the routed endpoint however I can't seem to find any information on working with the navigation menu to provide public navigation.  Could someone please point me in the right direction here?

**Comment by sydobrew** [comment]
After some further testing, it seems that the error is coming from the FAB_ROLES syntax.  The Role permission if set through the web security interface work as predicted but role permissions configured through the config file with FAB_ROLES = {"Public": [".*", "menu_access"]} fails as do other iterations through this syntax,

**Comment by Xuminhua** [comment]
Give all the related permission to the default public user will make the resources "public"(no login needed)

**Comment by fx-kirin** [comment]
I made it work like below with https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quicksqlviews.

```
FAB_ROLES = {
    "Public": [
        ["Contacts", "menu_access"],
        ["List Contacts", "menu_access"],
        ["ContactModelView", "can_list"],
    ]
}
```
I hoped I would have a document to do this.

**Comment by michaelzdrav** [comment]
> I made it work like below with https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quicksqlviews.
> 
> ```
> FAB_ROLES = {
>     "Public": [
>         ["Contacts", "menu_access"],
>         ["List Contacts", "menu_access"],
>         ["ContactModelView", "can_list"],
>     ]
> }
> ```
> 
> I would have liked to have a document to do this ahead of time. If you want to know the view_name, you have to check `flask_appbuilder.security.manager.BaseSecurityManager.has_access`
> 
> Regex definition `".*"` in `FAB_ROLE` doen't work like the document. The checker just check the text equation.


Do you have an example of how to do this? For example, I have an IndexView called class MyIndexView. I assumed the below would work but it doesn't seem to be working for me.
```
FAB_ROLES = {
    "Public": [
        ["MyIndexView", "menu_access"],
    ]
}
```

What else am I missing? This part isn't clear at all in the documentation and the documented ```.*``` doesn't work.
