### ISSUE TITLE
AuditMixin not working in Mongodb

### ISSUE THREAD

**Issue by masrayie** [dpgaspar/Flask-AppBuilder#905]
Hello i'm using F.A.B with mongodb and i have a case that use AuditMixin to get timestamp, but when i implement it in Model (Add it in parameter like this Model(AuditMixin, Document)) and then i add a record it success, but when i show the timestamp in list, there is no value, just showing the timestamp column,
is there any solutions ? thank you.

**Comment by dpgaspar** [comment]
Please fill out the info requested on the new issue template. And if possible an example gist/repo would be nice.
