### ISSUE TITLE
change forms on every request

### ISSUE THREAD

**Issue by AnandRayarao** [dpgaspar/Flask-AppBuilder#907]
Hi all,

    I want to assign forms to a view on run time, based on request I want change the fields dynamically 
   that is i want to change variable like add_forms,add_colums in Basecurd view on every request is it possible?

**Comment by soundmaking** [comment]
Hello, maybe a wiser voice will have better suggestion, but...

could this be done with an extra set of {% if statements %} in the jinja .html template or widget? 
- might need to save a copy and edit that, rather than being able to inherit (?)

**Comment by dpgaspar** [comment]
Closing, if it's still relevant, feel free to reopen
