### ISSUE TITLE
Is any idea to share models?

### ISSUE THREAD

**Issue by jiangrzh** [dpgaspar/Flask-AppBuilder#91]
hi, dpgaspar:
     I want to reuse some model in another process. but if i import model from the app, the process  will also loading views and permissions. Is any idea to import the model only?

**Comment by dpgaspar** [comment]
If your other process is inside 'myproject/app' just:

    from models import SomeModel

But i guess it's outside, right?

**Comment by jiangrzh** [comment]
yeah~

**Comment by dpgaspar** [comment]
You can change your app to init factory type:

https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/factoryapp

http://flask.pocoo.org/docs/0.10/patterns/appfactories/

You won't be able to use 'fabmanager'.

**Comment by jiangrzh** [comment]
It's also work for gunicorn?

**Comment by dpgaspar** [comment]
can't see why not.

**Comment by jiangrzh** [comment]
it's works, thank you very much!
