### ISSUE TITLE
Azure deployment redirect (Invalid login. Please try again.)

### ISSUE THREAD

**Issue by Harshitg** [dpgaspar/Flask-AppBuilder#912]
Hi all,

I have deployed the base version of the FAB application on azure under the URL: [Site URL](https://sitetester.azurewebsites.net/login/). The admin login has been created using the Kudu console with ID as admin and password as admin. The login keeps on redirecting to itself with an "Invalid login. Please try again." error, however the user exists in the app.db file itself

![image](https://user-images.githubusercontent.com/1675591/52902411-53610200-3236-11e9-995c-81bb792e5db5.png)

We have an important deployment coming up, any leads to resolve this would be appreciated.

Thanks
### Environment

Flask-Appbuilder version: latest

**Comment by dpgaspar** [comment]
Hi,

Is the password encrypted on the DB, did you use fabmanager create-admin cli command?

**Comment by Harshitg** [comment]
> 
> 
> Hi,
> 
> Is the password encrypted on the DB, did you use fabmanager create-admin cli command?

Hi,

The password is encrypted in the database, i have added a screenshot below. 

![image](https://user-images.githubusercontent.com/1675591/52907665-d5c7e100-328b-11e9-98c8-22e6348964ec.png)


The login has been created using this following command `fabmanager create-admin --username 'admin' --firstname 'admi' --lastname 'admi' --email 'admi' --password 'admin'`. The reason being on the Azure console, the fabmanager create-admin would be hung on the password 

![image](https://user-images.githubusercontent.com/1675591/52907669-f98b2700-328b-11e9-8ad1-c95f28a20a33.png)

In case it helps, the web.config is as follows:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
 <system.webServer>
  <handlers>
   <add name="httpPlatformHandler" path="*" verb="*" 
         modules="httpPlatformHandler" resourceType="Unspecified" />
  </handlers>

  <httpPlatform processPath="D:\home\python364x64\python.exe"
 arguments="app.py" requestTimeout="00:04:00" startupTimeLimit="120" startupRetryCount="3" stdoutLogEnabled="true">
   <environmentVariables>
    <environmentVariable name="PYTHONPATH" value="D:\home\site\wwwroot\app" />
    <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
   </environmentVariables>
  </httpPlatform>
 </system.webServer>
</configuration>`

Everything works well on the localhost on my computer. While on azure it seems to be failing.

Thanks

**Comment by Harshitg** [comment]
I continue to bother, but would anyone have any resolutions or can provide directions to resolve this issue.

**Comment by dpgaspar** [comment]
No bother, go to gitter if you want to talk
