### ISSUE TITLE
fabmanager create-db issue

### ISSUE THREAD

**Issue by FrankWangAU** [dpgaspar/Flask-AppBuilder#915]
I have app which is embedded into another package.

```
$ fabmanager create-db --app forklift.webapp.app
There in no appbuilder var on your package, you can use appbuilder parameter to config
```
 Then I found this line:
```
        _app = __import__(app_package)
```
https://github.com/dpgaspar/Flask-AppBuilder/blob/c665558b7263046e21a091303a77e16a91cd9557/flask_appbuilder/console.py#L31

After I changed to `import_module` function from importlib, problem goes away.
```
        _app = import_module(app_package)
```
Should we use [import_module()] (https://docs.python.org/3/library/importlib.html#importlib.import_module) instead of __import__?

**Comment by dpgaspar** [comment]
mmm, this is interesting, thank you for reporting it.

I'll take a look and get back

**Comment by dpgaspar** [comment]
New release will bring a new command line integrated with `Flask cli`. Will probably solve any issues related with app import, if `Flask cli` supports it (and can import you app) FAB will support it also.
