### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#916]
Hello,
I am trying to understand how this code works.

Let's say I have a "products" table in app.db and this products have been uploaded by various users.

How exactly I can

- retrive the sessionid of the logged user
- query db in order to extract only the products related to the user id
- building a table and pass data to one page

Thanks to everybody helps.

**Comment by soundmaking** [comment]
With the AuditMixin on your Product class you would get a field for ‘created by’ which you can filter on in a query to get products that were created by the current logged in user.

Your query in views.py might be:

```python
from flask import g
# ...
        list_of_products = db.session.query(
            Product
        ).filter(
            Product.created_by==g.user.id
        ).all()
```

Building a table in a template: pass the `list_of_products` data when calling render_template in your view functions:

```python
        return self.render_template(
            'my_product_table_template.html',
            list_of_products=list_of_products
        )
```

And in the template, something similar to this:

```html
            {% if response_data %} <!-- in this example response_data is a dict --> 
            <table class="table table-striped">
                {% for k,v in response_data.items() %}
                <tr>
                    <td><p><small>{{k}}</small></p></td>
                    <td><p>{{v}}</p></td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
```

**Comment by Ulixestoitaca** [comment]
oh thank you for your clearness and kindness!

last question: what in case my query should be partial as, for example "select id, product_name from products_table where ....."

**Comment by dpgaspar** [comment]
Hi,

Thank you @soundmaking. Just to add that you can filter ModelView by user using something similar to:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/basefilter/app/views.py

Hope this helps!

**Comment by Ulixestoitaca** [comment]
Thanks to both, relly. 
Unfortunately I am getting a runtime error "working outside of application context" calling g.user.id

**Comment by dpgaspar** [comment]
g only makes sense on an app context, Read about it on Flask docs

**Comment by soundmaking** [comment]
I hit that error too, you can only get `g.user` when the server is running... oh, and if the user is not logged in then you might hit other errors, so this is handy:

```python
if not g.user.is_anonymous:
    # do stuff with g.user
```

**Comment by Ulixestoitaca** [comment]
Thanks a lot, fortunately I had got that and bypassed the issue.
Now I am stuck with your query 

list_of_people = db.session.query( Persone ).filter( Persone.user_id==(g.user.id) ).all()

class Persone(Model):
    id = Column(Integer, primary_key=True)
    nome = Column(String(50))
    cognome = Column(String(50))
    compagnia = Column(String(50))
    user_id = Column(Integer)

1	mario	vergi	ilte	1
2	rosria	erricis	seat	1
3	marco	vergi	enav1

Do not understand why it sn't getting back results
