### ISSUE TITLE
Remove link from menu

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#919]
Hello,

I've added some link to a menu by appbuilder.add_view and appbuilder.add_link populating links by data coming from sqlite.

I'd like to know if it is in some way possible to remove one or more link from this collection.

Thank you

**Comment by dpgaspar** [comment]
Why do you want to remove it? You mean dynamically?

**Comment by Ulixestoitaca** [comment]
exactly, because in theory links in menu should be dynamic in this case.

**Comment by dpgaspar** [comment]
In theory in could to this, take a look at the menu.py and base.py. Yet this kind of approach is not supported, and I have not tested it
