### ISSUE TITLE
Retrieve Data directly from the db with SqlAlchemy on a BaseView or SimpleFormView

### ISSUE THREAD

**Issue by anogues** [dpgaspar/Flask-AppBuilder#92]
Hello,

I am using a SimpleFormView or either a BaseView. Do you know how i can query directly the database to retrieve a full set of results that match a specific query?

I know that with flask-mysqlalchemy i can do:

Races= race.query.all() or if i want to query race.query.filter(...)

But i don't know how to do it with appbuilder. Can you point me?. I've tried datamodel = SQLAInterface(Race) and then try to do something but i guess this is the model object and is not possible to query or retrive all of the data.

**Comment by dpgaspar** [comment]
Hello,

You can do something as simple as this (on views.py):

    from flask.ext.appbuilder import BaseView, expose
    from app import db, appbuilder
    from .models import Contact

    class MyContactView(BaseView):
        default_view = 'out'

        @expose('/out')
        def out(self):
            result = db.session.query(Contact).all()
            return str(result)

    appbuilder.add_view(MyContactView, "Exp Cont View", icon="fa-folder-open-o", category="Contacts", category_icon='fa-envelope')


Of course you should render a template or something on the out method.

**Comment by anogues** [comment]
Many Thanks Daniel.

It works fine :)

**Comment by dpgaspar** [comment]
No problem.
