### ISSUE TITLE
Does flask-appbuilder has timezone support

### ISSUE THREAD

**Issue by feng-tao** [dpgaspar/Flask-AppBuilder#920]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 1.12.3

pip freeze output:

### Describe the expected results

The Airflow community would like to make the UI time zone aware.  Two questions:
1. does FAB have timezone support?
2. from https://issues.apache.org/jira/projects/AIRFLOW/issues/AIRFLOW-3981, the community found two libraries(datepicker and datetimepicker) shipped with FAB. Does these two have time zone support?

Thanks.

```python
Paste a minimal example that causes the problem.
```

### Describe the actual results

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

**Comment by feng-tao** [comment]
cc @dpgaspar @astahlman

**Comment by dpgaspar** [comment]
Hi @feng-tao,

It does seem that this is doable by using moment js. Take a look at: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1725

Looks like your trying to implement it on AirFlow using a dropdown, so that users can choose between UTC or local time from the browser. Let me check if the packaged version of datetimepicker already supports it. 
If yes or after update, FAB would have to include moment js, and set it using the browser local time. Any thoughts?

**Comment by ashb** [comment]
@dpgaspar We probably want two or three TZ options: UTC, airflow-configured TZ (in our config files), and browser TZ.

Some of these TZs may be the same (and for added fun may be the same some of the year, but not always. DST is fun!)

**Comment by astahlman** [comment]
As far as I can tell, the version of datetimepicker bundled with FAB doesn't have time-zone support. According to [the datetimepicker docs](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/40fd466e9c27e87efbd918122d3125f36241af35/src/docs/Options.md#timezone), time-zone support was added in version 4.17.37, but [FAB bundles version 1.0.4](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/static/appbuilder/datepicker/bootstrap-datepicker.js#L2)

**Comment by dpgaspar** [comment]
Ok, thanks for the input @astahlman

**Comment by dpgaspar** [comment]
Hi,

I've started updating datetimepicker to 4.17.37, but it does not seem to render properly
incluided moment.js and moment-timezone.js (with data) also, but need to be initialized.

https://github.com/dpgaspar/Flask-AppBuilder/tree/feature/update-bootstrap-datetimepicker

Maybe you can continue from here? It would be great if you could submit a PR for this, I'm here to help 
in any guidance for integration on FAB. 

"We probably want two or three TZ options: UTC, airflow-configured TZ (in our config files), and browser TZ."

Could make sense to create a new config key, FAB_UI_TIMEZONE.

Thank you

**Comment by feng-tao** [comment]
thanks @dpgaspar , cc @astahlman @ashb

**Comment by astahlman** [comment]
> I've started updating datetimepicker to 4.17.37, but it does not seem to render properly

@dpgaspar I didn't encounter any rendering issues when I checked out the branch you referenced - can you point me to where you were seeing the issues?

In the meantime, I've opened https://github.com/dpgaspar/Flask-AppBuilder/pull/931 which has no change in functionality. All it does is add a (hacky) demonstration of toggling the timezone of a datetimepicker to the quickhowto2 example.

**Comment by dpgaspar** [comment]
Any news on this?

**Comment by ashb** [comment]
Unfreeze

**Comment by feng-tao** [comment]
?

**Comment by feng-tao** [comment]
@dpgaspar is the feature supported or not?
