### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by vrive** [dpgaspar/Flask-AppBuilder#921]
Hi I would like to know if there is a way to modify the Login to include a forgot password link and functionality. 

Thanks

**Comment by dpgaspar** [comment]
Yes, you can extend the SecurityManager. 
https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

**Comment by cippall** [comment]
Hi Daniel,

Can you please provide an example on how to implement a forgot password functionality? I'm struggling to understand how the extend  SecurityManager link that you mentioned can help in this case.

Many thanks!

**Comment by sdfreeman** [comment]
Hello, 

I am working with AUTH_DB and a SecurityManager that has been extended to do custom set up of new users when they register.  I would also like to add a 'forgot password' feature, can see ways to generate and send a unique link to the user's email adreessm but am not sure what functions to call for changing the stored password.  any suggestions on that part would be most welcome.

If I get it working then I will look at writing an example that could be shared.

thanks
