### ISSUE TITLE
Extending User Model and current users issue

### ISSUE THREAD

**Issue by vrive** [dpgaspar/Flask-AppBuilder#924]
Hi, I wanted to add an extra field to the user registration process so I modified the RegisterUser model, extended the RegisterUserDBForm, RegisterUserDBView, User model, and the SecurityManager. When I test it with registering a new user, the user is added to the db with the new field and can log in. However, a user created before the addition of the extra field can no longer login. How can I fix this issue?

**Comment by dpgaspar** [comment]
Hi @vrive,

Fill out the issue template, please.
