### ISSUE TITLE
develop a file upload function in superset

### ISSUE THREAD

**Issue by francisliyy** [dpgaspar/Flask-AppBuilder#925]
### Environment

Flask-Appbuilder version:  use superset master branch

### Describe the expected results

Tell us what should happen.

I tried to have a file upload function in the superset, so I followed the sample from flask app builder example:
https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickfiles

### Describe the actual results

when inserting database, it got null for file column, the errors like below:

2019-03-13 14:39:00,143:ERROR:flask_appbuilder.models.sqla.interface:Add record error: (MySQLdb._exceptions.OperationalError) (1048, "Column 'file' cannot be null") [SQL: 'INSERT INTO static_files (file, description) VALUES (%s, %s)'] [parameters: (None, 'test file upload')] (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
File "/home/lyx/visualBI/venv/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
context)
File "/home/lyx/visualBI/venv/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
cursor.execute(statement, parameters)
File "/home/lyx/visualBI/venv/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

### Steps to reproduce
(1) it is a model view list page.
(2) click add button to redirect into add page.
(3) choose a file
(4) input the description
(5) click save

**Comment by francisliyy** [comment]
![image](https://user-images.githubusercontent.com/6333979/54471632-02bdd400-47f7-11e9-8333-6342e609a565.png)
I debugged and found the "item" in line 931 have an empty file property, but in a F.A.B project, it did have something, it is not empty, the upload function is working in F.A.B project. However, the same code in superset failed.
Could you help to find why this upload can't work in a superset project?

**Comment by dpgaspar** [comment]
ok, let me take a look

**Comment by francisliyy** [comment]
@dpgaspar  thank you. 
Anything I need to provide, please let me know. Looking forward to receiving your feedback soon.

**Comment by francisliyy** [comment]
Hi @dpgaspar, have you found anything help? I can't make any progress about this problem

**Comment by dpgaspar** [comment]
Sorry for the delay,

When you say:

"I tried to have a file upload function in the superset, ..."

Are you extending Superset using a child of SupersetModelView? If yes can you share you're class?

If not, can you point where is this problem happening on Superset, and if you have opened an issue on Superset.

**Comment by francisliyy** [comment]
Hi @dpgaspar, Thank you for your reply.
As you said, at first I extended SupersetModelView and ran into that error, I thought that might be the problem, so I change it to ModelView as you did in F.A.B example, but it is still not working.

My code is like : 

in models/core.py
`class StaticFile(Model):

    __tablename__ = 'static_files'
    id = Column(Integer, primary_key=True)
    file_name = Column(String(250))
    file = Column(FileColumn, nullable=False)
    description = Column(String(150))

    def download(self):
        return Markup(
            '<a href="' + url_for('StaticFileModelView.download', filename=str(self.file)) + '">Download</a>')

    def file_name(self):
        return get_file_original_name(str(self.file))`

in views/core.py:
`class StaticFileModelView(ModelView):
    datamodel = SQLAInterface(models.StaticFile)

    label_columns = {'file_name': 'File Name', 'download': 'Download'}
    add_columns = ['file', 'description']
    edit_columns = ['file', 'description']
    list_columns = ['file_name', 'download']
    show_columns = ['file_name', 'download']

appbuilder.add_view(
    StaticFileModelView,
    'Upload static File',
    label=__('upload static File'),
    icon='fa-file',
    category='Manage')`

ScreenShot Attached
![image](https://user-images.githubusercontent.com/6333979/54980711-73c46f00-4fe1-11e9-8f77-87df0b3de829.png)
![image](https://user-images.githubusercontent.com/6333979/54980794-acfcdf00-4fe1-11e9-8141-22d7ff37d027.png)

**Comment by francisliyy** [comment]
Hi @dpgaspar, have you tried my code? hope to get it fixed soon.

**Comment by francisliyy** [comment]
@dpgaspar 
![image](https://user-images.githubusercontent.com/6333979/55548191-88051c00-5705-11e9-97e8-75fd5e425fff.png)
![image](https://user-images.githubusercontent.com/6333979/55548370-e5996880-5705-11e9-90c7-9835ad35bcb0.png)

I found here the self.data was supposed to be a FileStorage object, now it was a string instead, this is the reason why the upload failed, but how did it happen?
Have you got any idea?

**Comment by francisliyy** [comment]
hi, anybody can tell me where is this populate_obj invoked?

**Comment by dpgaspar** [comment]
`populate_obj` is an override, and is invoked on ModelView._add and ModelView._edit
