### ISSUE TITLE
updating record in @action

### ISSUE THREAD

**Issue by raoden1** [dpgaspar/Flask-AppBuilder#932]
Is it possible to update row.field in _@action_ 

for example I have View: **MessageGroup** with list of **Message** each Message has _Status_ field: Draft.

Then after choosing row and action **sent** I want to change in this object after successful action  filed _Status_ using self.datamodel. 

Is that possible ? and if yes how ?

**Comment by dpgaspar** [comment]
Were you able to solve this?

``` python
    @action("myaction", "Do something on this record", "Do you really want to?", "fa-rocket")
    def myaction(self, item):
        for message in item.messages:
            message.status = 'x'
        self.datamodel.update(item)
        return redirect(self.get_redirect())
```
Note: you can use SQLA session directly also using current_app.appbuilder.db_session

**Comment by raoden1** [comment]
```
    self.datamodel.update(item)

    AttributeError: 'MongoEngineInterface' object has no attribute 'update'
```
