### ISSUE TITLE
How to get current user info.

### ISSUE THREAD

**Issue by Whpitot** [dpgaspar/Flask-AppBuilder#933]
### Environment
flask-appbuilder == 1.12.4

### Describe the expected results
I want to get current user info (such as user.id, user.name) and add to table my self-defined when I execute add or update operation.

**Comment by soundmaking** [comment]
> I want to get current user info (such as user.id, user.name)

```python
from flask import g
# ...
if not g.user.is_anonymous:
    user_id = g.user.id
```

> and add to table my self-defined when I execute add or update operation.

not sure exactly what you mean, but two things come to mind 
  - the `AuditMixin` when defining your model classes, and 
  - extending the user model : https://flask-appbuilder.readthedocs.io/en/latest/security.html?highlight=myuser#extending-the-user-model

**Comment by Whpitot** [comment]
It has been done  after I heared your advice.
thank you very much.
