### ISSUE TITLE
duplicated email address in self registered users because upperCase letter

### ISSUE THREAD

**Issue by soundmaking** [dpgaspar/Flask-AppBuilder#935]
Hello, I am using my own extended SecurityManager, and have overwritten the add_user() function, but I am wondering if there's any good reason this line in SecurityManager class:

https://github.com/dpgaspar/Flask-AppBuilder/blob/c665558b7263046e21a091303a77e16a91cd9557/flask_appbuilder/security/sqla/manager.py#L95

is not:
`register_user.email = email.lower()`

to help email values be unique email addresses, rather than just unique strings as checked by the SQLA Column parameters.

**Comment by dpgaspar** [comment]
No reason, can you please submit a PR with this?

**Comment by soundmaking** [comment]
will do - but not right away...
: )
