### ISSUE TITLE
extendsecurity example click field Create_By_Name cause NotImplementedError

### ISSUE THREAD

**Issue by bsbrother** [dpgaspar/Flask-AppBuilder#936]
flask-appbuilder is very good for me, thank the author very much!
but when i run examples  meat a error:

I see https://github.com/dpgaspar/Flask-AppBuilder/issues/343,  then

$ cd Flask-AppBuilder/examples/extendsecurity
$ vi app/views.py
    order_columns = ['name', 'birthday', 'created_by']
$ python testdata.py
$ python run.py
Browser->  Login -> Contacts ->List Contact-> click 'Created By Username'
....
NotImplementedError: <function asc_op at 0x7f7e5a0add08>

is it mean created_by field is list then must manual implement a function asc_op? how to do?
thank you!

**Comment by dpgaspar** [comment]
Fixed the example, by removing the dotted notation
