### ISSUE TITLE
Deprecate support for python <3.6

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#939]
A placeholder issue for related conversation and planning around the process.

**Comment by dpgaspar** [comment]
yes, supporting python 2.7 is getting harder and harder, and the reasons to support it are fewer and fewer.

I propose to end py2 support on this next version 1.13.0 (that will include the new REST API).

**Comment by CameronNemo** [comment]
Is the REST API changing in an incompatible way?

**Comment by dpgaspar** [comment]
The current REST API is going to be deprecated, but still working. A new REST API is coming on 1.13.0

**Comment by dpgaspar** [comment]
Just a heads up, new release (that will probably be out today) will break on py2
