### ISSUE TITLE
Changes in the Flask-AppBuilder not reflected

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#94]
For example, making changes in the Flask-AppBuilder->flask_appbuilder->templates->appbuilder->index.html in debug mode, 

<h2><center>{{_('Welcome')}}<center></h2>

changed to 

<h2><center>{{_('Welcome Changed')}}<center></h2>

But even after restart, changes are not reflected?

**Comment by dpgaspar** [comment]
Hello,

You should not reflect change on the index like this. You don't have to change/fork the package to change the index. 

http://flask-appbuilder.readthedocs.org/en/latest/customizing.html#changing-the-index

It does not change because you have to reinstall the package when you change it
