### ISSUE TITLE
[discuss] deprecate support for Mongo

### ISSUE THREAD

**Issue by mistercrunch** [dpgaspar/Flask-AppBuilder#940]
How many people out there use FAB with Mongo in production?

How stable and feature complete is the Mongo implementation?

If reasonable, how hard would it be to deprecate support for Mongo?

**Comment by dpgaspar** [comment]
- How many people out there use FAB with Mongo in production?

Really can't tell. Anyone using Mongo with FAB, it's time to make some noise if you want to 
keep the feature.

How stable and feature complete is the Mongo implementation?

It's not feature complete.

If reasonable, how hard would it be to deprecate support for Mongo?

Not too hard. Generic data is a nice feature thought. The Abstract data interface is a nice concept
that could give us a layer to support multiple backends, on the other hand it's a bit hard and 
not natural to impose a relational structure on non relational backends

**Comment by jawestory** [comment]
hello i using mongodb with flask appbuilder 
can say  is all good until now  
little bit different approach but its ok 
and please keep this features :(

**Comment by mosynaq** [comment]
I use appbuilder+mongo too. It's good but certainly can get better. please keep this feature.
Thanks!
