### ISSUE TITLE
Recommendation on how to upload many images

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#942]
This is not so much a bug as a request for advice. I would like to perform a mass upload of files into my FAB app, and wanted to know the best approach for accomplishing this. Is there any way I can use the REST API to upload them? Or is there a lack of support for such operations? Can I place the images into the IMG_UPLOAD_FOLDER manually and then refer back to them somehow? I don't see any way that I could, so I am turning to you all for any recommendations.

**Comment by dpgaspar** [comment]
This problem can vary a lot, but yes you can use the new REST API (1.13.0, is coming out) for image upload. If your API/webserver has other purposes besides image upload, you probably want to rethink your architecture. Remember also that image uploading introduces state on the server and this will force you to rethink thing in terms of horizontal scaling and resiliency.

**Comment by CameronNemo** [comment]
Will take that into account. I imagine an network share could do the trick. As it turns out, there are only a couple hundred or so files images that need to be uploaded.

**Comment by CameronNemo** [comment]
Hmm regarding the new REST API, I have not been able to make it work with file or image upload. Is this expected?
