### ISSUE TITLE
New API forces specification of relationship fields

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#947]
### Environment

Flask-Appbuilder version: 1.13.0

pip freeze output:

```
alembic==1.0.8
apispec==1.2.0
astroid==2.2.5
attrs==19.1.0
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.13.0
Flask-Babel==0.12.2
Flask-JWT-Extended==3.18.1
Flask-Login==0.4.1
Flask-Migrate==2.4.0
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
idna==2.8
isort==4.3.15
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==3.0.1
lazy-object-proxy==1.3.1
Mako==1.0.7
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.2
mccabe==0.6.1
Pillow==6.0.0
prison==0.1.0
PyJWT==1.7.1
pylint==2.3.1
pyrsistent==0.14.11
python-dateutil==2.8.0
python-editor==1.0.4
python3-openid==3.1.0
pytz==2018.9
PyYAML==5.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.1
typed-ast==1.3.1
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.11.1
WTForms==2.2.1
```

### Describe the expected results

POST only the non-nullable fields for a model, `Foo`.

Models:

```python
class Foo(Model):
    id = Column(Integer, primary_key=True)
    children = relationship('Bar', backref=backref('Foo', uselist=False))

class Bar(Model):
    id = Column(Integer, primary_key=True)
    foo_id = Column(Integer, ForeignKey('foo.id'), nullable=False)
```

API:

```python
class FooApi(ModelRestApi):
    datamodel = SQLAInterface(Foo)
```

### Describe the actual results

Status code 422 on POST to `api/v1/fooapi/`

```json
{
  "message": {
    "children": [
      "Missing data for required field."
    ]
  }
}
```

### Steps to reproduce

POST to the `Foo` ModelRestApi with the relationship field not defined.

**Comment by dpgaspar** [comment]
I see,

Have you tried to define the add_columns/edit_columns for the Foo REST API, without the children field?

**Comment by CameronNemo** [comment]
With those defined, there are no issues. Am I using the feature wrong by not defining them?

**Comment by dpgaspar** [comment]
I would not say that, I'm still uncertain if I should discard these type of fields, or expect user's to explicitly exclude them. What do you think?

**Comment by CameronNemo** [comment]
Discarding them leaves less flexibility than expecting the user to exclude them. Note that in some situations one may want to fill in the field and in others leave it undefined.

**Comment by dpgaspar** [comment]
On this case you have ``nullable=False`` can you test with ``nullable=True``?

**Comment by CameronNemo** [comment]
Makes no difference. Note that the `nullable=False` keyword argument is on the non-API model (`Bar`), and I do intend for the field to be non-nullable when attempting to add rows to that table.

Additionally, I am seeing the same behavior with a many to many relationship that *is* nullable on both sides.

**Comment by dpgaspar** [comment]
that's worse, thank you for reporting this. let me check it ASAP.

**Comment by dpgaspar** [comment]
Confirmed, seems like required flag on M-M relations is not inferred correctly. I'm working on a solution.

**Comment by CameronNemo** [comment]
I have tested the branch, and unfortunately it does not fix the issue.

**Comment by dpgaspar** [comment]
I've tested your example and it works, as well as with M-M fields

```
curl -XPOST http://localhost:8080/api/v1/fooapi/ -d '{}' -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN"
{"id":1,"result":{"children":[]}}
```

**Comment by dpgaspar** [comment]
retry on 2.0.0

**Comment by CameronNemo** [comment]
Have retried with 2.0.0 from pypi via pip, it does work correctly. I think I made an error while attempting to install from source... I just did a `python3 setup.py install`.
