### ISSUE TITLE
release consistent versions to Pypi/conda-forge, atm Pypi=v1.11.0, conda-forge=v1.12.0

### ISSUE THREAD

**Issue by rjurney** [dpgaspar/Flask-AppBuilder#948]
The version of conda-forge's package is out of sync with Pypi and this causes problems for users. At the moment Pypi=v1.11.0, conda-forge=v1.12.0. Can you please push 1.12.0 to conda-forge, or update both Pypi and conda-forge to be consistent in some way?

See #808 for the latest Pypi release.

Thanks!

**Comment by dpgaspar** [comment]
@rjurney,

Latest version of FAB is 1.13.0 (1.14.0 is going out today), I only publish to Pypi. You can submit a PR on conda-forge FAB repo, bumping their version (or open an issue).

**Comment by rjurney** [comment]
@dpgaspar Thanks, I had assumed it was you. I'll do that.

**Comment by rjurney** [comment]
@dpgaspar Did 1.14.0 go out as 2.0? I saw that 2.0 was out and not 1.14.0 in the tags.
