### ISSUE TITLE
Error: No such command "fab".

### ISSUE THREAD

**Issue by mosynaq** [dpgaspar/Flask-AppBuilder#950]
### Environment

Flask-Appbuilder version: 1.13.0

pip freeze output:
```
apispec==1.2.0
attrs==19.1.0
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.13.0
Flask-Babel==0.12.2
Flask-JWT-Extended==3.18.1
Flask-Login==0.4.1
flask-mongoengine==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.2
mongoengine==0.17.0
prison==0.1.0
PyJWT==1.7.1
pymongo==3.7.2
pyrsistent==0.14.11
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.3
urllib3==1.24.1
Werkzeug==0.15.2
WTForms==2.2.1
```
### Describe the expected results

I simply want to be able to create an app!

### Describe the actual results

I use appbuilder version 1.13.0. I follow the steps in the [docs](https://flask-appbuilder.readthedocs.io/en/latest/installation.html#using-pip), and receive the following error:
```
(flask_appbuilder_venv37) D:\python_proj> flask fab create-app
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "fab".
```
I'm using python 3.7.3 on Windows. WSL too has the same problem with native python 3.5.2.

**Comment by dpgaspar** [comment]
Hey, sorry updated the docs too soon, going to release today, please use:

`fabmanager create-app`

on 1.14.0 (going out today) start using `flask fab <command>`

**Comment by dpgaspar** [comment]
Just made https://flask-appbuilder.readthedocs.io/en/v1.13.0/installation.html
(1.13.0 version)
