### ISSUE TITLE
Filter by Columns is/is not NULL

### ISSUE THREAD

**Issue by ashb** [dpgaspar/Flask-AppBuilder#954]
In Airflow there are a few places where we would like to be able to filter/search by a column being NULL, but this is not currently an option in any of the default filter types.

Is it possible to add this somehow?

**Comment by ashb** [comment]
I've found a way to add a custom filter type (Custom SQLAInterface that sets filter_converter_class) so I have Is Null and Is Not Null appearing in my list - but I can't find any way when digging through the code to work out how to control what type of field is displayed on the RHS of the dyanmic filter. It may not be possible right now?

**Comment by dpgaspar** [comment]
Yes it looks like your on the right track. Make a WiP PR that adds the new Filter and change SQLAFilterConverter accordingly. It does not have to be a final solution, I'll help you from there.

**Comment by ashb** [comment]
I don't have time just now (Airflow bug fix release to get out) so I may not get around to this immediately.

**Comment by dpgaspar** [comment]
No problem, when you have time. 

Going to close this issue, feel free to reopen if you think it makes sense.

Thank you!
