### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [dpgaspar/Flask-AppBuilder#958]
Hello! I'd like to contribute to your project by designing a logo for it. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by dpgaspar** [comment]
Hi @newfinal100,

That's great, a very welcome contribution. You can email me, if you have any initial ideas.

**Comment by dpgaspar** [comment]
ping @newfinal100 are you still up to it?

**Comment by dpgaspar** [comment]
too bad... anyone interested?
