### ISSUE TITLE
Workflow (business process management) using flask and FAB

### ISSUE THREAD

**Issue by Harshitg** [dpgaspar/Flask-AppBuilder#961]
Flask doesn't have any available add-ins to be able to build business process management capabilities
Django has many add-ins available for these capabilities. The reason being, Django is pre-built with user management and permissions, making it possible to build libraries. In our case, we migrated to FAB to get these capabilities.
The examples are viewflow (http://viewflow.io/) , (http://demo.viewflow.io/workflow/shipment/shipment/start/) and activflow (https://github.com/faxad/ActivFlow)

Any ideas if there exist libraries to help implement the process in Flask or is there a plan to implement them in FAB

**Comment by dpgaspar** [comment]
No plans to implement it in a near future. Note that FAB supports addons to attach views/api.
If you want to do it yourself, feel free to open new issues if you need any guidance.
