### ISSUE TITLE
Custom css file is not in effect

### ISSUE THREAD

**Issue by mynameisshiy** [dpgaspar/Flask-AppBuilder#964]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:2.0.0

pip freeze output:
apispec==1.3.0
attrs==19.1.0
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.0.2
Flask-AppBuilder==2.0.0
Flask-Babel==0.12.2
Flask-JWT-Extended==3.18.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.2
prison==0.1.0
PyJWT==1.7.1
pyrsistent==0.15.1
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.3
urllib3==1.24.2
Werkzeug==0.15.2
WTForms==2.2.1
### Describe the expected results

Tell us what should happen.

```python
Modified the theme settings in config
APP_THEME = "yeti2.css"
Then add the yeti2.css file in the /static/appbuilder/css/themes/ directory.
But after starting the service, access the home page, the console prompt file does not exist, the directory structure is as shown
```

### Describe the actual results

Tell us what happens instead.

```pytb
2019-04-26 14:28:28,486:INFO:werkzeug:127.0.0.1 - - [26/Apr/2019 14:28:28] "GET /static/appbuilder/css/themes/yeti2.css HTTP/1.1" 404 -
```
<img width="1018" alt="1" src="https://user-images.githubusercontent.com/8981574/56787832-4eb95b00-6830-11e9-8bba-ce8ff41a190d.png">
<img width="999" alt="2" src="https://user-images.githubusercontent.com/8981574/56787876-74466480-6830-11e9-8aa4-df3ad812dee3.png">

**Comment by CameronNemo** [comment]
Seems like only the ones shipped by FAB itself can be used (e.g. `yeti` or `lumen`).

**Comment by mynameisshiy** [comment]
> Seems like only the ones shipped by FAB itself can be used (e.g. `yeti` or `lumen`).
If I want to change these styles, just go to the css file inside appbuilder? I can see that the description of the framework can be overwritten. Why can't it be effective if you add it to your app's directory?

**Comment by CameronNemo** [comment]
I added an option for this in the PR #1212.
