### ISSUE TITLE
Installation issue for Linux RHEL 6.5

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#97]
For my Mac installation : 

pip install flask-appbuilder

which works fine so that I can launch fabmanager 

But for Linux RHEL 6.5 since working offline I downloaded zip from pypi:

https://pypi.python.org/pypi/Flask-AppBuilder and ftp across

but within RHEL I cannot launch fabmanager as it does not recognise this command?

**Comment by dpgaspar** [comment]
offline servers can be a pain.... to use pip.

It does not work because, you need to install the package first. On the root of the package exec:

    python setup.py install

You should take a look at pip bundle, it can be useful on theses cases

**Comment by scheung38** [comment]
I am using anaconda install, but after source activate env, and cd into it 

Python setup.py install 

-> can't open file setup.py, no such file or directory?

**Comment by dpgaspar** [comment]
unzip Flask-AppBuilder.zip, 'setup.py' is right on the root of it.

**Comment by scheung38** [comment]
Now with Flask-AppBuilder within

/User/seb/PycharmProject/Flask-AppBuilder-master and launching

$fabmanager create-app

->Trying download from https://github.../Flask-AppBuilder-Skeleton/archive/master.zip

but since working offline, then where should I place this Flask-AppBuilder-Skeleton relative to the Flask-AppBuilder? in the same PycharmProject directory as Flask-AppBuilder or in the virtualenv directory?

If downloaded Flask-AppBuilder-Skeleton somewhere in local directory, how to make fabmanager to point to it instead of making https to request Flask-AppBuilder-Skeleton from? Tried

fabmanager create-app ~/PycharmProject/Flask-AppBuilder-Skeleton-master

But Error:

Got unexpected extra argument?

**Comment by dpgaspar** [comment]
Hello again,

Flask-AppBuilder is the package and should be installed or placed on it's own directory.

Your apps should be on their own directory. Do something like this:

\workarea\
    \Flask-AppBuilder\

Place yourself on /workarea/ then:

    fabmanager create-app --name myapp

Next place yourself on the new app:

    fabmanager run

**Comment by scheung38** [comment]
Yes but it is trying to download Skeleton package as indicated by :

Downloaded the skeleton app, good coding! 

But this assumes I have Internet connection, which is the case in my Mac, but not in my RHEL 6.5 environment where I have no internet access to download this Skeleton as indicated by Linux prompt:

Something went wrong <urlopen error [Error -2] Name or service not known>
Trying to download from https...Skeleton/archive/master.zip

**Comment by dpgaspar** [comment]
On the offline server don't use create-app, this command only download the skeleton app for you.

So that error is normal, it's saying it can't resolve github network name.

**Comment by scheung38** [comment]
So how to fabmanager create-app successfully using offline mode?

**Comment by dpgaspar** [comment]
->Trying download from https://github.../Flask-AppBuilder-Skeleton/archive/master.zip

then copy zip to server.

**Comment by scheung38** [comment]
Yes have already done that, but upon launching fabmanager create-app it is still looking, not for the local version (but maybe there is an option to do that), but the github version which it doesnt have webaccess to?

**Comment by dpgaspar** [comment]
If you just copy the skeleton you don't have to use create-app.

I advise you to develop your app, somewhere with internet connection, then deploy to your offline server.

**Comment by dpgaspar** [comment]
Any luck on this?

**Comment by scheung38** [comment]
Well, from Flask-ApBuilder directory:

$ fabmanager create-app

but now after moving to a retricted working area, whether moving the created app one level higher will break anyway

**Comment by dpgaspar** [comment]
don't create your app's inside the Flask-AppBuilder package, create them outside.

If the "restricted area" does not have internet access, create-app will error. create/develop your app outside the "restricted area". Try do it like this:

1 - On your desktop/laptop (with internet)
     - install Flask-AppBuilder (inside virtualenv), use pip install
     - create a workarea directory.
     - on the ./workarea issue the command: fabmanager create-app --name MyApp --engine SQLAlchemy
     - Develop

2 - Copy ./workarea/MyApp to the directory served by your webserver.

**Comment by scheung38** [comment]
Thanks
