### ISSUE TITLE
Curious behavior when attempting to compare old and new versions of an item in pre_update

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#970]
I am attempting to compare the old and new version of a row using the pre_update function on the ModelView. It seems to work for only relational columns, not columns on the Model itself.

### Environment

Flask-Appbuilder version: 2.0.0

pip freeze output:

```
alembic==1.0.9
apispec==1.2.1
attrs==19.1.0
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.0.2
Flask-AppBuilder==2.0.0
Flask-Babel==0.12.2
Flask-JWT-Extended==3.18.1
Flask-Login==0.4.1
Flask-Migrate==2.4.0
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
Mako==1.0.9
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.2
Pillow==6.0.0
prison==0.1.0
PyJWT==1.7.1
pyrsistent==0.14.11
python-dateutil==2.8.0
python-editor==1.0.4
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.3
urllib3==1.24.2
uWSGI==2.0.18
Werkzeug==0.15.2
WTForms==2.2.1
```

### Describe the expected results

During pre_update, the old version of the item should be accessible for comparison.

```python
class Foo(Model):
    id = Column(Integer, primary_key=True)
    bar_id = Column(Integer, ForeignKey('bar.id'))
    bar = relationship('Bar', backref=backref('foo', uselist=False))
    num = Column(Integer)

class Bar(Model):
    id = Column(Integer, primary_key=True)

class FooView(ModelView):
    datamodel = SQLAInterface(Foo)

    def pre_update(self, item):
        print(item.to_json())
        print(self.datamodel.get(item.id).to_json())
        print(self.datamodel.session.query(self.datamodel.obj).all()[0].to_json())
```

### Describe the actual results

Attempts to query for the old item reveal that the table has already been updated with the new values. Result of the pre_update print statements when changing both fields is below:

```
{'id': 1, 'bar_id': 2, 'num': 1}
{'id': 1, 'bar_id': 2, 'num': 1}
{'id': 1, 'bar_id': 1, 'num': 1}
```

Notice how the bar ID is different for the queries, but the num field is the same.

**Comment by CameronNemo** [comment]
Seems as though I need to hook in before populate_obj is called.

**Comment by dpgaspar** [comment]
Yes.

For a different approach (if you don't need to send user feedback), you can use SQLAlchemy events: https://docs.sqlalchemy.org/en/13/orm/session_events.html

**Comment by larahelenaroth** [comment]
Any example on this? I'm not quite sure how to proceed.
