### ISSUE TITLE
APP_NAME = "Name" disappears when changed to APP_THEME = "yeti.css" 

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#98]
Not sure where the APP_NAME disappeared to when changing to some other theme such as yeti.css? But when hovers over it then it appears back?

**Comment by dpgaspar** [comment]
Thats a bootwatch/CSS thing, try:
- a diferent theme
- override CSS
- use APP_ICON

**Comment by dpgaspar** [comment]
you can also try (if you like) on __init__.py:

insert this to imports:

    from flask.ext.appbuilder.menu import Menu

inititalize AppBuilder like this:

    appbuilder = AppBuilder(app, db, menu=Menu(reverse=False))

This will tell the framework not to invert the menu.

**Comment by scheung38** [comment]
Although this works, but this loses the background blue panel altogether in the case of yeti.css theme?
