### ISSUE TITLE
RBAC Github Enterprise OAuth provider callback URL?

### ISSUE THREAD

**Issue by geez** [dpgaspar/Flask-AppBuilder#984]
Hi all,
Quick question, when using RBAC with OAuth providers (1.10.2):
- we are not specifying the `authenticate` or `auth_backend` in the [webserver] section of `airflow.cfg` anymore
- Instead, we set the OAuth provider config in the flask-appbuilder's  `webserver_config.py`:
```
# Adapting Google OAuth example to Github:
OAUTH_PROVIDERS = [
    {'name':'github', 'icon':'fa-github', 'token_key':'access_token',
         'remote_app': {
            'base_url':'https://github.corporate-domain.com/login',
            'access_token_url':'https://github.corporate-domain.com/login/oauth/access_token',
            'authorize_url':'https://github.corporate-domain.com/login/oauth/authorize',
            'request_token_url': None,
            'consumer_key': 'XXXXXXXXXXXX',
            'consumer_secret': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
         }
    }
]
```
_Question:_
- so what callback URL do we specify in the app? `http:/webapp/ghe_oauth/callback` would not work right? (example with github entreprise)

No matter what I specify for the callback url (/ghe_oauth/callback or http://webapp.com), I get an error message about `redirect_uri` mismatch:
```
error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application
```

_Docs ref:_
Here is how you setup OAuth with Github Entreprise on Airflow _**without**_ RBAC: https://airflow.apache.org/security.html#github-enterprise-ghe-authentication

And here is how you setup OAuth via the `webserver_config.py` of flask_appbuilder used by airflow _**with**_ RBAC:
https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth

What's the **callback url** when using RBAC and OAuth with Airflow?

**Comment by geez** [comment]
Airflow issue rather than FAB - https://issues.apache.org/jira/browse/AIRFLOW-4470

**Comment by dpgaspar** [comment]
maybe not, see if you need any help on this, sorry for the delayed answer

**Comment by geez** [comment]
@dpgaspar Hello, thanks for cheking! :)
The Apache Airflow project integrated flask-appbuilder to benefit from the role based access control capabilities. Since the move, the Airflow documentation directs to the FAB documentation regarding OAuth backends.
My question at this stage is about the callback URL specified in the OAuth app at the provider.
In my case, it's the github enterprise Oauth app callback URL that I do not know.
Before the switch to FAB, airflow provided a ghe_oauth backend with a specific callback URL as in http://airflow-app.com/ghe_oauth/callback.

What would be the callback url when using FAB with a GHE backend?

Many thx in advance,
G.

**Comment by dpgaspar** [comment]
Hi @geez,

The exposed callback is ``@expose("/oauth-authorized/<provider>")`` have not retested the OAuth with Github, I know that flask-oauthlib that FAB is using is not maintained anymore, and this should migrate it to flask-dance (for example).

**Comment by dhuckins** [comment]
with older versions, I've been able to get the callback working when I set the callback url to 
`http://localhost:8080/oauth-authorized/github` (running on my machine for example)

however, it seems to want to redirect to ` /oauth-authorized/login`
which is throwing a key error on https://github.com/dpgaspar/Flask-AppBuilder/blob/4b63cbcb4e9872f8aa1628a07348241118410e5c/flask_appbuilder/security/views.py#L677
`KeyError: 'login'`

haven't been able to track why/where it's getting redirected to ` /oauth-authorized/login`

abridged requirements.txt
```text
Flask==1.1.0
Flask-AppBuilder==2.1.5
Flask-Babel==0.12.2
Flask-JWT-Extended==3.20.0
Flask-Login==0.4.1
Flask-OAuthlib==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
# ...
oauthlib==2.1.0
# ....
```

**Comment by jnorton2** [comment]
Were you able to resolve this problem?
