### ISSUE TITLE
minor error in doc

### ISSUE THREAD

**Issue by noxqs** [dpgaspar/Flask-AppBuilder#987]
on page : https://flask-appbuilder.readthedocs.io/en/latest/advanced.html
under custom fields, the first code block, last line:
`return Markup('<b>' + custom + '</b>')`
 should be
`return Markup('<b>' + self.custom + '</b>')`

**Comment by dpgaspar** [comment]
Hi @noxqs ,

Thank you for reporting this. Can you make a PR with it?

**Comment by noxqs** [comment]
Okay, never did that before. Let me find out how to do a pull request, I am following https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by noxqs** [comment]
done (I think) at [#988](https://github.com/dpgaspar/Flask-AppBuilder/pull/988)

**Comment by dpgaspar** [comment]
Thank you, going to close this. Your PR has some extra files, that need to be removed.
