### ISSUE TITLE
New Flask-AppBuilder release

### ISSUE THREAD

**Issue by elukey** [dpgaspar/Flask-AppBuilder#989]
Hi! Don't mean to rush, just wanted to follow up with you if the new release is coming in the next days or not. I am building my own version of Superset starting from the 0.32 branch, and I'd love to include your changes to use FAB 2.0 (only in master I know, I'll cherry pick) plus the pull request that I have submitted last week.

Thanks in advance!

**Comment by dpgaspar** [comment]
Released, your wait is over

**Comment by elukey** [comment]
You rock, it is difficult to find owners of open source code with this attention to the community. Thanks!
