### ISSUE TITLE
Cannot fabmanager create-admin in mongoengine?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#99]
fabmanager create-admin fails with:

Was unable to import app Error: Cannot connect to database default :
[Errno 61] Connection refused

**Comment by dpgaspar** [comment]
Is your mongoDB up?

**Comment by dpgaspar** [comment]
To use MongoEngine you need a MongoDB server running and install python's package flask-mongoengine

**Comment by scheung38** [comment]
Reopening again, yes mongoDB is up, but why even after creating a new Mongodb app:

$brew services start mongodb

$ fabmanager create-app
Your new app name: mymongoengineapp
Your engine type, SQLAlchemy or MongoEngine [SQLAlchemy]:  MongoEngine
Downloaded the skeleton app, good coding!

cd mymongoengineapp/
pip install flask-appbuilder
pip install flask-mongoengine
git clone https://github.com/dpgaspar/Flask-AppBuilder-Skeleton.git
fabmanager run

localhost:8080 ->

mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
