### ISSUE TITLE
Adding a  new menu entry to Security list at a specific position

### ISSUE THREAD

**Issue by cippall** [dpgaspar/Flask-AppBuilder#996]
Hi,

How can one insert a new menu entry into Security list view,  between User Registrations and Base Permissions?

At the moment it get's listed at the bottom:

`
appbuilder.add_view(
                TestView,
                "Test View",
                icon="fa-user-plus",
                label=_("Test View"),
                category="Security",
            )
`

**Comment by dpgaspar** [comment]
You can't without some hacking, One way is to create your own SecurityManager just to override ``register_views``.

**Comment by dpgaspar** [comment]
Going close this one, feel free to reopen or open a new one
