### ISSUE TITLE
Update Installation doc with minimum Python version 3.6

### ISSUE THREAD

**Issue by lemeur** [dpgaspar/Flask-AppBuilder#998]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

Tested with Flask-Appbuilder version 2.1.1.
Minimum Requirement for the new CLI to work is Python 3.6.

This could be updated in the Installation documentation: currently the requirement is only on "Python 3".

**Comment by dpgaspar** [comment]
Thanks, your PR is merged
